# C3 continued: R9 and R10 companion sections
$dir = "C:\PRISM\mcp-server\data\docs\roadmap"

# === R9 ===
$r9 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R9_INTEGRATION.md")
$r9.Add(""); $r9.Add("---"); $r9.Add("")
$r9.Add("## R9 COMPANION ASSETS (v14.5 -- built per-MS, verified at R9 gate)")
$r9.Add(""); $r9.Add("### PER-MS COMPANION SCHEDULE:"); $r9.Add("``````")
$r9.Add("MS0 PRODUCES:")
$r9.Add("  SKILL: prism-machine-connectivity (MTConnect/OPC-UA data interpretation, status codes)")
$r9.Add("  HOOK: machine_connection_health (warning, periodic, checks MTConnect/OPC-UA status)")
$r9.Add("")
$r9.Add("MS1 PRODUCES:")
$r9.Add("  SKILL: prism-cam-integration (CAM plugin usage, parameter injection, troubleshooting)")
$r9.Add("  HOOK: cam_plugin_version_check (warning, startup, verifies CAM plugin compatibility)")
$r9.Add("")
$r9.Add("MS2 PRODUCES:")
$r9.Add("  SKILL: prism-dnc-transfer (G-code transfer protocols, verification, error handling)")
$r9.Add("")
$r9.Add("MS3 PRODUCES:")
$r9.Add("  SKILL: prism-mobile-guide (tablet interface usage, at-machine workflows)")
$r9.Add("")
$r9.Add("MS4 PRODUCES:")
$r9.Add("  SKILL: prism-erp-integration (ERP/MES data mapping, schedule sync, order routing)")
$r9.Add("")
$r9.Add("MS5 PRODUCES:")
$r9.Add("  SCRIPT: integration_smoke_test (tests all connected systems respond)")
$r9.Add("  SCRIPT: measurement_feedback_test (verifies closed-loop measurement data flow)")
$r9.Add("")
$r9.Add("MS6 GATE VERIFIES:")
$r9.Add("  Both hooks fire, all 5 skills load, both scripts pass")
$r9.Add("  End-to-end: query via mobile -> PRISM calculates -> CAM receives params -> DNC transfers")
$r9.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R9_INTEGRATION.md", $r9.ToArray())
Write-Output "C3: R9 done ($($r9.Count) lines)"

# === R10 ===
$r10 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R10_REVOLUTION.md")
$r10.Add(""); $r10.Add("---"); $r10.Add("")
$r10.Add("## R10 COMPANION ASSETS (v14.5 -- built per-revolution, verified at R10 gate)")
$r10.Add(""); $r10.Add("### PER-REVOLUTION COMPANION SCHEDULE:"); $r10.Add("``````")
$r10.Add("REVOLUTION 1 (Manufacturing Genome) PRODUCES:")
$r10.Add("  SKILL: prism-genome-advisor (material DNA queries, genome-based parameter prediction)")
$r10.Add("")
$r10.Add("REVOLUTION 2 (Inverse Problem Solver) PRODUCES:")
$r10.Add("  SKILL: prism-inverse-solver (specify outcome -> get parameters, constraint interpretation)")
$r10.Add("")
$r10.Add("REVOLUTION 3 (Generative Process Planning) PRODUCES:")
$r10.Add("  SKILL: prism-generative-planning (auto-generated process plans, trade-off analysis)")
$r10.Add("")
$r10.Add("REVOLUTION 4 (Federated Learning) PRODUCES:")
$r10.Add("  HOOK: federated_privacy_check (blocking, pre-share, verifies no proprietary data leaks)")
$r10.Add("")
$r10.Add("REVOLUTION 5 (Failure Forensics) PRODUCES:")
$r10.Add("  SKILL: prism-failure-forensics (failure pattern analysis, root cause, prevention)")
$r10.Add("")
$r10.Add("REVOLUTION 6 (Predictive Supply) PRODUCES:")
$r10.Add("  SKILL: prism-supply-intelligence (lead time prediction, substitution, risk assessment)")
$r10.Add("")
$r10.Add("REVOLUTION 7 (Apprentice System) PRODUCES:")
$r10.Add("  SKILL: prism-apprentice-guide (skill gap analysis, training path generation)")
$r10.Add("")
$r10.Add("REVOLUTION 8 (Sustainability) PRODUCES:")
$r10.Add("  HOOK: carbon_budget_check (warning, post-plan, verifies carbon budget compliance)")
$r10.Add("")
$r10.Add("REVOLUTION 9 (Adaptive Control) PRODUCES:")
$r10.Add("  HOOK: digital_twin_sync_check (warning, periodic, verifies twin matches physical state)")
$r10.Add("  SKILL: prism-digital-twin-guide (digital twin interaction and interpretation)")
$r10.Add("")
$r10.Add("REVOLUTION 10 (Knowledge Graph) PRODUCES:")
$r10.Add("  SCRIPT: twin_accuracy_benchmark (compares twin predictions vs actual outcomes)")
$r10.Add("")
$r10.Add("GATE VERIFIES:")
$r10.Add("  All hooks fire, all skills load, benchmark scripts pass")
$r10.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R10_REVOLUTION.md", $r10.ToArray())
Write-Output "C3: R10 done ($($r10.Count) lines)"
