/**
 * HyperMillACScriptExecutor — AC Python Script Execution Engine
 *
 * Executes AC Python scripts generated by HyperMillCodeGeneratorEngine (E1120).
 *
 * Safety sandbox:
 *   Scripts are validated before execution.  The validator rejects scripts that
 *   attempt to access the file system outside the hyperMILL project directory,
 *   import dangerous modules (os, subprocess, sys.exit, etc.), or exceed the
 *   maximum line count.
 *
 * Execution model:
 *   In real mode, the validated script is forwarded to the AC companion HTTP
 *   server (HyperMillACBridgeEngine, port 18365) via /execute.
 *   In mock mode, a synthetic response is returned immediately — suitable for
 *   CI pipelines where hyperMILL is not installed.
 *
 * Agent 18 finding: AC companion server missing — cam:hypermill_ac_execute had
 * no real implementation.  This engine provides the implementation.
 *
 * @engine HyperMillACScriptExecutor
 * @shortcode E1167
 * @dispatcher camDispatcher
 * @actions hypermill_ac_execute (new full implementation)
 * @milestone HM-REV-MS9/U-HMR48
 */

// ─── Types ────────────────────────────────────────────────────────────────────

/** Result of the script sandbox validation step. */
export interface ACScriptValidationResult {
  valid: boolean;
  violations: string[];
  lineCount: number;
  hasImportOs: boolean;
  hasSubprocess: boolean;
  hasFileSystemAccess: boolean;
  hasSysExit: boolean;
}

/** Result of executing an AC Python script. */
export interface ACScriptExecutionResult {
  success: boolean;
  mockMode: boolean;
  scriptHash: string;
  validationResult: ACScriptValidationResult;
  stdout: string;
  stderr: string;
  returnCode: number;
  durationMs: number;
  error?: string;
  /** Structured output parsed from stdout (when available). */
  structuredOutput?: Record<string, unknown>;
}

// ─── Sandbox Configuration ────────────────────────────────────────────────────

export interface ACSandboxConfig {
  /**
   * Maximum number of lines in a validated script.
   * Prevents resource exhaustion from runaway generated scripts.
   */
  maxLines: number;

  /**
   * Forbidden Python import names.
   * Scripts importing any of these will be rejected.
   */
  forbiddenImports: readonly string[];

  /**
   * Forbidden function call patterns (regex strings).
   * Matches against the raw script text.
   */
  forbiddenPatterns: readonly string[];

  /**
   * Allowed project directory prefix for file system access.
   * File paths that don't start with this prefix are blocked.
   * Empty string = no file system access allowed at all.
   */
  allowedProjectPathPrefix: string;
}

export const DEFAULT_SANDBOX_CONFIG: ACSandboxConfig = {
  maxLines: 2000,
  forbiddenImports: [
    "os",
    "subprocess",
    "sys",
    "shutil",
    "pathlib",
    "glob",
    "tempfile",
    "socket",
    "http",
    "urllib",
    "requests",
    "ftplib",
    "smtplib",
    "pickle",
    "shelve",
    "ctypes",
    "cffi",
    "importlib",
    "exec",
    "eval",
    "compile",
    "__import__",
  ],
  forbiddenPatterns: [
    // Exec / eval builtin calls
    String.raw`\bexec\s*\(`,
    String.raw`\beval\s*\(`,
    // sys.exit
    String.raw`sys\.exit`,
    // open() file handles
    String.raw`\bopen\s*\(`,
    // Shell injection via os.system / os.popen
    String.raw`os\.(system|popen|spawn|exec)`,
    // subprocess
    String.raw`subprocess\.(run|Popen|call|check_output)`,
  ],
  allowedProjectPathPrefix: "",
};

// ─── Script Validator ─────────────────────────────────────────────────────────

/**
 * Validate an AC Python script against the sandbox rules.
 *
 * @param script - Raw Python script text.
 * @param config - Sandbox configuration (defaults to DEFAULT_SANDBOX_CONFIG).
 * @returns ACScriptValidationResult with any violations listed.
 */
export function validateACScript(
  script: string,
  config: ACSandboxConfig = DEFAULT_SANDBOX_CONFIG
): ACScriptValidationResult {
  const lines = script.split("\n");
  const violations: string[] = [];

  // Line count check
  if (lines.length > config.maxLines) {
    violations.push(
      `Script exceeds maximum line count: ${lines.length} > ${config.maxLines}`
    );
  }

  // Check forbidden imports
  // Matches: import os, from os import *, import os.path, etc.
  const importOsMatch = config.forbiddenImports.some((mod) => {
    const importPattern = new RegExp(
      `(^|\\n)\\s*import\\s+${mod}(\\s|,|$)|(^|\\n)\\s*from\\s+${mod}(\\s|\\.)`
    );
    return importPattern.test(script);
  });

  const hasImportOs = /(\n|^)\s*import\s+os(\s|,|$)|(\n|^)\s*from\s+os(\s|\.)/.test(
    "\n" + script
  );
  const hasSubprocess = /(\n|^)\s*import\s+subprocess|(\n|^)\s*from\s+subprocess/.test(
    "\n" + script
  );
  const hasSysExit = /sys\.exit/.test(script);
  const hasFileSystemAccess = /\bopen\s*\(/.test(script);

  if (importOsMatch) {
    violations.push(
      "Forbidden import detected: scripts may not import restricted modules. " +
      `Forbidden list: ${config.forbiddenImports.join(", ")}`
    );
  }

  // Check forbidden patterns
  for (const patternStr of config.forbiddenPatterns) {
    const re = new RegExp(patternStr);
    if (re.test(script)) {
      violations.push(`Forbidden pattern detected: ${patternStr}`);
    }
  }

  return {
    valid: violations.length === 0,
    violations,
    lineCount: lines.length,
    hasImportOs,
    hasSubprocess,
    hasFileSystemAccess,
    hasSysExit,
  };
}

// ─── Script Executor ──────────────────────────────────────────────────────────

/**
 * Simple SHA-256-style hash for a script string.
 * Used for logging and deduplication — not for cryptographic security.
 */
function hashScript(script: string): string {
  let hash = 5381;
  for (let i = 0; i < script.length; i++) {
    hash = ((hash << 5) + hash) ^ script.charCodeAt(i);
    hash = hash >>> 0; // Keep as unsigned 32-bit int
  }
  return hash.toString(16).padStart(8, "0");
}

/** Attempt to parse JSON structured output from stdout. */
function tryParseStructuredOutput(
  stdout: string
): Record<string, unknown> | undefined {
  const match = stdout.match(/\{[\s\S]*\}/);
  if (!match) return undefined;
  try {
    return JSON.parse(match[0]) as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

/**
 * HyperMillACScriptExecutor
 *
 * Validates and executes AC Python scripts via the AC companion server.
 *
 * Usage:
 *   const executor = new HyperMillACScriptExecutor({ mockMode: true });
 *   const result = await executor.execute(script);
 *   console.log(result.success); // true (mock)
 */
export class HyperMillACScriptExecutor {
  private readonly _mockMode: boolean;
  private readonly _acHost: string;
  private readonly _acPort: number;
  private readonly _timeoutMs: number;
  private readonly _sandbox: ACSandboxConfig;

  constructor(options: {
    mockMode?: boolean;
    acHost?: string;
    acPort?: number;
    timeoutMs?: number;
    sandbox?: Partial<ACSandboxConfig>;
  } = {}) {
    this._mockMode = options.mockMode ?? false;
    this._acHost = options.acHost ?? "127.0.0.1";
    this._acPort = options.acPort ?? 18365;
    this._timeoutMs = options.timeoutMs ?? 30_000;
    this._sandbox = { ...DEFAULT_SANDBOX_CONFIG, ...options.sandbox };
  }

  /**
   * Execute an AC Python script.
   *
   * Steps:
   *   1. Validate the script against sandbox rules.
   *   2. If validation fails, return failure immediately — never forward.
   *   3. In mock mode: return synthetic success result.
   *   4. In real mode: POST to AC companion /execute endpoint.
   *
   * @param script - Python script text (from HyperMillCodeGeneratorEngine).
   * @param scriptParams - Named parameters to inject into the script context.
   * @returns ACScriptExecutionResult
   */
  async execute(
    script: string,
    scriptParams: Record<string, unknown> = {}
  ): Promise<ACScriptExecutionResult> {
    const t0 = Date.now();
    const scriptHash = hashScript(script);
    const validationResult = validateACScript(script, this._sandbox);

    if (!validationResult.valid) {
      return {
        success: false,
        mockMode: this._mockMode,
        scriptHash,
        validationResult,
        stdout: "",
        stderr: validationResult.violations.join("\n"),
        returnCode: -1,
        durationMs: Date.now() - t0,
        error: `Script validation failed: ${validationResult.violations[0]}`,
      };
    }

    if (this._mockMode) {
      return this._executeMock(script, scriptParams, scriptHash, validationResult, t0);
    }

    return this._executeReal(script, scriptParams, scriptHash, validationResult, t0);
  }

  // ── Mock execution ─────────────────────────────────────────────────────────

  private _executeMock(
    _script: string,
    scriptParams: Record<string, unknown>,
    scriptHash: string,
    validationResult: ACScriptValidationResult,
    t0: number
  ): ACScriptExecutionResult {
    const mockOutput = JSON.stringify({
      status: "ok",
      script_hash: scriptHash,
      params: scriptParams,
      operations_applied: 1,
      nc_generated: false,
      message: "[MOCK] AC script executed successfully",
    });

    return {
      success: true,
      mockMode: true,
      scriptHash,
      validationResult,
      stdout: mockOutput,
      stderr: "",
      returnCode: 0,
      durationMs: Date.now() - t0,
      structuredOutput: JSON.parse(mockOutput) as Record<string, unknown>,
    };
  }

  // ── Real execution ─────────────────────────────────────────────────────────

  private async _executeReal(
    script: string,
    scriptParams: Record<string, unknown>,
    scriptHash: string,
    validationResult: ACScriptValidationResult,
    t0: number
  ): Promise<ACScriptExecutionResult> {
    const url = `http://${this._acHost}:${this._acPort}/execute`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this._timeoutMs);

    try {
      let fetchFn: typeof fetch;
      if (typeof globalThis.fetch === "function") {
        fetchFn = globalThis.fetch.bind(globalThis);
      } else {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const mod = await import("node-fetch" as any);
        fetchFn = (mod.default ?? mod) as unknown as typeof fetch;
      }

      const res = await fetchFn(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-PRISM-Client": "E1167",
        },
        body: JSON.stringify({
          script,
          params: scriptParams,
          script_hash: scriptHash,
        }),
        signal: controller.signal as AbortSignal,
      });

      const durationMs = Date.now() - t0;
      const rawText = await res.text();

      let body: Record<string, unknown> = {};
      try {
        body = JSON.parse(rawText) as Record<string, unknown>;
      } catch { body = { raw_text: rawText }; }

      const success = res.ok && !body.error;
      const stdout = String(body.stdout ?? body.output ?? rawText);
      const stderr = String(body.stderr ?? body.error ?? "");
      const returnCode = Number(body.return_code ?? body.returnCode ?? (success ? 0 : 1));

      return {
        success,
        mockMode: false,
        scriptHash,
        validationResult,
        stdout,
        stderr,
        returnCode,
        durationMs,
        error: success ? undefined : String(body.error ?? `HTTP ${res.status}`),
        structuredOutput: tryParseStructuredOutput(stdout),
      };
    } catch (err: unknown) {
      const isAbort = (err as { name?: string })?.name === "AbortError";
      return {
        success: false,
        mockMode: false,
        scriptHash,
        validationResult,
        stdout: "",
        stderr: String((err as Error)?.message ?? err),
        returnCode: -1,
        durationMs: Date.now() - t0,
        error: isAbort
          ? `AC script execution timed out after ${this._timeoutMs}ms`
          : String((err as Error)?.message ?? err),
      };
    } finally {
      clearTimeout(timer);
    }
  }
}

// ─── Singletons ───────────────────────────────────────────────────────────────

/** Production executor — requires AC companion server running on 127.0.0.1:18365. */
export const hyperMillACScriptExecutor = new HyperMillACScriptExecutor({
  mockMode: false,
});

/** Mock executor — for CI pipelines without hyperMILL installed. */
export const hyperMillACScriptExecutorMock = new HyperMillACScriptExecutor({
  mockMode: true,
});
