/**
 * PrintToGeometryEngine — 2D Blueprint → 3D CadQuery Model Generator
 *
 * Converts extracted blueprint dimensions and features into parametric
 * CadQuery Python scripts that create 3D solid models.
 *
 * Pipeline position: BlueprintOCREngine → PrintToGeometryEngine → FeatureRecognitionEngine
 *
 * Handles prismatic parts (milling), cylindrical parts (turning), and hybrid.
 * Uses feature-driven modeling: base stock → subtract features → add bosses.
 */

interface AtomicValue<T> { value: T; unit?: string; formula?: string; confidence?: number; source?: string; }

export interface BlueprintFeature {
  type: "hole" | "pocket" | "slot" | "boss" | "chamfer" | "fillet" | "thread" | "counterbore" | "countersink" | "keyway" | "groove" | "step" | "face"
    // Complex/industry features (aerospace, medical, mold, automotive)
    | "shell" | "draft" | "rib" | "web" | "loft" | "sweep" | "revolve" | "mirror"
    | "thin_wall_pocket" | "lightening_pocket" | "scallop" | "helix" | "spiral"
    | "o_ring_groove" | "snap_fit" | "dovetail" | "t_slot" | "undercut"
    | "bore_internal" | "taper" | "spherical_radius" | "compound_angle_face"
    | "cooling_channel" | "ejector_pin_hole" | "parting_line_step"
    | "turbine_blade_slot" | "spline_groove" | "oil_passage" | "valve_seat"
    | "bone_screw_thread" | "implant_surface" | "micro_feature";
  dimensions: Record<string, number>; // diameter_mm, depth_mm, width_mm, length_mm, angle_deg, pitch_mm, wall_thickness_mm, draft_angle_deg, helix_pitch_mm, taper_angle_deg, radius_mm
  position?: { x: number; y: number; z?: number };
  count?: number; // for patterns
  pattern?: "linear" | "circular" | "rectangular";
  pattern_spacing?: number;
  tolerance?: string; // e.g. "±0.05"
  notes?: string;
}

export interface BlueprintAnalysis {
  part_name?: string;
  material?: string;
  units: "mm" | "inch";
  overall_dimensions: { length: number; width: number; height: number };
  part_type: "prismatic" | "cylindrical" | "hybrid";
  outer_diameter?: number; // for cylindrical parts
  features: BlueprintFeature[];
  gdt_callouts?: Array<{ symbol: string; value: number; datum?: string; feature_ref?: string }>;
  finish_requirements?: Array<{ surface: string; ra_um: number }>;
  title_block?: Record<string, string>;
}

export interface GeometryResult {
  cadquery_script: string;
  features_modeled: number;
  features_skipped: Array<{ feature: BlueprintFeature; reason: string }>;
  bounding_box: { x: number; y: number; z: number };
  estimated_volume_mm3: number;
  estimated_mass_kg: number; // assumes steel 7.85 g/cm³
  confidence: number;
  warnings: string[];
}

export class PrintToGeometryEngine {
  readonly name = "PrintToGeometryEngine";

  convert(input: BlueprintAnalysis): AtomicValue<GeometryResult> {
    const warnings: string[] = [];
    const skipped: Array<{ feature: BlueprintFeature; reason: string }> = [];
    const lines: string[] = [];
    const dims = input.overall_dimensions;
    const unit_factor = input.units === "inch" ? 25.4 : 1;

    // Convert to mm
    const L = dims.length * unit_factor;
    const W = dims.width * unit_factor;
    const H = dims.height * unit_factor;

    // Header
    lines.push("import cadquery as cq");
    lines.push("");
    lines.push(f_comment(`Part: ${input.part_name ?? "Unnamed"}`));
    lines.push(f_comment(`Material: ${input.material ?? "Unknown"}`));
    lines.push(f_comment(`Generated by PRISM PrintToGeometryEngine`));
    lines.push("");

    if (input.part_type === "cylindrical" && input.outer_diameter) {
      const OD = input.outer_diameter * unit_factor;
      lines.push(`# Base stock: cylinder OD=${OD.toFixed(2)}mm × L=${L.toFixed(2)}mm`);
      lines.push(`result = cq.Workplane("XY").cylinder(${(L).toFixed(2)}, ${(OD / 2).toFixed(2)})`);
    } else {
      lines.push(`# Base stock: ${L.toFixed(2)} × ${W.toFixed(2)} × ${H.toFixed(2)} mm`);
      lines.push(`result = cq.Workplane("XY").box(${L.toFixed(2)}, ${W.toFixed(2)}, ${H.toFixed(2)})`);
    }
    lines.push("");

    let modeled = 0;

    for (const feat of input.features) {
      const d = Object.fromEntries(
        Object.entries(feat.dimensions).map(([k, v]) => [k, v * unit_factor])
      );

      try {
        const featureLines = this.generateFeature(feat, d, input.part_type, L, W, H);
        if (featureLines.length > 0) {
          lines.push(`# Feature: ${feat.type}${feat.count && feat.count > 1 ? ` ×${feat.count}` : ""}`);
          lines.push(...featureLines);
          lines.push("");
          modeled++;
        }
      } catch {
        skipped.push({ feature: feat, reason: `Unsupported feature type or missing dimensions` });
        warnings.push(`Skipped ${feat.type}: insufficient dimensions`);
      }
    }

    // Export
    lines.push("# Export");
    lines.push(`cq.exporters.export(result, "${(input.part_name ?? "part").replace(/[^a-zA-Z0-9]/g, "_")}.step")`);
    lines.push(`print(f"Part generated: {result.val().BoundingBox()}")`);

    const vol = L * W * H; // approximate bounding box volume
    const mass = (vol / 1000) * 7.85 / 1000; // mm³ → cm³ → kg (steel)

    const totalFeatures = input.features.length;
    const confidence = totalFeatures === 0 ? 0.5 : Math.min(0.95, 0.4 + 0.55 * (modeled / totalFeatures));

    return {
      value: {
        cadquery_script: lines.join("\n"),
        features_modeled: modeled,
        features_skipped: skipped,
        bounding_box: { x: L, y: W, z: H },
        estimated_volume_mm3: vol,
        estimated_mass_kg: Math.round(mass * 1000) / 1000,
        confidence,
        warnings,
      },
      confidence,
      source: this.name,
    };
  }

  private generateFeature(
    feat: BlueprintFeature,
    d: Record<string, number>,
    partType: string,
    L: number, W: number, H: number
  ): string[] {
    const lines: string[] = [];
    const pos = feat.position;
    const posStr = pos ? `.center(${pos.x.toFixed(2)}, ${pos.y.toFixed(2)})` : "";

    switch (feat.type) {
      case "hole": {
        const dia = d.diameter_mm ?? d.diameter ?? 10;
        const depth = d.depth_mm ?? d.depth ?? H;
        const through = depth >= H * 0.95;
        const count = feat.count ?? 1;

        if (count > 1 && feat.pattern === "circular" && feat.pattern_spacing) {
          const radius = feat.pattern_spacing;
          lines.push(`result = result.faces(">Z").workplane()`);
          lines.push(`  .polarArray(${radius.toFixed(2)}, 0, 360, ${count})`);
          lines.push(`  .${through ? "cutThruAll" : `hole(${dia.toFixed(2)}, ${depth.toFixed(2)})`}()`);
        } else if (count > 1 && feat.pattern === "linear" && feat.pattern_spacing) {
          lines.push(`result = result.faces(">Z").workplane()${posStr}`);
          lines.push(`  .rarray(${feat.pattern_spacing.toFixed(2)}, 1, ${count}, 1)`);
          lines.push(`  .${through ? "cutThruAll" : `hole(${dia.toFixed(2)}, ${depth.toFixed(2)})`}()`);
        } else {
          lines.push(`result = result.faces(">Z").workplane()${posStr}`);
          lines.push(`  .hole(${dia.toFixed(2)}${through ? "" : `, ${depth.toFixed(2)}`})`);
        }
        break;
      }

      case "pocket": {
        const pL = d.length_mm ?? d.length ?? 20;
        const pW = d.width_mm ?? d.width ?? 15;
        const pD = d.depth_mm ?? d.depth ?? 5;
        const cornerR = d.corner_radius_mm ?? d.corner_radius ?? 3;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .rect(${pL.toFixed(2)}, ${pW.toFixed(2)})`);
        lines.push(`  .cutBlind(-${pD.toFixed(2)})`);
        if (cornerR > 0) {
          lines.push(`  # Corner radius: ${cornerR.toFixed(2)}mm (applied via tool radius)`);
        }
        break;
      }

      case "slot": {
        const sL = d.length_mm ?? d.length ?? 30;
        const sW = d.width_mm ?? d.width ?? 8;
        const sD = d.depth_mm ?? d.depth ?? 5;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .slot2D(${sL.toFixed(2)}, ${sW.toFixed(2)})`);
        lines.push(`  .cutBlind(-${sD.toFixed(2)})`);
        break;
      }

      case "boss": {
        const bD = d.diameter_mm ?? d.diameter ?? 15;
        const bH = d.height_mm ?? d.height ?? 5;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .circle(${(bD / 2).toFixed(2)})`);
        lines.push(`  .extrude(${bH.toFixed(2)})`);
        break;
      }

      case "chamfer": {
        const cSize = d.size_mm ?? d.size ?? d.width_mm ?? 1;
        lines.push(`result = result.edges("|Z").chamfer(${cSize.toFixed(2)})`);
        break;
      }

      case "fillet": {
        const fR = d.radius_mm ?? d.radius ?? 2;
        lines.push(`result = result.edges("|Z").fillet(${fR.toFixed(2)})`);
        break;
      }

      case "counterbore": {
        const cbDia = d.diameter_mm ?? d.diameter ?? 10;
        const cbDepth = d.depth_mm ?? d.depth ?? 5;
        const boreDia = d.bore_diameter_mm ?? d.bore_diameter ?? cbDia * 1.8;
        const boreDepth = d.bore_depth_mm ?? d.bore_depth ?? cbDepth * 0.4;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .cboreHole(${cbDia.toFixed(2)}, ${boreDia.toFixed(2)}, ${boreDepth.toFixed(2)}${d.depth ? `, ${cbDepth.toFixed(2)}` : ""})`);
        break;
      }

      case "countersink": {
        const csDia = d.diameter_mm ?? d.diameter ?? 5;
        const csAngle = d.angle_deg ?? d.angle ?? 82;
        const cskDia = d.countersink_diameter_mm ?? d.countersink_diameter ?? csDia * 2;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .cskHole(${csDia.toFixed(2)}, ${cskDia.toFixed(2)}, ${csAngle.toFixed(0)})`);
        break;
      }

      case "step": {
        const stL = d.length_mm ?? d.length ?? L * 0.5;
        const stW = d.width_mm ?? d.width ?? W;
        const stD = d.depth_mm ?? d.depth ?? H * 0.3;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .rect(${stL.toFixed(2)}, ${stW.toFixed(2)}, centered=False)`);
        lines.push(`  .cutBlind(-${stD.toFixed(2)})`);
        break;
      }

      case "keyway": {
        const kwW = d.width_mm ?? d.width ?? 6;
        const kwD = d.depth_mm ?? d.depth ?? 3;
        const kwL = d.length_mm ?? d.length ?? 20;
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .rect(${kwL.toFixed(2)}, ${kwW.toFixed(2)})`);
        lines.push(`  .cutBlind(-${kwD.toFixed(2)})`);
        break;
      }

      case "groove": {
        const gW = d.width_mm ?? d.width ?? 3;
        const gD = d.depth_mm ?? d.depth ?? 2;
        if (partType === "cylindrical") {
          lines.push(`# Groove: width=${gW.toFixed(2)}mm, depth=${gD.toFixed(2)}mm (turning)`);
          lines.push(`result = result.faces(">Z").workplane()${posStr}`);
          lines.push(`  .rect(${gW.toFixed(2)}, ${(d.diameter_mm ?? 20).toFixed(2)})`);
          lines.push(`  .cutBlind(-${gD.toFixed(2)})`);
        } else {
          lines.push(`result = result.faces(">Z").workplane()${posStr}`);
          lines.push(`  .rect(${gW.toFixed(2)}, ${W.toFixed(2)})`);
          lines.push(`  .cutBlind(-${gD.toFixed(2)})`);
        }
        break;
      }

      case "thread": {
        const tDia = d.diameter_mm ?? d.diameter ?? 10;
        const tPitch = d.pitch_mm ?? d.pitch ?? 1.5;
        const tDepth = d.depth_mm ?? d.depth ?? H;
        lines.push(`# Thread: M${tDia.toFixed(0)}×${tPitch.toFixed(1)}, depth=${tDepth.toFixed(1)}mm`);
        lines.push(`# Note: Thread profile modeled as plain hole (threads are machining features)`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .hole(${(tDia - tPitch).toFixed(2)}, ${tDepth.toFixed(2)})`);
        break;
      }

      case "face":
        lines.push(`# Face: surface finish requirement (no geometry change)`);
        break;

      // ── Complex/Industry Features (aerospace, medical, mold, automotive) ──

      case "shell": {
        const wallT = d.wall_thickness_mm ?? d.thickness ?? 2;
        lines.push(`result = result.shell(-${wallT.toFixed(2)})`);
        break;
      }

      case "draft": {
        const draftAngle = d.draft_angle_deg ?? d.angle ?? 3;
        lines.push(`# Draft angle: ${draftAngle.toFixed(1)}° (mold/casting requirement)`);
        lines.push(`# Applied via CAM strategy (wall taper) — ${draftAngle}° per side`);
        break;
      }

      case "rib": case "web": {
        const rL = d.length_mm ?? d.length ?? 40;
        const rH = d.height_mm ?? d.height ?? 15;
        const rT = d.thickness_mm ?? d.wall_thickness_mm ?? 2;
        lines.push(`# ${feat.type}: ${rL.toFixed(1)}x${rH.toFixed(1)}x${rT.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .rect(${rL.toFixed(2)}, ${rT.toFixed(2)})`);
        lines.push(`  .extrude(${rH.toFixed(2)})`);
        break;
      }

      case "thin_wall_pocket": case "lightening_pocket": {
        const twpL = d.length_mm ?? d.length ?? 40;
        const twpW = d.width_mm ?? d.width ?? 30;
        const twpD = d.depth_mm ?? d.depth ?? 15;
        const wallTp = d.wall_thickness_mm ?? 1.5;
        lines.push(`# ${feat.type}: ${twpL.toFixed(1)}x${twpW.toFixed(1)}x${twpD.toFixed(1)}mm, wall=${wallTp.toFixed(2)}mm`);
        lines.push(`# Aerospace thin-wall: requires HSM with light radial engagement`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}`);
        lines.push(`  .rect(${twpL.toFixed(2)}, ${twpW.toFixed(2)})`);
        lines.push(`  .cutBlind(-${twpD.toFixed(2)})`);
        break;
      }

      case "loft": {
        const botW = d.bottom_width_mm ?? d.width ?? 30;
        const topW = d.top_width_mm ?? botW * 0.6;
        const lH = d.height_mm ?? d.height ?? 20;
        lines.push(`# Loft: bottom ${botW.toFixed(1)}mm -> top ${topW.toFixed(1)}mm, height ${lH.toFixed(1)}mm`);
        lines.push(`result = result.union(cq.Workplane("XY").rect(${botW.toFixed(2)}, ${botW.toFixed(2)}).workplane(offset=${lH.toFixed(2)}).rect(${topW.toFixed(2)}, ${topW.toFixed(2)}).loft())`);
        break;
      }

      case "sweep": {
        const sR = d.radius_mm ?? d.radius ?? 5;
        const pathR = d.path_radius_mm ?? d.path_radius ?? 30;
        lines.push(`# Sweep: profile R=${sR.toFixed(1)}mm along arc R=${pathR.toFixed(1)}mm`);
        lines.push(`path = cq.Workplane("XZ").radiusArc((${pathR.toFixed(2)}, 0), ${pathR.toFixed(2)})`);
        lines.push(`result = result.union(cq.Workplane("XY").circle(${sR.toFixed(2)}).sweep(path))`);
        break;
      }

      case "revolve": {
        const profileH = d.height_mm ?? d.height ?? 20;
        const profileW = d.width_mm ?? d.width ?? 10;
        const revAngle = d.angle_deg ?? d.angle ?? 360;
        lines.push(`# Revolve: ${profileW.toFixed(1)}x${profileH.toFixed(1)}mm, ${revAngle.toFixed(0)} deg`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${profileW.toFixed(2)}, ${profileH.toFixed(2)}).revolve(${revAngle.toFixed(0)}, (0,0,0), (0,1,0))`);
        break;
      }

      case "mirror": {
        lines.push(`result = result.mirror("YZ")`);
        break;
      }

      case "helix": case "spiral": {
        const hPitch = d.pitch_mm ?? d.helix_pitch_mm ?? 5;
        const hR = d.radius_mm ?? d.radius ?? 10;
        const hH = d.height_mm ?? d.height ?? hPitch * 5;
        lines.push(`# ${feat.type}: R=${hR.toFixed(1)}mm, pitch=${hPitch.toFixed(1)}mm`);
        lines.push(`helix_wire = cq.Wire.makeHelix(${hPitch.toFixed(2)}, ${hH.toFixed(2)}, ${hR.toFixed(2)})`);
        lines.push(`result = result.union(cq.Workplane("XY").circle(${(hR * 0.15).toFixed(2)}).sweep(helix_wire))`);
        break;
      }

      case "o_ring_groove": {
        const orID = d.groove_id_mm ?? d.diameter_mm ?? 20;
        const orW = d.width_mm ?? d.width ?? 2.5;
        const orD = d.depth_mm ?? d.depth ?? 1.8;
        lines.push(`# O-ring groove: ID=${orID.toFixed(1)}mm, W=${orW.toFixed(2)}mm, D=${orD.toFixed(2)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.circle(${(orID / 2 + orW / 2).toFixed(2)}).circle(${(orID / 2 - orW / 2).toFixed(2)}).cutBlind(-${orD.toFixed(2)})`);
        break;
      }

      case "dovetail": {
        const dtW = d.width_mm ?? d.width ?? 15;
        const dtD = d.depth_mm ?? d.depth ?? 8;
        lines.push(`# Dovetail: W=${dtW.toFixed(1)}mm, D=${dtD.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${dtW.toFixed(2)}, ${dtD.toFixed(2)}).cutBlind(-${dtD.toFixed(2)})`);
        break;
      }

      case "t_slot": {
        const tsW = d.width_mm ?? d.width ?? 12;
        const tsD = d.depth_mm ?? d.depth ?? 10;
        const tsNeckW = d.neck_width_mm ?? tsW * 0.5;
        lines.push(`# T-slot: W=${tsW.toFixed(1)}mm, neck=${tsNeckW.toFixed(1)}mm, D=${tsD.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${tsNeckW.toFixed(2)}, ${tsD.toFixed(2)}).cutBlind(-${(tsD * 0.6).toFixed(2)})`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${tsW.toFixed(2)}, ${(tsD * 0.4).toFixed(2)}).cutBlind(-${tsD.toFixed(2)})`);
        break;
      }

      case "taper": {
        const tapAngle = d.taper_angle_deg ?? d.angle ?? 5;
        const tapL = d.length_mm ?? d.length ?? 30;
        const tapDStart = d.diameter_start_mm ?? d.diameter_mm ?? 20;
        const tapDEnd = tapDStart - 2 * tapL * Math.tan(tapAngle * Math.PI / 180);
        lines.push(`# Taper: ${tapAngle.toFixed(1)} deg over ${tapL.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.circle(${(tapDStart / 2).toFixed(2)}).workplane(offset=${tapL.toFixed(2)}).circle(${(tapDEnd / 2).toFixed(2)}).loft()`);
        break;
      }

      case "spherical_radius": {
        const sphR = d.radius_mm ?? d.radius ?? 15;
        lines.push(`# Spherical radius: R=${sphR.toFixed(1)}mm`);
        lines.push(`result = result.union(cq.Workplane("XZ")${posStr}.radiusArc((0, ${sphR.toFixed(2)}), ${sphR.toFixed(2)}).close().revolve(360, (0,0,0), (0,1,0)))`);
        break;
      }

      case "compound_angle_face": {
        const caA = d.angle_a_deg ?? d.angle ?? 15;
        const caB = d.angle_b_deg ?? 0;
        const caD = d.depth_mm ?? d.depth ?? 10;
        lines.push(`# Compound angle face: A=${caA.toFixed(1)} B=${caB.toFixed(1)} deg — requires 4/5-axis`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.transformed(rotate=(${caA.toFixed(1)}, ${caB.toFixed(1)}, 0)).rect(${L.toFixed(2)}, ${W.toFixed(2)}).cutBlind(-${caD.toFixed(2)})`);
        break;
      }

      case "bore_internal": {
        const bID = d.diameter_mm ?? d.diameter ?? 25;
        const bDepth = d.depth_mm ?? d.depth ?? 20;
        lines.push(`# Internal bore: ID=${bID.toFixed(2)}mm — requires boring bar`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.hole(${bID.toFixed(2)}, ${bDepth.toFixed(2)})`);
        break;
      }

      case "cooling_channel": case "oil_passage": {
        const ccD = d.diameter_mm ?? d.diameter ?? 6;
        const ccDepth = d.depth_mm ?? d.depth ?? 40;
        const face = feat.type === "oil_passage" ? '">X"' : '">Z"';
        lines.push(`# ${feat.type}: dia=${ccD.toFixed(1)}mm, depth=${ccDepth.toFixed(1)}mm (gun-drill/EDM)`);
        lines.push(`result = result.faces(${face}).workplane()${posStr}.hole(${ccD.toFixed(2)}, ${ccDepth.toFixed(2)})`);
        break;
      }

      case "ejector_pin_hole": {
        const epD = d.diameter_mm ?? d.diameter ?? 6;
        const epDepth = d.depth_mm ?? d.depth ?? 30;
        lines.push(`# Ejector pin hole: dia=${epD.toFixed(2)}mm H7 (mold)`);
        lines.push(`result = result.faces("<Z").workplane()${posStr}.hole(${epD.toFixed(2)}, ${epDepth.toFixed(2)})`);
        break;
      }

      case "parting_line_step": {
        const plD = d.depth_mm ?? d.depth ?? 0.5;
        lines.push(`# Parting line step: depth=${plD.toFixed(2)}mm (mold)`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${L.toFixed(2)}, ${W.toFixed(2)}).cutBlind(-${plD.toFixed(2)})`);
        break;
      }

      case "turbine_blade_slot": case "spline_groove": {
        const tbW = d.width_mm ?? d.width ?? 8;
        const tbD = d.depth_mm ?? d.depth ?? 12;
        lines.push(`# ${feat.type}: W=${tbW.toFixed(1)}mm, D=${tbD.toFixed(1)}mm (broached/EDM)`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${tbW.toFixed(2)}, ${tbD.toFixed(2)}).cutBlind(-${tbD.toFixed(2)})`);
        break;
      }

      case "valve_seat": {
        const vsOD = d.diameter_mm ?? d.diameter ?? 30;
        const vsW = d.width_mm ?? d.width ?? 2;
        lines.push(`# Valve seat: OD=${vsOD.toFixed(1)}mm, width=${vsW.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.circle(${(vsOD / 2).toFixed(2)}).circle(${(vsOD / 2 - vsW).toFixed(2)}).cutBlind(-${vsW.toFixed(2)})`);
        break;
      }

      case "bone_screw_thread": {
        const bstD = d.diameter_mm ?? d.diameter ?? 3.5;
        const bstPitch = d.pitch_mm ?? d.pitch ?? 1.25;
        const bstL = d.length_mm ?? d.length ?? 20;
        lines.push(`# Bone screw: M${bstD.toFixed(1)}xP${bstPitch.toFixed(2)} x${bstL.toFixed(1)}mm — buttress profile`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.hole(${(bstD - bstPitch).toFixed(2)}, ${bstL.toFixed(2)})`);
        break;
      }

      case "implant_surface": case "micro_feature": {
        const mfSize = d.size_mm ?? d.width_mm ?? d.diameter_mm ?? 0.5;
        lines.push(`# ${feat.type}: ${mfSize.toFixed(3)}mm — micro-machining, <1um TIR required`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${mfSize.toFixed(3)}, ${mfSize.toFixed(3)}).cutBlind(-${(mfSize * 0.5).toFixed(3)})`);
        break;
      }

      case "snap_fit": {
        const sfL = d.length_mm ?? d.length ?? 15;
        const sfW = d.width_mm ?? d.width ?? 3;
        const sfH = d.height_mm ?? d.height ?? 2;
        lines.push(`# Snap-fit cantilever: ${sfL.toFixed(1)}x${sfW.toFixed(1)}x${sfH.toFixed(1)}mm`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${sfL.toFixed(2)}, ${sfW.toFixed(2)}).extrude(${sfH.toFixed(2)})`);
        break;
      }

      case "undercut": {
        const ucW = d.width_mm ?? d.width ?? 10;
        const ucD = d.depth_mm ?? d.depth ?? 5;
        lines.push(`# Undercut: W=${ucW.toFixed(1)}mm, D=${ucD.toFixed(1)}mm — lollipop cutter or EDM`);
        lines.push(`result = result.faces(">Z").workplane()${posStr}.rect(${ucW.toFixed(2)}, ${ucD.toFixed(2)}).cutBlind(-${ucD.toFixed(2)})`);
        break;
      }

      case "scallop": {
        const scR = d.radius_mm ?? d.radius ?? 5;
        const scCount = feat.count ?? 6;
        lines.push(`# Scallop pattern: R=${scR.toFixed(1)}mm x${scCount}`);
        lines.push(`result = result.faces(">Z").workplane().polarArray(${(L * 0.3).toFixed(2)}, 0, 360, ${scCount}).circle(${scR.toFixed(2)}).cutThruAll()`);
        break;
      }

      default:
        throw new Error(`Unsupported feature: ${feat.type}`);
    }

    return lines;
  }
}

function f_comment(text: string): string {
  return `# ${text}`;
}

export const printToGeometryEngine = new PrintToGeometryEngine();
