/**
 * CimcoVerificationBridgeEngine — CIMCO Edit 2026 + Machine Simulation ↔ PRISM bridge.
 * =============================================================================
 *
 * SPINE-1 of the CIMCO integration (CIMCO-INTEGRATION-MS0 / U-CIMCO-BRIDGE-ENGINE).
 * The single in-process surface every galaxy calls to query the verified CIMCO
 * inventory and evaluate Machine-Simulation reports. CIMCO is PRISM's fleet
 * program/post **verification + simulation oracle** (wiki
 * [[cimco-verification-simulation-integration]]).
 *
 * Design (no logic duplication):
 *   - The three index JSONs under `state/shared/cimco/` are generated artifacts of
 *     the canonical `.mjs` indexers (`scripts/cimco-machine-index.mjs`,
 *     `cimco-post-index.mjs`, `cimco-tool-index.mjs`). This engine READS that data
 *     (fail-soft) — it does NOT re-parse `.mcfg`/`.js`/`.tmlib` (that stays in the
 *     canonical generators).
 *   - `evaluateSimulationReport()` is a FAITHFUL TypeScript port of
 *     `scripts/cimco-control-map.mjs#parseSimulationReport` (the canonical pass/fail
 *     gate). The `.mjs` remains canonical for the CLI; this port exists so the gate
 *     is callable in-process. A parity test (`CimcoVerificationBridgeEngine.test.ts`)
 *     locks the contract against the same fixtures the `.mjs` test uses. If the
 *     canonical rule changes, BOTH must change — the test will catch drift.
 *
 * UNITS-FIRST: every machine/tool result carries its units-resolution status. 44/86
 * vendor `.mcfg` omit `Header.Unit` → flagged units-UNRESOLVED. Never assume units —
 * a mismatch is a 25.4× scale error (CLAUDE.md §SAFETY RAILS / units-guard).
 *
 * Verification provenance: a CIMCO-sim CLEAN result is "conformance-clean, NOT
 * controller-verified" — it proves kinematics/collision/limits, NOT byte-exact
 * controller behavior (that is the golden round-trip harness's job).
 *
 * Authored 2026-06-02 — slot:echo (post-processor). Wired via `prism_cimco`.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

// ─── Index JSON shapes (generated by the canonical .mjs indexers) ────────────

/** One machine def from machine-index.json (`scripts/cimco-machine-index.mjs`). */
export interface CimcoMachineEntry {
  file: string;
  displayName: string | null;
  orientation: string | null; // "Lathe" | "Horizontal" | "Vertical" | "unknown"
  unit: string | null; // "mm" | "inch" | "unknown" (may be INFERRED — see unitSource)
  unitsResolved: boolean; // true ONLY when Header.Unit was declared; an inferred unit stays false
  // Units provenance (machine-index schema 1.1.0, U-CIMCO-MCFG-UNITS-INFER). SAFETY: never trust
  // `unit` alone — an "inferred-magnitude" unit is a best-guess (only ever "mm"), NOT a declaration.
  // A live-run clearance gate must require unitSource==="declared" OR (inferred AND operator-verified).
  unitSource?: "declared" | "inferred-magnitude" | "unknown";
  unitsInferred?: boolean;
  inferenceConfidence?: "high" | "medium" | null;
  maxLinearRange?: number | null; // max linear-axis travel (the inference magnitude); null if none
  axes?: string[];
  axisCount?: number;
  collisionPairs?: number;
  hasRevolver?: boolean;
  toolchangePositions?: number;
  maxCuttingFeedrate?: number | null;
  warnings?: string[];
}

interface MachineIndex {
  schemaVersion: string;
  machineCount: number;
  byOrientation: Record<string, number>;
  byUnit: Record<string, number>;
  byUnitSource?: Record<string, number>; // {declared, inferred-magnitude, unknown} (schema 1.1.0)
  unresolvedUnits: string[]; // filenames NOT authoritatively declaring Header.Unit (= inferred + unknown)
  unitsInferred?: string[]; // subset of unresolvedUnits whose unit was magnitude-inferred (best-guess mm)
  unitsUnknown?: string[]; // subset with neither a declaration nor a usable magnitude (never use blind)
  machines: CimcoMachineEntry[];
}

/** One readable `.js` post from post-index.json. */
export interface CimcoJsPostEntry {
  file: string;
  parsed: boolean;
  title: string | null;
  summary?: string | null;
  type: string | null; // POST_TYPE_MILL | POST_TYPE_TURN | ...
  author?: string | null;
  version?: string | null;
  diameterProgramming?: boolean;
  xAxisName?: string | null;
  zAxisName?: string | null;
}

/** One compiled `.eRPost` controller def (binary — reference only, not text-authorable). */
export interface CimcoRpostEntry {
  file: string;
  vendor: string;
  name: string;
  binary: boolean;
}

interface PostIndex {
  schemaVersion: string;
  jsPostCount: number;
  jsParsedCount: number;
  rpostCount: number;
  vendorCount: number;
  byType: Record<string, number>;
  vendors: unknown;
  jsPosts: CimcoJsPostEntry[];
  rposts: CimcoRpostEntry[];
}

/** One cutter from a `.tmlib` tool library. */
export interface CimcoToolEntry {
  type: string;
  itemNumber?: number | string | null;
  description?: string | null;
  unitSystem?: string | null; // "Imperial" | "Metric" | null (unresolved)
  fluteDiameter?: number | null;
  shaftDiameter?: number | null;
  bodyLength?: number | null;
  fluteLength?: number | null;
  tipAngle?: number | null;
}

interface ToolLibraryEntry {
  file: string;
  libraryVersion: string | null;
  cutterCount: number;
  byType: Record<string, number>;
  byUnitSystem: Record<string, number>;
  tools: CimcoToolEntry[];
}

interface ToolIndex {
  schemaVersion: string;
  libraryCount: number;
  totalCutters: number;
  byType: Record<string, number>;
  byUnitSystem: Record<string, number>;
  unitsUnresolved: Array<{ file: string; count: number }>;
  libraries: ToolLibraryEntry[];
}

/** One navigable CIMCO surface from nav-map.json (generated by the cimco-blind-nav-plot Workflow). */
export interface CimcoNavSurface {
  id: string;
  label: string;
  area?: string;
  path?: string;
  shortcut?: string | null;
  channel: string; // file | sql | dnc-api | cli | uia (driveability, ranked file>sql/dnc-api>cli>uia)
  action?: string;
  postProvingRelevance?: string | null;
  fields?: string[];
  sourcePage?: string;
}

interface NavMapIndex {
  schemaVersion: string;
  surfaceCount?: number;
  channelDistribution?: Record<string, number>;
  clusters?: Array<{ cluster: string; count: number; gaps?: string[]; postProvingNotes?: string }>;
  criticalPathVerdicts?: Array<{ pathName: string; navigable: boolean; confidence?: string; missingSteps?: string[] }>;
  synthesis?: {
    criticalProcedures?: Array<{ name: string; steps: string[]; channel?: string; blockers?: string[] }>;
    automationChannels?: Array<{ channel: string; surfaceCount?: number; robustness?: string }>;
    blindNavGaps?: string[];
    postProvingReadiness?: string;
    recommendedNextUnits?: string[];
  };
  surfaces: CimcoNavSurface[];
}

/** CIMCO launch surface from launch-surface.json (U-CIMCO-LAUNCH-PROBE — how a blind agent starts/drives the app). */
interface LaunchSurfaceDoc {
  schemaVersion: string;
  installRoot: string;
  executables: Array<{ id: string; exe: string; role: string; sizeBytes?: number; primary?: boolean }>;
  launchPatterns: Array<{ id: string; verified: boolean; needsLiveVerify?: boolean; channel?: string; template: string; purpose?: string; source?: string }>;
  integrationHook?: { id: string; channel?: string; blindSafe?: boolean; where?: string; mechanism?: string; macros?: Record<string, string>; prismUse?: string };
  licenseGate?: { verified?: boolean; note?: string };
}

/** Per-dialect G/M allowlist from dialect-allowlists.json (U-CIMCO-DIALECT-ALLOWLISTS — mined from JM goldens). */
interface DialectAllowlistDoc {
  schemaVersion: string;
  filesScanned?: number;
  families: Record<string, { sampleCount: number; gCodes: string[]; mCodes: string[]; firstSeenG?: Record<string, string>; firstSeenM?: Record<string, string> }>;
}

// ─── Control channels (mirrors scripts/cimco-control-map.mjs CHANNELS, ranked) ──
// Data only — the canonical catalog (action→channel+confidence+evidence) stays in
// the .mjs. This list lets a caller know HOW PRISM drives CIMCO, API/CLI before UI.
export const CIMCO_CONTROL_CHANNELS = [
  { channel: "FILE", rank: 1, note: ".mcfg/.js/.tmlib JSON/XML read (CONFIRMED, no running process)" },
  { channel: "SQL", rank: 2, note: "bundled MariaDB NC-Base/DNC-Max/MDC-Max datastore (schema UNVERIFIED)" },
  { channel: "DNC_API", rank: 3, note: "DNCMaxCtrl.exe / DNC-Max API / TCP drip-feed (UNVERIFIED)" },
  { channel: "CLI", rank: 4, note: "CIMCOEdit.exe <file> open (LIKELY)" },
  { channel: "UIA", rank: 5, note: "fallback for GUI-only Machine-Sim + Simulation-Report read (no screenshots — read element text)" },
] as const;

// ─── Simulation-report contract (FAITHFUL port — canonical: cimco-control-map.mjs) ──
const REPORT_CATEGORIES = new Set(["error", "warning", "collision", "limit"]);

export type SimReportRow = {
  line?: number | string | null;
  type?: string | null;
  description?: string | null;
  action?: string | null;
  category?: string | null;
};
export type SimReportInput =
  | null
  | Array<string | SimReportRow | null>
  | Record<string, unknown>;

export interface SimReportVerdict {
  pass: boolean;
  counts: { error: number; warning: number; collision: number; limit: number };
  firstOffendingLine: number | null;
  errors: Array<{ line: number | null; type: string; description: string; action: string }>;
  warnings: Array<{ line: number | null; type: string; description: string; action: string }>;
  collisions: Array<{ line: number | null; type: string; description: string; action: string }>;
  limits: Array<{ line: number | null; type: string; description: string; action: string }>;
  collisionCheckConfirmed: boolean; // did the collision/limit check demonstrably run? (fail-OPEN guard)
  clearedForLiveRun: boolean; // pass AND the check ran — the ONLY safe "go" signal (NOT bare `pass`)
  summary: string;
  controllerVerified: false; // a sim-clean run is conformance-clean, NOT controller-verified
}

// ─── 3-of-3 live-run clearance gate (U-CIMCO-PROMOTION-3OF3-GATE) ────────────
/** The CIMCO sim machine resolved for a JM machine (subset of CimcoMachineEntry / jm-fleet-sim-map). */
export interface LiveRunClearanceMachine {
  unit?: string | null;
  unitsResolved?: boolean;
  unitSource?: "declared" | "inferred-magnitude" | "unknown" | string;
  unitsInferred?: boolean;
  inferenceConfidence?: "high" | "medium" | null;
  displayName?: string | null;
  file?: string | null;
}
export interface LiveRunClearanceInput {
  machine?: LiveRunClearanceMachine | null;
  /** The Machine-Sim verdict from evaluateSimulationReport (must carry clearedForLiveRun). */
  simVerdict?: Pick<SimReportVerdict, "pass" | "clearedForLiveRun" | "collisionCheckConfirmed" | "summary"> | null;
  /** Operator/automated confirmation the .mcfg kinematics (travels / axis-config / centre-of-rotation) match the REAL machine. */
  kinematicsVerified?: boolean;
  /** The NC program's declared units (G20=inch / G21=mm) — reconciliation note only; JM convention = inch. */
  programUnits?: "inch" | "mm" | null;
  /**
   * U-CIMCO-SIM-4 machine+controller+units BIND verdict (from cimco-bind-gate /
   * the sim driver's verify mode): the LOADED CIMCO machine binds the post's
   * intended machine — right .mcfg + VR-not-NGC controller post + matching units.
   * A clean sim on a WRONG-bound machine is worthless (the same nothing-proved
   * class as wrong kinematics). Absent → bind gate skipped (back-compat); supply
   * it for the full gate.
   */
  bindVerdict?: { bound?: boolean; blocker?: string | null; machineId?: string | null } | null;
  /**
   * U-CIMCO-SIM-5 run-completeness (from cimco-completion-gate): the sim observably
   * finished the WHOLE program — terminal-complete (not a timer) + quiescent report
   * + full line/block coverage + no blocking modal. Absent → relies on
   * simVerdict.clearedForLiveRun; supply it for the explicit §E2/§E4 check.
   */
  runComplete?: { runComplete?: boolean; blockers?: string[] } | boolean | null;
}
export interface LiveRunClearanceCondition {
  ok: boolean;
  detail: string;
}
export interface LiveRunClearanceVerdict {
  cleared: boolean; // the ONLY "approved for live test" signal — fail-safe false
  conditions: {
    machineBound: LiveRunClearanceCondition; // U-CIMCO-SIM-4: right machine/controller/units loaded
    machineUnitsKnown: LiveRunClearanceCondition;
    kinematicsVerified: LiveRunClearanceCondition;
    simClearedForLiveRun: LiveRunClearanceCondition;
    runComplete: LiveRunClearanceCondition; // U-CIMCO-SIM-5: sim observably finished the whole program
  };
  blockers: string[]; // specific, operator-actionable
  summary: string;
}

function _resolveIndexDir(): string | null {
  const candidates = [
    process.env.PRISM_CIMCO_INDEX_DIR,
    resolve(process.cwd(), "state/shared/cimco"),
    resolve(process.cwd(), "../state/shared/cimco"),
    "H:/prism/state/shared/cimco",
  ].filter(Boolean) as string[];
  for (const dir of candidates) {
    if (existsSync(resolve(dir, "machine-index.json"))) return dir;
  }
  // None has machine-index — still return the first existing dir so other indexes resolve.
  for (const dir of candidates) if (existsSync(dir)) return dir;
  return null;
}

export class CimcoVerificationBridgeEngine {
  private _dir: string | null | undefined;
  private _machine: MachineIndex | null | undefined;
  private _post: PostIndex | null | undefined;
  private _tool: ToolIndex | null | undefined;
  private _nav: NavMapIndex | null | undefined;
  private _launch: LaunchSurfaceDoc | null | undefined;
  private _allowlist: DialectAllowlistDoc | null | undefined;

  /** Resolve (and cache) the index directory. */
  private dir(): string | null {
    if (this._dir === undefined) this._dir = _resolveIndexDir();
    return this._dir;
  }

  /** Fail-soft JSON load — missing/corrupt index → null (never throws, never fakes). */
  private load<T>(file: string): T | null {
    const dir = this.dir();
    if (!dir) return null;
    const p = resolve(dir, file);
    if (!existsSync(p)) return null;
    try {
      return JSON.parse(readFileSync(p, "utf8")) as T;
    } catch {
      return null;
    }
  }

  private machineIndex(): MachineIndex | null {
    if (this._machine === undefined) this._machine = this.load<MachineIndex>("machine-index.json");
    return this._machine;
  }
  private postIndex(): PostIndex | null {
    if (this._post === undefined) this._post = this.load<PostIndex>("post-index.json");
    return this._post;
  }
  private toolIndex(): ToolIndex | null {
    if (this._tool === undefined) this._tool = this.load<ToolIndex>("tool-index.json");
    return this._tool;
  }
  private navMapIndex(): NavMapIndex | null {
    if (this._nav === undefined) this._nav = this.load<NavMapIndex>("nav-map.json");
    return this._nav;
  }
  private launchSurfaceDoc(): LaunchSurfaceDoc | null {
    if (this._launch === undefined) this._launch = this.load<LaunchSurfaceDoc>("launch-surface.json");
    return this._launch;
  }
  private dialectAllowlistDoc(): DialectAllowlistDoc | null {
    if (this._allowlist === undefined) this._allowlist = this.load<DialectAllowlistDoc>("dialect-allowlists.json");
    return this._allowlist;
  }

  /** Force a re-read of the index JSONs (after the .mjs indexers regenerate). */
  refresh(): void {
    this._dir = undefined;
    this._machine = undefined;
    this._post = undefined;
    this._tool = undefined;
    this._nav = undefined;
    this._launch = undefined;
    this._allowlist = undefined;
  }

  // ─── Inventory summary (the data-quality headline) ─────────────────────────
  summary() {
    const m = this.machineIndex();
    const p = this.postIndex();
    const t = this.toolIndex();
    const machineUnresolved = m?.unresolvedUnits?.length ?? 0;
    const toolUnresolved = (t?.unitsUnresolved ?? []).reduce((s, u) => s + (u.count ?? 0), 0);
    return {
      indexDir: this.dir(),
      available: { machines: !!m, posts: !!p, tools: !!t },
      machines: m
        ? { count: m.machineCount, byOrientation: m.byOrientation, byUnit: m.byUnit, unitsUnresolved: machineUnresolved }
        : null,
      posts: p
        ? { jsPosts: p.jsPostCount, jsParsed: p.jsParsedCount, controllers: p.rpostCount, vendors: p.vendorCount, byType: p.byType }
        : null,
      tools: t
        ? { libraries: t.libraryCount, cutters: t.totalCutters, byUnitSystem: t.byUnitSystem, unitsUnresolved: toolUnresolved }
        : null,
      // UNITS-FIRST data-quality flag — these must be resolved before any geometry/feed use.
      unitsUnresolvedTotal: machineUnresolved + toolUnresolved,
      provenance: "CIMCO Edit 2026 + Machine Simulation — local verified install (resources/cimco-2026)",
    };
  }

  // ─── Machine query ─────────────────────────────────────────────────────────
  machineQuery(opts: { name?: string; orientation?: string; unitsResolvedOnly?: boolean; limit?: number } = {}) {
    const m = this.machineIndex();
    if (!m) return { available: false, count: 0, machines: [], note: "machine-index.json not found — run scripts/cimco-machine-index.mjs" };
    const nameQ = (opts.name ?? "").trim().toLowerCase();
    const orientQ = (opts.orientation ?? "").trim().toLowerCase();
    let rows = m.machines;
    if (nameQ) rows = rows.filter((r) => (r.displayName ?? r.file ?? "").toLowerCase().includes(nameQ) || (r.file ?? "").toLowerCase().includes(nameQ));
    if (orientQ) rows = rows.filter((r) => (r.orientation ?? "").toLowerCase() === orientQ);
    if (opts.unitsResolvedOnly) rows = rows.filter((r) => r.unitsResolved === true);
    const total = rows.length;
    const limit = opts.limit && opts.limit > 0 ? opts.limit : 100;
    return {
      available: true,
      count: total,
      truncated: total > limit,
      unitsUnresolvedInMatch: rows.filter((r) => !r.unitsResolved).length,
      // Of the unresolved, how many carry a magnitude-inferred best-guess (only ever mm) vs none at all.
      // A live-run gate must NOT treat inferred as declared — surface it so callers can branch honestly.
      unitsInferredInMatch: rows.filter((r) => r.unitsInferred === true).length,
      machines: rows.slice(0, limit),
    };
  }

  // ─── Post / controller query ───────────────────────────────────────────────
  postQuery(opts: { kind?: "js" | "erpost"; type?: string; vendor?: string; name?: string; limit?: number } = {}) {
    const p = this.postIndex();
    if (!p) return { available: false, jsPosts: [], controllers: [], note: "post-index.json not found — run scripts/cimco-post-index.mjs" };
    const nameQ = (opts.name ?? "").trim().toLowerCase();
    const typeQ = (opts.type ?? "").trim().toUpperCase();
    const vendorQ = (opts.vendor ?? "").trim().toLowerCase();
    const limit = opts.limit && opts.limit > 0 ? opts.limit : 100;

    let js: CimcoJsPostEntry[] = [];
    let erpost: CimcoRpostEntry[] = [];
    const wantJs = opts.kind !== "erpost";
    const wantErpost = opts.kind !== "js";

    if (wantJs) {
      js = p.jsPosts;
      if (nameQ) js = js.filter((r) => (r.title ?? r.file ?? "").toLowerCase().includes(nameQ) || (r.file ?? "").toLowerCase().includes(nameQ));
      if (typeQ) js = js.filter((r) => (r.type ?? "").toUpperCase().includes(typeQ));
    }
    if (wantErpost) {
      erpost = p.rposts;
      if (nameQ) erpost = erpost.filter((r) => (r.name ?? "").toLowerCase().includes(nameQ) || (r.file ?? "").toLowerCase().includes(nameQ));
      if (vendorQ) erpost = erpost.filter((r) => (r.vendor ?? "").toLowerCase().includes(vendorQ));
    }
    return {
      available: true,
      jsPostCount: js.length,
      controllerCount: erpost.length,
      // .js are readable/authorable; .eRPost are compiled (reference only, never claimed text-authorable).
      jsPosts: js.slice(0, limit),
      controllers: erpost.slice(0, limit).map((r) => ({ ...r, authorable: false })),
    };
  }

  // ─── Tool query ──────────────────────────────────────────────────────────
  toolQuery(opts: { unitSystem?: string; type?: string; library?: string; limit?: number } = {}) {
    const t = this.toolIndex();
    if (!t) return { available: false, count: 0, tools: [], note: "tool-index.json not found — run scripts/cimco-tool-index.mjs" };
    const unitQ = (opts.unitSystem ?? "").trim().toLowerCase();
    const typeQ = (opts.type ?? "").trim().toLowerCase();
    const libQ = (opts.library ?? "").trim().toLowerCase();
    const limit = opts.limit && opts.limit > 0 ? opts.limit : 100;

    const out: Array<CimcoToolEntry & { library: string }> = [];
    for (const lib of t.libraries) {
      if (libQ && !(lib.file ?? "").toLowerCase().includes(libQ)) continue;
      for (const tool of lib.tools) {
        if (unitQ && (tool.unitSystem ?? "").toLowerCase() !== unitQ) continue;
        if (typeQ && !(tool.type ?? "").toLowerCase().includes(typeQ)) continue;
        out.push({ ...tool, library: lib.file });
      }
    }
    return {
      available: true,
      count: out.length,
      truncated: out.length > limit,
      unitsUnresolvedInMatch: out.filter((r) => !r.unitSystem).length,
      tools: out.slice(0, limit),
    };
  }

  // ─── Control-channel resolution (how PRISM drives CIMCO) ───────────────────
  controlChannels() {
    return {
      channels: CIMCO_CONTROL_CHANNELS,
      doctrine: "API/CLI before UI-automation; UIA only for GUI-only Machine-Sim/Report. No screenshots.",
      canonical: "scripts/cimco-control-map.mjs (COMMAND_CATALOG action→channel+confidence+evidence)",
    };
  }

  // ─── Blind-navigation map (511 surfaces — canonical: scripts/cimco-nav-map.mjs) ──
  // Faithful read of nav-map.json (generated by the cimco-blind-nav-plot Workflow over the 154
  // decompiled CHM pages). The query/filter logic is parity-locked to scripts/cimco-nav-map.mjs#queryNav
  // (the .mjs stays canonical for the CLI; this port makes the map queryable in-process). Fail-soft:
  // a missing nav-map.json → available:false (never throws, never fakes — like the other indexes).

  /** Query the navigable-surface map (every menu/dialog/tab/shortcut keyed by automation channel). */
  navQuery(opts: { channel?: string; area?: string; proofRelevant?: boolean; text?: string; limit?: number } = {}) {
    const nav = this.navMapIndex();
    if (!nav || !Array.isArray(nav.surfaces)) {
      return { available: false, count: 0, surfaces: [], note: "nav-map.json not found — regenerate via the cimco-blind-nav-plot Workflow" };
    }
    let rows = nav.surfaces;
    const channelQ = (opts.channel ?? "").trim().toLowerCase();
    const areaQ = (opts.area ?? "").trim().toLowerCase();
    const textQ = (opts.text ?? "").trim().toLowerCase();
    if (channelQ) rows = rows.filter((s) => String(s.channel ?? "").toLowerCase() === channelQ);
    if (areaQ) rows = rows.filter((s) => String(s.area ?? "").toLowerCase().includes(areaQ));
    if (opts.proofRelevant === true) rows = rows.filter((s) => s.postProvingRelevance != null && s.postProvingRelevance !== "");
    if (textQ) {
      rows = rows.filter((s) =>
        [s.id, s.label, s.action, s.area, s.path].some((f) => String(f ?? "").toLowerCase().includes(textQ)),
      );
    }
    const total = rows.length;
    const limit = opts.limit && opts.limit > 0 ? opts.limit : 100;
    return { available: true, count: total, truncated: total > limit, surfaces: rows.slice(0, limit) };
  }

  /**
   * Blind-nav readiness rollup — the load-bearing "can PRISM drive CIMCO to prove a post?" answer.
   * Critical-path navigability + channel distribution + the honest UIA-verdict-wall gaps + next units.
   */
  navReadiness() {
    const nav = this.navMapIndex();
    if (!nav || !Array.isArray(nav.surfaces)) {
      return { available: false, note: "nav-map.json not found — regenerate via the cimco-blind-nav-plot Workflow" };
    }
    const verdicts = Array.isArray(nav.criticalPathVerdicts) ? nav.criticalPathVerdicts : [];
    const navigable = verdicts.filter((v) => v.navigable === true).length;
    const dist: Record<string, number> = {};
    for (const s of nav.surfaces) dist[String(s.channel ?? "?")] = (dist[String(s.channel ?? "?")] || 0) + 1;
    const synth = nav.synthesis || {};
    return {
      available: true,
      surfaceCount: nav.surfaces.length,
      proofRelevant: nav.surfaces.filter((s) => s.postProvingRelevance != null && s.postProvingRelevance !== "").length,
      channelDistribution: dist,
      criticalPaths: verdicts.map((v) => ({ pathName: v.pathName, navigable: v.navigable, confidence: v.confidence ?? null, missingSteps: v.missingSteps ?? [] })),
      criticalPathsNavigable: `${navigable}/${verdicts.length}`,
      fullyNavigable: verdicts.length > 0 && navigable === verdicts.length,
      criticalProcedures: Array.isArray(synth.criticalProcedures) ? synth.criticalProcedures : [],
      blindNavGaps: Array.isArray(synth.blindNavGaps) ? synth.blindNavGaps : [],
      postProvingReadiness: synth.postProvingReadiness ?? null,
      recommendedNextUnits: Array.isArray(synth.recommendedNextUnits) ? synth.recommendedNextUnits : [],
      note: "Setup+input (file/cli) + ship (FTP) are blind-driveable; the verdict half (Machine-Sim + Simulation-Report) is UIA-only on the live licensed app (SPINE-2).",
    };
  }

  /**
   * CIMCO launch surface — HOW a blind agent starts/drives the local install to prove a post
   * (U-CIMCO-LAUNCH-PROBE). Mirrors scripts/cimco-launch-probe.mjs launchSummary(); parity asserted
   * in the engine test. Fail-soft: missing launch-surface.json → available:false (never fabricates).
   * Honest split: verified launch patterns vs needsLiveVerify; the blind-safe External-Commands hook.
   */
  launchSurface() {
    const ls = this.launchSurfaceDoc();
    if (!ls || !Array.isArray(ls.executables)) {
      return { available: false, note: "launch-surface.json not found — run scripts/cimco-launch-probe.mjs author (U-CIMCO-LAUNCH-PROBE)" };
    }
    const patterns = Array.isArray(ls.launchPatterns) ? ls.launchPatterns : [];
    const verified = patterns.filter((p) => p.verified === true && p.needsLiveVerify !== true);
    const needsLiveVerify = patterns.filter((p) => p.verified !== true || p.needsLiveVerify === true);
    return {
      available: true,
      schemaVersion: ls.schemaVersion,
      installRoot: ls.installRoot,
      executables: ls.executables.map((e) => ({ id: e.id, exe: e.exe, role: e.role, primary: !!e.primary })),
      exeCount: ls.executables.length,
      verifiedLaunchPatterns: verified.map((p) => ({ id: p.id, template: p.template, channel: p.channel ?? null, purpose: p.purpose ?? null })),
      needsLiveVerify: needsLiveVerify.map((p) => ({ id: p.id, template: p.template, purpose: p.purpose ?? null })),
      integrationHook: ls.integrationHook
        ? { id: ls.integrationHook.id, channel: ls.integrationHook.channel ?? null, blindSafe: !!ls.integrationHook.blindSafe, where: ls.integrationHook.where ?? null, macros: ls.integrationHook.macros ?? {}, prismUse: ls.integrationHook.prismUse ?? null }
        : null,
      licenseGated: !!ls.licenseGate,
      note: "open-file (CLI) is the verified blind launch; the External-Commands hook (FILE channel, blindSafe) is how PRISM wires INTO CIMCO without UIA; the Machine-Sim verdict still needs the SPINE-2 UIA report reader + a live license.",
    };
  }

  // ─── Dialect G/M allowlist + lint (faithful ports; canonical = scripts/cimco-dialect-allowlist.mjs + nc-dialect-masks.mjs) ──

  /** Strip NC comments (faithful port of cimco-dialect-allowlist.mjs stripComments). */
  private _stripComments(text: string): string {
    return String(text || "").replace(/\([^)\n]*\)/g, " ").replace(/;[^\n]*/g, " ");
  }

  /** Extract the SET of G/M codes (faithful port of cimco-dialect-allowlist.mjs extractCodes). */
  private _extractCodes(text: string): { g: string[]; m: string[] } {
    const body = this._stripComments(text);
    const g = new Set<string>();
    const m = new Set<string>();
    for (const mt of body.matchAll(/\bG(\d{1,3}(?:\.\d+)?)\b/gi)) g.add("G" + mt[1].replace(/^0+(?=\d)/, ""));
    for (const mt of body.matchAll(/\bM(\d{1,3})\b/gi)) m.add("M" + String(parseInt(mt[1], 10)));
    return { g: [...g], m: [...m] };
  }

  /** Detect dialect family (faithful port of scripts/lib/nc-dialect-masks.mjs detectDialect). */
  private _detectDialect(text: string): string {
    const t = String(text || "").slice(0, 1200);
    if (/===\s*PRISM\s+JM-Die/i.test(t)) return "prism";
    if (/M9\d\s*\(Adaptive Control/i.test(t) || (/^L\d{3}\b/m.test(t) && /^\s*H\d+\s*=/m.test(t))) return "mitsubishi-edm";
    if (/MCX\s*FILE|MCAM\s*FILE|DATE=DD-MM-YY/i.test(t)) return "mastercam";
    if (/^O1001\b/m.test(t)) return "hurco";
    if (/^\$[^\n]*\.MIN%/im.test(t) || /^\s*DEF WORK\b/im.test(t) || /\/CALL OBAR\b/i.test(t)) return "okuma-osp";
    return "unknown";
  }

  /** Per-dialect allowlist summary (the JM-golden code vocabulary the lint checks against). */
  dialectAllowlist() {
    const al = this.dialectAllowlistDoc();
    if (!al || !al.families) {
      return { available: false, note: "dialect-allowlists.json not found — run `node scripts/cimco-dialect-allowlist.mjs build` (U-CIMCO-DIALECT-ALLOWLISTS)" };
    }
    return {
      available: true,
      schemaVersion: al.schemaVersion,
      filesScanned: al.filesScanned ?? null,
      families: Object.fromEntries(
        Object.entries(al.families).map(([fam, v]) => [fam, { sampleCount: v.sampleCount, gCount: v.gCodes.length, mCount: v.mCodes.length }]),
      ),
      note: "Mined from JM's OWN goldens — a whitelist of OBSERVED codes, not a controller spec.",
    };
  }

  /**
   * Lint a candidate post's G/M-code vocabulary against the JM-golden allowlist for its dialect family.
   * Mirrors scripts/cimco-dialect-allowlist.mjs dialectLint — unobserved codes are surfaced for REVIEW,
   * NEVER failed (unobserved≠invalid). Fail-soft on a missing allowlist or unknown family (no false pass).
   */
  dialectLint(ncText: string, familyOverride?: string) {
    const al = this.dialectAllowlistDoc();
    if (!al || !al.families) {
      return { available: false, note: "dialect-allowlists.json not found — run the allowlist builder (U-CIMCO-DIALECT-ALLOWLISTS)" };
    }
    const classified = this._detectDialect(ncText);
    const family = familyOverride || classified;
    const fam = al.families[family];
    const { g, m } = this._extractCodes(ncText);
    const observedG = g.sort();
    const observedM = m.sort();
    if (!fam) {
      return {
        available: true, family, classified, hasAllowlist: false, sampleCount: 0,
        observedG, observedM, unobservedG: [], unobservedM: [], review: false,
        note: `no JM-golden allowlist for dialect '${family}' (classified='${classified}') — cannot lint; verify on the live CIMCO sim. NOT a pass.`,
      };
    }
    const allowG = new Set(fam.gCodes), allowM = new Set(fam.mCodes);
    const unobservedG = observedG.filter((c) => !allowG.has(c));
    const unobservedM = observedM.filter((c) => !allowM.has(c));
    const review = unobservedG.length > 0 || unobservedM.length > 0;
    return {
      available: true, family, classified, hasAllowlist: true, sampleCount: fam.sampleCount,
      observedG, observedM, unobservedG, unobservedM, review,
      note: review
        ? `${unobservedG.length} G + ${unobservedM.length} M code(s) not observed in ${fam.sampleCount} JM '${family}' goldens — REVIEW (unobserved≠invalid; confirm on live sim).`
        : `all emitted codes observed in JM '${family}' goldens (${fam.sampleCount} sampled) — no novel codes.`,
    };
  }

  // ─── Simulation-report pass/fail gate (faithful port; canonical = .mjs) ────
  evaluateSimulationReport(input: SimReportInput): SimReportVerdict {
    const buckets: Record<"error" | "warning" | "collision" | "limit", SimReportVerdict["errors"]> = {
      error: [],
      warning: [],
      collision: [],
      limit: [],
    };

    // Fail-OPEN guard (parity with cimco-control-map.mjs): a null/empty report is AMBIGUOUS — a clean
    // sim, OR the "Check collision and limit errors" pass never executed. A grouped-object caller may
    // assert it ran via `collisionCheckRan:true`.
    const explicitCheckRan =
      input != null && !Array.isArray(input) && typeof input === "object"
        ? (input as Record<string, unknown>).collisionCheckRan === true
        : undefined;

    const classify = (typeStr: unknown, descr?: unknown): "error" | "warning" | "collision" | "limit" => {
      const tt = String(typeStr ?? "").trim().toLowerCase();
      if (!tt) return "error"; // a typeless report row is an unclassified problem — fail-safe to error
      // A gouge is a cutting crash (tool removes material it shouldn't) — fail it as a collision.
      if (tt.includes("collision") || tt.includes("gouge")) return "collision";
      if (tt.includes("limit") || tt.includes("over-travel") || tt.includes("overtravel") || tt.includes("travel")) return "limit";
      // NORMAL stop events (tool change, M00/M01/M30 program/optional stop, program end) are NOT crashes —
      // route to advisory so a stop-event row never FALSE-FAILS a good program. Only EXPLICIT labels match;
      // anything ambiguous stays fail-safe (error). Parity with cimco-control-map.mjs (U-CIMCO-SIM-VERDICT-HARDEN).
      if (
        tt.includes("tool change") || tt.includes("toolchange") ||
        tt.includes("program stop") || tt.includes("optional stop") || tt.includes("program end")
      ) {
        // DEFENSE-IN-DEPTH (parity with .mjs): this downgrade is the ONE branch that removes a fail.
        // Never downgrade a stop-event row whose DESCRIPTION carries a real hazard — scan it first.
        const d = String(descr ?? "").toLowerCase();
        if (d.includes("collision") || d.includes("gouge")) return "collision";
        if (d.includes("over-travel") || d.includes("overtravel") || d.includes("limit") || d.includes("travel")) return "limit";
        return "warning";
      }
      if (tt.includes("warn")) return "warning";
      return "error";
    };

    const pushRow = (row: SimReportRow) => {
      const category =
        row.category && REPORT_CATEGORIES.has(row.category)
          ? (row.category as "error" | "warning" | "collision" | "limit")
          : classify(row.type ?? row.category, row.description);
      const lineNum = row.line != null && Number.isFinite(Number(row.line)) ? Number(row.line) : null;
      buckets[category].push({
        line: lineNum,
        type: String(row.type ?? category),
        description: String(row.description ?? ""),
        action: String(row.action ?? ""),
      });
    };

    if (input == null) {
      // empty report = clean run (sim ran, found nothing)
    } else if (Array.isArray(input)) {
      for (const item of input) {
        if (item == null) continue;
        if (typeof item === "string") {
          const parts = item.split(/\s*\|\s*|\t+|\s{2,}/).map((s) => s.trim()).filter(Boolean);
          if (parts.length === 0) continue;
          const maybeLine = parts[0].replace(/^N/i, "");
          const hasLine = /^\d+$/.test(maybeLine);
          pushRow({
            line: hasLine ? maybeLine : null,
            type: parts[hasLine ? 1 : 0] ?? "",
            description: parts[hasLine ? 2 : 1] ?? "",
            action: parts[hasLine ? 3 : 2] ?? "",
          });
        } else if (typeof item === "object") {
          pushRow(item as SimReportRow);
        }
      }
    } else if (typeof input === "object") {
      for (const cat of ["error", "warning", "collision", "limit"] as const) {
        const rec = input as Record<string, unknown>;
        // `||` (NOT `??`) — byte-faithful to canonical parseSimulationReport. A falsy-but-present
        // singular key (e.g. {collision: 0, collisions:[...]}) MUST fall through to the plural
        // findings array; `??` would keep the `0` and silently drop the array → fail-OPEN.
        const arr = (rec[cat] || rec[`${cat}s`]) as unknown;
        if (Array.isArray(arr)) {
          for (const r of arr) {
            pushRow(typeof r === "object" && r != null ? { ...(r as SimReportRow), category: cat } : { description: String(r), category: cat });
          }
        }
      }
    } else {
      throw new Error("evaluateSimulationReport: expected array, grouped object, or null");
    }

    const counts = {
      error: buckets.error.length,
      warning: buckets.warning.length,
      collision: buckets.collision.length,
      limit: buckets.limit.length,
    };
    const pass = counts.error === 0 && counts.collision === 0 && counts.limit === 0;

    // Findings present = the collision-check pass demonstrably ran. Otherwise require explicit
    // confirmation; an UNCONFIRMED empty report is conformance-pass but NOT cleared for a live run.
    const anyFindings = counts.error + counts.warning + counts.collision + counts.limit > 0;
    const collisionCheckConfirmed = anyFindings || explicitCheckRan === true;
    const clearedForLiveRun = pass && collisionCheckConfirmed;

    const offenders = [...buckets.error, ...buckets.collision, ...buckets.limit]
      .map((r) => r.line)
      .filter((l): l is number => l != null)
      .sort((a, b) => a - b);
    const firstOffendingLine = offenders.length ? offenders[0] : null;

    const summary = !collisionCheckConfirmed
      ? `CIMCO-sim report EMPTY + collision-check-ran UNCONFIRMED — an empty report may mean the check never executed; NOT cleared for live run (pass is conformance-only)`
      : pass
        ? `CIMCO-sim CLEAN (0 collisions, 0 limits, 0 errors, ${counts.warning} warning(s)) — conformance-clean, NOT controller-verified`
        : `CIMCO-sim FAIL: ${counts.collision} collision(s), ${counts.limit} limit(s), ${counts.error} error(s)` +
          (firstOffendingLine != null ? ` (first @ line ${firstOffendingLine})` : "");

    return {
      pass,
      counts,
      firstOffendingLine,
      errors: buckets.error,
      warnings: buckets.warning,
      collisions: buckets.collision,
      limits: buckets.limit,
      collisionCheckConfirmed,
      clearedForLiveRun,
      summary,
      controllerVerified: false,
    };
  }

  /**
   * 3-of-3 live-run clearance gate (the operator-facing "approved for live test?" verdict).
   * A CNC post is cleared ONLY when ALL THREE hold:
   *   (1) machine units are AUTHORITATIVELY known — Header.Unit DECLARED. An inferred-magnitude guess
   *       does NOT clear (operator must confirm / declare): a wrong-units sim is a 25.4× scale error.
   *   (2) kinematics are VERIFIED — the .mcfg travels/axis-config/centre-of-rotation match the real
   *       machine. A clean sim on wrong kinematics proves nothing (esp. 5-axis trunnion).
   *   (3) the sim is CLEAR with the collision-check demonstrably run (simVerdict.clearedForLiveRun).
   * FAIL-SAFE: any unknown/unmet condition → cleared:false + a specific operator-actionable blocker.
   * This NEVER auto-approves — conditions (1)-inferred and (2) are operator-gated BY DESIGN (the live-sim
   * verdict + kinematic fidelity cannot be self-certified headlessly). See wiki [[cimco-verification-simulation-integration]].
   */
  assessLiveRunClearance(input: LiveRunClearanceInput = {}): LiveRunClearanceVerdict {
    const blockers: string[] = [];

    // (0) Machine BOUND — the LOADED CIMCO machine matches the post's intended machine
    // (right .mcfg + VR-not-NGC controller post + matching units), from the U-CIMCO-SIM-4
    // bind gate. A clean sim on a wrong-bound machine proves nothing. Absent → not gated
    // (back-compat); present → bound:true required, else a specific blocker.
    const bv = input.bindVerdict ?? null;
    let bindOk = true;
    let bindDetail: string;
    if (!bv) {
      bindDetail = "machine bind not supplied — units/kinematics gates apply; supply bindVerdict (cimco-bind-gate / sim driver verify) for the full machine-bind gate";
    } else if (bv.bound === true) {
      bindDetail = `machine BOUND (${bv.machineId ?? "?"}) — loaded CIMCO machine + controller post + units match the post`;
    } else {
      bindOk = false;
      bindDetail = `machine NOT bound (${bv.blocker ?? "unknown"}${bv.machineId ? ` for ${bv.machineId}` : ""}) — the loaded CIMCO machine/controller/units do not match the post; a clean sim is meaningless`;
      blockers.push(bindDetail);
    }

    // (1) Machine units AUTHORITATIVELY known (declared) — inferred is a best-guess, not a clearance.
    const m = input.machine ?? null;
    let unitsOk = false;
    let unitsDetail: string;
    if (!m) {
      unitsDetail = "no CIMCO sim machine resolved — cannot assess units";
      blockers.push("no sim machine resolved for this JM machine (run cimco_machine_query / the JM→sim map)");
    } else if (m.unitsResolved === true && (m.unit === "mm" || m.unit === "inch")) {
      unitsOk = true;
      unitsDetail = `machine units DECLARED ${m.unit} (${m.displayName ?? m.file ?? "?"})`;
    } else if (m.unitsInferred === true || m.unitSource === "inferred-magnitude") {
      unitsDetail = `machine units only INFERRED ${m.unit ?? "?"} (${m.inferenceConfidence ?? "?"} confidence) — NOT declared; operator must confirm or add Header.Unit (25.4× scale guard)`;
      blockers.push(unitsDetail);
    } else {
      unitsDetail = "machine units UNKNOWN — cannot run (25.4× scale risk)";
      blockers.push(unitsDetail);
    }
    // Reconciliation note (advisory): a mm machine + inch program is fine IF CIMCO scales via G20/G21.
    if (unitsOk && input.programUnits && m && m.unit && input.programUnits !== m.unit) {
      unitsDetail += `; program is ${input.programUnits} vs machine ${m.unit} — CIMCO must scale via G20/G21 (verify)`;
    }

    // (2) Kinematics VERIFIED against the real machine (operator-gated).
    const kinOk = input.kinematicsVerified === true;
    const kinDetail = kinOk
      ? "kinematics VERIFIED against the real machine"
      : "kinematics NOT verified — confirm the .mcfg travels/axis-config/centre-of-rotation match the real machine (a clean sim on wrong kinematics proves nothing)";
    if (!kinOk) blockers.push(kinDetail);

    // (3) Sim CLEAR with the collision-check demonstrably run.
    const sv = input.simVerdict ?? null;
    let simOk = false;
    let simDetail: string;
    if (!sv) {
      simDetail = "no Machine-Sim verdict provided — run cimco_sim_report_evaluate on a live sim report first";
      blockers.push(simDetail);
    } else if (sv.clearedForLiveRun === true) {
      simOk = true;
      simDetail = "Machine-Sim CLEAR + collision-check confirmed (clearedForLiveRun)";
    } else if (sv.pass === true) {
      simDetail = "Machine-Sim has no findings BUT collision-check-ran UNCONFIRMED — re-run with the collision/limit check executed";
      blockers.push(simDetail);
    } else {
      simDetail = `Machine-Sim FAIL — ${sv.summary ?? "collision/limit/error present"}`;
      blockers.push(simDetail);
    }

    // (4) Run observably COMPLETE — the U-CIMCO-SIM-5 §E2/§E4 gate (terminal-complete +
    // quiescent report + full line/block coverage + no blocking modal). Absent → not gated
    // (the sim-clear gate already requires clearedForLiveRun, into which the driver folds
    // run-completeness); present → runComplete:true required, else a specific blocker.
    const rc = input.runComplete ?? null;
    let runOk = true;
    let runDetail: string;
    if (rc == null) {
      runDetail = "run-completeness not supplied — relying on simVerdict.clearedForLiveRun; supply runComplete (cimco-completion-gate) for the explicit §E2/§E4 check";
    } else {
      const ok = typeof rc === "boolean" ? rc : rc.runComplete === true;
      runOk = ok;
      const why = typeof rc === "boolean" ? "" : (Array.isArray(rc.blockers) && rc.blockers.length ? ` — ${rc.blockers.join("; ")}` : "");
      runDetail = ok
        ? "run observably COMPLETE (terminal-complete + quiescent report + full line/block coverage + no blocking modal)"
        : `run NOT complete${why} — a clean report on an incomplete/early-stopped run is NOT a clearance`;
      if (!ok) blockers.push(runDetail);
    }

    const cleared = bindOk && unitsOk && kinOk && simOk && runOk;
    const summary = cleared
      ? "APPROVED FOR LIVE TEST — all gates pass (machine bound + units declared + kinematics verified + sim clear + run complete). Conformance-verified, NOT controller-verified."
      : `NOT cleared for live run — ${blockers.length} blocker(s): ${blockers.join(" | ")}`;

    return {
      cleared,
      conditions: {
        machineBound: { ok: bindOk, detail: bindDetail },
        machineUnitsKnown: { ok: unitsOk, detail: unitsDetail },
        kinematicsVerified: { ok: kinOk, detail: kinDetail },
        simClearedForLiveRun: { ok: simOk, detail: simDetail },
        runComplete: { ok: runOk, detail: runDetail },
      },
      blockers,
      summary,
    };
  }
}

export const cimcoVerificationBridgeEngine = new CimcoVerificationBridgeEngine();
