/**
 * CADFoundationEncoderEngine — CAD-COMPLETE-MS0/U-CADC-NN01
 *
 * Shared foundation encoder for the CAD closed-loop NN cluster
 * (LP01 outcome bus → LP02 feedback → LP03 replay → LP04 backprop → NN01 encoder).
 *
 * **Role.** Turns heterogeneous CAD inputs — an operation stream, a BRep
 * topology summary, and a sketch summary — into a fixed-dimensional
 * embedding vector that downstream NN heads (per-CAD-system adapters in
 * LP04) all share. Doing this once at the foundation layer is what lets
 * cross-CAD transfer work: a Fusion adapter's gradients can sensibly
 * influence a Mastercam adapter because both see the same embedding shape.
 *
 * **Vocabulary.** Token ids are derived deterministically from
 * `CAD_OPERATION_KINDS` (115 ops, exported by `interfaces/ICADCodeGenerator.ts`).
 * Reserved ids: 0 = PAD, 1 = UNK. Op ids start at 2 and are assigned in the
 * order they appear in the source-of-truth array — so adding a new op kind
 * at the end of `CAD_OPERATION_KINDS` is forward-compatible (existing token
 * ids never shift). The mapping is exposed via {@link getVocabulary} so a
 * checkpoint can pin the vocab snapshot.
 *
 * **Embedding lookup.** Each token id maps to a deterministic OP_EMBED_DIM-d
 * row in an embedding table generated by an LCG hash seeded on
 * `tokenId * VOCAB_SEED_PRIME`. No real-valued training params, no learned
 * weights — this is a stable basis that LP04's per-head linear value
 * function rides on top of. The same input ALWAYS produces the same
 * embedding, in this session and across restarts.
 *
 * **Pooling.** Op-stream → mean-pool the per-token embeddings → L2-normalize.
 * (No attention; the foundation tier is intentionally cheap so the
 * per-head LP04 layer is where the learning happens.)
 *
 * **Output dim.** The unified embedding concatenates:
 *   - OP_EMBED_DIM (8) — mean-pooled op-stream embedding
 *   - BREP_FEATURE_DIM (5) — vertex/edge/face/shell/solid counts, log-normalized
 *   - SKETCH_FEATURE_DIM (4) — entity/constraint/dimension/closed-loop counts
 * Total: UNIFIED_EMBED_DIM (17). LP04's φ is 4-d today; NN01's φ_unified
 * gives downstream heads a richer feature space without changing LP04's
 * wire contract — LP04 just keeps using its own 4-d φ until a follow-up
 * unit promotes it onto φ_unified.
 *
 * **Stats.** {@link getStats} surfaces totalEncodings + totalUnknownTokens
 * + the byKind breakdown (op/brep/sketch). UNK counts are the canary that
 * tells you a CAD generator started emitting ops not yet in the vocab.
 *
 * **Safety.** This engine is pure compute, no I/O, no global mutation
 * outside its singleton counters. It does NOT consume `prism_safety` —
 * encoding a malformed payload is a structured warning, not a thrown error
 * (callers downstream of the NN cluster need batch-tolerant behavior).
 *
 * Refs: BERT-style token embeddings (Devlin et al. 2018); foundation-model
 * pattern (Bommasani et al. 2021); CAD-specific tokenization
 * (DeepCAD/SkexGen 2021–2022).
 */

import {
  CAD_OPERATION_KINDS,
  type CADOperation,
  type CADOperationKind,
} from "../interfaces/ICADCodeGenerator.js";

// ── Constants ────────────────────────────────────────────────────────────────

/** Reserved id for padding (zero rows / empty inputs). */
export const PAD_TOKEN_ID = 0;
/** Reserved id for unknown operation kinds (forward-compatibility). */
export const UNK_TOKEN_ID = 1;
/** First op-derived token id (PAD=0, UNK=1, ops start at 2). */
const FIRST_OP_TOKEN_ID = 2;

/** Per-token embedding dimensionality. */
export const OP_EMBED_DIM = 8;
/** BRep summary feature dimensionality. */
export const BREP_FEATURE_DIM = 5;
/** Sketch summary feature dimensionality. */
export const SKETCH_FEATURE_DIM = 4;
/** Unified embedding dim = OP_EMBED_DIM + BREP_FEATURE_DIM + SKETCH_FEATURE_DIM. */
export const UNIFIED_EMBED_DIM = OP_EMBED_DIM + BREP_FEATURE_DIM + SKETCH_FEATURE_DIM;

/** LCG seed prime used to derive token embedding rows (DJB2-style mix). */
const VOCAB_SEED_PRIME = 2_654_435_761; // Knuth multiplicative hash constant
/** LCG modulus (2^31). */
const LCG_M = 0x7fff_ffff;
/** LCG multiplier. */
const LCG_A = 1_103_515_245;
/** LCG increment. */
const LCG_C = 12_345;

// ── Types ────────────────────────────────────────────────────────────────────

/** BRep topology counts. Caller supplies any subset; missing → 0. */
export interface BRepSummary {
  vertexCount?: number;
  edgeCount?: number;
  faceCount?: number;
  shellCount?: number;
  solidCount?: number;
}

/** Sketch entity counts. Caller supplies any subset; missing → 0. */
export interface SketchSummary {
  entityCount?: number;
  constraintCount?: number;
  dimensionCount?: number;
  closedLoopCount?: number;
}

/** Operation-stream encode result. */
export interface OperationStreamEncoding {
  /** Token id sequence (PAD=0, UNK=1, ops≥2). Same length as input ops. */
  tokens: number[];
  /** Mean-pooled, L2-normalized embedding (length OP_EMBED_DIM). */
  embedding: number[];
  /** Op kinds that fell through to UNK (forward-compat canary). */
  unknownTokens: string[];
}

/** Unified encoding of an op stream + BRep + sketch payload. */
export interface UnifiedCADEmbedding {
  /** Concatenated embedding (length UNIFIED_EMBED_DIM). */
  embedding: number[];
  /** Op-stream component (length OP_EMBED_DIM). */
  opEmbedding: number[];
  /** BRep component (length BREP_FEATURE_DIM). */
  brepFeatures: number[];
  /** Sketch component (length SKETCH_FEATURE_DIM). */
  sketchFeatures: number[];
  /** Token ids of op stream (empty if no ops supplied). */
  tokens: number[];
  /** UNK op kinds (forward-compat canary). */
  unknownTokens: string[];
}

/** Aggregate counters for telemetry / dispatcher inspection. */
export interface EncoderStats {
  totalOpStreamEncodings: number;
  totalBRepEncodings: number;
  totalSketchEncodings: number;
  totalUnifiedEncodings: number;
  totalUnknownTokens: number;
  vocabSize: number;
}

// ── Vocabulary (computed once at module load) ────────────────────────────────

/** kind → token id (FIRST_OP_TOKEN_ID..) */
const KIND_TO_TOKEN: Map<string, number> = (() => {
  const m = new Map<string, number>();
  CAD_OPERATION_KINDS.forEach((kind, i) => m.set(kind, FIRST_OP_TOKEN_ID + i));
  return m;
})();
/** Total vocab size including reserved tokens (PAD+UNK+ops). */
const VOCAB_SIZE = FIRST_OP_TOKEN_ID + CAD_OPERATION_KINDS.length;

// ── Pure helpers ─────────────────────────────────────────────────────────────

/** Deterministic LCG hash → real in [-1, 1]. */
function seededValue(seed: number, dim: number): number {
  let state = (seed + dim * VOCAB_SEED_PRIME) & LCG_M;
  state = (LCG_A * state + LCG_C) & LCG_M;
  return (state / LCG_M) * 2 - 1;
}

/** Generate a deterministic embedding row for one token. */
function embeddingRow(tokenId: number): number[] {
  if (tokenId === PAD_TOKEN_ID) return new Array(OP_EMBED_DIM).fill(0);
  const seed = tokenId * VOCAB_SEED_PRIME;
  const row = new Array<number>(OP_EMBED_DIM);
  for (let d = 0; d < OP_EMBED_DIM; d++) row[d] = seededValue(seed, d);
  return row;
}

/** L2-normalize a vector (zero-vec preserved). */
function l2Normalize(v: number[]): number[] {
  let s = 0;
  for (const x of v) s += x * x;
  if (s <= 0) return v.slice();
  const inv = 1 / Math.sqrt(s);
  return v.map(x => x * inv);
}

/** Log-normalize a count: log1p(max(0,n)) / log1p(1024). Caps at ~1 for n≤1024. */
function logNormalizeCount(n: number | undefined): number {
  if (typeof n !== "number" || !Number.isFinite(n) || n <= 0) return 0;
  return Math.log1p(n) / Math.log1p(1024);
}

// ── Engine ───────────────────────────────────────────────────────────────────

export class CADFoundationEncoderEngine {
  private totalOpStream = 0;
  private totalBRep = 0;
  private totalSketch = 0;
  private totalUnified = 0;
  private totalUnknown = 0;

  /** Look up a token id for an op kind. UNK_TOKEN_ID if not in vocab. */
  tokenOf(kind: string): number {
    return KIND_TO_TOKEN.get(kind) ?? UNK_TOKEN_ID;
  }

  /** Returns a shallow copy of the kind→tokenId mapping (sorted by tokenId). */
  getVocabulary(): Array<{ tokenId: number; kind: string }> {
    return CAD_OPERATION_KINDS.map((kind, i) => ({ tokenId: FIRST_OP_TOKEN_ID + i, kind }));
  }

  /** Encode an op stream into a mean-pooled, L2-normalized embedding. */
  encodeOperationStream(ops: ReadonlyArray<CADOperation>): OperationStreamEncoding {
    if (!Array.isArray(ops)) {
      throw new TypeError("encodeOperationStream: ops must be an array");
    }
    this.totalOpStream++;
    if (ops.length === 0) {
      return { tokens: [], embedding: new Array(OP_EMBED_DIM).fill(0), unknownTokens: [] };
    }
    const tokens: number[] = [];
    const unknown: string[] = [];
    const sum = new Array<number>(OP_EMBED_DIM).fill(0);
    for (const op of ops) {
      const kind = typeof op?.kind === "string" ? (op.kind as CADOperationKind) : "custom";
      const tokenId = KIND_TO_TOKEN.get(kind) ?? UNK_TOKEN_ID;
      tokens.push(tokenId);
      if (tokenId === UNK_TOKEN_ID && kind !== "custom") {
        unknown.push(kind);
        this.totalUnknown++;
      }
      const row = embeddingRow(tokenId);
      for (let d = 0; d < OP_EMBED_DIM; d++) sum[d] += row[d];
    }
    const inv = 1 / ops.length;
    for (let d = 0; d < OP_EMBED_DIM; d++) sum[d] *= inv;
    return { tokens, embedding: l2Normalize(sum), unknownTokens: unknown };
  }

  /** Encode a BRep topology summary into a fixed-size feature vector. */
  encodeBRepSummary(brep: BRepSummary | undefined): number[] {
    this.totalBRep++;
    const b = brep ?? {};
    return [
      logNormalizeCount(b.vertexCount),
      logNormalizeCount(b.edgeCount),
      logNormalizeCount(b.faceCount),
      logNormalizeCount(b.shellCount),
      logNormalizeCount(b.solidCount),
    ];
  }

  /** Encode a sketch summary into a fixed-size feature vector. */
  encodeSketchSummary(sketch: SketchSummary | undefined): number[] {
    this.totalSketch++;
    const s = sketch ?? {};
    return [
      logNormalizeCount(s.entityCount),
      logNormalizeCount(s.constraintCount),
      logNormalizeCount(s.dimensionCount),
      logNormalizeCount(s.closedLoopCount),
    ];
  }

  /** Unified encoding combining op stream + BRep + sketch. */
  encodeFull(input: {
    ops?: ReadonlyArray<CADOperation>;
    brep?: BRepSummary;
    sketch?: SketchSummary;
  }): UnifiedCADEmbedding {
    this.totalUnified++;
    const opResult = this.encodeOperationStream(input.ops ?? []);
    const brep = this.encodeBRepSummary(input.brep);
    const sketch = this.encodeSketchSummary(input.sketch);
    const embedding = [...opResult.embedding, ...brep, ...sketch];
    return {
      embedding,
      opEmbedding: opResult.embedding,
      brepFeatures: brep,
      sketchFeatures: sketch,
      tokens: opResult.tokens,
      unknownTokens: opResult.unknownTokens,
    };
  }

  /** Aggregate counters. */
  getStats(): EncoderStats {
    return {
      totalOpStreamEncodings: this.totalOpStream,
      totalBRepEncodings: this.totalBRep,
      totalSketchEncodings: this.totalSketch,
      totalUnifiedEncodings: this.totalUnified,
      totalUnknownTokens: this.totalUnknown,
      vocabSize: VOCAB_SIZE,
    };
  }

  /** Test-only reset of counters. */
  _resetForTests(): void {
    this.totalOpStream = 0;
    this.totalBRep = 0;
    this.totalSketch = 0;
    this.totalUnified = 0;
    this.totalUnknown = 0;
  }
}

export const cadFoundationEncoderEngine = new CADFoundationEncoderEngine();
