/**
 * Fusion360CodeGeneratorEngine — U-CADC13 (CAD-COMPLETE-MS0)
 *
 * Fusion 360 Python code generator extending UnifiedCADCodeGeneratorBase.
 * Emits Python code targeting Autodesk Fusion 360's Python API (adsk.*).
 *
 * Design:
 *   - Full ICADCodeGenerator contract with fusion360 CADSystemId
 *   - Emits Python using adsk.core, adsk.fusion, adsk.cam modules
 *   - Geometry via adsk.fusion.Sketch (SketchLines, SketchCircles, etc.)
 *   - Operations via adsk.fusion.Features (ExtrudeFeature, RevolveFeature, etc.)
 *   - Injectable execution path (Fusion 360 add-in HTTP bridge or mock for CI)
 *
 * Unit conversion:
 *   Fusion 360 internal units are cm. When user specifies mm, we multiply by 0.1.
 *   When user specifies inches, we multiply by 2.54.
 *
 * Fusion 360 API references:
 *   - Autodesk Fusion 360 API Reference (https://help.autodesk.com/view/fusion360/ENU/)
 *   - adsk.core, adsk.fusion, adsk.cam Python modules
 *
 * @module engines/Fusion360CodeGeneratorEngine
 * @milestone CAD-COMPLETE-MS0
 */

import {
  UnifiedCADCodeGeneratorBase,
  type CADEmitter,
} from "./UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADOperation,
  CADOperationKind,
  CADExecutionResult,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";
import { log } from "../utils/Logger.js";
import type { ExtractedAction } from "./VideoActionExtractorEngine.js";

// Re-export the typed-CADOperation Adapter so callers can import either surface
// (legacy ExtractedAction Engine vs. typed CADOperation Adapter) from one path.
export {
  Fusion360CADGeneratorAdapter,
  fusion360CADGeneratorAdapter,
  type Fusion360AdapterContext,
} from "./Fusion360CADGeneratorAdapter.js";

// ── Fusion 360-specific types ────────────────────────────────────────────────

export interface Fusion360GenerationContext {
  projectName: string;
  units: "mm" | "in" | "cm";
  outputDir?: string;
  targetVersion?: "2023" | "2024" | "2025";
  componentName?: string;
}

/**
 * Legacy script result shape consumed by:
 *   - cadDispatcher.ts f360_* MCP actions
 *   - VideoActionExtractor → Fusion 360 replay pipeline
 *   - Test contract in fusion360-code-generator.test.ts
 */
export interface Fusion360Script {
  script: string;
  operations: string[];
  parameter_count: number;
  script_name: string;
  estimated_complexity: "simple" | "moderate" | "complex";
}

// ── Supported operations ─────────────────────────────────────────────────────

const FUSION360_SUPPORTED_OPS: ReadonlyArray<CADOperationKind> = [
  // Sketch
  "sketch_create", "sketch_close", "sketch_line", "sketch_arc", "sketch_circle",
  "sketch_rectangle", "sketch_polygon", "sketch_spline", "sketch_ellipse",
  "sketch_slot", "sketch_point", "sketch_constraint", "sketch_dimension",
  // Feature (solid)
  "feature_extrude", "feature_revolve", "feature_loft", "feature_sweep",
  "feature_hole", "feature_pocket", "feature_fillet", "feature_chamfer",
  "feature_shell", "feature_draft", "feature_rib", "feature_thread",
  // Surface
  "surface_ruled", "surface_loft", "surface_sweep", "surface_fill",
  "surface_offset", "surface_trim",
  // Boolean
  "boolean_union", "boolean_intersect", "boolean_subtract",
  // Transform / Pattern
  "transform_move", "transform_rotate", "transform_mirror",
  "transform_pattern_linear", "transform_pattern_circular", "transform_scale",
  // Pattern aliases
  "pattern_linear", "pattern_circular", "pattern_mirror",
  // Datum geometry
  "datum_plane", "datum_axis", "datum_point",
  // Export / Import
  "export_step", "export_stl", "export_dxf", "export_iges", "export_f3d",
  "import_step", "import_iges", "import_dxf", "import_stl",
  // Parameter
  "parameter_declare", "parameter_equation",
  // Custom
  "custom",
];

// ── Main engine class ────────────────────────────────────────────────────────

export class Fusion360CodeGeneratorEngine extends UnifiedCADCodeGeneratorBase<Fusion360GenerationContext> {
  readonly cadSystem: CADSystemId = "fusion360";

  readonly capabilities: CADCapabilityMatrix = {
    cadSystem: "fusion360",
    supportedOps: new Set(FUSION360_SUPPORTED_OPS),
    // adsk.fusion API is natively cm/rad (mirrors the canonical Fusion360CADGeneratorAdapter
    // for the same host); callers convert upstream per CADCapabilityMatrix contract.
    nativeLengthUnit: "cm",
    nativeAngleUnit: "rad",
    requiresSubprocess: true,
    typicalLatencyMs: 1500,
    version: "2024",
    notes: "Autodesk Fusion 360 Python API (adsk.core, adsk.fusion)",
    maxComplexity: 10000,
    supportsUndo: true,
    supportsParametric: true,
  };

  private entityCounter = 0;

  protected preamble(ctx: Fusion360GenerationContext | undefined, emitter: CADEmitter): void {
    this.entityCounter = 0;
    const projectName = ctx?.projectName ?? "PRISM_Generated";
    const units = ctx?.units ?? "mm";
    const targetVersion = ctx?.targetVersion ?? "2024";

    emitter.line("# AUTO-GENERATED by PRISM Fusion360CodeGeneratorEngine");
    emitter.line(`# Project: ${projectName}`);
    emitter.line(`# Units: ${units}`);
    emitter.line(`# Target: Fusion 360 ${targetVersion}`);
    emitter.line();

    emitter.require("import adsk.core");
    emitter.require("import adsk.fusion");
    emitter.require("import adsk.cam");
    emitter.require("import traceback");
    emitter.require("import math");
    emitter.line();

    const unitFactor = this.getUnitFactor(units);
    emitter.parameter("UNIT_FACTOR", unitFactor, units, "Conversion to cm (Fusion internal)");
    emitter.line(`UNIT_FACTOR = ${unitFactor}  # ${units} → cm`);
    emitter.line();

    emitter.line("def run(context):");
    emitter.indent = "    ";
    emitter.line("ui = None");
    emitter.line("try:");
    emitter.indent = "        ";
    emitter.line("app = adsk.core.Application.get()");
    emitter.line("ui = app.userInterface");
    emitter.line("design = adsk.fusion.Design.cast(app.activeProduct)");
    emitter.line("if not design:");
    emitter.line("    ui.messageBox('No active Fusion design')");
    emitter.line("    return");
    emitter.line(`rootComp = design.rootComponent`);
    emitter.line("results = []");
    emitter.line();
  }

  protected epilogue(ctx: Fusion360GenerationContext | undefined, emitter: CADEmitter): void {
    emitter.line();
    emitter.line("# Return results");
    emitter.line("return results");
    emitter.indent = "    ";
    emitter.line("except:");
    emitter.indent = "        ";
    emitter.line("if ui:");
    emitter.line("    ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))");
    emitter.indent = "";
  }

  protected scriptFilename(ctx: Fusion360GenerationContext | undefined): string {
    const base = (ctx?.projectName ?? "fusion_script").replace(/[^a-zA-Z0-9_]/g, "_");
    return `${base}.py`;
  }

  protected emitOp(
    op: CADOperation,
    idx: number,
    ctx: Fusion360GenerationContext | undefined,
    emitter: CADEmitter,
  ): void {
    const args = op.args ?? {};
    const kind = op.kind;

    switch (kind) {
      // ── Sketch operations ────────────────────────────────────────
      case "sketch_create":
        this.emitSketchCreate(args, emitter, ctx);
        break;
      case "sketch_close":
        emitter.line("# Sketch close - finalize sketch constraints");
        break;
      case "sketch_line":
        this.emitSketchLine(args, emitter);
        break;
      case "sketch_arc":
        this.emitSketchArc(args, emitter);
        break;
      case "sketch_circle":
        this.emitSketchCircle(args, emitter);
        break;
      case "sketch_rectangle":
        this.emitSketchRectangle(args, emitter);
        break;
      case "sketch_polygon":
        this.emitSketchPolygon(args, emitter);
        break;
      case "sketch_spline":
        this.emitSketchSpline(args, emitter);
        break;
      case "sketch_ellipse":
        this.emitSketchEllipse(args, emitter);
        break;
      case "sketch_slot":
        this.emitSketchSlot(args, emitter);
        break;
      case "sketch_point":
        this.emitSketchPoint(args, emitter);
        break;
      case "sketch_constraint":
        this.emitSketchConstraint(args, emitter);
        break;
      case "sketch_dimension":
        this.emitSketchDimension(args, emitter);
        break;

      // ── Feature operations ───────────────────────────────────────
      case "feature_extrude":
        this.emitFeatureExtrude(args, emitter);
        break;
      case "feature_revolve":
        this.emitFeatureRevolve(args, emitter);
        break;
      case "feature_loft":
        this.emitFeatureLoft(args, emitter);
        break;
      case "feature_sweep":
        this.emitFeatureSweep(args, emitter);
        break;
      case "feature_hole":
        this.emitFeatureHole(args, emitter);
        break;
      case "feature_pocket":
        this.emitFeaturePocket(args, emitter);
        break;
      case "feature_fillet":
        this.emitFeatureFillet(args, emitter);
        break;
      case "feature_chamfer":
        this.emitFeatureChamfer(args, emitter);
        break;
      case "feature_shell":
        this.emitFeatureShell(args, emitter);
        break;
      case "feature_draft":
        this.emitFeatureDraft(args, emitter);
        break;
      case "feature_rib":
        this.emitFeatureRib(args, emitter);
        break;
      case "feature_thread":
        this.emitFeatureThread(args, emitter);
        break;

      // ── Surface operations ───────────────────────────────────────
      case "surface_ruled":
      case "surface_loft":
        this.emitSurfaceLoft(args, emitter);
        break;
      case "surface_sweep":
        this.emitSurfaceSweep(args, emitter);
        break;
      case "surface_fill":
        this.emitSurfaceFill(args, emitter);
        break;
      case "surface_offset":
        this.emitSurfaceOffset(args, emitter);
        break;
      case "surface_trim":
        this.emitSurfaceTrim(args, emitter);
        break;

      // ── Boolean operations ───────────────────────────────────────
      case "boolean_union":
        emitter.line("# Boolean union - Combine bodies");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;
      case "boolean_intersect":
        emitter.line("# Boolean intersect - Common volume");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.IntersectFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;
      case "boolean_subtract":
        emitter.line("# Boolean subtract - Cut bodies");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.CutFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;

      // ── Transform / Pattern operations ───────────────────────────
      case "transform_move":
        this.emitTransformMove(args, emitter);
        break;
      case "transform_rotate":
        this.emitTransformRotate(args, emitter);
        break;
      case "transform_mirror":
      case "pattern_mirror":
        this.emitTransformMirror(args, emitter);
        break;
      case "transform_pattern_linear":
      case "pattern_linear":
        this.emitPatternLinear(args, emitter);
        break;
      case "transform_pattern_circular":
      case "pattern_circular":
        this.emitPatternCircular(args, emitter);
        break;
      case "transform_scale":
        this.emitTransformScale(args, emitter);
        break;

      // ── Datum geometry ───────────────────────────────────────────
      case "datum_plane":
        this.emitDatumPlane(args, emitter);
        break;
      case "datum_axis":
        this.emitDatumAxis(args, emitter);
        break;
      case "datum_point":
        this.emitDatumPoint(args, emitter);
        break;

      // ── Export / Import ──────────────────────────────────────────
      case "export_step":
        this.emitExport(args, emitter, "STEP");
        break;
      case "export_stl":
        this.emitExport(args, emitter, "STL");
        break;
      case "export_dxf":
        this.emitExport(args, emitter, "DXF");
        break;
      case "export_iges":
        this.emitExport(args, emitter, "IGES");
        break;
      case "export_f3d":
        this.emitExport(args, emitter, "F3D");
        break;
      case "import_step":
      case "import_iges":
      case "import_dxf":
      case "import_stl":
        this.emitImport(args, emitter);
        break;

      // ── Parameters ───────────────────────────────────────────────
      case "parameter_declare":
        this.emitParameterDeclare(args, emitter);
        break;
      case "parameter_equation":
        this.emitParameterEquation(args, emitter);
        break;

      // ── Custom ───────────────────────────────────────────────────
      case "custom":
        this.emitCustom(args, emitter);
        break;

      default:
        emitter.warn(`Unhandled operation kind: ${kind}`);
    }
  }

  // ── Unit conversion ──────────────────────────────────────────────────────

  private getUnitFactor(units: string): number {
    switch (units) {
      case "mm": return 0.1;    // mm to cm
      case "in": return 2.54;   // in to cm
      case "cm": return 1.0;
      default: return 0.1;
    }
  }

  private num(val: unknown, defaultVal = 0): number {
    if (typeof val === "number" && !isNaN(val) && isFinite(val)) return val;
    return defaultVal;
  }

  private nextEntity(): string {
    return `entity_${++this.entityCounter}`;
  }

  // ── Sketch emission helpers ──────────────────────────────────────────────

  private emitSketchCreate(args: Record<string, unknown>, emitter: CADEmitter, ctx: Fusion360GenerationContext | undefined): void {
    const plane = String(args.plane ?? "XY").toUpperCase();
    const sketchName = this.nextEntity();

    emitter.line(`# Create sketch on ${plane} plane`);

    if (plane === "XY") {
      emitter.line(`${sketchName}_plane = rootComp.xYConstructionPlane`);
    } else if (plane === "XZ") {
      emitter.line(`${sketchName}_plane = rootComp.xZConstructionPlane`);
    } else if (plane === "YZ") {
      emitter.line(`${sketchName}_plane = rootComp.yZConstructionPlane`);
    } else {
      emitter.line(`${sketchName}_plane = rootComp.xYConstructionPlane  # default`);
    }

    emitter.line(`sketches = rootComp.sketches`);
    emitter.line(`sketch = sketches.add(${sketchName}_plane)`);
    emitter.parameter("sketch_plane", plane, "plane", "Sketch construction plane");
  }

  private emitSketchLine(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x1 = this.num(args.x1);
    const y1 = this.num(args.y1);
    const x2 = this.num(args.x2, 10);
    const y2 = this.num(args.y2, 10);

    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0)`);
    emitter.line("line = lines.addByTwoPoints(pt1, pt2)");
    emitter.parameter("line_x1", x1, "mm", "Line start X");
    emitter.parameter("line_y1", y1, "mm", "Line start Y");
  }

  private emitSketchArc(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 10);
    const startAngle = this.num(args.startAngle, 0);
    const sweepAngle = this.num(args.sweepAngle, 90);

    emitter.line("arcs = sketch.sketchCurves.sketchArcs");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`arc = arcs.addByCenterStartSweep(center, adsk.core.Point3D.create(${cx + radius}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0), math.radians(${sweepAngle}))`);
    emitter.parameter("arc_radius", radius, "mm", "Arc radius");
  }

  private emitSketchCircle(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 10);

    emitter.line("circles = sketch.sketchCurves.sketchCircles");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`circle = circles.addByCenterRadius(center, ${radius}*UNIT_FACTOR)`);
    emitter.parameter("circle_radius", radius, "mm", "Circle radius");
  }

  private emitSketchRectangle(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const width = this.num(args.width, 100);
    const height = this.num(args.height, 50);

    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x + width}*UNIT_FACTOR, ${y + height}*UNIT_FACTOR, 0)`);
    emitter.line("rect = lines.addTwoPointRectangle(pt1, pt2)");
    emitter.parameter("rect_width", width, "mm", "Rectangle width");
    emitter.parameter("rect_height", height, "mm", "Rectangle height");
  }

  private emitSketchPolygon(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 20);
    const sides = this.num(args.sides, 6);

    emitter.line(`# ${sides}-sided polygon inscribed in circle of radius ${radius}`);
    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`points = []`);
    emitter.line(`for i in range(${sides}):`);
    emitter.line(`    angle = 2 * math.pi * i / ${sides}`);
    emitter.line(`    px = ${cx}*UNIT_FACTOR + ${radius}*UNIT_FACTOR * math.cos(angle)`);
    emitter.line(`    py = ${cy}*UNIT_FACTOR + ${radius}*UNIT_FACTOR * math.sin(angle)`);
    emitter.line(`    points.append(adsk.core.Point3D.create(px, py, 0))`);
    emitter.line(`for i in range(${sides}):`);
    emitter.line(`    lines.addByTwoPoints(points[i], points[(i+1) % ${sides}])`);
    emitter.parameter("polygon_sides", sides, "count", "Number of sides");
  }

  private emitSketchSpline(args: Record<string, unknown>, emitter: CADEmitter): void {
    const points = args.points as number[][] ?? [[0, 0, 0], [10, 5, 0], [20, 0, 0]];

    emitter.line("splines = sketch.sketchCurves.sketchFittedSplines");
    emitter.line("splinePoints = adsk.core.ObjectCollection.create()");
    for (const pt of points) {
      const [x, y, z] = pt;
      emitter.line(`splinePoints.add(adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, ${z ?? 0}*UNIT_FACTOR))`);
    }
    emitter.line("spline = splines.add(splinePoints)");
  }

  private emitSketchEllipse(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const majorRadius = this.num(args.majorRadius, 20);
    const minorRadius = this.num(args.minorRadius, 10);

    emitter.line("ellipses = sketch.sketchCurves.sketchEllipses");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`majorAxis = adsk.core.Point3D.create(${cx + majorRadius}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`ellipse = ellipses.add(center, majorAxis, ${minorRadius / majorRadius})`);
    emitter.parameter("ellipse_major", majorRadius, "mm", "Ellipse major radius");
    emitter.parameter("ellipse_minor", minorRadius, "mm", "Ellipse minor radius");
  }

  private emitSketchSlot(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x1 = this.num(args.x1);
    const y1 = this.num(args.y1);
    const x2 = this.num(args.x2, 50);
    const y2 = this.num(args.y2);
    const width = this.num(args.width, 10);

    emitter.line("# Slot (center-to-center with width)");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0)`);
    emitter.line(`# Create slot using arc and lines`);
    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line("arcs = sketch.sketchCurves.sketchArcs");
    emitter.parameter("slot_width", width, "mm", "Slot width");
  }

  private emitSketchPoint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);

    emitter.line("sketchPoints = sketch.sketchPoints");
    emitter.line(`pt = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line("point = sketchPoints.add(pt)");
  }

  private emitSketchConstraint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const constraintType = String(args.type ?? "coincident");
    emitter.line(`# Constraint: ${constraintType}`);
    emitter.line(`constraints = sketch.geometricConstraints`);

    switch (constraintType) {
      case "horizontal":
        emitter.line("constraints.addHorizontal(line)");
        break;
      case "vertical":
        emitter.line("constraints.addVertical(line)");
        break;
      case "perpendicular":
        emitter.line("constraints.addPerpendicular(line1, line2)");
        break;
      case "parallel":
        emitter.line("constraints.addParallel(line1, line2)");
        break;
      case "tangent":
        emitter.line("constraints.addTangent(curve1, curve2)");
        break;
      case "coincident":
      default:
        emitter.line("constraints.addCoincident(pt1, pt2)");
    }
  }

  private emitSketchDimension(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dimType = String(args.type ?? "linear");
    const value = this.num(args.value, 10);

    emitter.line(`# Dimension: ${dimType} = ${value}`);
    emitter.line("dims = sketch.sketchDimensions");
    emitter.line(`textPoint = adsk.core.Point3D.create(0, 0, 0)`);

    if (dimType === "diameter" || dimType === "radius") {
      emitter.line(`dim = dims.addDiameterDimension(circle, textPoint)`);
    } else {
      emitter.line(`dim = dims.addDistanceDimension(pt1, pt2, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, textPoint)`);
    }
    emitter.parameter(`dim_${dimType}`, value, "mm", `Dimension ${dimType}`);
  }

  // ── Feature emission helpers ─────────────────────────────────────────────

  private emitFeatureExtrude(args: Record<string, unknown>, emitter: CADEmitter): void {
    const depth = this.num(args.depth, 10);
    const direction = String(args.direction ?? "positive");
    const operation = String(args.operation ?? "new_body");

    emitter.line("# Extrude feature");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("extrudes = rootComp.features.extrudeFeatures");
    emitter.line("extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");

    const dirSign = direction === "negative" ? "-" : "";
    emitter.line(`dist = adsk.core.ValueInput.createByReal(${dirSign}${depth} * UNIT_FACTOR)`);
    emitter.line("extInput.setDistanceExtent(False, dist)");
    emitter.line("ext = extrudes.add(extInput)");
    emitter.parameter("extrude_depth", depth, "mm", "Extrude depth");
  }

  private emitFeatureRevolve(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 360);
    const axisX = this.num(args.axisX, 1);
    const axisY = this.num(args.axisY, 0);
    const axisZ = this.num(args.axisZ, 0);

    emitter.line("# Revolve feature");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("revolves = rootComp.features.revolveFeatures");

    if (axisX === 1) {
      emitter.line("revAxis = rootComp.xConstructionAxis");
    } else if (axisY === 1) {
      emitter.line("revAxis = rootComp.yConstructionAxis");
    } else {
      emitter.line("revAxis = rootComp.zConstructionAxis");
    }

    emitter.line("revInput = revolves.createInput(prof, revAxis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line(`revAngle = adsk.core.ValueInput.createByReal(math.radians(${angle}))`);
    emitter.line("revInput.setAngleExtent(False, revAngle)");
    emitter.line("rev = revolves.add(revInput)");
    emitter.parameter("revolve_angle", angle, "deg", "Revolve angle");
  }

  private emitFeatureLoft(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Loft feature");
    emitter.line("lofts = rootComp.features.loftFeatures");
    emitter.line("loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("loftSections = loftInput.loftSections");
    emitter.line("# Add profiles to loft sections");
    emitter.line("# loftSections.add(profile1)");
    emitter.line("# loftSections.add(profile2)");
    emitter.line("# loft = lofts.add(loftInput)");
  }

  private emitFeatureSweep(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Sweep feature");
    emitter.line("sweeps = rootComp.features.sweepFeatures");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("# path = pathSketch.sketchCurves.sketchLines.item(0)");
    emitter.line("# sweepInput = sweeps.createInput(prof, path, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# sweep = sweeps.add(sweepInput)");
  }

  private emitFeatureHole(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const diameter = this.num(args.diameter, 10);
    const depth = this.num(args.depth, 20);

    emitter.line("# Hole feature");
    emitter.line("holes = rootComp.features.holeFeatures");
    emitter.line(`holePt = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line("# Select face for hole placement");
    emitter.line(`holeDiam = adsk.core.ValueInput.createByReal(${diameter} * UNIT_FACTOR)`);
    emitter.line(`holeDepth = adsk.core.ValueInput.createByReal(${depth} * UNIT_FACTOR)`);
    emitter.line("# holeInput = holes.createSimpleInput(holeDiam)");
    emitter.line("# holeInput.setPositionByPoint(face, holePt)");
    emitter.line("# holeInput.setDistanceExtent(holeDepth)");
    emitter.line("# hole = holes.add(holeInput)");
    emitter.parameter("hole_diameter", diameter, "mm", "Hole diameter");
    emitter.parameter("hole_depth", depth, "mm", "Hole depth");
  }

  private emitFeaturePocket(args: Record<string, unknown>, emitter: CADEmitter): void {
    const depth = this.num(args.depth, 5);

    emitter.line("# Pocket (negative extrude)");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("extrudes = rootComp.features.extrudeFeatures");
    emitter.line("extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.CutFeatureOperation)");
    emitter.line(`dist = adsk.core.ValueInput.createByReal(-${depth} * UNIT_FACTOR)`);
    emitter.line("extInput.setDistanceExtent(False, dist)");
    emitter.line("pocket = extrudes.add(extInput)");
    emitter.parameter("pocket_depth", depth, "mm", "Pocket depth");
  }

  private emitFeatureFillet(args: Record<string, unknown>, emitter: CADEmitter): void {
    const radius = this.num(args.radius, 2);

    emitter.line("# Fillet feature");
    emitter.line("fillets = rootComp.features.filletFeatures");
    emitter.line("edges = adsk.core.ObjectCollection.create()");
    emitter.line("# Select edges to fillet");
    emitter.line("# for edge in body.edges: edges.add(edge)");
    emitter.line(`filletInput = fillets.createInput()`);
    emitter.line("filletInput.addConstantRadiusEdgeSet(edges, adsk.core.ValueInput.createByReal(" + radius + " * UNIT_FACTOR), True)");
    emitter.line("fillet = fillets.add(filletInput)");
    emitter.parameter("fillet_radius", radius, "mm", "Fillet radius");
  }

  private emitFeatureChamfer(args: Record<string, unknown>, emitter: CADEmitter): void {
    const distance = this.num(args.distance, 1);
    const angle = this.num(args.angle, 45);

    emitter.line("# Chamfer feature");
    emitter.line("chamfers = rootComp.features.chamferFeatures");
    emitter.line("edges = adsk.core.ObjectCollection.create()");
    emitter.line("# Select edges to chamfer");
    emitter.line(`chamferInput = chamfers.createInput(edges, True)`);
    emitter.line(`chamferInput.setToEqualDistance(adsk.core.ValueInput.createByReal(${distance} * UNIT_FACTOR))`);
    emitter.line("chamfer = chamfers.add(chamferInput)");
    emitter.parameter("chamfer_distance", distance, "mm", "Chamfer distance");
  }

  private emitFeatureShell(args: Record<string, unknown>, emitter: CADEmitter): void {
    const thickness = this.num(args.thickness, 2);

    emitter.line("# Shell feature");
    emitter.line("shells = rootComp.features.shellFeatures");
    emitter.line("faces = adsk.core.ObjectCollection.create()");
    emitter.line("# Select faces to remove");
    emitter.line(`shellInput = shells.createInput(faces, False)`);
    emitter.line(`shellInput.insideThickness = adsk.core.ValueInput.createByReal(${thickness} * UNIT_FACTOR)`);
    emitter.line("shell = shells.add(shellInput)");
    emitter.parameter("shell_thickness", thickness, "mm", "Shell wall thickness");
  }

  private emitFeatureDraft(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 3);

    emitter.line("# Draft feature");
    emitter.line("drafts = rootComp.features.draftFeatures");
    emitter.line("faces = adsk.core.ObjectCollection.create()");
    emitter.line("# Select faces to draft");
    emitter.line(`draftInput = drafts.createInput(faces, rootComp.zConstructionAxis, adsk.core.ValueInput.createByReal(math.radians(${angle})), False)`);
    emitter.line("draft = drafts.add(draftInput)");
    emitter.parameter("draft_angle", angle, "deg", "Draft angle");
  }

  private emitFeatureRib(args: Record<string, unknown>, emitter: CADEmitter): void {
    const thickness = this.num(args.thickness, 3);

    emitter.line("# Rib feature");
    emitter.line("ribs = rootComp.features.ribFeatures");
    emitter.line(`ribInput = ribs.createInput(sketch.profiles.item(0), adsk.core.ValueInput.createByReal(${thickness} * UNIT_FACTOR), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)`);
    emitter.line("rib = ribs.add(ribInput)");
    emitter.parameter("rib_thickness", thickness, "mm", "Rib thickness");
  }

  private emitFeatureThread(args: Record<string, unknown>, emitter: CADEmitter): void {
    const threadType = String(args.type ?? "metric");

    emitter.line(`# Thread feature (${threadType})`);
    emitter.line("threads = rootComp.features.threadFeatures");
    emitter.line("# Select cylindrical face");
    emitter.line("# threadInput = threads.createInput(face, threadData)");
    emitter.line("# thread = threads.add(threadInput)");
    emitter.parameter("thread_type", threadType, "type", "Thread specification");
  }

  // ── Surface emission helpers ─────────────────────────────────────────────

  private emitSurfaceLoft(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface loft");
    emitter.line("lofts = rootComp.features.loftFeatures");
    emitter.line("loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("loftInput.isSolid = False  # Create surface, not solid");
    emitter.line("# Add profiles and rails");
    emitter.line("# loft = lofts.add(loftInput)");
  }

  private emitSurfaceSweep(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface sweep");
    emitter.line("sweeps = rootComp.features.sweepFeatures");
    emitter.line("# sweepInput = sweeps.createInput(profile, path, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# sweepInput.isSolid = False");
    emitter.line("# sweep = sweeps.add(sweepInput)");
  }

  private emitSurfaceFill(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface fill (patch)");
    emitter.line("patches = rootComp.features.patchFeatures");
    emitter.line("# Select boundary edges");
    emitter.line("# patchInput = patches.createInput(edges, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# patch = patches.add(patchInput)");
  }

  private emitSurfaceOffset(args: Record<string, unknown>, emitter: CADEmitter): void {
    const distance = this.num(args.distance, 1);
    emitter.line(`# Surface offset by ${distance}mm`);
    emitter.line("offsets = rootComp.features.offsetFeatures");
    emitter.line("# Select surface faces");
    emitter.line(`# offsetInput = offsets.createInput(faces, adsk.core.ValueInput.createByReal(${distance} * UNIT_FACTOR), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)`);
    emitter.line("# offset = offsets.add(offsetInput)");
  }

  private emitSurfaceTrim(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface trim");
    emitter.line("trims = rootComp.features.trimFeatures");
    emitter.line("# Select surface and trimming tool");
    emitter.line("# trimInput = trims.createInput(surface, trimTool)");
    emitter.line("# trim = trims.add(trimInput)");
  }

  // ── Transform emission helpers ───────────────────────────────────────────

  private emitTransformMove(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dx = this.num(args.dx);
    const dy = this.num(args.dy);
    const dz = this.num(args.dz);

    emitter.line("# Move/translate");
    emitter.line("moves = rootComp.features.moveFeatures");
    emitter.line("bodies = adsk.core.ObjectCollection.create()");
    emitter.line("# Add bodies to move");
    emitter.line("moveInput = moves.createInput(bodies, adsk.fusion.TransformTypes.MoveType)");
    emitter.line(`vector = adsk.core.Vector3D.create(${dx}*UNIT_FACTOR, ${dy}*UNIT_FACTOR, ${dz}*UNIT_FACTOR)`);
    emitter.line("moveInput.setToMove(vector)");
    emitter.line("move = moves.add(moveInput)");
    emitter.parameter("move_dx", dx, "mm", "Move X distance");
  }

  private emitTransformRotate(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 45);
    const axisX = this.num(args.axisX);
    const axisY = this.num(args.axisY);
    const axisZ = this.num(args.axisZ, 1);

    emitter.line("# Rotate");
    emitter.line("moves = rootComp.features.moveFeatures");
    emitter.line("bodies = adsk.core.ObjectCollection.create()");
    emitter.line("moveInput = moves.createInput(bodies, adsk.fusion.TransformTypes.RotateType)");

    if (axisZ === 1) {
      emitter.line("axis = rootComp.zConstructionAxis");
    } else if (axisY === 1) {
      emitter.line("axis = rootComp.yConstructionAxis");
    } else {
      emitter.line("axis = rootComp.xConstructionAxis");
    }

    emitter.line(`moveInput.setToRotate(axis, math.radians(${angle}))`);
    emitter.line("move = moves.add(moveInput)");
    emitter.parameter("rotate_angle", angle, "deg", "Rotation angle");
  }

  private emitTransformMirror(args: Record<string, unknown>, emitter: CADEmitter): void {
    const plane = String(args.plane ?? "XY");

    emitter.line(`# Mirror about ${plane} plane`);
    emitter.line("mirrors = rootComp.features.mirrorFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");

    if (plane === "XY") {
      emitter.line("mirrorPlane = rootComp.xYConstructionPlane");
    } else if (plane === "XZ") {
      emitter.line("mirrorPlane = rootComp.xZConstructionPlane");
    } else {
      emitter.line("mirrorPlane = rootComp.yZConstructionPlane");
    }

    emitter.line("mirrorInput = mirrors.createInput(entities, mirrorPlane)");
    emitter.line("mirror = mirrors.add(mirrorInput)");
  }

  private emitPatternLinear(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dx = this.num(args.dx, 25);
    const dy = this.num(args.dy);
    const count = this.num(args.count, 4);

    emitter.line("# Linear pattern");
    emitter.line("patterns = rootComp.features.rectangularPatternFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("# Add features to pattern");
    emitter.line(`patternInput = patterns.createInput(entities, rootComp.xConstructionAxis, adsk.core.ValueInput.createByReal(${count}), adsk.core.ValueInput.createByReal(${dx}*UNIT_FACTOR), adsk.fusion.PatternDistanceType.SpacingPatternDistanceType)`);
    emitter.line("pattern = patterns.add(patternInput)");
    emitter.parameter("pattern_count", count, "count", "Pattern instance count");
    emitter.parameter("pattern_spacing", dx, "mm", "Pattern spacing");
  }

  private emitPatternCircular(args: Record<string, unknown>, emitter: CADEmitter): void {
    const count = this.num(args.count, 6);
    const angle = this.num(args.angle, 360);

    emitter.line("# Circular pattern");
    emitter.line("patterns = rootComp.features.circularPatternFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("# Add features to pattern");
    emitter.line(`patternInput = patterns.createInput(entities, rootComp.zConstructionAxis)`);
    emitter.line(`patternInput.quantity = adsk.core.ValueInput.createByReal(${count})`);
    emitter.line(`patternInput.totalAngle = adsk.core.ValueInput.createByReal(math.radians(${angle}))`);
    emitter.line("pattern = patterns.add(patternInput)");
    emitter.parameter("circular_pattern_count", count, "count", "Circular pattern count");
  }

  private emitTransformScale(args: Record<string, unknown>, emitter: CADEmitter): void {
    const factor = this.num(args.factor, 1.5);

    emitter.line("# Scale");
    emitter.line("scales = rootComp.features.scaleFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("scalePoint = adsk.core.Point3D.create(0, 0, 0)");
    emitter.line(`scaleInput = scales.createInput(entities, scalePoint, adsk.core.ValueInput.createByReal(${factor}))`);
    emitter.line("scale = scales.add(scaleInput)");
    emitter.parameter("scale_factor", factor, "ratio", "Scale factor");
  }

  // ── Datum geometry helpers ───────────────────────────────────────────────

  private emitDatumPlane(args: Record<string, unknown>, emitter: CADEmitter): void {
    const offset = this.num(args.offset, 10);

    emitter.line("# Construction plane");
    emitter.line("planes = rootComp.constructionPlanes");
    emitter.line("planeInput = planes.createInput()");
    emitter.line(`planeInput.setByOffset(rootComp.xYConstructionPlane, adsk.core.ValueInput.createByReal(${offset}*UNIT_FACTOR))`);
    emitter.line("plane = planes.add(planeInput)");
    emitter.parameter("datum_plane_offset", offset, "mm", "Plane offset distance");
  }

  private emitDatumAxis(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Construction axis");
    emitter.line("axes = rootComp.constructionAxes");
    emitter.line("axisInput = axes.createInput()");
    emitter.line("# Define axis by two points or line");
    emitter.line("# axis = axes.add(axisInput)");
  }

  private emitDatumPoint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const z = this.num(args.z);

    emitter.line("# Construction point");
    emitter.line("points = rootComp.constructionPoints");
    emitter.line("pointInput = points.createInput()");
    emitter.line(`pointInput.setByPoint(adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, ${z}*UNIT_FACTOR))`);
    emitter.line("point = points.add(pointInput)");
  }

  // ── Export/Import helpers ────────────────────────────────────────────────

  private emitExport(args: Record<string, unknown>, emitter: CADEmitter, format: string): void {
    const filename = String(args.filename ?? `output.${format.toLowerCase()}`);

    emitter.line(`# Export to ${format}`);
    emitter.line("exportMgr = design.exportManager");

    switch (format) {
      case "STEP":
        emitter.line(`stepOptions = exportMgr.createSTEPExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(stepOptions)");
        break;
      case "STL":
        emitter.line(`stlOptions = exportMgr.createSTLExportOptions(rootComp.bRepBodies.item(0), '${filename}')`);
        emitter.line("stlOptions.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium");
        emitter.line("exportMgr.execute(stlOptions)");
        break;
      case "DXF":
        emitter.line(`# DXF export from sketch`);
        emitter.line(`# sketch.saveAsDXF('${filename}')`);
        break;
      case "IGES":
        emitter.line(`igesOptions = exportMgr.createIGESExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(igesOptions)");
        break;
      case "F3D":
        emitter.line(`fusionOptions = exportMgr.createFusionArchiveExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(fusionOptions)");
        break;
    }
    emitter.parameter("export_filename", filename, "path", `${format} export path`);
  }

  private emitImport(args: Record<string, unknown>, emitter: CADEmitter): void {
    const filepath = String(args.filepath ?? "input.step");

    emitter.line(`# Import file: ${filepath}`);
    emitter.line("importMgr = app.importManager");
    emitter.line(`importOptions = importMgr.createSTEPImportOptions('${filepath}')`);
    emitter.line("importMgr.importToTarget(importOptions, rootComp)");
  }

  // ── Parameter helpers ────────────────────────────────────────────────────

  private emitParameterDeclare(args: Record<string, unknown>, emitter: CADEmitter): void {
    const name = String(args.name ?? "param1");
    const value = this.num(args.value, 10);
    const unit = String(args.unit ?? "mm");

    emitter.line("# User parameter");
    emitter.line("params = design.userParameters");
    emitter.line(`params.add('${name}', adsk.core.ValueInput.createByReal(${value}*UNIT_FACTOR), '${unit}', '')`);
    emitter.parameter(name, value, unit, "User-defined parameter");
  }

  private emitParameterEquation(args: Record<string, unknown>, emitter: CADEmitter): void {
    const name = String(args.name ?? "derived");
    const expression = String(args.expression ?? "param1 * 2");

    emitter.line(`# Parameter equation: ${name} = ${expression}`);
    emitter.line("params = design.userParameters");
    emitter.line(`params.add('${name}', adsk.core.ValueInput.createByString('${expression}'), '', '')`);
  }

  // ── Custom code helper ───────────────────────────────────────────────────

  private emitCustom(args: Record<string, unknown>, emitter: CADEmitter): void {
    const code = String(args.code ?? "# Custom Python block");
    emitter.line("# --- Custom code block ---");
    for (const line of code.split("\n")) {
      emitter.line(line);
    }
    emitter.line("# --- End custom block ---");
  }

  // ── Legacy ExtractedAction → Fusion 360 Python script API ────────────────
  //
  // These methods are the production callers' contract (cadDispatcher.ts
  // f360_generate_script / f360_from_description / f360_parametric_script /
  // f360_convert_cadquery). They emit Python directly without going through
  // the typed CADOperation pipeline because the legacy contract requires a
  // specific shape that predates UnifiedCADCodeGeneratorBase.

  /**
   * Generate a Fusion 360 Python script from an ExtractedAction sequence.
   * Used by tutorial-replay pipelines + f360_generate_script MCP action.
   */
  generateScript(
    actions: ExtractedAction[],
    options?: { component_name?: string; parametric?: boolean },
  ): Fusion360Script {
    const componentName = options?.component_name ?? "PRISM_Generated";
    const parametric = options?.parametric ?? false;
    const operations: string[] = [];
    const lines: string[] = [];

    lines.push("# AUTO-GENERATED by PRISM Fusion360CodeGeneratorEngine");
    lines.push(`# Component: ${componentName}`);
    lines.push("# Units: mm (converted to cm internally for Fusion 360)");
    lines.push("");
    lines.push("import adsk.core, adsk.fusion, traceback");
    lines.push("import math");
    lines.push("");
    lines.push("def select_edges_by_direction(body, direction='all'):");
    lines.push('    """Helper: collect edges from a body matching a direction tag."""');
    lines.push("    edges = adsk.core.ObjectCollection.create()");
    lines.push("    for edge in body.edges:");
    lines.push("        edges.add(edge)");
    lines.push("    return edges");
    lines.push("");

    let parameterCount = 0;
    const params = parametric ? this.extractParameters(actions) : [];

    if (parametric && params.length > 0) {
      lines.push("# === Parameters ===");
      for (const p of params) {
        lines.push(`${p.name} = ${p.value}  # ${p.unit ?? "mm"}`);
        parameterCount++;
      }
      lines.push("");
    }

    lines.push("def run(context):");
    lines.push("    ui = None");
    lines.push("    try:");
    lines.push("        app = adsk.core.Application.get()");
    lines.push("        ui = app.userInterface");
    lines.push("        design = adsk.fusion.Design.cast(app.activeProduct)");
    lines.push("        if not design:");
    lines.push("            if ui: ui.messageBox('No active Fusion design')");
    lines.push("            return");
    lines.push("        rootComp = design.rootComponent");
    lines.push("        bodies = []  # track created bodies for downstream ops");
    lines.push("");

    if (parametric && params.length > 0) {
      for (const p of params) {
        lines.push(
          `        design.userParameters.add('${p.name}', adsk.core.ValueInput.createByReal(${(p.value / 10).toString()}), '${p.unit ?? "mm"}', '')`,
        );
      }
      lines.push("");
    }

    for (const a of actions) {
      operations.push(a.action_type);
      const desc = (a.description || a.action_type).replace(/\n/g, " ");
      lines.push(`        # Step ${a.step_number}: ${desc}`);
      for (const ol of this.emitLegacyAction(a)) {
        lines.push(`        ${ol}`);
      }
      lines.push("");
    }

    lines.push(`        ui.messageBox('${componentName} created successfully!')`);
    lines.push("    except:");
    lines.push("        if ui:");
    lines.push("            ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))");

    return {
      script: lines.join("\n"),
      operations,
      parameter_count: parameterCount,
      script_name: `${componentName}.py`,
      estimated_complexity: this.estimateComplexity(actions),
    };
  }

  /**
   * Generate a parametric Fusion 360 script — dimensions hoisted as named
   * variables at the top + corresponding userParameters.add() calls.
   */
  generateParametricScript(
    actions: ExtractedAction[],
    options?: { component_name?: string },
  ): Fusion360Script {
    return this.generateScript(actions, { ...options, parametric: true });
  }

  /**
   * Generate a Fusion 360 script from a natural-language part description.
   * Recognises: "box WxHxD", "cylinder diameter D, height H", optional
   * "with Nmm fillet" / "with Nmm chamfer".
   */
  generateFromDescription(
    description: string,
    options?: { component_name?: string },
  ): Fusion360Script {
    const actions = this.parseDescription(description);
    return this.generateScript(actions, options);
  }

  /**
   * Convert a CadQuery script to an equivalent Fusion 360 script.
   * Recognises .Workplane().box(...), .circle(...).extrude(...),
   * .fillet(...), .chamfer(...).
   */
  convertCadQueryToFusion360(
    cqScript: string,
    options?: { component_name?: string },
  ): Fusion360Script {
    const actions = this.parseCadQuery(cqScript);
    return this.generateScript(actions, options);
  }

  /**
   * Validate a generated Fusion 360 script for structural correctness +
   * common authoring mistakes (missing run(), unconverted mm, missing
   * imports).
   */
  validateScript(script: string): { valid: boolean; issues: string[] } {
    const issues: string[] = [];
    if (!script.includes("def run(context):")) {
      issues.push("Missing run(context) function entry point");
    }
    if (!/import\s+adsk/.test(script)) {
      issues.push("Missing 'import adsk' — Fusion API not loaded");
    }
    // Heuristic: createByReal(N) where N >= 100 almost certainly is raw mm
    // (Fusion is internal cm — even a 1m part would be 100cm and exceptional).
    const re = /createByReal\(\s*(-?\d+(?:\.\d+)?)\s*\)/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(script)) !== null) {
      const v = Math.abs(Number(m[1]));
      if (v >= 100) {
        issues.push(
          `createByReal(${m[1]}) — value too large for cm; likely unconverted mm`,
        );
        break;
      }
    }
    return { valid: issues.length === 0, issues };
  }

  /**
   * Catalogue of supported legacy action_type → Fusion 360 mappings.
   * Consumed by f360_supported_ops MCP action + tutorial-extractor UIs.
   */
  getOperationCatalog(): Array<{ action_type: string; description: string }> {
    return [
      { action_type: "sketch_create", description: "Create sketch on construction plane" },
      { action_type: "sketch_line", description: "Draw line in active sketch" },
      { action_type: "sketch_arc", description: "Draw arc by center, start, sweep" },
      { action_type: "sketch_circle", description: "Draw circle by center & radius" },
      { action_type: "sketch_rectangle", description: "Draw rectangle by two points" },
      { action_type: "sketch_polygon", description: "Inscribed polygon in circle" },
      { action_type: "sketch_spline", description: "Fitted spline through points" },
      { action_type: "sketch_ellipse", description: "Ellipse by center + axes" },
      { action_type: "sketch_slot", description: "Slot by two centres + width" },
      { action_type: "sketch_dimension", description: "Add driving dimension" },
      { action_type: "sketch_constraint", description: "Add geometric constraint" },
      { action_type: "extrude", description: "Extrude profile to new body" },
      { action_type: "extrude_cut", description: "Extrude cut into existing body" },
      { action_type: "revolve", description: "Revolve profile about axis" },
      { action_type: "loft", description: "Loft between profiles" },
      { action_type: "sweep", description: "Sweep profile along path" },
      { action_type: "fillet", description: "Add constant-radius fillet to edges" },
      { action_type: "chamfer", description: "Add equal-distance chamfer to edges" },
      { action_type: "shell", description: "Shell out body to constant thickness" },
      { action_type: "draft", description: "Add draft angle to faces" },
      { action_type: "hole", description: "Add simple hole" },
      { action_type: "boolean_union", description: "Combine bodies (union)" },
      { action_type: "boolean_subtract", description: "Combine bodies (cut)" },
      { action_type: "boolean_intersect", description: "Combine bodies (intersect)" },
      { action_type: "pattern_linear", description: "Rectangular feature pattern" },
      { action_type: "pattern_circular", description: "Circular feature pattern" },
      { action_type: "mirror_body", description: "Mirror body about plane" },
    ];
  }

  // ── Legacy emission helpers ──────────────────────────────────────────────

  private emitLegacyAction(a: ExtractedAction): string[] {
    const p = a.parameters ?? {};
    const num = (k: string, def = 0): number => {
      const v = (p as Record<string, unknown>)[k];
      if (typeof v === "number" && isFinite(v)) return v;
      if (typeof v === "string") {
        const n = Number(v);
        if (isFinite(n)) return n;
      }
      return def;
    };
    // mm → cm string. 50 → "5", 25 → "2.5", 3 → "0.3" (no trailing zeros)
    const mm = (n: number): string => (n / 10).toString();
    const lines: string[] = [];

    switch (a.action_type) {
      case "sketch_create": {
        const plane = String(p.plane ?? "XY").toUpperCase();
        const planeProp =
          plane === "XZ"
            ? "xZConstructionPlane"
            : plane === "YZ"
              ? "yZConstructionPlane"
              : "xYConstructionPlane";
        lines.push("sketches = rootComp.sketches");
        lines.push(`sketch = sketches.add(rootComp.${planeProp})`);
        break;
      }
      case "sketch_close":
        lines.push("# sketch_close — finalize active sketch");
        break;
      case "sketch_rectangle": {
        const w = num("width_mm", 50);
        const h = num("height_mm", 30);
        lines.push(`# rectangle: width ${w}mm = ${mm(w)}cm, height ${h}mm = ${mm(h)}cm`);
        lines.push("pt1 = adsk.core.Point3D.create(0, 0, 0)");
        lines.push(`pt2 = adsk.core.Point3D.create(${mm(w)}, ${mm(h)}, 0)`);
        lines.push("sketch.sketchCurves.sketchLines.addTwoPointRectangle(pt1, pt2)");
        break;
      }
      case "sketch_circle": {
        const r = num("radius_mm", 10);
        lines.push(`# circle: radius ${r}mm = ${mm(r)}cm`);
        lines.push(
          `sketch.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0, 0, 0), ${mm(r)})`,
        );
        break;
      }
      case "sketch_line": {
        const x1 = num("x1_mm");
        const y1 = num("y1_mm");
        const x2 = num("x2_mm", 10);
        const y2 = num("y2_mm", 10);
        lines.push(
          `pt1 = adsk.core.Point3D.create(${mm(x1)}, ${mm(y1)}, 0)`,
        );
        lines.push(
          `pt2 = adsk.core.Point3D.create(${mm(x2)}, ${mm(y2)}, 0)`,
        );
        lines.push("sketch.sketchCurves.sketchLines.addByTwoPoints(pt1, pt2)");
        break;
      }
      case "sketch_arc": {
        const cx = num("centerX_mm");
        const cy = num("centerY_mm");
        const r = num("radius_mm", 10);
        const sweep = num("sweep_deg", 90);
        lines.push("arcs = sketch.sketchCurves.sketchArcs");
        lines.push(
          `arcs.addByCenterStartSweep(adsk.core.Point3D.create(${mm(cx)}, ${mm(cy)}, 0), adsk.core.Point3D.create(${mm(cx + r)}, ${mm(cy)}, 0), math.radians(${sweep}))`,
        );
        break;
      }
      case "sketch_dimension":
      case "sketch_constraint":
      case "sketch_offset":
      case "sketch_trim":
      case "sketch_mirror":
      case "sketch_spline":
        lines.push(`# ${a.action_type} — emitted as sketch annotation`);
        break;
      case "extrude": {
        const d = num("distance_mm", 10);
        lines.push(`# extrude: depth ${d}mm = ${mm(d)}cm`);
        lines.push("prof = sketch.profiles.item(0)");
        lines.push(
          "extInput = rootComp.features.extrudeFeatures.createInput(prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
        );
        lines.push(
          `extInput.setDistanceExtent(False, adsk.core.ValueInput.createByReal(${mm(d)}))`,
        );
        lines.push("ext = rootComp.features.extrudeFeatures.add(extInput)");
        lines.push("if ext.bodies.count > 0: bodies.append(ext.bodies.item(0))");
        break;
      }
      case "extrude_cut": {
        const d = num("distance_mm", 10);
        lines.push(`# extrude_cut: depth ${d}mm = ${mm(d)}cm`);
        lines.push("prof = sketch.profiles.item(0)");
        lines.push(
          "extInput = rootComp.features.extrudeFeatures.createInput(prof, adsk.fusion.FeatureOperations.CutFeatureOperation)",
        );
        lines.push(
          `extInput.setDistanceExtent(False, adsk.core.ValueInput.createByReal(-${mm(d)}))`,
        );
        lines.push("rootComp.features.extrudeFeatures.add(extInput)");
        break;
      }
      case "revolve": {
        const ang = num("angle_deg", 360);
        lines.push("prof = sketch.profiles.item(0)");
        lines.push("revolves = rootComp.features.revolveFeatures");
        lines.push(
          "revInput = revolves.createInput(prof, rootComp.zConstructionAxis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
        );
        lines.push(
          `revInput.setAngleExtent(False, adsk.core.ValueInput.createByReal(math.radians(${ang})))`,
        );
        lines.push("rev = revolves.add(revInput)");
        lines.push("if rev.bodies.count > 0: bodies.append(rev.bodies.item(0))");
        break;
      }
      case "sweep":
        lines.push("# sweep — sweepFeatures.createInput(profile, path, ...)");
        lines.push("sweeps = rootComp.features.sweepFeatures");
        break;
      case "loft":
        lines.push("# loft");
        lines.push("lofts = rootComp.features.loftFeatures");
        lines.push(
          "loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
        );
        lines.push("# add loftSections from sketches before lofts.add(loftInput)");
        break;
      case "fillet": {
        const r = num("radius_mm", 2);
        lines.push(`# fillet: radius ${r}mm = ${mm(r)}cm`);
        lines.push(
          "body = bodies[-1] if bodies else (rootComp.bRepBodies.item(0) if rootComp.bRepBodies.count > 0 else None)",
        );
        lines.push("if body is not None:");
        lines.push("    edges = select_edges_by_direction(body, 'all')");
        lines.push("    fillets = rootComp.features.filletFeatures");
        lines.push("    filletInput = fillets.createInput()");
        lines.push(
          `    filletInput.addConstantRadiusEdgeSet(edges, adsk.core.ValueInput.createByReal(${mm(r)}), True)`,
        );
        lines.push("    fillets.add(filletInput)");
        break;
      }
      case "chamfer": {
        const d = num("distance_mm", 1);
        lines.push(`# chamfer: distance ${d}mm = ${mm(d)}cm`);
        lines.push(
          "body = bodies[-1] if bodies else (rootComp.bRepBodies.item(0) if rootComp.bRepBodies.count > 0 else None)",
        );
        lines.push("if body is not None:");
        lines.push("    edges = select_edges_by_direction(body, 'all')");
        lines.push("    chamfers = rootComp.features.chamferFeatures");
        lines.push("    chamferInput = chamfers.createInput(edges, True)");
        lines.push(
          `    chamferInput.setToEqualDistance(adsk.core.ValueInput.createByReal(${mm(d)}))`,
        );
        lines.push("    chamfers.add(chamferInput)");
        break;
      }
      case "shell": {
        const t = num("thickness_mm", 2);
        lines.push(`# shell: thickness ${t}mm = ${mm(t)}cm`);
        lines.push("shells = rootComp.features.shellFeatures");
        lines.push("faces = adsk.core.ObjectCollection.create()");
        lines.push("# select faces to remove before shellFeatures.createInput");
        lines.push("shellInput = shells.createInput(faces, False)");
        lines.push(
          `shellInput.insideThickness = adsk.core.ValueInput.createByReal(${mm(t)})`,
        );
        lines.push("shells.add(shellInput)");
        break;
      }
      case "draft": {
        const ang = num("angle_deg", 3);
        lines.push(`# draft: angle ${ang}°`);
        lines.push("drafts = rootComp.features.draftFeatures");
        lines.push("faces = adsk.core.ObjectCollection.create()");
        lines.push(
          `draftInput = drafts.createInput(faces, rootComp.zConstructionAxis, adsk.core.ValueInput.createByReal(math.radians(${ang})), False)`,
        );
        lines.push("drafts.add(draftInput)");
        break;
      }
      case "hole": {
        const dia = num("diameter_mm", 10);
        const dep = num("depth_mm", 20);
        lines.push(`# hole: diameter ${dia}mm = ${mm(dia)}cm, depth ${dep}mm = ${mm(dep)}cm`);
        lines.push("holes = rootComp.features.holeFeatures");
        lines.push(
          `holeInput = holes.createSimpleInput(adsk.core.ValueInput.createByReal(${mm(dia)}))`,
        );
        lines.push(
          `holeInput.setDistanceExtent(adsk.core.ValueInput.createByReal(${mm(dep)}))`,
        );
        lines.push("# holeInput.setPositionByPoint(face, point) before holes.add");
        break;
      }
      case "boolean_union":
      case "boolean_subtract":
      case "boolean_intersect": {
        const op =
          a.action_type === "boolean_subtract"
            ? "CutFeatureOperation"
            : a.action_type === "boolean_intersect"
              ? "IntersectFeatureOperation"
              : "JoinFeatureOperation";
        lines.push(`# ${a.action_type}`);
        lines.push("combineFeatures = rootComp.features.combineFeatures");
        lines.push("if len(bodies) >= 2:");
        lines.push("    target = bodies[0]");
        lines.push("    tools = adsk.core.ObjectCollection.create()");
        lines.push("    for b in bodies[1:]: tools.add(b)");
        lines.push("    combineInput = combineFeatures.createInput(target, tools)");
        lines.push(
          `    combineInput.operation = adsk.fusion.FeatureOperations.${op}`,
        );
        lines.push("    combineFeatures.add(combineInput)");
        break;
      }
      case "pattern_linear": {
        const cnt = num("count_x", 4);
        const sp = num("spacing_x_mm", 25);
        lines.push(`# linear pattern: count ${cnt}, spacing ${sp}mm = ${mm(sp)}cm`);
        lines.push("patterns = rootComp.features.rectangularPatternFeatures");
        lines.push("entities = adsk.core.ObjectCollection.create()");
        lines.push("for b in bodies: entities.add(b)");
        lines.push(
          `patternInput = patterns.createInput(entities, rootComp.xConstructionAxis, adsk.core.ValueInput.createByReal(${cnt}), adsk.core.ValueInput.createByReal(${mm(sp)}), adsk.fusion.PatternDistanceType.SpacingPatternDistanceType)`,
        );
        lines.push("patterns.add(patternInput)");
        break;
      }
      case "pattern_circular": {
        const cnt = num("count", 6);
        const ang = num("angle_deg", 360);
        lines.push(`# circular pattern: count ${cnt}, total angle ${ang}°`);
        lines.push("patterns = rootComp.features.circularPatternFeatures");
        lines.push("entities = adsk.core.ObjectCollection.create()");
        lines.push("for b in bodies: entities.add(b)");
        lines.push(
          "patternInput = patterns.createInput(entities, rootComp.zConstructionAxis)",
        );
        lines.push(
          `patternInput.quantity = adsk.core.ValueInput.createByReal(${cnt})`,
        );
        lines.push(
          `patternInput.totalAngle = adsk.core.ValueInput.createByReal(math.radians(${ang}))`,
        );
        lines.push("patterns.add(patternInput)");
        break;
      }
      case "mirror_body": {
        const plane = String(p.plane ?? "XY").toUpperCase();
        const planeProp =
          plane === "XZ"
            ? "xZConstructionPlane"
            : plane === "YZ"
              ? "yZConstructionPlane"
              : "xYConstructionPlane";
        lines.push(`# mirror about ${plane} plane`);
        lines.push("mirrors = rootComp.features.mirrorFeatures");
        lines.push("entities = adsk.core.ObjectCollection.create()");
        lines.push("for b in bodies: entities.add(b)");
        lines.push(
          `mirrorInput = mirrors.createInput(entities, rootComp.${planeProp})`,
        );
        lines.push("mirrors.add(mirrorInput)");
        break;
      }
      default:
        lines.push(`# unhandled action_type: ${a.action_type}`);
    }
    return lines;
  }

  private extractParameters(
    actions: ExtractedAction[],
  ): Array<{ name: string; value: number; unit?: string }> {
    const out: Array<{ name: string; value: number; unit?: string }> = [];
    let extrudeIdx = 0;
    let filletIdx = 0;
    let chamferIdx = 0;
    for (const a of actions) {
      const p = a.parameters as Record<string, unknown>;
      const numIf = (k: string): number | undefined => {
        const v = p[k];
        return typeof v === "number" && isFinite(v) ? v : undefined;
      };
      if (a.action_type === "sketch_rectangle") {
        const w = numIf("width_mm");
        const h = numIf("height_mm");
        if (w !== undefined) out.push({ name: "width", value: w, unit: "mm" });
        if (h !== undefined) out.push({ name: "height", value: h, unit: "mm" });
      } else if (a.action_type === "sketch_circle") {
        const r = numIf("radius_mm");
        if (r !== undefined) out.push({ name: "radius", value: r, unit: "mm" });
      } else if (a.action_type === "extrude" || a.action_type === "extrude_cut") {
        const d = numIf("distance_mm");
        if (d !== undefined) {
          const name = extrudeIdx === 0 ? "extrude_depth" : `extrude_depth_${extrudeIdx + 1}`;
          out.push({ name, value: d, unit: "mm" });
          extrudeIdx++;
        }
      } else if (a.action_type === "fillet") {
        const r = numIf("radius_mm");
        if (r !== undefined) {
          const name = filletIdx === 0 ? "fillet_radius" : `fillet_radius_${filletIdx + 1}`;
          out.push({ name, value: r, unit: "mm" });
          filletIdx++;
        }
      } else if (a.action_type === "chamfer") {
        const d = numIf("distance_mm");
        if (d !== undefined) {
          const name = chamferIdx === 0 ? "chamfer_distance" : `chamfer_distance_${chamferIdx + 1}`;
          out.push({ name, value: d, unit: "mm" });
          chamferIdx++;
        }
      } else if (a.action_type === "shell") {
        const t = numIf("thickness_mm");
        if (t !== undefined) out.push({ name: "shell_thickness", value: t, unit: "mm" });
      }
    }
    return out;
  }

  private estimateComplexity(
    actions: ExtractedAction[],
  ): "simple" | "moderate" | "complex" {
    const COMPLEX = new Set([
      "loft",
      "sweep",
      "shell",
      "boolean_union",
      "boolean_subtract",
      "boolean_intersect",
      "pattern_linear",
      "pattern_circular",
      "draft",
      "mirror_body",
    ]);
    let score = actions.length;
    for (const a of actions) if (COMPLEX.has(a.action_type)) score += 2;
    if (score < 5) return "simple";
    if (score < 10) return "moderate";
    return "complex";
  }

  private parseDescription(desc: string): ExtractedAction[] {
    const actions: ExtractedAction[] = [];
    const lc = desc.toLowerCase();
    let step = 1;
    const make = (
      type: ExtractedAction["action_type"],
      params: Record<string, number | string> = {},
      d = "",
    ): ExtractedAction => ({
      step_number: step++,
      timestamp_s: 0,
      action_type: type,
      operation: type,
      parameters: params,
      confidence: 1,
      description: d || type,
      keyframe_index: 0,
    });

    const boxRe = /box\s+(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)/;
    const boxM = boxRe.exec(lc);
    if (boxM) {
      const w = Number(boxM[1]);
      const h = Number(boxM[2]);
      const d = Number(boxM[3]);
      actions.push(make("sketch_create", { plane: "XY" }, "Create base sketch"));
      actions.push(
        make("sketch_rectangle", { width_mm: w, height_mm: h }, `Rectangle ${w}×${h}mm`),
      );
      actions.push(make("extrude", { distance_mm: d }, `Extrude ${d}mm`));
    }

    const cylRe = /cylinder.*?(?:diameter|dia)\s+(\d+(?:\.\d+)?).*?(?:height|tall|h)\s+(\d+(?:\.\d+)?)/;
    const cylM = cylRe.exec(lc);
    if (cylM && !boxM) {
      const dia = Number(cylM[1]);
      const ht = Number(cylM[2]);
      actions.push(make("sketch_create", { plane: "XY" }, "Create base sketch"));
      actions.push(
        make("sketch_circle", { radius_mm: dia / 2 }, `Circle radius ${dia / 2}mm`),
      );
      actions.push(make("extrude", { distance_mm: ht }, `Extrude ${ht}mm`));
    }

    const filletRe = /(?:with\s+)?(\d+(?:\.\d+)?)\s*mm?\s+fillet/;
    const fM = filletRe.exec(lc);
    if (fM) {
      actions.push(make("fillet", { radius_mm: Number(fM[1]) }, `Fillet ${fM[1]}mm`));
    }

    const chRe = /(?:with\s+)?(\d+(?:\.\d+)?)\s*mm?\s+chamfer/;
    const chM = chRe.exec(lc);
    if (chM) {
      actions.push(
        make("chamfer", { distance_mm: Number(chM[1]) }, `Chamfer ${chM[1]}mm`),
      );
    }

    return actions;
  }

  private parseCadQuery(cq: string): ExtractedAction[] {
    const actions: ExtractedAction[] = [];
    let step = 1;
    const make = (
      type: ExtractedAction["action_type"],
      params: Record<string, number | string> = {},
      d = "",
    ): ExtractedAction => ({
      step_number: step++,
      timestamp_s: 0,
      action_type: type,
      operation: type,
      parameters: params,
      confidence: 1,
      description: d || type,
      keyframe_index: 0,
    });

    const wpRe = /Workplane\(\s*["']([XYZ]{2})["']\s*\)/;
    const wpM = wpRe.exec(cq);
    const plane = wpM ? wpM[1] : "XY";

    const boxRe = /\.box\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*\)/;
    const boxM = boxRe.exec(cq);
    if (boxM) {
      const w = Number(boxM[1]);
      const h = Number(boxM[2]);
      const d = Number(boxM[3]);
      actions.push(make("sketch_create", { plane }, `Create sketch on ${plane}`));
      actions.push(
        make("sketch_rectangle", { width_mm: w, height_mm: h }, `Rectangle ${w}×${h}`),
      );
      actions.push(make("extrude", { distance_mm: d }, `Extrude ${d}`));
    }

    const circRe = /\.circle\(\s*(\d+(?:\.\d+)?)\s*\)/;
    const extRe = /\.extrude\(\s*(\d+(?:\.\d+)?)\s*\)/;
    const circM = circRe.exec(cq);
    const extM = extRe.exec(cq);
    if (circM && !boxM) {
      const r = Number(circM[1]);
      actions.push(make("sketch_create", { plane }, `Create sketch on ${plane}`));
      actions.push(make("sketch_circle", { radius_mm: r }, `Circle radius ${r}`));
      if (extM) actions.push(make("extrude", { distance_mm: Number(extM[1]) }));
    }

    const fRe = /\.fillet\(\s*(\d+(?:\.\d+)?)\s*\)/;
    const fM = fRe.exec(cq);
    if (fM) actions.push(make("fillet", { radius_mm: Number(fM[1]) }));

    const cRe = /\.chamfer\(\s*(\d+(?:\.\d+)?)\s*\)/;
    const cM = cRe.exec(cq);
    if (cM) actions.push(make("chamfer", { distance_mm: Number(cM[1]) }));

    const shRe = /\.shell\(\s*(\d+(?:\.\d+)?)\s*\)/;
    const shM = shRe.exec(cq);
    if (shM) actions.push(make("shell", { thickness_mm: Number(shM[1]) }));

    return actions;
  }

  // ── Execution ────────────────────────────────────────────────────────────

  protected async runScriptBody(
    script: { body: string; cadSystem: CADSystemId },
  ): Promise<CADExecutionResult> {
    const isMock = process.env.PRISM_CAD_MOCK === "true" || process.env.CI === "true";

    if (isMock) {
      log.debug("Fusion360CodeGeneratorEngine: mock execution mode");
      return {
        ok: true,
        log: "Mock Fusion 360 execution completed",
        durationMs: Math.floor(Math.random() * 100) + 50,
        metrics: {
          faceCount: Math.floor(Math.random() * 20) + 6,
          edgeCount: Math.floor(Math.random() * 40) + 12,
          bodyCount: 1,
          volumeMm3: Math.random() * 50000 + 1000,
        },
      };
    }

    log.info("Fusion360CodeGeneratorEngine: real execution via HTTP bridge");
    return {
      ok: false,
      error: "Real Fusion 360 execution requires HTTP add-in bridge (not configured)",
      durationMs: 0,
    };
  }
}

// ── Singleton export ─────────────────────────────────────────────────────────

export const fusion360CodeGeneratorEngine = new Fusion360CodeGeneratorEngine();
