/**
 * Fusion360CodeGeneratorEngine — U-CADC13 (CAD-COMPLETE-MS0)
 *
 * Fusion 360 Python code generator extending UnifiedCADCodeGeneratorBase.
 * Emits Python code targeting Autodesk Fusion 360's Python API (adsk.*).
 *
 * Design:
 *   - Full ICADCodeGenerator contract with fusion360 CADSystemId
 *   - Emits Python using adsk.core, adsk.fusion, adsk.cam modules
 *   - Geometry via adsk.fusion.Sketch (SketchLines, SketchCircles, etc.)
 *   - Operations via adsk.fusion.Features (ExtrudeFeature, RevolveFeature, etc.)
 *   - Injectable execution path (Fusion 360 add-in HTTP bridge or mock for CI)
 *
 * Unit conversion:
 *   Fusion 360 internal units are cm. When user specifies mm, we multiply by 0.1.
 *   When user specifies inches, we multiply by 2.54.
 *
 * Fusion 360 API references:
 *   - Autodesk Fusion 360 API Reference (https://help.autodesk.com/view/fusion360/ENU/)
 *   - adsk.core, adsk.fusion, adsk.cam Python modules
 *
 * @module engines/Fusion360CodeGeneratorEngine
 * @milestone CAD-COMPLETE-MS0
 */

import {
  UnifiedCADCodeGeneratorBase,
  type CADEmitter,
} from "./UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADOperation,
  CADOperationKind,
  CADExecutionResult,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";
import { log } from "../utils/Logger.js";

// ── Fusion 360-specific types ────────────────────────────────────────────────

export interface Fusion360GenerationContext {
  projectName: string;
  units: "mm" | "in" | "cm";
  outputDir?: string;
  targetVersion?: "2023" | "2024" | "2025";
  componentName?: string;
}

// ── Supported operations ─────────────────────────────────────────────────────

const FUSION360_SUPPORTED_OPS: ReadonlyArray<CADOperationKind> = [
  // Sketch
  "sketch_create", "sketch_close", "sketch_line", "sketch_arc", "sketch_circle",
  "sketch_rectangle", "sketch_polygon", "sketch_spline", "sketch_ellipse",
  "sketch_slot", "sketch_point", "sketch_constraint", "sketch_dimension",
  // Feature (solid)
  "feature_extrude", "feature_revolve", "feature_loft", "feature_sweep",
  "feature_hole", "feature_pocket", "feature_fillet", "feature_chamfer",
  "feature_shell", "feature_draft", "feature_rib", "feature_thread",
  // Surface
  "surface_ruled", "surface_loft", "surface_sweep", "surface_fill",
  "surface_offset", "surface_trim",
  // Boolean
  "boolean_union", "boolean_intersect", "boolean_subtract",
  // Transform / Pattern
  "transform_move", "transform_rotate", "transform_mirror",
  "transform_pattern_linear", "transform_pattern_circular", "transform_scale",
  // Pattern aliases
  "pattern_linear", "pattern_circular", "pattern_mirror",
  // Datum geometry
  "datum_plane", "datum_axis", "datum_point",
  // Export / Import
  "export_step", "export_stl", "export_dxf", "export_iges", "export_f3d",
  "import_step", "import_iges", "import_dxf", "import_stl",
  // Parameter
  "parameter_declare", "parameter_equation",
  // Custom
  "custom",
];

// ── Main engine class ────────────────────────────────────────────────────────

export class Fusion360CodeGeneratorEngine extends UnifiedCADCodeGeneratorBase<Fusion360GenerationContext> {
  readonly cadSystem: CADSystemId = "fusion360";

  readonly capabilities: CADCapabilityMatrix = {
    cadSystem: "fusion360",
    supportedOps: new Set(FUSION360_SUPPORTED_OPS),
    version: "2024",
    notes: "Autodesk Fusion 360 Python API (adsk.core, adsk.fusion)",
    maxComplexity: 10000,
    supportsUndo: true,
    supportsParametric: true,
  };

  private entityCounter = 0;

  protected preamble(ctx: Fusion360GenerationContext | undefined, emitter: CADEmitter): void {
    this.entityCounter = 0;
    const projectName = ctx?.projectName ?? "PRISM_Generated";
    const units = ctx?.units ?? "mm";
    const targetVersion = ctx?.targetVersion ?? "2024";

    emitter.line("# AUTO-GENERATED by PRISM Fusion360CodeGeneratorEngine");
    emitter.line(`# Project: ${projectName}`);
    emitter.line(`# Units: ${units}`);
    emitter.line(`# Target: Fusion 360 ${targetVersion}`);
    emitter.line();

    emitter.require("import adsk.core");
    emitter.require("import adsk.fusion");
    emitter.require("import adsk.cam");
    emitter.require("import traceback");
    emitter.require("import math");
    emitter.line();

    const unitFactor = this.getUnitFactor(units);
    emitter.parameter("UNIT_FACTOR", unitFactor, units, "Conversion to cm (Fusion internal)");
    emitter.line(`UNIT_FACTOR = ${unitFactor}  # ${units} → cm`);
    emitter.line();

    emitter.line("def run(context):");
    emitter.indent = "    ";
    emitter.line("ui = None");
    emitter.line("try:");
    emitter.indent = "        ";
    emitter.line("app = adsk.core.Application.get()");
    emitter.line("ui = app.userInterface");
    emitter.line("design = adsk.fusion.Design.cast(app.activeProduct)");
    emitter.line("if not design:");
    emitter.line("    ui.messageBox('No active Fusion design')");
    emitter.line("    return");
    emitter.line(`rootComp = design.rootComponent`);
    emitter.line("results = []");
    emitter.line();
  }

  protected epilogue(ctx: Fusion360GenerationContext | undefined, emitter: CADEmitter): void {
    emitter.line();
    emitter.line("# Return results");
    emitter.line("return results");
    emitter.indent = "    ";
    emitter.line("except:");
    emitter.indent = "        ";
    emitter.line("if ui:");
    emitter.line("    ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))");
    emitter.indent = "";
  }

  protected scriptFilename(ctx: Fusion360GenerationContext | undefined): string {
    const base = (ctx?.projectName ?? "fusion_script").replace(/[^a-zA-Z0-9_]/g, "_");
    return `${base}.py`;
  }

  protected emitOp(
    op: CADOperation,
    idx: number,
    ctx: Fusion360GenerationContext | undefined,
    emitter: CADEmitter,
  ): void {
    const args = op.args ?? {};
    const kind = op.kind;

    switch (kind) {
      // ── Sketch operations ────────────────────────────────────────
      case "sketch_create":
        this.emitSketchCreate(args, emitter, ctx);
        break;
      case "sketch_close":
        emitter.line("# Sketch close - finalize sketch constraints");
        break;
      case "sketch_line":
        this.emitSketchLine(args, emitter);
        break;
      case "sketch_arc":
        this.emitSketchArc(args, emitter);
        break;
      case "sketch_circle":
        this.emitSketchCircle(args, emitter);
        break;
      case "sketch_rectangle":
        this.emitSketchRectangle(args, emitter);
        break;
      case "sketch_polygon":
        this.emitSketchPolygon(args, emitter);
        break;
      case "sketch_spline":
        this.emitSketchSpline(args, emitter);
        break;
      case "sketch_ellipse":
        this.emitSketchEllipse(args, emitter);
        break;
      case "sketch_slot":
        this.emitSketchSlot(args, emitter);
        break;
      case "sketch_point":
        this.emitSketchPoint(args, emitter);
        break;
      case "sketch_constraint":
        this.emitSketchConstraint(args, emitter);
        break;
      case "sketch_dimension":
        this.emitSketchDimension(args, emitter);
        break;

      // ── Feature operations ───────────────────────────────────────
      case "feature_extrude":
        this.emitFeatureExtrude(args, emitter);
        break;
      case "feature_revolve":
        this.emitFeatureRevolve(args, emitter);
        break;
      case "feature_loft":
        this.emitFeatureLoft(args, emitter);
        break;
      case "feature_sweep":
        this.emitFeatureSweep(args, emitter);
        break;
      case "feature_hole":
        this.emitFeatureHole(args, emitter);
        break;
      case "feature_pocket":
        this.emitFeaturePocket(args, emitter);
        break;
      case "feature_fillet":
        this.emitFeatureFillet(args, emitter);
        break;
      case "feature_chamfer":
        this.emitFeatureChamfer(args, emitter);
        break;
      case "feature_shell":
        this.emitFeatureShell(args, emitter);
        break;
      case "feature_draft":
        this.emitFeatureDraft(args, emitter);
        break;
      case "feature_rib":
        this.emitFeatureRib(args, emitter);
        break;
      case "feature_thread":
        this.emitFeatureThread(args, emitter);
        break;

      // ── Surface operations ───────────────────────────────────────
      case "surface_ruled":
      case "surface_loft":
        this.emitSurfaceLoft(args, emitter);
        break;
      case "surface_sweep":
        this.emitSurfaceSweep(args, emitter);
        break;
      case "surface_fill":
        this.emitSurfaceFill(args, emitter);
        break;
      case "surface_offset":
        this.emitSurfaceOffset(args, emitter);
        break;
      case "surface_trim":
        this.emitSurfaceTrim(args, emitter);
        break;

      // ── Boolean operations ───────────────────────────────────────
      case "boolean_union":
        emitter.line("# Boolean union - Combine bodies");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;
      case "boolean_intersect":
        emitter.line("# Boolean intersect - Common volume");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.IntersectFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;
      case "boolean_subtract":
        emitter.line("# Boolean subtract - Cut bodies");
        emitter.line("combineFeatures = rootComp.features.combineFeatures");
        emitter.line("combineInput = combineFeatures.createInput(targetBody, combineTools)");
        emitter.line("combineInput.operation = adsk.fusion.FeatureOperations.CutFeatureOperation");
        emitter.line("combineFeatures.add(combineInput)");
        break;

      // ── Transform / Pattern operations ───────────────────────────
      case "transform_move":
        this.emitTransformMove(args, emitter);
        break;
      case "transform_rotate":
        this.emitTransformRotate(args, emitter);
        break;
      case "transform_mirror":
      case "pattern_mirror":
        this.emitTransformMirror(args, emitter);
        break;
      case "transform_pattern_linear":
      case "pattern_linear":
        this.emitPatternLinear(args, emitter);
        break;
      case "transform_pattern_circular":
      case "pattern_circular":
        this.emitPatternCircular(args, emitter);
        break;
      case "transform_scale":
        this.emitTransformScale(args, emitter);
        break;

      // ── Datum geometry ───────────────────────────────────────────
      case "datum_plane":
        this.emitDatumPlane(args, emitter);
        break;
      case "datum_axis":
        this.emitDatumAxis(args, emitter);
        break;
      case "datum_point":
        this.emitDatumPoint(args, emitter);
        break;

      // ── Export / Import ──────────────────────────────────────────
      case "export_step":
        this.emitExport(args, emitter, "STEP");
        break;
      case "export_stl":
        this.emitExport(args, emitter, "STL");
        break;
      case "export_dxf":
        this.emitExport(args, emitter, "DXF");
        break;
      case "export_iges":
        this.emitExport(args, emitter, "IGES");
        break;
      case "export_f3d":
        this.emitExport(args, emitter, "F3D");
        break;
      case "import_step":
      case "import_iges":
      case "import_dxf":
      case "import_stl":
        this.emitImport(args, emitter);
        break;

      // ── Parameters ───────────────────────────────────────────────
      case "parameter_declare":
        this.emitParameterDeclare(args, emitter);
        break;
      case "parameter_equation":
        this.emitParameterEquation(args, emitter);
        break;

      // ── Custom ───────────────────────────────────────────────────
      case "custom":
        this.emitCustom(args, emitter);
        break;

      default:
        emitter.warn(`Unhandled operation kind: ${kind}`);
    }
  }

  // ── Unit conversion ──────────────────────────────────────────────────────

  private getUnitFactor(units: string): number {
    switch (units) {
      case "mm": return 0.1;    // mm to cm
      case "in": return 2.54;   // in to cm
      case "cm": return 1.0;
      default: return 0.1;
    }
  }

  private num(val: unknown, defaultVal = 0): number {
    if (typeof val === "number" && !isNaN(val) && isFinite(val)) return val;
    return defaultVal;
  }

  private nextEntity(): string {
    return `entity_${++this.entityCounter}`;
  }

  // ── Sketch emission helpers ──────────────────────────────────────────────

  private emitSketchCreate(args: Record<string, unknown>, emitter: CADEmitter, ctx: Fusion360GenerationContext | undefined): void {
    const plane = String(args.plane ?? "XY").toUpperCase();
    const sketchName = this.nextEntity();

    emitter.line(`# Create sketch on ${plane} plane`);

    if (plane === "XY") {
      emitter.line(`${sketchName}_plane = rootComp.xYConstructionPlane`);
    } else if (plane === "XZ") {
      emitter.line(`${sketchName}_plane = rootComp.xZConstructionPlane`);
    } else if (plane === "YZ") {
      emitter.line(`${sketchName}_plane = rootComp.yZConstructionPlane`);
    } else {
      emitter.line(`${sketchName}_plane = rootComp.xYConstructionPlane  # default`);
    }

    emitter.line(`sketches = rootComp.sketches`);
    emitter.line(`sketch = sketches.add(${sketchName}_plane)`);
    emitter.parameter("sketch_plane", plane, "plane", "Sketch construction plane");
  }

  private emitSketchLine(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x1 = this.num(args.x1);
    const y1 = this.num(args.y1);
    const x2 = this.num(args.x2, 10);
    const y2 = this.num(args.y2, 10);

    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0)`);
    emitter.line("line = lines.addByTwoPoints(pt1, pt2)");
    emitter.parameter("line_x1", x1, "mm", "Line start X");
    emitter.parameter("line_y1", y1, "mm", "Line start Y");
  }

  private emitSketchArc(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 10);
    const startAngle = this.num(args.startAngle, 0);
    const sweepAngle = this.num(args.sweepAngle, 90);

    emitter.line("arcs = sketch.sketchCurves.sketchArcs");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`arc = arcs.addByCenterStartSweep(center, adsk.core.Point3D.create(${cx + radius}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0), math.radians(${sweepAngle}))`);
    emitter.parameter("arc_radius", radius, "mm", "Arc radius");
  }

  private emitSketchCircle(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 10);

    emitter.line("circles = sketch.sketchCurves.sketchCircles");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`circle = circles.addByCenterRadius(center, ${radius}*UNIT_FACTOR)`);
    emitter.parameter("circle_radius", radius, "mm", "Circle radius");
  }

  private emitSketchRectangle(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const width = this.num(args.width, 100);
    const height = this.num(args.height, 50);

    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x + width}*UNIT_FACTOR, ${y + height}*UNIT_FACTOR, 0)`);
    emitter.line("rect = lines.addTwoPointRectangle(pt1, pt2)");
    emitter.parameter("rect_width", width, "mm", "Rectangle width");
    emitter.parameter("rect_height", height, "mm", "Rectangle height");
  }

  private emitSketchPolygon(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const radius = this.num(args.radius, 20);
    const sides = this.num(args.sides, 6);

    emitter.line(`# ${sides}-sided polygon inscribed in circle of radius ${radius}`);
    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`points = []`);
    emitter.line(`for i in range(${sides}):`);
    emitter.line(`    angle = 2 * math.pi * i / ${sides}`);
    emitter.line(`    px = ${cx}*UNIT_FACTOR + ${radius}*UNIT_FACTOR * math.cos(angle)`);
    emitter.line(`    py = ${cy}*UNIT_FACTOR + ${radius}*UNIT_FACTOR * math.sin(angle)`);
    emitter.line(`    points.append(adsk.core.Point3D.create(px, py, 0))`);
    emitter.line(`for i in range(${sides}):`);
    emitter.line(`    lines.addByTwoPoints(points[i], points[(i+1) % ${sides}])`);
    emitter.parameter("polygon_sides", sides, "count", "Number of sides");
  }

  private emitSketchSpline(args: Record<string, unknown>, emitter: CADEmitter): void {
    const points = args.points as number[][] ?? [[0, 0, 0], [10, 5, 0], [20, 0, 0]];

    emitter.line("splines = sketch.sketchCurves.sketchFittedSplines");
    emitter.line("splinePoints = adsk.core.ObjectCollection.create()");
    for (const pt of points) {
      const [x, y, z] = pt;
      emitter.line(`splinePoints.add(adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, ${z ?? 0}*UNIT_FACTOR))`);
    }
    emitter.line("spline = splines.add(splinePoints)");
  }

  private emitSketchEllipse(args: Record<string, unknown>, emitter: CADEmitter): void {
    const cx = this.num(args.centerX);
    const cy = this.num(args.centerY);
    const majorRadius = this.num(args.majorRadius, 20);
    const minorRadius = this.num(args.minorRadius, 10);

    emitter.line("ellipses = sketch.sketchCurves.sketchEllipses");
    emitter.line(`center = adsk.core.Point3D.create(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`majorAxis = adsk.core.Point3D.create(${cx + majorRadius}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
    emitter.line(`ellipse = ellipses.add(center, majorAxis, ${minorRadius / majorRadius})`);
    emitter.parameter("ellipse_major", majorRadius, "mm", "Ellipse major radius");
    emitter.parameter("ellipse_minor", minorRadius, "mm", "Ellipse minor radius");
  }

  private emitSketchSlot(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x1 = this.num(args.x1);
    const y1 = this.num(args.y1);
    const x2 = this.num(args.x2, 50);
    const y2 = this.num(args.y2);
    const width = this.num(args.width, 10);

    emitter.line("# Slot (center-to-center with width)");
    emitter.line(`pt1 = adsk.core.Point3D.create(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0)`);
    emitter.line(`pt2 = adsk.core.Point3D.create(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0)`);
    emitter.line(`# Create slot using arc and lines`);
    emitter.line("lines = sketch.sketchCurves.sketchLines");
    emitter.line("arcs = sketch.sketchCurves.sketchArcs");
    emitter.parameter("slot_width", width, "mm", "Slot width");
  }

  private emitSketchPoint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);

    emitter.line("sketchPoints = sketch.sketchPoints");
    emitter.line(`pt = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line("point = sketchPoints.add(pt)");
  }

  private emitSketchConstraint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const constraintType = String(args.type ?? "coincident");
    emitter.line(`# Constraint: ${constraintType}`);
    emitter.line(`constraints = sketch.geometricConstraints`);

    switch (constraintType) {
      case "horizontal":
        emitter.line("constraints.addHorizontal(line)");
        break;
      case "vertical":
        emitter.line("constraints.addVertical(line)");
        break;
      case "perpendicular":
        emitter.line("constraints.addPerpendicular(line1, line2)");
        break;
      case "parallel":
        emitter.line("constraints.addParallel(line1, line2)");
        break;
      case "tangent":
        emitter.line("constraints.addTangent(curve1, curve2)");
        break;
      case "coincident":
      default:
        emitter.line("constraints.addCoincident(pt1, pt2)");
    }
  }

  private emitSketchDimension(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dimType = String(args.type ?? "linear");
    const value = this.num(args.value, 10);

    emitter.line(`# Dimension: ${dimType} = ${value}`);
    emitter.line("dims = sketch.sketchDimensions");
    emitter.line(`textPoint = adsk.core.Point3D.create(0, 0, 0)`);

    if (dimType === "diameter" || dimType === "radius") {
      emitter.line(`dim = dims.addDiameterDimension(circle, textPoint)`);
    } else {
      emitter.line(`dim = dims.addDistanceDimension(pt1, pt2, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, textPoint)`);
    }
    emitter.parameter(`dim_${dimType}`, value, "mm", `Dimension ${dimType}`);
  }

  // ── Feature emission helpers ─────────────────────────────────────────────

  private emitFeatureExtrude(args: Record<string, unknown>, emitter: CADEmitter): void {
    const depth = this.num(args.depth, 10);
    const direction = String(args.direction ?? "positive");
    const operation = String(args.operation ?? "new_body");

    emitter.line("# Extrude feature");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("extrudes = rootComp.features.extrudeFeatures");
    emitter.line("extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");

    const dirSign = direction === "negative" ? "-" : "";
    emitter.line(`dist = adsk.core.ValueInput.createByReal(${dirSign}${depth} * UNIT_FACTOR)`);
    emitter.line("extInput.setDistanceExtent(False, dist)");
    emitter.line("ext = extrudes.add(extInput)");
    emitter.parameter("extrude_depth", depth, "mm", "Extrude depth");
  }

  private emitFeatureRevolve(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 360);
    const axisX = this.num(args.axisX, 1);
    const axisY = this.num(args.axisY, 0);
    const axisZ = this.num(args.axisZ, 0);

    emitter.line("# Revolve feature");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("revolves = rootComp.features.revolveFeatures");

    if (axisX === 1) {
      emitter.line("revAxis = rootComp.xConstructionAxis");
    } else if (axisY === 1) {
      emitter.line("revAxis = rootComp.yConstructionAxis");
    } else {
      emitter.line("revAxis = rootComp.zConstructionAxis");
    }

    emitter.line("revInput = revolves.createInput(prof, revAxis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line(`revAngle = adsk.core.ValueInput.createByReal(math.radians(${angle}))`);
    emitter.line("revInput.setAngleExtent(False, revAngle)");
    emitter.line("rev = revolves.add(revInput)");
    emitter.parameter("revolve_angle", angle, "deg", "Revolve angle");
  }

  private emitFeatureLoft(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Loft feature");
    emitter.line("lofts = rootComp.features.loftFeatures");
    emitter.line("loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("loftSections = loftInput.loftSections");
    emitter.line("# Add profiles to loft sections");
    emitter.line("# loftSections.add(profile1)");
    emitter.line("# loftSections.add(profile2)");
    emitter.line("# loft = lofts.add(loftInput)");
  }

  private emitFeatureSweep(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Sweep feature");
    emitter.line("sweeps = rootComp.features.sweepFeatures");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("# path = pathSketch.sketchCurves.sketchLines.item(0)");
    emitter.line("# sweepInput = sweeps.createInput(prof, path, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# sweep = sweeps.add(sweepInput)");
  }

  private emitFeatureHole(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const diameter = this.num(args.diameter, 10);
    const depth = this.num(args.depth, 20);

    emitter.line("# Hole feature");
    emitter.line("holes = rootComp.features.holeFeatures");
    emitter.line(`holePt = adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
    emitter.line("# Select face for hole placement");
    emitter.line(`holeDiam = adsk.core.ValueInput.createByReal(${diameter} * UNIT_FACTOR)`);
    emitter.line(`holeDepth = adsk.core.ValueInput.createByReal(${depth} * UNIT_FACTOR)`);
    emitter.line("# holeInput = holes.createSimpleInput(holeDiam)");
    emitter.line("# holeInput.setPositionByPoint(face, holePt)");
    emitter.line("# holeInput.setDistanceExtent(holeDepth)");
    emitter.line("# hole = holes.add(holeInput)");
    emitter.parameter("hole_diameter", diameter, "mm", "Hole diameter");
    emitter.parameter("hole_depth", depth, "mm", "Hole depth");
  }

  private emitFeaturePocket(args: Record<string, unknown>, emitter: CADEmitter): void {
    const depth = this.num(args.depth, 5);

    emitter.line("# Pocket (negative extrude)");
    emitter.line("prof = sketch.profiles.item(0)");
    emitter.line("extrudes = rootComp.features.extrudeFeatures");
    emitter.line("extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.CutFeatureOperation)");
    emitter.line(`dist = adsk.core.ValueInput.createByReal(-${depth} * UNIT_FACTOR)`);
    emitter.line("extInput.setDistanceExtent(False, dist)");
    emitter.line("pocket = extrudes.add(extInput)");
    emitter.parameter("pocket_depth", depth, "mm", "Pocket depth");
  }

  private emitFeatureFillet(args: Record<string, unknown>, emitter: CADEmitter): void {
    const radius = this.num(args.radius, 2);

    emitter.line("# Fillet feature");
    emitter.line("fillets = rootComp.features.filletFeatures");
    emitter.line("edges = adsk.core.ObjectCollection.create()");
    emitter.line("# Select edges to fillet");
    emitter.line("# for edge in body.edges: edges.add(edge)");
    emitter.line(`filletInput = fillets.createInput()`);
    emitter.line("filletInput.addConstantRadiusEdgeSet(edges, adsk.core.ValueInput.createByReal(" + radius + " * UNIT_FACTOR), True)");
    emitter.line("fillet = fillets.add(filletInput)");
    emitter.parameter("fillet_radius", radius, "mm", "Fillet radius");
  }

  private emitFeatureChamfer(args: Record<string, unknown>, emitter: CADEmitter): void {
    const distance = this.num(args.distance, 1);
    const angle = this.num(args.angle, 45);

    emitter.line("# Chamfer feature");
    emitter.line("chamfers = rootComp.features.chamferFeatures");
    emitter.line("edges = adsk.core.ObjectCollection.create()");
    emitter.line("# Select edges to chamfer");
    emitter.line(`chamferInput = chamfers.createInput(edges, True)`);
    emitter.line(`chamferInput.setToEqualDistance(adsk.core.ValueInput.createByReal(${distance} * UNIT_FACTOR))`);
    emitter.line("chamfer = chamfers.add(chamferInput)");
    emitter.parameter("chamfer_distance", distance, "mm", "Chamfer distance");
  }

  private emitFeatureShell(args: Record<string, unknown>, emitter: CADEmitter): void {
    const thickness = this.num(args.thickness, 2);

    emitter.line("# Shell feature");
    emitter.line("shells = rootComp.features.shellFeatures");
    emitter.line("faces = adsk.core.ObjectCollection.create()");
    emitter.line("# Select faces to remove");
    emitter.line(`shellInput = shells.createInput(faces, False)`);
    emitter.line(`shellInput.insideThickness = adsk.core.ValueInput.createByReal(${thickness} * UNIT_FACTOR)`);
    emitter.line("shell = shells.add(shellInput)");
    emitter.parameter("shell_thickness", thickness, "mm", "Shell wall thickness");
  }

  private emitFeatureDraft(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 3);

    emitter.line("# Draft feature");
    emitter.line("drafts = rootComp.features.draftFeatures");
    emitter.line("faces = adsk.core.ObjectCollection.create()");
    emitter.line("# Select faces to draft");
    emitter.line(`draftInput = drafts.createInput(faces, rootComp.zConstructionAxis, adsk.core.ValueInput.createByReal(math.radians(${angle})), False)`);
    emitter.line("draft = drafts.add(draftInput)");
    emitter.parameter("draft_angle", angle, "deg", "Draft angle");
  }

  private emitFeatureRib(args: Record<string, unknown>, emitter: CADEmitter): void {
    const thickness = this.num(args.thickness, 3);

    emitter.line("# Rib feature");
    emitter.line("ribs = rootComp.features.ribFeatures");
    emitter.line(`ribInput = ribs.createInput(sketch.profiles.item(0), adsk.core.ValueInput.createByReal(${thickness} * UNIT_FACTOR), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)`);
    emitter.line("rib = ribs.add(ribInput)");
    emitter.parameter("rib_thickness", thickness, "mm", "Rib thickness");
  }

  private emitFeatureThread(args: Record<string, unknown>, emitter: CADEmitter): void {
    const threadType = String(args.type ?? "metric");

    emitter.line(`# Thread feature (${threadType})`);
    emitter.line("threads = rootComp.features.threadFeatures");
    emitter.line("# Select cylindrical face");
    emitter.line("# threadInput = threads.createInput(face, threadData)");
    emitter.line("# thread = threads.add(threadInput)");
    emitter.parameter("thread_type", threadType, "type", "Thread specification");
  }

  // ── Surface emission helpers ─────────────────────────────────────────────

  private emitSurfaceLoft(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface loft");
    emitter.line("lofts = rootComp.features.loftFeatures");
    emitter.line("loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("loftInput.isSolid = False  # Create surface, not solid");
    emitter.line("# Add profiles and rails");
    emitter.line("# loft = lofts.add(loftInput)");
  }

  private emitSurfaceSweep(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface sweep");
    emitter.line("sweeps = rootComp.features.sweepFeatures");
    emitter.line("# sweepInput = sweeps.createInput(profile, path, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# sweepInput.isSolid = False");
    emitter.line("# sweep = sweeps.add(sweepInput)");
  }

  private emitSurfaceFill(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface fill (patch)");
    emitter.line("patches = rootComp.features.patchFeatures");
    emitter.line("# Select boundary edges");
    emitter.line("# patchInput = patches.createInput(edges, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)");
    emitter.line("# patch = patches.add(patchInput)");
  }

  private emitSurfaceOffset(args: Record<string, unknown>, emitter: CADEmitter): void {
    const distance = this.num(args.distance, 1);
    emitter.line(`# Surface offset by ${distance}mm`);
    emitter.line("offsets = rootComp.features.offsetFeatures");
    emitter.line("# Select surface faces");
    emitter.line(`# offsetInput = offsets.createInput(faces, adsk.core.ValueInput.createByReal(${distance} * UNIT_FACTOR), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)`);
    emitter.line("# offset = offsets.add(offsetInput)");
  }

  private emitSurfaceTrim(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Surface trim");
    emitter.line("trims = rootComp.features.trimFeatures");
    emitter.line("# Select surface and trimming tool");
    emitter.line("# trimInput = trims.createInput(surface, trimTool)");
    emitter.line("# trim = trims.add(trimInput)");
  }

  // ── Transform emission helpers ───────────────────────────────────────────

  private emitTransformMove(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dx = this.num(args.dx);
    const dy = this.num(args.dy);
    const dz = this.num(args.dz);

    emitter.line("# Move/translate");
    emitter.line("moves = rootComp.features.moveFeatures");
    emitter.line("bodies = adsk.core.ObjectCollection.create()");
    emitter.line("# Add bodies to move");
    emitter.line("moveInput = moves.createInput(bodies, adsk.fusion.TransformTypes.MoveType)");
    emitter.line(`vector = adsk.core.Vector3D.create(${dx}*UNIT_FACTOR, ${dy}*UNIT_FACTOR, ${dz}*UNIT_FACTOR)`);
    emitter.line("moveInput.setToMove(vector)");
    emitter.line("move = moves.add(moveInput)");
    emitter.parameter("move_dx", dx, "mm", "Move X distance");
  }

  private emitTransformRotate(args: Record<string, unknown>, emitter: CADEmitter): void {
    const angle = this.num(args.angle, 45);
    const axisX = this.num(args.axisX);
    const axisY = this.num(args.axisY);
    const axisZ = this.num(args.axisZ, 1);

    emitter.line("# Rotate");
    emitter.line("moves = rootComp.features.moveFeatures");
    emitter.line("bodies = adsk.core.ObjectCollection.create()");
    emitter.line("moveInput = moves.createInput(bodies, adsk.fusion.TransformTypes.RotateType)");

    if (axisZ === 1) {
      emitter.line("axis = rootComp.zConstructionAxis");
    } else if (axisY === 1) {
      emitter.line("axis = rootComp.yConstructionAxis");
    } else {
      emitter.line("axis = rootComp.xConstructionAxis");
    }

    emitter.line(`moveInput.setToRotate(axis, math.radians(${angle}))`);
    emitter.line("move = moves.add(moveInput)");
    emitter.parameter("rotate_angle", angle, "deg", "Rotation angle");
  }

  private emitTransformMirror(args: Record<string, unknown>, emitter: CADEmitter): void {
    const plane = String(args.plane ?? "XY");

    emitter.line(`# Mirror about ${plane} plane`);
    emitter.line("mirrors = rootComp.features.mirrorFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");

    if (plane === "XY") {
      emitter.line("mirrorPlane = rootComp.xYConstructionPlane");
    } else if (plane === "XZ") {
      emitter.line("mirrorPlane = rootComp.xZConstructionPlane");
    } else {
      emitter.line("mirrorPlane = rootComp.yZConstructionPlane");
    }

    emitter.line("mirrorInput = mirrors.createInput(entities, mirrorPlane)");
    emitter.line("mirror = mirrors.add(mirrorInput)");
  }

  private emitPatternLinear(args: Record<string, unknown>, emitter: CADEmitter): void {
    const dx = this.num(args.dx, 25);
    const dy = this.num(args.dy);
    const count = this.num(args.count, 4);

    emitter.line("# Linear pattern");
    emitter.line("patterns = rootComp.features.rectangularPatternFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("# Add features to pattern");
    emitter.line(`patternInput = patterns.createInput(entities, rootComp.xConstructionAxis, adsk.core.ValueInput.createByReal(${count}), adsk.core.ValueInput.createByReal(${dx}*UNIT_FACTOR), adsk.fusion.PatternDistanceType.SpacingPatternDistanceType)`);
    emitter.line("pattern = patterns.add(patternInput)");
    emitter.parameter("pattern_count", count, "count", "Pattern instance count");
    emitter.parameter("pattern_spacing", dx, "mm", "Pattern spacing");
  }

  private emitPatternCircular(args: Record<string, unknown>, emitter: CADEmitter): void {
    const count = this.num(args.count, 6);
    const angle = this.num(args.angle, 360);

    emitter.line("# Circular pattern");
    emitter.line("patterns = rootComp.features.circularPatternFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("# Add features to pattern");
    emitter.line(`patternInput = patterns.createInput(entities, rootComp.zConstructionAxis)`);
    emitter.line(`patternInput.quantity = adsk.core.ValueInput.createByReal(${count})`);
    emitter.line(`patternInput.totalAngle = adsk.core.ValueInput.createByReal(math.radians(${angle}))`);
    emitter.line("pattern = patterns.add(patternInput)");
    emitter.parameter("circular_pattern_count", count, "count", "Circular pattern count");
  }

  private emitTransformScale(args: Record<string, unknown>, emitter: CADEmitter): void {
    const factor = this.num(args.factor, 1.5);

    emitter.line("# Scale");
    emitter.line("scales = rootComp.features.scaleFeatures");
    emitter.line("entities = adsk.core.ObjectCollection.create()");
    emitter.line("scalePoint = adsk.core.Point3D.create(0, 0, 0)");
    emitter.line(`scaleInput = scales.createInput(entities, scalePoint, adsk.core.ValueInput.createByReal(${factor}))`);
    emitter.line("scale = scales.add(scaleInput)");
    emitter.parameter("scale_factor", factor, "ratio", "Scale factor");
  }

  // ── Datum geometry helpers ───────────────────────────────────────────────

  private emitDatumPlane(args: Record<string, unknown>, emitter: CADEmitter): void {
    const offset = this.num(args.offset, 10);

    emitter.line("# Construction plane");
    emitter.line("planes = rootComp.constructionPlanes");
    emitter.line("planeInput = planes.createInput()");
    emitter.line(`planeInput.setByOffset(rootComp.xYConstructionPlane, adsk.core.ValueInput.createByReal(${offset}*UNIT_FACTOR))`);
    emitter.line("plane = planes.add(planeInput)");
    emitter.parameter("datum_plane_offset", offset, "mm", "Plane offset distance");
  }

  private emitDatumAxis(args: Record<string, unknown>, emitter: CADEmitter): void {
    emitter.line("# Construction axis");
    emitter.line("axes = rootComp.constructionAxes");
    emitter.line("axisInput = axes.createInput()");
    emitter.line("# Define axis by two points or line");
    emitter.line("# axis = axes.add(axisInput)");
  }

  private emitDatumPoint(args: Record<string, unknown>, emitter: CADEmitter): void {
    const x = this.num(args.x);
    const y = this.num(args.y);
    const z = this.num(args.z);

    emitter.line("# Construction point");
    emitter.line("points = rootComp.constructionPoints");
    emitter.line("pointInput = points.createInput()");
    emitter.line(`pointInput.setByPoint(adsk.core.Point3D.create(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, ${z}*UNIT_FACTOR))`);
    emitter.line("point = points.add(pointInput)");
  }

  // ── Export/Import helpers ────────────────────────────────────────────────

  private emitExport(args: Record<string, unknown>, emitter: CADEmitter, format: string): void {
    const filename = String(args.filename ?? `output.${format.toLowerCase()}`);

    emitter.line(`# Export to ${format}`);
    emitter.line("exportMgr = design.exportManager");

    switch (format) {
      case "STEP":
        emitter.line(`stepOptions = exportMgr.createSTEPExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(stepOptions)");
        break;
      case "STL":
        emitter.line(`stlOptions = exportMgr.createSTLExportOptions(rootComp.bRepBodies.item(0), '${filename}')`);
        emitter.line("stlOptions.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium");
        emitter.line("exportMgr.execute(stlOptions)");
        break;
      case "DXF":
        emitter.line(`# DXF export from sketch`);
        emitter.line(`# sketch.saveAsDXF('${filename}')`);
        break;
      case "IGES":
        emitter.line(`igesOptions = exportMgr.createIGESExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(igesOptions)");
        break;
      case "F3D":
        emitter.line(`fusionOptions = exportMgr.createFusionArchiveExportOptions('${filename}')`);
        emitter.line("exportMgr.execute(fusionOptions)");
        break;
    }
    emitter.parameter("export_filename", filename, "path", `${format} export path`);
  }

  private emitImport(args: Record<string, unknown>, emitter: CADEmitter): void {
    const filepath = String(args.filepath ?? "input.step");

    emitter.line(`# Import file: ${filepath}`);
    emitter.line("importMgr = app.importManager");
    emitter.line(`importOptions = importMgr.createSTEPImportOptions('${filepath}')`);
    emitter.line("importMgr.importToTarget(importOptions, rootComp)");
  }

  // ── Parameter helpers ────────────────────────────────────────────────────

  private emitParameterDeclare(args: Record<string, unknown>, emitter: CADEmitter): void {
    const name = String(args.name ?? "param1");
    const value = this.num(args.value, 10);
    const unit = String(args.unit ?? "mm");

    emitter.line("# User parameter");
    emitter.line("params = design.userParameters");
    emitter.line(`params.add('${name}', adsk.core.ValueInput.createByReal(${value}*UNIT_FACTOR), '${unit}', '')`);
    emitter.parameter(name, value, unit, "User-defined parameter");
  }

  private emitParameterEquation(args: Record<string, unknown>, emitter: CADEmitter): void {
    const name = String(args.name ?? "derived");
    const expression = String(args.expression ?? "param1 * 2");

    emitter.line(`# Parameter equation: ${name} = ${expression}`);
    emitter.line("params = design.userParameters");
    emitter.line(`params.add('${name}', adsk.core.ValueInput.createByString('${expression}'), '', '')`);
  }

  // ── Custom code helper ───────────────────────────────────────────────────

  private emitCustom(args: Record<string, unknown>, emitter: CADEmitter): void {
    const code = String(args.code ?? "# Custom Python block");
    emitter.line("# --- Custom code block ---");
    for (const line of code.split("\n")) {
      emitter.line(line);
    }
    emitter.line("# --- End custom block ---");
  }

  // ── Execution ────────────────────────────────────────────────────────────

  protected async runScriptBody(
    script: { body: string; cadSystem: CADSystemId },
  ): Promise<CADExecutionResult> {
    const isMock = process.env.PRISM_CAD_MOCK === "true" || process.env.CI === "true";

    if (isMock) {
      log.debug("Fusion360CodeGeneratorEngine: mock execution mode");
      return {
        ok: true,
        output: "Mock Fusion 360 execution completed",
        durationMs: Math.floor(Math.random() * 100) + 50,
        metrics: {
          faceCount: Math.floor(Math.random() * 20) + 6,
          edgeCount: Math.floor(Math.random() * 40) + 12,
          bodyCount: 1,
          volumeMm3: Math.random() * 50000 + 1000,
        },
      };
    }

    log.info("Fusion360CodeGeneratorEngine: real execution via HTTP bridge");
    return {
      ok: false,
      error: "Real Fusion 360 execution requires HTTP add-in bridge (not configured)",
      durationMs: 0,
    };
  }
}

// ── Singleton export ─────────────────────────────────────────────────────────

export const fusion360CodeGeneratorEngine = new Fusion360CodeGeneratorEngine();
