/**
 * HyperCADSStockModelEngine — Automated Stock Model Creation via AC Python (E1162)
 *
 * Generates hyperMILL Automation Center Python scripts for stock model creation:
 *   - bounding_box: Axis-aligned bounding box stock with uniform offset
 *   - offset_solid: Offset solid from part body with configurable axial/radial allowances
 *   - cylinder: Cylindrical stock from OD with configurable length
 *
 * Default stock allowance is 2.0mm per PRISM standard (no USB key needed for generation).
 * The hyperCADS-import-validation hook is registered here to fire before CAM operations.
 *
 * @engine HyperCADSStockModelEngine
 * @shortcode E1162
 * @dispatcher camDispatcher
 * @actions cam_hyperCADS_stock_model
 * @milestone HM-REV-MS0 / U-HMR03
 */

import { hookExecutor } from "./HookExecutor.js";
import {
  type HookDefinition,
  type HookContext,
  hookSuccess,
  hookWarning,
} from "./HookExecutor.js";

// ─── Stock Allowance Constant ─────────────────────────────────────────────────

/**
 * Default stock offset allowance in mm.
 * Source: PRISM manufacturing standard — conservative finishing allowance for
 * milled parts. Gives 2mm material on all faces for final finish passes.
 * Common range: 1–3mm for typical CNC milling stock.
 */
export const DEFAULT_STOCK_ALLOWANCE_MM = 2.0;

// ─── Types ────────────────────────────────────────────────────────────────────

/** Stock model generation mode */
export type StockMode = "bounding_box" | "offset_solid" | "cylinder";

/** Bounding box stock parameters */
export interface BoundingBoxStockParams {
  mode: "bounding_box";
  /** Part body name to envelope */
  body_name?: string;
  /** Uniform offset on all sides in mm (default: DEFAULT_STOCK_ALLOWANCE_MM = 2.0) */
  offset_mm?: number;
  /** Stock model name */
  stock_name?: string;
}

/** Offset solid stock parameters */
export interface OffsetSolidStockParams {
  mode: "offset_solid";
  /** Part body name to offset */
  body_name?: string;
  /** Axial (Z) allowance in mm (default: DEFAULT_STOCK_ALLOWANCE_MM = 2.0) */
  axial_allowance_mm?: number;
  /** Radial (XY) allowance in mm (default: DEFAULT_STOCK_ALLOWANCE_MM = 2.0) */
  radial_allowance_mm?: number;
  /** Stock model name */
  stock_name?: string;
}

/** Cylinder stock parameters */
export interface CylinderStockParams {
  mode: "cylinder";
  /** Outer diameter (OD) of cylinder stock in mm */
  od_mm: number;
  /** Total length of cylinder stock in mm */
  length_mm: number;
  /** Center axis: "X" | "Y" | "Z" (default "Z") */
  axis?: "X" | "Y" | "Z";
  /** Stock model name */
  stock_name?: string;
  /** Material name (for hyperCAD-S material assignment) */
  material?: string;
}

export type StockModelParams =
  | BoundingBoxStockParams
  | OffsetSolidStockParams
  | CylinderStockParams;

/** Stock model script result */
export interface StockModelResult {
  /** Generated AC Python script */
  script: string;
  /** Number of script lines */
  line_count: number;
  /** Stock generation mode used */
  mode: StockMode;
  /** Offset allowance applied in mm */
  allowance_mm: number;
  /** Stock model name assigned */
  stock_name: string;
  /** Warnings */
  warnings: string[];
  /** Mock mode flag */
  mock_mode: boolean;
}

// ─── Script Header ────────────────────────────────────────────────────────────

function buildHeader(mode: StockMode): string[] {
  return [
    "# hyperCAD-S Automation Center Script — Stock Model Creation",
    "# Generated by PRISM HyperCADSStockModelEngine (E1162)",
    `# Mode: ${mode}`,
    "# hyperMILL v33.0 / hyperCAD-S 2024",
    "",
    "import hm",
    "",
  ];
}

// ─── Script Builders ──────────────────────────────────────────────────────────

function buildBoundingBoxScript(p: BoundingBoxStockParams): { lines: string[]; allowance: number; stockName: string } {
  const bodyName = p.body_name ?? "imported_part";
  const offset = p.offset_mm ?? DEFAULT_STOCK_ALLOWANCE_MM;
  const stockName = p.stock_name ?? "stock_bounding_box";

  const lines = [
    `# --- Bounding Box Stock (offset: ${offset}mm on all sides) ---`,
    `# DEFAULT_STOCK_ALLOWANCE_MM = ${DEFAULT_STOCK_ALLOWANCE_MM}mm`,
    `hm.SelectBody(Name="${bodyName}")`,
    `bbox = hm.GetBodyBoundingBox(BodyName="${bodyName}")`,
    `if bbox is None:`,
    `    raise RuntimeError(f"Cannot compute bounding box for body: ${bodyName}")`,
    "",
    `# Expand bounding box by offset on all sides`,
    `stock_result = hm.CreateBoxStock(`,
    `    XMin=bbox["xmin"] - ${offset},`,
    `    XMax=bbox["xmax"] + ${offset},`,
    `    YMin=bbox["ymin"] - ${offset},`,
    `    YMax=bbox["ymax"] + ${offset},`,
    `    ZMin=bbox["zmin"] - ${offset},`,
    `    ZMax=bbox["zmax"] + ${offset},`,
    `    StockName="${stockName}",`,
    `)`,
    `hm.SetActiveStock(StockName="${stockName}")`,
    `print(f"[PRISM] Bounding box stock created: ${stockName} (offset={offset}mm)")`,
    `print(f"[PRISM] Stock dims: X={bbox['xmax']-bbox['xmin']+${2*offset}:.1f} Y={bbox['ymax']-bbox['ymin']+${2*offset}:.1f} Z={bbox['zmax']-bbox['zmin']+${2*offset}:.1f}mm")`,
  ];

  return { lines, allowance: offset, stockName };
}

function buildOffsetSolidScript(p: OffsetSolidStockParams): { lines: string[]; allowance: number; stockName: string } {
  const bodyName = p.body_name ?? "imported_part";
  const axialAllowance = p.axial_allowance_mm ?? DEFAULT_STOCK_ALLOWANCE_MM;
  const radialAllowance = p.radial_allowance_mm ?? DEFAULT_STOCK_ALLOWANCE_MM;
  const stockName = p.stock_name ?? "stock_offset_solid";

  const lines = [
    `# --- Offset Solid Stock (axial: ${axialAllowance}mm, radial: ${radialAllowance}mm) ---`,
    `# DEFAULT_STOCK_ALLOWANCE_MM = ${DEFAULT_STOCK_ALLOWANCE_MM}mm`,
    `hm.SelectBody(Name="${bodyName}")`,
    "",
    `# Create offset solid stock`,
    `stock_result = hm.CreateOffsetSolidStock(`,
    `    BodyName="${bodyName}",`,
    `    AxialAllowance=${axialAllowance},`,
    `    RadialAllowance=${radialAllowance},`,
    `    StockName="${stockName}",`,
    `)`,
    `if stock_result is None:`,
    `    raise RuntimeError("CreateOffsetSolidStock failed — body may have open faces")`,
    `hm.SetActiveStock(StockName="${stockName}")`,
    `print(f"[PRISM] Offset solid stock created: ${stockName}")`,
    `print(f"[PRISM] Axial allowance: ${axialAllowance}mm | Radial allowance: ${radialAllowance}mm")`,
  ];

  // Return the smaller of axial/radial for the generic allowance field
  const allowance = Math.min(axialAllowance, radialAllowance);
  return { lines, allowance, stockName };
}

function buildCylinderScript(p: CylinderStockParams): { lines: string[]; allowance: number; stockName: string } {
  const axis = p.axis ?? "Z";
  const stockName = p.stock_name ?? "stock_cylinder";
  const material = p.material ?? "";

  const lines = [
    `# --- Cylinder Stock (OD: ${p.od_mm}mm, Length: ${p.length_mm}mm, Axis: ${axis}) ---`,
    `stock_result = hm.CreateCylinderStock(`,
    `    Diameter=${p.od_mm},`,
    `    Length=${p.length_mm},`,
    `    Axis="${axis}",`,
    `    StockName="${stockName}",`,
    `)`,
    `if stock_result is None:`,
    `    raise RuntimeError("CreateCylinderStock failed — check diameter and length values")`,
    `hm.SetActiveStock(StockName="${stockName}")`,
  ];

  if (material) {
    lines.push(
      `hm.AssignStockMaterial(StockName="${stockName}", Material="${material}")`,
      `print(f"[PRISM] Material assigned: ${material}")`,
    );
  }

  lines.push(
    `print(f"[PRISM] Cylinder stock created: ${stockName} (OD=${p.od_mm}mm, L=${p.length_mm}mm, axis=${axis})")`,
  );

  return { lines, allowance: 0, stockName };
}

// ─── Engine Class ──────────────────────────────────────────────────────────────

/**
 * HyperCADSStockModelEngine — generates AC Python scripts for stock model creation.
 *
 * Three modes: bounding_box | offset_solid | cylinder.
 * Default stock allowance: DEFAULT_STOCK_ALLOWANCE_MM = 2.0mm.
 */
export class HyperCADSStockModelEngine {
  private generationCount = 0;

  /**
   * Generate stock model script for the specified mode.
   *
   * @param params - Stock model parameters (mode + mode-specific fields)
   * @returns StockModelResult with AC Python script
   */
  generateStockScript(params: StockModelParams): StockModelResult {
    this.generationCount++;
    const warnings: string[] = [];

    const header = buildHeader(params.mode);
    let body: { lines: string[]; allowance: number; stockName: string };

    switch (params.mode) {
      case "bounding_box":
        body = buildBoundingBoxScript(params);
        break;
      case "offset_solid":
        body = buildOffsetSolidScript(params);
        if ((params.axial_allowance_mm ?? DEFAULT_STOCK_ALLOWANCE_MM) > 10) {
          warnings.push("axial_allowance_mm > 10mm — unusually large stock allowance");
        }
        if ((params.radial_allowance_mm ?? DEFAULT_STOCK_ALLOWANCE_MM) > 10) {
          warnings.push("radial_allowance_mm > 10mm — unusually large stock allowance");
        }
        break;
      case "cylinder":
        body = buildCylinderScript(params);
        if (params.od_mm <= 0) {
          warnings.push("od_mm must be > 0");
        }
        if (params.length_mm <= 0) {
          warnings.push("length_mm must be > 0");
        }
        break;
    }

    const allLines = [...header, ...body.lines, "", `print("[PRISM] Stock model engine complete")`];
    const script = allLines.join("\n");

    return {
      script,
      line_count: allLines.length,
      mode: params.mode,
      allowance_mm: body.allowance,
      stock_name: body.stockName,
      warnings,
      mock_mode: process.env["HYPERMILL_MOCK"] === "true",
    };
  }

  /** Return generation count */
  getGenerationCount(): number {
    return this.generationCount;
  }
}

/** Singleton export */
export const hyperCADSStockModelEngine = new HyperCADSStockModelEngine();

// ─── hyperCADS-import-validation Hook ────────────────────────────────────────

/**
 * hyperCADS-import-validation — warns when a CAM operation runs without stock model.
 *
 * Fires at pre-toolpath phase. Reads ctx.target.data for stock_model_set flag.
 * Warns (non-blocking) if stock model was not assigned before CAM operations.
 *
 * Source: hyperMILL Best Practice Guide v33 — stock model required before toolpath gen.
 */
const hyperCADSImportValidation: HookDefinition = {
  id: "hyperCADS-import-validation",
  name: "hyperCAD-S Import Validation",
  description:
    "Warns when a CAM operation targets a part without a confirmed stock model. " +
    "Stock model ensures correct rest material tracking and toolpath boundaries. " +
    "Run HyperCADSStockModelEngine before generating toolpaths.",
  phase: "pre-toolpath",
  category: "validation",
  mode: "warning",
  priority: "high",
  enabled: true,
  tags: ["hypermill", "hyperCADS", "stock-model", "import-validation", "HM-REV-MS0"],
  handler: (ctx: HookContext) => {
    const d = (ctx.target?.data ?? {}) as Record<string, unknown>;

    const stockModelSet: unknown = d["stock_model_set"] ?? d["stockModelSet"];
    const operationType: unknown = d["operation_type"] ?? d["operationType"] ?? "";

    // Only check for CAM operations (not pure CAD import/heal)
    const isCAMOp =
      typeof operationType === "string" &&
      !["hyperCADS_import", "hyperCADS_heal", "hyperCADS_analyze"].includes(operationType);

    if (!isCAMOp) {
      return hookSuccess(hyperCADSImportValidation, "Non-CAM operation — stock model check skipped");
    }

    if (stockModelSet === true) {
      return hookSuccess(hyperCADSImportValidation, "Stock model confirmed set before CAM operation");
    }

    return hookWarning(
      hyperCADSImportValidation,
      "No stock model set before CAM operation. Run cam_hyperCADS_stock_model first for " +
      "accurate rest material tracking. Default allowance: " + DEFAULT_STOCK_ALLOWANCE_MM + "mm.",
    );
  },
};

/**
 * Register all HyperCADS hooks with the global hookExecutor.
 * Call this once at server startup.
 */
export function registerHyperCADSHooks(): void {
  hookExecutor.registerMany([hyperCADSImportValidation]);
}

// Auto-register on module load
registerHyperCADSHooks();
