/**
 * HyperCADSCodeGeneratorEngine — U-CADC12 (CAD-COMPLETE-MS0)
 *
 * hyperCAD-S Python code generator extending UnifiedCADCodeGeneratorBase.
 * Emits Python code targeting hyperCAD-S Automation API (Open Mind hyperMILL suite).
 *
 * Design:
 *   - Full ICADCodeGenerator contract with hypercads CADSystemId
 *   - Emits Python using hyperCAD-S automation modules
 *   - Geometry via hcad.geometry (Point, Line, Arc, Spline, Surface)
 *   - Operations via hcad.modeling (Extrude, Revolve, Boolean, etc.)
 *   - Injectable execution path (subprocess Python or mock for CI)
 *
 * hyperCAD-S API references:
 *   - hyperCAD-S 2024 Automation Guide
 *   - hcad.* Python modules
 *
 * @module engines/HyperCADSCodeGeneratorEngine
 * @milestone CAD-COMPLETE-MS0
 */

import {
  UnifiedCADCodeGeneratorBase,
  type CADEmitter,
} from "./UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADOperation,
  CADOperationKind,
  CADExecutionResult,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";
import { log } from "../utils/Logger.js";

// ── hyperCAD-S-specific types ────────────────────────────────────────────────

export interface HyperCADSGenerationContext {
  projectName: string;
  units: "mm" | "in";
  outputDir?: string;
  targetVersion?: "2023" | "2024" | "2025";
}

// ── Supported operations ─────────────────────────────────────────────────────

const HYPERCADS_SUPPORTED_OPS: ReadonlyArray<CADOperationKind> = [
  "sketch_create", "sketch_close", "sketch_line", "sketch_arc", "sketch_circle",
  "sketch_rectangle", "sketch_polygon", "sketch_spline", "sketch_ellipse",
  "sketch_slot", "sketch_point", "sketch_constraint", "sketch_dimension",
  "feature_extrude", "feature_revolve", "feature_loft", "feature_sweep",
  "feature_hole", "feature_pocket", "feature_fillet", "feature_chamfer",
  "feature_shell", "feature_draft", "feature_rib", "feature_thread",
  "surface_ruled", "surface_loft", "surface_sweep", "surface_fill",
  "surface_offset", "surface_trim",
  "boolean_union", "boolean_intersect", "boolean_subtract",
  "transform_move", "transform_rotate", "transform_mirror",
  "transform_pattern_linear", "transform_pattern_circular", "transform_scale",
  "export_step", "export_stl", "export_dxf", "export_iges",
  "import_step", "import_iges", "import_dxf",
];

// ── Main engine class ────────────────────────────────────────────────────────

export class HyperCADSCodeGeneratorEngine extends UnifiedCADCodeGeneratorBase<HyperCADSGenerationContext> {
  readonly cadSystem: CADSystemId = "hypercad_s";

  readonly capabilities: CADCapabilityMatrix = {
    cadSystem: "hypercad_s",
    supportedOps: new Set(HYPERCADS_SUPPORTED_OPS),
    // emit code converts all coords to mm (UNIT_FACTOR = in?25.4:1.0, "Conversion to mm");
    // angles emitted raw in degrees (mod.rotate/revolve/chamfer). Python hcad API → subprocess.
    nativeLengthUnit: "mm",
    nativeAngleUnit: "deg",
    requiresSubprocess: true,
    typicalLatencyMs: 1500,
    version: "2024",
    notes: "hyperCAD-S Python Automation API targeting hyperMILL 2024+",
    maxComplexity: 5000,
    supportsUndo: true,
    supportsParametric: true,
  };

  private entityCounter = 0;

  protected preamble(ctx: HyperCADSGenerationContext | undefined, emitter: CADEmitter): void {
    this.entityCounter = 0;
    emitter.line("# AUTO-GENERATED by PRISM HyperCADSCodeGeneratorEngine");
    emitter.line(`# Project: ${ctx?.projectName ?? "PRISM_Generated"}`);
    emitter.line(`# Units: ${ctx?.units ?? "mm"}`);
    emitter.line(`# Target: hyperCAD-S ${ctx?.targetVersion ?? "2024"}`);
    emitter.line();
    emitter.require("import hcad");
    emitter.require("import hcad.geometry as geo");
    emitter.require("import hcad.modeling as mod");
    emitter.require("import hcad.io as io");
    emitter.require("import math");
    emitter.line();
    const unitFactor = ctx?.units === "in" ? 25.4 : 1.0;
    emitter.parameter("UNIT_FACTOR", unitFactor, ctx?.units ?? "mm", "Conversion to mm");
    emitter.line(`UNIT_FACTOR = ${unitFactor}  # ${ctx?.units ?? "mm"} mode`);
    emitter.line();
    emitter.line("def main():");
    emitter.indent = "    ";
    emitter.line("results = []");
    emitter.line("try:");
    emitter.indent = "        ";
  }

  protected emitOp(op: CADOperation, opIndex: number, ctx: HyperCADSGenerationContext | undefined, emitter: CADEmitter): void {
    emitter.line(`# Op ${opIndex}: ${op.kind}`);
    switch (op.kind) {
      case "sketch_create": this.emitSketchCreate(op, emitter); break;
      case "sketch_close": emitter.line("hcad.close_sketch()"); break;
      case "sketch_line": this.emitSketchLine(op, emitter); break;
      case "sketch_arc": this.emitSketchArc(op, emitter); break;
      case "sketch_circle": this.emitSketchCircle(op, emitter); break;
      case "sketch_rectangle": this.emitSketchRectangle(op, emitter); break;
      case "sketch_polygon": this.emitSketchPolygon(op, emitter); break;
      case "sketch_spline": this.emitSketchSpline(op, emitter); break;
      case "sketch_ellipse": this.emitSketchEllipse(op, emitter); break;
      case "sketch_slot": this.emitSketchSlot(op, emitter); break;
      case "sketch_point": this.emitSketchPoint(op, emitter); break;
      case "sketch_constraint": emitter.line(`# Constraint: ${op.args.type ?? "geometric"}`); break;
      case "sketch_dimension": emitter.line(`# Dimension: ${op.args.name ?? "dim"} = ${op.args.value ?? 0}`); break;
      case "feature_extrude": this.emitFeatureExtrude(op, emitter); break;
      case "feature_revolve": this.emitFeatureRevolve(op, emitter); break;
      case "feature_loft": emitter.line("mod.loft(hcad.get_selected_profiles())"); break;
      case "feature_sweep": emitter.line("mod.sweep(hcad.get_profile(), hcad.get_path())"); break;
      case "feature_hole": this.emitFeatureHole(op, emitter); break;
      case "feature_pocket": this.emitFeaturePocket(op, emitter); break;
      case "feature_fillet": this.emitFeatureFillet(op, emitter); break;
      case "feature_chamfer": this.emitFeatureChamfer(op, emitter); break;
      case "feature_shell": emitter.line(`mod.shell(${(op.args.thickness as number) ?? 2} * UNIT_FACTOR)`); break;
      case "feature_draft": emitter.line(`mod.draft(${(op.args.angle as number) ?? 3})`); break;
      case "feature_rib": emitter.line(`mod.rib(${(op.args.thickness as number) ?? 3} * UNIT_FACTOR)`); break;
      case "feature_thread": emitter.line(`mod.cosmetic_thread(${(op.args.pitch as number) ?? 1.5} * UNIT_FACTOR)`); break;
      case "surface_ruled": emitter.line("mod.ruled_surface(hcad.get_curves())"); break;
      case "surface_loft": emitter.line("mod.loft_surface(hcad.get_profiles())"); break;
      case "surface_sweep": emitter.line("mod.sweep_surface(hcad.get_profile(), hcad.get_path())"); break;
      case "surface_fill": emitter.line("mod.fill_surface(hcad.get_boundary())"); break;
      case "surface_offset": emitter.line(`mod.offset_surface(${(op.args.distance as number) ?? 2} * UNIT_FACTOR)`); break;
      case "surface_trim": emitter.line("mod.trim_surface(hcad.get_surface(), hcad.get_boundary())"); break;
      case "boolean_union": emitter.line("mod.boolean_add()"); break;
      case "boolean_intersect": emitter.line("mod.boolean_common()"); break;
      case "boolean_subtract": emitter.line("mod.boolean_subtract()"); break;
      case "transform_move": this.emitTransformMove(op, emitter); break;
      case "transform_rotate": this.emitTransformRotate(op, emitter); break;
      case "transform_mirror": emitter.line(`mod.mirror(geo.Vector(${op.args.planeNormalX ?? 1}, ${op.args.planeNormalY ?? 0}, ${op.args.planeNormalZ ?? 0}))`); break;
      case "transform_pattern_linear": this.emitPatternLinear(op, emitter); break;
      case "transform_pattern_circular": this.emitPatternCircular(op, emitter); break;
      case "transform_scale": emitter.line(`mod.scale(${(op.args.factor as number) ?? 2})`); break;
      case "export_step": this.emitExport(op, emitter, ctx, "STEP"); break;
      case "export_stl": this.emitExport(op, emitter, ctx, "STL"); break;
      case "export_dxf": this.emitExport(op, emitter, ctx, "DXF"); break;
      case "export_iges": this.emitExport(op, emitter, ctx, "IGES"); break;
      case "import_step": case "import_iges": case "import_dxf":
        emitter.line(`io.open("${op.args.filepath ?? "import.step"}")`); break;
      default: emitter.warn(`Unsupported: ${op.kind}`, "error");
    }
    emitter.line();
  }

  private emitSketchCreate(op: CADOperation, emitter: CADEmitter): void {
    const plane = op.args.plane as string ?? "XY";
    emitter.line(`hcad.create_sketch(plane="${plane}")`);
  }

  private emitSketchLine(op: CADOperation, emitter: CADEmitter): void {
    const [x1, y1, z1] = [op.args.x1 as number ?? 0, op.args.y1 as number ?? 0, op.args.z1 as number ?? 0];
    const [x2, y2, z2] = [op.args.x2 as number ?? 10, op.args.y2 as number ?? 0, op.args.z2 as number ?? 0];
    const v = `line_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Line(geo.Point(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, ${z1}*UNIT_FACTOR), geo.Point(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, ${z2}*UNIT_FACTOR))`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchArc(op: CADOperation, emitter: CADEmitter): void {
    const [cx, cy, cz] = [op.args.centerX as number ?? 0, op.args.centerY as number ?? 0, op.args.centerZ as number ?? 0];
    const r = op.args.radius as number ?? 10;
    const [sa, ea] = [op.args.startAngle as number ?? 0, op.args.endAngle as number ?? 90];
    const v = `arc_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Arc(geo.Point(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, ${cz}*UNIT_FACTOR), ${r}*UNIT_FACTOR, ${sa}, ${ea})`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchCircle(op: CADOperation, emitter: CADEmitter): void {
    const [cx, cy, cz] = [op.args.centerX as number ?? 0, op.args.centerY as number ?? 0, op.args.centerZ as number ?? 0];
    const r = op.args.radius as number ?? 10;
    const v = `circle_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Circle(geo.Point(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, ${cz}*UNIT_FACTOR), ${r}*UNIT_FACTOR)`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchRectangle(op: CADOperation, emitter: CADEmitter): void {
    const [x, y, w, h] = [op.args.x as number ?? 0, op.args.y as number ?? 0, op.args.width as number ?? 10, op.args.height as number ?? 10];
    const v = `rect_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Rectangle(geo.Point(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0), ${w}*UNIT_FACTOR, ${h}*UNIT_FACTOR)`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchPolygon(op: CADOperation, emitter: CADEmitter): void {
    const [cx, cy] = [op.args.centerX as number ?? 0, op.args.centerY as number ?? 0];
    const [r, s] = [op.args.radius as number ?? 10, op.args.sides as number ?? 6];
    const v = `poly_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Polygon(geo.Point(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0), ${r}*UNIT_FACTOR, ${s})`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchSpline(op: CADOperation, emitter: CADEmitter): void {
    const pts = (op.args.points as unknown as ReadonlyArray<ReadonlyArray<number>>) ?? [[0,0,0],[10,5,0],[20,0,0]];
    const v = `spline_${this.entityCounter++}`;
    const ptStr = pts.map(p => `geo.Point(${p[0]??0}*UNIT_FACTOR, ${p[1]??0}*UNIT_FACTOR, ${p[2]??0}*UNIT_FACTOR)`).join(", ");
    emitter.line(`${v} = geo.Spline([${ptStr}])`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchEllipse(op: CADOperation, emitter: CADEmitter): void {
    const [cx, cy] = [op.args.centerX as number ?? 0, op.args.centerY as number ?? 0];
    const [maj, min] = [op.args.majorRadius as number ?? 20, op.args.minorRadius as number ?? 10];
    const v = `ellipse_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Ellipse(geo.Point(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0), ${maj}*UNIT_FACTOR, ${min}*UNIT_FACTOR)`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchSlot(op: CADOperation, emitter: CADEmitter): void {
    const [x1, y1, x2, y2, w] = [op.args.x1 as number ?? 0, op.args.y1 as number ?? 0, op.args.x2 as number ?? 20, op.args.y2 as number ?? 0, op.args.width as number ?? 10];
    const v = `slot_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Slot(geo.Point(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0), geo.Point(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0), ${w}*UNIT_FACTOR)`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitSketchPoint(op: CADOperation, emitter: CADEmitter): void {
    const [x, y, z] = [op.args.x as number ?? 0, op.args.y as number ?? 0, op.args.z as number ?? 0];
    const v = `pt_${this.entityCounter++}`;
    emitter.line(`${v} = geo.Point(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, ${z}*UNIT_FACTOR)`);
    emitter.line(`hcad.add_entity(${v})`);
  }

  private emitFeatureExtrude(op: CADOperation, emitter: CADEmitter): void {
    const d = op.args.depth as number ?? 10;
    const dir = op.args.direction as string ?? "positive";
    const sign = dir === "negative" ? -1 : 1;
    emitter.line(`mod.extrude(${d * sign} * UNIT_FACTOR)`);
    emitter.parameter("extrude_depth", d, "mm", "Extrusion depth");
  }

  private emitFeatureRevolve(op: CADOperation, emitter: CADEmitter): void {
    const angle = op.args.angle as number ?? 360;
    const [ax, ay, az] = [op.args.axisX as number ?? 0, op.args.axisY as number ?? 0, op.args.axisZ as number ?? 1];
    emitter.line(`mod.revolve(${angle}, geo.Vector(${ax}, ${ay}, ${az}))`);
  }

  private emitFeatureHole(op: CADOperation, emitter: CADEmitter): void {
    const [x, y, d, depth] = [op.args.x as number ?? 0, op.args.y as number ?? 0, op.args.diameter as number ?? 10, op.args.depth as number ?? 20];
    emitter.line(`mod.drill_hole(geo.Point(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0), ${d}*UNIT_FACTOR, ${depth}*UNIT_FACTOR)`);
    emitter.parameter("hole_diameter", d, "mm", "Hole diameter");
  }

  private emitFeaturePocket(op: CADOperation, emitter: CADEmitter): void {
    const d = op.args.depth as number ?? 10;
    emitter.line(`mod.pocket(${d} * UNIT_FACTOR)`);
  }

  private emitFeatureFillet(op: CADOperation, emitter: CADEmitter): void {
    const r = op.args.radius as number ?? 2;
    emitter.line(`mod.fillet(${r} * UNIT_FACTOR)`);
  }

  private emitFeatureChamfer(op: CADOperation, emitter: CADEmitter): void {
    const [dist, angle] = [op.args.distance as number ?? 2, op.args.angle as number ?? 45];
    emitter.line(`mod.chamfer(${dist} * UNIT_FACTOR, ${angle})`);
  }

  private emitTransformMove(op: CADOperation, emitter: CADEmitter): void {
    const [dx, dy, dz] = [op.args.dx as number ?? 0, op.args.dy as number ?? 0, op.args.dz as number ?? 0];
    emitter.line(`mod.translate(geo.Vector(${dx}*UNIT_FACTOR, ${dy}*UNIT_FACTOR, ${dz}*UNIT_FACTOR))`);
  }

  private emitTransformRotate(op: CADOperation, emitter: CADEmitter): void {
    const angle = op.args.angle as number ?? 90;
    const [ax, ay, az] = [op.args.axisX as number ?? 0, op.args.axisY as number ?? 0, op.args.axisZ as number ?? 1];
    emitter.line(`mod.rotate(${angle}, geo.Vector(${ax}, ${ay}, ${az}))`);
  }

  private emitPatternLinear(op: CADOperation, emitter: CADEmitter): void {
    const [dx, dy, cnt] = [op.args.dx as number ?? 10, op.args.dy as number ?? 0, op.args.count as number ?? 3];
    emitter.line(`mod.linear_pattern(geo.Vector(${dx}*UNIT_FACTOR, ${dy}*UNIT_FACTOR, 0), ${cnt})`);
  }

  private emitPatternCircular(op: CADOperation, emitter: CADEmitter): void {
    const [cnt, angle] = [op.args.count as number ?? 6, op.args.angle as number ?? 360];
    emitter.line(`mod.circular_pattern(${cnt}, ${angle})`);
  }

  private emitExport(op: CADOperation, emitter: CADEmitter, ctx: HyperCADSGenerationContext | undefined, fmt: string): void {
    const fn = op.args.filename as string ?? `export.${fmt.toLowerCase()}`;
    const dir = ctx?.outputDir ?? "C:/PRISM_Output";
    emitter.line(`io.export("${dir}/${fn}", format="${fmt}")`);
    emitter.line(`results.append("Exported: ${dir}/${fn}")`);
  }

  protected epilogue(ctx: HyperCADSGenerationContext | undefined, emitter: CADEmitter): void {
    emitter.indent = "    ";
    emitter.line("except Exception as e:");
    emitter.line("    print(f'ERROR: {e}')")
    emitter.line("    return False");
    emitter.line("print('\\n'.join(results))");
    emitter.line("return True");
    emitter.line();
    emitter.indent = "";
    emitter.line("if __name__ == '__main__':");
    emitter.line("    main()");
  }

  protected scriptFilename(ctx: HyperCADSGenerationContext | undefined): string {
    const name = ctx?.projectName?.replace(/[^a-zA-Z0-9_]/g, "_") ?? "PRISM_Generated";
    return `${name}.py`;
  }

  protected async runScriptBody(script: ReturnType<typeof this.buildScript>): Promise<CADExecutionResult> {
    log.info(`[HyperCADSCodeGenerator] Executing: ${script.filename}`);
    if (process.env.PRISM_CAD_MOCK === "true" || process.env.CI === "true") {
      return { ok: true, metrics: { volumeMm3: 1000, faceCount: 6, boundingBoxMm: [10, 10, 10] }, durationMs: 50 };
    }
    try {
      const fs = await import("fs/promises");
      const path = await import("path");
      const { execFile } = await import("child_process");
      const util = await import("util");
      const execFileAsync = util.promisify(execFile);
      const outputDir = process.env.PRISM_HYPERCADS_OUTPUT ?? "C:\\PRISM_Output";
      await fs.mkdir(outputDir, { recursive: true });
      const fullScript = script.imports.join("\n") + "\n\n" + script.body;
      const scriptPath = path.join(outputDir, script.filename);
      await fs.writeFile(scriptPath, fullScript, "utf-8");
      const pythonPath = process.env.HYPERCADS_PYTHON ?? "C:\\Program Files\\OPEN MIND\\hyperCAD-S 2024\\python\\python.exe";
      await execFileAsync(pythonPath, [scriptPath], { timeout: 120000 });
      return { ok: true, outputFiles: [scriptPath], durationMs: 100 };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err), durationMs: 0 };
    }
  }
}

export const hyperCADSCodeGeneratorEngine = new HyperCADSCodeGeneratorEngine();
