/**
 * InventorCADCodeGeneratorEngine — U-CADC08 (PHASE-2)
 *
 * Generates iLogic VB.NET scripts for Autodesk Inventor CAD geometry creation.
 * Extends UnifiedCADCodeGeneratorBase for consistent API across CAD systems.
 *
 * Output: iLogic VB.NET automation scripts (.iLogicVb) that create:
 *   - Sketches (lines, arcs, circles, rectangles, splines, slots)
 *   - Features (extrude, revolve, loft, sweep, hole, pocket)
 *   - Modifiers (fillet, chamfer, shell, draft, mirror)
 *   - Patterns (rectangular, circular, feature mirror)
 *   - Boolean operations (union, intersect, subtract)
 *   - Assembly operations (place, constrain, ground)
 *
 * Inventor API Hierarchy:
 *   ThisApplication.Documents.Add(kPartDocumentObject)
 *   PartDocument.ComponentDefinition.Sketches.Add(workPlane)
 *   Sketch.SketchLines / SketchCircles / SketchArcs
 *   ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent()
 *   ComponentDefinition.Features.RevolveFeatures.AddFull()
 *
 * @engine InventorCADCodeGeneratorEngine
 * @shortcode E2481
 * @dispatcher cadDispatcher
 * @actions inventor_cad_generate, inventor_cad_execute, inventor_cad_validate
 * @milestone CAD-COMPLETE-MS0/U-CADC08
 */

import {
  UnifiedCADCodeGeneratorBase,
  CADEmitter,
  CADBuildError,
} from "./UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADOperation,
  CADScript,
  CADExecutionResult,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";
import { spawn } from "child_process";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

// ── Supported Operations ──────────────────────────────────────────────────────

const INVENTOR_SUPPORTED_OPS = new Set([
  // Sketch primitives
  "sketch_create",
  "sketch_line",
  "sketch_arc",
  "sketch_circle",
  "sketch_rectangle",
  "sketch_polygon",
  "sketch_spline",
  "sketch_slot",
  "sketch_ellipse",
  "sketch_point",
  "sketch_offset",
  "sketch_mirror",
  "sketch_trim",
  "sketch_extend",
  "sketch_dimension",
  "sketch_constraint",
  // Features
  "feature_extrude",
  "feature_revolve",
  "feature_loft",
  "feature_sweep",
  "feature_hole",
  "feature_pocket",
  "feature_fillet",
  "feature_chamfer",
  "feature_shell",
  "feature_draft",
  "feature_rib",
  "feature_emboss",
  "feature_decal",
  "feature_thread",
  "feature_coil",
  // Patterns
  "pattern_rectangular",
  "pattern_circular",
  "pattern_linear",
  "pattern_mirror",
  "pattern_sketch",
  // Boolean operations
  "boolean_union",
  "boolean_intersect",
  "boolean_subtract",
  // Work features
  "work_plane",
  "work_axis",
  "work_point",
  // Assembly
  "assembly_place",
  "assembly_constrain",
  "assembly_ground",
  "assembly_joint",
  // Parameters
  "parameter_declare",
  "parameter_link",
  // Import/Export
  "import_step",
  "import_iges",
  "export_step",
  "export_stl",
  "export_dxf",
] as const);

type InventorOpKind = (typeof INVENTOR_SUPPORTED_OPS) extends Set<infer T>
  ? T
  : never;

// ── Capability Matrix ─────────────────────────────────────────────────────────

const INVENTOR_CAPABILITIES: CADCapabilityMatrix = {
  supportedOps: INVENTOR_SUPPORTED_OPS as unknown as Set<string>,
  maxOpsPerScript: 500,
  supportsParameters: true,
  supportsUndo: true,
  supportsBatchExecution: true,
  parametricModeling: true,
  directModeling: false,
  assemblyModeling: true,
  sheetMetal: true,
  surfaceModeling: true,
  meshModeling: false,
};

// ── Engine Implementation ─────────────────────────────────────────────────────

export interface InventorCADContext {
  documentType?: "part" | "assembly" | "drawing";
  units?: "mm" | "in" | "cm";
  templatePath?: string;
  outputPath?: string;
}

export class InventorCADCodeGeneratorEngine extends UnifiedCADCodeGeneratorBase<InventorCADContext> {
  readonly cadSystem: CADSystemId = "inventor";
  readonly capabilities = INVENTOR_CAPABILITIES;

  private sketchCounter = 0;
  private featureCounter = 0;

  // ── Preamble ────────────────────────────────────────────────────────────────

  protected preamble(
    ctx: InventorCADContext | undefined,
    em: CADEmitter
  ): void {
    const docType = ctx?.documentType ?? "part";
    const units = ctx?.units ?? "mm";

    em.line("' ═══════════════════════════════════════════════════════════════");
    em.line("' PRISM CAD Generator — Autodesk Inventor iLogic Script");
    em.line(`' Document Type: ${docType}`);
    em.line(`' Units: ${units}`);
    em.line("' Generated by InventorCADCodeGeneratorEngine (E2481)");
    em.line("' ═══════════════════════════════════════════════════════════════");
    em.line("");

    // Imports
    em.line("Imports Inventor");
    em.line("Imports System.Math");
    em.line("");

    // Get application reference
    em.line("' Initialize Inventor application");
    em.line("Dim oApp As Inventor.Application = ThisApplication");
    em.line("");

    // Create or get document
    if (docType === "part") {
      em.line("' Create new part document");
      em.line(
        'Dim oDoc As PartDocument = oApp.Documents.Add(DocumentTypeEnum.kPartDocumentObject, "", True)'
      );
      em.line("Dim oDef As PartComponentDefinition = oDoc.ComponentDefinition");
    } else if (docType === "assembly") {
      em.line("' Create new assembly document");
      em.line(
        'Dim oDoc As AssemblyDocument = oApp.Documents.Add(DocumentTypeEnum.kAssemblyDocumentObject, "", True)'
      );
      em.line(
        "Dim oDef As AssemblyComponentDefinition = oDoc.ComponentDefinition"
      );
    }
    em.line("");

    // Set units
    em.line("' Set document units");
    if (units === "mm") {
      em.line(
        "oDoc.UnitsOfMeasure.LengthUnits = UnitsTypeEnum.kMillimeterLengthUnits"
      );
    } else if (units === "in") {
      em.line(
        "oDoc.UnitsOfMeasure.LengthUnits = UnitsTypeEnum.kInchLengthUnits"
      );
    } else if (units === "cm") {
      em.line(
        "oDoc.UnitsOfMeasure.LengthUnits = UnitsTypeEnum.kCentimeterLengthUnits"
      );
    }
    em.line("");

    // Helper variables
    em.line("' Working variables");
    em.line("Dim oSketch As PlanarSketch");
    em.line("Dim oProfile As Profile");
    em.line("Dim oFeature As Object");
    em.line("Dim oWorkPlane As WorkPlane");
    em.line("Dim _sketch_idx As Integer = 0");
    em.line("Dim _feature_idx As Integer = 0");
    em.line("");

    // Reset counters
    this.sketchCounter = 0;
    this.featureCounter = 0;
  }

  // ── Epilogue ────────────────────────────────────────────────────────────────

  protected epilogue(
    ctx: InventorCADContext | undefined,
    em: CADEmitter
  ): void {
    em.line("");
    em.line("' ═══════════════════════════════════════════════════════════════");
    em.line("' Finalize document");
    em.line("' ═══════════════════════════════════════════════════════════════");
    em.line("");
    em.line("' Update document");
    em.line("oDoc.Update2(True)");
    em.line("");

    if (ctx?.outputPath) {
      em.line("' Save document");
      em.line(`oDoc.SaveAs("${ctx.outputPath.replace(/\\/g, "\\\\")}", False)`);
    }

    em.line("");
    em.line("' Script complete");
    em.line("MessageBox.Show(\"Part created successfully\", \"PRISM\")");
  }

  // ── Script Filename ─────────────────────────────────────────────────────────

  protected scriptFilename(ctx: InventorCADContext | undefined): string {
    return `prism_inventor_${Date.now()}.iLogicVb`;
  }

  // ── Operation Emission ──────────────────────────────────────────────────────

  protected emitOp(
    op: CADOperation,
    opIndex: number,
    ctx: InventorCADContext | undefined,
    em: CADEmitter
  ): void {
    switch (op.kind as InventorOpKind) {
      // Sketch operations
      case "sketch_create":
        this.emitSketchCreate(op, em);
        break;
      case "sketch_line":
        this.emitSketchLine(op, em);
        break;
      case "sketch_arc":
        this.emitSketchArc(op, em);
        break;
      case "sketch_circle":
        this.emitSketchCircle(op, em);
        break;
      case "sketch_rectangle":
        this.emitSketchRectangle(op, em);
        break;
      case "sketch_polygon":
        this.emitSketchPolygon(op, em);
        break;
      case "sketch_spline":
        this.emitSketchSpline(op, em);
        break;
      case "sketch_slot":
        this.emitSketchSlot(op, em);
        break;
      case "sketch_ellipse":
        this.emitSketchEllipse(op, em);
        break;
      case "sketch_point":
        this.emitSketchPoint(op, em);
        break;
      case "sketch_offset":
        this.emitSketchOffset(op, em);
        break;
      case "sketch_mirror":
        this.emitSketchMirror(op, em);
        break;
      case "sketch_trim":
        this.emitSketchTrim(op, em);
        break;
      case "sketch_extend":
        this.emitSketchExtend(op, em);
        break;
      case "sketch_dimension":
        this.emitSketchDimension(op, em);
        break;
      case "sketch_constraint":
        this.emitSketchConstraint(op, em);
        break;

      // Feature operations
      case "feature_extrude":
        this.emitFeatureExtrude(op, em);
        break;
      case "feature_revolve":
        this.emitFeatureRevolve(op, em);
        break;
      case "feature_loft":
        this.emitFeatureLoft(op, em);
        break;
      case "feature_sweep":
        this.emitFeatureSweep(op, em);
        break;
      case "feature_hole":
        this.emitFeatureHole(op, em);
        break;
      case "feature_pocket":
        this.emitFeaturePocket(op, em);
        break;
      case "feature_fillet":
        this.emitFeatureFillet(op, em);
        break;
      case "feature_chamfer":
        this.emitFeatureChamfer(op, em);
        break;
      case "feature_shell":
        this.emitFeatureShell(op, em);
        break;
      case "feature_draft":
        this.emitFeatureDraft(op, em);
        break;
      case "feature_rib":
        this.emitFeatureRib(op, em);
        break;
      case "feature_emboss":
        this.emitFeatureEmboss(op, em);
        break;
      case "feature_decal":
        this.emitFeatureDecal(op, em);
        break;
      case "feature_thread":
        this.emitFeatureThread(op, em);
        break;
      case "feature_coil":
        this.emitFeatureCoil(op, em);
        break;

      // Pattern operations
      case "pattern_rectangular":
        this.emitPatternRectangular(op, em);
        break;
      case "pattern_circular":
        this.emitPatternCircular(op, em);
        break;
      case "pattern_linear":
        this.emitPatternLinear(op, em);
        break;
      case "pattern_mirror":
        this.emitPatternMirror(op, em);
        break;
      case "pattern_sketch":
        this.emitPatternSketch(op, em);
        break;

      // Boolean operations
      case "boolean_union":
        this.emitBooleanUnion(op, em);
        break;
      case "boolean_intersect":
        this.emitBooleanIntersect(op, em);
        break;
      case "boolean_subtract":
        this.emitBooleanSubtract(op, em);
        break;

      // Work features
      case "work_plane":
        this.emitWorkPlane(op, em);
        break;
      case "work_axis":
        this.emitWorkAxis(op, em);
        break;
      case "work_point":
        this.emitWorkPoint(op, em);
        break;

      // Assembly operations
      case "assembly_place":
        this.emitAssemblyPlace(op, em);
        break;
      case "assembly_constrain":
        this.emitAssemblyConstrain(op, em);
        break;
      case "assembly_ground":
        this.emitAssemblyGround(op, em);
        break;
      case "assembly_joint":
        this.emitAssemblyJoint(op, em);
        break;

      // Parameters
      case "parameter_declare":
        this.emitParameterDeclare(op, em);
        break;
      case "parameter_link":
        this.emitParameterLink(op, em);
        break;

      // Import/Export
      case "import_step":
        this.emitImportStep(op, em);
        break;
      case "import_iges":
        this.emitImportIges(op, em);
        break;
      case "export_step":
        this.emitExportStep(op, em);
        break;
      case "export_stl":
        this.emitExportStl(op, em);
        break;
      case "export_dxf":
        this.emitExportDxf(op, em);
        break;

      default:
        throw new CADBuildError(
          `Unsupported operation kind: ${op.kind}`,
          opIndex,
          op.kind
        );
    }
  }

  // ── Helper: require argument ────────────────────────────────────────────────

  private requireArg<T>(
    op: CADOperation,
    key: string,
    expectedType: "number" | "string" | "boolean" | "object"
  ): T {
    const val = op.args[key];
    if (val === undefined || val === null) {
      throw new Error(`op '${op.kind}' missing required arg '${key}'`);
    }
    if (typeof val !== expectedType && expectedType !== "object") {
      throw new Error(
        `op '${op.kind}' arg '${key}' expected ${expectedType}, got ${typeof val}`
      );
    }
    return val as T;
  }

  private optionalArg<T>(
    op: CADOperation,
    key: string,
    defaultValue: T
  ): T {
    const val = op.args[key];
    return val !== undefined && val !== null ? (val as T) : defaultValue;
  }

  // ── Sketch Emission ─────────────────────────────────────────────────────────

  private emitSketchCreate(op: CADOperation, em: CADEmitter): void {
    const plane = this.optionalArg<string>(op, "plane", "XY");
    const name = this.optionalArg<string>(op, "name", "");
    const offset = this.optionalArg<number>(op, "offset", 0);

    this.sketchCounter++;
    const sketchName = name || `Sketch${this.sketchCounter}`;

    em.line(`' Create sketch: ${sketchName}`);
    em.line("_sketch_idx += 1");

    // Get work plane
    if (plane === "XY" || plane === "XZ" || plane === "YZ") {
      const planeMap: Record<string, string> = {
        XY: "oDef.WorkPlanes.Item(3)", // XY plane
        XZ: "oDef.WorkPlanes.Item(2)", // XZ plane
        YZ: "oDef.WorkPlanes.Item(1)", // YZ plane
      };
      if (offset !== 0) {
        em.line(
          `oWorkPlane = oDef.WorkPlanes.AddByPlaneAndOffset(${planeMap[plane]}, ${offset})`
        );
        em.line("oSketch = oDef.Sketches.Add(oWorkPlane)");
      } else {
        em.line(`oSketch = oDef.Sketches.Add(${planeMap[plane]})`);
      }
    } else {
      // Custom plane reference
      em.line(`oSketch = oDef.Sketches.Add(${plane})`);
    }
    em.line(`oSketch.Name = "${sketchName}"`);
  }

  private emitSketchLine(op: CADOperation, em: CADEmitter): void {
    const x1 = this.requireArg<number>(op, "x1", "number");
    const y1 = this.requireArg<number>(op, "y1", "number");
    const x2 = this.requireArg<number>(op, "x2", "number");
    const y2 = this.requireArg<number>(op, "y2", "number");

    em.line(
      `oSketch.SketchLines.AddByTwoPoints(oApp.TransientGeometry.CreatePoint2d(${x1}, ${y1}), oApp.TransientGeometry.CreatePoint2d(${x2}, ${y2}))`
    );
  }

  private emitSketchArc(op: CADOperation, em: CADEmitter): void {
    const cx = this.requireArg<number>(op, "cx", "number");
    const cy = this.requireArg<number>(op, "cy", "number");
    const radius = this.requireArg<number>(op, "radius", "number");
    const startAngle = this.optionalArg<number>(op, "start_angle", 0);
    const endAngle = this.optionalArg<number>(op, "end_angle", 180);

    // Convert degrees to radians
    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;

    em.line(
      `oSketch.SketchArcs.AddByCenterStartEndPoint(oApp.TransientGeometry.CreatePoint2d(${cx}, ${cy}), oApp.TransientGeometry.CreatePoint2d(${cx + radius * Math.cos(startRad)}, ${cy + radius * Math.sin(startRad)}), oApp.TransientGeometry.CreatePoint2d(${cx + radius * Math.cos(endRad)}, ${cy + radius * Math.sin(endRad)}))`
    );
  }

  private emitSketchCircle(op: CADOperation, em: CADEmitter): void {
    const cx = this.requireArg<number>(op, "cx", "number");
    const cy = this.requireArg<number>(op, "cy", "number");
    const radius = this.requireArg<number>(op, "radius", "number");

    em.line(
      `oSketch.SketchCircles.AddByCenterRadius(oApp.TransientGeometry.CreatePoint2d(${cx}, ${cy}), ${radius})`
    );
  }

  private emitSketchRectangle(op: CADOperation, em: CADEmitter): void {
    const x = this.optionalArg<number>(op, "x", 0);
    const y = this.optionalArg<number>(op, "y", 0);
    const width = this.requireArg<number>(op, "width", "number");
    const height = this.requireArg<number>(op, "height", "number");

    em.line(
      `oSketch.SketchLines.AddAsTwoPointRectangle(oApp.TransientGeometry.CreatePoint2d(${x}, ${y}), oApp.TransientGeometry.CreatePoint2d(${x + width}, ${y + height}))`
    );
  }

  private emitSketchPolygon(op: CADOperation, em: CADEmitter): void {
    const cx = this.requireArg<number>(op, "cx", "number");
    const cy = this.requireArg<number>(op, "cy", "number");
    const radius = this.requireArg<number>(op, "radius", "number");
    const sides = this.optionalArg<number>(op, "sides", 6);

    em.line(
      `oSketch.SketchLines.AddAsPolygon(${sides}, oApp.TransientGeometry.CreatePoint2d(${cx}, ${cy}), oApp.TransientGeometry.CreatePoint2d(${cx + radius}, ${cy}), False)`
    );
  }

  private emitSketchSpline(op: CADOperation, em: CADEmitter): void {
    const points = this.requireArg<number[]>(op, "points", "object");

    if (points.length < 4 || points.length % 2 !== 0) {
      throw new Error("sketch_spline requires at least 2 points (4 coordinates)");
    }

    em.line("Dim splinePoints As ObjectCollection");
    em.line("splinePoints = oApp.TransientObjects.CreateObjectCollection()");

    for (let i = 0; i < points.length; i += 2) {
      em.line(
        `splinePoints.Add(oApp.TransientGeometry.CreatePoint2d(${points[i]}, ${points[i + 1]}))`
      );
    }
    em.line("oSketch.SketchSplines.Add(splinePoints)");
  }

  private emitSketchSlot(op: CADOperation, em: CADEmitter): void {
    const cx = this.requireArg<number>(op, "cx", "number");
    const cy = this.requireArg<number>(op, "cy", "number");
    const length = this.requireArg<number>(op, "length", "number");
    const width = this.requireArg<number>(op, "width", "number");

    const halfLen = length / 2;
    const halfWidth = width / 2;

    em.line("' Create slot geometry");
    // Left arc
    em.line(
      `oSketch.SketchArcs.AddByCenterStartEndPoint(oApp.TransientGeometry.CreatePoint2d(${cx - halfLen}, ${cy}), oApp.TransientGeometry.CreatePoint2d(${cx - halfLen}, ${cy + halfWidth}), oApp.TransientGeometry.CreatePoint2d(${cx - halfLen}, ${cy - halfWidth}))`
    );
    // Right arc
    em.line(
      `oSketch.SketchArcs.AddByCenterStartEndPoint(oApp.TransientGeometry.CreatePoint2d(${cx + halfLen}, ${cy}), oApp.TransientGeometry.CreatePoint2d(${cx + halfLen}, ${cy - halfWidth}), oApp.TransientGeometry.CreatePoint2d(${cx + halfLen}, ${cy + halfWidth}))`
    );
    // Top line
    em.line(
      `oSketch.SketchLines.AddByTwoPoints(oApp.TransientGeometry.CreatePoint2d(${cx - halfLen}, ${cy + halfWidth}), oApp.TransientGeometry.CreatePoint2d(${cx + halfLen}, ${cy + halfWidth}))`
    );
    // Bottom line
    em.line(
      `oSketch.SketchLines.AddByTwoPoints(oApp.TransientGeometry.CreatePoint2d(${cx - halfLen}, ${cy - halfWidth}), oApp.TransientGeometry.CreatePoint2d(${cx + halfLen}, ${cy - halfWidth}))`
    );
  }

  private emitSketchEllipse(op: CADOperation, em: CADEmitter): void {
    const cx = this.requireArg<number>(op, "cx", "number");
    const cy = this.requireArg<number>(op, "cy", "number");
    const majorRadius = this.requireArg<number>(op, "major_radius", "number");
    const minorRadius = this.requireArg<number>(op, "minor_radius", "number");

    em.line(
      `oSketch.SketchEllipses.Add(oApp.TransientGeometry.CreatePoint2d(${cx}, ${cy}), oApp.TransientGeometry.CreatePoint2d(${cx + majorRadius}, ${cy}), ${minorRadius / majorRadius})`
    );
  }

  private emitSketchPoint(op: CADOperation, em: CADEmitter): void {
    const x = this.requireArg<number>(op, "x", "number");
    const y = this.requireArg<number>(op, "y", "number");

    em.line(
      `oSketch.SketchPoints.Add(oApp.TransientGeometry.CreatePoint2d(${x}, ${y}))`
    );
  }

  private emitSketchOffset(op: CADOperation, em: CADEmitter): void {
    const distance = this.requireArg<number>(op, "distance", "number");
    em.line(`' Offset sketch entities by ${distance}mm`);
    em.line(
      `oSketch.OffsetSketchEntitiesUsingDistance(oSketch.SketchEntities, ${distance}, False, False)`
    );
  }

  private emitSketchMirror(op: CADOperation, em: CADEmitter): void {
    em.line("' Mirror sketch entities about center line");
    em.line(
      "oSketch.MoveSketchObjects(oSketch.SketchEntities, oApp.TransientGeometry.CreatePoint2d(0, 0), True, True, oSketch.SketchLines.Item(1))"
    );
  }

  private emitSketchTrim(op: CADOperation, em: CADEmitter): void {
    em.line("' Trim (manual trim not directly scriptable - use constraints)");
    em.warn("sketch_trim requires manual interaction in Inventor", "info");
  }

  private emitSketchExtend(op: CADOperation, em: CADEmitter): void {
    em.line("' Extend (manual extend not directly scriptable)");
    em.warn("sketch_extend requires manual interaction in Inventor", "info");
  }

  private emitSketchDimension(op: CADOperation, em: CADEmitter): void {
    const value = this.requireArg<number>(op, "value", "number");
    const name = this.optionalArg<string>(op, "name", "");

    em.line(
      `Dim oDim As DimensionConstraint = oSketch.DimensionConstraints.AddTwoPointDistance(oSketch.SketchEntities.Item(1).StartSketchPoint, oSketch.SketchEntities.Item(1).EndSketchPoint, DimensionOrientationEnum.kAlignedDim, oApp.TransientGeometry.CreatePoint2d(0, 0))`
    );
    em.line(`oDim.Parameter.Value = ${value}`);
    if (name) {
      em.line(`oDim.Parameter.Name = "${name}"`);
    }
  }

  private emitSketchConstraint(op: CADOperation, em: CADEmitter): void {
    const type = this.requireArg<string>(op, "type", "string");
    em.line(`' Add ${type} constraint`);
    em.line(`' Constraint application depends on selected entities`);
  }

  // ── Feature Emission ────────────────────────────────────────────────────────

  private emitFeatureExtrude(op: CADOperation, em: CADEmitter): void {
    const length = this.requireArg<number>(op, "length", "number");
    const symmetric = this.optionalArg<boolean>(op, "symmetric", false);
    const direction = this.optionalArg<string>(op, "direction", "positive");

    this.featureCounter++;
    em.line(`' Extrude feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");

    if (symmetric) {
      em.line(
        `oFeature = oDef.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, ${length / 2}, PartFeatureExtentDirectionEnum.kSymmetricExtentDirection, PartFeatureOperationEnum.kJoinOperation)`
      );
    } else {
      const dir =
        direction === "negative"
          ? "PartFeatureExtentDirectionEnum.kNegativeExtentDirection"
          : "PartFeatureExtentDirectionEnum.kPositiveExtentDirection";
      em.line(
        `oFeature = oDef.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, ${length}, ${dir}, PartFeatureOperationEnum.kJoinOperation)`
      );
    }
  }

  private emitFeatureRevolve(op: CADOperation, em: CADEmitter): void {
    const angle = this.optionalArg<number>(op, "angle", 360);

    this.featureCounter++;
    em.line(`' Revolve feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");

    if (angle === 360) {
      em.line(
        "oFeature = oDef.Features.RevolveFeatures.AddFull(oProfile, oSketch.SketchLines.Item(1), PartFeatureOperationEnum.kJoinOperation)"
      );
    } else {
      em.line(
        `oFeature = oDef.Features.RevolveFeatures.AddByAngle(oProfile, oSketch.SketchLines.Item(1), ${angle} * PI / 180, PartFeatureExtentDirectionEnum.kPositiveExtentDirection, PartFeatureOperationEnum.kJoinOperation)`
      );
    }
  }

  private emitFeatureLoft(op: CADOperation, em: CADEmitter): void {
    this.featureCounter++;
    em.line(`' Loft feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim loftSections As ObjectCollection");
    em.line("loftSections = oApp.TransientObjects.CreateObjectCollection()");
    em.line("' Add profiles to loftSections collection");
    em.line(
      "oFeature = oDef.Features.LoftFeatures.AddLoftFeature(loftSections, PartFeatureOperationEnum.kJoinOperation, False)"
    );
  }

  private emitFeatureSweep(op: CADOperation, em: CADEmitter): void {
    this.featureCounter++;
    em.line(`' Sweep feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");
    em.line(
      "oFeature = oDef.Features.SweepFeatures.AddSimple(oProfile, oSketch, PartFeatureOperationEnum.kJoinOperation)"
    );
  }

  private emitFeatureHole(op: CADOperation, em: CADEmitter): void {
    const diameter = this.requireArg<number>(op, "diameter", "number");
    const depth = this.requireArg<number>(op, "depth", "number");
    const x = this.optionalArg<number>(op, "x", 0);
    const y = this.optionalArg<number>(op, "y", 0);

    this.featureCounter++;
    em.line(`' Hole feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line(
      `Dim holeCenter As Point = oApp.TransientGeometry.CreatePoint(${x}, ${y}, 0)`
    );
    em.line(
      `oFeature = oDef.Features.HoleFeatures.AddDrilledByThroughAllExtent(oDef.Features.Item(oDef.Features.Count).Faces.Item(1), holeCenter, ${diameter})`
    );
    em.line(
      `oFeature.ExtentType = PartFeatureExtentEnum.kDistanceExtent`
    );
    em.line(`oFeature.ExtentDistance.Value = ${depth}`);
  }

  private emitFeaturePocket(op: CADOperation, em: CADEmitter): void {
    const length = this.requireArg<number>(op, "length", "number");

    this.featureCounter++;
    em.line(`' Pocket (cut extrude) feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");
    em.line(
      `oFeature = oDef.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, ${length}, PartFeatureExtentDirectionEnum.kNegativeExtentDirection, PartFeatureOperationEnum.kCutOperation)`
    );
  }

  private emitFeatureFillet(op: CADOperation, em: CADEmitter): void {
    const radius = this.requireArg<number>(op, "radius", "number");

    this.featureCounter++;
    em.line(`' Fillet feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim filletEdges As EdgeCollection");
    em.line("filletEdges = oApp.TransientObjects.CreateEdgeCollection()");
    em.line(
      "For Each oEdge As Edge In oDef.Features.Item(oDef.Features.Count).Edges"
    );
    em.line("    filletEdges.Add(oEdge)");
    em.line("Next");
    em.line(
      `oFeature = oDef.Features.FilletFeatures.AddSimple(filletEdges, ${radius})`
    );
  }

  private emitFeatureChamfer(op: CADOperation, em: CADEmitter): void {
    const distance = this.requireArg<number>(op, "distance", "number");

    this.featureCounter++;
    em.line(`' Chamfer feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim chamferEdges As EdgeCollection");
    em.line("chamferEdges = oApp.TransientObjects.CreateEdgeCollection()");
    em.line(
      "For Each oEdge As Edge In oDef.Features.Item(oDef.Features.Count).Edges"
    );
    em.line("    chamferEdges.Add(oEdge)");
    em.line("Next");
    em.line(
      `oFeature = oDef.Features.ChamferFeatures.AddUsingDistance(chamferEdges, ${distance})`
    );
  }

  private emitFeatureShell(op: CADOperation, em: CADEmitter): void {
    const thickness = this.requireArg<number>(op, "thickness", "number");

    this.featureCounter++;
    em.line(`' Shell feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim shellFaces As FaceCollection");
    em.line("shellFaces = oApp.TransientObjects.CreateFaceCollection()");
    em.line(
      `oFeature = oDef.Features.ShellFeatures.Add(shellFaces, ${thickness}, ShellDirectionEnum.kInsideShellDirection)`
    );
  }

  private emitFeatureDraft(op: CADOperation, em: CADEmitter): void {
    const angle = this.requireArg<number>(op, "angle", "number");

    this.featureCounter++;
    em.line(`' Draft feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim draftFaces As FaceCollection");
    em.line("draftFaces = oApp.TransientObjects.CreateFaceCollection()");
    em.line(
      `oFeature = oDef.Features.FaceFeatures.AddDraftFeature(draftFaces, ${angle} * PI / 180, oDef.WorkPlanes.Item(3))`
    );
  }

  private emitFeatureRib(op: CADOperation, em: CADEmitter): void {
    const thickness = this.requireArg<number>(op, "thickness", "number");

    this.featureCounter++;
    em.line(`' Rib feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");
    em.line(
      `oFeature = oDef.Features.RibFeatures.Add(oProfile, ${thickness}, PartFeatureExtentDirectionEnum.kSymmetricExtentDirection)`
    );
  }

  private emitFeatureEmboss(op: CADOperation, em: CADEmitter): void {
    const depth = this.requireArg<number>(op, "depth", "number");

    this.featureCounter++;
    em.line(`' Emboss feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");
    em.line(
      `oFeature = oDef.Features.EmbossFeatures.Add(oProfile, ${depth}, EmbossFeatureTypeEnum.kEmbossFromFaceFeatureType)`
    );
  }

  private emitFeatureDecal(op: CADOperation, em: CADEmitter): void {
    em.line("' Decal feature (image-based, requires external file)");
    em.warn("feature_decal requires manual setup in Inventor", "info");
  }

  private emitFeatureThread(op: CADOperation, em: CADEmitter): void {
    const pitch = this.requireArg<number>(op, "pitch", "number");

    this.featureCounter++;
    em.line(`' Thread feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("Dim threadFace As Face");
    em.line(
      "threadFace = oDef.Features.Item(oDef.Features.Count).Faces.Item(1)"
    );
    em.line(
      `oFeature = oDef.Features.ThreadFeatures.Add(threadFace, True, True, ${pitch}, oApp.AssetLibraries.Item(1).ThreadAssets.Item(1))`
    );
  }

  private emitFeatureCoil(op: CADOperation, em: CADEmitter): void {
    const pitch = this.requireArg<number>(op, "pitch", "number");
    const revolutions = this.optionalArg<number>(op, "revolutions", 10);

    this.featureCounter++;
    em.line(`' Coil feature ${this.featureCounter}`);
    em.line("_feature_idx += 1");
    em.line("oProfile = oSketch.Profiles.AddForSolid()");
    em.line(
      `oFeature = oDef.Features.CoilFeatures.AddByPitchAndRevolution(oProfile, oSketch.SketchLines.Item(1), ${pitch}, ${revolutions}, PartFeatureOperationEnum.kJoinOperation)`
    );
  }

  // ── Pattern Emission ────────────────────────────────────────────────────────

  private emitPatternRectangular(op: CADOperation, em: CADEmitter): void {
    const countX = this.optionalArg<number>(op, "count_x", 2);
    const countY = this.optionalArg<number>(op, "count_y", 2);
    const spacingX = this.optionalArg<number>(op, "spacing_x", 10);
    const spacingY = this.optionalArg<number>(op, "spacing_y", 10);

    em.line("' Rectangular pattern");
    em.line("Dim patternFeatures As ObjectCollection");
    em.line("patternFeatures = oApp.TransientObjects.CreateObjectCollection()");
    em.line(
      "patternFeatures.Add(oDef.Features.Item(oDef.Features.Count))"
    );
    em.line(
      `oFeature = oDef.Features.RectangularPatternFeatures.Add(patternFeatures, oDef.WorkAxes.Item(1), ${countX}, ${spacingX}, oDef.WorkAxes.Item(2), ${countY}, ${spacingY})`
    );
  }

  private emitPatternCircular(op: CADOperation, em: CADEmitter): void {
    const count = this.requireArg<number>(op, "count", "number");
    const angle = this.optionalArg<number>(op, "angle", 360);

    em.line("' Circular pattern");
    em.line("Dim patternFeatures As ObjectCollection");
    em.line("patternFeatures = oApp.TransientObjects.CreateObjectCollection()");
    em.line(
      "patternFeatures.Add(oDef.Features.Item(oDef.Features.Count))"
    );
    em.line(
      `oFeature = oDef.Features.CircularPatternFeatures.Add(patternFeatures, oDef.WorkAxes.Item(3), ${count}, ${angle} * PI / 180)`
    );
  }

  private emitPatternLinear(op: CADOperation, em: CADEmitter): void {
    const count = this.requireArg<number>(op, "count", "number");
    const spacing = this.requireArg<number>(op, "spacing", "number");

    em.line("' Linear pattern (1D rectangular)");
    em.line("Dim patternFeatures As ObjectCollection");
    em.line("patternFeatures = oApp.TransientObjects.CreateObjectCollection()");
    em.line(
      "patternFeatures.Add(oDef.Features.Item(oDef.Features.Count))"
    );
    em.line(
      `oFeature = oDef.Features.RectangularPatternFeatures.Add(patternFeatures, oDef.WorkAxes.Item(1), ${count}, ${spacing})`
    );
  }

  private emitPatternMirror(op: CADOperation, em: CADEmitter): void {
    em.line("' Mirror pattern");
    em.line("Dim patternFeatures As ObjectCollection");
    em.line("patternFeatures = oApp.TransientObjects.CreateObjectCollection()");
    em.line(
      "patternFeatures.Add(oDef.Features.Item(oDef.Features.Count))"
    );
    em.line(
      "oFeature = oDef.Features.MirrorFeatures.Add(patternFeatures, oDef.WorkPlanes.Item(1))"
    );
  }

  private emitPatternSketch(op: CADOperation, em: CADEmitter): void {
    em.line("' Sketch-driven pattern");
    em.line("Dim patternFeatures As ObjectCollection");
    em.line("patternFeatures = oApp.TransientObjects.CreateObjectCollection()");
    em.line(
      "patternFeatures.Add(oDef.Features.Item(oDef.Features.Count))"
    );
    em.line(
      "oFeature = oDef.Features.SketchDrivenPatternFeatures.Add(patternFeatures, oSketch)"
    );
  }

  // ── Boolean Emission ────────────────────────────────────────────────────────

  private emitBooleanUnion(op: CADOperation, em: CADEmitter): void {
    em.line("' Boolean union (combine surfaces)");
    em.line(
      "oDef.Features.CombineFeatures.Add(oDef.SurfaceBodies, BooleanTypeEnum.kBooleanTypeUnion)"
    );
  }

  private emitBooleanIntersect(op: CADOperation, em: CADEmitter): void {
    em.line("' Boolean intersect");
    em.line(
      "oDef.Features.CombineFeatures.Add(oDef.SurfaceBodies, BooleanTypeEnum.kBooleanTypeIntersect)"
    );
  }

  private emitBooleanSubtract(op: CADOperation, em: CADEmitter): void {
    em.line("' Boolean subtract");
    em.line(
      "oDef.Features.CombineFeatures.Add(oDef.SurfaceBodies, BooleanTypeEnum.kBooleanTypeDifference)"
    );
  }

  // ── Work Feature Emission ───────────────────────────────────────────────────

  private emitWorkPlane(op: CADOperation, em: CADEmitter): void {
    const offset = this.optionalArg<number>(op, "offset", 0);
    const plane = this.optionalArg<string>(op, "base", "XY");

    const planeMap: Record<string, string> = {
      XY: "oDef.WorkPlanes.Item(3)",
      XZ: "oDef.WorkPlanes.Item(2)",
      YZ: "oDef.WorkPlanes.Item(1)",
    };

    em.line(
      `oWorkPlane = oDef.WorkPlanes.AddByPlaneAndOffset(${planeMap[plane] ?? plane}, ${offset})`
    );
  }

  private emitWorkAxis(op: CADOperation, em: CADEmitter): void {
    em.line("' Create work axis");
    em.line(
      "Dim oAxis As WorkAxis = oDef.WorkAxes.AddByTwoPoints(oApp.TransientGeometry.CreatePoint(0, 0, 0), oApp.TransientGeometry.CreatePoint(0, 0, 100))"
    );
  }

  private emitWorkPoint(op: CADOperation, em: CADEmitter): void {
    const x = this.optionalArg<number>(op, "x", 0);
    const y = this.optionalArg<number>(op, "y", 0);
    const z = this.optionalArg<number>(op, "z", 0);

    em.line(
      `Dim oPoint As WorkPoint = oDef.WorkPoints.AddFixed(oApp.TransientGeometry.CreatePoint(${x}, ${y}, ${z}))`
    );
  }

  // ── Assembly Emission ───────────────────────────────────────────────────────

  private emitAssemblyPlace(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Place component: ${filePath}`);
    em.line(
      `Dim oOcc As ComponentOccurrence = oDef.Occurrences.Add("${filePath.replace(/\\/g, "\\\\")}", oApp.TransientGeometry.CreateMatrix())`
    );
  }

  private emitAssemblyConstrain(op: CADOperation, em: CADEmitter): void {
    const type = this.optionalArg<string>(op, "type", "mate");

    em.line(`' Add ${type} constraint`);
    em.line("' Constraint application requires face/edge selection");
  }

  private emitAssemblyGround(op: CADOperation, em: CADEmitter): void {
    em.line("' Ground component (first occurrence)");
    em.line("oDef.Occurrences.Item(1).Grounded = True");
  }

  private emitAssemblyJoint(op: CADOperation, em: CADEmitter): void {
    const type = this.optionalArg<string>(op, "type", "rigid");

    em.line(`' Add ${type} joint`);
    em.line("' Joint application requires geometry selection");
  }

  // ── Parameter Emission ──────────────────────────────────────────────────────

  private emitParameterDeclare(op: CADOperation, em: CADEmitter): void {
    const name = this.requireArg<string>(op, "name", "string");
    const value = this.requireArg<number>(op, "value", "number");
    const unit = this.optionalArg<string>(op, "unit", "mm");

    em.parameter(name, value, unit);
    em.line(`' Parameter: ${name} = ${value} ${unit}`);
    em.line(`Dim ${name} As Double = ${value}`);
    em.line(
      `oDef.Parameters.UserParameters.AddByValue("${name}", ${value}, UnitsTypeEnum.kMillimeterLengthUnits)`
    );
  }

  private emitParameterLink(op: CADOperation, em: CADEmitter): void {
    const source = this.requireArg<string>(op, "source", "string");
    const target = this.requireArg<string>(op, "target", "string");

    em.line(`' Link parameter ${source} to ${target}`);
    em.line(`oDef.Parameters.Item("${target}").Expression = "${source}"`);
  }

  // ── Import/Export Emission ──────────────────────────────────────────────────

  private emitImportStep(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Import STEP: ${filePath}`);
    em.line(
      `oApp.Documents.Open("${filePath.replace(/\\/g, "\\\\")}", True)`
    );
  }

  private emitImportIges(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Import IGES: ${filePath}`);
    em.line(
      `oApp.Documents.Open("${filePath.replace(/\\/g, "\\\\")}", True)`
    );
  }

  private emitExportStep(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Export STEP: ${filePath}`);
    em.line(
      `oDoc.SaveAs("${filePath.replace(/\\/g, "\\\\")}", True)`
    );
  }

  private emitExportStl(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Export STL: ${filePath}`);
    em.line(
      `oDoc.SaveAs("${filePath.replace(/\\/g, "\\\\")}", True)`
    );
  }

  private emitExportDxf(op: CADOperation, em: CADEmitter): void {
    const filePath = this.requireArg<string>(op, "file", "string");

    em.line(`' Export DXF: ${filePath}`);
    em.line(
      `oDoc.SaveAs("${filePath.replace(/\\/g, "\\\\")}", True)`
    );
  }

  // ── Script Execution ────────────────────────────────────────────────────────

  protected async runScriptBody(
    script: CADScript<string>
  ): Promise<CADExecutionResult> {
    // Write script to temp file
    const tempDir = os.tmpdir();
    const scriptPath = path.join(tempDir, script.filename);
    fs.writeFileSync(scriptPath, script.body, "utf-8");

    // In real implementation, this would use InventorAutomationBridge
    // For now, return mock result indicating script was generated
    return {
      ok: true,
      cadSystem: this.cadSystem,
      executionTimeMs: 0,
      scriptPath,
      metrics: {
        operationCount: script.lineage.length,
        warningCount: script.warnings.length,
        parameterCount: script.parameters.size,
      },
      warnings: script.warnings.map((w) => w.message),
    };
  }
}

// ── Singleton Export ──────────────────────────────────────────────────────────

export const inventorCADCodeGeneratorEngine =
  new InventorCADCodeGeneratorEngine();
