/**
 * JobChecklistEngine -- the stateful per-employee check-off layer for a job
 * traveler. The existing shop-floor stack (JobTravelerEngine, ShopState,
 * ShopFloorCheckIn) tracks setup/cycle TIME per step but carries no check-off
 * items an employee marks done. This engine is that missing layer.
 *
 * Model: per job x step x checklist-item, it stores
 *   { checked, checked_by_employee_id, checked_at, note }.
 * Items + their required/signoff flags come from the steps generated by
 * TravelerGenerationOrchestratorEngine (attachChecklists seeds them).
 *
 * Segregation-of-duties (mirrors EmployeeTaskHandoffEngine's rank guards):
 *   - An employee may only check items on a step whose DEPARTMENT matches the
 *     employee's department (resolved from EmployeeEngine, or passed explicitly).
 *     A `lead`/`supervisor`/`manager`/`admin` may check any department's items.
 *   - An inspection-GATE step's signoff items require an `inspector` or
 *     `lead`-or-above role.
 *
 * A step is "checklist-complete" when every REQUIRED item is checked. The
 * engine emits `traveler.step.checklist_complete` on the event bus + audits it,
 * so the JobTravelerEngine / dashboards can gate the routing step.
 *
 * NOT a duplicate of PreCutChecklistEngine / PreMOUKickoffChecklistEngine
 * (single-gate checklists) -- this is the per-job multi-department check-off
 * STORE. R12 fail-loud on unknown job/step/item.
 *
 * @module engines/JobChecklistEngine
 * @milestone QUOTING-TRAVELER/U-JOBCHECKLIST (2026-06-29, slot:charlie)
 */

import { eventBus } from "./EventBus.js";
import { auditEngine } from "./AuditEngine.js";
import type {
  GeneratedTravelerStep,
  ChecklistItem,
  TravelerDepartment,
} from "./TravelerGenerationOrchestratorEngine.js";

// ============================================================================
// TYPES
// ============================================================================

/** Live state of a single checklist item on a job step. */
export interface ChecklistItemState extends ChecklistItem {
  checked: boolean;
  checked_by_employee_id?: string;
  checked_at?: string;
  note?: string;
}

/** A job step's checklist + roll-up. */
export interface StepChecklist {
  job_id: string;
  step_seq: number;
  operation: string;
  department: TravelerDepartment;
  is_inspection_gate: boolean;
  items: ChecklistItemState[];
  required_total: number;
  required_checked: number;
  complete: boolean;
}

/** Whole-job checklist view. */
export interface JobChecklist {
  job_id: string;
  steps: StepChecklist[];
  total_required: number;
  total_required_checked: number;
  pct_complete: number;
}

/** Roles that may check ANY department's items (supervisory). */
const SUPERVISORY_ROLES = new Set(["lead", "supervisor", "manager", "admin"]);
/** Roles permitted to sign off an inspection-gate item. */
const INSPECTION_ROLES = new Set(["inspector", "lead", "supervisor", "manager", "admin"]);

/** Maps a shop-floor TravelerDepartment to the EmployeeEngine HR `Department`
 * so a department-match SoD check works across the two taxonomies (the HR
 * taxonomy collapses turning/grinding/edm/deburr under "machining"). */
const TRAVELER_DEPT_TO_HR_DEPT: Record<TravelerDepartment, string> = {
  programming: "programming",
  saw: "machining",
  machining: "machining",
  turning: "machining",
  grinding: "machining",
  edm: "machining",
  deburr: "machining",
  finishing: "planning",
  inspection: "quality",
  shipping: "shipping",
};

export interface CheckItemInput {
  job_id: string;
  step_seq: number;
  item_id: string;
  employee_id: string;
  /** Optional explicit dept/role override; otherwise resolved from EmployeeEngine. */
  employee_department?: string;
  employee_role?: string;
  note?: string;
}

// ============================================================================
// ENGINE
// ============================================================================

interface InternalStep {
  job_id: string;
  step_seq: number;
  operation: string;
  department: TravelerDepartment;
  is_inspection_gate: boolean;
  items: Map<string, ChecklistItemState>;
  /** Insertion order of item ids (stable rendering). */
  order: string[];
  completedEmitted: boolean;
}

export class JobChecklistEngine {
  /** job_id -> (step_seq -> InternalStep) */
  private store: Map<string, Map<number, InternalStep>> = new Map();

  /**
   * Seed (or replace) the checklists for a job from generated traveler steps.
   * @param jobId - the job id
   * @param steps - GeneratedTravelerStep[] from TravelerGenerationOrchestratorEngine
   * @returns the freshly-attached JobChecklist
   */
  attachChecklists(jobId: string, steps: GeneratedTravelerStep[]): JobChecklist {
    if (!jobId || jobId.trim().length === 0) {
      throw new Error("JobChecklistEngine: job_id is required");
    }
    if (!Array.isArray(steps) || steps.length === 0) {
      throw new Error("JobChecklistEngine: at least one step is required");
    }
    const stepMap = new Map<number, InternalStep>();
    for (const s of steps) {
      const items = new Map<string, ChecklistItemState>();
      const order: string[] = [];
      for (const item of s.checklist) {
        if (items.has(item.id)) {
          throw new Error(`JobChecklistEngine: duplicate checklist item id '${item.id}' on step ${s.seq}`);
        }
        items.set(item.id, { ...item, checked: false });
        order.push(item.id);
      }
      stepMap.set(s.seq, {
        job_id: jobId,
        step_seq: s.seq,
        operation: s.operation,
        department: s.department,
        is_inspection_gate: s.is_inspection_gate,
        items,
        order,
        completedEmitted: false,
      });
    }
    this.store.set(jobId, stepMap);

    auditEngine.log("data", "job_checklist_attached", "system", {
      job_id: jobId, step_count: steps.length,
    }, { resource_type: "job", resource_id: jobId });

    return this.getJobChecklist(jobId);
  }

  /**
   * Check (mark done) a checklist item. Enforces segregation-of-duties.
   * @param input - job/step/item + employee + optional dept/role override + note
   * @returns the updated StepChecklist
   * @throws on unknown job/step/item, already-checked, or SoD violation (R12)
   */
  checkItem(input: CheckItemInput): StepChecklist {
    const step = this.requireStep(input.job_id, input.step_seq);
    const item = step.items.get(input.item_id);
    if (!item) {
      throw new Error(`JobChecklistEngine: item '${input.item_id}' not found on job '${input.job_id}' step ${input.step_seq}`);
    }
    if (!input.employee_id || input.employee_id.trim().length === 0) {
      throw new Error("JobChecklistEngine: employee_id is required to check an item");
    }

    const { department: empDept, role: empRole } = this.resolveEmployee(input);

    // SoD: department match (supervisory roles bypass). FAIL-CLOSED: a
    // non-supervisory actor whose department cannot be resolved (unknown
    // employee + no explicit override) is REJECTED -- a segregation-of-duties
    // guard must default to deny, never degrade to open for an unidentified
    // actor (scrutiny arm C, U-TRAVGEN follow-up).
    const isSupervisor = SUPERVISORY_ROLES.has(empRole);
    if (!isSupervisor) {
      const stepHrDept = TRAVELER_DEPT_TO_HR_DEPT[step.department];
      if (!empDept) {
        throw new Error(
          `JobChecklistEngine: employee '${input.employee_id}' has no resolvable department; supply employee_department (or register the employee) -- cannot check a department-scoped item without an identified department`,
        );
      }
      if (stepHrDept && empDept !== stepHrDept) {
        throw new Error(
          `JobChecklistEngine: employee '${input.employee_id}' (dept '${empDept}') cannot check items on a '${step.department}' (dept '${stepHrDept}') step`,
        );
      }
    }
    // SoD: inspection-gate signoff items require an inspector / lead-or-above.
    if (step.is_inspection_gate && item.signoff && !INSPECTION_ROLES.has(empRole)) {
      throw new Error(
        `JobChecklistEngine: role '${empRole}' cannot sign off an inspection-gate item; requires inspector or lead-or-above`,
      );
    }

    if (item.checked) {
      throw new Error(`JobChecklistEngine: item '${input.item_id}' is already checked (by ${item.checked_by_employee_id})`);
    }

    item.checked = true;
    item.checked_by_employee_id = input.employee_id;
    item.checked_at = new Date().toISOString();
    if (input.note !== undefined) item.note = input.note;

    auditEngine.log("data", "job_checklist_item_checked", input.employee_id, {
      job_id: input.job_id, step_seq: input.step_seq, item_id: input.item_id, signoff: item.signoff,
    }, { resource_type: "job", resource_id: input.job_id });

    eventBus.publish("traveler.checklist.item_checked", {
      job_id: input.job_id, step_seq: input.step_seq, item_id: input.item_id, employee_id: input.employee_id,
    }, { category: "data", source: "JobChecklistEngine" });

    this.maybeEmitStepComplete(step);
    return this.toStepChecklist(step);
  }

  /**
   * Un-check an item (correct a mistake). Only the employee who checked it, or
   * a supervisory role, may un-check.
   * @param input - same shape as checkItem (note ignored)
   * @returns the updated StepChecklist
   */
  uncheckItem(input: CheckItemInput): StepChecklist {
    const step = this.requireStep(input.job_id, input.step_seq);
    const item = step.items.get(input.item_id);
    if (!item) {
      throw new Error(`JobChecklistEngine: item '${input.item_id}' not found on job '${input.job_id}' step ${input.step_seq}`);
    }
    if (!item.checked) {
      throw new Error(`JobChecklistEngine: item '${input.item_id}' is not checked`);
    }
    const { role: empRole } = this.resolveEmployee(input);
    const isSupervisor = SUPERVISORY_ROLES.has(empRole);
    if (!isSupervisor && item.checked_by_employee_id !== input.employee_id) {
      throw new Error(
        `JobChecklistEngine: only ${item.checked_by_employee_id} or a supervisor can un-check item '${input.item_id}'`,
      );
    }
    item.checked = false;
    delete item.checked_by_employee_id;
    delete item.checked_at;
    delete item.note;
    // Re-arm the complete event if it had fired.
    step.completedEmitted = false;

    auditEngine.log("data", "job_checklist_item_unchecked", input.employee_id, {
      job_id: input.job_id, step_seq: input.step_seq, item_id: input.item_id,
    }, { resource_type: "job", resource_id: input.job_id });

    return this.toStepChecklist(step);
  }

  /** Get the checklist for one step.
   * @throws if the job/step is unknown */
  getStepChecklist(jobId: string, stepSeq: number): StepChecklist {
    return this.toStepChecklist(this.requireStep(jobId, stepSeq));
  }

  /** Get the whole-job checklist roll-up.
   * @throws if the job is unknown */
  getJobChecklist(jobId: string): JobChecklist {
    const stepMap = this.store.get(jobId);
    if (!stepMap) {
      throw new Error(`JobChecklistEngine: no checklist for job '${jobId}'`);
    }
    const steps = [...stepMap.values()]
      .sort((a, b) => a.step_seq - b.step_seq)
      .map((s) => this.toStepChecklist(s));
    const totalReq = steps.reduce((n, s) => n + s.required_total, 0);
    const totalReqChecked = steps.reduce((n, s) => n + s.required_checked, 0);
    return {
      job_id: jobId,
      steps,
      total_required: totalReq,
      total_required_checked: totalReqChecked,
      pct_complete: totalReq > 0 ? Math.round((totalReqChecked / totalReq) * 100) : 0,
    };
  }

  /** Is the step's required-item set fully checked?
   * @throws if the job/step is unknown */
  stepComplete(jobId: string, stepSeq: number): boolean {
    return this.isStepComplete(this.requireStep(jobId, stepSeq));
  }

  /** Clear all state (tests). */
  reset(): void {
    this.store.clear();
  }

  // ========================================================================
  // PRIVATE
  // ========================================================================

  private requireStep(jobId: string, stepSeq: number): InternalStep {
    const stepMap = this.store.get(jobId);
    if (!stepMap) {
      throw new Error(`JobChecklistEngine: no checklist for job '${jobId}'`);
    }
    const step = stepMap.get(stepSeq);
    if (!step) {
      throw new Error(`JobChecklistEngine: step ${stepSeq} not found on job '${jobId}'`);
    }
    return step;
  }

  /** Resolve the employee's dept/role from the explicit override, else from
   * EmployeeEngine. Best-effort: a missing employee yields empty dept (the
   * department-match guard then can't false-block; the role guard still runs). */
  private resolveEmployee(input: CheckItemInput): { department: string; role: string } {
    if (input.employee_department !== undefined || input.employee_role !== undefined) {
      return {
        department: input.employee_department ?? "",
        role: input.employee_role ?? "",
      };
    }
    try {
      // Lazy require to avoid a hard engine->engine load-order dependency.
      const { employeeEngine } = require("./EmployeeEngine.js");
      const emp = employeeEngine.get(input.employee_id);
      if (emp) return { department: String(emp.department ?? ""), role: String(emp.role ?? "") };
    } catch { /* EmployeeEngine lookup is best-effort */ }
    return { department: "", role: "" };
  }

  private isStepComplete(step: InternalStep): boolean {
    for (const id of step.order) {
      const item = step.items.get(id)!;
      if (item.required && !item.checked) return false;
    }
    return true;
  }

  private maybeEmitStepComplete(step: InternalStep): void {
    if (step.completedEmitted) return;
    if (!this.isStepComplete(step)) return;
    step.completedEmitted = true;
    auditEngine.log("data", "job_checklist_step_complete", "system", {
      job_id: step.job_id, step_seq: step.step_seq, department: step.department,
    }, { resource_type: "job", resource_id: step.job_id });
    eventBus.publish("traveler.step.checklist_complete", {
      job_id: step.job_id, step_seq: step.step_seq, department: step.department, operation: step.operation,
    }, { category: "data", source: "JobChecklistEngine" });
  }

  private toStepChecklist(step: InternalStep): StepChecklist {
    const items = step.order.map((id) => ({ ...step.items.get(id)! }));
    const reqItems = items.filter((i) => i.required);
    const reqChecked = reqItems.filter((i) => i.checked).length;
    return {
      job_id: step.job_id,
      step_seq: step.step_seq,
      operation: step.operation,
      department: step.department,
      is_inspection_gate: step.is_inspection_gate,
      items,
      required_total: reqItems.length,
      required_checked: reqChecked,
      complete: reqItems.length > 0 ? reqChecked === reqItems.length : true,
    };
  }
}

export const jobChecklistEngine = new JobChecklistEngine();
