/**
 * LatheLoRAMergeQuantEngine — Merge and Quantize
 *
 * U-LTH72: Merges LoRA adapters into base model and quantizes for deployment.
 * Supports GGUF (llama.cpp), AWQ (vLLM), and GPTQ formats.
 *
 * @module engines/LatheLoRAMergeQuantEngine
 */

// ============================================================================
// TYPES
// ============================================================================

export type QuantFormat = "gguf" | "awq" | "gptq" | "fp16" | "bf16";
export type GGUFQuant =
  | "Q4_K_M"
  | "Q4_K_S"
  | "Q5_K_M"
  | "Q5_K_S"
  | "Q6_K"
  | "Q8_0"
  | "F16";

export interface MergeConfig {
  base_model: string;
  adapter_path: string;
  output_dir: string;
  output_format: QuantFormat;
  gguf_quant?: GGUFQuant;
  awq_bits?: 4 | 8;
  gptq_bits?: 2 | 3 | 4 | 8;
  calibration_samples?: number;
  push_to_hub?: boolean;
  hub_model_id?: string;
}

export interface MergeResult {
  success: boolean;
  output_path: string;
  model_size_mb: number;
  format: QuantFormat;
  quant_method?: string;
  errors: string[];
}

export interface SizeEstimate {
  fp16_size_gb: number;
  estimated_size_gb: number;
  compression_ratio: number;
}

// ============================================================================
// QUANT SIZE MULTIPLIERS
// ============================================================================

const GGUF_SIZE_MULTIPLIERS: Record<GGUFQuant, number> = {
  "Q4_K_M": 0.27,
  "Q4_K_S": 0.25,
  "Q5_K_M": 0.33,
  "Q5_K_S": 0.31,
  "Q6_K": 0.40,
  "Q8_0": 0.54,
  "F16": 1.0,
};

const MODEL_FP16_SIZES: Record<string, number> = {
  "llama-3-8b": 16,
  "mistral-7b": 14,
  "phi-3.5-mini": 7.6,
  "gemma-2-9b": 18,
  "qwen2.5-7b": 14,
};

// ============================================================================
// DEFAULT CONFIGURATION
// ============================================================================

const DEFAULT_CONFIG: MergeConfig = {
  base_model: "meta-llama/Meta-Llama-3-8B",
  adapter_path: "models/lathe-lora/final",
  output_dir: "models/lathe-merged",
  output_format: "gguf",
  gguf_quant: "Q4_K_M",
  awq_bits: 4,
  gptq_bits: 4,
  calibration_samples: 128,
  push_to_hub: false,
};

// ============================================================================
// ENGINE
// ============================================================================

class LatheLoRAMergeQuantEngine {
  private config: MergeConfig = { ...DEFAULT_CONFIG };

  // --------------------------------------------------------------------------
  // Configuration
  // --------------------------------------------------------------------------

  setConfig(config: Partial<MergeConfig>): MergeConfig {
    this.config = { ...this.config, ...config };
    return this.config;
  }

  getConfig(): MergeConfig {
    return { ...this.config };
  }

  // --------------------------------------------------------------------------
  // Merge Script Generation
  // --------------------------------------------------------------------------

  generateMergeScript(): string {
    const c = this.config;

    return `#!/usr/bin/env python3
"""
LatheLoRA Merge Script

Merges LoRA adapter into base model.
Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

# Configuration
BASE_MODEL = "${c.base_model}"
ADAPTER_PATH = "${c.adapter_path}"
OUTPUT_DIR = "${c.output_dir}/merged"

def merge_lora():
    print(f"Loading base model: {BASE_MODEL}")
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

    print(f"Loading LoRA adapter: {ADAPTER_PATH}")
    model = PeftModel.from_pretrained(model, ADAPTER_PATH)

    print("Merging LoRA weights into base model...")
    model = model.merge_and_unload()

    print(f"Saving merged model to: {OUTPUT_DIR}")
    model.save_pretrained(OUTPUT_DIR, safe_serialization=True)
    tokenizer.save_pretrained(OUTPUT_DIR)

    print("Merge complete!")
    return OUTPUT_DIR

if __name__ == "__main__":
    merge_lora()
`;
  }

  // --------------------------------------------------------------------------
  // Quantization Script Generation
  // --------------------------------------------------------------------------

  generateQuantScript(): string {
    switch (this.config.output_format) {
      case "gguf":
        return this.generateGGUFScript();
      case "awq":
        return this.generateAWQScript();
      case "gptq":
        return this.generateGPTQScript();
      default:
        return this.generateFP16Script();
    }
  }

  private generateGGUFScript(): string {
    const c = this.config;
    const quant = c.gguf_quant || "Q4_K_M";

    return `#!/usr/bin/env python3
"""
GGUF Quantization Script

Converts merged model to GGUF format for llama.cpp.
Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

import subprocess
import os
from pathlib import Path

MERGED_PATH = "${c.output_dir}/merged"
OUTPUT_DIR = "${c.output_dir}"
QUANT_TYPE = "${quant}"

def convert_to_gguf():
    # Step 1: Convert to GGUF F16
    print("Converting to GGUF format...")
    f16_path = Path(OUTPUT_DIR) / "lathe-lora-f16.gguf"

    subprocess.run([
        "python", "llama.cpp/convert.py",
        MERGED_PATH,
        "--outfile", str(f16_path),
        "--outtype", "f16",
    ], check=True)

    # Step 2: Quantize
    print(f"Quantizing to {QUANT_TYPE}...")
    quant_path = Path(OUTPUT_DIR) / f"lathe-lora-{QUANT_TYPE.lower()}.gguf"

    subprocess.run([
        "./llama.cpp/quantize",
        str(f16_path),
        str(quant_path),
        QUANT_TYPE,
    ], check=True)

    # Step 3: Cleanup F16 (optional)
    # os.remove(f16_path)

    print(f"Quantized model saved to: {quant_path}")
    return quant_path

if __name__ == "__main__":
    convert_to_gguf()
`;
  }

  private generateAWQScript(): string {
    const c = this.config;

    return `#!/usr/bin/env python3
"""
AWQ Quantization Script

Converts merged model to AWQ format for vLLM.
Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

MERGED_PATH = "${c.output_dir}/merged"
OUTPUT_DIR = "${c.output_dir}/awq"
BITS = ${c.awq_bits || 4}
CALIBRATION_SAMPLES = ${c.calibration_samples || 128}

def quantize_awq():
    print(f"Loading model from {MERGED_PATH}")
    model = AutoAWQForCausalLM.from_pretrained(
        MERGED_PATH,
        device_map="auto",
    )
    tokenizer = AutoTokenizer.from_pretrained(MERGED_PATH)

    # Calibration data - lathe G-code examples
    calibration_data = [
        "O0001\\nG28 U0 W0\\nT0101\\nG50 S3000\\nG96 S200 M03\\nG0 X100 Z5\\nG71 U2 R1\\nG71 P10 Q20 U0.5 W0.1 F0.25\\nN10 G0 X20\\nG1 Z-50\\nX30\\nZ-80\\nN20 X100\\nG70 P10 Q20\\nG28 U0 W0\\nM30",
        "O0002\\nG21 G90\\nG28 U0 W0\\nT0303\\nG50 S2500\\nG97 S1500 M03\\nG76 P020060 Q100 R100\\nG76 X18.5 Z-20 P750 Q200 F1.5\\nG28 U0 W0\\nM30",
    ]

    print(f"Quantizing to AWQ {BITS}-bit...")
    quant_config = {
        "w_bit": BITS,
        "q_group_size": 128,
        "version": "GEMM",
    }

    model.quantize(
        tokenizer,
        quant_config=quant_config,
        calib_data=calibration_data[:CALIBRATION_SAMPLES],
    )

    print(f"Saving to {OUTPUT_DIR}")
    model.save_quantized(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    print("AWQ quantization complete!")

if __name__ == "__main__":
    quantize_awq()
`;
  }

  private generateGPTQScript(): string {
    const c = this.config;

    return `#!/usr/bin/env python3
"""
GPTQ Quantization Script

Converts merged model to GPTQ format.
Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

from transformers import AutoTokenizer, GPTQConfig, AutoModelForCausalLM

MERGED_PATH = "${c.output_dir}/merged"
OUTPUT_DIR = "${c.output_dir}/gptq"
BITS = ${c.gptq_bits || 4}

def quantize_gptq():
    print(f"Loading model from {MERGED_PATH}")
    tokenizer = AutoTokenizer.from_pretrained(MERGED_PATH)

    gptq_config = GPTQConfig(
        bits=BITS,
        dataset="c4",
        tokenizer=tokenizer,
    )

    model = AutoModelForCausalLM.from_pretrained(
        MERGED_PATH,
        quantization_config=gptq_config,
        device_map="auto",
    )

    print(f"Saving to {OUTPUT_DIR}")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    print("GPTQ quantization complete!")

if __name__ == "__main__":
    quantize_gptq()
`;
  }

  private generateFP16Script(): string {
    return `#!/usr/bin/env python3
"""
FP16 Export Script

Exports merged model in FP16 format.
Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

# The merge script already outputs FP16.
# No additional quantization needed.
print("Model is already in FP16 format after merge.")
print("Output path: ${this.config.output_dir}/merged")
`;
  }

  // --------------------------------------------------------------------------
  // Combined Script
  // --------------------------------------------------------------------------

  generateFullPipeline(): string {
    return `#!/usr/bin/env python3
"""
LatheLoRA Full Merge + Quantize Pipeline

Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

import subprocess
import sys
from pathlib import Path

def run_step(name: str, script_path: str):
    print(f"\\n{'='*60}")
    print(f"Step: {name}")
    print(f"{'='*60}\\n")

    result = subprocess.run([sys.executable, script_path])
    if result.returncode != 0:
        print(f"Error in step: {name}")
        sys.exit(1)

def main():
    scripts_dir = Path("${this.config.output_dir}")

    # Step 1: Merge
    run_step("Merge LoRA", str(scripts_dir / "merge_lora.py"))

    # Step 2: Quantize
    run_step("Quantize (${this.config.output_format})", str(scripts_dir / "quantize.py"))

    print("\\n" + "="*60)
    print("Pipeline complete!")
    print("="*60)

if __name__ == "__main__":
    main()
`;
  }

  // --------------------------------------------------------------------------
  // Size Estimation
  // --------------------------------------------------------------------------

  estimateSize(modelName: string): SizeEstimate {
    let fp16Size = 16;

    for (const [key, size] of Object.entries(MODEL_FP16_SIZES)) {
      if (modelName.toLowerCase().includes(key)) {
        fp16Size = size;
        break;
      }
    }

    let estimatedSize: number;
    const format = this.config.output_format;

    switch (format) {
      case "gguf":
        const quant = this.config.gguf_quant || "Q4_K_M";
        estimatedSize = fp16Size * GGUF_SIZE_MULTIPLIERS[quant];
        break;
      case "awq":
        estimatedSize = fp16Size * (this.config.awq_bits === 8 ? 0.55 : 0.28);
        break;
      case "gptq":
        const gptqMultiplier: Record<number, number> = { 2: 0.14, 3: 0.20, 4: 0.28, 8: 0.55 };
        estimatedSize = fp16Size * (gptqMultiplier[this.config.gptq_bits || 4] || 0.28);
        break;
      default:
        estimatedSize = fp16Size;
    }

    return {
      fp16_size_gb: fp16Size,
      estimated_size_gb: Math.round(estimatedSize * 100) / 100,
      compression_ratio: Math.round((fp16Size / estimatedSize) * 10) / 10,
    };
  }

  // --------------------------------------------------------------------------
  // Validation
  // --------------------------------------------------------------------------

  validateConfig(): { valid: boolean; errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!this.config.base_model) {
      errors.push("base_model is required");
    }

    if (!this.config.adapter_path) {
      errors.push("adapter_path is required");
    }

    if (this.config.output_format === "gguf" && !this.config.gguf_quant) {
      warnings.push("gguf_quant not set, defaulting to Q4_K_M");
    }

    if (this.config.output_format === "awq" && this.config.calibration_samples! < 64) {
      warnings.push("calibration_samples < 64 may hurt AWQ quality");
    }

    if (this.config.push_to_hub && !this.config.hub_model_id) {
      errors.push("hub_model_id required when push_to_hub is true");
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  // --------------------------------------------------------------------------
  // Format Recommendations
  // --------------------------------------------------------------------------

  recommendFormat(useCase: "local" | "server" | "edge"): {
    format: QuantFormat;
    quant?: GGUFQuant;
    reason: string;
  } {
    switch (useCase) {
      case "local":
        return {
          format: "gguf",
          quant: "Q4_K_M",
          reason: "GGUF Q4_K_M: best balance of speed and quality for llama.cpp on consumer GPUs",
        };
      case "server":
        return {
          format: "awq",
          reason: "AWQ 4-bit: optimal for vLLM serving with high throughput",
        };
      case "edge":
        return {
          format: "gguf",
          quant: "Q4_K_S",
          reason: "GGUF Q4_K_S: smallest size for edge deployment on limited memory",
        };
    }
  }

  // --------------------------------------------------------------------------
  // Hub Push Script
  // --------------------------------------------------------------------------

  generateHubPushScript(): string {
    if (!this.config.push_to_hub || !this.config.hub_model_id) {
      return "# Hub push disabled or hub_model_id not set";
    }

    return `#!/usr/bin/env python3
"""
Push to Hugging Face Hub

Generated by LatheLoRAMergeQuantEngine (U-LTH72)
"""

from huggingface_hub import HfApi, upload_folder

HUB_MODEL_ID = "${this.config.hub_model_id}"
OUTPUT_DIR = "${this.config.output_dir}/merged"

def push_to_hub():
    api = HfApi()

    print(f"Pushing to: {HUB_MODEL_ID}")
    upload_folder(
        folder_path=OUTPUT_DIR,
        repo_id=HUB_MODEL_ID,
        repo_type="model",
        commit_message="LatheLoRA merged model",
    )
    print("Push complete!")

if __name__ == "__main__":
    push_to_hub()
`;
  }
}

export const latheLoRAMergeQuantEngine = new LatheLoRAMergeQuantEngine();
