// @ts-nocheck
/**
 * MultiCamStrategyEngineExt — Extended CAM System Strategies
 *
 * Adds 12 additional CAM systems + Mazatrol conversational + Macro programming:
 *   - PowerMill (Autodesk/Delcam)
 *   - CATIA CAM (Dassault Systèmes)
 *   - Cimatron (3D Systems)
 *   - Tebis (Tebis AG)
 *   - WorkNC (Hexagon)
 *   - CAMWorks (HCL Technologies)
 *   - BobCAD-CAM
 *   - Edgecam (Hexagon)
 *   - TopSolid (Missler Software)
 *   - SprutCAM (SprutCAM Tech)
 *   - Mazatrol (Mazak conversational CNC)
 *   - Open Mind hyperMILL (additional cycles not in HyperMillStrategyEngine)
 *   - Macro Programming (parametric G-code cycles)
 *   - Vericut/VQC (simulation-driven optimization)
 *
 * Generated by /autopilot exhaustive toolpath strategy expansion
 */

// ============================================================================
// TYPES
// ============================================================================

export type ExtendedCamSource =
  | "powermill"
  | "catia"
  | "cimatron"
  | "tebis"
  | "worknc"
  | "camworks"
  | "bobcad"
  | "edgecam"
  | "topsolid"
  | "sprutcam"
  | "mazatrol"
  | "macro_programming"
  | "vericut";

export type ExtCamGeometryType =
  | "pocket_2d" | "contour_2d" | "face" | "slot" | "chamfer"
  | "freeform_3d" | "steep_wall" | "flat_area" | "groove" | "rib"
  | "corner" | "turning_external" | "turning_internal" | "turning_groove"
  | "thread" | "hole" | "bore" | "impeller_blade" | "port_inlet"
  | "ruled_surface" | "trimming_edge" | "undercut" | "turbine_blade"
  | "mold_core" | "mold_cavity" | "electrode" | "tire_mold"
  | "blisk" | "medical_implant" | "thin_wall" | "deep_cavity";

export type ExtCamOperationGoal =
  | "roughing" | "finishing" | "semi_finishing" | "rest_machining"
  | "drilling" | "adaptive_clearing" | "deburring"
  | "conversational" | "macro_cycle" | "simulation_optimize";

export interface ExtCamStrategyInput {
  camSystem: ExtendedCamSource;
  geometryType: ExtCamGeometryType;
  operationGoal: ExtCamOperationGoal;
  materialGroup?: string;
  toolDiameterMm?: number;
  wallAngleDeg?: number;
  hasPreviousRoughing?: boolean;
  axisCount?: 3 | 4 | 5;
}

export interface ExtCamStrategyResult {
  strategyName: string;
  nativeCycleName: string;
  camSystem: ExtendedCamSource;
  description: string;
  suggestedStepdown: number | null;
  suggestedStepover: number | null;
  cuttingMode: "climb" | "conventional" | "zigzag";
  warnings: string[];
  confidence: number;
  equivalentIntents: string[];
  source: string;
}

interface ExtStrategyEntry {
  nativeCycle: string;
  description: string;
  stepdownFactor: number | null;
  stepoverFactor: number | null;
  cuttingMode: "climb" | "conventional" | "zigzag";
  suitableFor: { geometry: ExtCamGeometryType[]; goal: ExtCamOperationGoal[] };
  priority: number;
  equivalentIntents: string[];
  materialNotes?: Record<string, string>;
}

// ============================================================================
// POWERMILL STRATEGIES (Autodesk/Delcam) — 28 strategies
// ============================================================================

const POWERMILL_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Vortex", description: "PowerMill flagship HSM roughing — constant engagement trochoidal. Reduces cycle time 40-60% vs conventional. Automatic engagement control.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d", "slot", "deep_cavity"], goal: ["roughing", "adaptive_clearing"] }, priority: 14, equivalentIntents: ["adaptive_clearing", "rough_3d"], materialNotes: { P: "Full DOC, 8-15% WOC", S: "Reduced DOC, 5-8% WOC, excellent for titanium", H: "Conservative ae, ceramic tooling recommended" } },
  { nativeCycle: "Offset Area Clearance", description: "Traditional 2D pocket roughing with concentric offset passes. Reliable default roughing strategy.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d", "rough_3d"] },
  { nativeCycle: "Raster Area Clearance", description: "Linear zigzag passes across area. Simple, predictable cutting paths. Good for large flat areas.", stepdownFactor: 1.0, stepoverFactor: 0.6, cuttingMode: "zigzag", suitableFor: { geometry: ["face", "flat_area", "freeform_3d"], goal: ["roughing"] }, priority: 7, equivalentIntents: ["rough_3d", "face_mill"] },
  { nativeCycle: "Profile Area Clearance", description: "Z-level offset clearance following part profile. Leaves uniform stock for finishing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Plunge Milling", description: "Axial plunge cuts for deep cavities and hard materials. Converts radial force to axial.", stepdownFactor: null, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["deep_cavity", "pocket_2d"], goal: ["roughing"] }, priority: 8, equivalentIntents: ["plunge_rough"] },
  { nativeCycle: "Rest Roughing", description: "Automatic detection and machining of remaining material from previous operation. Reference tool comparison.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner", "pocket_2d"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Raster Finishing", description: "Linear passes across 3D surface. Uniform scallop height control. Angle control for steep/shallow.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d", "flat_area"], goal: ["finishing", "semi_finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Offset Finishing", description: "Concentric offset passes following surface contour. Good for near-round geometry.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Constant Z Finishing", description: "Waterline/Z-level finishing for steep walls. Uniform step-down between passes.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d", "mold_cavity"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline", "finish_3d"] },
  { nativeCycle: "Steep and Shallow Finishing", description: "Automatic split between waterline (steep) and raster (shallow). Optimal surface finish across all angles.", stepdownFactor: 0.3, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["steep_shallow", "finish_3d"] },
  { nativeCycle: "3D Offset Finishing", description: "Constant cusp-height finishing with offset passes projected onto surface.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["scallop", "finish_3d"] },
  { nativeCycle: "Pencil Finishing", description: "Corner filleting passes along concavities. Removes cusps left by ball-end finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d", "mold_cavity"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["pencil"] },
  { nativeCycle: "Flowline Finishing", description: "UV-flow-based finish passes following surface natural flow lines. Ideal for aerodynamic/automotive surfaces.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "turbine_blade", "impeller_blade"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["flowline", "finish_3d"] },
  { nativeCycle: "Pattern Finishing", description: "Custom-defined finish pattern — project curves onto surface. Spiral, radial, drive-curve modes.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Rib Machining", description: "Dedicated strategy for thin ribs and walls. Alternating sides, progressive depth. Vibration management.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["rib", "thin_wall"], goal: ["roughing", "finishing"] }, priority: 12, equivalentIntents: ["rib_machining"], materialNotes: { S: "Alternate sides, 50% DOC, titanium rib best practice", N: "Full DOC aluminum ribs, high feed" } },
  { nativeCycle: "Port Machining", description: "5-axis port/manifold machining. Automatic axis tilting through port geometry.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["port_inlet", "undercut"], goal: ["roughing", "finishing"] }, priority: 12, equivalentIntents: ["5axis_port"] },
  { nativeCycle: "Blade Finishing", description: "5-axis turbine blade finishing with hub avoidance and fillet blending.", stepdownFactor: null, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["turbine_blade", "impeller_blade"], goal: ["finishing"] }, priority: 13, equivalentIntents: ["5axis_blade"] },
  { nativeCycle: "Swarf Milling", description: "5-axis side-of-tool cutting along ruled surfaces. Maximum surface finish on walls.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["ruled_surface", "steep_wall"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_swarf"] },
  { nativeCycle: "Multi-Axis Roughing", description: "5-axis rough with automatic tilting to avoid collisions. Tool axis interpolation.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "deep_cavity", "undercut"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["5axis_rough"] },
  { nativeCycle: "Multi-Axis Finishing", description: "5-axis finish with tilt control, gouge protection, and smooth axis transitions.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "impeller_blade", "turbine_blade"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "Wire EDM 2-Axis", description: "2-axis wire EDM profiling with skim cuts and auto-threading.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["wire_edm"] },
  { nativeCycle: "Wire EDM 4-Axis", description: "4-axis wire EDM with taper cutting and independent UV paths.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["wire_edm_4axis"] },
  { nativeCycle: "Drilling", description: "Hole making with peck/chip-break cycles, deep hole and gun drilling support.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Electrode Machining", description: "Dedicated EDM electrode milling with spark gap compensation and burn-vector orientation.", stepdownFactor: 0.5, stepoverFactor: 0.2, cuttingMode: "climb", suitableFor: { geometry: ["electrode", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["electrode"] },
  { nativeCycle: "Corner Finishing", description: "Dedicated corner cleaning — rest machining targeting internal radii and concavities.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing", "rest_machining"] }, priority: 10, equivalentIntents: ["corner_finish"] },
  { nativeCycle: "Face Milling", description: "Top surface face milling with zigzag or one-way. Overlap control for uniform finish.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face", "flat_area"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Chamfer Milling", description: "Edge chamfering with angle and depth control.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["chamfer"] },
  { nativeCycle: "Raceline", description: "Machine-optimized finish strategy that computes optimal toolpath considering machine dynamics and axis limits.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["finishing"] }, priority: 13, equivalentIntents: ["finish_3d", "machine_optimized"], materialNotes: { P: "Feed rate optimized for machine jerk limits", H: "Reduced corner feed, preserved surface quality" } },
];

// ============================================================================
// CATIA CAM STRATEGIES (Dassault Systèmes) — 24 strategies
// ============================================================================

const CATIA_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Prismatic Roughing", description: "2.5D pocket roughing with island avoidance and helical entry. CATIA V5/3DEXPERIENCE prismatic machining.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["pocket_2d", "rough_2d"] },
  { nativeCycle: "Prismatic Finishing", description: "2.5D profile finishing with lead-in/out arcs and multi-pass compensation.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d", "pocket_2d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "HSM Roughing", description: "CATIA high-speed machining roughing with constant engagement and trochoidal paths.", stepdownFactor: 1.5, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 13, equivalentIntents: ["adaptive_clearing", "rough_3d"], materialNotes: { P: "Full DOC with ae 10-20%", S: "Reduced ae for superalloys", N: "Aggressive ae for aluminum" } },
  { nativeCycle: "Surface Roughing", description: "3D Z-level roughing for freeform surfaces. Offset or raster pattern selection.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Sweeping", description: "Parallel/zigzag finishing across 3D surface. Angle-based direction control.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing", "semi_finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Z-Level Finishing", description: "Waterline finishing for steep walls. Automatic shallow area avoidance.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Pencil Machining", description: "Concavity tracing for corner cleanup. Automatic fillet detection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "isoParametric Machining", description: "UV parameter-space machining following surface isoparametric curves.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "turbine_blade"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["isocurve", "finish_3d"] },
  { nativeCycle: "Multi-Axis Sweeping", description: "5-axis sweep finishing with automatic tool axis control and collision avoidance.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "impeller_blade", "turbine_blade"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "Multi-Axis Swarf", description: "5-axis side-cutting along ruled surfaces. Full flute engagement on walls.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["ruled_surface"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_swarf"] },
  { nativeCycle: "Multi-Axis Roughing", description: "5-axis roughing with tilt interpolation for undercuts and deep cavities.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "deep_cavity"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["5axis_rough"] },
  { nativeCycle: "Spiral Milling", description: "Inside-out or outside-in spiral passes. Good for circular/near-round pockets.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "finishing"] }, priority: 8, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Facing", description: "Face milling with zigzag passes and overlap control.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face", "flat_area"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Drilling", description: "Point-to-point drilling with peck and chip-break cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Boring", description: "Precision boring cycles with fine feed control.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["bore"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["bore"] },
  { nativeCycle: "Thread Milling", description: "Helical interpolation thread milling.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["thread_mill"] },
  { nativeCycle: "Lathe Roughing", description: "OD/ID turning roughing with constant depth of cut.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Lathe Finishing", description: "OD/ID turning finishing with spring pass.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "Groove Machining", description: "Plunge grooving and face grooving cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove", "groove"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["groove"] },
  { nativeCycle: "Thread Turning", description: "Single/multi-point thread turning with infeed control.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["thread_turn"] },
  { nativeCycle: "Contour Driven", description: "Drive-curve-based machining following user-defined curves projected onto surface.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["drive_curve"] },
  { nativeCycle: "Geodesic Machining", description: "Geodesic paths on surface for uniform cusp height regardless of surface curvature.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["geodesic"] },
  { nativeCycle: "Rest Material Machining", description: "Automatic rest material detection from reference tool and machining of remaining stock.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough", "rest_finish"] },
  { nativeCycle: "Composite Layup Trim", description: "5-axis composite trimming along ply boundaries. Aerospace composite manufacturing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["trimming_edge"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_trim"] },
];

// ============================================================================
// CIMATRON STRATEGIES (3D Systems) — 20 strategies
// ============================================================================

const CIMATRON_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Volume Milling", description: "Cimatron roughing with automatic island and core detection. Mold/die focused.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d", "mold_cavity", "mold_core"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["rough_3d", "pocket_2d"] },
  { nativeCycle: "Rough Geodesic", description: "HSM roughing with geodesic engagement control. Constant chip load maintenance.", stepdownFactor: 1.5, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_cavity"], goal: ["roughing", "adaptive_clearing"] }, priority: 12, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Spiral Roughing", description: "Inside-out spiral roughing for near-round pockets and cavity bottoms.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 8, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Z-Level Roughing", description: "Traditional Z-level offset roughing with corner rounding.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Rest Roughing", description: "Automatic rest material roughing from reference tool comparison.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Parallel Finishing", description: "Linear raster finishing across 3D surfaces with angle control.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d", "flat_area"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Contour Finishing", description: "Waterline Z-level finishing for steep wall regions.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Pencil Finishing", description: "Concavity/fillet tracing for corner cleanup.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Geodesic Finishing", description: "Constant cusp-height finishing using geodesic distance computation.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["geodesic", "scallop"] },
  { nativeCycle: "Clean Between", description: "Clean material between concavities. Advanced rest finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d"], goal: ["finishing", "rest_machining"] }, priority: 10, equivalentIntents: ["rest_finish"] },
  { nativeCycle: "Steep & Shallow", description: "Auto-split between waterline and raster based on wall angle threshold.", stepdownFactor: 0.3, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["steep_shallow"] },
  { nativeCycle: "Mold Parting Line", description: "Automatic mold parting line detection and machining.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["mold_core", "mold_cavity"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["parting_line"] },
  { nativeCycle: "Electrode Milling", description: "EDM electrode with spark gap offset and orbiting strategy.", stepdownFactor: 0.5, stepoverFactor: 0.2, cuttingMode: "climb", suitableFor: { geometry: ["electrode"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["electrode"] },
  { nativeCycle: "5-Axis Tilted", description: "5-axis finishing with automatic tilt away from steep regions.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "5-Axis Swarf", description: "5-axis side-cutting for ruled surfaces.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["ruled_surface"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_swarf"] },
  { nativeCycle: "Drilling", description: "Point-to-point drilling with auto cycle selection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Die Sinking Prep", description: "Combined roughing+finishing for EDM die sinking electrode preparation.", stepdownFactor: 0.5, stepoverFactor: 0.2, cuttingMode: "climb", suitableFor: { geometry: ["electrode", "mold_cavity"], goal: ["roughing", "finishing"] }, priority: 10, equivalentIntents: ["electrode"] },
  { nativeCycle: "Face Milling", description: "Surface facing with overlap control.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "NC Template", description: "User-defined NC template for custom operations. Parametric cycle automation.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing", "finishing"] }, priority: 7, equivalentIntents: ["custom"] },
  { nativeCycle: "Micro Milling", description: "Specialized micro-milling with reduced feeds, fine stepover, and vibration-aware paths.", stepdownFactor: 0.2, stepoverFactor: 0.05, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "electrode"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["micro_finish"], materialNotes: { H: "Micro grain carbide, 50K+ RPM", N: "Diamond-coated micro tools" } },
];

// ============================================================================
// TEBIS STRATEGIES (Tebis AG) — 22 strategies
// ============================================================================

const TEBIS_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Roughing with Rest Material", description: "Tebis intelligent roughing with automatic rest material tracking through all operations.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_cavity", "mold_core"], goal: ["roughing"] }, priority: 11, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "HSC Roughing", description: "High-speed cutting roughing with trochoidal engagement. Optimized for HSC machines.", stepdownFactor: 1.5, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing", "adaptive_clearing"] }, priority: 13, equivalentIntents: ["adaptive_clearing"], materialNotes: { H: "Designed for hardened steel HSC, ceramic/CBN tooling", P: "Full DOC with reduced ae" } },
  { nativeCycle: "Plane Roughing", description: "Z-level planar roughing with automatic core/island detection.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Rest Roughing", description: "Reference tool comparison for rest material removal.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Z-Constant Finishing", description: "Waterline finishing with automatic shallow-area exclusion.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Equidistant Finishing", description: "Constant cusp height finishing across entire surface. Tebis signature quality.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["scallop", "finish_3d"] },
  { nativeCycle: "Optimized Finishing", description: "Machine-kinematics-aware finishing — considers axis limits, jerk, and acceleration for optimal feed rates.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 13, equivalentIntents: ["finish_3d", "machine_optimized"] },
  { nativeCycle: "Pencil Milling", description: "Concavity tracing with automatic radius detection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Parallel Finishing", description: "Linear parallel passes with angle control.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d", "flat_area"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Radial Finishing", description: "Radial passes from center outward. Ideal for near-round geometry.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["radial"] },
  { nativeCycle: "5-Axis Simultaneous", description: "Full 5-axis simultaneous finishing with collision-free tool axis optimization.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "impeller_blade"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "5-Axis Roughing", description: "5-axis roughing with automatic tilting for deep/undercut features.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "deep_cavity"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["5axis_rough"] },
  { nativeCycle: "Barrel Cutter Finishing", description: "Tangent-plane finishing with barrel (circle-segment) cutters. 5-10x stepover increase.", stepdownFactor: null, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "steep_wall"], goal: ["finishing"] }, priority: 13, equivalentIntents: ["barrel_finish"], materialNotes: { P: "5x stepover vs ball end", H: "Reduced cycle time on hardened mold steel" } },
  { nativeCycle: "Tire Mold Finishing", description: "Specialized tire mold profiling with undercut handling and sector-based machining.", stepdownFactor: null, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["tire_mold", "undercut"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["tire_mold"] },
  { nativeCycle: "Deburring", description: "Edge-following deburr path with force control parameters.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["deburring"] }, priority: 9, equivalentIntents: ["deburr"] },
  { nativeCycle: "Drilling", description: "Pattern drilling with auto cycle selection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Face Milling", description: "Face milling with step control.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Cleanup Finishing", description: "Automatic detection and machining of unmachined areas from previous ops.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["finishing", "rest_machining"] }, priority: 10, equivalentIntents: ["rest_finish"] },
  { nativeCycle: "Electrode Machining", description: "EDM electrode preparation with offset compensation.", stepdownFactor: 0.3, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["electrode"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["electrode"] },
  { nativeCycle: "Chamfer Milling", description: "Edge chamfering with angle and depth control.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["chamfer"] },
  { nativeCycle: "NC Template Automation", description: "Tebis NCJob template — parametric automation of complete machining sequences.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "mold_core", "mold_cavity"], goal: ["roughing", "finishing"] }, priority: 8, equivalentIntents: ["template_auto"] },
  { nativeCycle: "Collision-Safe 3+2", description: "Indexed 3+2 machining with automatic orientation for collision avoidance.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "deep_cavity"], goal: ["roughing", "finishing"] }, priority: 10, equivalentIntents: ["3plus2"] },
];

// ============================================================================
// WORKNC STRATEGIES (Hexagon) — 20 strategies
// ============================================================================

const WORKNC_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Auto 5-Axis", description: "WorkNC flagship — automatic 3-to-5 axis conversion. No manual axis definition needed.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "deep_cavity"], goal: ["finishing"] }, priority: 14, equivalentIntents: ["5axis_finish", "auto_5axis"], materialNotes: { S: "Automatic tilt for optimal cutting angle on titanium", H: "Short tool, aggressive tilt for hardened steel" } },
  { nativeCycle: "Waveform Roughing", description: "WorkNC constant-engagement roughing with trochoidal-style paths.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 13, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Global Roughing", description: "Z-level roughing with automatic island handling and corner optimization.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Re-Roughing", description: "Rest material roughing with reference tool stock model.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Planar Finishing", description: "Linear parallel finishing with angle optimization.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d", "flat_area"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Z-Level Finishing", description: "Waterline contour finishing for steep walls.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Contour Remachining", description: "Automatic rest finishing in concavities and corners.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner", "freeform_3d"], goal: ["finishing", "rest_machining"] }, priority: 10, equivalentIntents: ["pencil", "rest_finish"] },
  { nativeCycle: "Drive Curve Finishing", description: "User-defined drive curve projected onto surface.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["drive_curve"] },
  { nativeCycle: "Spiral Finishing", description: "Inside-out or outside-in spiral finishing.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["spiral"] },
  { nativeCycle: "Constant Cusp Finishing", description: "Scallop-height-controlled finishing with geodesic stepover.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["scallop"] },
  { nativeCycle: "5-Axis Auto Tilt Roughing", description: "5-axis roughing with automatic tilt for deep features.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["deep_cavity", "undercut"], goal: ["roughing"] }, priority: 11, equivalentIntents: ["5axis_rough"] },
  { nativeCycle: "5-Axis Swarf", description: "Side-of-tool cutting on ruled surfaces.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["ruled_surface"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_swarf"] },
  { nativeCycle: "5-Axis Impeller", description: "Dedicated impeller blade machining with splitter/hub awareness.", stepdownFactor: null, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["impeller_blade"], goal: ["finishing"] }, priority: 13, equivalentIntents: ["5axis_impeller"] },
  { nativeCycle: "Drilling", description: "Pattern drilling with cycle selection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Face Milling", description: "Surface facing passes.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Chamfer", description: "Edge chamfering.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["chamfer"] },
  { nativeCycle: "Pocket 2D", description: "2D pocket clearing with island detection.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Profile 2D", description: "2D profile/contour milling.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Barrel Cutter Finishing", description: "Circle-segment (barrel/lens) cutter finishing for large stepover on steep walls.", stepdownFactor: null, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["barrel_finish"] },
  { nativeCycle: "Electrode", description: "EDM electrode machining with spark gap management.", stepdownFactor: 0.3, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["electrode"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["electrode"] },
];

// ============================================================================
// CAMWORKS STRATEGIES (HCL Technologies) — 18 strategies
// ============================================================================

const CAMWORKS_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "VoluMill", description: "CAMWorks VoluMill integration — constant engagement roughing with science-based toolpaths.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d", "slot"], goal: ["roughing", "adaptive_clearing"] }, priority: 14, equivalentIntents: ["adaptive_clearing"], materialNotes: { P: "Full DOC, 8-15% ae", S: "60% DOC, 5-8% ae", H: "40% DOC, 5% ae" } },
  { nativeCycle: "OptiRough", description: "CAMWorks native HSM roughing with chip thinning compensation.", stepdownFactor: 1.5, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 12, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Rough Mill", description: "Standard Z-level roughing with offset passes.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d", "pocket_2d"] },
  { nativeCycle: "Contour Mill", description: "2D profile milling with multi-pass and compensation.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Face Mill", description: "Face milling with zigzag passes.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Finish Mill", description: "3D surface finishing with parallel/offset/spiral patterns.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Z-Level Finish", description: "Waterline finishing for steep areas.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Flat Finish", description: "Flat area detection and finishing with face/end mill.", stepdownFactor: null, stepoverFactor: 0.4, cuttingMode: "zigzag", suitableFor: { geometry: ["flat_area"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["flat_finish"] },
  { nativeCycle: "Pencil Mill", description: "Corner and fillet cleanup.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Rest Mill", description: "Rest material roughing/finishing.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough", "rest_finish"] },
  { nativeCycle: "Slot Mill", description: "Full-width slot cutting.", stepdownFactor: 0.5, stepoverFactor: 1.0, cuttingMode: "climb", suitableFor: { geometry: ["slot"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["slot"] },
  { nativeCycle: "Thread Mill", description: "Helical thread milling.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["thread_mill"] },
  { nativeCycle: "Drill", description: "Feature-based drilling with auto-cycle selection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Turn Rough", description: "OD/ID turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Turn Finish", description: "OD/ID turning finishing with spring pass.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "Turn Groove", description: "Plunge and face grooving cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove", "groove"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["groove"] },
  { nativeCycle: "Chamfer Mill", description: "Edge chamfering.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["chamfer"] },
  { nativeCycle: "AFR Pattern", description: "Automatic Feature Recognition — auto-detects machinable features and assigns strategies.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "hole", "slot", "contour_2d", "face"], goal: ["roughing", "finishing", "drilling"] }, priority: 8, equivalentIntents: ["afr_auto"] },
];

// ============================================================================
// BOBCAD-CAM STRATEGIES — 16 strategies
// ============================================================================

const BOBCAD_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Adaptive HSM", description: "BobCAD adaptive roughing with constant chip load.", stepdownFactor: 1.5, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 12, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Advanced Rough", description: "Z-level roughing with island detection and rest tracking.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Z-Level Finish", description: "Waterline finishing.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["waterline"] },
  { nativeCycle: "Parallel Finish", description: "Linear parallel surface finishing.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Equidistant Finish", description: "Constant cusp-height finishing.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["scallop"] },
  { nativeCycle: "Pencil Trace", description: "Corner cleanup.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Pocket", description: "2D pocketing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Profile", description: "2D profiling.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Face", description: "Face milling.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Drill", description: "Drilling with cycle selection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Lathe Rough", description: "OD/ID turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Lathe Finish", description: "OD/ID turning finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "Lathe Groove", description: "Grooving cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove"], goal: ["roughing", "finishing"] }, priority: 8, equivalentIntents: ["groove"] },
  { nativeCycle: "Thread Mill", description: "Helical thread milling.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["thread_mill"] },
  { nativeCycle: "4-Axis Wrap", description: "Wrap-around 4th axis toolpath for cylindrical parts.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["4axis_wrap"] },
  { nativeCycle: "5-Axis Multiaxis", description: "Simultaneous 5-axis with collision avoidance.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["5axis_finish"] },
];

// ============================================================================
// EDGECAM STRATEGIES (Hexagon) — 18 strategies
// ============================================================================

const EDGECAM_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Waveform Roughing", description: "Edgecam flagship constant-engagement roughing. Smooth trochoidal paths with controlled radial depth.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d", "slot"], goal: ["roughing", "adaptive_clearing"] }, priority: 14, equivalentIntents: ["adaptive_clearing"], materialNotes: { P: "Full DOC, 10-15% ae", S: "70% DOC, 5-10% ae for titanium" } },
  { nativeCycle: "Rough Mill", description: "Standard Z-level roughing with offset pattern.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Profile Mill", description: "2D profile milling with compensation.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Face Mill", description: "Face milling.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Slot Mill", description: "Full-width slot cutting.", stepdownFactor: 0.5, stepoverFactor: 1.0, cuttingMode: "climb", suitableFor: { geometry: ["slot"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["slot"] },
  { nativeCycle: "Parallel Lace", description: "Linear parallel finishing passes.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Z-Level Finish", description: "Waterline finishing for steep areas.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall", "freeform_3d"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Pencil Trace", description: "Corner cleanup finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Rest Rough", description: "Rest material roughing.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Constant Cusp", description: "Scallop-height-controlled finishing.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["scallop"] },
  { nativeCycle: "Spiral Finish", description: "Inside-out spiral finishing.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["spiral"] },
  { nativeCycle: "5-Axis Simultaneous", description: "Full 5-axis finishing with collision avoidance.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "Turning Rough", description: "OD/ID turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Turning Finish", description: "OD/ID turning finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "Turning Groove", description: "Grooving cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["groove"] },
  { nativeCycle: "Turning Thread", description: "Thread turning.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["thread_turn"] },
  { nativeCycle: "Drill", description: "Hole-making cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Chamfer", description: "Edge chamfering.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["chamfer"] },
];

// ============================================================================
// TOPSOLID STRATEGIES (Missler Software) — 18 strategies
// ============================================================================

const TOPSOLID_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Roughing Trochoidal", description: "TopSolid constant-engagement HSM roughing.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 13, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Roughing Z-Level", description: "Standard Z-level roughing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Roughing Plunge", description: "Axial plunge roughing for deep features.", stepdownFactor: null, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["deep_cavity"], goal: ["roughing"] }, priority: 8, equivalentIntents: ["plunge_rough"] },
  { nativeCycle: "Re-Roughing", description: "Rest material roughing.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Finishing Parallel", description: "Linear parallel finishing.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Finishing Z-Constant", description: "Waterline finishing.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Finishing Spiral", description: "Spiral finishing from center outward.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["spiral"] },
  { nativeCycle: "Finishing Geodesic", description: "Geodesic constant-cusp finishing.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["geodesic", "scallop"] },
  { nativeCycle: "Pencil", description: "Corner filleting.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Pocketing", description: "2D pocket clearing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Profiling", description: "2D profile milling.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Face Mill", description: "Face milling.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Drilling", description: "Drilling cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Turning Rough", description: "OD/ID turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Turning Finish", description: "OD/ID turning finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "Turning Groove", description: "Grooving cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["groove"] },
  { nativeCycle: "Turning Thread", description: "Thread turning.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["thread_turn"] },
  { nativeCycle: "5-Axis Continuous", description: "Full 5-axis simultaneous machining.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "impeller_blade"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_finish"] },
];

// ============================================================================
// SPRUTCAM STRATEGIES (SprutCAM Tech) — 18 strategies
// ============================================================================

const SPRUTCAM_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Adaptive Clearing", description: "SprutCAM constant engagement roughing with trochoidal paths.", stepdownFactor: 2.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "freeform_3d"], goal: ["roughing", "adaptive_clearing"] }, priority: 13, equivalentIntents: ["adaptive_clearing"] },
  { nativeCycle: "Waterline Roughing", description: "Z-level roughing with offset passes.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Planar Roughing", description: "Raster/zigzag roughing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing"] }, priority: 8, equivalentIntents: ["rough_3d"] },
  { nativeCycle: "Rest Roughing", description: "Rest material from reference tool.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "corner"], goal: ["rest_machining"] }, priority: 10, equivalentIntents: ["rest_rough"] },
  { nativeCycle: "Planar Finishing", description: "Parallel finishing.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "zigzag", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["finish_3d"] },
  { nativeCycle: "Waterline Finishing", description: "Z-level waterline finishing.", stepdownFactor: 0.3, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["steep_wall"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["waterline"] },
  { nativeCycle: "Scallop Finishing", description: "Constant cusp-height finishing.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["scallop"] },
  { nativeCycle: "Pencil", description: "Corner cleanup.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["corner"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["pencil"] },
  { nativeCycle: "Spiral Finishing", description: "Spiral finish from center.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 8, equivalentIntents: ["spiral"] },
  { nativeCycle: "Pocket 2D", description: "2D pocketing.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing"] }, priority: 9, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "Contour 2D", description: "2D profiling.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing"] }, priority: 9, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "Face Mill", description: "Face milling.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "Drilling", description: "Drilling cycles.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "Turning Rough", description: "OD/ID turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "Turning Finish", description: "OD/ID turning finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["finishing"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "5-Axis Swarf", description: "Side-of-tool cutting on ruled surfaces.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["ruled_surface"], goal: ["finishing"] }, priority: 11, equivalentIntents: ["5axis_swarf"] },
  { nativeCycle: "5-Axis Multiaxis", description: "Full 5-axis simultaneous machining. SprutCAM specializes in complex multi-axis.", stepdownFactor: null, stepoverFactor: 0.12, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut", "impeller_blade", "turbine_blade"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["5axis_finish"] },
  { nativeCycle: "Robot Machining", description: "6-axis robot machining with singularity avoidance. SprutCAM robot CAM.", stepdownFactor: null, stepoverFactor: 0.2, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing", "finishing"] }, priority: 10, equivalentIntents: ["robot_machining"] },
];

// ============================================================================
// MAZATROL STRATEGIES (Mazak Conversational CNC) — 22 strategies
// ============================================================================

const MAZATROL_STRATEGIES: ExtStrategyEntry[] = [
  // --- Milling ---
  { nativeCycle: "MAZATROL POCKET", description: "Mazatrol conversational pocket milling. G-code-free pocket definition with automatic ramping and island avoidance. Mazak SMOOTH CNC.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "conversational"] }, priority: 10, equivalentIntents: ["pocket_2d"] },
  { nativeCycle: "MAZATROL LINE", description: "Conversational linear milling — defines start/end points with depth. 2D profile cutting.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["roughing", "finishing", "conversational"] }, priority: 9, equivalentIntents: ["contour_2d"] },
  { nativeCycle: "MAZATROL FACE", description: "Conversational face milling with automatic pass pattern.", stepdownFactor: 0.5, stepoverFactor: 0.7, cuttingMode: "zigzag", suitableFor: { geometry: ["face"], goal: ["roughing", "finishing", "conversational"] }, priority: 9, equivalentIntents: ["face_mill"] },
  { nativeCycle: "MAZATROL SLOT", description: "Conversational slot milling with width/depth/length parameters.", stepdownFactor: 0.5, stepoverFactor: 1.0, cuttingMode: "climb", suitableFor: { geometry: ["slot"], goal: ["roughing", "conversational"] }, priority: 9, equivalentIntents: ["slot"] },
  { nativeCycle: "MAZATROL CHAMFER", description: "Conversational chamfering.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["chamfer"], goal: ["finishing", "conversational"] }, priority: 8, equivalentIntents: ["chamfer"] },
  { nativeCycle: "MAZATROL DRILLING", description: "Conversational drilling with auto-cycle selection (peck, chip-break, deep hole, tapping).", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling", "conversational"] }, priority: 10, equivalentIntents: ["drill"] },
  { nativeCycle: "MAZATROL BORING", description: "Conversational boring cycle.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["bore"], goal: ["finishing", "conversational"] }, priority: 10, equivalentIntents: ["bore"] },
  { nativeCycle: "MAZATROL TAPPING", description: "Conversational tapping with rigid tap support.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing", "conversational"] }, priority: 10, equivalentIntents: ["tap"] },
  { nativeCycle: "SMOOTH MACHINING", description: "Mazak SMOOTH CNC high-speed surface machining. Machine-dynamics-optimized feed control for smooth surface finish.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing"] }, priority: 12, equivalentIntents: ["finish_3d", "machine_optimized"], materialNotes: { P: "SMOOTH Ai thermal compensation active", H: "SMOOTH corner deceleration" } },
  // --- Turning (Mazatrol TURNING) ---
  { nativeCycle: "MAZATROL BAR", description: "Conversational bar turning — roughing and finishing of external cylindrical features.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external"], goal: ["roughing", "conversational"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "MAZATROL BAR FINISH", description: "Conversational bar turning finishing pass with spring pass option.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external"], goal: ["finishing", "conversational"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "MAZATROL BORE", description: "Conversational internal turning roughing.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_internal"], goal: ["roughing", "conversational"] }, priority: 10, equivalentIntents: ["turn_rough"] },
  { nativeCycle: "MAZATROL BORE FINISH", description: "Conversational internal turning finishing.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_internal"], goal: ["finishing", "conversational"] }, priority: 10, equivalentIntents: ["turn_finish"] },
  { nativeCycle: "MAZATROL THREAD", description: "Conversational thread turning with auto lead/infeed calculation.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing", "conversational"] }, priority: 10, equivalentIntents: ["thread_turn"] },
  { nativeCycle: "MAZATROL GROOVE", description: "Conversational grooving — OD/ID/face. Auto plunge/wipe.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove", "groove"], goal: ["roughing", "finishing", "conversational"] }, priority: 9, equivalentIntents: ["groove"] },
  { nativeCycle: "MAZATROL CUTOFF", description: "Conversational part cutoff/parting.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_groove"], goal: ["roughing", "conversational"] }, priority: 9, equivalentIntents: ["parting"] },
  // --- Mill-Turn Mazatrol ---
  { nativeCycle: "MAZATROL MILL-TURN", description: "Conversational mill-turn — combines turning and milling in single setup on INTEGREX/VARIAXIS.", stepdownFactor: 0.5, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "contour_2d", "hole", "turning_external"], goal: ["roughing", "finishing", "drilling", "conversational"] }, priority: 11, equivalentIntents: ["mill_turn"] },
  { nativeCycle: "MAZATROL C-AXIS", description: "Conversational C-axis milling on turning center. Cross-drilling, flats, keyways.", stepdownFactor: 0.5, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "hole", "slot"], goal: ["roughing", "finishing", "drilling", "conversational"] }, priority: 10, equivalentIntents: ["c_axis_mill"] },
  { nativeCycle: "MAZATROL Y-AXIS", description: "Conversational Y-axis milling — off-center features on turning center.", stepdownFactor: 0.5, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "contour_2d"], goal: ["roughing", "finishing", "conversational"] }, priority: 10, equivalentIntents: ["y_axis_mill"] },
  { nativeCycle: "SMOOTH Ai Machining", description: "Mazak SMOOTH Ai — AI-assisted spindle monitoring and feed optimization. Thermal compensation, vibration detection, servo tuning.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing", "finishing"] }, priority: 13, equivalentIntents: ["ai_optimize", "machine_optimized"] },
  { nativeCycle: "DONE ALL-IN-ONE", description: "Mazak DONE IN ONE — complete part machining in single setup across all axes. INTEGREX multi-tasking.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "turning_external", "turning_internal", "hole", "thread"], goal: ["roughing", "finishing", "drilling", "conversational"] }, priority: 12, equivalentIntents: ["done_in_one", "multi_task"] },
  { nativeCycle: "MAZATROL 5-AXIS", description: "Mazatrol conversational 5-axis with VARIAXIS control. Automatic tilting for undercut access.", stepdownFactor: null, stepoverFactor: 0.15, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "undercut"], goal: ["finishing", "conversational"] }, priority: 11, equivalentIntents: ["5axis_finish"] },
];

// ============================================================================
// MACRO PROGRAMMING STRATEGIES (Parametric G-Code) — 20 strategies
// ============================================================================

const MACRO_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Fanuc Custom Macro B - Pocket", description: "Parametric pocket macro using #variables. Adjustable depth, width, corner radius. G65 P-call.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "macro_cycle"] }, priority: 9, equivalentIntents: ["pocket_2d", "macro"] },
  { nativeCycle: "Fanuc Custom Macro B - Circular Pocket", description: "Parametric circular pocket with helical interpolation (G02/G03). Variable diameter and depth.", stepdownFactor: 1.0, stepoverFactor: 0.4, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "bore"], goal: ["roughing", "macro_cycle"] }, priority: 9, equivalentIntents: ["circular_pocket", "macro"] },
  { nativeCycle: "Fanuc Custom Macro B - Thread Mill", description: "G02/G03 helical thread milling macro with pitch parameter. Single-point and multi-point.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["thread"], goal: ["finishing", "macro_cycle"] }, priority: 10, equivalentIntents: ["thread_mill", "macro"] },
  { nativeCycle: "Fanuc Custom Macro B - Bolt Circle", description: "Parametric bolt circle drilling with G65 call. N-holes, diameter, start angle.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling", "macro_cycle"] }, priority: 10, equivalentIntents: ["bolt_circle", "macro"] },
  { nativeCycle: "Fanuc Custom Macro B - Engrave", description: "Text engraving macro with character set. G65 P-call with ASCII parameters.", stepdownFactor: 0.1, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing", "macro_cycle"] }, priority: 8, equivalentIntents: ["engrave", "macro"] },
  { nativeCycle: "Siemens ShopMill Pocket", description: "Siemens 840D ShopMill conversational pocket. Rectangular/circular with islands.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "conversational", "macro_cycle"] }, priority: 10, equivalentIntents: ["pocket_2d", "shopmill"] },
  { nativeCycle: "Siemens ShopMill Contour", description: "ShopMill conversational contour milling.", stepdownFactor: 1.0, stepoverFactor: 0.3, cuttingMode: "climb", suitableFor: { geometry: ["contour_2d"], goal: ["finishing", "conversational", "macro_cycle"] }, priority: 10, equivalentIntents: ["contour_2d", "shopmill"] },
  { nativeCycle: "Siemens ShopTurn", description: "ShopTurn conversational turning with automatic cycle selection.", stepdownFactor: 1.0, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing", "finishing", "conversational"] }, priority: 10, equivalentIntents: ["turn_rough", "shopturn"] },
  { nativeCycle: "Siemens CYCLE800", description: "Siemens 5-axis swivel cycle — automatic frame rotation for 3+2 positioning.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing", "finishing", "macro_cycle"] }, priority: 10, equivalentIntents: ["3plus2", "cycle800"] },
  { nativeCycle: "Haas Macro - Pocket", description: "Haas NGC macro pocket with variable depth and tool comp. M97/M98 subprogram.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "macro_cycle"] }, priority: 9, equivalentIntents: ["pocket_2d", "macro"] },
  { nativeCycle: "Haas Macro - Bolt Pattern", description: "Haas bolt hole pattern macro with variable hole count and diameter.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole"], goal: ["drilling", "macro_cycle"] }, priority: 9, equivalentIntents: ["bolt_circle", "macro"] },
  { nativeCycle: "Okuma OSP - Custom Cycle", description: "Okuma OSP user-defined custom cycle with NAVI parameters. IGF (Interactive Graphic Function).", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d", "contour_2d"], goal: ["roughing", "finishing", "conversational"] }, priority: 9, equivalentIntents: ["custom", "osp_navi"] },
  { nativeCycle: "Heidenhain Contour Pocket", description: "Heidenhain CYCLE247/CYCLE251 pocket milling with SL contour definition.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["pocket_2d"], goal: ["roughing", "macro_cycle"] }, priority: 10, equivalentIntents: ["pocket_2d", "heidenhain"] },
  { nativeCycle: "Heidenhain TCH PROBE", description: "Heidenhain touch probe cycles for in-process measurement. TT140/TS460.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["hole", "contour_2d"], goal: ["finishing", "macro_cycle"] }, priority: 9, equivalentIntents: ["probe", "heidenhain"] },
  { nativeCycle: "Brother Speedio Tapping", description: "Brother Speedio high-speed rigid tapping cycle. 200ms chip-to-chip optimized.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["thread"], goal: ["finishing", "macro_cycle"] }, priority: 10, equivalentIntents: ["tap", "high_speed"] },
  { nativeCycle: "Parametric Trochoidal Slot", description: "Custom macro trochoidal slot milling — variable radius arc segments with G02/G03. Works on any Fanuc-compatible control.", stepdownFactor: 1.0, stepoverFactor: 0.1, cuttingMode: "climb", suitableFor: { geometry: ["slot"], goal: ["roughing", "macro_cycle"] }, priority: 11, equivalentIntents: ["trochoidal_slot", "macro"] },
  { nativeCycle: "Parametric Helical Bore", description: "Helical interpolation bore milling macro. Variable diameter finish with G02 Z-.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["bore"], goal: ["finishing", "macro_cycle"] }, priority: 10, equivalentIntents: ["helical_bore", "macro"] },
  { nativeCycle: "Probing Macro - Part Setup", description: "Multi-point probing for automatic WCS setup. G65 P9xxx on Fanuc, O9xxx subprogram.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["contour_2d"], goal: ["macro_cycle"] }, priority: 9, equivalentIntents: ["probe", "macro"] },
  { nativeCycle: "Parametric Surface Roughing", description: "Custom macro 3D roughing using incremental Z-level with variable stepover. Suitable for manual programming of freeform surfaces.", stepdownFactor: 1.0, stepoverFactor: 0.5, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["roughing", "macro_cycle"] }, priority: 7, equivalentIntents: ["rough_3d", "macro"] },
  { nativeCycle: "AOT Adaptive Override", description: "Adaptive override technology — real-time spindle load monitoring with automatic feed rate adjustment. Controller-level macro using skip signals and analog inputs.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["roughing", "finishing", "macro_cycle"] }, priority: 12, equivalentIntents: ["adaptive_override", "aot", "macro"], materialNotes: { S: "Essential for titanium — prevents overload", H: "Prevents tool breakage in hardened steel" } },
];

// ============================================================================
// VERICUT/VQC STRATEGIES (Simulation-Driven Optimization) — 12 strategies
// ============================================================================

const VERICUT_STRATEGIES: ExtStrategyEntry[] = [
  { nativeCycle: "Force Optimization", description: "Vericut FORCE — physics-based feed rate optimization. Analyzes chip thickness, force, power, deflection per micro-segment. Rewrites NC program with optimized feed rates.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d", "slot"], goal: ["roughing", "finishing", "simulation_optimize"] }, priority: 14, equivalentIntents: ["force_optimize", "simulation"], materialNotes: { P: "15-25% cycle time reduction typical", S: "30-40% reduction, prevents tool overload", H: "Conservative force limits, tool life focus" } },
  { nativeCycle: "Force Turning", description: "Vericut FORCE for turning — optimizes turning feed rates based on chip load and force limits.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "conventional", suitableFor: { geometry: ["turning_external", "turning_internal"], goal: ["roughing", "finishing", "simulation_optimize"] }, priority: 13, equivalentIntents: ["force_optimize", "turn_optimize"] },
  { nativeCycle: "Collision Detection", description: "Full machine simulation with collision checking — tool, holder, spindle, fixture, workpiece. G-code level verification.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "deep_cavity", "undercut"], goal: ["simulation_optimize"] }, priority: 14, equivalentIntents: ["collision_check", "simulation"] },
  { nativeCycle: "Stock Comparison", description: "Compare machined stock vs design model. Detect gouges, excess material, missed areas. Color-mapped deviation display.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["simulation_optimize"] }, priority: 12, equivalentIntents: ["stock_compare", "simulation"] },
  { nativeCycle: "AUTO-DIFF", description: "Automatic comparison of original vs optimized NC programs. Validates FORCE changes preserve geometry.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["simulation_optimize"] }, priority: 11, equivalentIntents: ["auto_diff", "simulation"] },
  { nativeCycle: "Toolpath Review", description: "Visual toolpath review with speed/feed color coding. Identify rapid traverse near workpiece.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["simulation_optimize"] }, priority: 10, equivalentIntents: ["toolpath_review", "simulation"] },
  { nativeCycle: "Multi-Setup Simulation", description: "Full multi-setup simulation with fixture changes, part flipping, and in-process stock tracking.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d", "turning_external"], goal: ["simulation_optimize"] }, priority: 12, equivalentIntents: ["multi_setup", "simulation"] },
  { nativeCycle: "5-Axis Simulation", description: "Full 5-axis machine simulation with kinematic model. Axis limit, singularity, and over-travel detection.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "impeller_blade", "turbine_blade"], goal: ["simulation_optimize"] }, priority: 13, equivalentIntents: ["5axis_simulation"] },
  { nativeCycle: "Tool Wear Simulation", description: "Predictive tool wear modeling based on material removal volume, cutting speed, and engagement.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["simulation_optimize"] }, priority: 11, equivalentIntents: ["wear_simulation"] },
  { nativeCycle: "Cycle Time Analysis", description: "Accurate cycle time prediction including rapids, feed moves, tool changes, and dwell times.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d", "pocket_2d"], goal: ["simulation_optimize"] }, priority: 10, equivalentIntents: ["cycle_time", "simulation"] },
  { nativeCycle: "Machine Dynamics Optimization", description: "Feed rate smoothing based on machine axis acceleration/jerk limits. Prevents axis reversal shocks.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["finishing", "simulation_optimize"] }, priority: 12, equivalentIntents: ["dynamics_optimize", "machine_optimized"] },
  { nativeCycle: "Additive Simulation", description: "Hybrid additive+subtractive simulation — deposit then machine. DED/WAAM process verification.", stepdownFactor: null, stepoverFactor: null, cuttingMode: "climb", suitableFor: { geometry: ["freeform_3d"], goal: ["simulation_optimize"] }, priority: 10, equivalentIntents: ["additive_simulation"] },
];

// ============================================================================
// STRATEGY MAP + FLAGSHIP
// ============================================================================

const EXT_STRATEGY_MAP: Record<ExtendedCamSource, ExtStrategyEntry[]> = {
  powermill: POWERMILL_STRATEGIES,
  catia: CATIA_STRATEGIES,
  cimatron: CIMATRON_STRATEGIES,
  tebis: TEBIS_STRATEGIES,
  worknc: WORKNC_STRATEGIES,
  camworks: CAMWORKS_STRATEGIES,
  bobcad: BOBCAD_STRATEGIES,
  edgecam: EDGECAM_STRATEGIES,
  topsolid: TOPSOLID_STRATEGIES,
  sprutcam: SPRUTCAM_STRATEGIES,
  mazatrol: MAZATROL_STRATEGIES,
  macro_programming: MACRO_STRATEGIES,
  vericut: VERICUT_STRATEGIES,
};

const EXT_FLAGSHIP_STRATEGIES: Record<ExtendedCamSource, string> = {
  powermill: "Vortex",
  catia: "HSM Roughing",
  cimatron: "Rough Geodesic",
  tebis: "Optimized Finishing",
  worknc: "Auto 5-Axis",
  camworks: "VoluMill",
  bobcad: "Adaptive HSM",
  edgecam: "Waveform Roughing",
  topsolid: "Roughing Trochoidal",
  sprutcam: "5-Axis Multiaxis",
  mazatrol: "SMOOTH Ai Machining",
  macro_programming: "AOT Adaptive Override",
  vericut: "Force Optimization",
};

// ============================================================================
// ENGINE CLASS
// ============================================================================

export interface ExtMultiCamStats {
  totalStrategies: number;
  bySystem: Record<ExtendedCamSource, number>;
  calculations: number;
}

export class MultiCamStrategyEngineExt {
  private calculations = 0;

  /**
   * Recommend the best strategy for a given extended CAM system.
   */
  recommend(input: ExtCamStrategyInput): ExtCamStrategyResult {
    this.calculations++;
    const strategies = EXT_STRATEGY_MAP[input.camSystem];
    if (!strategies) {
      return this.notFound(input, `Unknown CAM system: ${input.camSystem}`);
    }

    const candidates = strategies.filter(
      (s) =>
        s.suitableFor.geometry.includes(input.geometryType as any) &&
        s.suitableFor.goal.includes(input.operationGoal as any)
    );

    if (candidates.length === 0) {
      return this.notFound(input, `No strategy for ${input.geometryType}/${input.operationGoal} in ${input.camSystem}`);
    }

    candidates.sort((a, b) => b.priority - a.priority);
    const best = candidates[0];

    const warnings: string[] = [];
    if (input.materialGroup === "S" && input.operationGoal === "roughing") {
      warnings.push("Superalloy roughing: reduce speed 30-40%, use through-spindle coolant");
    }
    if (input.materialGroup === "H" && best.stepdownFactor && best.stepdownFactor > 1.5) {
      warnings.push("Hardened material: reduce depth of cut to 50%");
    }
    if (input.axisCount && input.axisCount < 5 && best.equivalentIntents.some((i) => i.startsWith("5axis"))) {
      warnings.push(`Strategy requires 5-axis but machine has ${input.axisCount} axes`);
    }

    let stepdown = best.stepdownFactor;
    let stepover = best.stepoverFactor;
    if (input.materialGroup === "S" || input.materialGroup === "H") {
      if (stepdown !== null) stepdown = Math.min(stepdown, 1.0);
      if (stepover !== null) stepover = Math.min(stepover, stepover * 0.7);
    }

    return {
      strategyName: best.nativeCycle,
      nativeCycleName: best.nativeCycle,
      camSystem: input.camSystem,
      description: best.description,
      suggestedStepdown: stepdown,
      suggestedStepover: stepover,
      cuttingMode: best.cuttingMode,
      warnings,
      confidence: this.calcConfidence(best, input),
      equivalentIntents: best.equivalentIntents,
      source: `multicam_ext:${input.camSystem}`,
    };
  }

  /**
   * List all strategies for a given extended CAM system.
   */
  listStrategies(camSystem: ExtendedCamSource): ExtCamStrategyResult[] {
    const strategies = EXT_STRATEGY_MAP[camSystem];
    if (!strategies) return [];
    return strategies.map((s) => ({
      strategyName: s.nativeCycle,
      nativeCycleName: s.nativeCycle,
      camSystem,
      description: s.description,
      suggestedStepdown: s.stepdownFactor,
      suggestedStepover: s.stepoverFactor,
      cuttingMode: s.cuttingMode,
      warnings: [],
      confidence: 1.0,
      equivalentIntents: s.equivalentIntents,
      source: `multicam_ext:${camSystem}`,
    }));
  }

  /**
   * Get flagship strategy for an extended CAM system.
   */
  getFlagship(camSystem: ExtendedCamSource): ExtCamStrategyResult | null {
    const name = EXT_FLAGSHIP_STRATEGIES[camSystem];
    if (!name) return null;
    const strategies = EXT_STRATEGY_MAP[camSystem];
    const entry = strategies?.find((s) => s.nativeCycle === name);
    if (!entry) return null;
    return {
      strategyName: entry.nativeCycle,
      nativeCycleName: entry.nativeCycle,
      camSystem,
      description: entry.description,
      suggestedStepdown: entry.stepdownFactor,
      suggestedStepover: entry.stepoverFactor,
      cuttingMode: entry.cuttingMode,
      warnings: [],
      confidence: 1.0,
      equivalentIntents: entry.equivalentIntents,
      source: `multicam_ext:${camSystem}`,
    };
  }

  /**
   * Compare across all extended CAM systems.
   */
  compareAcrossSystems(
    geometryType: ExtCamGeometryType,
    operationGoal: ExtCamOperationGoal
  ): Record<ExtendedCamSource, ExtCamStrategyResult | null> {
    const result: Record<string, ExtCamStrategyResult | null> = {};
    for (const sys of Object.keys(EXT_STRATEGY_MAP) as ExtendedCamSource[]) {
      const rec = this.recommend({ camSystem: sys, geometryType, operationGoal });
      result[sys] = rec.confidence > 0 ? rec : null;
    }
    return result as Record<ExtendedCamSource, ExtCamStrategyResult | null>;
  }

  /**
   * Get portability intents for a native cycle.
   */
  getPortabilityIntents(camSystem: ExtendedCamSource, nativeCycleName: string): string[] {
    const strategies = EXT_STRATEGY_MAP[camSystem];
    if (!strategies) return [];
    const entry = strategies.find((s) => s.nativeCycle === nativeCycleName);
    return entry?.equivalentIntents ?? [];
  }

  /**
   * Get stats.
   */
  stats(): ExtMultiCamStats {
    const bySystem: Record<string, number> = {};
    let total = 0;
    for (const [sys, strats] of Object.entries(EXT_STRATEGY_MAP)) {
      bySystem[sys] = strats.length;
      total += strats.length;
    }
    return {
      totalStrategies: total,
      bySystem: bySystem as Record<ExtendedCamSource, number>,
      calculations: this.calculations,
    };
  }

  /**
   * List all supported extended CAM systems.
   */
  listSystems(): ExtendedCamSource[] {
    return Object.keys(EXT_STRATEGY_MAP) as ExtendedCamSource[];
  }

  /**
   * Search strategies across all systems by keyword.
   */
  search(query: string, limit = 20): ExtCamStrategyResult[] {
    const q = query.toLowerCase();
    const results: ExtCamStrategyResult[] = [];
    for (const [sys, strats] of Object.entries(EXT_STRATEGY_MAP)) {
      for (const s of strats) {
        if (results.length >= limit) break;
        if (
          s.nativeCycle.toLowerCase().includes(q) ||
          s.description.toLowerCase().includes(q) ||
          s.equivalentIntents.some((i) => i.includes(q))
        ) {
          results.push({
            strategyName: s.nativeCycle,
            nativeCycleName: s.nativeCycle,
            camSystem: sys as ExtendedCamSource,
            description: s.description,
            suggestedStepdown: s.stepdownFactor,
            suggestedStepover: s.stepoverFactor,
            cuttingMode: s.cuttingMode,
            warnings: [],
            confidence: 1.0,
            equivalentIntents: s.equivalentIntents,
            source: `multicam_ext:${sys}`,
          });
        }
      }
    }
    return results;
  }

  // ── Private ─────────────────────────────────────────────────────────────

  private calcConfidence(entry: ExtStrategyEntry, input: ExtCamStrategyInput): number {
    let c = 0.8;
    if (input.materialGroup) c += 0.05;
    if (input.toolDiameterMm) c += 0.05;
    if (entry.priority >= 12) c += 0.05;
    if (entry.materialNotes && input.materialGroup && entry.materialNotes[input.materialGroup]) c += 0.05;
    return Math.min(c, 1.0);
  }

  private notFound(input: ExtCamStrategyInput, msg: string): ExtCamStrategyResult {
    return {
      strategyName: "none",
      nativeCycleName: "none",
      camSystem: input.camSystem,
      description: msg,
      suggestedStepdown: null,
      suggestedStepover: null,
      cuttingMode: "climb",
      warnings: [msg],
      confidence: 0,
      equivalentIntents: [],
      source: `multicam_ext:${input.camSystem}`,
    };
  }
}

// ── Singleton ───────────────────────────────────────────────────────────────
export const multiCamStrategyEngineExt = new MultiCamStrategyEngineExt();
