/**
 * NXCodeGeneratorEngine — U-CADC14 (PHASE-4)
 *
 * Python code generator for Siemens NX using NXOpen API.
 * Extends UnifiedCADCodeGeneratorBase for consistent interface across CAD systems.
 *
 * NXOpen Python modules:
 *   - NXOpen          — Core application, session, part access
 *   - NXOpen.UF       — User Function (legacy but still used)
 *   - NXOpen.Features — Feature creation (extrude, revolve, hole, etc.)
 *   - NXOpen.GeometricUtilities — Geometry helpers
 *   - NXOpen.Assemblies — Assembly operations
 *
 * NX uses millimeters internally (no unit conversion needed for mm).
 * For inches: multiply by 25.4 before passing to NXOpen.
 *
 * @module engines/NXCodeGeneratorEngine
 */

import {
  UnifiedCADCodeGeneratorBase,
  type CADEmitter,
} from "./UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADOperation,
  CADOperationKind,
  CADScript,
  CADExecutionResult,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";

// ── Context ──────────────────────────────────────────────────────────────────

export interface NXGenerationContext {
  projectName: string;
  units: "mm" | "in";
  targetVersion?: "NX12" | "NX1847" | "NX1872" | "NX1926" | "NX2007" | "NX2206" | "NX2306";
  outputDir?: string;
  partTemplate?: string;
  useUserFunction?: boolean;
}

// ── Supported operations ─────────────────────────────────────────────────────

const NX_SUPPORTED_OPS: ReadonlySet<CADOperationKind> = new Set<CADOperationKind>([
  // Sketch
  "sketch_create",
  "sketch_line",
  "sketch_circle",
  "sketch_arc",
  "sketch_rectangle",
  "sketch_polygon",
  "sketch_spline",
  "sketch_ellipse",
  "sketch_slot",
  "sketch_centerline",
  "sketch_dimension",
  "sketch_constraint",
  "sketch_mirror",
  "sketch_offset",
  "sketch_trim",
  "sketch_extend",
  "sketch_fillet",
  "sketch_chamfer",
  // Feature
  "feature_extrude",
  "feature_revolve",
  "feature_sweep",
  "feature_loft",
  "feature_hole",
  "feature_pocket",
  "feature_boss",
  "feature_rib",
  "feature_fillet",
  "feature_chamfer",
  "feature_shell",
  "feature_draft",
  "feature_thread",
  "feature_pattern_linear",
  "feature_pattern_circular",
  "feature_mirror",
  // Surface
  "surface_extrude",
  "surface_revolve",
  "surface_sweep",
  "surface_loft",
  "surface_fill",
  "surface_offset",
  "surface_thicken",
  "surface_trim",
  "surface_extend",
  // Boolean
  "boolean_union",
  "boolean_subtract",
  "boolean_intersect",
  // Transform
  "transform_move",
  "transform_rotate",
  "transform_scale",
  "transform_mirror",
  "transform_pattern_linear",
  "transform_pattern_circular",
  // Export/Import
  "export_step",
  "export_iges",
  "export_stl",
  "export_parasolid",
  "export_jt",
  "import_step",
  "import_iges",
  "import_parasolid",
  "import_jt",
  // Assembly
  "assembly_create",
  "assembly_add_component",
  "assembly_constrain",
  "assembly_explode",
]);

// ── Engine ───────────────────────────────────────────────────────────────────

export class NXCodeGeneratorEngine extends UnifiedCADCodeGeneratorBase<NXGenerationContext> {
  readonly cadSystem: CADSystemId = "nx";
  readonly capabilities: CADCapabilityMatrix = {
    cadSystem: "nx",
    supportedOps: new Set(NX_SUPPORTED_OPS),
    // emit code converts coords to mm (UNIT_FACTOR = in?25.4:1.0; NXOpen.Part.Units.Millimeters);
    // angles converted deg->rad via math.radians() before NXOpen (host expects rad). Python NXOpen -> subprocess.
    nativeLengthUnit: "mm",
    nativeAngleUnit: "rad",
    requiresSubprocess: true,
    typicalLatencyMs: 1500,
    supportsParametric: true,
    supportsUndo: true,
    maxComplexity: 5000,
    version: "NX2306",
  };

  // ── Preamble ─────────────────────────────────────────────────────────────

  protected preamble(ctx: NXGenerationContext | undefined, emitter: CADEmitter): void {
    const version = ctx?.targetVersion ?? "NX2306";
    const units = ctx?.units ?? "mm";
    const useUF = ctx?.useUserFunction ?? false;

    emitter.require("import NXOpen");
    emitter.require("import NXOpen.Features");
    emitter.require("import NXOpen.GeometricUtilities");
    emitter.require("import NXOpen.Assemblies");
    if (useUF) {
      emitter.require("import NXOpen.UF");
    }

    emitter.line("# NXOpen Python Journal");
    emitter.line(`# Generated by PRISM NXCodeGeneratorEngine (U-CADC14)`);
    emitter.line(`# Target: Siemens NX ${version}`);
    emitter.line(`# Units: ${units}`);
    emitter.line();
    emitter.line("import NXOpen");
    emitter.line("import NXOpen.Features");
    emitter.line("import NXOpen.GeometricUtilities");
    emitter.line("import NXOpen.Assemblies");
    if (useUF) {
      emitter.line("import NXOpen.UF");
    }
    emitter.line("import math");
    emitter.line();

    // Unit factor: NX uses mm internally
    const unitFactor = units === "in" ? 25.4 : 1.0;
    emitter.line(`UNIT_FACTOR = ${unitFactor}  # ${units} → mm`);
    emitter.parameter("UNIT_FACTOR", unitFactor, units, "Unit conversion factor");
    emitter.line();

    emitter.line("def main():");
    emitter.indent = "    ";

    // Session and work part setup
    emitter.line("session = NXOpen.Session.GetSession()");
    emitter.line("work_part = session.Parts.Work");
    emitter.line("if work_part is None:");
    emitter.indent = "        ";
    emitter.line('base_units = NXOpen.Part.Units.Millimeters if UNIT_FACTOR == 1 else NXOpen.Part.Units.Inches');
    if (ctx?.partTemplate) {
      emitter.line(`work_part = session.Parts.NewDisplay("${ctx.partTemplate}", base_units)`);
    } else {
      emitter.line('work_part = session.Parts.NewDisplay("prism_part", base_units)');
    }
    emitter.indent = "    ";
    emitter.line();
    emitter.line("# Feature collection for boolean operations");
    emitter.line("_features = []");
    emitter.line("_current_sketch = None");
    emitter.line("_current_body = None");
    emitter.line();
  }

  // ── Epilogue ─────────────────────────────────────────────────────────────

  protected epilogue(ctx: NXGenerationContext | undefined, emitter: CADEmitter): void {
    emitter.line();
    emitter.line("# Save and update display");
    emitter.line("work_part.Save(NXOpen.BasePart.SaveComponents.TrueValue, NXOpen.BasePart.CloseAfterSave.FalseValue)");
    emitter.line("session.ApplicationSwitchImmediate('UG_APP_MODELING')");
    emitter.line();

    // Close main()
    emitter.indent = "";
    emitter.line();
    emitter.line('if __name__ == "__main__":');
    emitter.line("    main()");
  }

  // ── Per-op emission ──────────────────────────────────────────────────────

  protected emitOp(
    op: CADOperation,
    idx: number,
    ctx: NXGenerationContext | undefined,
    emitter: CADEmitter,
  ): void {
    const a = op.args;
    const safeNum = (v: unknown, def = 0): number => {
      if (typeof v === "number" && Number.isFinite(v)) return v;
      return def;
    };
    const safeStr = (v: unknown, def = ""): string => {
      if (typeof v === "string") return v;
      return def;
    };

    switch (op.kind) {
      // ─── Sketch ────────────────────────────────────────────────────────
      case "sketch_create": {
        const plane = safeStr(a.plane, "XY");
        emitter.line(`# Sketch on ${plane} plane`);
        emitter.line(`sketch_builder = work_part.Sketches.CreateSketchInPlaceBuilder2(None)`);
        if (plane === "XY") {
          emitter.line(`sketch_plane = work_part.Datums.FindObject("DATUM_CSYS(0) XY plane")`);
        } else if (plane === "XZ") {
          emitter.line(`sketch_plane = work_part.Datums.FindObject("DATUM_CSYS(0) XZ plane")`);
        } else {
          emitter.line(`sketch_plane = work_part.Datums.FindObject("DATUM_CSYS(0) YZ plane")`);
        }
        emitter.line(`sketch_builder.PlaneReference = sketch_plane`);
        emitter.line(`_current_sketch = sketch_builder.Commit()`);
        emitter.line(`sketch_builder.Destroy()`);
        emitter.line(`_current_sketch.Activate(NXOpen.Sketch.ViewReorient.TrueValue)`);
        break;
      }

      case "sketch_line": {
        const x1 = safeNum(a.x1);
        const y1 = safeNum(a.y1);
        const x2 = safeNum(a.x2);
        const y2 = safeNum(a.y2);
        emitter.line(`line_start = NXOpen.Point3d(${x1}*UNIT_FACTOR, ${y1}*UNIT_FACTOR, 0)`);
        emitter.line(`line_end = NXOpen.Point3d(${x2}*UNIT_FACTOR, ${y2}*UNIT_FACTOR, 0)`);
        emitter.line(`_current_sketch.CreateLine(line_start, line_end)`);
        break;
      }

      case "sketch_circle": {
        const cx = safeNum(a.centerX);
        const cy = safeNum(a.centerY);
        const r = safeNum(a.radius, 10);
        emitter.line(`circle_center = NXOpen.Point3d(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
        emitter.line(`circle_axis = NXOpen.Vector3d(0, 0, 1)`);
        emitter.line(`_current_sketch.CreateCircle(circle_center, circle_axis, ${r}*UNIT_FACTOR)`);
        emitter.parameter("circle_radius", r, ctx?.units ?? "mm");
        break;
      }

      case "sketch_arc": {
        const cx = safeNum(a.centerX);
        const cy = safeNum(a.centerY);
        const r = safeNum(a.radius, 10);
        const startAngle = safeNum(a.startAngle, 0);
        const endAngle = safeNum(a.endAngle, 90);
        emitter.line(`arc_center = NXOpen.Point3d(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
        emitter.line(`arc_axis = NXOpen.Vector3d(0, 0, 1)`);
        emitter.line(`_current_sketch.CreateArc(arc_center, arc_axis, ${r}*UNIT_FACTOR, math.radians(${startAngle}), math.radians(${endAngle}))`);
        break;
      }

      case "sketch_rectangle": {
        const x = safeNum(a.x);
        const y = safeNum(a.y);
        const w = safeNum(a.width, 100);
        const h = safeNum(a.height, 50);
        emitter.line(`# Rectangle at (${x}, ${y}) size ${w}x${h}`);
        emitter.line(`rect_p1 = NXOpen.Point3d(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
        emitter.line(`rect_p2 = NXOpen.Point3d(${x + w}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
        emitter.line(`rect_p3 = NXOpen.Point3d(${x + w}*UNIT_FACTOR, ${y + h}*UNIT_FACTOR, 0)`);
        emitter.line(`rect_p4 = NXOpen.Point3d(${x}*UNIT_FACTOR, ${y + h}*UNIT_FACTOR, 0)`);
        emitter.line(`_current_sketch.CreateLine(rect_p1, rect_p2)`);
        emitter.line(`_current_sketch.CreateLine(rect_p2, rect_p3)`);
        emitter.line(`_current_sketch.CreateLine(rect_p3, rect_p4)`);
        emitter.line(`_current_sketch.CreateLine(rect_p4, rect_p1)`);
        emitter.parameter("rect_width", w, ctx?.units ?? "mm");
        emitter.parameter("rect_height", h, ctx?.units ?? "mm");
        break;
      }

      case "sketch_polygon": {
        const cx = safeNum(a.centerX);
        const cy = safeNum(a.centerY);
        const r = safeNum(a.radius, 30);
        const sides = Math.max(3, safeNum(a.sides, 6));
        emitter.line(`# Regular polygon: ${sides} sides, radius ${r}`);
        emitter.line(`polygon_pts = []`);
        emitter.line(`for i in range(${sides}):`);
        emitter.line(`    angle = 2 * math.pi * i / ${sides}`);
        emitter.line(`    px = ${cx}*UNIT_FACTOR + ${r}*UNIT_FACTOR * math.cos(angle)`);
        emitter.line(`    py = ${cy}*UNIT_FACTOR + ${r}*UNIT_FACTOR * math.sin(angle)`);
        emitter.line(`    polygon_pts.append(NXOpen.Point3d(px, py, 0))`);
        emitter.line(`for i in range(${sides}):`);
        emitter.line(`    _current_sketch.CreateLine(polygon_pts[i], polygon_pts[(i+1) % ${sides}])`);
        break;
      }

      case "sketch_spline": {
        const points = Array.isArray(a.points) ? a.points : [[0, 0, 0], [10, 10, 0], [20, 0, 0]];
        emitter.line(`# Spline through ${points.length} points`);
        emitter.line(`spline_pts = [`);
        for (const pt of points) {
          const [px, py, pz] = Array.isArray(pt) ? pt : [0, 0, 0];
          emitter.line(`    NXOpen.Point3d(${px}*UNIT_FACTOR, ${py}*UNIT_FACTOR, ${pz}*UNIT_FACTOR),`);
        }
        emitter.line(`]`);
        emitter.line(`_current_sketch.CreateSpline(spline_pts, NXOpen.Sketch.SplineMethod.ThroughPoints)`);
        break;
      }

      case "sketch_ellipse": {
        const cx = safeNum(a.centerX);
        const cy = safeNum(a.centerY);
        const major = safeNum(a.majorRadius, 20);
        const minor = safeNum(a.minorRadius, 10);
        emitter.line(`ellipse_center = NXOpen.Point3d(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
        emitter.line(`ellipse_major = NXOpen.Vector3d(1, 0, 0)`);
        emitter.line(`_current_sketch.CreateEllipse(ellipse_center, ${major}*UNIT_FACTOR, ${minor}*UNIT_FACTOR, ellipse_major)`);
        break;
      }

      case "sketch_slot": {
        const cx = safeNum(a.centerX);
        const cy = safeNum(a.centerY);
        const length = safeNum(a.length, 40);
        const width = safeNum(a.width, 10);
        const angle = safeNum(a.angle, 0);
        emitter.line(`# Slot at (${cx}, ${cy}), length=${length}, width=${width}`);
        emitter.line(`slot_builder = work_part.Sketches.CreateSlotBuilder(_current_sketch)`);
        emitter.line(`slot_builder.SlotType = NXOpen.Sketches.SlotBuilder.SlotTypes.Straight`);
        emitter.line(`slot_builder.Length.Value = ${length}*UNIT_FACTOR`);
        emitter.line(`slot_builder.Width.Value = ${width}*UNIT_FACTOR`);
        emitter.line(`slot_builder.Angle.Value = ${angle}`);
        emitter.line(`slot_builder.CenterPoint = NXOpen.Point3d(${cx}*UNIT_FACTOR, ${cy}*UNIT_FACTOR, 0)`);
        emitter.line(`slot_builder.Commit()`);
        emitter.line(`slot_builder.Destroy()`);
        break;
      }

      case "sketch_centerline":
      case "sketch_dimension":
      case "sketch_constraint":
      case "sketch_mirror":
      case "sketch_offset":
      case "sketch_trim":
      case "sketch_extend":
      case "sketch_fillet":
      case "sketch_chamfer":
        emitter.line(`# ${op.kind} — TODO: implement NXOpen equivalent`);
        emitter.warn(`${op.kind} not fully implemented`, "info");
        break;

      // ─── Features ──────────────────────────────────────────────────────
      case "feature_extrude": {
        const depth = safeNum(a.depth, 10);
        const dir = safeStr(a.direction, "positive");
        const signedDepth = dir === "negative" ? -depth : depth;
        emitter.line(`# Extrude sketch ${signedDepth}mm`);
        emitter.line(`_current_sketch.Deactivate(NXOpen.Sketch.ViewReorient.TrueValue, NXOpen.Sketch.UpdateLevel.Model)`);
        emitter.line(`extrude_builder = work_part.Features.CreateExtrudeBuilder(None)`);
        emitter.line(`extrude_builder.Section.AddToSection([], _current_sketch, None, None, None, None, 0)`);
        emitter.line(`extrude_builder.Limits.StartExtend.Value.Value = 0`);
        emitter.line(`extrude_builder.Limits.EndExtend.Value.Value = ${Math.abs(signedDepth)}*UNIT_FACTOR`);
        if (signedDepth < 0) {
          emitter.line(`extrude_builder.Direction = NXOpen.Features.ExtrudeBuilder.DirectionType.Reverse`);
        }
        emitter.line(`_features.append(extrude_builder.Commit())`);
        emitter.line(`_current_body = _features[-1].GetBodies()[0]`);
        emitter.line(`extrude_builder.Destroy()`);
        emitter.parameter("extrude_depth", depth, ctx?.units ?? "mm");
        break;
      }

      case "feature_revolve": {
        const angle = safeNum(a.angle, 360);
        const axisX = safeNum(a.axisX, 1);
        const axisY = safeNum(a.axisY, 0);
        const axisZ = safeNum(a.axisZ, 0);
        emitter.line(`# Revolve ${angle}° around axis (${axisX}, ${axisY}, ${axisZ})`);
        emitter.line(`_current_sketch.Deactivate(NXOpen.Sketch.ViewReorient.TrueValue, NXOpen.Sketch.UpdateLevel.Model)`);
        emitter.line(`revolve_builder = work_part.Features.CreateRevolveBuilder(None)`);
        emitter.line(`revolve_builder.Section.AddToSection([], _current_sketch, None, None, None, None, 0)`);
        emitter.line(`axis_origin = NXOpen.Point3d(0, 0, 0)`);
        emitter.line(`axis_dir = NXOpen.Vector3d(${axisX}, ${axisY}, ${axisZ})`);
        emitter.line(`revolve_builder.Axis = NXOpen.Axis(axis_origin, axis_dir)`);
        emitter.line(`revolve_builder.Limits.StartExtend.Value.Value = 0`);
        emitter.line(`revolve_builder.Limits.EndExtend.Value.Value = ${angle}`);
        emitter.line(`_features.append(revolve_builder.Commit())`);
        emitter.line(`_current_body = _features[-1].GetBodies()[0]`);
        emitter.line(`revolve_builder.Destroy()`);
        emitter.parameter("revolve_angle", angle, "deg");
        break;
      }

      case "feature_sweep": {
        emitter.line(`# Sweep along path`);
        emitter.line(`sweep_builder = work_part.Features.CreateSweepBuilder(None)`);
        emitter.line(`sweep_builder.Section.AddToSection([], _current_sketch, None, None, None, None, 0)`);
        emitter.line(`# Path would be set from guide curve`);
        emitter.line(`_features.append(sweep_builder.Commit())`);
        emitter.line(`sweep_builder.Destroy()`);
        break;
      }

      case "feature_loft": {
        emitter.line(`# Loft between profiles`);
        emitter.line(`loft_builder = work_part.Features.CreateThroughCurvesBuilder(None)`);
        emitter.line(`# Sections would be added here`);
        emitter.line(`_features.append(loft_builder.Commit())`);
        emitter.line(`loft_builder.Destroy()`);
        break;
      }

      case "feature_hole": {
        const x = safeNum(a.x);
        const y = safeNum(a.y);
        const d = safeNum(a.diameter, 10);
        const depth = safeNum(a.depth, 20);
        emitter.line(`# Hole at (${x}, ${y}), D=${d}, depth=${depth}`);
        emitter.line(`hole_builder = work_part.Features.CreateHoleBuilder(None)`);
        emitter.line(`hole_builder.Type = NXOpen.Features.HoleBuilder.Types.Simple`);
        emitter.line(`hole_builder.HoleDiameter.Value = ${d}*UNIT_FACTOR`);
        emitter.line(`hole_builder.Depth.Value = ${depth}*UNIT_FACTOR`);
        emitter.line(`hole_point = NXOpen.Point3d(${x}*UNIT_FACTOR, ${y}*UNIT_FACTOR, 0)`);
        emitter.line(`hole_builder.HolePosition = hole_point`);
        emitter.line(`_features.append(hole_builder.Commit())`);
        emitter.line(`hole_builder.Destroy()`);
        emitter.parameter("hole_diameter", d, ctx?.units ?? "mm");
        emitter.parameter("hole_depth", depth, ctx?.units ?? "mm");
        break;
      }

      case "feature_pocket": {
        const depth = safeNum(a.depth, 10);
        emitter.line(`# Pocket (cut extrude) depth=${depth}`);
        emitter.line(`_current_sketch.Deactivate(NXOpen.Sketch.ViewReorient.TrueValue, NXOpen.Sketch.UpdateLevel.Model)`);
        emitter.line(`pocket_builder = work_part.Features.CreateExtrudeBuilder(None)`);
        emitter.line(`pocket_builder.Section.AddToSection([], _current_sketch, None, None, None, None, 0)`);
        emitter.line(`pocket_builder.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Subtract`);
        emitter.line(`pocket_builder.Limits.EndExtend.Value.Value = ${depth}*UNIT_FACTOR`);
        emitter.line(`_features.append(pocket_builder.Commit())`);
        emitter.line(`pocket_builder.Destroy()`);
        emitter.parameter("pocket_depth", depth, ctx?.units ?? "mm");
        break;
      }

      case "feature_boss": {
        const height = safeNum(a.height, 10);
        emitter.line(`# Boss (add extrude) height=${height}`);
        emitter.line(`_current_sketch.Deactivate(NXOpen.Sketch.ViewReorient.TrueValue, NXOpen.Sketch.UpdateLevel.Model)`);
        emitter.line(`boss_builder = work_part.Features.CreateExtrudeBuilder(None)`);
        emitter.line(`boss_builder.Section.AddToSection([], _current_sketch, None, None, None, None, 0)`);
        emitter.line(`boss_builder.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Unite`);
        emitter.line(`boss_builder.Limits.EndExtend.Value.Value = ${height}*UNIT_FACTOR`);
        emitter.line(`_features.append(boss_builder.Commit())`);
        emitter.line(`boss_builder.Destroy()`);
        break;
      }

      case "feature_rib": {
        const thickness = safeNum(a.thickness, 5);
        emitter.line(`# Rib thickness=${thickness}`);
        emitter.line(`rib_builder = work_part.Features.CreateRibBuilder(None)`);
        emitter.line(`rib_builder.Thickness.Value = ${thickness}*UNIT_FACTOR`);
        emitter.line(`_features.append(rib_builder.Commit())`);
        emitter.line(`rib_builder.Destroy()`);
        break;
      }

      case "feature_fillet": {
        const r = safeNum(a.radius, 3);
        emitter.line(`# Fillet radius=${r}`);
        emitter.line(`fillet_builder = work_part.Features.CreateEdgeBlendBuilder(None)`);
        emitter.line(`fillet_builder.DefaultRadius.Value = ${r}*UNIT_FACTOR`);
        emitter.line(`# Add edges to blend`);
        emitter.line(`_features.append(fillet_builder.Commit())`);
        emitter.line(`fillet_builder.Destroy()`);
        emitter.parameter("fillet_radius", r, ctx?.units ?? "mm");
        break;
      }

      case "feature_chamfer": {
        const d = safeNum(a.distance, 2);
        const angle = safeNum(a.angle, 45);
        emitter.line(`# Chamfer distance=${d}, angle=${angle}`);
        emitter.line(`chamfer_builder = work_part.Features.CreateChamferBuilder(None)`);
        emitter.line(`chamfer_builder.FirstOffset.Value = ${d}*UNIT_FACTOR`);
        emitter.line(`chamfer_builder.Angle.Value = ${angle}`);
        emitter.line(`_features.append(chamfer_builder.Commit())`);
        emitter.line(`chamfer_builder.Destroy()`);
        emitter.parameter("chamfer_distance", d, ctx?.units ?? "mm");
        break;
      }

      case "feature_shell": {
        const thickness = safeNum(a.thickness, 2);
        emitter.line(`# Shell thickness=${thickness}`);
        emitter.line(`shell_builder = work_part.Features.CreateShellBuilder(None)`);
        emitter.line(`shell_builder.AllFacesThickness.Value = ${thickness}*UNIT_FACTOR`);
        emitter.line(`_features.append(shell_builder.Commit())`);
        emitter.line(`shell_builder.Destroy()`);
        emitter.parameter("shell_thickness", thickness, ctx?.units ?? "mm");
        break;
      }

      case "feature_draft": {
        const angle = safeNum(a.angle, 3);
        emitter.line(`# Draft angle=${angle}°`);
        emitter.line(`draft_builder = work_part.Features.CreateDraftBuilder(None)`);
        emitter.line(`draft_builder.DraftAngle.Value = ${angle}`);
        emitter.line(`_features.append(draft_builder.Commit())`);
        emitter.line(`draft_builder.Destroy()`);
        emitter.parameter("draft_angle", angle, "deg");
        break;
      }

      case "feature_thread": {
        const pitch = safeNum(a.pitch, 1.5);
        const depth = safeNum(a.depth, 10);
        emitter.line(`# Thread pitch=${pitch}, depth=${depth}`);
        emitter.line(`thread_builder = work_part.Features.CreateSymbolicThreadBuilder(None)`);
        emitter.line(`thread_builder.MinorDiameter.Value = ${pitch}*UNIT_FACTOR`);
        emitter.line(`thread_builder.Length.Value = ${depth}*UNIT_FACTOR`);
        emitter.line(`_features.append(thread_builder.Commit())`);
        emitter.line(`thread_builder.Destroy()`);
        break;
      }

      case "feature_pattern_linear":
      case "feature_pattern_circular":
      case "feature_mirror":
        emitter.line(`# ${op.kind} — pattern/mirror feature`);
        emitter.warn(`${op.kind} stub`, "info");
        break;

      // ─── Surface ───────────────────────────────────────────────────────
      case "surface_extrude":
      case "surface_revolve":
      case "surface_sweep":
      case "surface_loft":
      case "surface_fill":
      case "surface_offset":
      case "surface_thicken":
      case "surface_trim":
      case "surface_extend":
        emitter.line(`# ${op.kind} — surface operation`);
        emitter.warn(`${op.kind} not fully implemented`, "info");
        break;

      // ─── Boolean ───────────────────────────────────────────────────────
      case "boolean_union": {
        emitter.line(`# Boolean Unite`);
        emitter.line(`bool_builder = work_part.Features.CreateBooleanBuilder(None)`);
        emitter.line(`bool_builder.Operation = NXOpen.Features.Feature.BooleanType.Unite`);
        emitter.line(`_features.append(bool_builder.Commit())`);
        emitter.line(`bool_builder.Destroy()`);
        break;
      }

      case "boolean_subtract": {
        emitter.line(`# Boolean Subtract`);
        emitter.line(`bool_builder = work_part.Features.CreateBooleanBuilder(None)`);
        emitter.line(`bool_builder.Operation = NXOpen.Features.Feature.BooleanType.Subtract`);
        emitter.line(`_features.append(bool_builder.Commit())`);
        emitter.line(`bool_builder.Destroy()`);
        break;
      }

      case "boolean_intersect": {
        emitter.line(`# Boolean Intersect`);
        emitter.line(`bool_builder = work_part.Features.CreateBooleanBuilder(None)`);
        emitter.line(`bool_builder.Operation = NXOpen.Features.Feature.BooleanType.Intersect`);
        emitter.line(`_features.append(bool_builder.Commit())`);
        emitter.line(`bool_builder.Destroy()`);
        break;
      }

      // ─── Transform ─────────────────────────────────────────────────────
      case "transform_move": {
        const dx = safeNum(a.dx);
        const dy = safeNum(a.dy);
        const dz = safeNum(a.dz);
        emitter.line(`# Move (${dx}, ${dy}, ${dz})`);
        emitter.line(`move_builder = work_part.Features.CreateMoveObjectBuilder(None)`);
        emitter.line(`move_builder.TransformMotion.DeltaXc.Value = ${dx}*UNIT_FACTOR`);
        emitter.line(`move_builder.TransformMotion.DeltaYc.Value = ${dy}*UNIT_FACTOR`);
        emitter.line(`move_builder.TransformMotion.DeltaZc.Value = ${dz}*UNIT_FACTOR`);
        emitter.line(`move_builder.Commit()`);
        emitter.line(`move_builder.Destroy()`);
        break;
      }

      case "transform_rotate": {
        const angle = safeNum(a.angle, 45);
        const axisX = safeNum(a.axisX, 0);
        const axisY = safeNum(a.axisY, 0);
        const axisZ = safeNum(a.axisZ, 1);
        emitter.line(`# Rotate ${angle}° around (${axisX}, ${axisY}, ${axisZ})`);
        emitter.line(`rotate_builder = work_part.Features.CreateMoveObjectBuilder(None)`);
        emitter.line(`rotate_builder.TransformMotion.Option = NXOpen.GeometricUtilities.ModlMotion.Options.Angle`);
        emitter.line(`rotate_builder.TransformMotion.Angle.Value = ${angle}`);
        emitter.line(`rotate_builder.Commit()`);
        emitter.line(`rotate_builder.Destroy()`);
        break;
      }

      case "transform_scale": {
        const factor = safeNum(a.factor, 1);
        emitter.line(`# Scale ${factor}`);
        emitter.line(`scale_builder = work_part.Features.CreateScaleBuilder(None)`);
        emitter.line(`scale_builder.UniformScale.Value = ${factor}`);
        emitter.line(`scale_builder.Commit()`);
        emitter.line(`scale_builder.Destroy()`);
        break;
      }

      case "transform_mirror": {
        emitter.line(`# Mirror transform`);
        emitter.line(`mirror_builder = work_part.Features.CreateMirrorBodyBuilder(None)`);
        emitter.line(`mirror_builder.Commit()`);
        emitter.line(`mirror_builder.Destroy()`);
        break;
      }

      case "transform_pattern_linear": {
        const dx = safeNum(a.dx, 25);
        const dy = safeNum(a.dy, 0);
        const count = Math.max(1, safeNum(a.count, 4));
        emitter.line(`# Linear pattern: ${count} copies, spacing (${dx}, ${dy})`);
        emitter.line(`pattern_builder = work_part.Features.CreatePatternFeatureBuilder(None)`);
        emitter.line(`pattern_builder.PatternType = NXOpen.Features.PatternFeatureBuilder.PatternTypes.Linear`);
        emitter.line(`pattern_builder.XDirectionSpacing.Value = ${dx}*UNIT_FACTOR`);
        emitter.line(`pattern_builder.YDirectionSpacing.Value = ${dy}*UNIT_FACTOR`);
        emitter.line(`pattern_builder.XDirectionCount.Value = ${count}`);
        emitter.line(`pattern_builder.Commit()`);
        emitter.line(`pattern_builder.Destroy()`);
        break;
      }

      case "transform_pattern_circular": {
        const count = Math.max(1, safeNum(a.count, 6));
        const angle = safeNum(a.angle, 360);
        emitter.line(`# Circular pattern: ${count} copies, ${angle}°`);
        emitter.line(`pattern_builder = work_part.Features.CreatePatternFeatureBuilder(None)`);
        emitter.line(`pattern_builder.PatternType = NXOpen.Features.PatternFeatureBuilder.PatternTypes.Circular`);
        emitter.line(`pattern_builder.CircularSpacingAngle.Value = ${angle / count}`);
        emitter.line(`pattern_builder.CircularCount.Value = ${count}`);
        emitter.line(`pattern_builder.Commit()`);
        emitter.line(`pattern_builder.Destroy()`);
        break;
      }

      // ─── Export ────────────────────────────────────────────────────────
      case "export_step": {
        const filename = safeStr(a.filename, "output.step");
        const outDir = ctx?.outputDir ?? ".";
        emitter.line(`# Export STEP`);
        emitter.line(`step_creator = session.DexManager.CreateStep203Creator()`);
        emitter.line(`step_creator.ExportAs = NXOpen.Step203Creator.ExportAsOption.Ap203`);
        emitter.line(`step_creator.InputFile = "${outDir}/${filename}"`);
        emitter.line(`step_creator.Commit()`);
        emitter.line(`step_creator.Destroy()`);
        break;
      }

      case "export_iges": {
        const filename = safeStr(a.filename, "output.igs");
        const outDir = ctx?.outputDir ?? ".";
        emitter.line(`# Export IGES`);
        emitter.line(`iges_creator = session.DexManager.CreateIgesCreator()`);
        emitter.line(`iges_creator.InputFile = "${outDir}/${filename}"`);
        emitter.line(`iges_creator.Commit()`);
        emitter.line(`iges_creator.Destroy()`);
        break;
      }

      case "export_stl": {
        const filename = safeStr(a.filename, "output.stl");
        const outDir = ctx?.outputDir ?? ".";
        emitter.line(`# Export STL`);
        emitter.line(`stl_creator = session.DexManager.CreateStlCreator()`);
        emitter.line(`stl_creator.OutputFile = "${outDir}/${filename}"`);
        emitter.line(`stl_creator.Commit()`);
        emitter.line(`stl_creator.Destroy()`);
        break;
      }

      case "export_parasolid": {
        const filename = safeStr(a.filename, "output.x_t");
        const outDir = ctx?.outputDir ?? ".";
        emitter.line(`# Export Parasolid`);
        emitter.line(`parasolid_creator = session.DexManager.CreateParasolidCreator()`);
        emitter.line(`parasolid_creator.OutputFile = "${outDir}/${filename}"`);
        emitter.line(`parasolid_creator.Commit()`);
        emitter.line(`parasolid_creator.Destroy()`);
        break;
      }

      case "export_jt": {
        const filename = safeStr(a.filename, "output.jt");
        const outDir = ctx?.outputDir ?? ".";
        emitter.line(`# Export JT`);
        emitter.line(`jt_creator = session.DexManager.CreateJtCreator()`);
        emitter.line(`jt_creator.OutputFile = "${outDir}/${filename}"`);
        emitter.line(`jt_creator.Commit()`);
        emitter.line(`jt_creator.Destroy()`);
        break;
      }

      // ─── Import ────────────────────────────────────────────────────────
      case "import_step": {
        const filepath = safeStr(a.filepath, "input.step");
        emitter.line(`# Import STEP`);
        emitter.line(`step_importer = session.DexManager.CreateStep203Importer()`);
        emitter.line(`step_importer.InputFile = "${filepath}"`);
        emitter.line(`step_importer.Commit()`);
        emitter.line(`step_importer.Destroy()`);
        break;
      }

      case "import_iges": {
        const filepath = safeStr(a.filepath, "input.igs");
        emitter.line(`# Import IGES`);
        emitter.line(`iges_importer = session.DexManager.CreateIgesImporter()`);
        emitter.line(`iges_importer.InputFile = "${filepath}"`);
        emitter.line(`iges_importer.Commit()`);
        emitter.line(`iges_importer.Destroy()`);
        break;
      }

      case "import_parasolid": {
        const filepath = safeStr(a.filepath, "input.x_t");
        emitter.line(`# Import Parasolid`);
        emitter.line(`parasolid_importer = session.DexManager.CreateParasolidImporter()`);
        emitter.line(`parasolid_importer.InputFile = "${filepath}"`);
        emitter.line(`parasolid_importer.Commit()`);
        emitter.line(`parasolid_importer.Destroy()`);
        break;
      }

      case "import_jt": {
        const filepath = safeStr(a.filepath, "input.jt");
        emitter.line(`# Import JT`);
        emitter.line(`jt_importer = session.DexManager.CreateJtImporter()`);
        emitter.line(`jt_importer.InputFile = "${filepath}"`);
        emitter.line(`jt_importer.Commit()`);
        emitter.line(`jt_importer.Destroy()`);
        break;
      }

      // ─── Assembly ──────────────────────────────────────────────────────
      case "assembly_create": {
        const name = safeStr(a.name, "assembly");
        emitter.line(`# Create assembly`);
        emitter.line(`asm_part = session.Parts.NewDisplay("${name}", NXOpen.Part.Units.Millimeters)`);
        emitter.line(`work_part = asm_part`);
        break;
      }

      case "assembly_add_component": {
        const partPath = safeStr(a.partPath, "component.prt");
        emitter.line(`# Add component to assembly`);
        emitter.line(`comp_builder = work_part.AssemblyManager.CreateAddComponentBuilder()`);
        emitter.line(`comp_builder.SetPartToAdd("${partPath}")`);
        emitter.line(`comp_builder.Commit()`);
        emitter.line(`comp_builder.Destroy()`);
        break;
      }

      case "assembly_constrain": {
        const constraintType = safeStr(a.type, "fix");
        emitter.line(`# Assembly constraint: ${constraintType}`);
        emitter.line(`constraint_builder = work_part.ComponentAssembly.CreateComponentConstraintBuilder()`);
        emitter.line(`constraint_builder.Commit()`);
        emitter.line(`constraint_builder.Destroy()`);
        break;
      }

      case "assembly_explode": {
        emitter.line(`# Explode assembly view`);
        emitter.line(`explode_builder = work_part.AssemblyManager.CreateExplodedViewBuilder()`);
        emitter.line(`explode_builder.Commit()`);
        emitter.line(`explode_builder.Destroy()`);
        break;
      }

      default:
        emitter.warn(`Unknown operation: ${op.kind}`, "error");
    }
  }

  // ── Script filename ────────────────────────────────────────────────────

  protected scriptFilename(ctx: NXGenerationContext | undefined): string {
    const name = ctx?.projectName ?? "prism_part";
    const safe = name.replace(/[^a-zA-Z0-9_]/g, "_");
    return `${safe}.py`;
  }

  // ── Execution ──────────────────────────────────────────────────────────

  protected async runScriptBody(
    script: CADScript<string>,
  ): Promise<CADExecutionResult> {
    const isMock =
      process.env.PRISM_CAD_MOCK === "true" || process.env.CI === "true";

    if (isMock) {
      console.error("[DEBUG] NXCodeGeneratorEngine: mock execution mode");
      return {
        ok: true,
        durationMs: 5,
        metrics: {
          volumeMm3: 12500,
          surfaceAreaMm2: 3750,
          faceCount: 8,
          edgeCount: 18,
          vertexCount: 12,
          boundingBoxMm: [50, 50, 50],
        },
      };
    }

    // Real execution would call NX batch mode:
    // run_journal.exe -nx_part -run {script.filename}
    return {
      ok: false,
      error: "NX journal execution requires NX installation",
      durationMs: 0,
    };
  }
}

// ── Singleton export ─────────────────────────────────────────────────────────

export const nxCodeGeneratorEngine = new NXCodeGeneratorEngine();
