/**
 * PPOkumaTurningPostEngine — Okuma OSP-P300L turning post processing
 *
 * Generates turning-specific G-code for Okuma lathes (LB3000, LU3000)
 * using OSP-P300L dialect. JM Die's primary production machines — 7 Okuma
 * lathes producing cold heading dies and tooling inserts.
 *
 * Covers:
 *   - OD roughing/finishing (G71/G70 or manual)
 *   - ID boring
 *   - Grooving/parting (G75)
 *   - Threading (G76 single-point, G92 simple thread)
 *   - Face turning
 *   - CSS (constant surface speed) G96/G97
 *   - Turret indexing (T0101 format)
 *   - Tailstock engagement
 *   - Sub-spindle transfer (LU3000)
 *
 * @module PPOkumaTurningPostEngine
 */

// ── Types ─────────────────────────────────────────────────────────────

export interface TurningOperation {
  type: "od_rough" | "od_finish" | "id_bore" | "face" | "groove" | "part" | "thread" | "drill";
  tool_number: number;
  tool_position: number;       // turret position (same as tool_number for Okuma)
  tool_description?: string;
  insert_type?: string;        // CNMG, DNMG, VNMG, etc.

  // Cutting parameters
  speed_sfm?: number;          // surface feet per minute (CSS)
  speed_rpm?: number;          // direct RPM (overrides CSS)
  feed_ipr?: number;           // inches per revolution
  feed_mm_rev?: number;        // mm per revolution
  depth_of_cut_mm?: number;
  max_rpm?: number;            // CSS clamp

  // Geometry
  start_x_mm?: number;         // OD start diameter
  end_x_mm?: number;           // OD end diameter
  start_z_mm?: number;         // Z start
  end_z_mm?: number;           // Z end (depth)

  // Threading
  thread_pitch_mm?: number;
  thread_depth_mm?: number;
  thread_passes?: number;

  // Coolant
  coolant: "flood" | "mist" | "off" | "tsc";

  // Options
  css?: boolean;               // use constant surface speed
  finish_allowance_mm?: number;
}

export interface TurningProgramInput {
  machine_id: string;
  program_number?: string;
  part_description?: string;
  bar_diameter_mm?: number;
  part_length_mm?: number;
  material?: string;
  operations: TurningOperation[];
}

export interface TurningProgram {
  gcode_lines: string[];
  gcode_text: string;
  line_count: number;
  machine: string;
  operation_count: number;
  warnings: string[];
}

// ── Engine ─────────────────────────────────────────────────────────────

export class PPOkumaTurningPostEngine {
  /**
   * Generate a complete turning program for an Okuma lathe.
   */
  generate(input: TurningProgramInput): TurningProgram {
    const lines: string[] = [];
    const warnings: string[] = [];
    const progNum = input.program_number ?? "0001";

    // Program header (Okuma OSP-P300L format)
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "TURNING PROGRAM"})`);
    lines.push(`(MACHINE: ${input.machine_id})`);
    lines.push(`(MATERIAL: ${input.material ?? "UNKNOWN"})`);
    if (input.bar_diameter_mm) lines.push(`(BAR DIA: ${input.bar_diameter_mm}mm)`);
    lines.push(`(GENERATED BY PP-AGI TURNING POST)`);
    lines.push("");

    // Safe start
    lines.push("G28 U0 W0");
    lines.push("G50 S3000 (MAX RPM CLAMP)");
    lines.push("G21 G40 G80 G99 (METRIC, COMP CANCEL, CYCLE CANCEL, FEED/REV)");
    lines.push("");

    // Generate each operation
    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      lines.push(`(--- OP ${i + 1}: ${op.type.toUpperCase()} T${String(op.tool_number).padStart(2, "0")} ---)`);

      // Tool change
      lines.push(`T${String(op.tool_number).padStart(2, "0")}${String(op.tool_position).padStart(2, "0")}`);

      // CSS or direct RPM
      if (op.css && op.speed_sfm) {
        const maxRpm = op.max_rpm ?? 3000;
        lines.push(`G50 S${maxRpm} (RPM CLAMP)`);
        lines.push(`G96 S${op.speed_sfm} M3 (CSS ${op.speed_sfm} SFM)`);
      } else if (op.speed_rpm) {
        lines.push(`G97 S${op.speed_rpm} M3 (DIRECT RPM)`);
      }

      // Coolant
      switch (op.coolant) {
        case "flood": lines.push("M8"); break;
        case "mist": lines.push("M7"); break;
        case "tsc": lines.push("M51 (TSC)"); break;
      }

      // Operation-specific code
      switch (op.type) {
        case "od_rough":
          this.generateODRough(lines, op, warnings);
          break;
        case "od_finish":
          this.generateODFinish(lines, op);
          break;
        case "id_bore":
          this.generateIDBore(lines, op, warnings);
          break;
        case "face":
          this.generateFace(lines, op);
          break;
        case "groove":
        case "part":
          this.generateGroove(lines, op, op.type === "part");
          break;
        case "thread":
          this.generateThread(lines, op, warnings);
          break;
        case "drill":
          this.generateDrill(lines, op);
          break;
      }

      // End operation
      lines.push("M5 (SPINDLE STOP)");
      lines.push("M9 (COOLANT OFF)");
      lines.push("G28 U0 W0 (HOME)");
      lines.push("");
    }

    // Program end
    lines.push("M30");
    lines.push("%");

    const gcodeText = lines.join("\n");
    return {
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      machine: input.machine_id,
      operation_count: input.operations.length,
      warnings,
    };
  }

  /** Generate a simple OD roughing program. */
  generateSimpleODRough(
    barDia: number, finishDia: number, length: number,
    sfm: number, feedIPR: number, doc: number,
  ): TurningProgram {
    return this.generate({
      machine_id: "jmdie-okuma-lb3000",
      part_description: `OD ROUGH ${barDia}mm to ${finishDia}mm`,
      bar_diameter_mm: barDia,
      operations: [{
        type: "od_rough", tool_number: 1, tool_position: 1,
        tool_description: "CNMG 432 roughing",
        speed_sfm: sfm, feed_ipr: feedIPR, depth_of_cut_mm: doc,
        css: true, coolant: "flood",
        start_x_mm: barDia, end_x_mm: finishDia,
        start_z_mm: 1, end_z_mm: -length,
      }],
    });
  }

  // ── Operation generators ────────────────────────────────────────────

  private generateODRough(lines: string[], op: TurningOperation, warnings: string[]) {
    const feed = op.feed_mm_rev ?? (op.feed_ipr ? op.feed_ipr * 25.4 : 0.3);
    const doc = op.depth_of_cut_mm ?? 2.0;
    const startX = op.start_x_mm ?? 50;
    const endX = op.end_x_mm ?? 30;
    const startZ = op.start_z_mm ?? 1;
    const endZ = op.end_z_mm ?? -50;
    const finishAllow = op.finish_allowance_mm ?? 0.5;

    if (doc > 5) warnings.push(`OD rough DOC ${doc}mm is aggressive — verify insert capability`);

    lines.push(`G0 X${(startX + 2).toFixed(1)} Z${startZ.toFixed(1)} (RAPID TO START)`);
    lines.push(`(ROUGH CYCLE: DOC=${doc}mm, FINISH ALLOW=${finishAllow}mm)`);

    // Simple multi-pass roughing
    const passes = Math.ceil((startX - endX - finishAllow * 2) / (doc * 2));
    let currentX = startX;
    for (let p = 0; p < Math.min(passes, 20); p++) {
      currentX -= doc * 2;
      if (currentX < endX + finishAllow * 2) currentX = endX + finishAllow * 2;
      lines.push(`G0 X${currentX.toFixed(3)}`);
      lines.push(`G1 Z${endZ.toFixed(1)} F${feed.toFixed(3)}`);
      lines.push(`G0 X${(currentX + 1).toFixed(1)}`);
      lines.push(`G0 Z${startZ.toFixed(1)}`);
    }
  }

  private generateODFinish(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? (op.feed_ipr ? op.feed_ipr * 25.4 : 0.1);
    const endX = op.end_x_mm ?? 30;
    const startZ = op.start_z_mm ?? 1;
    const endZ = op.end_z_mm ?? -50;

    lines.push(`G0 X${(endX + 2).toFixed(1)} Z${startZ.toFixed(1)}`);
    lines.push(`G1 X${endX.toFixed(3)} F${feed.toFixed(3)} (FINISH DIAMETER)`);
    lines.push(`G1 Z${endZ.toFixed(1)}`);
    lines.push(`G0 X${(endX + 2).toFixed(1)}`);
  }

  private generateIDBore(lines: string[], op: TurningOperation, warnings: string[]) {
    const feed = op.feed_mm_rev ?? 0.12;
    const startX = op.start_x_mm ?? 20;
    const endX = op.end_x_mm ?? 25;
    const endZ = op.end_z_mm ?? -30;

    if (endX - startX > 10) warnings.push("Large bore diameter change — verify boring bar reach");

    lines.push(`G0 X${(startX - 2).toFixed(1)} Z1.0`);
    lines.push(`G1 X${endX.toFixed(3)} Z${endZ.toFixed(1)} F${feed.toFixed(3)} (BORE)`);
    lines.push(`G0 X${(startX - 2).toFixed(1)}`);
    lines.push(`G0 Z1.0`);
  }

  private generateFace(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? 0.2;
    const barDia = op.start_x_mm ?? 50;

    lines.push(`G0 X${(barDia + 2).toFixed(1)} Z0.5`);
    lines.push(`G1 Z0 F${feed.toFixed(3)} (FACE)`);
    lines.push(`G1 X-1.6 (FACE TO CENTER)`);
    lines.push(`G0 Z1.0`);
    lines.push(`G0 X${(barDia + 2).toFixed(1)}`);
  }

  private generateGroove(lines: string[], op: TurningOperation, isPartOff: boolean) {
    const feed = op.feed_mm_rev ?? 0.05;
    const grooveX = op.end_x_mm ?? (isPartOff ? -1 : 25);
    const grooveZ = op.end_z_mm ?? -20;
    const startX = op.start_x_mm ?? 50;

    lines.push(`G0 X${(startX + 2).toFixed(1)} Z${grooveZ.toFixed(1)}`);
    if (isPartOff) {
      lines.push(`G1 X${grooveX.toFixed(1)} F${feed.toFixed(3)} (PART OFF)`);
    } else {
      lines.push(`G75 R0.5 (PECK GROOVE)`);
      lines.push(`G75 X${grooveX.toFixed(1)} Z${grooveZ.toFixed(1)} P1000 Q500 F${feed.toFixed(3)}`);
    }
    lines.push(`G0 X${(startX + 2).toFixed(1)}`);
  }

  private generateThread(lines: string[], op: TurningOperation, warnings: string[]) {
    const pitch = op.thread_pitch_mm ?? 1.5;
    const depth = op.thread_depth_mm ?? pitch * 0.6134; // 60° standard
    const passes = op.thread_passes ?? 6;
    const startX = op.start_x_mm ?? 30;
    const endZ = op.end_z_mm ?? -20;

    if (pitch > 4) warnings.push(`Large thread pitch ${pitch}mm — verify machine capability`);

    lines.push(`G0 X${(startX + 5).toFixed(1)} Z3.0 (THREAD START)`);
    lines.push(`(THREAD: PITCH=${pitch}mm, DEPTH=${depth.toFixed(3)}mm, ${passes} PASSES)`);
    lines.push(`G76 P0${passes < 10 ? "0" : ""}${passes}0060 Q100 R0.05`);
    lines.push(`G76 X${(startX - depth * 2).toFixed(3)} Z${endZ.toFixed(1)} P${Math.round(depth * 1000)} Q200 F${pitch.toFixed(3)}`);
  }

  private generateDrill(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? 0.15;
    const depth = op.end_z_mm ?? -30;

    lines.push(`G0 X0 Z2.0 (CENTER)`);
    lines.push(`G83 Z${depth.toFixed(1)} Q5000 F${feed.toFixed(3)} (PECK DRILL)`);
    lines.push(`G80`);
    lines.push(`G0 Z2.0`);
  }
}

export const ppOkumaTurningPostEngine = new PPOkumaTurningPostEngine();
