/**
 * PPOkumaTurningPostEngine — Okuma OSP-P300L turning post processing
 *
 * Generates turning-specific G-code for Okuma lathes (LB3000, LU3000)
 * using OSP-P300L dialect. JM Die's primary production machines — 7 Okuma
 * lathes producing cold heading dies and tooling inserts.
 *
 * Covers (Okuma OSP dialect -- NOT Fanuc; verified vs Mark's running JM .MIN +
 * reference_echo_okuma_cycle_dialect_2026_06_28, cloned from OkumaB250LatheMasterPostEngine):
 *   - OD roughing/finishing (explicit G0/G1 multi-pass -- no canned cycle)
 *   - ID boring (explicit G0/G1)
 *   - Grooving/parting (explicit G1 plunge + G4 F<sec> dwell -- NOT Fanuc G75; G75 has no valid OSP form)
 *   - Threading (OSP G71 single-line cycle: G71 X Z B D U H F M33 M73 -- NOT Fanuc G76; on OSP G71 IS threading)
 *   - Face turning (explicit G0/G1)
 *   - Drilling (G83 axial peck -- VERIFIED valid on OSP)
 *   - CSS (constant surface speed) G96/G97
 *   - Turret indexing (6-digit T<station><offset><wear>, e.g. T010101 -- NOT 4-digit)
 *   - Tailstock engagement
 *   - Sub-spindle transfer (LU3000)
 *
 * @module PPOkumaTurningPostEngine
 */

// ── Types ─────────────────────────────────────────────────────────────

export interface TurningOperation {
  type: "od_rough" | "od_finish" | "id_bore" | "face" | "groove" | "part" | "thread" | "drill";
  tool_number: number;
  tool_position: number;       // turret position (same as tool_number for Okuma)
  tool_description?: string;
  insert_type?: string;        // CNMG, DNMG, VNMG, etc.

  // Cutting parameters
  speed_sfm?: number;          // surface feet per minute (CSS)
  speed_rpm?: number;          // direct RPM (overrides CSS)
  feed_ipr?: number;           // inches per revolution
  feed_mm_rev?: number;        // mm per revolution
  depth_of_cut_mm?: number;
  max_rpm?: number;            // CSS clamp

  // Geometry
  start_x_mm?: number;         // OD start diameter
  end_x_mm?: number;           // OD end diameter
  start_z_mm?: number;         // Z start
  end_z_mm?: number;           // Z end (depth)

  // Threading
  thread_pitch_mm?: number;
  thread_depth_mm?: number;
  thread_passes?: number;

  // Coolant
  coolant: "flood" | "mist" | "off" | "tsc";

  // Options
  css?: boolean;               // use constant surface speed
  finish_allowance_mm?: number;
}

export interface TurningProgramInput {
  machine_id: string;
  program_number?: string;
  part_description?: string;
  bar_diameter_mm?: number;
  part_length_mm?: number;
  material?: string;
  operations: TurningOperation[];
}

export interface TurningProgram {
  gcode_lines: string[];
  gcode_text: string;
  line_count: number;
  machine: string;
  operation_count: number;
  warnings: string[];
}

// ── Engine ─────────────────────────────────────────────────────────────

/** U-PP-NONFINITE-EMIT-SWEEP: numeric op fields that format directly into an emitted
 *  token (X/Z coords, F feed, S speed, thread/cut params). A present-but-non-finite
 *  value formats into a literal `XNaN`/`SInfinity`/`FNaN` the OSP control rejects -- so
 *  HALT the op's emit (fail loud), never silently emit a wrong-but-valid coord (a silent
 *  0 could rapid the turret to centerline). The `?? default` fallbacks in the generators
 *  only catch null/undefined, NOT NaN/Infinity. Sibling of the OkumaB250/OkumaOSP/
 *  HurcoV11/Mitsubishi fixes (R15 apply-to-all). Absent fields are not flagged. */
function nonFiniteTurningEmitFields(op: TurningOperation): string[] {
  const FIELDS = [
    "start_x_mm", "end_x_mm", "start_z_mm", "end_z_mm",
    "feed_mm_rev", "feed_ipr", "depth_of_cut_mm", "finish_allowance_mm",
    "speed_sfm", "speed_rpm", "max_rpm",
    "thread_pitch_mm", "thread_depth_mm",
  ] as const;
  const bad: string[] = [];
  for (const f of FIELDS) {
    const v = (op as unknown as Record<string, unknown>)[f];
    if (typeof v === "number" && !Number.isFinite(v)) bad.push(`${f}=${v}`);
  }
  return bad;
}

export class PPOkumaTurningPostEngine {
  /**
   * Generate a complete turning program for an Okuma lathe.
   */
  generate(input: TurningProgramInput): TurningProgram {
    const lines: string[] = [];
    const warnings: string[] = [];
    const progNum = input.program_number ?? "0001";

    // Program header (Okuma OSP-P300L format)
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "TURNING PROGRAM"})`);
    lines.push(`(MACHINE: ${input.machine_id})`);
    lines.push(`(MATERIAL: ${input.material ?? "UNKNOWN"})`);
    if (input.bar_diameter_mm) lines.push(`(BAR DIA: ${input.bar_diameter_mm}mm)`);
    lines.push(`(GENERATED BY PP-AGI TURNING POST)`);
    lines.push("");

    // Safe start
    lines.push("G28 U0 W0");
    lines.push("G50 S3000 (MAX RPM CLAMP)");
    lines.push("G21 G40 G80 G99 (METRIC, COMP CANCEL, CYCLE CANCEL, FEED/REV)");
    lines.push("");

    // Generate each operation
    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      lines.push(`(--- OP ${i + 1}: ${op.type.toUpperCase()} T${String(op.tool_number).padStart(2, "0")} ---)`);

      // U-PP-NONFINITE-EMIT-SWEEP: a non-finite coord/feed/speed/thread field would emit a
      // literal `XNaN`/`SInfinity`/`FNaN` the OSP control rejects -- HALT the op's emit
      // (fail loud) + warn; never silently emit a wrong-but-valid coord.
      const badEmit = nonFiniteTurningEmitFields(op);
      if (badEmit.length > 0) {
        warnings.push(`Op ${i + 1} (${op.type}): non-finite emit field(s) [${badEmit.join(", ")}] -- operation block replaced with an ERROR marker to avoid a literal XNaN/SInfinity/FNaN the OSP control rejects; fix the upstream toolpath before running.`);
        lines.push(`(ERROR: OP ${i + 1} ${op.type.toUpperCase()} NON-FINITE ${badEmit.join(" ")} -- DO NOT RUN, REVIEW TOOLPATH)`);
        lines.push("");
        continue;
      }

      // Tool change -- Okuma OSP 6-digit T<station><offset><wear> (all three pairs = the tool
      // number), NOT the 4-digit T<NN><NN> form. Verified vs Mark's running JM programs
      // (T010101/T020202/T070707/T111111 dominate the corpus 85,498x; the prior 4-digit form
      // appears 0x). Cloned from OkumaB250LatheMasterPostEngine.generateToolChange
      // (reference_echo_okuma_cycle_dialect_2026_06_28). op.tool_position stays on the input for
      // back-compat but the OSP convention sets offset+wear = station per Mark's corpus.
      const tnum = String(op.tool_number).padStart(2, "0");
      lines.push(`T${tnum}${tnum}${tnum}`);

      // CSS or direct RPM
      if (op.css && op.speed_sfm) {
        const maxRpm = op.max_rpm ?? 3000;
        lines.push(`G50 S${maxRpm} (RPM CLAMP)`);
        lines.push(`G96 S${op.speed_sfm} M3 (CSS ${op.speed_sfm} SFM)`);
      } else if (op.speed_rpm) {
        lines.push(`G97 S${op.speed_rpm} M3 (DIRECT RPM)`);
      }

      // Coolant
      switch (op.coolant) {
        case "flood": lines.push("M8"); break;
        case "mist": lines.push("M7"); break;
        case "tsc": lines.push("M51 (TSC)"); break;
      }

      // Operation-specific code
      switch (op.type) {
        case "od_rough":
          this.generateODRough(lines, op, warnings);
          break;
        case "od_finish":
          this.generateODFinish(lines, op);
          break;
        case "id_bore":
          this.generateIDBore(lines, op, warnings);
          break;
        case "face":
          this.generateFace(lines, op);
          break;
        case "groove":
        case "part":
          this.generateGroove(lines, op, op.type === "part");
          break;
        case "thread":
          this.generateThread(lines, op, warnings);
          break;
        case "drill":
          this.generateDrill(lines, op);
          break;
      }

      // End operation
      lines.push("M5 (SPINDLE STOP)");
      lines.push("M9 (COOLANT OFF)");
      lines.push("G28 U0 W0 (HOME)");
      lines.push("");
    }

    // Program end
    lines.push("M30");
    lines.push("%");

    const gcodeText = lines.join("\n");
    return {
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      machine: input.machine_id,
      operation_count: input.operations.length,
      warnings,
    };
  }

  /** Generate a simple OD roughing program. */
  generateSimpleODRough(
    barDia: number, finishDia: number, length: number,
    sfm: number, feedIPR: number, doc: number,
  ): TurningProgram {
    return this.generate({
      machine_id: "jmdie-okuma-lb3000",
      part_description: `OD ROUGH ${barDia}mm to ${finishDia}mm`,
      bar_diameter_mm: barDia,
      operations: [{
        type: "od_rough", tool_number: 1, tool_position: 1,
        tool_description: "CNMG 432 roughing",
        speed_sfm: sfm, feed_ipr: feedIPR, depth_of_cut_mm: doc,
        css: true, coolant: "flood",
        start_x_mm: barDia, end_x_mm: finishDia,
        start_z_mm: 1, end_z_mm: -length,
      }],
    });
  }

  // ── Operation generators ────────────────────────────────────────────

  private generateODRough(lines: string[], op: TurningOperation, warnings: string[]) {
    const feed = op.feed_mm_rev ?? (op.feed_ipr ? op.feed_ipr * 25.4 : 0.3);
    const doc = op.depth_of_cut_mm ?? 2.0;
    const startX = op.start_x_mm ?? 50;
    const endX = op.end_x_mm ?? 30;
    const startZ = op.start_z_mm ?? 1;
    const endZ = op.end_z_mm ?? -50;
    const finishAllow = op.finish_allowance_mm ?? 0.5;

    if (doc > 5) warnings.push(`OD rough DOC ${doc}mm is aggressive — verify insert capability`);

    lines.push(`G0 X${(startX + 2).toFixed(1)} Z${startZ.toFixed(1)} (RAPID TO START)`);
    lines.push(`(ROUGH CYCLE: DOC=${doc}mm, FINISH ALLOW=${finishAllow}mm)`);

    // Simple multi-pass roughing
    const passes = Math.ceil((startX - endX - finishAllow * 2) / (doc * 2));
    let currentX = startX;
    for (let p = 0; p < Math.min(passes, 20); p++) {
      currentX -= doc * 2;
      if (currentX < endX + finishAllow * 2) currentX = endX + finishAllow * 2;
      lines.push(`G0 X${currentX.toFixed(3)}`);
      lines.push(`G1 Z${endZ.toFixed(1)} F${feed.toFixed(3)}`);
      lines.push(`G0 X${(currentX + 1).toFixed(1)}`);
      lines.push(`G0 Z${startZ.toFixed(1)}`);
    }
  }

  private generateODFinish(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? (op.feed_ipr ? op.feed_ipr * 25.4 : 0.1);
    const endX = op.end_x_mm ?? 30;
    const startZ = op.start_z_mm ?? 1;
    const endZ = op.end_z_mm ?? -50;

    lines.push(`G0 X${(endX + 2).toFixed(1)} Z${startZ.toFixed(1)}`);
    lines.push(`G1 X${endX.toFixed(3)} F${feed.toFixed(3)} (FINISH DIAMETER)`);
    lines.push(`G1 Z${endZ.toFixed(1)}`);
    lines.push(`G0 X${(endX + 2).toFixed(1)}`);
  }

  private generateIDBore(lines: string[], op: TurningOperation, warnings: string[]) {
    const feed = op.feed_mm_rev ?? 0.12;
    const startX = op.start_x_mm ?? 20;
    const endX = op.end_x_mm ?? 25;
    const endZ = op.end_z_mm ?? -30;

    if (endX - startX > 10) warnings.push("Large bore diameter change — verify boring bar reach");

    lines.push(`G0 X${(startX - 2).toFixed(1)} Z1.0`);
    lines.push(`G1 X${endX.toFixed(3)} Z${endZ.toFixed(1)} F${feed.toFixed(3)} (BORE)`);
    lines.push(`G0 X${(startX - 2).toFixed(1)}`);
    lines.push(`G0 Z1.0`);
  }

  private generateFace(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? 0.2;
    const barDia = op.start_x_mm ?? 50;

    lines.push(`G0 X${(barDia + 2).toFixed(1)} Z0.5`);
    lines.push(`G1 Z0 F${feed.toFixed(3)} (FACE)`);
    lines.push(`G1 X-1.6 (FACE TO CENTER)`);
    lines.push(`G0 Z1.0`);
    lines.push(`G0 X${(barDia + 2).toFixed(1)}`);
  }

  private generateGroove(lines: string[], op: TurningOperation, isPartOff: boolean) {
    const feed = op.feed_mm_rev ?? 0.05;
    const grooveX = op.end_x_mm ?? (isPartOff ? -1 : 25);
    const grooveZ = op.end_z_mm ?? -20;
    const startX = op.start_x_mm ?? 50;

    // Okuma OSP grooving + part-off are EXPLICIT (G1 plunge / G4 F<sec> dwell / retract) -- NOT the
    // Fanuc G75 peck cycle, which has NO valid OSP form (the real JM corpus uses G75 0x). Cloned from
    // the dialect-complete OkumaB250LatheMasterPostEngine.generateGroovingCycle/generatePartOff
    // (verified vs Mark's running .MIN: THREAD M8X125.MIN:44-52 OD groove, A05-LSC-25-B.MIN:118-133
    // ID groove). Okuma dwell is G4 F<seconds>, NOT Fanuc G04 P<ms>. See
    // reference_echo_okuma_cycle_dialect_2026_06_28.
    lines.push(`G0 X${(startX + 2).toFixed(1)} Z${grooveZ.toFixed(1)} (RAPID TO GROOVE)`);
    if (isPartOff) {
      lines.push(`G1 X${grooveX.toFixed(1)} F${feed.toFixed(3)} (PART OFF)`);
      lines.push(`G4 F0.5 (DWELL AT CENTER)`);
    } else {
      lines.push(`G1 X${grooveX.toFixed(1)} F${feed.toFixed(3)} (PLUNGE TO GROOVE BOTTOM)`);
      lines.push(`G4 F0.5 (DWELL -- CLEAN GROOVE BOTTOM)`);
    }
    lines.push(`G0 X${(startX + 2).toFixed(1)} (RETRACT CLEAR)`);
  }

  private generateThread(lines: string[], op: TurningOperation, warnings: string[]) {
    const pitch = op.thread_pitch_mm ?? 1.5;
    const depth = op.thread_depth_mm ?? pitch * 0.6134; // 60° standard
    const startX = op.start_x_mm ?? 30;
    const endZ = op.end_z_mm ?? -20;

    if (pitch > 4) warnings.push(`Large thread pitch ${pitch}mm — verify machine capability`);

    // Okuma OSP G71 single-line threading cycle -- NOT Fanuc G76. On Okuma OSP, G71 IS the
    // threading cycle (Fanuc's G71 = longitudinal roughing); emitting Fanuc G76 here alarms /
    // mis-cycles the control. Cloned from the dialect-complete
    // OkumaB250LatheMasterPostEngine.generateThreadingCycle, verified line-for-line vs Mark's
    // running JM programs (THREAD M8X125.MIN, A05-LSC-25-B.MIN) + the JM Multus .cps. Canonical:
    //   G71 X<minor dia, diametral> Z<end> B<incl angle> D<first cut> U<finish allow>
    //       H<height, diametral = 2x radial> F<lead mm> M33 M73
    // D/U = Mark's proven D.003"=0.08mm first cut, U.001"=0.025mm finish. G71 manages infeed/passes
    // internally (no Fanuc P/Q pass-count word). See reference_echo_okuma_cycle_dialect_2026_06_28.
    const angle = 60; // included thread angle (deg)
    const firstCut = 0.08; // D, first pass depth mm (Mark D.003")
    const finishAllow = 0.025; // U, finish allowance mm (Mark U.001")
    const minorDia = startX - depth * 2; // minor dia endpoint (diametral)
    const heightDia = depth * 2; // H output as diameter (2x radial depth)

    lines.push(`G0 X${(startX + 5).toFixed(1)} Z3.0 (THREAD START)`);
    lines.push(`(THREAD: PITCH=${pitch}mm DEPTH=${depth.toFixed(3)}mm -- OSP G71 SINGLE-LINE)`);
    lines.push(
      `G71 X${minorDia.toFixed(3)} Z${endZ.toFixed(3)} B${angle} ` +
        `D${firstCut.toFixed(3)} U${finishAllow.toFixed(3)} H${heightDia.toFixed(3)} ` +
        `F${pitch.toFixed(3)} M33 M73`,
    );
  }

  private generateDrill(lines: string[], op: TurningOperation) {
    const feed = op.feed_mm_rev ?? 0.15;
    const depth = op.end_z_mm ?? -30;

    lines.push(`G0 X0 Z2.0 (CENTER)`);
    lines.push(`G83 Z${depth.toFixed(1)} Q5000 F${feed.toFixed(3)} (PECK DRILL)`);
    lines.push(`G80`);
    lines.push(`G0 Z2.0`);
  }
}

export const ppOkumaTurningPostEngine = new PPOkumaTurningPostEngine();
