/**
 * PSNIncorporationOrchestratorEngine — MCP-callable orchestrator over the
 * PSN-INCORPORATION-MS0 envelope's DL/ML/reasoning units.
 *
 * Wraps `scripts/psn-incorp-automate.mjs` logic in a typed engine so the
 * fleet can invoke it via MCP dispatcher actions instead of bash.
 *
 * Pure orchestration — NO physics, NO inlined constants, NO stubs.
 * The engine reads `mcp-server/data/milestones/PSN-INCORPORATION-MS0.json`
 * and `state/shared/specs/psn-incorp/<unit-id>.md` (generated by the script)
 * and exposes typed queries over the result.
 *
 * Source envelope: PSN-INCORPORATION-MS0 (105 units across 9 phases)
 * Source script: scripts/psn-incorp-automate.mjs
 * Source skill: .claude/commands/psn-automate.md
 * Source Stop hook: .claude/hooks/stop-psn-automate-status.mjs
 *
 * Author: charlie slot (claude-451f7328) /goal-7 iter3, 2026-05-23.
 * Doctrine: feedback_psn_definition (legs #2, #6, #11), feedback_dont_soften_completeness_gates.
 */

import * as fs from "fs";
import * as path from "path";

// ML phases per the envelope's structure — same set the script filters on.
const ML_PHASES = new Set(["P4-R1-NEURAL", "P8-R3-LEARNING", "P9-R3-REASONING"]);

// Slot-soul domain regexes (mirror the script's SLOT_DOMAINS table).
const SLOT_DOMAINS: Record<string, RegExp> = {
  alpha: /\b(mill|milling|kienzle|chatter)\b/i,
  bravo: /\b(lathe|turning|swiss)\b/i,
  charlie: /\b(WEDM|wire|spark|recast|HAZ|kerf|flush|electrode|safety_gate|EDM)\b/i,
  delta: /\b(CAD|blueprint|OCR|drawing|SAM|CLIP)\b/i,
  echo: /\b(CAM|toolpath|hyperMILL|Mastercam)\b/i,
  foxtrot: /\b(tribal|wiki|knowledge|memory)\b/i,
  hotel: /\b(ERP|cost|quote|workflow|temporal|inngest)\b/i,
  india: /\b(post|controller|Fanuc|Siemens|Heidenhain|Outlines)\b/i,
  juliett: /\b(speed|feed|active learning|curriculum)\b/i,
  kilo: /\b(print-to-program|p2p|intake)\b/i,
  lima: /\b(academy|mobile|Continue)\b/i,
};

interface EnvelopeUnit {
  id: string;
  title: string;
  status: string;
  cost?: string;
  legs?: number[];
  source?: string;
  note?: string;
}

interface EnvelopeFile {
  id: string;
  phases?: Array<{ id: string; units: string[] }>;
  unit_list?: EnvelopeUnit[];
}

export interface OrchestratorOptions {
  envelopePath?: string;
  specsDir?: string;
}

export interface EligibleUnitsResult {
  envelopeId: string;
  mlPhases: string[];
  totalEligible: number;
  units: EnvelopeUnit[];
}

export interface PlanCoverageResult {
  totalEligible: number;
  plansOnDisk: number;
  withoutPlans: string[];
  withPlans: string[];
}

export interface SlotPickResult {
  slot: string;
  matched: EnvelopeUnit[];
  unmatched: number;
}

export class PSNIncorporationOrchestratorEngine {
  private envelopePath: string;
  private specsDir: string;

  constructor(opts: OrchestratorOptions = {}) {
    const repo = "H:/prism";
    this.envelopePath =
      opts.envelopePath ?? path.join(repo, "mcp-server/data/milestones/PSN-INCORPORATION-MS0.json");
    this.specsDir = opts.specsDir ?? path.join(repo, "state/shared/specs/psn-incorp");
  }

  private loadEnvelope(): EnvelopeFile {
    const raw = fs.readFileSync(this.envelopePath, "utf8");
    return JSON.parse(raw);
  }

  private mlPhaseUnitIds(env: EnvelopeFile): Set<string> {
    const ids = new Set<string>();
    for (const p of env.phases ?? []) {
      if (ML_PHASES.has(p.id)) for (const u of p.units ?? []) ids.add(u);
    }
    return ids;
  }

  /** All open DL/ML/reasoning units across the envelope. */
  listEligible(): EligibleUnitsResult {
    const env = this.loadEnvelope();
    const mlIds = this.mlPhaseUnitIds(env);
    const units = (env.unit_list ?? []).filter(
      (u) => mlIds.has(u.id) && u.status !== "complete" && u.status !== "completed"
    );
    return {
      envelopeId: env.id,
      mlPhases: [...ML_PHASES],
      totalEligible: units.length,
      units,
    };
  }

  /** Coverage report: how many eligible units have implementation plans on disk. */
  planCoverage(): PlanCoverageResult {
    const eligible = this.listEligible().units;
    let plansOnDisk: Set<string>;
    try {
      plansOnDisk = new Set(
        fs.readdirSync(this.specsDir)
          .filter((f) => f.endsWith(".md"))
          .map((f) => f.replace(/\.md$/, ""))
      );
    } catch {
      plansOnDisk = new Set();
    }
    const withPlans = eligible.filter((u) => plansOnDisk.has(u.id)).map((u) => u.id);
    const withoutPlans = eligible.filter((u) => !plansOnDisk.has(u.id)).map((u) => u.id);
    return {
      totalEligible: eligible.length,
      plansOnDisk: withPlans.length,
      withoutPlans,
      withPlans,
    };
  }

  /** Filter eligible units to a slot's domain regex (charlie picks wire-EDM, etc.). */
  pickForSlot(slot: string): SlotPickResult {
    const eligible = this.listEligible().units;
    const re = SLOT_DOMAINS[slot.toLowerCase()];
    if (!re) {
      return { slot, matched: [], unmatched: eligible.length };
    }
    const matched = eligible.filter((u) => re.test((u.title ?? "") + " " + (u.note ?? "")));
    return { slot, matched, unmatched: eligible.length - matched.length };
  }

  /** Get a specific unit's full record by ID. */
  getUnit(unitId: string): EnvelopeUnit | null {
    const env = this.loadEnvelope();
    return (env.unit_list ?? []).find((u) => u.id === unitId) ?? null;
  }

  /** Read the on-disk implementation plan for a unit, if it exists. */
  readPlan(unitId: string): string | null {
    const p = path.join(this.specsDir, unitId + ".md");
    try {
      return fs.readFileSync(p, "utf8");
    } catch {
      return null;
    }
  }
}

export const psnIncorporationOrchestratorEngine = new PSNIncorporationOrchestratorEngine();
