/**
 * SpecHTMLCompanionEngine — master Markdown → HTML renderer for PRISM strategic specs.
 *
 * Owns the HTML render layer for BACKEND-DEVTOOLS-RGS6 HTML-COMPANION-MS0 (HC-0..HC-5);
 * HTML-PRIMARY-MS0 (U-HPS01..07) consumes / hardens it. The contract is a *pure* function
 * `render(md, opts) → RenderResult` — no filesystem, no network — so it is equally usable
 * from the `scripts/emit-spec-html.mjs` CLI, the `prism_dev:spec_html_render` dispatcher
 * action, and unit tests.
 *
 * Self-contained: no `marked`/`markdown-it` dependency (none is installed and a strategic-spec
 * renderer must work offline + emit W3C-valid static HTML). The Markdown subset covered is the
 * one PRISM specs actually use:
 *   - ATX headings `#`..`######` → `<h1 id="slug">` … with collision-safe slugs (HC-3 anchors)
 *   - **bold** / *italic* / _italic_ / `code` / ~~strike~~  + inline `[text](url)` / `![alt](url)`
 *   - unordered (`-`/`*`/`+`) and ordered (`1.`) lists, nested by indent
 *   - GFM pipe tables with `:---` / `:---:` / `---:` column alignment
 *   - fenced code blocks (HTML-escaped); a `mermaid` fence → `<div class="mermaid">` (HC-3)
 *   - blockquotes `>` , thematic breaks `---`/`***`/`___`, paragraphs
 *   - YAML-ish frontmatter (`---` … `---`) → a metadata table at the top of the document
 *
 * Safety: every text / code-fence / attribute value is HTML-escaped; link & image URLs are
 * scheme-filtered (only http(s), mailto, tel, relative, and `#anchor` survive — `javascript:` etc.
 * are dropped). Raw HTML in the Markdown is escaped, never passed through. Oversized inputs are
 * truncated with a visible notice rather than risking OOM.
 *
 * Chrome: dark/light/auto theme via CSS custom properties + `prefers-color-scheme` (HC-2),
 * a table-of-contents sidebar built from the heading tree (HC-3), WAI-ARIA landmarks + a
 * skip-link (HC-4), and a source-hash `<meta>` the drift guard reads back (HC-5).
 *
 * References: CommonMark 0.31 (subset), GitHub-Flavored-Markdown tables, WAI-ARIA 1.2 landmark
 * roles, Thariq "HTML is the new Markdown" (2026-05-08) reconciled with Karpathy "docs are one
 * text file" — MD stays canonical, HTML is the human interface.
 */

import { createHash } from "node:crypto";

// ─── Public types ──────────────────────────────────────────────────────────

export type SpecHtmlTheme = "dark" | "light" | "auto";

export interface RenderOptions {
  /** Color theme. "auto" (default) follows `prefers-color-scheme`; "dark"/"light" pin it. */
  theme?: SpecHtmlTheme;
  /** Render a table-of-contents sidebar from headings (default true; auto-suppressed if <2 headings). */
  toc?: boolean;
  /** Document `<title>`. Defaults to frontmatter `title`/`milestone` → first H1 → "PRISM Spec". */
  title?: string;
  /** Optional "Generated by …" provenance shown under the title. */
  generatedBy?: string;
  /** Optional href to the canonical `.md` source, linked in the footer. */
  sourcePath?: string;
  /** Hard cap on input size in bytes; larger inputs are truncated with a notice. Default 16 MiB. */
  maxBytes?: number;
}

export interface SpecHeading {
  level: number;          // 1..6
  text: string;           // plain text (Markdown/HTML stripped)
  slug: string;           // unique #anchor id
}

export interface RenderResult {
  html: string;
  title: string;
  headings: SpecHeading[];
  frontmatter: Record<string, string>;
  /** Whether the source contained at least one mermaid fence (mermaid.js was embedded). */
  hasMermaid: boolean;
  /** sha256(source-markdown), hex — the drift guard compares this to its `.html.hash` sidecar. */
  sourceHash: string;
  /** Non-fatal issues encountered while rendering (malformed frontmatter, truncation, …). */
  warnings: string[];
  bytes: number;          // length of the produced HTML
}

// ─── Constants ─────────────────────────────────────────────────────────────

const DEFAULT_MAX_BYTES = 16 * 1024 * 1024;
const MERMAID_CDN = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
const MERMAID_EDGE_CAP = 4000;          // beyond this we warn the diagram may be slow in-browser
const SAFE_URL_SCHEMES = new Set(["http:", "https:", "mailto:", "tel:"]);
const HARD_BREAK = "";            // private-use sentinel for an intra-paragraph hard break (survives escaping)
const FENCE_LANG_TOKEN = /[^a-z0-9+#.\-]/g;

// ─── HTML escaping ─────────────────────────────────────────────────────────

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/** Escape text destined for an HTML text/attribute context. Call exactly once per value. */
export function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => HTML_ESCAPES[c]);
}

/** Decode the handful of entities `escapeHtml` produces (so URL handling sees original chars). */
function decodeEntities(s: string): string {
  return String(s)
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

/** Sanitize a link/image URL: allow http(s)/mailto/tel, relative paths and `#anchor`; drop the rest. */
function sanitizeUrl(raw: string): string {
  const url = String(raw).trim();
  if (!url) return "";
  if (url.startsWith("#") || url.startsWith("/") || url.startsWith("./") || url.startsWith("../")) return url;
  // No scheme at all → treat as a relative path (e.g. "FILE.md", "dir/file.html").
  if (!/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(url)) return url;
  const scheme = url.slice(0, url.indexOf(":") + 1).toLowerCase();
  return SAFE_URL_SCHEMES.has(scheme) ? url : "";
}

// ─── Slug generation (collision-safe — HC-3 anchor navigation) ─────────────

function makeSlugger(): (text: string) => string {
  const seen = new Map<string, number>();
  return (text: string): string => {
    const base =
      text
        .toLowerCase()
        .replace(/<[^>]*>/g, "")
        .normalize("NFKD")
        .replace(/[̀-ͯ]/g, "")        // strip combining marks
        .replace(/[^a-z0-9 _-]+/g, "")          // ASCII-only slug body — predictable, always valid id
        .trim()
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-+|-+$/g, "") || "section";
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return n === 0 ? base : `${base}-${n + 1}`;
  };
}

// ─── Inline rendering ──────────────────────────────────────────────────────

/**
 * Render Markdown inline syntax inside a single segment of text.
 * Strategy: lift out inline-code spans first (their contents are escaped, never further processed),
 * escape everything else, then run image/link/emphasis/strike on the escaped string. Because the
 * non-code text is escaped *before* the emphasis regexes run, nothing injected can leak markup.
 */
function renderInline(src: string): string {
  const codeSpans: string[] = [];
  // `code`, ``co`de`` — opening run of N backticks closed by another run of N (CommonMark-ish).
  let text = String(src).replace(/(`+)(.+?)\1(?!`)/g, (_m, _ticks, body) => {
    codeSpans.push(`<code>${escapeHtml(String(body).replace(/^ | $/g, ""))}</code>`);
    return `${codeSpans.length - 1}`;
  });

  text = escapeHtml(text);

  // Images  ![alt](url "title")  — handled before links (same bracket shape).
  text = text.replace(/!\[([^\]]*)\]\(\s*([^)\s]+)(?:\s+&quot;([^&]*)&quot;)?\s*\)/g, (_m, alt, url, title) => {
    const safe = sanitizeUrl(decodeEntities(url));
    if (!safe) return escapeHtml(`![${alt}]`);
    const t = title ? ` title="${escapeHtml(decodeEntities(title))}"` : "";
    return `<img src="${escapeHtml(safe)}" alt="${alt}"${t} loading="lazy">`;
  });

  // Links  [text](url "title")
  text = text.replace(/\[([^\]]+)\]\(\s*([^)\s]+)(?:\s+&quot;([^&]*)&quot;)?\s*\)/g, (_m, label, url, title) => {
    const safe = sanitizeUrl(decodeEntities(url));
    if (!safe) return label;
    const t = title ? ` title="${escapeHtml(decodeEntities(title))}"` : "";
    const rel = /^https?:/i.test(safe) ? ' rel="noopener noreferrer"' : "";
    return `<a href="${escapeHtml(safe)}"${t}${rel}>${label}</a>`;
  });

  // Bold then italic (so `**x**` isn't half-consumed by the `*x*` rule).
  text = text.replace(/\*\*([^*]+?)\*\*/g, "<strong>$1</strong>");
  text = text.replace(/__([^_]+?)__/g, "<strong>$1</strong>");
  text = text.replace(/(^|[^*\w])\*([^*\s][^*]*?)\*(?!\w)/g, "$1<em>$2</em>");
  text = text.replace(/(^|[^_\w])_([^_\s][^_]*?)_(?!\w)/g, "$1<em>$2</em>");
  text = text.replace(/~~([^~]+?)~~/g, "<del>$1</del>");

  // Restore code spans.
  text = text.replace(/(\d+)/g, (_m, i) => codeSpans[Number(i)] ?? "");
  // Intra-paragraph hard breaks (set by the block layer).
  return text.replace(new RegExp(HARD_BREAK, "g"), "<br>\n");
}

/** Plain-text projection of an inline string (heading → TOC text + slug). */
function inlineToPlainText(src: string): string {
  return String(src)
    .replace(/`+([^`]*)`+/g, "$1")
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\*\*([^*]+?)\*\*|__([^_]+?)__/g, "$1$2")
    .replace(/\*([^*]+?)\*|_([^_]+?)_/g, "$1$2")
    .replace(/~~([^~]+?)~~/g, "$1")
    .replace(/<[^>]*>/g, "")
    .replace(new RegExp(HARD_BREAK, "g"), " ")
    .trim();
}

// ─── Frontmatter ───────────────────────────────────────────────────────────

/**
 * Pull a leading `---` … `---` block off the top. No YAML dependency: specs use it for flat
 * `key: value` (plus nested `key:` headers we fold into the parent as a readable string). If the
 * opening `---` has no closing fence within the first 250 lines we treat the whole input as body
 * and warn (the malformed-frontmatter failure mode).
 */
function extractFrontmatter(md: string, warnings: string[]): { frontmatter: Record<string, string>; body: string } {
  const empty = { frontmatter: {} as Record<string, string>, body: md };
  if (!/^---\r?\n/.test(md)) return empty;
  const lines = md.split(/\r?\n/);
  let end = -1;
  for (let i = 1; i < lines.length && i < 250; i++) {
    if (lines[i] === "---" || lines[i] === "...") { end = i; break; }
  }
  if (end === -1) {
    warnings.push("frontmatter opened with '---' but no closing '---' within 250 lines — treated as body");
    return empty;
  }
  const fm: Record<string, string> = {};
  let lastKey = "";
  for (let i = 1; i < end; i++) {
    const line = lines[i];
    if (!line.trim() || /^\s*#/.test(line)) continue;
    const kv = /^(\s*)([A-Za-z0-9_.\- ]+?):\s?(.*)$/.exec(line);
    if (kv) {
      const indent = kv[1].length;
      const key = kv[2].trim();
      const val = kv[3].trim().replace(/^["']|["']$/g, "");
      if (indent === 0) { fm[key] = val; lastKey = key; }
      else if (lastKey) {
        const piece = `${key}${val ? ": " + val : ""}`;
        fm[lastKey] = fm[lastKey] ? `${fm[lastKey]}; ${piece}` : piece;
      }
    } else if (/^\s*-\s+/.test(line) && lastKey) {
      const item = line.replace(/^\s*-\s+/, "").trim();
      fm[lastKey] = fm[lastKey] ? `${fm[lastKey]}, ${item}` : item;
    }
  }
  return { frontmatter: fm, body: lines.slice(end + 1).join("\n") };
}

// ─── Block-level parsing ───────────────────────────────────────────────────

interface BlockState {
  out: string[];
  headings: SpecHeading[];
  slug: (t: string) => string;
  hasMermaid: boolean;
  warnings: string[];
}

const RE = {
  heading: /^(#{1,6})\s+(.*?)\s*#*\s*$/,
  fence: /^\s*(`{3,}|~{3,})\s*([^\s`~]*)\s*$/,
  hr: /^\s{0,3}([-*_])(?:\s*\1){2,}\s*$/,
  ulItem: /^(\s*)([-*+])\s+(.*)$/,
  olItem: /^(\s*)(\d{1,9})[.)]\s+(.*)$/,
  blockquote: /^\s{0,3}>\s?(.*)$/,
  tableSep: /^\s*\|?\s*:?-{1,}:?\s*(\|\s*:?-{1,}:?\s*)+\|?\s*$/,
};

function isBlockStarter(line: string): boolean {
  return RE.heading.test(line) || RE.fence.test(line) || RE.hr.test(line) || RE.blockquote.test(line) || RE.ulItem.test(line) || RE.olItem.test(line);
}

function renderBlocks(md: string, st: BlockState): void {
  const lines = md.split(/\r?\n/);
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (!line.trim()) { i++; continue; }

    // Fenced code block.
    const fence = RE.fence.exec(line);
    if (fence) {
      const marker = fence[1];
      const fenceChar = marker[0];
      const minLen = marker.length;
      const closeRe = new RegExp("^\\s*" + (fenceChar === "`" ? "`" : "~") + "{" + minLen + ",}\\s*$");
      const buf: string[] = [];
      i++;
      while (i < lines.length) {
        if (closeRe.test(lines[i])) { i++; break; }
        buf.push(lines[i]);
        i++;
      }
      const lang = (fence[2] || "").toLowerCase().replace(FENCE_LANG_TOKEN, "");
      if (lang === "mermaid") {
        st.hasMermaid = true;
        const graph = buf.join("\n");
        const edgeGuess = (graph.match(/-->|---|==>|-\.->/g) || []).length;
        if (edgeGuess > MERMAID_EDGE_CAP) st.warnings.push(`mermaid block is large (~${edgeGuess} edges) — in-browser render may be slow`);
        st.out.push(`<div class="mermaid">\n${escapeHtml(graph)}\n</div>`);
      } else {
        const cls = lang ? ` class="language-${lang}"` : "";
        st.out.push(`<pre><code${cls}>${escapeHtml(buf.join("\n"))}\n</code></pre>`);
      }
      continue;
    }

    // ATX heading.
    const h = RE.heading.exec(line);
    if (h) {
      const level = h[1].length;
      const rawInline = h[2];
      const plain = inlineToPlainText(rawInline) || "Section";
      const slug = st.slug(plain);
      st.headings.push({ level, text: plain, slug });
      st.out.push(
        `<h${level} id="${escapeHtml(slug)}">` +
          `<a class="anchor" href="#${escapeHtml(slug)}" aria-label="Permalink to ${escapeHtml(plain)}">#</a>` +
          renderInline(rawInline) +
          `</h${level}>`,
      );
      i++;
      continue;
    }

    // Thematic break.
    if (RE.hr.test(line)) { st.out.push("<hr>"); i++; continue; }

    // GFM table: a header row immediately followed by a delimiter row.
    if (line.includes("|") && i + 1 < lines.length && RE.tableSep.test(lines[i + 1])) {
      const headerCells = splitTableRow(line);
      const aligns = splitTableRow(lines[i + 1]).map((c) => {
        const t = c.trim();
        const l = t.startsWith(":"), r = t.endsWith(":");
        return l && r ? "center" : r ? "right" : l ? "left" : "";
      });
      i += 2;
      const bodyRows: string[][] = [];
      while (i < lines.length && lines[i].includes("|") && lines[i].trim() && !RE.fence.test(lines[i]) && !RE.heading.test(lines[i])) {
        bodyRows.push(splitTableRow(lines[i]));
        i++;
      }
      st.out.push(renderTable(headerCells, aligns, bodyRows));
      continue;
    }

    // Blockquote — consume the contiguous run, recurse on the de-quoted body.
    if (RE.blockquote.test(line)) {
      const buf: string[] = [];
      while (i < lines.length && lines[i].trim() && RE.blockquote.test(lines[i])) {
        buf.push(lines[i].replace(/^\s{0,3}>\s?/, ""));
        i++;
      }
      const inner: BlockState = { out: [], headings: st.headings, slug: st.slug, hasMermaid: false, warnings: st.warnings };
      renderBlocks(buf.join("\n"), inner);
      st.hasMermaid = st.hasMermaid || inner.hasMermaid;
      st.out.push(`<blockquote>\n${inner.out.join("\n")}\n</blockquote>`);
      continue;
    }

    // Lists (unordered / ordered), nested by indent.
    if (RE.ulItem.test(line) || RE.olItem.test(line)) {
      const { html, next } = parseList(lines, i);
      st.out.push(html);
      i = next;
      continue;
    }

    // Paragraph — accumulate until a blank line, a block-starter, or a table header.
    const para: string[] = [];
    while (i < lines.length && lines[i].trim()) {
      const l = lines[i];
      if (isBlockStarter(l)) break;
      if (l.includes("|") && i + 1 < lines.length && RE.tableSep.test(lines[i + 1])) break;
      para.push(l);
      i++;
    }
    if (para.length) {
      let joined = "";
      para.forEach((p, idx) => {
        const hard = /(\\| {2,})$/.test(p) && idx < para.length - 1;
        joined += p.replace(/\s+$/, "");
        if (idx < para.length - 1) joined += hard ? HARD_BREAK : " ";
      });
      st.out.push(`<p>${renderInline(joined)}</p>`);
    }
  }
}

function splitTableRow(row: string): string[] {
  let s = row.trim();
  if (s.startsWith("|")) s = s.slice(1);
  if (s.endsWith("|")) s = s.slice(0, -1);
  const cells: string[] = [];
  let cur = "";
  for (let i = 0; i < s.length; i++) {
    if (s[i] === "\\" && s[i + 1] === "|") { cur += "|"; i++; continue; }
    if (s[i] === "|") { cells.push(cur); cur = ""; continue; }
    cur += s[i];
  }
  cells.push(cur);
  return cells.map((c) => c.trim());
}

function renderTable(header: string[], aligns: string[], rows: string[][]): string {
  const th = header
    .map((c, k) => `<th${aligns[k] ? ` style="text-align:${aligns[k]}"` : ""}>${renderInline(c)}</th>`)
    .join("");
  const body = rows
    .map((r) => {
      const cells: string[] = [];
      for (let k = 0; k < header.length; k++) {
        const v = r[k] ?? "";
        cells.push(`<td${aligns[k] ? ` style="text-align:${aligns[k]}"` : ""}>${renderInline(v)}</td>`);
      }
      return `<tr>${cells.join("")}</tr>`;
    })
    .join("\n");
  return `<div class="table-wrap"><table>\n<thead><tr>${th}</tr></thead>\n<tbody>\n${body}\n</tbody>\n</table></div>`;
}

/**
 * Parse a (possibly nested) list starting at `lines[start]`. Returns the rendered `<ul>`/`<ol>`
 * and the index of the first line *after* the list. A more-indented item opens a sublist inside
 * the current `<li>`; a less-indented item belongs to an outer list and terminates this one.
 */
function parseList(lines: string[], start: number): { html: string; next: number } {
  const firstM = (RE.ulItem.exec(lines[start]) || RE.olItem.exec(lines[start])) as RegExpExecArray;
  const baseIndent = firstM[1].length;
  const ordered = !!RE.olItem.exec(lines[start]);
  const startNum = ordered ? parseInt((RE.olItem.exec(lines[start]) as RegExpExecArray)[2], 10) : 1;
  const items: string[] = [];
  let i = start;

  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) {
      // One blank line may separate "loose" items — peek; bail if the list clearly ended.
      const nextItemM = i + 1 < lines.length ? (RE.ulItem.exec(lines[i + 1]) || RE.olItem.exec(lines[i + 1])) : null;
      if (nextItemM && nextItemM[1].length >= baseIndent) { i++; continue; }
      break;
    }
    const m = RE.ulItem.exec(line) || RE.olItem.exec(line);
    if (m) {
      const indent = m[1].length;
      if (indent < baseIndent) break;
      if (indent > baseIndent) {
        const sub = parseList(lines, i);
        if (items.length === 0) items.push("<li>");
        items[items.length - 1] = items[items.length - 1].replace(/<\/li>$/, "") + "\n" + sub.html;
        if (!/<\/li>$/.test(items[items.length - 1])) items[items.length - 1] += "</li>";
        i = sub.next;
        continue;
      }
      const cont: string[] = [m[3]];
      i++;
      while (i < lines.length && lines[i].trim() && !RE.ulItem.test(lines[i]) && !RE.olItem.test(lines[i]) && !isBlockStarter(lines[i])) {
        const indentOf = lines[i].match(/^(\s*)/)?.[1].length ?? 0;
        if (indentOf <= baseIndent) break;
        cont.push(lines[i].trim());
        i++;
      }
      items.push(`<li>${renderInline(cont.join(" "))}</li>`);
      continue;
    }
    // Non-item line: if it's at/under base indent the list is over; otherwise it's loose prose
    // under the previous item (rare in PRISM specs) — fold it into that <li>.
    if ((line.match(/^(\s*)/)?.[1].length ?? 0) <= baseIndent) break;
    if (items.length) {
      const last = items.length - 1;
      items[last] = items[last].replace(/<\/li>$/, ` ${renderInline(line.trim())}</li>`);
    }
    i++;
  }

  const tag = ordered ? "ol" : "ul";
  const startAttr = ordered && startNum !== 1 ? ` start="${startNum}"` : "";
  return { html: `<${tag}${startAttr}>\n${items.join("\n")}\n</${tag}>`, next: i };
}

// ─── TOC + metadata panel ──────────────────────────────────────────────────

function renderToc(headings: SpecHeading[]): string {
  const usable = headings.filter((h) => h.level >= 1 && h.level <= 4);
  if (usable.length < 2) return "";
  const items = usable
    .map((h) => `<li class="toc-l${h.level}"><a href="#${escapeHtml(h.slug)}">${escapeHtml(h.text)}</a></li>`)
    .join("\n");
  return `<nav class="toc" aria-label="Table of contents"><div class="toc-title">On this page</div><ul>\n${items}\n</ul></nav>`;
}

function renderFrontmatterPanel(fm: Record<string, string>): string {
  const keys = Object.keys(fm).filter((k) => fm[k] !== undefined && fm[k] !== "");
  if (keys.length === 0) return "";
  const rows = keys.map((k) => `<tr><th scope="row">${escapeHtml(k)}</th><td>${renderInline(fm[k])}</td></tr>`).join("\n");
  return `<details class="frontmatter" open><summary>Document metadata</summary><div class="table-wrap"><table>\n<tbody>\n${rows}\n</tbody>\n</table></div></details>`;
}

// ─── Page chrome ───────────────────────────────────────────────────────────

function pageStyles(): string {
  return `
:root, [data-theme="light"] {
  --bg:#ffffff; --bg-soft:#f6f8fa; --bg-code:#f6f8fa; --fg:#1f2328; --fg-muted:#636c76;
  --border:#d0d7de; --accent:#0969da; --accent-soft:#ddf4ff; --thead:#f6f8fa; --quote:#656d76;
  --table-stripe:#f6f8fa;
}
[data-theme="dark"] {
  --bg:#0d1117; --bg-soft:#161b22; --bg-code:#161b22; --fg:#e6edf3; --fg-muted:#8b949e;
  --border:#30363d; --accent:#2f81f7; --accent-soft:#163356; --thead:#161b22; --quote:#8b949e;
  --table-stripe:#11151c;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg:#0d1117; --bg-soft:#161b22; --bg-code:#161b22; --fg:#e6edf3; --fg-muted:#8b949e;
    --border:#30363d; --accent:#2f81f7; --accent-soft:#163356; --thead:#161b22; --quote:#8b949e;
    --table-stripe:#11151c;
  }
}
* { box-sizing:border-box; }
html { scroll-behavior:smooth; }
body { margin:0; background:var(--bg); color:var(--fg); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; line-height:1.6; font-size:16px; }
.skip-link { position:absolute; left:-9999px; top:0; background:var(--accent); color:#fff; padding:8px 14px; z-index:100; border-radius:0 0 6px 0; }
.skip-link:focus { left:0; }
.layout { display:grid; grid-template-columns:minmax(0,1fr); max-width:1180px; margin:0 auto; padding:0 20px; }
@media (min-width:1000px) { .layout { grid-template-columns:260px minmax(0,1fr); gap:40px; } }
header.doc-head { grid-column:1 / -1; padding:28px 0 16px; border-bottom:1px solid var(--border); }
header.doc-head h1.page-title { margin:0 0 6px; font-size:1.9rem; line-height:1.25; }
header.doc-head .provenance { color:var(--fg-muted); font-size:.85rem; margin:0; }
header.doc-head .theme-toggle { float:right; background:var(--bg-soft); color:var(--fg); border:1px solid var(--border); border-radius:6px; padding:5px 10px; font-size:.8rem; cursor:pointer; }
nav.toc { align-self:start; position:sticky; top:16px; max-height:calc(100vh - 32px); overflow:auto; font-size:.85rem; padding:14px 0; }
@media (max-width:999px) { nav.toc { position:static; max-height:none; border-bottom:1px solid var(--border); margin-bottom:12px; } }
nav.toc .toc-title { font-weight:600; color:var(--fg-muted); text-transform:uppercase; letter-spacing:.04em; font-size:.7rem; margin-bottom:8px; }
nav.toc ul { list-style:none; margin:0; padding:0; }
nav.toc li a { color:var(--fg-muted); text-decoration:none; display:block; padding:3px 6px; border-left:2px solid transparent; border-radius:0 4px 4px 0; }
nav.toc li a:hover { color:var(--accent); background:var(--accent-soft); border-left-color:var(--accent); }
nav.toc .toc-l2 a { padding-left:14px; } nav.toc .toc-l3 a { padding-left:26px; font-size:.95em; } nav.toc .toc-l4 a { padding-left:38px; font-size:.9em; }
main.doc-body { min-width:0; padding:24px 0 64px; }
main.doc-body h1,main.doc-body h2,main.doc-body h3,main.doc-body h4,main.doc-body h5,main.doc-body h6 { line-height:1.3; margin-top:1.8em; margin-bottom:.6em; scroll-margin-top:16px; position:relative; }
main.doc-body h1 { font-size:1.7rem; border-bottom:1px solid var(--border); padding-bottom:.3em; }
main.doc-body h2 { font-size:1.4rem; border-bottom:1px solid var(--border); padding-bottom:.3em; }
main.doc-body h3 { font-size:1.18rem; } main.doc-body h4 { font-size:1.02rem; }
main.doc-body a.anchor { position:absolute; left:-1.1em; opacity:0; text-decoration:none; color:var(--fg-muted); font-weight:400; padding-right:.3em; }
main.doc-body h1:hover a.anchor,main.doc-body h2:hover a.anchor,main.doc-body h3:hover a.anchor,main.doc-body h4:hover a.anchor { opacity:1; }
main.doc-body a { color:var(--accent); text-decoration:none; } main.doc-body a:hover { text-decoration:underline; }
main.doc-body p { margin:.8em 0; }
main.doc-body code { background:var(--bg-code); border-radius:4px; padding:.15em .35em; font-size:.88em; font-family:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace; }
main.doc-body pre { background:var(--bg-code); border:1px solid var(--border); border-radius:8px; padding:14px 16px; overflow:auto; line-height:1.45; }
main.doc-body pre code { background:none; padding:0; font-size:.86rem; }
main.doc-body blockquote { margin:1em 0; padding:.4em 1em; border-left:4px solid var(--border); color:var(--quote); }
main.doc-body ul,main.doc-body ol { margin:.6em 0; padding-left:1.6em; }
main.doc-body li { margin:.2em 0; }
main.doc-body hr { border:0; border-top:1px solid var(--border); margin:2em 0; }
main.doc-body .table-wrap { overflow-x:auto; margin:1em 0; }
main.doc-body table { border-collapse:collapse; width:100%; font-size:.9rem; }
main.doc-body th,main.doc-body td { border:1px solid var(--border); padding:6px 11px; text-align:left; vertical-align:top; }
main.doc-body thead th { background:var(--thead); }
main.doc-body tbody tr:nth-child(2n) { background:var(--table-stripe); }
main.doc-body details.frontmatter { background:var(--bg-soft); border:1px solid var(--border); border-radius:8px; padding:6px 14px; margin:0 0 22px; }
main.doc-body details.frontmatter summary { cursor:pointer; font-weight:600; color:var(--fg-muted); }
main.doc-body details.frontmatter table { font-size:.82rem; }
main.doc-body details.frontmatter th { width:1%; white-space:nowrap; background:transparent; color:var(--fg-muted); }
main.doc-body .mermaid { background:var(--bg-soft); border:1px solid var(--border); border-radius:8px; padding:14px; margin:1em 0; text-align:center; overflow:auto; white-space:pre-wrap; }
main.doc-body .truncation-notice { background:var(--accent-soft); border:1px solid var(--accent); border-radius:6px; padding:10px 14px; font-size:.9rem; }
footer.doc-foot { grid-column:1 / -1; border-top:1px solid var(--border); margin-top:48px; padding:18px 0 40px; color:var(--fg-muted); font-size:.82rem; }
footer.doc-foot code { background:var(--bg-code); border-radius:4px; padding:.12em .3em; }
`;
}

/** Progressive enhancement: the page is fully styled without JS — this only lets a reader pin a theme. */
function themeToggleScript(): string {
  return `(function(){
  try {
    var k = "prism-spec-theme";
    var saved = localStorage.getItem(k);
    if (saved === "dark" || saved === "light") document.documentElement.setAttribute("data-theme", saved);
  } catch (e) { /* localStorage blocked — keep default theme */ }
  var b = document.getElementById("themeToggle");
  if (!b) return;
  b.addEventListener("click", function () {
    var cur = document.documentElement.getAttribute("data-theme");
    var sysDark = !!(window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches);
    var next = cur === "dark" ? "light" : cur === "light" ? "dark" : (sysDark ? "light" : "dark");
    document.documentElement.setAttribute("data-theme", next);
    b.textContent = next === "dark" ? "\\u263E dark" : "\\u2600 light";
    try { localStorage.setItem(k, next); } catch (e) { /* persistence unavailable — non-fatal */ }
  });
})();`;
}

/** Loaded only when the doc actually contains a mermaid fence. CDN-down → diagrams stay readable text. */
function mermaidScript(): string {
  return `import mermaid from "${MERMAID_CDN}";
try {
  var pinned = document.documentElement.getAttribute("data-theme");
  var sysDark = !!(window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches);
  var dark = pinned === "dark" || (pinned !== "light" && sysDark);
  mermaid.initialize({ startOnLoad: true, securityLevel: "strict", theme: dark ? "dark" : "default" });
} catch (e) { /* leave the raw mermaid text visible inside .mermaid */ }`;
}

// ─── Engine ────────────────────────────────────────────────────────────────

export class SpecHTMLCompanionEngine {
  /** Pure: Markdown string → standalone HTML document. Never throws on weird input; collects warnings. */
  render(markdown: string, opts: RenderOptions = {}): RenderResult {
    const warnings: string[] = [];
    let md = typeof markdown === "string" ? markdown : String(markdown ?? "");
    const sourceHash = createHash("sha256").update(md, "utf8").digest("hex");

    const maxBytes = opts.maxBytes && opts.maxBytes > 0 ? opts.maxBytes : DEFAULT_MAX_BYTES;
    let truncated = false;
    if (Buffer.byteLength(md, "utf8") > maxBytes) {
      md = Buffer.from(md, "utf8").subarray(0, maxBytes).toString("utf8");
      const lastNl = md.lastIndexOf("\n");
      if (lastNl > 0) md = md.slice(0, lastNl);
      truncated = true;
      warnings.push(`input exceeded ${maxBytes} bytes — truncated for safe rendering`);
    }

    const { frontmatter, body } = extractFrontmatter(md, warnings);

    const st: BlockState = { out: [], headings: [], slug: makeSlugger(), hasMermaid: false, warnings };
    try {
      renderBlocks(body, st);
    } catch (err) {
      warnings.push(`block render error: ${(err as Error).message} — emitting partial output`);
    }

    const firstH1 = st.headings.find((h) => h.level === 1)?.text;
    const title = String(opts.title || frontmatter.title || frontmatter.milestone || firstH1 || "PRISM Spec").trim() || "PRISM Spec";
    const wantToc = opts.toc !== false;
    const theme: SpecHtmlTheme = opts.theme === "dark" || opts.theme === "light" ? opts.theme : "auto";

    const tocHtml = wantToc ? renderToc(st.headings) : "";
    const fmHtml = renderFrontmatterPanel(frontmatter);
    const bodyInner = st.out.join("\n");
    const truncNotice = truncated
      ? `<div class="truncation-notice">⚠ Truncated to the first ${maxBytes.toLocaleString()} bytes for safe rendering — see the canonical <code>.md</code> for the full text.</div>\n`
      : "";

    const provenance: string[] = [`Generated ${new Date().toISOString()}`];
    if (opts.generatedBy) provenance.push(`by <code>${escapeHtml(opts.generatedBy)}</code>`);
    provenance.push("· the Markdown alongside is canonical");

    const htmlAttr = theme === "auto" ? "" : ` data-theme="${theme}"`;
    const sourceLink = opts.sourcePath ? ` <a href="${escapeHtml(escapeHtml(opts.sourcePath))}">${escapeHtml(opts.sourcePath)}</a>` : "";
    const scripts = [
      `<script>${themeToggleScript()}</script>`,
      st.hasMermaid ? `<script type="module">${mermaidScript()}</script>` : "",
    ].filter(Boolean).join("\n");

    const html = `<!DOCTYPE html>
<html lang="en"${htmlAttr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="SpecHTMLCompanionEngine">
<meta name="prism-source-hash" content="${sourceHash}">
<title>${escapeHtml(title)}</title>
<style>${pageStyles()}</style>
</head>
<body>
<a class="skip-link" href="#content">Skip to content</a>
<div class="layout">
<header class="doc-head">
<button id="themeToggle" class="theme-toggle" type="button" aria-label="Toggle color theme">${theme === "dark" ? "☾ dark" : theme === "light" ? "☀ light" : "◐ theme"}</button>
<h1 class="page-title">${escapeHtml(title)}</h1>
<p class="provenance">${provenance.join(" ")}</p>
</header>
${tocHtml}
<main id="content" class="doc-body" role="main">
${truncNotice}${fmHtml ? fmHtml + "\n" : ""}${bodyInner}
</main>
<footer class="doc-foot">
<p>HTML companion — the canonical document is the Markdown file alongside it.${sourceLink} Regenerate: <code>node scripts/emit-spec-html.mjs &lt;path.md&gt;</code></p>
${warnings.length ? `<p>Render warnings: ${warnings.map((w) => escapeHtml(w)).join("; ")}</p>` : ""}
</footer>
</div>
${scripts}
</body>
</html>
`;

    return {
      html,
      title,
      headings: st.headings,
      frontmatter,
      hasMermaid: st.hasMermaid,
      sourceHash,
      warnings,
      bytes: html.length,
    };
  }

  /** sha256(markdown), hex — used by the HC-5 drift guard (`emit-spec-html.mjs --check-drift`). */
  hashSource(markdown: string): string {
    return createHash("sha256").update(typeof markdown === "string" ? markdown : String(markdown ?? ""), "utf8").digest("hex");
  }

  /**
   * Has the HTML twin drifted from its source? Compares sha256(md) against the `prism-source-hash`
   * `<meta>` embedded in a previously-generated HTML. Returns true when they differ (regen needed)
   * or when the HTML carries no recorded hash.
   */
  isDrifted(markdown: string, generatedHtml: string): boolean {
    const want = this.hashSource(markdown);
    const m = /<meta\s+name="prism-source-hash"\s+content="([0-9a-f]{64})"/i.exec(String(generatedHtml ?? ""));
    if (!m) return true;
    return m[1] !== want;
  }
}

export const specHtmlCompanionEngine = new SpecHTMLCompanionEngine();
