/**
 * TribalVaultPopulatorEngine — turn the in-memory TribalKnowledgeEngine
 * tip list into a directory of Markdown files under `knowledge/tribal/`,
 * one per tip, with Obsidian wikilink backlinks between related tips.
 *
 * Milestone: INTEL-OLLAMA-OBSIDIAN-MS0 / P1-U03.
 *
 * Why this exists
 * ---------------
 * PRISM's TribalKnowledgeEngine holds 3,000+ machinist tips in memory but
 * has no on-disk vault representation. Without that, Qdrant can't embed
 * them, the wiki can't surface them, and an offline operator on a second
 * PC can't read them. This populator is the missing on-disk projection.
 *
 * Design
 * ------
 * Pure side-effect engine on top of caller-supplied tips (the list from
 * TribalKnowledgeEngine.search({limit: 99999})). Idempotent on content
 * hash baked into mirror frontmatter. Backlinks are generated by
 * grouping tips by `category` + `material_groups` overlap so each tip
 * links to up to N siblings in the same lane.
 *
 * Idempotency: a vault file is rewritten only when the source tip's
 * normalized SHA-256 differs from the hash baked into the existing
 * mirror's frontmatter.
 *
 * Failure mode: every I/O wrapped — engine returns a structured
 * PopulateResult, never throws.
 *
 * @module engines/TribalVaultPopulatorEngine
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";

const SCHEMA_VERSION = "1.0.0";
const FRONTMATTER_OPEN_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
const CONTENT_HASH_RE = /^content_hash:\s*([a-f0-9]+)\s*$/im;

/** Loose structural type matching `KnowledgeTip` from TribalKnowledgeEngine. */
export interface TribalTipLike {
  id: string;
  title: string;
  body: string;
  category: string;
  subcategory?: string;
  domain?: string;
  knowledge_type?: string;
  tags: string[];
  material_groups?: string[];
  operation_types?: string[];
  machine_ids?: string[];
  workholding_type?: string;
  confidence: number;
  source: string;
  created_at: string;
  usage_count?: number;
}

export interface PopulateOpts {
  /** All tips to project to disk. */
  tips: TribalTipLike[];
  /** Vault root. Default: H:/prism/knowledge/tribal */
  vaultRoot?: string;
  /** Maximum number of backlinks to generate per tip. Default 5. */
  maxBacklinks?: number;
  /** When true, plan but do not write. */
  dryRun?: boolean;
  /** Optional embed callback: invoked with each newly-written tip. Best-effort. */
  embed?: (tip: TribalTipLike, vaultPath: string, body: string) => Promise<void> | void;
}

export interface PopulateResult {
  ok: boolean;
  tipsScanned: number;
  filesWritten: number;
  /** Files whose content_hash matched the existing mirror — no rewrite. */
  filesSkipped: number;
  filesFailed: number;
  embedAttempts: number;
  embedSuccesses: number;
  errors: Array<{ tipId: string; error: string }>;
  vaultRoot: string;
  durationMs: number;
}

const DEFAULT_VAULT_ROOT = process.env.PRISM_TRIBAL_DIR
  ?? "H:/prism/knowledge/tribal";
const DEFAULT_MAX_BACKLINKS = 5;

export class TribalVaultPopulatorEngine {
  /**
   * Populate the vault from a tip array. Idempotent on each tip's
   * content hash. Never throws.
   */
  async populate(opts: PopulateOpts): Promise<PopulateResult> {
    const start = Date.now();
    const vaultRoot = opts.vaultRoot ?? DEFAULT_VAULT_ROOT;
    const maxBacklinks = opts.maxBacklinks ?? DEFAULT_MAX_BACKLINKS;
    const dryRun = opts.dryRun === true;

    const result: PopulateResult = {
      ok: true,
      tipsScanned: 0,
      filesWritten: 0,
      filesSkipped: 0,
      filesFailed: 0,
      embedAttempts: 0,
      embedSuccesses: 0,
      errors: [],
      vaultRoot,
      durationMs: 0,
    };

    const tips = Array.isArray(opts.tips) ? opts.tips : [];
    result.tipsScanned = tips.length;

    if (tips.length === 0) {
      result.durationMs = Date.now() - start;
      return result;
    }

    if (!dryRun) {
      try { fs.mkdirSync(vaultRoot, { recursive: true }); } catch { /* mirrorOne will catch */ }
    }

    const slugToTip = new Map<string, TribalTipLike>();
    for (const tip of tips) slugToTip.set(this.tipSlug(tip), tip);
    const backlinkIndex = this.buildBacklinkIndex(tips, maxBacklinks);

    for (const tip of tips) {
      try {
        const filename = `${this.tipSlug(tip)}.md`;
        const target = path.join(vaultRoot, filename);
        const hash = this.hashTip(tip);

        if (fs.existsSync(target)) {
          const existing = fs.readFileSync(target, "utf-8");
          if (this.extractContentHash(existing) === hash) {
            result.filesSkipped++;
            continue;
          }
        }

        const backlinks = backlinkIndex.get(tip.id) ?? [];
        const body = this.renderTip(tip, hash, backlinks);

        if (dryRun) {
          result.filesWritten++;
          continue;
        }

        this.atomicWrite(target, body);
        result.filesWritten++;

        if (opts.embed) {
          result.embedAttempts++;
          try {
            await opts.embed(tip, target, body);
            result.embedSuccesses++;
          } catch (e) {
            // embed failure is best-effort; never propagates
            result.errors.push({ tipId: tip.id, error: `embed: ${(e as Error).message ?? e}` });
          }
        }
      } catch (e) {
        result.filesFailed++;
        result.errors.push({ tipId: tip.id, error: (e as Error).message ?? String(e) });
      }
    }

    result.ok = result.filesFailed === 0;
    result.durationMs = Date.now() - start;
    return result;
  }

  /** Stable filesystem-safe slug from tip id (preserves uniqueness via hash suffix). */
  tipSlug(tip: TribalTipLike): string {
    const base = String(tip.id ?? tip.title ?? "tip")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80);
    if (base.length > 0) return base || "tip";
    // Pure-symbol id collapse — fall back to short hash
    return "tip-" + this.hashContent(String(tip.id)).slice(0, 8);
  }

  hashTip(tip: TribalTipLike): string {
    const canonical = JSON.stringify({
      id: tip.id,
      title: tip.title,
      body: tip.body,
      category: tip.category,
      subcategory: tip.subcategory ?? null,
      domain: tip.domain ?? null,
      tags: [...(tip.tags ?? [])].sort(),
      material_groups: [...(tip.material_groups ?? [])].sort(),
      operation_types: [...(tip.operation_types ?? [])].sort(),
      confidence: tip.confidence,
    });
    return this.hashContent(canonical);
  }

  hashContent(s: string): string {
    return createHash("sha256").update(s, "utf-8").digest("hex");
  }

  extractContentHash(mirrored: string): string | null {
    const fm = mirrored.match(FRONTMATTER_OPEN_RE);
    if (!fm) return null;
    const m = fm[1].match(CONTENT_HASH_RE);
    return m ? m[1] : null;
  }

  /**
   * For each tip, find up to maxBacklinks sibling tips by:
   *   1. Same category (highest priority)
   *   2. Overlapping material_groups
   *   3. Overlapping operation_types
   * Sorted by overlap score, then by confidence.
   */
  buildBacklinkIndex(tips: TribalTipLike[], maxBacklinks: number): Map<string, Array<{ id: string; slug: string; title: string; reason: string }>> {
    const result = new Map<string, Array<{ id: string; slug: string; title: string; reason: string }>>();
    if (maxBacklinks <= 0) return result;

    for (const tip of tips) {
      const candidates: Array<{ id: string; slug: string; title: string; score: number; reason: string }> = [];
      for (const other of tips) {
        if (other.id === tip.id) continue;
        let score = 0;
        const reasons: string[] = [];
        if (other.category === tip.category) { score += 4; reasons.push("category"); }
        const matMatch = (other.material_groups ?? []).filter((m) => (tip.material_groups ?? []).includes(m)).length;
        if (matMatch > 0) { score += 2 * matMatch; reasons.push(`material:${matMatch}`); }
        const opMatch = (other.operation_types ?? []).filter((o) => (tip.operation_types ?? []).includes(o)).length;
        if (opMatch > 0) { score += 2 * opMatch; reasons.push(`op:${opMatch}`); }
        const tagMatch = (other.tags ?? []).filter((t) => (tip.tags ?? []).includes(t)).length;
        if (tagMatch > 0) { score += tagMatch; reasons.push(`tag:${tagMatch}`); }
        if (score === 0) continue;
        candidates.push({
          id: other.id,
          slug: this.tipSlug(other),
          title: other.title ?? other.id,
          score: score + (other.confidence ?? 0) / 200, // tiebreaker
          reason: reasons.join("+"),
        });
      }
      candidates.sort((a, b) => b.score - a.score);
      result.set(tip.id, candidates.slice(0, maxBacklinks).map((c) => ({
        id: c.id, slug: c.slug, title: c.title, reason: c.reason,
      })));
    }
    return result;
  }

  // ---- private helpers ----

  private renderTip(tip: TribalTipLike, hash: string, backlinks: Array<{ id: string; slug: string; title: string; reason: string }>): string {
    const ts = new Date().toISOString();
    const tagsList = (tip.tags ?? []).map((t) => this.escapeYaml(t));
    const materialList = (tip.material_groups ?? []).map((m) => this.escapeYaml(m));
    const opList = (tip.operation_types ?? []).map((o) => this.escapeYaml(o));

    const fm = [
      "---",
      `schema_version: ${SCHEMA_VERSION}`,
      `kind: tribal_tip`,
      `id: ${this.escapeYaml(tip.id)}`,
      `title: ${this.escapeYaml(tip.title ?? tip.id)}`,
      `category: ${this.escapeYaml(tip.category)}`,
      ...(tip.subcategory ? [`subcategory: ${this.escapeYaml(tip.subcategory)}`] : []),
      ...(tip.domain ? [`domain: ${this.escapeYaml(tip.domain)}`] : []),
      ...(tip.knowledge_type ? [`knowledge_type: ${this.escapeYaml(tip.knowledge_type)}`] : []),
      `confidence: ${tip.confidence}`,
      `source: ${this.escapeYaml(tip.source ?? "unknown")}`,
      `created_at: ${this.escapeYaml(tip.created_at ?? ts)}`,
      `usage_count: ${tip.usage_count ?? 0}`,
      `tags: [${tagsList.map((t) => `"${t}"`).join(", ")}]`,
      `material_groups: [${materialList.map((m) => `"${m}"`).join(", ")}]`,
      `operation_types: [${opList.map((o) => `"${o}"`).join(", ")}]`,
      `content_hash: ${hash}`,
      `mirror_ts: ${ts}`,
      `mirror_engine: TribalVaultPopulatorEngine`,
      "---",
      "",
    ].join("\n");

    const lines: string[] = [
      fm,
      `# ${tip.title ?? tip.id}`,
      "",
      `**Category:** \`${tip.category}\`${tip.subcategory ? ` · **Subcategory:** \`${tip.subcategory}\`` : ""}${tip.domain ? ` · **Domain:** \`${tip.domain}\`` : ""}`,
      "",
      `**Confidence:** \`${tip.confidence}\` · **Source:** \`${this.escapeBackticks(tip.source ?? "unknown")}\``,
      "",
      "## Tip",
      "",
      tip.body ?? "(no body)",
      "",
    ];

    if ((tip.material_groups ?? []).length > 0 || (tip.operation_types ?? []).length > 0 || (tip.machine_ids ?? []).length > 0) {
      lines.push("## Applies to");
      lines.push("");
      if ((tip.material_groups ?? []).length > 0) lines.push(`- Material groups: ${(tip.material_groups ?? []).map((m) => `\`${m}\``).join(", ")}`);
      if ((tip.operation_types ?? []).length > 0) lines.push(`- Operation types: ${(tip.operation_types ?? []).map((o) => `\`${o}\``).join(", ")}`);
      if ((tip.machine_ids ?? []).length > 0) lines.push(`- Machine IDs: ${(tip.machine_ids ?? []).map((m) => `\`${m}\``).join(", ")}`);
      lines.push("");
    }

    if (backlinks.length > 0) {
      lines.push("## Related tips");
      lines.push("");
      for (const bl of backlinks) {
        lines.push(`- [[${bl.slug}|${bl.title}]] _(${bl.reason})_`);
      }
      lines.push("");
    }

    lines.push("## Tags");
    lines.push("");
    lines.push((tip.tags ?? []).map((t) => `#${this.tagToken(t)}`).join(" ") || "_(none)_");
    lines.push("");

    return lines.join("\n");
  }

  private atomicWrite(target: string, content: string): void {
    const dir = path.dirname(target);
    fs.mkdirSync(dir, { recursive: true });
    const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
    fs.writeFileSync(tmp, content, "utf-8");
    try { fs.renameSync(tmp, target); }
    catch {
      try { fs.unlinkSync(target); } catch { /* ignore */ }
      fs.renameSync(tmp, target);
    }
  }

  private escapeYaml(s: string): string {
    return String(s ?? "").replace(/[\r\n]/g, " ").replace(/"/g, "'");
  }

  private escapeBackticks(s: string): string {
    return String(s ?? "").replace(/`/g, "ʼ");
  }

  private tagToken(s: string): string {
    return String(s ?? "").toLowerCase().replace(/[^a-z0-9_-]/g, "-").replace(/^-+|-+$/g, "");
  }
}

export const tribalVaultPopulatorEngine = new TribalVaultPopulatorEngine();
