/**
 * TribalKnowledgeEngine — Manufacturing Intelligence Layer
 *
 * Captures, stores, and retrieves shop-floor tribal knowledge — the
 * undocumented tips, tricks, and lessons learned from experienced machinists.
 * Composes ApprenticeEngine + KnowledgeGraphEngine.
 *
 * Actions: knowledge_capture, knowledge_search, knowledge_suggest, knowledge_stats
 */

// ============================================================================
// TYPES
// ============================================================================

export interface KnowledgeTip {
  id: string;
  title: string;
  body: string;
  category: KnowledgeCategory;
  tags: string[];
  material_groups?: string[];
  operation_types?: string[];
  confidence: number;                // 0–100 (validated by experts)
  source: string;                    // "operator:John", "incident:2024-03-15", etc.
  created_at: string;
  usage_count: number;
}

// Core manufacturing categories (always tracked for coverage gaps)
/** C O R E_ C A T E G O R I E S constant.
 */
export const CORE_CATEGORIES = [
  "setup", "tooling", "speeds_feeds", "fixturing",
  "surface_finish", "thread", "safety", "maintenance",
  "material_handling", "quality", "troubleshooting",
] as const;

// Extended categories for non-machining domains (auto-created by /video-learn)
/** Knowledge Category type definition.
 */
export type KnowledgeCategory =
  | typeof CORE_CATEGORIES[number]
  | "programming" | "electronics" | "automation" | "metrology"
  | "design" | "materials_science" | "process_engineering"
  | "lean_manufacturing" | "additive" | "inspection"
  | (string & {});  // extensible — any string accepted for dynamic categories

/** Knowledge Search Input configuration/data structure.
 */
export interface KnowledgeSearchInput {
  query?: string;
  material_iso_group?: string;
  operation_type?: string;
  category?: KnowledgeCategory;
  min_confidence?: number;
  limit?: number;
}

/** Knowledge Suggestion configuration/data structure.
 */
export interface KnowledgeSuggestion {
  tips: KnowledgeTip[];
  relevance_scores: Record<string, number>;
  context_match: string;
}

/** Knowledge Stats configuration/data structure.
 */
export interface KnowledgeStats {
  total_tips: number;
  by_category: Record<string, number>;
  by_confidence: { high: number; medium: number; low: number };
  most_used: { id: string; title: string; usage_count: number }[];
  coverage_gaps: string[];
}

// ============================================================================
// KNOWLEDGE BASE (built-in tribal knowledge from manufacturing domain)
// ============================================================================

const KNOWLEDGE_BASE: KnowledgeTip[] = [
  { id: "tk-001", title: "Stainless 304 work hardening prevention", body: "Never dwell in the cut with 304/316 stainless. Use climb milling, positive rake angles, and maintain constant chip load. If you hear the pitch change, you've already work-hardened the surface — increase speed 15% and take a fresh cut below the hardened layer.", category: "speeds_feeds", tags: ["stainless", "work-hardening", "304", "316"], material_groups: ["M"], operation_types: ["pocket", "profile"], confidence: 95, source: "operator:senior_machinist", created_at: "2024-01-15", usage_count: 47 },
  { id: "tk-002", title: "Titanium chip color indicator", body: "Watch chip color when cutting Ti-6Al-4V: silver/light gold = good parameters. Dark blue/purple = too hot — reduce speed immediately. If chips are dark brown/black, you're burning the tool and workpiece. Through-spindle coolant is mandatory above 45 m/min.", category: "tooling", tags: ["titanium", "chip-color", "temperature"], material_groups: ["S"], operation_types: ["face", "pocket", "profile"], confidence: 90, source: "operator:aerospace_lead", created_at: "2024-02-10", usage_count: 33 },
  { id: "tk-003", title: "Vise jaw alignment check", body: "Every Monday morning: run a dial indicator across the fixed jaw. If TIR exceeds 0.0005\" (0.013mm), re-seat the jaw with a soft hammer and re-indicate. 90% of 'mystery' taper errors trace back to jaw alignment drift from weekend thermal cycling.", category: "fixturing", tags: ["vise", "alignment", "taper", "quality"], confidence: 88, source: "operator:quality_lead", created_at: "2024-03-01", usage_count: 28 },
  { id: "tk-004", title: "Deep pocket chip evacuation trick", body: "For pockets deeper than 2×diameter: program a retract-to-safe-Z every 3rd pass to let chips clear. Without this, you'll recut chips and get terrible surface finish plus accelerated flank wear. Takes 10% more cycle time but saves the tool and part.", category: "tooling", tags: ["pocket", "chip-evacuation", "deep-pocket"], operation_types: ["pocket"], confidence: 92, source: "operator:cam_programmer", created_at: "2024-01-20", usage_count: 41 },
  { id: "tk-005", title: "Thread milling vs tapping decision", body: "Use thread mills (not taps) for: blind holes in expensive parts, hole diameters >M12, exotic materials (Inconel, Ti), and any single-piece prototype. Taps are faster but if they break in the hole, the part is scrap. Thread mill breaks? Just replace and re-run the path.", category: "tooling", tags: ["threading", "thread-mill", "tap", "risk"], operation_types: ["thread"], confidence: 95, source: "operator:shop_foreman", created_at: "2024-04-05", usage_count: 38 },
  { id: "tk-006", title: "Aluminum face mill chatter fix", body: "If you get chatter face-milling aluminum, before reducing speed: try INCREASING speed to 15000+ RPM with high feed. The light cuts at high speed often eliminate resonance that occurs at mid-range RPMs. Also check that your face mill has unequal tooth spacing.", category: "speeds_feeds", tags: ["aluminum", "chatter", "face-mill", "high-speed"], material_groups: ["N"], operation_types: ["face"], confidence: 85, source: "operator:hsm_specialist", created_at: "2024-05-12", usage_count: 22 },
  { id: "tk-007", title: "Cast iron dry machining advantage", body: "Gray cast iron machines BETTER dry than with coolant. The graphite flakes act as a natural lubricant. Adding flood coolant creates a thermal shock that cracks carbide inserts. Use compressed air only for chip clearing.", category: "speeds_feeds", tags: ["cast-iron", "dry-cutting", "coolant"], material_groups: ["K"], operation_types: ["face", "pocket", "drill"], confidence: 92, source: "operator:tooling_engineer", created_at: "2024-02-28", usage_count: 35 },
  { id: "tk-008", title: "First-article inspection shortcut", body: "For first article: machine the first part 0.05mm oversize on all critical dimensions. Measure, calculate offsets, then cut the final dimensions. One extra part saves you from scrapping $500+ worth of material and 2 hours of machine time.", category: "quality", tags: ["first-article", "inspection", "offset"], confidence: 90, source: "operator:quality_machinist", created_at: "2024-06-01", usage_count: 44 },
  { id: "tk-009", title: "Tool length measurement best practice", body: "ALWAYS measure tool length with spindle warm (run at 80% RPM for 5 minutes first). Cold spindle can be 0.01-0.03mm shorter than running temperature. On tight tolerance work (±0.01mm), this matters.", category: "setup", tags: ["tool-length", "thermal-growth", "calibration"], confidence: 88, source: "operator:precision_lead", created_at: "2024-03-15", usage_count: 31 },
  { id: "tk-010", title: "Deburring sequence matters", body: "Always deburr BEFORE final inspection, AFTER all machining. But critical: deburr the datum surfaces FIRST so your measurement references are clean. A burr on a datum face can shift your entire measurement by 0.02mm+.", category: "quality", tags: ["deburring", "inspection", "datum"], confidence: 93, source: "operator:inspection_lead", created_at: "2024-04-20", usage_count: 26 },
  { id: "tk-011", title: "Workholding for thin walls", body: "For thin-wall parts (<2mm wall thickness): fill the pocket with low-melt alloy (Cerrobend, melts at 70°C) before finish machining the outside. The filler supports the wall against cutting forces. Melt it out in warm water after machining.", category: "fixturing", tags: ["thin-wall", "workholding", "cerrobend", "support"], confidence: 80, source: "operator:aerospace_machinist", created_at: "2024-07-01", usage_count: 15 },
  { id: "tk-012", title: "Safety: never reach into running machine", body: "NEVER reach into the work zone while spindle is rotating, even at low RPM. Use the chip hook tool to clear chips. Two machinists in this shop have lost fingertips from 'just brushing away chips.' The machine does not care about your deadline.", category: "safety", tags: ["safety", "chips", "injury-prevention"], confidence: 100, source: "safety:incident_review", created_at: "2024-01-01", usage_count: 89 },

  // --- Video-learned tips (source: Mastercam 2024 Tutorial — Titans of CNC) ---
  { id: "tk-vl-aVcqrFkLMbU-01", title: "Mastercam 2024 2D milling reference parameters", body: "From a Mastercam 2024 tutorial by Titans of CNC: facing with 3\" face mill at 3000 RPM / 40 IPM / 0.040\" DOC. Roughing with 1/2\" 3-flute end mill using dynamic mill (trochoidal) at 8000 RPM / 60 IPM / 25% stepover / chip load 0.0025 per tooth. Finishing contour at 5% stepover. Drilling with 1/4\" drill using peck cycle. Post-processed for Haas VF-2 with Fanuc-compatible control.", category: "speeds_feeds", tags: ["mastercam", "milling", "2d-toolpath", "haas", "fanuc", "trochoidal", "facing", "drilling"], material_groups: ["P"], operation_types: ["face", "pocket", "profile", "drill"], confidence: 70, source: "video:aVcqrFkLMbU", created_at: "2026-03-01", usage_count: 0 },
  { id: "tk-vl-aVcqrFkLMbU-02", title: "Mastercam 2024 tool selection for 2D milling job", body: "Recommended tool set from Mastercam tutorial: 3\" face mill for facing, 1/2\" 3-flute end mill for roughing and finishing contours, 1/4\" drill for bolt holes. The 3-flute end mill is preferred over 4-flute for aluminum and general-purpose steel milling due to better chip evacuation in slotting and pocketing.", category: "tooling", tags: ["mastercam", "tool-selection", "face-mill", "end-mill", "drill"], operation_types: ["face", "pocket", "profile", "drill"], confidence: 70, source: "video:aVcqrFkLMbU", created_at: "2026-03-01", usage_count: 0 },
  { id: "tk-vl-aVcqrFkLMbU-03", title: "Dynamic mill (trochoidal) in Mastercam for efficient roughing", body: "Mastercam's '2D Dynamic Mill' uses trochoidal milling for efficient material removal. Key advantage: maintains consistent chip load by varying the engagement angle rather than using conventional pocket passes. Set stepover to 25% of tool diameter for optimal balance of MRR and tool life. Particularly effective for hard materials and deep pockets.", category: "speeds_feeds", tags: ["mastercam", "dynamic-mill", "trochoidal", "roughing", "chip-load"], operation_types: ["pocket", "profile"], confidence: 70, source: "video:aVcqrFkLMbU", created_at: "2026-03-01", usage_count: 0 },
  { id: "tk-vl-aVcqrFkLMbU-04", title: "Trochoidal milling maintains consistent chip load", body: "Trochoidal (circular) toolpaths maintain constant tool engagement angle, preventing the load spikes that cause chatter and premature tool wear in conventional roughing. In Mastercam this is called 'Dynamic Mill.' Use it whenever roughing pockets or profiles in steels, stainless, and superalloys. Pair with 25% WOC and aggressive axial DOC for best MRR.", category: "speeds_feeds", tags: ["trochoidal", "chip-load", "engagement-angle", "roughing"], operation_types: ["pocket", "profile"], confidence: 70, source: "video:aVcqrFkLMbU", created_at: "2026-03-01", usage_count: 0 },
  { id: "tk-vl-aVcqrFkLMbU-05", title: "Contour finishing pass for wall quality", body: "After roughing with dynamic mill, add a separate contour finishing pass with reduced stepover (5% of tool diameter) for good wall surface finish. Use the same end mill as roughing but at finishing parameters. In Mastercam, select 'Contour' toolpath type and pick the finished profile geometry.", category: "surface_finish", tags: ["contour", "finishing", "surface-finish", "mastercam"], operation_types: ["profile"], confidence: 70, source: "video:aVcqrFkLMbU", created_at: "2026-03-01", usage_count: 0 },

  // --- Document-learned tips (source: CAD Drawing Standards & Best Practices handbook) ---
  { id: "TK-DL-cad-drawing-01", title: "GD&T datum scheme is mandatory for position tolerance", body: "Position tolerance (⊕) ALWAYS requires a datum reference frame. A common drawing error is specifying position tolerance without defining datums — the tolerance is meaningless without them. Define three mutually perpendicular datum planes (A, B, C) before applying position callouts. Per ASME Y14.5-2018, this is the most common GD&T callout and the most commonly misapplied.", category: "quality", tags: ["gdt", "datum", "position-tolerance", "asme-y14.5", "drawing"], confidence: 90, source: "document:cad_drawing_standards@section4", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-02", title: "Never dimension to hidden lines — use section views", body: "Dimensioning to hidden (dashed) lines is a top-10 drawing error across all CAD platforms. If a feature is internal or not visible in the current view, create a section view (full, half, offset, or broken-out) to expose it. This applies equally in SolidWorks, Fusion 360, CATIA, NX, and FreeCAD TechDraw. Section views eliminate ambiguity and reduce interpretation errors on the shop floor.", category: "quality", tags: ["drawing", "section-view", "dimensioning", "hidden-lines", "best-practice"], confidence: 92, source: "document:cad_drawing_standards@section6", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-03", title: "Dimension once — never repeat across views", body: "Every dimension should appear exactly once on the drawing. Repeating a dimension in multiple views creates conflicting tolerance interpretations and confuses the machinist. Place dimensions in the view that best shows the feature's true shape, preferably between views. Reference dimensions (parenthesized) are the only exception.", category: "quality", tags: ["drawing", "dimensioning", "over-dimensioning", "tolerance-stack"], confidence: 93, source: "document:cad_drawing_standards@section3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-04", title: "Use baseline dimensioning for critical tolerance features", body: "For features where cumulative tolerance stack-up is unacceptable, use baseline (datum) dimensioning — all dimensions originate from a single reference. Chain dimensioning accumulates tolerances: N dimensions at ±0.1mm gives ±(N×0.1)mm at the end. Baseline dimensioning keeps each feature at ±0.1mm from the datum regardless of chain length.", category: "quality", tags: ["baseline-dimensioning", "tolerance-stack", "datum", "chain-dimensioning"], confidence: 90, source: "document:cad_drawing_standards@section3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-05", title: "Surface finish must be specified on all mating surfaces", body: "Every surface that mates with another part MUST have a surface finish callout (Ra value per ISO 1302 or ASME Y14.36). Common values: Ra 1.6-3.2 μm for standard machining, Ra 0.4-0.8 μm for bearing seats and sealing surfaces, Ra 0.05-0.2 μm for lapped/polished surfaces. Missing finish specs on fits is a top-10 drawing error that causes assembly failures.", category: "quality", tags: ["surface-finish", "Ra", "mating-surface", "iso-1302", "drawing"], confidence: 88, source: "document:cad_drawing_standards@section3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-06", title: "Position tolerance calculation for hole patterns", body: "For fastener hole patterns: Floating fastener formula: T_hole = H_MMC - F_MMC (where H=hole diameter at MMC, F=fastener diameter at MMC). Fixed fastener formula: T_hole = (H_MMC - F_MMC) / 2. Always specify position tolerance at MMC (Ⓜ) for holes — this allows bonus tolerance as the hole gets larger, maximizing manufacturing yield.", category: "quality", tags: ["position-tolerance", "hole-pattern", "mmc", "fastener", "gdt", "formula"], confidence: 85, source: "document:cad_drawing_standards@section4", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-07", title: "SolidWorks: use Model Items to auto-import dimensions", body: "In SolidWorks drawings, use Insert → Model Items to automatically pull dimensions from the 3D model into drawing views. This is faster and more accurate than re-dimensioning manually. After auto-import, clean up placement (move dimensions between views, adjust spacing). Set drafting standard under Tools → Options → Document Properties → Drafting Standard (ANSI or ISO).", category: "setup", tags: ["solidworks", "drawing", "model-items", "automation", "cad"], confidence: 80, source: "document:cad_drawing_standards@section5", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-08", title: "CATIA: use Generative Drafting over Interactive Drafting", body: "In CATIA V5/V6, always use Generative Drafting (automatic from 3D model) instead of Interactive Drafting (manual). Generative Drafting maintains full associativity — model changes auto-update the drawing. Use dress-up features (centerlines, threads, axis lines) BEFORE dimensioning. CATIA has the most comprehensive GD&T symbol library of all major CAD systems.", category: "setup", tags: ["catia", "drawing", "generative-drafting", "associativity", "cad"], confidence: 80, source: "document:cad_drawing_standards@section5", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-09", title: "Siemens NX PMI for Model-Based Definition", body: "Siemens NX leads the industry in PMI (Product Manufacturing Information) — dimensions, tolerances, and annotations stored directly on the 3D model. This enables Model-Based Definition (MBD) per ASME Y14.41-2019, eliminating 2D drawings entirely. PMI feeds automated CMM programming for inspection. Export as STEP AP242 for interoperability with other CAD systems.", category: "setup", tags: ["nx", "pmi", "mbd", "asme-y14.41", "step-ap242", "inspection", "cad"], confidence: 82, source: "document:cad_drawing_standards@section7", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-10", title: "Always include projection symbol and general tolerance block", body: "Two items that MUST appear on every technical drawing: (1) Projection symbol — third-angle (ASME/North America) or first-angle (ISO/Europe) — to prevent view misinterpretation. (2) General tolerance block (e.g., ISO 2768-mK) covering all undimensioned features. Without these, the shop floor has to guess orientation and tolerance class, leading to scrap.", category: "quality", tags: ["projection", "tolerance-block", "iso-2768", "title-block", "drawing"], confidence: 91, source: "document:cad_drawing_standards@section6", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-11", title: "Edge break/deburr note is mandatory on machined parts", body: "Every machined part drawing must include an edge break callout (e.g., 'BREAK ALL SHARP EDGES 0.2-0.5mm' or 'DEBURR ALL EDGES'). Sharp edges are dangerous to handlers, cause stress concentrations, and interfere with coatings/plating. This is one of the most commonly omitted notes and a frequent cause of part rejection at incoming inspection.", category: "safety", tags: ["deburr", "edge-break", "drawing", "safety", "inspection"], confidence: 90, source: "document:cad_drawing_standards@section6", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-12", title: "Hole callouts must be complete: diameter + depth + type", body: "Every hole on a drawing needs a complete callout: diameter, depth (THRU or blind depth), and type (plain, counterbore ⌴, countersink ∠, tapped). Tapped holes additionally need thread spec (e.g., M10x1.5 - 6H x 20 DEEP). Incomplete hole callouts are a leading cause of manufacturing questions and RFIs that delay production.", category: "quality", tags: ["hole-callout", "counterbore", "countersink", "tapped-hole", "drawing"], confidence: 88, source: "document:cad_drawing_standards@section3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-13", title: "Form tolerances (flatness, cylindricity) need no datum", body: "The four form tolerances — straightness (⏤), flatness (⏥), circularity (○), and cylindricity (⌭) — are the ONLY GD&T controls that do NOT require a datum reference. They control individual feature shape. All other GD&T categories (orientation, location, profile, runout) require at least one datum. Incorrectly adding datums to form tolerances is a common error.", category: "quality", tags: ["gdt", "form-tolerance", "flatness", "cylindricity", "datum", "drawing"], confidence: 88, source: "document:cad_drawing_standards@section4", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-14", title: "ISO 2768 tolerance classes for general dimensions", body: "ISO 2768 defines four general tolerance classes for undimensioned features: f (fine: ±0.05 to ±0.5mm), m (medium: ±0.1 to ±1.0mm), c (coarse: ±0.2 to ±2.0mm), v (very coarse: ±0.5 to ±4.0mm). Always state the class in the title block (e.g., 'ISO 2768-mK'). The second letter (K) adds geometrical tolerance per Part 2. Medium (m) is the default for most machined parts.", category: "quality", tags: ["iso-2768", "general-tolerance", "tolerance-class", "drawing", "title-block"], confidence: 85, source: "document:cad_drawing_standards@section3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-cad-drawing-15", title: "FreeCAD/CadQuery: export STEP then use TechDraw for 2D", body: "CadQuery generates 3D models programmatically but has no built-in 2D drawing capability. For technical drawings: export to STEP, then use FreeCAD's TechDraw workbench. TechDraw supports projection groups, section views, detail views, dimensions, and surface finish symbols. For quick 2D cross-sections from CadQuery, use cq.exporters.export(result.section(), 'cross_section.dxf').", category: "setup", tags: ["freecad", "cadquery", "techdraw", "step", "dxf", "cad", "drawing"], confidence: 78, source: "document:cad_drawing_standards@section5", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-01", title: "Wire EDM overburn decreases per skim pass", body: "Overburn (the extra material removed beyond the wire path) decreases with each skim pass. Typical progression for brass 0.25mm wire: first cut 0.035mm, skim 1 = 0.020mm, skim 2 = 0.010mm, skim 3 = 0.000mm (zero overburn). Each pass uses lower power and slower speed. Program total offset = wire_radius + overburn for each pass. Source: Mastercam Wire Tutorial Ch.1-2.", category: "machining", tags: ["wire-edm", "overburn", "skim-cut", "offset", "wire"], confidence: 85, source: "document:mastercam_wire_tutorial@ch1-2", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-02", title: "Tab cutting keeps wire EDM parts from dropping", body: "When wire-cutting a closed contour, the slug drops when the cut completes — potentially damaging the part or wire. Use tab cutting: leave 1-2mm tabs (uncut bridges) to hold the slug, then snap or grind them off. Program a 'glue stop' (M01 optional stop) at tab positions so operator can apply adhesive for heavy slugs. Tab width depends on material thickness and weight. Source: Mastercam Wire Tutorial Ch.2.", category: "machining", tags: ["wire-edm", "tab", "slug", "glue-stop", "workholding"], confidence: 88, source: "document:mastercam_wire_tutorial@ch2", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-03", title: "Wire EDM lead-in/lead-out geometry for burr-free cuts", body: "Lead-in and lead-out geometry prevents witness marks at the contour entry/exit point. Best practice: use a line+arc lead (straight approach followed by tangent arc onto contour). Arc radius 0.125-0.5mm, sweep angle 60-90 degrees. Add 0.02mm overlap past the start point to eliminate the entry burr. For skim passes, use shorter leads than the rough cut. Source: Mastercam Wire Tutorial Ch.1.", category: "machining", tags: ["wire-edm", "lead-in", "lead-out", "burr", "contour", "wire"], confidence: 87, source: "document:mastercam_wire_tutorial@ch1", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-04", title: "No-core wire EDM toolpaths for complete material removal", body: "Standard wire EDM cuts a closed contour, leaving a slug (core). No-core toolpaths remove material completely without leaving a slug — useful when the slug would be too heavy to handle or when the cavity shape prevents slug removal. Mastercam's 'Parallel Spiral' no-core pattern spirals inward from the boundary. Slower than contour cutting but eliminates slug handling. Source: Mastercam Wire Tutorial Ch.3.", category: "machining", tags: ["wire-edm", "no-core", "parallel-spiral", "slug", "cavity"], confidence: 82, source: "document:mastercam_wire_tutorial@ch3", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-05", title: "Reverse wire cutting eliminates re-threading", body: "When a wire EDM contour requires multiple passes (rough + skims), reverse cutting runs alternating passes in opposite directions. This eliminates the need to re-thread the wire at the start point between passes — the wire simply reverses direction. Reduces cycle time by 1-3 minutes per pass (threading time). Not suitable for taper cuts where wire angle must be consistent. Source: Mastercam Wire Tutorial Ch.2.", category: "machining", tags: ["wire-edm", "reverse-cut", "threading", "cycle-time", "skim-cut"], confidence: 83, source: "document:mastercam_wire_tutorial@ch2", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-wire-06", title: "Thread point placement near contour start", body: "The thread point (where the wire is initially threaded through a pre-drilled hole) should be placed near the contour start point but NOT on the contour itself. Use 'break closest entity' to split the contour chain at the nearest point to the thread hole. Thread point offset from contour: 0.5-2mm. For multiple contours sharing a thread hole, chain them in order of proximity. Source: Mastercam Wire Tutorial Ch.1.", category: "machining", tags: ["wire-edm", "thread-point", "start-hole", "chaining", "setup"], confidence: 80, source: "document:mastercam_wire_tutorial@ch1", created_at: "2026-03-01", usage_count: 0 },
  { id: "TK-DL-mc-solids-01", title: "Draft angle and fillet guidelines for machined/molded parts", body: "Apply draft angles of 5-10 degrees on vertical walls for moldability and ease of machining. Always apply fillets AFTER boolean cut operations (cuts remove fillet geometry if applied first). Shell operations should be the LAST feature before fillets — shelling after filleting causes unpredictable wall thickness. For CNC: fillets > tool radius to avoid sharp internal corners. Source: Mastercam Solids Tutorial.", category: "design", tags: ["draft-angle", "fillet", "shell", "modeling", "cad", "mold-design"], confidence: 82, source: "document:mastercam_solids_tutorial", created_at: "2026-03-01", usage_count: 0 },

  // --- Document-learned tips (source: hyperMILL Manual Parts 1-4) ---
  { id: "TK-DL-hm-001", title: "Never change measurement system mid-project in hyperMILL", body: "Do not change the measurement system (Metric/Inch) during CAM programming. Existing definition values will NOT be converted. Copying jobs between hyperMILL documents with different measurement systems is not allowed. Set the correct unit system at project creation and lock it.", category: "setup", tags: ["hypermill", "units", "metric", "inch", "cam-setup"], confidence: 95, source: "document:hypermill-manual-en-1@p35", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-002", title: "Always enable Automatic Geometry Check in hyperMILL", body: "The Automatic Geometry Check function (Setup > Settings > Calculation) should ALWAYS be enabled. When geometry is modified, it deletes outdated cache data and reconverts before calculation. Disabling this causes faulty calculations from stale cached geometry. It is active by default for good reason.", category: "setup", tags: ["hypermill", "geometry-check", "cache", "calculation", "cam-setup"], confidence: 95, source: "document:hypermill-manual-en-1@p36", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-003", title: "Clearance plane must be above ALL geometry including fixtures", body: "The clearance plane must be situated above ALL workpiece and fixture boundaries in Z direction. Traversing movements at the clearance plane are NOT checked for collisions. A clearance plane set too low will result in rapid-travel crashes into the workpiece or fixtures without any warning from the system.", category: "safety", tags: ["hypermill", "clearance-plane", "collision", "rapid", "safety"], confidence: 95, source: "document:hypermill-manual-en-4@p759", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-004", title: "Use Optimised Roughing for HSC-compatible 3D roughing", body: "hyperMILL Optimised Roughing generates highly efficient toolpaths that reduce direction changes for high-speed cutting. It auto-detects rectangular and circular pocket shapes, uses stock model geometry for minimal air cutting, and generates resulting stock for subsequent rest machining. Preferred over Arbitrary Stock Roughing for most 3D roughing operations.", category: "speeds_feeds", tags: ["hypermill", "roughing", "hsc", "3d", "toolpath-optimization"], confidence: 90, source: "document:hypermill-manual-en-4@p773", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-005", title: "Z Level Finishing adapts stepdown to surface steepness", body: "hyperMILL Z Level Finishing automatically adapts vertical stepdown values to the surface flow. For steep surfaces, this avoids unnecessary fine infeed increments and guarantees optimal line distance. Use Z Level for surfaces with wall angles above 45 degrees. For mixed steep/flat areas, use Complete Finishing which combines Z-level with pocket-shaped flat area machining.", category: "surface_finish", tags: ["hypermill", "finishing", "z-level", "steep", "scallop-height"], confidence: 88, source: "document:hypermill-manual-en-4@p889", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-006", title: "Equidistant Finishing for best HSM surface quality", body: "hyperMILL Equidistant Finishing provides constant infeed on the surface, making it particularly suitable for high-speed milling. It machines equidistantly within a closed guide curve or flowing between two guide curves. The constant surface step ensures uniform scallop height across freeform surfaces.", category: "surface_finish", tags: ["hypermill", "finishing", "equidistant", "hsm", "surface-quality", "scallop"], confidence: 88, source: "document:hypermill-manual-en-4@p915", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-007", title: "Boundary curve minimum distance rule", body: "When defining machining boundaries in hyperMILL 3D cycles, the minimum distance between the boundary curve and the actual machining area should be the cutter radius plus the machining allowance. Boundaries that are too close to the machining area cause tool overtravel and potential collision.", category: "setup", tags: ["hypermill", "boundary", "machining-area", "cutter-radius", "allowance"], confidence: 90, source: "document:hypermill-manual-en-4@p761", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-008", title: "Avoid overlapping machining areas to prevent tool marks", body: "In hyperMILL 3D machining, machining areas should not overlap and should not be too close together. Overlapping boundaries cause steps and tool marks at the boundary intersection. If areas must be adjacent, combine them into one machining area. Independent areas with the same direction, strategy, tool, and frame orientation can be machined together in one cycle.", category: "surface_finish", tags: ["hypermill", "boundary", "overlap", "tool-marks", "3d-machining"], confidence: 88, source: "document:hypermill-manual-en-4@p761", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-009", title: "Negative allowance constraints prevent nose-diving", body: "When using negative stock allowances in hyperMILL: (1) sum of negative allowance + tool corner radius must NOT be negative, (2) flat end mills are NOT allowed with negative allowances, (3) surface gaps must not exceed 2x(tool radius + negative allowance). Violating these constraints causes tool nose-diving into the workpiece.", category: "safety", tags: ["hypermill", "allowance", "negative", "nose-diving", "tool-safety"], confidence: 92, source: "document:hypermill-manual-en-4@p757", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-010", title: "Only round inserts for turning High Performance Mode", body: "In hyperMILL millTURN module, High Performance Mode (hyperMILL MAXX Machining) for turning jobs ONLY permits tools with round inserts. Diamond, square, trigon, and other insert shapes are not allowed in HPM. Verify insert type before enabling this mode.", category: "tooling", tags: ["hypermill", "turning", "hpm", "round-insert", "millturn"], confidence: 92, source: "document:hypermill-manual-en-2@p303", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-011", title: "Ascending/descending infeed reduces insert wear in turning", body: "In hyperMILL turning roughing, the Ascending and Descending infeed options vary the cutting depth between passes. This changes the intervention point of the insert into the material each pass, distributing wear across the cutting edge. Particularly important when using ceramic inserts which are sensitive to repeated impact at the same point.", category: "tooling", tags: ["hypermill", "turning", "infeed", "tool-wear", "ceramic", "insert-life"], confidence: 85, source: "document:hypermill-manual-en-2@p307", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-012", title: "Chipbreak Z controls chip length in turning", body: "hyperMILL Chipbreak Z parameter controls chip break and removal during turning. It specifies the Z-direction infeed length after which the tool stops (dwell time or rotations). Use shorter chipbreak values for harder materials. Enable Use Sections for long workpieces to improve stability by dividing the cut into segments.", category: "speeds_feeds", tags: ["hypermill", "turning", "chipbreak", "chip-control", "stability"], confidence: 85, source: "document:hypermill-manual-en-2@p308", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-013", title: "Update rest material cycle when reference tool changes", body: "In hyperMILL 2D machining, if the tool diameter is changed in the milling cycle that generates rest material, the corresponding rest material cycle MUST also be updated. Failure to update creates a mismatch where the rest machining cycle assumes the previous tool size, risking tool plunge into material at full depth.", category: "safety", tags: ["hypermill", "rest-machining", "tool-change", "plunge-risk", "2d-milling"], confidence: 90, source: "document:hypermill-manual-en-3@p638", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-014", title: "Pocket milling tool must not match geometry exactly", body: "In hyperMILL 2D Pocket Milling, ensure the tool is only in contact with the model geometry on one side. The tool diameter must NOT correspond exactly with the model geometry to be machined. An exact match causes full-width engagement on both sides simultaneously, leading to excessive cutting forces and potential tool breakage.", category: "tooling", tags: ["hypermill", "pocket", "tool-diameter", "engagement", "2d-milling"], confidence: 88, source: "document:hypermill-manual-en-3@p639", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-hm-015", title: "No double or superimposed surfaces in 3D milling areas", body: "hyperMILL 3D milling surfaces must not contain any double or superimposed surfaces. Also, boundary areas and edges of milling surfaces must not contain surfaces the tool cannot access (like narrow slots). These conditions cause unpredictable toolpath behavior including nose-diving. Clean up CAD geometry before CAM programming.", category: "setup", tags: ["hypermill", "surface-cleanup", "cad-prep", "3d-milling", "nose-diving"], confidence: 88, source: "document:hypermill-manual-en-4@p761", created_at: "2026-03-03", usage_count: 0 },

  // --- MIT 2.830J Control of Manufacturing Processes (Lectures 3, 9, 13-14, 18, 20-21) ---
  { id: "TK-DL-2830j-001", title: "EWMA chart beats Shewhart for small shifts (<1.5σ)", body: "For detecting small sustained mean shifts (<1.5σ), use EWMA or CUSUM charts instead of standard Shewhart X-bar charts. EWMA with λ=0.1-0.2 is optimal for shifts around 0.5-1σ. Shewhart charts are only efficient for detecting large shifts (>2σ). Source: MIT 2.830J Lecture 9 (Hardt).", category: "quality", tags: ["spc", "ewma", "cusum", "shewhart", "mean-shift", "control-chart"], confidence: 92, source: "document:mit2830j@lecture9", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-002", title: "EWMA λ selection: smaller λ for smaller shifts", body: "EWMA smoothing parameter λ (called r in some texts): use λ=0.05-0.1 for detecting shifts <0.5σ, λ=0.1-0.25 for 0.5-1.5σ shifts, λ=0.4+ for large shifts (but at that point Shewhart may be better). Lower λ gives more memory of past observations. Trade-off: smaller λ = slower false alarm rate but longer detection delay for large shifts.", category: "quality", tags: ["spc", "ewma", "lambda", "tuning", "shift-detection"], confidence: 90, source: "document:mit2830j@lecture9", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-003", title: "Check autocorrelation BEFORE applying SPC charts", body: "Standard SPC charts (Shewhart, EWMA, CUSUM) assume observations are independent. If your process data is autocorrelated (common in CNC with thermal drift), these charts produce excessive false alarms. ALWAYS check lag-1 autocorrelation first. If significant (>0.3), either use EWMA on residuals or apply cycle-to-cycle control first.", category: "quality", tags: ["spc", "autocorrelation", "independence", "false-alarm", "thermal-drift"], confidence: 95, source: "document:mit2830j@lecture9", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-004", title: "Cycle-to-cycle (CtC) control: check stability with K < 1", body: "In cycle-to-cycle manufacturing control, the loop gain K = Kc × Kp must satisfy |K| < 1 for stability. K_p is process gain (often ≈1), K_c is controller gain. Start with Kc = 0.3-0.5 and tune up. Going above K=1 causes oscillation that INCREASES variance instead of reducing it. The optimal gain minimizes σ²_output = σ²_d × (1-K)² / (1-(1-K)²).", category: "quality", tags: ["ctc-control", "feedback", "stability", "process-gain", "controller-tuning"], confidence: 93, source: "document:mit2830j@lecture20", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-005", title: "Use I-control (not P-control) when mean shifts persist", body: "P-control (proportional) leaves steady-state error when there's a sustained mean shift (like tool wear). I-control (integral) accumulates the error and drives it to zero. Use I-control for: gradual tool wear compensation, thermal drift correction, systematic material variation. Use P-control for: random batch-to-batch variation, low-autocorrelation disturbances.", category: "quality", tags: ["ctc-control", "integral-control", "proportional-control", "tool-wear", "drift"], confidence: 90, source: "document:mit2830j@lecture20", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-006", title: "DOE: use fractional factorial to save runs", body: "Full factorial 2^k experiments get expensive fast (2^6 = 64 runs). Use fractional factorial 2^{k-p} when k≥4 factors. A 2^{6-2} design needs only 16 runs instead of 64, at the cost of aliased interactions. Rule: main effects are almost always more important than interactions. Screen with fractional factorial first, then run full factorial on the significant factors only.", category: "quality", tags: ["doe", "factorial", "fractional", "screening", "efficiency"], confidence: 90, source: "document:mit2830j@lecture13-14", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-007", title: "Resolution III designs alias main effects with 2-factor interactions", body: "In fractional factorial designs, Resolution III (like 2^{3-1}) aliases each main effect with a 2-factor interaction. This means if A is aliased with BC, you can't tell if the effect is from A alone or from the BC interaction. Resolution IV aliases 2-factor interactions with each other (main effects are clear). Always use Resolution IV or higher for important screening experiments.", category: "quality", tags: ["doe", "resolution", "aliasing", "fractional-factorial", "screening"], confidence: 88, source: "document:mit2830j@lecture14", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-008", title: "Add center points to 2-level factorials to detect curvature", body: "A 2-level factorial design can only fit linear models. Add 3-5 center points (all factors at midpoint) to test for curvature without increasing the number of factorial runs. If the center point average differs significantly from the factorial average, there is curvature and you need a response surface design (CCD or Box-Behnken).", category: "quality", tags: ["doe", "center-points", "curvature", "response-surface", "ccd"], confidence: 88, source: "document:mit2830j@lecture14", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-009", title: "Cpk vs Cp: always use Cpk for real processes", body: "Cp measures potential capability assuming process is centered. Cpk measures ACTUAL capability including mean offset. Cpk = min((USL-μ)/(3σ), (μ-LSL)/(3σ)). A process with Cp=2.0 but off-center can have Cpk=0.5 and produce 10% scrap. Always report Cpk, not just Cp. Target Cpk ≥ 1.33 (4σ) for production, Cpk ≥ 1.67 (5σ) for safety-critical.", category: "quality", tags: ["capability", "cpk", "cp", "tolerance", "centering", "scrap-rate"], confidence: 95, source: "document:mit2830j@lecture3", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-010", title: "Taguchi quality loss: variation costs money even within spec", body: "Taguchi's quality loss function L = k(y-T)² means ANY deviation from target costs money — not just out-of-spec parts. Expected loss E[L] = k(σ² + (μ-T)²). This means: (1) reducing variance is always valuable even if Cpk looks fine, (2) centering the process on target matters as much as reducing spread, (3) a process at ±0.5σ from target costs 25% of the loss at ±1σ.", category: "quality", tags: ["taguchi", "quality-loss", "variation", "cost", "target-centering"], confidence: 90, source: "document:mit2830j@lecture3", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-011", title: "Robust design: minimize sensitivity to noise factors", body: "Taguchi robust design (MIT 2.830J Lecture 18): instead of controlling all variation sources, find control factor settings that make the output INSENSITIVE to noise. Use crossed array: inner array (control factors) × outer array (noise factors). Pick settings where the signal-to-noise ratio (SNR) is maximized. This often costs less than tightening tolerances on inputs.", category: "quality", tags: ["taguchi", "robust-design", "noise-factors", "snr", "tolerance-design"], confidence: 88, source: "document:mit2830j@lecture18", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-012", title: "Process variation has systematic + random components", body: "Total process variation σ²_total = σ²_systematic + σ²_random. Systematic sources (tool wear, thermal drift, fixture shift) create patterns and autocorrelation — these can be controlled with CtC feedback. Random sources (material microstructure, vibration, coolant turbulence) are independent — these can only be reduced with SPC monitoring and root cause elimination. Identify which dominates before choosing a control strategy.", category: "quality", tags: ["variation", "systematic", "random", "control-strategy", "root-cause"], confidence: 92, source: "document:mit2830j@lecture3", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-013", title: "CUSUM is optimal for detecting sustained shifts of known size", body: "If you know the approximate shift size δ you want to detect, CUSUM with k=δ/2 is the optimal detector (lowest ARL₁). Standard params: k=0.5σ (half-sigma slack), h=5σ (decision interval) gives ARL₀≈465 and detects 1σ shift in ~10 samples. CUSUM accumulates evidence over time — it will ALWAYS eventually detect a sustained shift, no matter how small.", category: "quality", tags: ["cusum", "shift-detection", "arl", "optimal-detector", "sustained-shift"], confidence: 90, source: "document:mit2830j@lecture9", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-014", title: "Spatial process variation requires spatial models, not just SPC", body: "For processes with spatial variation (injection molding cavity-to-cavity, wafer uniformity, multi-cavity dies), standard SPC on individual measurements misses the pattern. Use spatial models: (1) decompose into radial + angular components, (2) fit polynomial surfaces, (3) track spatial signature changes cycle-to-cycle. A process can be 'in control' on average but have worsening spatial uniformity.", category: "quality", tags: ["spatial-variation", "injection-molding", "uniformity", "wafer", "multi-cavity"], confidence: 85, source: "document:mit2830j@lecture21", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-2830j-015", title: "Manufacturing processes taxonomy: 4 classes × energy domain", body: "All manufacturing processes fall into 4 classes: Material Removal (machining, EDM, laser), Material Addition (welding, 3D printing, CVD), Forming/Deformation (forging, stamping, rolling), and Phase Change (casting, injection molding, sintering). Each can be further classified by energy domain (mechanical, thermal, chemical, electrical). This taxonomy helps identify analogous control strategies across different process types.", category: "setup", tags: ["process-taxonomy", "manufacturing", "classification", "removal", "addition", "forming"], confidence: 85, source: "document:mit2830j@lecture3", created_at: "2026-03-03", usage_count: 0 },

  // --- CNC Batch 1: Design & Machining Guides (CNCCookbook, Engineering Guide, SINUMERIK) ---
  { id: "TK-DL-cnc-001", title: "Minimum wall thickness: 0.8mm metal, 1.5mm plastic", body: "CNC machining minimum wall thickness limits: metal parts 0.8mm recommended (0.5mm feasible but risky), plastic parts 1.5mm recommended (1.0mm feasible). Thinner walls vibrate during cutting causing poor surface finish and tolerance loss. Tall thin walls (aspect ratio >4) are especially problematic.", category: "design", tags: ["dfm", "wall-thickness", "design-rules", "vibration"], confidence: 90, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-002", title: "Cavity depth limit: 4× width recommended, 10× tool diameter max", body: "Pocket/cavity depth should not exceed 4× the cavity width (recommended) or 10× the tool diameter (absolute max, 250mm). Deeper cavities require longer tools with larger diameters, which increases internal fillet radius. Internal edge fillets should be ≥1/3 × cavity depth.", category: "design", tags: ["dfm", "cavity", "pocket", "depth", "fillet"], confidence: 90, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-003", title: "Thread sizing: M6+ recommended, max engagement 3× nominal", body: "For CNC machined threads, M6 and above are recommended (M2 is feasible minimum). Thread engagement length beyond 3× nominal diameter provides diminishing returns on holding strength. For blind holes, thread milling is preferred over tapping to avoid tap breakage.", category: "design", tags: ["dfm", "threads", "tapping", "thread-milling", "engagement"], confidence: 88, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-004", title: "Standard CNC tolerance: ±0.125mm; tight: ±0.050mm; feasible: ±0.025mm", body: "Standard CNC machining tolerance is ±0.125mm (±0.005\"). Tighter tolerances increase cost significantly: ±0.050mm needs careful setup, ±0.025mm is the feasible limit for standard CNC (grinding/lapping needed below this). Each halving of tolerance roughly doubles machining cost.", category: "design", tags: ["dfm", "tolerance", "precision", "cost", "grinding"], confidence: 92, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-005", title: "HSS surface speed table: Al 250, Brass 200, Mild Steel 110, Stainless 30 SFM", body: "HSS baseline surface speeds (SFM): Aluminum 6061=250, Brass=200, Bronze=100, Cast Iron=80, Mild Steel (1018)=110, Alloy Steel (4140)=80, Tool Steel (D2)=60, Stainless 303=45, Stainless 316=30, Titanium 6Al-4V=50. Carbide tooling runs 3-4× these values. Always start at 80% and increase.", category: "speeds", tags: ["sfm", "hss", "surface-speed", "material", "baseline"], confidence: 85, source: "document:cnc-feeds-speeds-guide@ch3", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-006", title: "Never let chip load drop below 0.004\" — rubbing destroys tools", body: "Minimum chip load threshold for carbide end mills is approximately 0.004\" (0.1mm) per tooth. Below this, the tool rubs instead of cutting, generating excessive heat and accelerating wear. This is the #1 cause of premature tool failure in hobby/small CNC shops. When in doubt, increase feed rate rather than decrease it.", category: "speeds", tags: ["chip-load", "rubbing", "minimum-feed", "tool-wear", "carbide"], confidence: 90, source: "document:cnc-feeds-speeds-guide@ch5", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-007", title: "Flute count by material: Al=2-3, Steel=4, Cast Iron=5-6", body: "Optimal flute count depends on material chip characteristics. Aluminum and soft metals: 2-3 flutes (large gullets for big chips). Steel and alloys: 4 flutes (balance between chip space and rigidity). Cast iron and hardened steel: 5-6+ flutes (small chips, need rigidity). More flutes = higher feed rate at same chip load but less chip clearance.", category: "tooling", tags: ["flute-count", "end-mill", "aluminum", "steel", "chip-clearance"], confidence: 85, source: "document:cnc-feeds-speeds-guide@ch4", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-008", title: "45° face mill gives ~40% more MRR than 90° with balanced forces", body: "A 45° entering angle face mill produces ~40% higher material removal rate than a 90° equivalent due to chip thinning effect. The radial and axial forces are more balanced. However, 45° mills exert ~2× the axial force — avoid on thin-walled parts. Use 90° for thin walls (half the axial force), button cutters for interrupted cuts in superalloys.", category: "tooling", tags: ["face-mill", "entering-angle", "mrr", "chip-thinning", "thin-wall"], confidence: 88, source: "document:cnc-face-mill-guide@selection", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-009", title: "Thread mill diameter must be < 70% of thread diameter", body: "When thread milling, the cutter diameter must be less than 70% of the thread's nominal diameter to ensure proper helical interpolation clearance. Synchronous (climb) milling is preferred for thread milling — produces better surface finish and less burr. Dry machining is preferred except for stainless, aluminum, and cast iron which benefit from coolant.", category: "tooling", tags: ["thread-milling", "diameter-ratio", "synchronous", "dry-machining"], confidence: 88, source: "document:cnc-thread-mill-guide@technique", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-010", title: "Deep hole thresholds: <5D standard, 5-7D peck, 7-10D parabolic, >20D gun drill", body: "Deep hole drilling technique by L/D ratio: <5D = standard drill (no special cycle), 5-7D = peck drilling required, 7-10D = parabolic flute + peck (reduce feed 10%), 10-20D = custom progressive peck cycle (reduce feed 20%), >20D = gun drill or BTA system (limit ~400D). Through-spindle coolant strongly recommended above 5D.", category: "drilling", tags: ["deep-hole", "peck", "gun-drill", "ld-ratio", "parabolic-flute"], confidence: 90, source: "document:cnc-deep-hole-guide@thresholds", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-011", title: "CNC machine cost comparison: 3-axis $75/hr baseline", body: "Typical CNC machine shop rates (2024 USD): 3-axis mill $75/hr (baseline), CNC lathe $65/hr (-15%), indexed 5-axis $120/hr (+60%), continuous 5-axis $150/hr (+100%), mill-turn $95/hr (+25%). When designing parts, consider whether features truly require 5-axis or can be achieved with 3-axis + fixture rotation.", category: "cost", tags: ["machine-cost", "hourly-rate", "3-axis", "5-axis", "mill-turn"], confidence: 80, source: "document:cnc-complete-guide@cost", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-012", title: "Undercut width range: 3-40mm, depth ≤ 2× width", body: "CNC undercuts (T-slots, O-rings, snap rings) have practical limits: minimum width 3mm (1/8\"), maximum width 40mm, and depth should not exceed 2× the width. Clearance diameter must be at least 4× the undercut depth. Standard inch fraction sizes (1/8\", 3/16\", 1/4\") are preferred for tool availability.", category: "design", tags: ["dfm", "undercut", "t-slot", "o-ring", "dimensions"], confidence: 85, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-013", title: "Non-standard hole sizes require end mill boring — 5-10× slower than drilling", body: "Holes with non-standard diameters cannot use standard twist drills and must be machined with an end mill using helical interpolation or boring. This is 5-10× slower than drilling. Always prefer standard drill sizes (letter, number, fractional, or metric) when possible. Check a drill chart before specifying hole diameters.", category: "design", tags: ["dfm", "holes", "drill-size", "boring", "helical-interpolation"], confidence: 85, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-014", title: "SINUMERIK CYCLE832: set tolerance, smoothing, and jerk for HSM", body: "Siemens SINUMERIK CYCLE832 (High Speed Settings) configures three parameters: tolerance (path deviation in mm), smoothing level (affects contour accuracy), and jerk limitation. Tighter tolerance = more accurate but slower. For roughing use tolerance 0.05-0.1mm; for finishing use 0.005-0.01mm. COMPCAD converts G1 blocks to splines for smoother motion.", category: "setup", tags: ["sinumerik", "cycle832", "hsm", "tolerance", "compcad", "spline"], confidence: 85, source: "document:sinumerik-5axis@cycle832", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-015", title: "SINUMERIK TRAORI enables 5-axis transformation — required before CUT3D", body: "SINUMERIK 5-axis programming requires TRAORI (TRAnsformation ORIentation) to activate kinematic transformation before any 5-axis moves. CUT3D enables peripheral milling with tool radius compensation in 5-axis mode. Without TRAORI active, 5-axis interpolation commands are rejected. TRAFOOF disables transformation.", category: "setup", tags: ["sinumerik", "traori", "5-axis", "cut3d", "transformation", "kinematic"], confidence: 85, source: "document:sinumerik-5axis@traori", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-016", title: "Wiper inserts improve face mill finish without reducing feed", body: "Wiper insert geometry on face mills allows achieving fine surface finish (Ra <0.8µm) at production feed rates. Standard inserts require reduced feed for finish passes. Wiper inserts have a secondary flat or radius that burnishes the surface on the trailing edge. Use one wiper insert per face mill body — more than one can cause vibration.", category: "tooling", tags: ["face-mill", "wiper-insert", "surface-finish", "productivity"], confidence: 85, source: "document:cnc-face-mill-guide@wiper", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-017", title: "Small features below 2.5mm require micro-machining — cost jumps significantly", body: "Features smaller than 2.5mm width/diameter enter micro-machining territory requiring specialized spindles (40,000+ RPM), microscope inspection, and extremely rigid setups. Feasible minimum is ~0.1mm but cost is 10-50× standard machining. Below 0.1mm, consider EDM or laser machining instead of conventional CNC.", category: "design", tags: ["dfm", "micro-machining", "small-features", "edm", "cost"], confidence: 85, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-018", title: "Tall feature aspect ratio >4 causes vibration — rotate part or add support", body: "Features taller than 4× their base width are prone to vibration (chatter) during machining. Solutions: (1) orient part so tall feature is parallel to spindle axis, (2) add temporary support ribs (machine away last), (3) reduce DOC and increase number of passes, (4) use climb milling to push feature against solid material.", category: "design", tags: ["dfm", "aspect-ratio", "vibration", "chatter", "tall-feature"], confidence: 85, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-019", title: "Internal fillet must be ≥1/3 × pocket depth for tool rigidity", body: "Internal corner fillets in pockets should be at least 1/3 of the pocket depth. This allows using a sufficiently rigid tool. A 30mm deep pocket needs ≥10mm fillet radius (20mm tool diameter). Smaller fillets require smaller tools with worse rigidity, causing vibration and limiting depth. Floor edges can be left sharp (tool nose radius) or given 0.1-1mm radius.", category: "design", tags: ["dfm", "fillet", "internal-corner", "pocket", "tool-diameter"], confidence: 88, source: "document:cnc-complete-guide@design-rules", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cnc-020", title: "Chip thinning with radial engagement <50%: increase feed to maintain chip load", body: "When radial engagement (stepover/tool diameter) drops below 50%, the actual chip thickness is less than the programmed feed per tooth due to geometry. At 25% radial engagement, actual chip is ~71% of programmed. At 10%, it's ~45%. Increase programmed feed rate by the chip thinning factor to maintain proper chip load and avoid rubbing. HSM strategies exploit this for higher MRR.", category: "speeds", tags: ["chip-thinning", "radial-engagement", "hsm", "feed-rate", "stepover"], confidence: 88, source: "document:cnc-feeds-speeds-guide@ch6", created_at: "2026-03-03", usage_count: 0 },

  // --- CNC Batch 2: InventorCAM/SolidCAM + hyperMILL CAM Strategy Guides ---
  { id: "TK-DL-cam-001", title: "Constant Z for steep (30-90°), 3D Constant Step Over for shallow areas", body: "Use Constant Z (waterline) finishing for steep model areas with inclination 30-90°. In shallow areas the Z-passes become widely spaced causing poor finish. Switch to 3D Constant Step Over or Linear machining for areas below ~30° inclination. The Hybrid Constant Z strategy automatically inserts additional passes in shallow zones between Z-levels.", category: "strategy", tags: ["3d-finishing", "constant-z", "step-over", "slope-angle", "hybrid"], confidence: 90, source: "document:inventorcam-3d-hsm@ch2", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-002", title: "Rest machining from top-down beats pencil milling in corners", body: "Pencil milling in vertical corners forces both the flute and radius into full contact simultaneously, creating adverse cutting conditions. Rest machining picks corners from the top down with proper cutting engagement. Use rest machining instead of pencil milling for internal corners. Pencil milling is still appropriate for fillet blending along edges.", category: "strategy", tags: ["rest-machining", "pencil-milling", "corners", "engagement", "finishing"], confidence: 88, source: "document:inventorcam-3d-hsm@ch2.11", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-003", title: "HSM requires smooth links — minimize retracts to high Z", body: "High-speed machining demands continuous machine motion. Retracts to safe Z between passes kill feed rate and create dwell marks. HSM linking strategies: (1) stay on surface within tolerance, (2) stay down within clearance, (3) angle retracts rather than vertical, (4) smooth with arcs. Every retract to safe Z adds 2-5 seconds of non-cutting time.", category: "strategy", tags: ["hsm", "linking", "retract", "air-cutting", "feed-rate"], confidence: 88, source: "document:inventorcam-3d-hsm@ch7", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-004", title: "5-axis hierarchy: 3+2 fixed > auto-indexing > simultaneous", body: "Prefer simplest 5-axis approach that works: (1) 3+2 fixed position — fastest, most rigid, all machines support it. (2) Automatic indexing — finds collision-free fixed angles per area, minimizes machine movement. (3) Simultaneous 5-axis — only when geometry requires continuous tool orientation change (deep cavities, steep walls, SWARF). Simultaneous increases programming time 3-5× and machine wear.", category: "strategy", tags: ["5-axis", "3+2", "indexing", "simultaneous", "hierarchy"], confidence: 90, source: "document:hypermill-cam-strategies@5axis", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-005", title: "SWARF machining: line contact = fewer passes + better surface", body: "SWARF (Side Wall And Ruled Finish) uses the tool's side for line contact with steep surfaces instead of point contact. This produces better surface quality with fewer passes compared to ball-nose finishing. SWARF requires: (1) ruled/near-ruled surfaces, (2) 5-axis simultaneous capability, (3) careful tilt angle management to avoid gouging. Best for aerospace structural ribs and blade surfaces.", category: "strategy", tags: ["swarf", "5-axis", "line-contact", "surface-quality", "aerospace"], confidence: 88, source: "document:inventorcam-swarf@intro", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-006", title: "Morphed machining: passes follow drive curves for blended surfaces", body: "Morphed machining generates passes that gradually transition (morph) between two drive boundary curves. Each pass takes characteristics of both curves proportionally. This produces superior surface finish on blended/transitional surfaces compared to Linear or Constant Z. Best for fillet surfaces, turbine blades, and aesthetic surfaces where uniform tool marks are critical.", category: "strategy", tags: ["morphed", "drive-curves", "surface-blend", "finishing", "aesthetic"], confidence: 85, source: "document:inventorcam-3d-hsm@ch2.8", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-007", title: "Complementary finishing: Z-level + equidistant covers all slopes in one op", body: "Combined/complementary finishing strategies automatically divide the model by slope angle and apply the optimal strategy to each region. Z-level finishing handles steep areas, equidistant/profile finishing handles flat areas. Both can use spiral patterns for best surface quality. This eliminates the need for separate steep/shallow operations and ensures no gaps at the transition.", category: "strategy", tags: ["complementary", "z-level", "equidistant", "slope-division", "combined"], confidence: 88, source: "document:hypermill-cam-strategies@3d-complementary", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-008", title: "Trochoidal turning: rounded passes for better tool life on complex profiles", body: "Trochoidal turning uses rounded (arc-based) cutting passes instead of conventional linear passes. The smooth entry/exit reduces impact loading on the insert. Benefits: higher cutting speed, reduced tool wear, better chip control on complex profiles. Particularly effective for hardened materials and interrupted cuts where conventional turning causes insert chipping.", category: "turning", tags: ["trochoidal-turning", "tool-life", "rounded-passes", "hard-turning", "insert"], confidence: 85, source: "document:inventorcam-turning@trochoidal", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-009", title: "Balanced roughing: dual-tool simultaneous cuts halve cycle time", body: "Balanced rough turning uses two tools (master + slave) performing roughing cuts simultaneously from opposite sides. Both submachines must share the same turret table. This can nearly halve roughing cycle time on large-diameter parts. Requires: (1) mill-turn machine with dual turrets, (2) symmetric or near-symmetric part geometry, (3) careful synchronization to avoid collision.", category: "turning", tags: ["balanced-rough", "dual-tool", "cycle-time", "mill-turn", "synchronization"], confidence: 85, source: "document:inventorcam-turning@balanced-rough", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-010", title: "Mill-turn advantage: single setup eliminates re-fixturing errors", body: "Mill-turn machines combine turning and milling in one setup, eliminating re-fixturing between operations. Key benefits: (1) concentricity guaranteed between turned and milled features, (2) no datum shift from re-clamping, (3) reduced total cycle time (no manual handling), (4) single post-processor for all operations. Worth the +25% hourly rate premium for parts requiring both turning and milling features.", category: "setup", tags: ["mill-turn", "single-setup", "concentricity", "re-fixturing", "cost-benefit"], confidence: 88, source: "document:inventorcam-turning@mill-turn", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-011", title: "Spiral Z-level finishing gives best surface on closed milling areas", body: "For closed (pocket-like) milling areas, use spiral Z-level finishing instead of zigzag. Spiral motion maintains constant engagement and avoids the direction reversal marks that zigzag creates. Open milling areas should use zigzag with filleted path links. The spiral approach also reduces dwell time at reversals which can cause burn marks on heat-sensitive materials.", category: "strategy", tags: ["spiral", "z-level", "finishing", "surface-quality", "pocket"], confidence: 85, source: "document:hypermill-cam-strategies@3d-zlevel", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-012", title: "ISO machining follows UV curves for natural surface flow", body: "ISO machining generates toolpaths that follow the ISO parametric curves (U and V) of CAD surfaces. The paths align with the natural surface flow, producing more uniform tool marks. UV curves of contiguous surfaces are automatically aligned so the tool doesn't retract between surfaces. Best for: turbine blades, mold surfaces, any geometry where surface appearance matters.", category: "strategy", tags: ["iso-machining", "uv-curves", "surface-flow", "parametric", "appearance"], confidence: 85, source: "document:hypermill-cam-strategies@iso", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-013", title: "5-axis rework: convert 3D toolpaths to 5-axis to resolve collisions", body: "5-axis rework machining converts existing 3D toolpaths into 5-axis programs by adding tool orientation changes. Areas excluded from 3D operations due to collision can be recovered with 5-axis positions. This is faster than reprogramming from scratch: calculate in 3D first, then selectively convert collision areas to 5-axis. Automatic indexing or simultaneous modes available.", category: "strategy", tags: ["5-axis", "rework", "collision", "conversion", "3d-to-5axis"], confidence: 85, source: "document:hypermill-cam-strategies@5axis-rework", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-014", title: "Helical machining: continuous descending ramp avoids Z-level dwell marks", body: "Helical machining joins Constant Z profile sections into a continuous descending spiral, eliminating the Z-step witness marks left by standard Constant Z finishing. Controlled by step-down and max ramp angle parameters. Best for revolution bodies and cylindrical features where the continuous helical path matches the part geometry naturally.", category: "strategy", tags: ["helical", "finishing", "spiral", "witness-marks", "revolution-body"], confidence: 85, source: "document:inventorcam-3d-hsm@ch2.3", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cam-015", title: "Automatic minimum tool length calculation prevents collisions", body: "Before running any 3D HSM operation, use the automatic minimum tool length calculation. This checks the tool + holder assembly against the part geometry and reports the minimum length needed to avoid holder collision. Running operations with insufficient tool length causes holder crashes that damage both the tool and the workpiece. Add 5-10mm safety margin to the calculated minimum.", category: "setup", tags: ["tool-length", "holder-collision", "safety", "minimum-length", "hsm"], confidence: 88, source: "document:inventorcam-3d-hsm@ch4.1", created_at: "2026-03-03", usage_count: 0 },
  // --- Batch 3: Haas Mill Manual + MIT 2.008 (casting, deforming) ---
  { id: "TK-DL-haas-001", title: "Run spindle warm-up after 4+ days idle (Haas O09220)", body: "On Haas mills, if the spindle has been idle for more than 4 days, run the built-in 20-minute warm-up program O09220 before machining. This gradually increases RPM to distribute spindle lubrication and reach thermal equilibrium. For consistent high-speed work, run this warm-up daily. Skipping warm-up risks bearing damage and poor initial part accuracy due to thermal growth.", category: "setup", tags: ["haas", "spindle", "warm-up", "thermal", "maintenance"], confidence: 92, source: "document:haas-mill-2023@p96", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-haas-002", title: "G103 limits block look-ahead for macro timing (Haas)", body: "Haas controls read blocks ahead for smooth motion, but this causes macro outputs (M-codes, relays) to fire early. Use G103 P1 to limit look-ahead to 1 block when precise timing matters — e.g., turning a relay on, dwelling, then off. Without G103 P1, the output toggles instantly while the control pre-processes the dwell. Block delete '/' tokens also stop look-ahead even when block delete mode is off.", category: "programming", tags: ["haas", "g103", "look-ahead", "macro", "timing"], confidence: 90, source: "document:haas-mill-2023@p116", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-haas-003", title: "Use ROUND[] for macro integer comparisons (floating point trap)", body: "CNC controls store decimal numbers as binary floating point, so integer values in macro variables may read as 6.999999 or 7.000001 instead of 7. Always wrap integer comparisons with ROUND[]: use IF[ROUND[#10000] EQ 7] instead of IF[#10000 EQ 7]. This is critical for loop counters, tool number variables, and conditional branching. Applies to Haas, FANUC, and most controls using IEEE 754 math.", category: "programming", tags: ["macro", "floating-point", "haas", "fanuc", "rounding"], confidence: 90, source: "document:haas-mill-2023@p116", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cast-001", title: "Casting shrinkage allowances by material family", body: "Pattern dimensions must be oversized to compensate for solidification shrinkage. Typical allowances (mm/m): aluminum alloys 13, aluminum bronze 21, yellow brass 13, gray cast iron 8-13, white cast iron 21, carbon steel 16-21, chromium steel 21, manganese steel 26, magnesium 21, lead 26, zinc 26. Higher-shrinkage alloys (Mn steel, zinc, lead) need more generous patterns and risering. Source: MIT 2.008.", category: "material", tags: ["casting", "shrinkage", "pattern", "allowance", "material-properties"], confidence: 88, source: "document:mit2008-casting@shrinkage-table", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cast-002", title: "Casting tolerance comparison: sand vs investment vs die", body: "Achievable casting tolerances vary dramatically by process. Sand casting: 0.7-2mm (roughest). Investment casting: 0.08-0.2mm (good for complex shapes). Die casting: 0.02-0.6mm (best for production). When designing cast parts that need CNC finishing, plan machining allowances based on casting process tolerance. Investment castings may need minimal finish machining; sand castings need significant stock removal.", category: "quality", tags: ["casting", "tolerance", "sand-casting", "investment-casting", "die-casting"], confidence: 88, source: "document:mit2008-casting@quality-comparison", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cast-003", title: "Pattern machining allowance for cast parts by size and material", body: "Cast parts need machining allowance added to pattern dimensions. For cast iron: bore 3.2-7.9mm, surface 2.4-4.8mm, cope side 4.8-7.9mm (increases with pattern size 152-1524mm). Cast steel needs ~50% more allowance than cast iron. Nonferrous alloys need the least: 1.6-4.0mm. Cope (top) side always needs more allowance than drag side due to inclusions and porosity rising during solidification.", category: "design", tags: ["casting", "machining-allowance", "pattern", "cope", "drag"], confidence: 85, source: "document:mit2008-casting@machining-allowance-table", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cast-004", title: "Casting process selection: cost vs quality vs rate tradeoffs", body: "Sand casting: low tooling cost ($), high labor, rough quality (0.7-2mm tolerance), 2-10 week development, flexible shapes. Investment casting: moderate tooling, high labor, fine quality (0.08-0.2mm), 5-16 week development, complex internal geometry possible. Die casting: high tooling cost ($$$), low labor, excellent quality (0.02-0.6mm), 12-20 week development, low design flexibility. Choose sand for prototypes/low volume, die for high volume, investment for complex precision parts.", category: "process_selection", tags: ["casting", "sand", "investment", "die", "cost-quality-tradeoff"], confidence: 88, source: "document:mit2008-casting@process-comparison", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-cast-005", title: "Chvorinov solidification rule: sand ts~(V/A)² vs die ts~(V/A)¹", body: "Solidification time follows Chvorinov's rule: ts = C(V/A)^n where V=volume, A=surface area. For sand casting n=2 (heat transfer limited by sand conductivity ~0.5 W/mK), for die casting n=1 (metal mold conductivity ~200 W/mK dominates). This means thick sections in sand castings take disproportionately longer to solidify, causing more shrinkage porosity. Die casting solidifies more uniformly. Design risers to feed the last-to-solidify sections.", category: "physics", tags: ["casting", "solidification", "chvorinov", "heat-transfer", "riser-design"], confidence: 85, source: "document:mit2008-casting@solidification", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-form-001", title: "Spring back in bending: increases with Y/E ratio and R/t", body: "After bending, elastic recovery causes the part to spring back. The relationship is Ri/Rf = 1 - 3(Y/E)(Ri/t) + 4(Y/E)³(Ri/t)³ where Y=yield stress, E=Young's modulus, t=thickness, Ri=initial bend radius, Rf=final radius. Titanium (high Y/E ~0.01) springs back much more than steel (Y/E ~0.002). Compensate by over-bending. Thinner sheets and larger radii also increase spring back. Critical for bent-then-machined brackets and fixtures.", category: "physics", tags: ["bending", "spring-back", "sheet-metal", "forming", "compensation"], confidence: 82, source: "document:mit2008-deforming@spring-back", created_at: "2026-03-03", usage_count: 0 },
  { id: "TK-DL-form-002", title: "Forging force with friction: F≈πR²Y(1+2µR/3h) — friction dominates for flat parts", body: "Open-die forging force for axisymmetric upsetting with friction: F = πR²Y(1 + 2µR/3h) where R=radius, Y=yield stress, h=height, µ=friction coefficient. The friction term 2µR/3h becomes dominant for large R/h ratios (flat pancake shapes), potentially doubling the required force. This explains why thin forgings need much larger presses than thick ones of the same volume. Good lubrication (low µ) is critical for reducing press tonnage requirements.", category: "physics", tags: ["forging", "friction", "force", "upsetting", "press-tonnage"], confidence: 82, source: "document:mit2008-deforming@forging-force", created_at: "2026-03-03", usage_count: 0 },
  // --- Batch 4: Mazak INTEGREX IV manuals (EIA + Mazatrol + 3D) ---
  { id: "TK-DL-mazak-001", title: "G12.1 polar coordinate interpolation for face milling on cylindrical parts", body: "G12.1 enables milling features on the face or OD of a round part by converting XY rectangular coordinates to linear+rotational (X+C) axis motion. Program contours as if working on a flat plane; the control converts to synchronized C-axis rotation and X-axis movement. Essential for keyways, flats, hexagons, and cam profiles on turned parts. Cancel with G13.1. Feed rate F is tangential speed in mm/min. Cannot activate/cancel during cutter compensation (G41/G42) — must be in G40 mode.", category: "programming", tags: ["mazak", "integrex", "polar-interpolation", "g12.1", "c-axis", "turn-mill"], confidence: 90, source: "document:mazak-eia-integrex-iv@ch6-8", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-002", title: "G07.1 cylindrical interpolation — unwrap cylinder surface for 2D programming", body: "G07.1 C<radius> 'unwraps' a cylinder surface into a flat plane for programming. The C-axis angular motion is converted to linear distance on the circumference (arc = angle * radius). Program contours using Z and C as if on a flat surface; the control handles the rotational conversion. Ideal for cam grooves, helical grooves, and text engraving on cylindrical parts. Cancel with G07.1 C0. The radius parameter defines the cylinder surface being programmed.", category: "programming", tags: ["mazak", "integrex", "cylindrical-interpolation", "g07.1", "cam-groove", "unwrap"], confidence: 90, source: "document:mazak-eia-integrex-iv@ch6-12", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-003", title: "G06.1 spline interpolation for smooth free-form machining", body: "G06.1 creates smooth curves through specified points without requiring arc segments. The control automatically generates a spline curve that passes through all programmed points. Requires at least 3 points (2+ blocks in spline mode). The curve is automatically divided at corners where the angle between segments exceeds the spline-cancel angle parameter (F101). Cancel with any Group 01 code (G00/G01/G02/G03). Best for free-form surfaces where calculating arc centers would be impractical.", category: "programming", tags: ["mazak", "spline", "g06.1", "free-form", "interpolation", "smooth-path"], confidence: 85, source: "document:mazak-eia-integrex-iv@ch6-10", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-004", title: "G43.4/G43.5 tool tip point control (RTCP) for 5-axis on INTEGREX", body: "G43.4 (Type 1) and G43.5 (Type 2) enable Rotary Tool Center Point control on multi-axis machines. When the B-axis rotates the tool, RTCP automatically compensates XYZ positions to keep the tool tip stationary on the workpiece surface. Without RTCP, rotating the B-axis would shift the cutting point. Critical for 5-axis simultaneous machining on INTEGREX machines where the milling spindle tilts via B-axis. Type 1 vs Type 2 differ in how the compensation vector is calculated relative to the rotary axis center.", category: "programming", tags: ["mazak", "integrex", "rtcp", "g43.4", "5-axis", "tool-tip-control"], confidence: 88, source: "document:mazak-eia-integrex-iv@ch15", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-005", title: "G68.5 tilted working plane for angled feature machining on INTEGREX", body: "G68.5 (Mazak T-series) or G68 (M-series) activates 3D coordinate conversion to define a tilted working plane. After setting the B-axis angle, G68.5 rotates the programming coordinate system so you can program features (holes, pockets, contours) as if working on a flat surface, even though the actual machining is at an angle. Cancel with G69.5/G69. Essential for machining features on angled faces of complex parts without recalculating coordinates manually.", category: "programming", tags: ["mazak", "integrex", "tilted-plane", "g68.5", "coordinate-rotation", "angled-features"], confidence: 88, source: "document:mazak-eia-integrex-iv@ch15-12", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-006", title: "Mazatrol auto tool development: multi-drill staging by hole diameter", body: "Mazatrol conversational programming automatically develops (selects) tools based on hole geometry. For drilling: 1 drill if DIA <= D8 parameter, 2 drills if D8 < DIA <= D9, 3 drills if D9 < DIA <= D10. A centering drill is always included. Chamfering cutters are added unless chamfer=0 or hole+chamfer fits within existing tool diameter. The system generates alarm 416 'AUTO PROCESS IMPOSSIBLE' if depth < chamfer or diameter=0 or exceeds D10 limit. Same logic applies to counterbore (RGH CBOR), back counterbore (RGH BCB), reaming, and tapping units.", category: "programming", tags: ["mazak", "mazatrol", "auto-tool-development", "conversational", "drilling", "tool-staging"], confidence: 90, source: "document:mazak-mazatrol-matrix@ch3-5-3", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-007", title: "Mazatrol unit-based programming: Common -> Material -> Process units", body: "Mazatrol programs follow a strict unit structure: (1) Common unit defines workpiece coordinate system, (2) Material Shape unit defines blank geometry, (3) Process units define machining operations. Process units include: Point (drilling/tapping/boring), Line (contour milling), Face (pocket/face milling), Turning (OD/ID/face), Bar (bar stock), Copy (pattern repeat), Corner, Facing, Threading, Grooving, and Mill-Turn. Each unit auto-develops its own tool sequence. The structure ensures safe approach/retract between units and enables automatic cutting condition calculation.", category: "programming", tags: ["mazak", "mazatrol", "conversational", "unit-structure", "program-organization"], confidence: 88, source: "document:mazak-mazatrol-matrix@ch3", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-008", title: "Automatic corner override — feed reduction at direction changes", body: "Both Mazatrol and EIA programs benefit from automatic corner override: the control reduces feed rate when approaching sharp direction changes to prevent tool shock, surface marks, and overshooting. In Mazatrol line machining, the override angle and deceleration factor are set per unit. For EIA programs, parameter-based corner deceleration activates when the included angle between consecutive moves falls below a threshold. This is especially important for finish passes where corner quality directly impacts part accuracy and surface finish.", category: "strategy", tags: ["mazak", "corner-override", "feed-reduction", "direction-change", "surface-quality"], confidence: 85, source: "document:mazak-mazatrol-matrix@ch3-6-7", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-009", title: "INTEGREX mill-turn: upper/lower turret priority and synchronization", body: "INTEGREX IV machines have upper milling spindle + lower turret for simultaneous operations. The 'Priority Function for Same Tool' optimizes tool changes by reusing the same tool across multiple units without returning to the magazine. Lower turret control allows turning operations to run simultaneously with milling operations on the upper spindle. Key constraint: when both turrets are active, the feed rate is limited by the slower operation. Program synchronization points (M-codes) ensure turret positions don't conflict. This dual-turret capability can reduce cycle times by 30-50% on complex parts.", category: "strategy", tags: ["mazak", "integrex", "mill-turn", "dual-turret", "synchronization", "cycle-time"], confidence: 85, source: "document:mazak-mazatrol-matrix@ch4-5", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-mazak-010", title: "Mazatrol 3D units: 11 curved surface types for conversational 3D machining", body: "Mazatrol Matrix 3D provides 11 unit types for machining free-form curved surfaces using conversational programming (no CAM software needed). Surfaces are defined by guide lines (GL) and cross-sections. The system generates roughing and finishing toolpaths automatically. Key advantage: shop-floor programmers can create 3D programs directly on the control without CAD/CAM knowledge. Limitations: complex multi-surface blends and undercuts still require external CAM. Best used for simple molds, dies, and sculptured features on INTEGREX machines where the geometry can be described by cross-sectional profiles.", category: "strategy", tags: ["mazak", "mazatrol", "3d-machining", "conversational", "curved-surface", "mold"], confidence: 82, source: "document:mazak-3d-unit@ch1-2", created_at: "2026-03-06", usage_count: 0 },
  // --- Batch 5: Okuma OSP-P300 Special Functions + CNCCookbook ---
  { id: "TK-DL-okuma-001", title: "Okuma TAS-S/TAS-C: real-time thermal deformation compensation at 0.1um", body: "Okuma's Thermo-Active Stabilizer has three modes: TAS-S compensates spindle bearing/motor heat during rotation, TAS-C compensates machine body deformation from ambient temperature changes, and TAS-C with thermal expansion handles differential expansion across wide-travel machines (double-column). Temperature sensors embedded throughout the machine feed data to the NC which calculates and applies compensation in real-time at 0.1um resolution — finer than the 1um minimum NC data unit. Always active in all modes (auto/MDI/manual). Compensation is transparent to the operator (doesn't affect displayed coordinates or tool offsets).", category: "setup", tags: ["okuma", "osp-p300", "thermal-compensation", "tas", "accuracy", "real-time"], confidence: 92, source: "document:okuma-osp-p300-special@sec28", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-okuma-002", title: "Okuma tool life management: 7 determination modes for automatic replacement", body: "Okuma OSP-P300 supports 7 tool life determination modes: (1) used time, (2) travel distance, (3) machining cycle count, and combinations thereof. Tools are organized in groups; when a tool reaches its life limit, the control automatically selects the next tool in the group. The TOOL LIFE sheet displays current tool status with the active tool highlighted yellow. Life data can be reset per-tool or per-group. This enables lights-out machining by pre-loading redundant tools and letting the control manage replacements automatically.", category: "setup", tags: ["okuma", "osp-p300", "tool-life", "management", "automatic-replacement", "lights-out"], confidence: 88, source: "document:okuma-osp-p300-special@sec21", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-okuma-003", title: "Okuma simplified load monitor: detect tool breakage and overload in real-time", body: "The OSP-P300 simplified load monitor continuously tracks spindle and axis servo loads during machining. When load exceeds programmed thresholds, the control can alarm, retract, or skip to the next tool. Key for detecting: broken tools (sudden load drop), worn tools (gradual load increase), and collision events (spike). Set upper limit slightly above normal cutting load for the operation. The monitor displays real-time load bars on screen. Particularly valuable for unattended production runs where operator visual/audio detection is unavailable.", category: "safety", tags: ["okuma", "osp-p300", "load-monitor", "tool-breakage", "overload", "unattended"], confidence: 88, source: "document:okuma-osp-p300-special@sec6", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-okuma-004", title: "Okuma cycle time reduction: block overlap and corner smoothing", body: "OSP-P300 cycle time reduction function optimizes motion by overlapping block processing and smoothing corner transitions. Instead of decelerating to zero at each block boundary, the control calculates allowable corner speed based on axis acceleration limits and programmed tolerance. This is most effective for programs with many short linear segments (typical CAM output). The function is similar to Fanuc's AI Contour Control and Siemens CYCLE832 but uses Okuma-specific parameters. Enable via NC parameter; the effect is most dramatic on 3D surface finishing where thousands of micro-segments would otherwise cause jerky motion.", category: "strategy", tags: ["okuma", "osp-p300", "cycle-time", "corner-smoothing", "block-overlap", "hsm"], confidence: 85, source: "document:okuma-osp-p300-special@sec9", created_at: "2026-03-06", usage_count: 0 },
  { id: "TK-DL-cnc-021", title: "Mill CAM engraving trick: generate lathe profiles using mill CAM software", body: "If you have mill CAM but no lathe CAM, use the engraving/profiling toolpath to generate turning profiles. Draw the desired turned profile in CAD (XZ cross-section), import to mill CAM, and run an engraving toolpath along the contour. The output G-code contains the XZ coordinates of your profile. Strip the mill-specific codes (G17, spindle, etc.) and wrap the coordinates with G71 (rough turning cycle) header. The G71 cycle handles roughing passes automatically from the profile. This avoids manual coordinate calculation for complex turned profiles with arcs and tapers.", category: "programming", tags: ["lathe", "mill-cam", "engraving", "g71", "profile", "workaround"], confidence: 82, source: "document:cnccookbook-mill-cam-lathe@trick", created_at: "2026-03-06", usage_count: 0 },
];

// ============================================================================
// ENGINE CLASS
// ============================================================================

/** Tribal Knowledge Engine engine/manager.
 */
export class TribalKnowledgeEngine {
  private tips: KnowledgeTip[] = [...KNOWLEDGE_BASE];

  capture(tip: Omit<KnowledgeTip, "id" | "created_at" | "usage_count">): KnowledgeTip {
    const newTip: KnowledgeTip = {
      ...tip,
      id: `tk-${String(this.tips.length + 1).padStart(3, "0")}`,
      created_at: new Date().toISOString().slice(0, 10),
      usage_count: 0,
    };
    this.tips.push(newTip);
    return newTip;
  }

  search(input: KnowledgeSearchInput): KnowledgeTip[] {
    let results = [...this.tips];

    if (input.category) results = results.filter(t => t.category === input.category);
    if (input.material_iso_group) results = results.filter(t => !t.material_groups || t.material_groups.includes(input.material_iso_group!));
    if (input.operation_type) results = results.filter(t => !t.operation_types || t.operation_types.includes(input.operation_type!));
    if (input.min_confidence) results = results.filter(t => t.confidence >= input.min_confidence!);

    if (input.query) {
      const q = input.query.toLowerCase();
      results = results.filter(t =>
        t.title.toLowerCase().includes(q) ||
        t.body.toLowerCase().includes(q) ||
        t.tags.some(tag => tag.includes(q))
      );
    }

    // Sort by relevance (confidence × usage)
    results.sort((a, b) => (b.confidence * Math.log2(b.usage_count + 2)) - (a.confidence * Math.log2(a.usage_count + 2)));

    return results.slice(0, input.limit || 5);
  }

  suggest(materialIso: string, operationType: string): KnowledgeSuggestion {
    const tips = this.search({ material_iso_group: materialIso, operation_type: operationType, limit: 5 });
    const relevance: Record<string, number> = {};

    for (const tip of tips) {
      let score = tip.confidence / 100;
      if (tip.material_groups?.includes(materialIso)) score += 0.2;
      if (tip.operation_types?.includes(operationType)) score += 0.2;
      relevance[tip.id] = Math.min(1.0, Math.round(score * 100) / 100);
    }

    return {
      tips, relevance_scores: relevance,
      context_match: `Material: ISO ${materialIso}, Operation: ${operationType}`,
    };
  }

  stats(): KnowledgeStats {
    const byCategory: Record<string, number> = {};
    let high = 0, medium = 0, low = 0;

    for (const tip of this.tips) {
      byCategory[tip.category] = (byCategory[tip.category] || 0) + 1;
      if (tip.confidence >= 85) high++;
      else if (tip.confidence >= 60) medium++;
      else low++;
    }

    const sorted = [...this.tips].sort((a, b) => b.usage_count - a.usage_count);
    const mostUsed = sorted.slice(0, 5).map(t => ({ id: t.id, title: t.title, usage_count: t.usage_count }));

    // Identify coverage gaps
    const gaps = CORE_CATEGORIES.filter(c => !byCategory[c] || byCategory[c] < 2);

    return { total_tips: this.tips.length, by_category: byCategory, by_confidence: { high, medium, low }, most_used: mostUsed, coverage_gaps: gaps };
  }
}

/** Tribal Knowledge Engine constant.
 */
export const tribalKnowledgeEngine = new TribalKnowledgeEngine();
