/**
 * WEDMPostSodickEngine — Wire-EDM post processor for Sodick wire-cut
 * controls. Covers the AQ-series (AQ325L, AQ535L, AQ750L) and the AL/SL
 * series (AL400P, SL400G, SL600G), all built around the LN-series CNC.
 *
 * Vendor references:
 *   • Sodick "LN Professional Programming Manual" rev. 2015
 *   • Sodick "Power Master" E-table and S-table bulletins
 *   • JIS B 6313 (EDM G-code conventions)
 *
 * Dialect highlights the generic router did NOT capture:
 *   • E-tables: E000–E999. Each E-number is the index into the Power Master
 *     pulse-generation table (ON / OFF / IP / MAO / SV / V). The number is
 *     emitted as a standalone block; no comment needed, but we include one
 *     for operator readability.
 *   • S-code servo table: S01–S99 supplies servo voltage and feed-rate.
 *   • G82 nozzle-down / G81 nozzle-up flushing positioning.
 *   • M50/M51 pair for automatic wire threader (AWT).
 *   • Sodick taper uses G51 + P<deg> form on LN controllers (not A-word).
 *   • "q" suffix to program number on AQ controllers is omitted.
 *
 * MS-P1.5-ONESHOT/U-P1.5-OS-04
 */

import {
  IWEDMPostEngine,
  WEDMController,
  WEDMParsedPlan,
  WEDMPassId,
  WEDMPostInput,
  WEDMPostOutput,
  formatCoord,
  passDefaults,
} from "./WEDMPostTypes.js";

// ── Sodick Power Master E-table (pass → E/S codes) ─────────────────────────
// Source: LN Programming Manual defaults for 25 mm SKD11 (D2 equivalent).
const SODICK_TECH_TABLE: Record<WEDMPassId, { e: string; s: string; description: string }> = {
  rough: { e: "E510", s: "S04", description: "ROUGH main cut, 25mm SKD11, 0.25mm brass" },
  skim1: { e: "E520", s: "S03", description: "SKIM1 (stock 0.08mm)" },
  skim2: { e: "E530", s: "S02", description: "SKIM2 (stock 0.03mm, Ra ≤ 2.5µm)" },
  skim3: { e: "E540", s: "S01", description: "SKIM3 final (stock 0.008mm, Ra ≤ 1.0µm)" },
};

const SODICK_COORD_DECIMALS_MM = 3;
const SODICK_COORD_DECIMALS_IN = 5;

export class WEDMPostSodickEngine implements IWEDMPostEngine {
  readonly name = "WEDMPostSodickEngine";
  readonly version = "1.0.0";
  readonly supportedControllers: readonly WEDMController[] = ["sodick_aq", "sodick_al"];
  readonly manufacturer = "Sodick";

  dialectNameFor(controller: WEDMController): string {
    if (controller === "sodick_aq") return "Sodick AQ";
    if (controller === "sodick_al") return "Sodick AL";
    return "Sodick";
  }

  generate(input: WEDMPostInput): WEDMPostOutput {
    const controller = input.controller;
    if (!this.supportedControllers.includes(controller)) {
      return {
        success: false,
        controller,
        dialect_name: "UNKNOWN",
        gcode_lines: [],
        gcode_text: "",
        line_count: 0,
        operation_count: 0,
        warnings: [`WEDMPostSodickEngine does not support controller '${controller}'`],
        dialect_specific: {},
      };
    }

    const lines: string[] = [];
    const warnings: string[] = [];
    const dialectName = this.dialectNameFor(controller);
    const isImperial = input.units === "imperial";
    const decimals = isImperial ? SODICK_COORD_DECIMALS_IN : SODICK_COORD_DECIMALS_MM;
    const progNum = (input.program_number ?? "0001").padStart(4, "0");

    // ── Header ──
    lines.push("%");
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "WIRE EDM PROGRAM"})`);
    lines.push(`(CONTROLLER: ${dialectName} LN)`);
    lines.push(`(MATERIAL: ${input.material ?? "SKD11"} THICKNESS: ${input.thickness_mm.toFixed(2)}mm)`);
    lines.push(`(WIRE: ${(input.wire_diameter_mm ?? 0.25).toFixed(2)}mm)`);
    lines.push(`(GENERATED BY PRISM WEDM POST — SODICK DIALECT v${this.version})`);
    lines.push("");

    const unitCode = isImperial ? "G20" : "G21";
    const unitLabel = isImperial ? "INCH" : "METRIC";
    lines.push(`G90 ${unitCode} (ABSOLUTE ${unitLabel})`);
    lines.push("G92 X0 Y0 (SET PART ZERO)");
    lines.push("G29 (RETURN TO WIRE THREAD POSITION)");

    if (input.thickness_mm > 150) {
      warnings.push(`Thickness ${input.thickness_mm}mm exceeds AQ/SL max stroke — verify Z travel`);
    }
    if (input.thickness_mm <= 0 || !Number.isFinite(input.thickness_mm)) {
      warnings.push(`Invalid thickness ${input.thickness_mm}mm — Sodick expects > 0`);
    }

    const eCodesUsed: string[] = [];
    const sCodesUsed: string[] = [];
    const cornerControlSet = new Set<string>();

    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      const d = passDefaults(op.pass);
      const power = op.power_setting ?? d.power;
      const onTime = op.on_time_us ?? d.on_us;
      const offTime = op.off_time_us ?? d.off_us;
      const wireSpeed = op.wire_speed_m_min ?? d.wire_speed;
      const wireTension = op.wire_tension_g ?? d.wire_tension;
      const offset = op.offset_mm ?? 0.15;
      const direction = op.offset_direction ?? "left";
      const autoThread = op.auto_thread !== false;
      const submerged = op.submerged !== false;

      const tech = SODICK_TECH_TABLE[op.pass];
      eCodesUsed.push(tech.e);
      sCodesUsed.push(tech.s);

      lines.push("");
      lines.push(`(--- PASS ${i + 1}: ${op.pass.toUpperCase()} ${op.type.toUpperCase()} ---)`);
      lines.push(`${tech.e} (${tech.description})`);
      lines.push(`${tech.s} (SERVO TABLE)`);
      lines.push(`(PWR=${power} ON=${onTime}us OFF=${offTime}us WF=${wireSpeed}m/min WT=${wireTension}g)`);

      // Sodick stores offsets in H-registers just like Mitsubishi but the
      // convention is a direct value on the compensation line: G41 H<um>.
      const offsetUm = Math.round(offset * 1000);
      const offsetWord = `H${String(offsetUm).padStart(3, "0")}`;

      if (autoThread) {
        lines.push("M50 (AWT AUTO WIRE THREAD)");
      }
      if (submerged) {
        lines.push("M78 (SUBMERGE ON)");
        lines.push("G82 (NOZZLE DOWN)");
      }

      if (op.start_x !== undefined && op.start_y !== undefined) {
        const x = formatCoord(op.start_x, isImperial, decimals);
        const y = formatCoord(op.start_y, isImperial, decimals);
        lines.push(`G0 X${x} Y${y} (APPROACH)`);
      }

      const offsetCode = direction === "right" ? "G42" : "G41";
      lines.push(`${offsetCode} ${offsetWord} (COMP ON ${direction.toUpperCase()} ${offset.toFixed(3)}mm)`);

      // Sodick taper: G51 P<deg>
      if (op.type === "taper" && typeof op.taper_angle_deg === "number") {
        lines.push(`G51 P${op.taper_angle_deg.toFixed(3)} (TAPER ON ${op.taper_angle_deg.toFixed(3)}deg)`);
        if (typeof op.taper_height_mm === "number") {
          lines.push(`(TAPER HEIGHT ${op.taper_height_mm.toFixed(2)}mm)`);
        }
      }

      // Corner-control hint: Sodick uses the CC1/CC2/CC3 command to bias
      // energy around sharp turns. Emit a default CC2 for rough passes.
      if (op.pass === "rough") {
        lines.push("CC2 (CORNER CONTROL MEDIUM)");
        cornerControlSet.add("CC2");
      }

      if (op.profile_points && op.profile_points.length > 0) {
        for (const pt of op.profile_points) {
          const x = formatCoord(pt.x, isImperial, decimals);
          const y = formatCoord(pt.y, isImperial, decimals);
          let line = `G1 X${x} Y${y}`;
          if (pt.u !== undefined && pt.v !== undefined) {
            const u = formatCoord(pt.u, isImperial, decimals);
            const v = formatCoord(pt.v, isImperial, decimals);
            line += ` U${u} V${v}`;
          }
          lines.push(line);
        }
      } else {
        warnings.push(`Pass ${i + 1}: no profile_points — emitted placeholder`);
        lines.push("(... profile geometry missing ...)");
      }

      if (op.type === "taper") {
        lines.push("G50 (TAPER OFF)");
      }

      lines.push("G40 (CANCEL COMP)");
      lines.push("M51 (AWT CUT)");
      if (submerged) {
        lines.push("G81 (NOZZLE UP)");
        lines.push("M79 (SUBMERGE OFF)");
      }
    }

    // ── Footer ──
    lines.push("");
    lines.push("G92 X0 Y0 (HOME)");
    lines.push("M30");
    lines.push("%");

    const gcodeText = lines.join("\n");

    return {
      success: true,
      controller,
      dialect_name: dialectName,
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      operation_count: input.operations.length,
      warnings,
      dialect_specific: {
        manufacturer: this.manufacturer,
        uses_e_codes: true,
        uses_c_codes: false,
        uses_s_codes: true,
        e_codes_used: eCodesUsed,
        s_codes_used: sCodesUsed,
        corner_control: Array.from(cornerControlSet),
        wire_thread_code: "M50",
        wire_cut_code: "M51",
      },
    };
  }

  parse(gcode: string): WEDMParsedPlan {
    const plan: WEDMParsedPlan = {
      operations: [],
      controller_hint: "sodick_aq",
    };

    const progMatch = gcode.match(/^O(\d+)/m);
    if (progMatch) plan.program_number = progMatch[1];

    const blocks = gcode.split(/\(--- PASS \d+:/).slice(1);
    for (const block of blocks) {
      let pass: WEDMPassId | undefined;
      const eCodeMatch = block.match(/\bE(\d{3})\b/);
      if (eCodeMatch) {
        const eCode = `E${eCodeMatch[1]}`;
        for (const k of Object.keys(SODICK_TECH_TABLE) as WEDMPassId[]) {
          if (SODICK_TECH_TABLE[k].e === eCode) { pass = k; break; }
        }
      }

      const powerMatch = block.match(/PWR=(\d+)/);
      const onMatch = block.match(/ON=(\d+)/);
      const offMatch = block.match(/OFF=(\d+)/);
      const offsetMatch = block.match(/COMP ON .+?\s([\d.]+)mm/);
      const dirIsRight = /G42/.test(block);
      const submerged = /M78\s*\(SUBMERGE ON\)/.test(block);
      const taperMatch = block.match(/G51 P([-\d.]+)/);
      const pointMatches = block.match(/\bG1 X/g);

      plan.operations.push({
        pass,
        power: powerMatch ? Number(powerMatch[1]) : undefined,
        on_us: onMatch ? Number(onMatch[1]) : undefined,
        off_us: offMatch ? Number(offMatch[1]) : undefined,
        offset_mm: offsetMatch ? Number(offsetMatch[1]) : undefined,
        offset_direction: dirIsRight ? "right" : "left",
        submerged,
        taper_angle_deg: taperMatch ? Number(taperMatch[1]) : undefined,
        point_count: pointMatches ? pointMatches.length : 0,
      });
    }

    return plan;
  }

  getTechTable(): Readonly<Record<WEDMPassId, { e: string; s: string; description: string }>> {
    return SODICK_TECH_TABLE;
  }
}

export const wedmPostSodickEngine = new WEDMPostSodickEngine();
