/**
 * WEDMPostMitsubishiEngine — Wire-EDM post processor for Mitsubishi Electric
 * wire-cut controls (MELDAS / MELCUT), covering the FA-series (FA10, FA20,
 * FA20S, FA20V, FA30V) and the MV-series (MV1200R, MV2400R).
 *
 * Vendor references:
 *   • Mitsubishi Electric MELCUT-FA10 Programming Manual, rev. 2012
 *   • MV-Series "Tubular Shaft Motor" operator manual, 2018
 *   • ISO 6983-1 / EIA RS-274-D (G-code superset)
 *
 * Dialect highlights the generic router did NOT capture:
 *   • E-code power-supply tables: E000–E999, stored in the PE file on the
 *     MELCUT control. The on/off pulse width and peak current are selected
 *     by the E-number, not by spelling out ON/OFF in a comment.
 *   • H-code wire-offset register: H01–H99 — the machinist loads the radius
 *     into register Hnn and the program references it with G41/G42 Hnn.
 *   • M80/M81 flushing upper/lower jets.
 *   • T-codes T84 / T85 for anti-electrolysis power supply.
 *
 * MS-P1.5-ONESHOT/U-P1.5-OS-04
 */

import {
  IWEDMPostEngine,
  WEDMController,
  WEDMOperation,
  WEDMParsedPlan,
  WEDMPassId,
  WEDMPostInput,
  WEDMPostOutput,
  formatCoord,
  passDefaults,
} from "./WEDMPostTypes.js";

// ── Mitsubishi E-table mapping (pass → E-code) ─────────────────────────────
// Source: MELCUT-FA10 PE file defaults for 25 mm D2 tool steel, 0.25 mm wire.
// These are canonical tech-table references, not inlined power numbers.
const MITSUBISHI_E_TABLE: Record<WEDMPassId, { e: string; description: string }> = {
  rough:  { e: "E110", description: "Rough main cut (25 mm steel, 0.25mm Cu)" },
  skim1:  { e: "E120", description: "1st skim (stock 0.08 mm)" },
  skim2:  { e: "E130", description: "2nd skim (stock 0.03 mm)" },
  skim3:  { e: "E140", description: "Final skim (stock 0.008 mm, Ra ≤ 1.2 µm)" },
};

const MITSUBISHI_H_OFFSET_START = 1;       // H01 = first register
const MITSUBISHI_COORD_DECIMALS_MM = 3;    // MELDAS default μm precision
const MITSUBISHI_COORD_DECIMALS_IN = 5;    // 0.00001 inch precision

export class WEDMPostMitsubishiEngine implements IWEDMPostEngine {
  readonly name = "WEDMPostMitsubishiEngine";
  readonly version = "1.0.0";
  readonly supportedControllers: readonly WEDMController[] = ["mitsubishi_fa", "mitsubishi_mv"];
  readonly manufacturer = "Mitsubishi Electric";

  /**
   * Resolve the vendor-friendly dialect name for header comments.
   */
  dialectNameFor(controller: WEDMController): string {
    if (controller === "mitsubishi_fa") return "Mitsubishi FA";
    if (controller === "mitsubishi_mv") return "Mitsubishi MV";
    return "Mitsubishi";
  }

  /**
   * Generate Mitsubishi-dialect G-code for the supplied WEDM plan.
   *
   * @param input   Controller + plan (operations, material, thickness…)
   * @returns       Emitted program with per-operation warnings and the
   *                dialect-specific E/H-register metadata filled in.
   */
  generate(input: WEDMPostInput): WEDMPostOutput {
    const controller = input.controller;
    if (!this.supportedControllers.includes(controller)) {
      return {
        success: false,
        controller,
        dialect_name: "UNKNOWN",
        gcode_lines: [],
        gcode_text: "",
        line_count: 0,
        operation_count: 0,
        warnings: [`WEDMPostMitsubishiEngine does not support controller '${controller}'`],
        dialect_specific: {},
      };
    }

    const lines: string[] = [];
    const warnings: string[] = [];
    const dialectName = this.dialectNameFor(controller);
    const isImperial = input.units === "imperial";
    const decimals = isImperial ? MITSUBISHI_COORD_DECIMALS_IN : MITSUBISHI_COORD_DECIMALS_MM;
    const progNum = (input.program_number ?? "0001").padStart(4, "0");

    // ── Header ──
    lines.push("%");
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "WIRE EDM PROGRAM"})`);
    lines.push(`(CONTROLLER: ${dialectName} MELDAS/MELCUT)`);
    lines.push(`(MATERIAL: ${input.material ?? "TOOL STEEL"} THICKNESS: ${input.thickness_mm.toFixed(2)}mm)`);
    lines.push(`(WIRE: ${(input.wire_diameter_mm ?? 0.25).toFixed(2)}mm)`);
    lines.push(`(GENERATED BY PRISM WEDM POST — MITSUBISHI DIALECT v${this.version})`);
    lines.push("");

    // ── Setup block ──
    const unitCode = isImperial ? "G20" : "G21";
    const unitLabel = isImperial ? "INCH" : "METRIC";
    lines.push(`G90 ${unitCode} (ABSOLUTE ${unitLabel})`);
    lines.push("G92 X0 Y0 (SET PART ZERO)");
    lines.push("T84 (ANTI-ELECTROLYSIS ON)");

    // ── Thickness sanity ──
    if (input.thickness_mm > 100) {
      warnings.push(`Thickness ${input.thickness_mm}mm exceeds 100mm — verify flushing pressure on FA/MV`);
    }
    if (input.thickness_mm <= 0 || !Number.isFinite(input.thickness_mm)) {
      warnings.push(`Invalid thickness ${input.thickness_mm}mm — treating as 10mm reference`);
    }

    // ── Operations ──
    const eCodesUsed: string[] = [];
    const hRegistersUsed: string[] = [];

    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      const d = passDefaults(op.pass);
      const power = op.power_setting ?? d.power;
      const onTime = op.on_time_us ?? d.on_us;
      const offTime = op.off_time_us ?? d.off_us;
      const wireSpeed = op.wire_speed_m_min ?? d.wire_speed;
      const wireTension = op.wire_tension_g ?? d.wire_tension;
      const offset = op.offset_mm ?? 0.15;
      const direction = op.offset_direction ?? "left";
      const autoThread = op.auto_thread !== false;
      const submerged = op.submerged !== false;

      const hRegister = `H${String(MITSUBISHI_H_OFFSET_START + i).padStart(2, "0")}`;
      const eEntry = MITSUBISHI_E_TABLE[op.pass];
      hRegistersUsed.push(hRegister);
      eCodesUsed.push(eEntry.e);

      lines.push("");
      lines.push(`(--- PASS ${i + 1}: ${op.pass.toUpperCase()} ${op.type.toUpperCase()} ---)`);
      lines.push(`${eEntry.e} (${eEntry.description})`);
      lines.push(`(PWR=${power} TON=${onTime}us TOFF=${offTime}us WF=${wireSpeed}m/min WT=${wireTension}g)`);

      // Offset register load. Mitsubishi stores compensation in Hnn.
      lines.push(`#${hRegister.substring(1)}=${(offset * 1000).toFixed(0)} (OFFSET ${offset.toFixed(3)}mm → ${hRegister})`);

      if (autoThread) {
        lines.push("M6 (AUTO WIRE THREAD)");
      }
      if (submerged) {
        lines.push("M28 (SUBMERGE ON)");
        lines.push("M80 (UPPER JET ON)");
        lines.push("M81 (LOWER JET ON)");
      }

      // Start position (rapid) before compensation-on move.
      if (op.start_x !== undefined && op.start_y !== undefined) {
        const x = formatCoord(op.start_x, isImperial, decimals);
        const y = formatCoord(op.start_y, isImperial, decimals);
        lines.push(`G0 X${x} Y${y} (APPROACH)`);
      }

      // Compensation-on uses G41 (left) or G42 (right) with Hnn register.
      const offsetCode = direction === "right" ? "G42" : "G41";
      lines.push(`${offsetCode} ${hRegister} (COMP ON ${direction.toUpperCase()})`);

      // Taper setup uses G51 with A-word.
      if (op.type === "taper" && typeof op.taper_angle_deg === "number") {
        const angle = op.taper_angle_deg;
        lines.push(`G51 A${angle.toFixed(3)} (TAPER ON ${angle.toFixed(3)} deg)`);
        if (op.taper_height_mm !== undefined) {
          lines.push(`(TAPER HEIGHT ${op.taper_height_mm.toFixed(2)}mm)`);
        }
      }

      // Profile moves — Mitsubishi supports X/Y lower + U/V upper for 4-axis cuts.
      if (op.profile_points && op.profile_points.length > 0) {
        for (const pt of op.profile_points) {
          const x = formatCoord(pt.x, isImperial, decimals);
          const y = formatCoord(pt.y, isImperial, decimals);
          let line = `G1 X${x} Y${y}`;
          if (pt.u !== undefined && pt.v !== undefined) {
            const u = formatCoord(pt.u, isImperial, decimals);
            const v = formatCoord(pt.v, isImperial, decimals);
            line += ` U${u} V${v}`;
          }
          lines.push(line);
        }
      } else {
        warnings.push(`Pass ${i + 1}: no profile_points — emitted placeholder`);
        lines.push("(... profile geometry missing ...)");
      }

      if (op.type === "taper") {
        lines.push("G50 (TAPER OFF)");
      }

      lines.push("G40 (CANCEL COMP)");
      lines.push("M7 (WIRE CUT)");
      if (submerged) {
        lines.push("M81 (LOWER JET OFF)");
        lines.push("M80 (UPPER JET OFF)");
        lines.push("M29 (SUBMERGE OFF)");
      }
    }

    // ── Footer ──
    lines.push("");
    lines.push("G92 X0 Y0 (HOME)");
    lines.push("T85 (ANTI-ELECTROLYSIS OFF)");
    lines.push("M30");
    lines.push("%");

    const gcodeText = lines.join("\n");

    return {
      success: true,
      controller,
      dialect_name: dialectName,
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      operation_count: input.operations.length,
      warnings,
      dialect_specific: {
        manufacturer: this.manufacturer,
        uses_e_codes: true,
        uses_c_codes: false,
        e_codes_used: eCodesUsed,
        h_registers_used: hRegistersUsed,
        anti_electrolysis: true,
        wire_thread_code: "M6",
        wire_cut_code: "M7",
      },
    };
  }

  /**
   * Parse an emitted Mitsubishi program back into a structured plan so a
   * round-trip equivalence check can be performed (OS-04 exit criterion 4).
   *
   * This does not attempt to reconstruct every field of the original plan —
   * only the structural fields that every dialect shares: program number,
   * number of operations, pass-id (from the E-table), power class, offset,
   * taper angle, submerged flag, and the point count per pass.
   */
  parse(gcode: string): WEDMParsedPlan {
    const plan: WEDMParsedPlan = {
      operations: [],
      controller_hint: "mitsubishi_fa",
    };

    const progMatch = gcode.match(/^O(\d+)/m);
    if (progMatch) plan.program_number = progMatch[1];

    // Split into operation blocks on `(--- PASS` markers.
    const blocks = gcode.split(/\(--- PASS \d+:/).slice(1);
    for (const block of blocks) {
      let pass: WEDMPassId | undefined;
      // Recover pass from the E-code.
      const eMatch = block.match(/^\s*([A-Z]+)\s*([A-Z0-9]+)/);
      const eCodeMatch = block.match(/\bE(\d{3})\b/);
      if (eCodeMatch) {
        const eCode = `E${eCodeMatch[1]}`;
        for (const k of Object.keys(MITSUBISHI_E_TABLE) as WEDMPassId[]) {
          if (MITSUBISHI_E_TABLE[k].e === eCode) { pass = k; break; }
        }
      }
      if (!pass && eMatch) {
        const label = eMatch[1].toLowerCase();
        if (label === "rough" || label === "skim1" || label === "skim2" || label === "skim3") pass = label;
      }

      const powerMatch = block.match(/PWR=(\d+)/);
      const onMatch = block.match(/TON=(\d+)/);
      const offMatch = block.match(/TOFF=(\d+)/);
      const offsetMatch = block.match(/OFFSET\s+([\d.]+)mm/);
      const dirIsRight = /G42/.test(block);
      const submerged = /M28\s*\(SUBMERGE ON\)/.test(block);
      const taperMatch = block.match(/G51 A([-\d.]+)/);
      const pointMatches = block.match(/\bG1 X/g);

      plan.operations.push({
        pass,
        power: powerMatch ? Number(powerMatch[1]) : undefined,
        on_us: onMatch ? Number(onMatch[1]) : undefined,
        off_us: offMatch ? Number(offMatch[1]) : undefined,
        offset_mm: offsetMatch ? Number(offsetMatch[1]) : undefined,
        offset_direction: dirIsRight ? "right" : "left",
        submerged,
        taper_angle_deg: taperMatch ? Number(taperMatch[1]) : undefined,
        point_count: pointMatches ? pointMatches.length : 0,
      });
    }

    return plan;
  }

  /**
   * Expose the E-table so the router (and tests) can introspect the tech
   * references this engine will emit.
   */
  getETable(): Readonly<Record<WEDMPassId, { e: string; description: string }>> {
    return MITSUBISHI_E_TABLE;
  }
}

export const wedmPostMitsubishiEngine = new WEDMPostMitsubishiEngine();
