/**
 * WEDMThermalReleaseGateEngine — Thermal Balance Validation for S(x)
 *
 * Validates thermal balance in the cut zone using ASM Handbook Vol. 16
 * thermal conductivity model k(T). NOT Johnson-Cook (which is for
 * plastic deformation, not EDM spark thermal release).
 *
 * Wire EDM thermal concerns:
 * - Heat-affected zone (HAZ) depth
 * - Recast layer formation
 * - Thermal cracking
 * - Wire temperature (affects tension and wear)
 *
 * The energy balance:
 *   Q_spark = Q_wire + Q_workpiece + Q_dielectric + Q_debris
 *
 * Reference: ASM Handbook Vol. 16, Chapter 14 "Wire EDM"
 *            Table 14.2 - Thermal properties of common EDM materials
 *
 * @module WEDMThermalReleaseGateEngine
 * MS-P2.5-SAFETY/U-P2.5-SAFE-05
 */

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type EDMMaterial =
  | "steel_1045"
  | "steel_d2"
  | "steel_h13"
  | "steel_m2"
  | "tungsten_carbide"
  | "copper"
  | "aluminum_6061"
  | "titanium_ti6al4v"
  | "inconel_718"
  | "graphite";

export interface ThermalInput {
  /** Heat generated by sparks per unit time (Joules) */
  heat_release_J: number;
  /** Cooling capacity of dielectric system (Joules) */
  cooling_capacity_J: number;
  /** Workpiece material */
  material: EDMMaterial;
  /** Workpiece thickness (mm) */
  thickness_mm: number;
  /** On-time (microseconds) - affects energy per spark */
  on_time_us?: number;
  /** Off-time (microseconds) - affects cooling between sparks */
  off_time_us?: number;
  /** Measured recast depth (micrometers) - if available */
  recast_depth_um?: number;
  /** Maximum allowable recast depth (micrometers) */
  max_recast_um?: number;
}

export interface MaterialThermalProps {
  /** Thermal conductivity k (W/m·K) at room temperature */
  k_W_mK: number;
  /** Specific heat capacity Cp (J/kg·K) */
  cp_J_kgK: number;
  /** Density (kg/m³) */
  density_kg_m3: number;
  /** Melting point (°C) */
  melting_C: number;
  /** Thermal diffusivity α (m²/s) = k / (ρ·Cp) */
  alpha_m2_s: number;
  /** Typical max recast layer depth for this material (µm) */
  typical_recast_um: number;
}

export interface ThermalGateResult {
  success: boolean;
  pass: boolean;
  heat_release_J: number;
  cooling_capacity_J: number;
  thermal_ratio: number;
  estimated_recast_um: number;
  max_recast_um: number;
  material: EDMMaterial;
  material_props: MaterialThermalProps;
  hard_block: boolean;
  warnings: string[];
  summary: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// ASM HANDBOOK VOL. 16 THERMAL PROPERTIES
// ═══════════════════════════════════════════════════════════════════════════

const MATERIAL_THERMAL_PROPS: Record<EDMMaterial, MaterialThermalProps> = {
  steel_1045: {
    k_W_mK: 51.9,
    cp_J_kgK: 486,
    density_kg_m3: 7850,
    melting_C: 1520,
    alpha_m2_s: 13.6e-6,
    typical_recast_um: 15,
  },
  steel_d2: {
    k_W_mK: 20.0,
    cp_J_kgK: 460,
    density_kg_m3: 7700,
    melting_C: 1421,
    alpha_m2_s: 5.6e-6,
    typical_recast_um: 20,
  },
  steel_h13: {
    k_W_mK: 24.3,
    cp_J_kgK: 460,
    density_kg_m3: 7750,
    melting_C: 1427,
    alpha_m2_s: 6.8e-6,
    typical_recast_um: 18,
  },
  steel_m2: {
    k_W_mK: 26.0,
    cp_J_kgK: 420,
    density_kg_m3: 8160,
    melting_C: 1230,
    alpha_m2_s: 7.6e-6,
    typical_recast_um: 22,
  },
  tungsten_carbide: {
    k_W_mK: 84.0,
    cp_J_kgK: 292,
    density_kg_m3: 15630,
    melting_C: 2870,
    alpha_m2_s: 18.4e-6,
    typical_recast_um: 8,
  },
  copper: {
    k_W_mK: 401.0,
    cp_J_kgK: 385,
    density_kg_m3: 8960,
    melting_C: 1085,
    alpha_m2_s: 116e-6,
    typical_recast_um: 5,
  },
  aluminum_6061: {
    k_W_mK: 167.0,
    cp_J_kgK: 896,
    density_kg_m3: 2700,
    melting_C: 582,
    alpha_m2_s: 69e-6,
    typical_recast_um: 3,
  },
  titanium_ti6al4v: {
    k_W_mK: 6.7,
    cp_J_kgK: 526,
    density_kg_m3: 4430,
    melting_C: 1604,
    alpha_m2_s: 2.9e-6,
    typical_recast_um: 30,
  },
  inconel_718: {
    k_W_mK: 11.4,
    cp_J_kgK: 435,
    density_kg_m3: 8190,
    melting_C: 1260,
    alpha_m2_s: 3.2e-6,
    typical_recast_um: 35,
  },
  graphite: {
    k_W_mK: 130.0,
    cp_J_kgK: 710,
    density_kg_m3: 1750,
    melting_C: 3650,
    alpha_m2_s: 104e-6,
    typical_recast_um: 2,
  },
};

// ═══════════════════════════════════════════════════════════════════════════
// ENGINE
// ═══════════════════════════════════════════════════════════════════════════

export class WEDMThermalReleaseGateEngine {
  /**
   * Evaluate thermal balance for S(x) integration
   */
  evaluate(input: ThermalInput): ThermalGateResult {
    const props = MATERIAL_THERMAL_PROPS[input.material];
    const warnings: string[] = [];

    // Calculate thermal ratio (cooling / heat)
    const thermal_ratio = input.cooling_capacity_J / input.heat_release_J;

    // Estimate recast layer depth if not provided
    const estimated_recast_um = input.recast_depth_um ?? this.estimateRecastDepth(
      input.heat_release_J,
      input.cooling_capacity_J,
      props,
      input.on_time_us,
      input.off_time_us
    );

    // Determine max allowable recast
    const max_recast_um = input.max_recast_um ?? (props.typical_recast_um * 1.5);

    // Check thermal balance
    const thermalBalanceOK = thermal_ratio >= 0.8; // At least 80% of heat must be removed
    const recastOK = estimated_recast_um <= max_recast_um;
    const pass = thermalBalanceOK && recastOK;

    // Generate warnings
    if (thermal_ratio < 1.0 && thermal_ratio >= 0.8) {
      warnings.push(`Thermal ratio ${thermal_ratio.toFixed(2)} is marginal (< 1.0)`);
    }

    if (thermal_ratio < 0.8) {
      warnings.push(`CRITICAL: Thermal ratio ${thermal_ratio.toFixed(2)} below 0.8 - heat buildup risk`);
    }

    if (estimated_recast_um > props.typical_recast_um && estimated_recast_um <= max_recast_um) {
      warnings.push(`Recast depth ${estimated_recast_um.toFixed(1)}µm exceeds typical ${props.typical_recast_um}µm for ${input.material}`);
    }

    // Check for low thermal conductivity materials
    if (props.k_W_mK < 15) {
      warnings.push(`Low conductivity material (${props.k_W_mK} W/m·K) - use shorter on-time and longer off-time`);
    }

    // Check on/off time ratio if provided
    if (input.on_time_us && input.off_time_us) {
      const dutyCycle = input.on_time_us / (input.on_time_us + input.off_time_us);
      if (dutyCycle > 0.5 && props.k_W_mK < 30) {
        warnings.push(`High duty cycle (${(dutyCycle * 100).toFixed(0)}%) on low-conductivity material`);
      }
    }

    return {
      success: true,
      pass,
      heat_release_J: input.heat_release_J,
      cooling_capacity_J: input.cooling_capacity_J,
      thermal_ratio,
      estimated_recast_um,
      max_recast_um,
      material: input.material,
      material_props: props,
      hard_block: !pass,
      warnings,
      summary: this.buildSummary(pass, thermal_ratio, estimated_recast_um, max_recast_um, input.material, warnings),
    };
  }

  /**
   * Quick check for S(x) integration
   */
  quickCheckForSx(
    heat_release_J: number,
    cooling_capacity_J: number,
    recast_depth_um?: number,
    max_recast_um?: number
  ): {
    pass: boolean;
    heat_release_J: number;
    cooling_capacity_J: number;
    recast_depth_um: number;
    max_recast_um: number;
  } {
    // Use steel_d2 as default for quick check
    const result = this.evaluate({
      heat_release_J,
      cooling_capacity_J,
      material: "steel_d2",
      thickness_mm: 25,
      recast_depth_um,
      max_recast_um,
    });

    return {
      pass: result.pass,
      heat_release_J: result.heat_release_J,
      cooling_capacity_J: result.cooling_capacity_J,
      recast_depth_um: result.estimated_recast_um,
      max_recast_um: result.max_recast_um,
    };
  }

  /**
   * Get thermal properties for a material
   */
  getMaterialProps(material: EDMMaterial): MaterialThermalProps {
    return MATERIAL_THERMAL_PROPS[material];
  }

  /**
   * List all supported materials
   */
  listMaterials(): EDMMaterial[] {
    return Object.keys(MATERIAL_THERMAL_PROPS) as EDMMaterial[];
  }

  /**
   * Calculate recommended cooling capacity for given heat release
   */
  recommendCoolingCapacity(heat_release_J: number, safety_factor: number = 1.2): number {
    return heat_release_J * safety_factor;
  }

  /**
   * Calculate max allowable on-time for a material based on thermal diffusivity
   */
  recommendMaxOnTime(material: EDMMaterial, target_recast_um: number = 10): number {
    const props = MATERIAL_THERMAL_PROPS[material];
    // Simplified: t ~ (depth²) / (4 * α)
    const depth_m = target_recast_um * 1e-6;
    const t_seconds = (depth_m * depth_m) / (4 * props.alpha_m2_s);
    return t_seconds * 1e6; // Return in microseconds
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIVATE HELPERS
  // ═══════════════════════════════════════════════════════════════════════════

  private estimateRecastDepth(
    heat_J: number,
    cooling_J: number,
    props: MaterialThermalProps,
    on_time_us?: number,
    off_time_us?: number
  ): number {
    // Simplified thermal penetration model
    // Recast depth ≈ 2 * sqrt(α * t) where t is effective heating time

    // Default timing if not provided
    const t_on = (on_time_us ?? 10) * 1e-6; // Convert to seconds
    const t_off = (off_time_us ?? 50) * 1e-6;
    const duty_cycle = t_on / (t_on + t_off);

    // Effective heating time
    const t_eff = t_on * (1 - cooling_J / heat_J);
    const t_heating = Math.max(0, t_eff);

    // Thermal penetration depth (meters)
    const depth_m = 2 * Math.sqrt(props.alpha_m2_s * t_heating);

    // Scale by duty cycle and convert to micrometers
    const recast_um = depth_m * 1e6 * duty_cycle * 0.5; // 0.5 factor for recast vs HAZ

    // Clamp to realistic range based on material
    return Math.min(Math.max(recast_um, 1), props.typical_recast_um * 3);
  }

  private buildSummary(
    pass: boolean,
    thermal_ratio: number,
    recast_um: number,
    max_recast_um: number,
    material: EDMMaterial,
    warnings: string[]
  ): string {
    if (pass) {
      const warningNote = warnings.length > 0 ? ` (${warnings.length} warning(s))` : "";
      return `PASS: Thermal balance OK. Ratio: ${thermal_ratio.toFixed(2)}, Recast: ${recast_um.toFixed(1)}µm <= ${max_recast_um.toFixed(1)}µm (${material})${warningNote}`;
    }

    const issues: string[] = [];
    if (thermal_ratio < 0.8) {
      issues.push(`thermal ratio ${thermal_ratio.toFixed(2)} < 0.8`);
    }
    if (recast_um > max_recast_um) {
      issues.push(`recast ${recast_um.toFixed(1)}µm > ${max_recast_um.toFixed(1)}µm max`);
    }

    return `HARD BLOCK: Thermal imbalance. ${issues.join(", ")}. Risk of excessive HAZ and recast layer.`;
  }
}

export const wedmThermalReleaseGateEngine = new WEDMThermalReleaseGateEngine();
