/**
 * WEDMPostFanucEngine — Wire-EDM post processor for Fanuc ROBOCUT
 * controls, the α-CiA / α-CiB / α-C600iB generation. Fanuc's ROBOCUT is
 * driven by a 31i-WB series CNC and uses a pure ISO-G dialect with
 * parameter-register-based condition selection.
 *
 * Vendor references:
 *   • Fanuc "ROBOCUT α-CiB Operator's Manual" B-72794EN rev. 2019
 *   • Fanuc "Custom Macro Common Variables" section 7 (#500–#999)
 *   • ISO 6983-1 (universal G-code)
 *
 * Dialect highlights the generic router did NOT capture:
 *   • Fanuc does NOT use a dedicated E-code. Conditions are loaded into
 *     Custom-Macro common variables (#500–#599 — per-program, retained on
 *     power-off). Each pass writes:
 *       #501 = power-index
 *       #502 = on-time µs
 *       #503 = off-time µs
 *       #504 = wire-speed m/min
 *       #505 = wire-tension g
 *       #506 = offset µm
 *     and then calls subprogram O9010 via `G65 P9010`.
 *   • M60 / M61 wire thread / cut (not M6/M7 as on Mitsubishi).
 *   • Submerged M50 / M51.
 *   • Taper commands: G51.1 X<deg> on, G50.1 off (Fanuc decimal variant).
 *   • Offset uses Dnn as on other ISO dialects.
 *
 * MS-P1.5-ONESHOT/U-P1.5-OS-04
 */

import {
  IWEDMPostEngine,
  WEDMController,
  WEDMParsedPlan,
  WEDMPassId,
  WEDMPostInput,
  WEDMPostOutput,
  formatCoord,
  passDefaults,
} from "./WEDMPostTypes.js";

/**
 * Fanuc does not have a canonical "E-table". We synthesize a condition
 * label per pass for operator readability in comments only. Real Fanuc
 * machines read conditions from #500-range macro variables (see header).
 */
const FANUC_CONDITION_LABELS: Record<WEDMPassId, string> = {
  rough: "COND=ROUGH (#500 SERIES)",
  skim1: "COND=SKIM1 (#500 SERIES)",
  skim2: "COND=SKIM2 (#500 SERIES)",
  skim3: "COND=SKIM3 (#500 SERIES)",
};

const FANUC_COORD_DECIMALS_MM = 3;
const FANUC_COORD_DECIMALS_IN = 5;

export class WEDMPostFanucEngine implements IWEDMPostEngine {
  readonly name = "WEDMPostFanucEngine";
  readonly version = "1.0.0";
  readonly supportedControllers: readonly WEDMController[] = ["fanuc_robocut"];
  readonly manufacturer = "Fanuc";

  dialectNameFor(controller: WEDMController): string {
    if (controller === "fanuc_robocut") return "Fanuc ROBOCUT";
    return "Fanuc";
  }

  generate(input: WEDMPostInput): WEDMPostOutput {
    const controller = input.controller;
    if (!this.supportedControllers.includes(controller)) {
      return {
        success: false,
        controller,
        dialect_name: "UNKNOWN",
        gcode_lines: [],
        gcode_text: "",
        line_count: 0,
        operation_count: 0,
        warnings: [`WEDMPostFanucEngine does not support controller '${controller}'`],
        dialect_specific: {},
      };
    }

    const lines: string[] = [];
    const warnings: string[] = [];
    const dialectName = this.dialectNameFor(controller);
    const isImperial = input.units === "imperial";
    const decimals = isImperial ? FANUC_COORD_DECIMALS_IN : FANUC_COORD_DECIMALS_MM;
    const progNum = (input.program_number ?? "0001").padStart(4, "0");

    // ── Header ──
    lines.push("%");
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "WIRE EDM PROGRAM"})`);
    lines.push(`(CONTROLLER: ${dialectName} 31i-WB)`);
    lines.push(`(MATERIAL: ${input.material ?? "TOOL STEEL"} THICKNESS: ${input.thickness_mm.toFixed(2)}mm)`);
    lines.push(`(WIRE: ${(input.wire_diameter_mm ?? 0.25).toFixed(2)}mm)`);
    lines.push(`(CONDITIONS LOADED INTO MACRO VARS #501-#506 PER PASS)`);
    lines.push(`(GENERATED BY PRISM WEDM POST — FANUC DIALECT v${this.version})`);
    lines.push("");

    const unitCode = isImperial ? "G20" : "G21";
    const unitLabel = isImperial ? "INCH" : "METRIC";
    lines.push(`G90 ${unitCode} (ABSOLUTE ${unitLabel})`);
    lines.push("G92 X0 Y0 (SET WORK COORDS)");

    if (input.thickness_mm > 300) {
      warnings.push(`Thickness ${input.thickness_mm}mm exceeds α-C600iB Z-travel — verify machine`);
    }
    if (input.thickness_mm <= 0 || !Number.isFinite(input.thickness_mm)) {
      warnings.push(`Invalid thickness ${input.thickness_mm}mm`);
    }

    const macroVarsWritten: string[] = [];
    const dRegistersUsed: string[] = [];

    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      const d = passDefaults(op.pass);
      const power = op.power_setting ?? d.power;
      const onTime = op.on_time_us ?? d.on_us;
      const offTime = op.off_time_us ?? d.off_us;
      const wireSpeed = op.wire_speed_m_min ?? d.wire_speed;
      const wireTension = op.wire_tension_g ?? d.wire_tension;
      const offset = op.offset_mm ?? 0.15;
      const direction = op.offset_direction ?? "left";
      const autoThread = op.auto_thread !== false;
      const submerged = op.submerged !== false;

      const offsetUm = Math.round(offset * 1000);
      const dReg = `D${String(i + 1).padStart(2, "0")}`;
      dRegistersUsed.push(dReg);

      lines.push("");
      lines.push(`(--- PASS ${i + 1}: ${op.pass.toUpperCase()} ${op.type.toUpperCase()} ${FANUC_CONDITION_LABELS[op.pass]} ---)`);
      // Fanuc macro-variable condition loading block.
      lines.push(`#501=${power}  (POWER INDEX)`);
      lines.push(`#502=${onTime}  (ON-TIME us)`);
      lines.push(`#503=${offTime}  (OFF-TIME us)`);
      lines.push(`#504=${wireSpeed}  (WIRE SPEED m/min)`);
      lines.push(`#505=${wireTension}  (WIRE TENSION g)`);
      lines.push(`#506=${offsetUm}  (OFFSET um)`);
      lines.push("G65 P9010 (APPLY CONDITION SUBPROGRAM)");
      macroVarsWritten.push(`#501=${power}`, `#506=${offsetUm}`);

      if (autoThread) {
        lines.push("M60 (AUTO WIRE THREAD)");
      }
      if (submerged) {
        lines.push("M50 (SUBMERGE ON)");
      }

      if (op.start_x !== undefined && op.start_y !== undefined) {
        const x = formatCoord(op.start_x, isImperial, decimals);
        const y = formatCoord(op.start_y, isImperial, decimals);
        lines.push(`G0 X${x} Y${y} (APPROACH)`);
      }

      const offsetCode = direction === "right" ? "G42" : "G41";
      lines.push(`${offsetCode} ${dReg} (COMP ON ${direction.toUpperCase()} ${offset.toFixed(3)}mm)`);

      if (op.type === "taper" && typeof op.taper_angle_deg === "number") {
        lines.push(`G51.1 X${op.taper_angle_deg.toFixed(3)} (TAPER ON ${op.taper_angle_deg.toFixed(3)}deg)`);
        if (typeof op.taper_height_mm === "number") {
          lines.push(`(TAPER HEIGHT ${op.taper_height_mm.toFixed(2)}mm)`);
        }
      }

      if (op.profile_points && op.profile_points.length > 0) {
        for (const pt of op.profile_points) {
          const x = formatCoord(pt.x, isImperial, decimals);
          const y = formatCoord(pt.y, isImperial, decimals);
          let line = `G1 X${x} Y${y}`;
          if (pt.u !== undefined && pt.v !== undefined) {
            const u = formatCoord(pt.u, isImperial, decimals);
            const v = formatCoord(pt.v, isImperial, decimals);
            line += ` U${u} V${v}`;
          }
          lines.push(line);
        }
      } else {
        warnings.push(`Pass ${i + 1}: no profile_points — emitted placeholder`);
        lines.push("(... profile geometry missing ...)");
      }

      if (op.type === "taper") {
        lines.push("G50.1 (TAPER OFF)");
      }

      lines.push("G40 (CANCEL COMP)");
      lines.push("M61 (WIRE CUT)");
      if (submerged) {
        lines.push("M51 (SUBMERGE OFF)");
      }
    }

    // ── Footer ──
    lines.push("");
    lines.push("G92 X0 Y0 (HOME)");
    lines.push("M30");
    lines.push("%");

    const gcodeText = lines.join("\n");

    return {
      success: true,
      controller,
      dialect_name: dialectName,
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      operation_count: input.operations.length,
      warnings,
      dialect_specific: {
        manufacturer: this.manufacturer,
        uses_e_codes: false,
        uses_c_codes: false,
        uses_macro_vars: true,
        macro_vars_written: macroVarsWritten,
        d_registers_used: dRegistersUsed,
        condition_subprogram: "O9010",
        wire_thread_code: "M60",
        wire_cut_code: "M61",
      },
    };
  }

  parse(gcode: string): WEDMParsedPlan {
    const plan: WEDMParsedPlan = {
      operations: [],
      controller_hint: "fanuc_robocut",
    };

    const progMatch = gcode.match(/^O(\d+)/m);
    if (progMatch) plan.program_number = progMatch[1];

    const blocks = gcode.split(/\(--- PASS \d+:/).slice(1);
    for (const block of blocks) {
      let pass: WEDMPassId | undefined;
      // Recover pass from the COND= label.
      if (/COND=ROUGH/.test(block)) pass = "rough";
      else if (/COND=SKIM1/.test(block)) pass = "skim1";
      else if (/COND=SKIM2/.test(block)) pass = "skim2";
      else if (/COND=SKIM3/.test(block)) pass = "skim3";

      const powerMatch = block.match(/#501=(\d+)/);
      const onMatch = block.match(/#502=(\d+)/);
      const offMatch = block.match(/#503=(\d+)/);
      const offsetUmMatch = block.match(/#506=(\d+)/);
      const dirIsRight = /G42/.test(block);
      const submerged = /M50\s*\(SUBMERGE ON\)/.test(block);
      const taperMatch = block.match(/G51\.1 X([-\d.]+)/);
      const pointMatches = block.match(/\bG1 X/g);

      plan.operations.push({
        pass,
        power: powerMatch ? Number(powerMatch[1]) : undefined,
        on_us: onMatch ? Number(onMatch[1]) : undefined,
        off_us: offMatch ? Number(offMatch[1]) : undefined,
        offset_mm: offsetUmMatch ? Number(offsetUmMatch[1]) / 1000 : undefined,
        offset_direction: dirIsRight ? "right" : "left",
        submerged,
        taper_angle_deg: taperMatch ? Number(taperMatch[1]) : undefined,
        point_count: pointMatches ? pointMatches.length : 0,
      });
    }

    return plan;
  }

  getConditionLabels(): Readonly<Record<WEDMPassId, string>> {
    return FANUC_CONDITION_LABELS;
  }
}

export const wedmPostFanucEngine = new WEDMPostFanucEngine();
