/**
 * WEDMPostAgieEngine — Wire-EDM post processor for AgieCharmilles (GF
 * Machining Solutions) wire EDMs. Covers the CUT series (CUT P 350, CUT
 * P 550, CUT P 800, CUT E) and the Charm series legacy control (FW-series
 * machines such as FW1P, FW2U).
 *
 * Vendor references:
 *   • GF Machining Solutions "Vision 5 Programmer's Handbook" rev. 2017
 *   • AgieCharmilles "IPG / TPG programming manual" (ISO-GF form)
 *   • DIN 66025 (GF uses DIN-G-code conventions)
 *
 * Dialect highlights the generic router did NOT capture:
 *   • Tech table references use the *TEC* command: `TEC NNNN` selects the
 *     pulse description P00–P20 plus gap control. The generic router used
 *     a `C<NNN>` string; Agie's TEC form is emitted here.
 *   • Program frame: `%PM` header, `M17` (end + rewind) footer — GF legacy
 *     convention retained even on CUT-series for compatibility.
 *   • Offset is expressed in tenths-of-micron using the `.O` contour
 *     attribute line: e.g. `.O = 152` (152 × 0.001 mm = 0.152 mm).
 *   • Taper uses GF's unique `G08 A<deg>` on (G09 to cancel), distinct
 *     from ISO's G51/G50.
 *   • M20/M21 AWT (automatic wire threader).
 *   • CIRU / CORO corner control keywords on top of TEC.
 *
 * MS-P1.5-ONESHOT/U-P1.5-OS-04
 */

import {
  IWEDMPostEngine,
  WEDMController,
  WEDMParsedPlan,
  WEDMPassId,
  WEDMPostInput,
  WEDMPostOutput,
  formatCoord,
  passDefaults,
} from "./WEDMPostTypes.js";

// Source: Vision 5 default TEC table for 25 mm tool steel, 0.25 mm brass wire.
const AGIE_TEC_TABLE: Record<WEDMPassId, { tec: string; pulse: string; description: string }> = {
  rough: { tec: "TEC 0255", pulse: "P12", description: "ROUGH main, 25mm tool steel, 0.25mm brass" },
  skim1: { tec: "TEC 0270", pulse: "P08", description: "SKIM1 (stock 0.08mm)" },
  skim2: { tec: "TEC 0285", pulse: "P04", description: "SKIM2 mirror, Ra ≤ 1.0µm" },
  skim3: { tec: "TEC 0295", pulse: "P01", description: "SKIM3 ultra, Ra ≤ 0.3µm" },
};

const AGIE_COORD_DECIMALS_MM = 3;
const AGIE_COORD_DECIMALS_IN = 5;

export class WEDMPostAgieEngine implements IWEDMPostEngine {
  readonly name = "WEDMPostAgieEngine";
  readonly version = "1.0.0";
  readonly supportedControllers: readonly WEDMController[] = ["agie_cut", "agie_charm"];
  readonly manufacturer = "GF Machining Solutions";

  dialectNameFor(controller: WEDMController): string {
    if (controller === "agie_cut") return "AgieCharmilles CUT";
    if (controller === "agie_charm") return "AgieCharmilles Charm";
    return "AgieCharmilles";
  }

  generate(input: WEDMPostInput): WEDMPostOutput {
    const controller = input.controller;
    if (!this.supportedControllers.includes(controller)) {
      return {
        success: false,
        controller,
        dialect_name: "UNKNOWN",
        gcode_lines: [],
        gcode_text: "",
        line_count: 0,
        operation_count: 0,
        warnings: [`WEDMPostAgieEngine does not support controller '${controller}'`],
        dialect_specific: {},
      };
    }

    const lines: string[] = [];
    const warnings: string[] = [];
    const dialectName = this.dialectNameFor(controller);
    const isImperial = input.units === "imperial";
    const decimals = isImperial ? AGIE_COORD_DECIMALS_IN : AGIE_COORD_DECIMALS_MM;
    const progNum = (input.program_number ?? "0001").padStart(4, "0");

    // ── Header (GF frame) ──
    lines.push("%PM");
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "WIRE EDM PROGRAM"})`);
    lines.push(`(CONTROLLER: ${dialectName} VISION 5)`);
    lines.push(`(MATERIAL: ${input.material ?? "TOOL STEEL"} THICKNESS: ${input.thickness_mm.toFixed(2)}mm)`);
    lines.push(`(WIRE: ${(input.wire_diameter_mm ?? 0.25).toFixed(2)}mm)`);
    lines.push(`(GENERATED BY PRISM WEDM POST — AGIE DIALECT v${this.version})`);
    lines.push("");

    const unitCode = isImperial ? "G70" : "G71";    // DIN-style: G70 inch, G71 metric
    const unitLabel = isImperial ? "INCH" : "METRIC";
    lines.push(`G90 ${unitCode} (ABSOLUTE ${unitLabel})`);
    lines.push("G92 X0 Y0 (SET PART ZERO)");

    if (input.thickness_mm > 400) {
      warnings.push(`Thickness ${input.thickness_mm}mm exceeds CUT P 800 Z-travel — verify machine`);
    }
    if (input.thickness_mm <= 0 || !Number.isFinite(input.thickness_mm)) {
      warnings.push(`Invalid thickness ${input.thickness_mm}mm`);
    }

    const tecCodesUsed: string[] = [];
    const pulseCodesUsed: string[] = [];

    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      const d = passDefaults(op.pass);
      const power = op.power_setting ?? d.power;
      const onTime = op.on_time_us ?? d.on_us;
      const offTime = op.off_time_us ?? d.off_us;
      const wireSpeed = op.wire_speed_m_min ?? d.wire_speed;
      const wireTension = op.wire_tension_g ?? d.wire_tension;
      const offset = op.offset_mm ?? 0.15;
      const direction = op.offset_direction ?? "left";
      const autoThread = op.auto_thread !== false;
      const submerged = op.submerged !== false;

      const tec = AGIE_TEC_TABLE[op.pass];
      tecCodesUsed.push(tec.tec);
      pulseCodesUsed.push(tec.pulse);

      lines.push("");
      lines.push(`(--- PASS ${i + 1}: ${op.pass.toUpperCase()} ${op.type.toUpperCase()} ---)`);
      lines.push(`${tec.tec} ${tec.pulse} (${tec.description})`);
      lines.push(`(PWR=${power} ON=${onTime}us OFF=${offTime}us WF=${wireSpeed}m/min WT=${wireTension}g)`);

      // Agie contour-attribute: .O = offset in µm.
      lines.push(`.O = ${(offset * 1000).toFixed(0)} (OFFSET ${offset.toFixed(3)}mm)`);

      if (op.pass === "rough") {
        lines.push("CIRU 2 (CORNER CONTROL — ROUGH)");
      } else {
        lines.push("CORO 1 (CORNER CONTROL — SKIM)");
      }

      if (autoThread) {
        lines.push("M20 (AWT AUTO WIRE THREAD)");
      }
      if (submerged) {
        lines.push("M24 (SUBMERGE ON)");
      }

      if (op.start_x !== undefined && op.start_y !== undefined) {
        const x = formatCoord(op.start_x, isImperial, decimals);
        const y = formatCoord(op.start_y, isImperial, decimals);
        lines.push(`G0 X${x} Y${y} (APPROACH)`);
      }

      const offsetCode = direction === "right" ? "G42" : "G41";
      lines.push(`${offsetCode} (COMP ON ${direction.toUpperCase()})`);

      // Agie taper: G08 A<deg> on, G09 off.
      if (op.type === "taper" && typeof op.taper_angle_deg === "number") {
        lines.push(`G08 A${op.taper_angle_deg.toFixed(3)} (TAPER ON ${op.taper_angle_deg.toFixed(3)}deg)`);
        if (typeof op.taper_height_mm === "number") {
          lines.push(`(TAPER HEIGHT ${op.taper_height_mm.toFixed(2)}mm)`);
        }
      }

      if (op.profile_points && op.profile_points.length > 0) {
        for (const pt of op.profile_points) {
          const x = formatCoord(pt.x, isImperial, decimals);
          const y = formatCoord(pt.y, isImperial, decimals);
          let line = `G1 X${x} Y${y}`;
          if (pt.u !== undefined && pt.v !== undefined) {
            const u = formatCoord(pt.u, isImperial, decimals);
            const v = formatCoord(pt.v, isImperial, decimals);
            line += ` U${u} V${v}`;
          }
          lines.push(line);
        }
      } else {
        warnings.push(`Pass ${i + 1}: no profile_points — emitted placeholder`);
        lines.push("(... profile geometry missing ...)");
      }

      if (op.type === "taper") {
        lines.push("G09 (TAPER OFF)");
      }

      lines.push("G40 (CANCEL COMP)");
      lines.push("M21 (AWT CUT)");
      if (submerged) {
        lines.push("M25 (SUBMERGE OFF)");
      }
    }

    // ── Footer (M17 = end + rewind, GF frame) ──
    lines.push("");
    lines.push("G92 X0 Y0 (HOME)");
    lines.push("M17");
    lines.push("%");

    const gcodeText = lines.join("\n");

    return {
      success: true,
      controller,
      dialect_name: dialectName,
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      operation_count: input.operations.length,
      warnings,
      dialect_specific: {
        manufacturer: this.manufacturer,
        uses_e_codes: false,
        uses_c_codes: true,
        uses_tec_codes: true,
        tec_codes_used: tecCodesUsed,
        pulse_codes_used: pulseCodesUsed,
        program_frame: "PM / M17",
        wire_thread_code: "M20",
        wire_cut_code: "M21",
      },
    };
  }

  parse(gcode: string): WEDMParsedPlan {
    const plan: WEDMParsedPlan = {
      operations: [],
      controller_hint: "agie_cut",
    };

    const progMatch = gcode.match(/^O(\d+)/m);
    if (progMatch) plan.program_number = progMatch[1];

    const blocks = gcode.split(/\(--- PASS \d+:/).slice(1);
    for (const block of blocks) {
      let pass: WEDMPassId | undefined;
      const tecMatch = block.match(/TEC (\d{4})/);
      if (tecMatch) {
        const tecCode = `TEC ${tecMatch[1]}`;
        for (const k of Object.keys(AGIE_TEC_TABLE) as WEDMPassId[]) {
          if (AGIE_TEC_TABLE[k].tec === tecCode) { pass = k; break; }
        }
      }

      const powerMatch = block.match(/PWR=(\d+)/);
      const onMatch = block.match(/ON=(\d+)/);
      const offMatch = block.match(/OFF=(\d+)/);
      const offsetMatch = block.match(/OFFSET\s+([\d.]+)mm/);
      const dirIsRight = /G42/.test(block);
      const submerged = /M24\s*\(SUBMERGE ON\)/.test(block);
      const taperMatch = block.match(/G08 A([-\d.]+)/);
      const pointMatches = block.match(/\bG1 X/g);

      plan.operations.push({
        pass,
        power: powerMatch ? Number(powerMatch[1]) : undefined,
        on_us: onMatch ? Number(onMatch[1]) : undefined,
        off_us: offMatch ? Number(offMatch[1]) : undefined,
        offset_mm: offsetMatch ? Number(offsetMatch[1]) : undefined,
        offset_direction: dirIsRight ? "right" : "left",
        submerged,
        taper_angle_deg: taperMatch ? Number(taperMatch[1]) : undefined,
        point_count: pointMatches ? pointMatches.length : 0,
      });
    }

    return plan;
  }

  getTecTable(): Readonly<Record<WEDMPassId, { tec: string; pulse: string; description: string }>> {
    return AGIE_TEC_TABLE;
  }
}

export const wedmPostAgieEngine = new WEDMPostAgieEngine();
