/**
 * WEDMPostMakinoEngine — Wire-EDM post processor for Makino's U-series and
 * EU-series wire EDMs (U3, U6, U32i, U86, EU64, EU43). All are driven by
 * the Professional 6 / Professional 6+ control with the HyperDrive® power
 * supply.
 *
 * Vendor references:
 *   • Makino "Professional 6 Programming Manual" rev. 2019
 *   • Makino "HyperDrive-Digital Power Supply Operator's Manual"
 *   • AESDC-2014 pulse-generator notes (supplier appendix)
 *
 * Dialect highlights the generic router did NOT capture:
 *   • HyperDrive pairs: E-code (energy table) MUST be paired with a
 *     C-code (contour table). The C-code tunes acceleration / corner
 *     response independently of the energy table.
 *   • Makino prefixes M-codes with a leading zero (M06, M07, M02).
 *   • Submerged cutting handled by M21/M22 (not M28).
 *   • Offset uses D-word in a dedicated register (D01–D99) with a
 *     `(OFS=Dnn)` comment for the operator.
 *   • 4-axis programs explicitly emit a `G51 X<angle>` form when the taper
 *     is pure-X; the generic form uses angle_deg as a scalar.
 *
 * MS-P1.5-ONESHOT/U-P1.5-OS-04
 */

import {
  IWEDMPostEngine,
  WEDMController,
  WEDMParsedPlan,
  WEDMPassId,
  WEDMPostInput,
  WEDMPostOutput,
  formatCoord,
  passDefaults,
} from "./WEDMPostTypes.js";

// Source: Makino "HyperDrive tech-table" defaults for 25 mm SKD11 / 0.25 mm brass.
const MAKINO_TECH_TABLE: Record<WEDMPassId, { e: string; c: string; description: string }> = {
  rough: { e: "E450", c: "C12", description: "ROUGH HyperDrive 25mm SKD11" },
  skim1: { e: "E460", c: "C08", description: "SKIM1 fine surface pass" },
  skim2: { e: "E470", c: "C05", description: "SKIM2 (Ra ≤ 1.8µm)" },
  skim3: { e: "E480", c: "C02", description: "SKIM3 mirror (Ra ≤ 0.6µm)" },
};

const MAKINO_COORD_DECIMALS_MM = 4;
const MAKINO_COORD_DECIMALS_IN = 5;

export class WEDMPostMakinoEngine implements IWEDMPostEngine {
  readonly name = "WEDMPostMakinoEngine";
  readonly version = "1.0.0";
  readonly supportedControllers: readonly WEDMController[] = ["makino_u", "makino_eu"];
  readonly manufacturer = "Makino";

  dialectNameFor(controller: WEDMController): string {
    if (controller === "makino_u") return "Makino U";
    if (controller === "makino_eu") return "Makino EU";
    return "Makino";
  }

  generate(input: WEDMPostInput): WEDMPostOutput {
    const controller = input.controller;
    if (!this.supportedControllers.includes(controller)) {
      return {
        success: false,
        controller,
        dialect_name: "UNKNOWN",
        gcode_lines: [],
        gcode_text: "",
        line_count: 0,
        operation_count: 0,
        warnings: [`WEDMPostMakinoEngine does not support controller '${controller}'`],
        dialect_specific: {},
      };
    }

    const lines: string[] = [];
    const warnings: string[] = [];
    const dialectName = this.dialectNameFor(controller);
    const isImperial = input.units === "imperial";
    const decimals = isImperial ? MAKINO_COORD_DECIMALS_IN : MAKINO_COORD_DECIMALS_MM;
    const progNum = (input.program_number ?? "0001").padStart(4, "0");

    // ── Header ──
    lines.push("%");
    lines.push(`O${progNum}`);
    lines.push(`(${input.part_description ?? "WIRE EDM PROGRAM"})`);
    lines.push(`(CONTROLLER: ${dialectName} PROFESSIONAL 6)`);
    lines.push(`(POWER: HYPERDRIVE DIGITAL)`);
    lines.push(`(MATERIAL: ${input.material ?? "TOOL STEEL"} THICKNESS: ${input.thickness_mm.toFixed(2)}mm)`);
    lines.push(`(WIRE: ${(input.wire_diameter_mm ?? 0.25).toFixed(2)}mm)`);
    lines.push(`(GENERATED BY PRISM WEDM POST — MAKINO DIALECT v${this.version})`);
    lines.push("");

    const unitCode = isImperial ? "G20" : "G21";
    const unitLabel = isImperial ? "INCH" : "METRIC";
    lines.push(`G90 ${unitCode} (ABSOLUTE ${unitLabel})`);
    lines.push("G92 X0 Y0 (SET PART ZERO)");

    if (input.thickness_mm > 300) {
      warnings.push(`Thickness ${input.thickness_mm}mm exceeds U-series Z-travel on U3 — verify machine`);
    }
    if (input.thickness_mm <= 0 || !Number.isFinite(input.thickness_mm)) {
      warnings.push(`Invalid thickness ${input.thickness_mm}mm`);
    }

    const eCodesUsed: string[] = [];
    const cCodesUsed: string[] = [];
    const dRegistersUsed: string[] = [];

    for (let i = 0; i < input.operations.length; i++) {
      const op = input.operations[i];
      const d = passDefaults(op.pass);
      const power = op.power_setting ?? d.power;
      const onTime = op.on_time_us ?? d.on_us;
      const offTime = op.off_time_us ?? d.off_us;
      const wireSpeed = op.wire_speed_m_min ?? d.wire_speed;
      const wireTension = op.wire_tension_g ?? d.wire_tension;
      const offset = op.offset_mm ?? 0.15;
      const direction = op.offset_direction ?? "left";
      const autoThread = op.auto_thread !== false;
      const submerged = op.submerged !== false;

      const tech = MAKINO_TECH_TABLE[op.pass];
      eCodesUsed.push(tech.e);
      cCodesUsed.push(tech.c);
      const dReg = `D${String(i + 1).padStart(2, "0")}`;
      dRegistersUsed.push(dReg);

      lines.push("");
      lines.push(`(--- PASS ${i + 1}: ${op.pass.toUpperCase()} ${op.type.toUpperCase()} ---)`);
      // HyperDrive pair — E paired with C.
      lines.push(`${tech.e} ${tech.c} (${tech.description})`);
      lines.push(`(PWR=${power} TON=${onTime}us TOFF=${offTime}us WF=${wireSpeed}m/min WT=${wireTension}g)`);
      lines.push(`#${dReg.substring(1)}=${(offset * 1000).toFixed(0)} (OFS=${dReg} ${offset.toFixed(4)}mm)`);

      if (autoThread) {
        lines.push("M06 (AUTO WIRE THREAD)");
      }
      if (submerged) {
        lines.push("M21 (SUBMERGE ON)");
      }

      if (op.start_x !== undefined && op.start_y !== undefined) {
        const x = formatCoord(op.start_x, isImperial, decimals);
        const y = formatCoord(op.start_y, isImperial, decimals);
        lines.push(`G0 X${x} Y${y} (APPROACH)`);
      }

      const offsetCode = direction === "right" ? "G42" : "G41";
      lines.push(`${offsetCode} ${dReg} (COMP ON ${direction.toUpperCase()})`);

      if (op.type === "taper" && typeof op.taper_angle_deg === "number") {
        lines.push(`G51 X${op.taper_angle_deg.toFixed(4)} (TAPER ON ${op.taper_angle_deg.toFixed(4)}deg)`);
        if (typeof op.taper_height_mm === "number") {
          lines.push(`(TAPER HEIGHT ${op.taper_height_mm.toFixed(2)}mm)`);
        }
      }

      if (op.profile_points && op.profile_points.length > 0) {
        for (const pt of op.profile_points) {
          const x = formatCoord(pt.x, isImperial, decimals);
          const y = formatCoord(pt.y, isImperial, decimals);
          let line = `G1 X${x} Y${y}`;
          if (pt.u !== undefined && pt.v !== undefined) {
            const u = formatCoord(pt.u, isImperial, decimals);
            const v = formatCoord(pt.v, isImperial, decimals);
            line += ` U${u} V${v}`;
          }
          lines.push(line);
        }
      } else {
        warnings.push(`Pass ${i + 1}: no profile_points — emitted placeholder`);
        lines.push("(... profile geometry missing ...)");
      }

      if (op.type === "taper") {
        lines.push("G50 (TAPER OFF)");
      }

      lines.push("G40 (CANCEL COMP)");
      lines.push("M07 (WIRE CUT)");
      if (submerged) {
        lines.push("M22 (SUBMERGE OFF)");
      }
    }

    // ── Footer ──
    lines.push("");
    lines.push("G92 X0 Y0 (HOME)");
    lines.push("M02");
    lines.push("%");

    const gcodeText = lines.join("\n");

    return {
      success: true,
      controller,
      dialect_name: dialectName,
      gcode_lines: lines,
      gcode_text: gcodeText,
      line_count: lines.length,
      operation_count: input.operations.length,
      warnings,
      dialect_specific: {
        manufacturer: this.manufacturer,
        uses_e_codes: true,
        uses_c_codes: true,
        power_supply: "HyperDrive Digital",
        e_codes_used: eCodesUsed,
        c_codes_used: cCodesUsed,
        d_registers_used: dRegistersUsed,
        wire_thread_code: "M06",
        wire_cut_code: "M07",
      },
    };
  }

  parse(gcode: string): WEDMParsedPlan {
    const plan: WEDMParsedPlan = {
      operations: [],
      controller_hint: "makino_u",
    };

    const progMatch = gcode.match(/^O(\d+)/m);
    if (progMatch) plan.program_number = progMatch[1];

    const blocks = gcode.split(/\(--- PASS \d+:/).slice(1);
    for (const block of blocks) {
      let pass: WEDMPassId | undefined;
      const eCodeMatch = block.match(/\bE(\d{3})\b/);
      if (eCodeMatch) {
        const eCode = `E${eCodeMatch[1]}`;
        for (const k of Object.keys(MAKINO_TECH_TABLE) as WEDMPassId[]) {
          if (MAKINO_TECH_TABLE[k].e === eCode) { pass = k; break; }
        }
      }

      const powerMatch = block.match(/PWR=(\d+)/);
      const onMatch = block.match(/TON=(\d+)/);
      const offMatch = block.match(/TOFF=(\d+)/);
      const offsetMatch = block.match(/OFS=D\d+\s+([\d.]+)mm/);
      const dirIsRight = /G42/.test(block);
      const submerged = /M21\s*\(SUBMERGE ON\)/.test(block);
      const taperMatch = block.match(/G51 X([-\d.]+)/);
      const pointMatches = block.match(/\bG1 X/g);

      plan.operations.push({
        pass,
        power: powerMatch ? Number(powerMatch[1]) : undefined,
        on_us: onMatch ? Number(onMatch[1]) : undefined,
        off_us: offMatch ? Number(offMatch[1]) : undefined,
        offset_mm: offsetMatch ? Number(offsetMatch[1]) : undefined,
        offset_direction: dirIsRight ? "right" : "left",
        submerged,
        taper_angle_deg: taperMatch ? Number(taperMatch[1]) : undefined,
        point_count: pointMatches ? pointMatches.length : 0,
      });
    }

    return plan;
  }

  getTechTable(): Readonly<Record<WEDMPassId, { e: string; c: string; description: string }>> {
    return MAKINO_TECH_TABLE;
  }
}

export const wedmPostMakinoEngine = new WEDMPostMakinoEngine();
