# C3: Add companion sections to R4, R5, R6
$dir = "C:\PRISM\mcp-server\data\docs\roadmap"

# === R4 ===
$r4 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R4_ENTERPRISE.md")
$r4.Add(""); $r4.Add("---"); $r4.Add("")
$r4.Add("## R4 COMPANION ASSETS (v14.5 -- built per-MS, verified at R4-MS4 gate)")
$r4.Add(""); $r4.Add("### PER-MS COMPANION SCHEDULE:"); $r4.Add("``````")
$r4.Add("MS0 PRODUCES:")
$r4.Add("  HOOK: tenant_isolation_verify (blocking, post-tenant-create, verifies no cross-tenant leakage)")
$r4.Add("  Verify: Create 2 tenants, query as tenant B -> sees ONLY its data")
$r4.Add("")
$r4.Add("MS1 PRODUCES:")
$r4.Add("  SKILL: prism-compliance-guide (ISO 9001, AS9100, ITAR template usage and interpretation)")
$r4.Add("  Verify: Ask about ITAR compliance for titanium part -> skill loads with clause refs")
$r4.Add("")
$r4.Add("MS2 PRODUCES:")
$r4.Add("  HOOK: api_version_check (warning, pre-deploy, verifies /v1/ prefix on all endpoints)")
$r4.Add("  SKILL: prism-tenant-management (multi-tenant patterns, data residency, session isolation)")
$r4.Add("")
$r4.Add("MS3 PRODUCES:")
$r4.Add("  SKILL: prism-api-reference (auto-generated from endpoint schema, teaches API usage)")
$r4.Add("  SCRIPT: api_smoke_test (hits all endpoints, verifies auth + rate limiting)")
$r4.Add("")
$r4.Add("MS4 GATE VERIFIES:")
$r4.Add("  Both hooks fire, all 3 skills load, api_smoke_test passes")
$r4.Add("  SCRIPT: tenant_health_check (verifies all tenants isolated and healthy)")
$r4.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R4_ENTERPRISE.md", $r4.ToArray())
Write-Output "C3: R4 done ($($r4.Count) lines)"

# === R5 ===
$r5 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R5_VISUAL.md")
$r5.Add(""); $r5.Add("---"); $r5.Add("")
$r5.Add("## R5 COMPANION ASSETS (v14.5 -- built per-MS, verified at R5-MS5 gate)")
$r5.Add(""); $r5.Add("### PER-MS COMPANION SCHEDULE:"); $r5.Add("``````")
$r5.Add("MS0 PRODUCES:")
$r5.Add("  SKILL: prism-dashboard-components (component library reference, props, usage patterns)")
$r5.Add("")
$r5.Add("MS1 PRODUCES:")
$r5.Add("  HOOK: formula_display_accuracy (warning, post-render, verifies displayed calc matches engine)")
$r5.Add("")
$r5.Add("MS3 PRODUCES:")
$r5.Add("  SKILL: prism-monitoring-dashboard (real-time data interpretation, alert thresholds)")
$r5.Add("")
$r5.Add("MS4 PRODUCES:")
$r5.Add("  SCRIPT: report_generation_test (generates sample PDF/Excel, verifies formatting)")
$r5.Add("")
$r5.Add("MS5 GATE VERIFIES:")
$r5.Add("  Hook fires, both skills load, report script passes")
$r5.Add("  SCRIPT: screenshot_regression (captures dashboard state for visual regression baseline)")
$r5.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R5_VISUAL.md", $r5.ToArray())
Write-Output "C3: R5 done ($($r5.Count) lines)"

# === R6 ===
$r6 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R6_PRODUCTION.md")
$r6.Add(""); $r6.Add("---"); $r6.Add("")
$r6.Add("## R6 COMPANION ASSETS (v14.5 -- built per-MS, verified at R6-MS5 gate)")
$r6.Add(""); $r6.Add("### PER-MS COMPANION SCHEDULE:"); $r6.Add("``````")
$r6.Add("MS0 PRODUCES:")
$r6.Add("  SCRIPT: performance_baseline (captures response times, memory, throughput baseline)")
$r6.Add("")
$r6.Add("MS1 PRODUCES:")
$r6.Add("  HOOK: fault_recovery_verify (blocking, post-fault-injection, verifies clean recovery)")
$r6.Add("")
$r6.Add("MS2 PRODUCES:")
$r6.Add("  HOOK: safety_degradation_alert (blocking, continuous, alerts if S(x) drops under load)")
$r6.Add("  SKILL: prism-production-runbook (deployment, monitoring, incident response)")
$r6.Add("")
$r6.Add("MS3 PRODUCES:")
$r6.Add("  SKILL: prism-alert-interpretation (alert thresholds, escalation, root cause)")
$r6.Add("")
$r6.Add("MS4 PRODUCES:")
$r6.Add("  HOOK: deployment_rollback_trigger (blocking, post-deploy, auto-rollback on failure spike)")
$r6.Add("  SCRIPT: load_test_runner (automated load test with S(x) verification)")
$r6.Add("")
$r6.Add("MS5 GATE VERIFIES:")
$r6.Add("  All 3 hooks fire, both skills load, load_test_runner passes")
$r6.Add("  S(x) >= 0.70 verified under sustained production load")
$r6.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R6_PRODUCTION.md", $r6.ToArray())
Write-Output "C3: R6 done ($($r6.Count) lines)"
