# BATCH 2: C3 - Add companion asset sections to R4, R5, R6, R9, R10
$dir = "C:\PRISM\mcp-server\data\docs\roadmap"

# === R4 COMPANION ===
$r4 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R4_ENTERPRISE.md")
$r4.Add("")
$r4.Add("---")
$r4.Add("")
$r4.Add("## R4 COMPANION ASSETS (v14.5 -- built per-MS, verified at R4-MS4 gate)")
$r4.Add("")
$r4.Add("### PER-MS COMPANION SCHEDULE:")
$r4.Add("``````")
$r4.Add("MS0 PRODUCES:")
$r4.Add("  HOOK: tenant_isolation_verify (blocking, post-tenant-create, verifies no data leakage)")
$r4.Add("  Verify: Create 2 tenants, query as tenant B -> sees ONLY its own data")
$r4.Add("")
$r4.Add("MS1 PRODUCES:")
$r4.Add("  SKILL: prism-compliance-guide (ISO 9001, AS9100, ITAR template usage and interpretation)")
$r4.Add("  Verify: Ask about ITAR compliance for titanium part -> skill loads with clause refs")
$r4.Add("")
$r4.Add("MS2 PRODUCES:")
$r4.Add("  HOOK: api_version_check (warning, pre-deploy, verifies /v1/ prefix on all endpoints)")
$r4.Add("  SKILL: prism-tenant-management (multi-tenant patterns, data residency, session isolation)")
$r4.Add("  Verify: Deploy without version prefix -> hook warns")
$r4.Add("")
$r4.Add("MS3 PRODUCES:")
$r4.Add("  SKILL: prism-api-reference (auto-generated from endpoint schema, teaches API usage)")
$r4.Add("  SCRIPT: api_smoke_test (hits all endpoints, verifies auth + rate limiting)")
$r4.Add("  Verify: Run smoke test -> all endpoints respond correctly")
$r4.Add("")
$r4.Add("MS4 GATE VERIFIES:")
$r4.Add("  Both hooks fire on test cases")
$r4.Add("  All 3 skills load and respond to queries")
$r4.Add("  api_smoke_test and tenant_health_check scripts pass")
$r4.Add("  SCRIPT: tenant_health_check (verifies all tenants isolated and healthy)")
$r4.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R4_ENTERPRISE.md", $r4.ToArray())
Write-Output "C3: R4 companion added. Lines: $($r4.Count)"

# === R5 COMPANION ===
$r5 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R5_VISUAL.md")
$r5.Add("")
$r5.Add("---")
$r5.Add("")
$r5.Add("## R5 COMPANION ASSETS (v14.5 -- built per-MS, verified at R5-MS5 gate)")
$r5.Add("")
$r5.Add("### PER-MS COMPANION SCHEDULE:")
$r5.Add("``````")
$r5.Add("MS0 PRODUCES:")
$r5.Add("  SKILL: prism-dashboard-components (component library reference, props, usage patterns)")
$r5.Add("  Verify: Ask about available chart components -> skill loads with component catalog")
$r5.Add("")
$r5.Add("MS1 PRODUCES:")
$r5.Add("  HOOK: formula_display_accuracy (warning, post-render, verifies displayed calc matches engine)")
$r5.Add("  Verify: Render speed/feed calc with rounding error -> hook catches discrepancy")
$r5.Add("")
$r5.Add("MS2 PRODUCES: (page implementation -- uses MS0 components, no new companion)")
$r5.Add("")
$r5.Add("MS3 PRODUCES:")
$r5.Add("  SKILL: prism-monitoring-dashboard (real-time data interpretation, alert thresholds)")
$r5.Add("  Verify: Ask about spindle load spike pattern -> skill loads with interpretation guide")
$r5.Add("")
$r5.Add("MS4 PRODUCES:")
$r5.Add("  SCRIPT: report_generation_test (generates sample PDF/Excel reports, verifies formatting)")
$r5.Add("  Verify: Run script -> produces clean PDF with correct data")
$r5.Add("")
$r5.Add("MS5 GATE VERIFIES:")
$r5.Add("  Hook fires on display accuracy test")
$r5.Add("  Both skills load and respond to queries")
$r5.Add("  report_generation_test script passes")
$r5.Add("  SCRIPT: screenshot_regression (captures dashboard state for visual regression baseline)")
$r5.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R5_VISUAL.md", $r5.ToArray())
Write-Output "C3: R5 companion added. Lines: $($r5.Count)"

# === R6 COMPANION ===
$r6 = [System.Collections.ArrayList](Get-Content "$dir\PHASE_R6_PRODUCTION.md")
$r6.Add("")
$r6.Add("---")
$r6.Add("")
$r6.Add("## R6 COMPANION ASSETS (v14.5 -- built per-MS, verified at R6-MS5 gate)")
$r6.Add("")
$r6.Add("### PER-MS COMPANION SCHEDULE:")
$r6.Add("``````")
$r6.Add("MS0 PRODUCES:")
$r6.Add("  SCRIPT: performance_baseline (captures response times, memory, throughput baseline)")
$r6.Add("  Verify: Run script -> produces JSON with all baseline metrics")
$r6.Add("")
$r6.Add("MS1 PRODUCES:")
$r6.Add("  HOOK: fault_recovery_verify (blocking, post-fault-injection, verifies clean recovery)")
$r6.Add("  Verify: Inject network timeout -> system recovers, hook confirms clean state")
$r6.Add("")
$r6.Add("MS2 PRODUCES:")
$r6.Add("  HOOK: safety_degradation_alert (blocking, continuous, alerts if S(x) drops under load)")
$r6.Add("  SKILL: prism-production-runbook (deployment, monitoring, incident response procedures)")
$r6.Add("  Verify: Run load test at 2x capacity -> S(x) stays >=0.70, hook doesn't fire")
$r6.Add("")
$r6.Add("MS3 PRODUCES:")
$r6.Add("  SKILL: prism-alert-interpretation (teaches alert thresholds, escalation, root cause)")
$r6.Add("  Verify: Trigger heap warning -> skill explains meaning and recommended action")
$r6.Add("")
$r6.Add("MS4 PRODUCES:")
$r6.Add("  HOOK: deployment_rollback_trigger (blocking, post-deploy, auto-rollback on failure spike)")
$r6.Add("  SCRIPT: load_test_runner (automated load test with S(x) verification)")
$r6.Add("  Verify: Deploy intentionally broken build -> hook triggers rollback within 60s")
$r6.Add("")
$r6.Add("MS5 GATE VERIFIES:")
$r6.Add("  All 3 hooks fire on test scenarios")
$r6.Add("  Both skills load and respond to queries")
$r6.Add("  performance_baseline and load_test_runner scripts pass")
$r6.Add("  S(x) >= 0.70 verified under sustained production load")
$r6.Add("``````")
[System.IO.File]::WriteAllLines("$dir\PHASE_R6_PRODUCTION.md", $r6.ToArray())
Write-Output "C3: R6 companion added. Lines: $($r6.Count)"
