#!/usr/bin/env pwsh
<#
.SYNOPSIS
  CLEANUP-MS0/U-CLEANUP-G10 — viz-output-size watchdog cron (weekly).

.DESCRIPTION
  Thin Windows-Task-Scheduler wrapper around scripts/viz-output-size.mjs.
  Once a week, scans state/shared/system-viz/, alerts when total bytes
  exceed --threshold-gb (default 2 GB), and (with -Archive) moves
  non-current snapshot files (*.previous.json, *.bak, *.snapshot-DATE.*,
  *-snapshot-DATE.*, *.archive.N.json) to H:/prism-backups/viz/<ISO>/.

  Why weekly: the system-viz dir is regenerated by the wiki + viz cron
  chain; 415 MB baseline (observed 2026-05-14) grows by ~10-20 MB per
  regeneration cycle. A 2 GB threshold gives ~5x headroom and a weekly
  cadence catches the trend before it becomes a git-history-strip event
  (see [[reference_git_history_strip_event_2026_05_12]]).

  Exit codes propagated from the .mjs:
    0 = under threshold (success)
    1 = internal error (unreadable root, write failure during archive)
    2 = OVER threshold — the alert signal. The .ps1 surfaces this in
        $LASTEXITCODE so Task Scheduler can be set to "send notification
        when last run result was anything other than 0" (operator can
        further wire to chat-bus alert in a future hook).

.PARAMETER Json
  Pass --json (machine-readable summary to stdout).

.PARAMETER Archive
  Pass --archive (move non-current snapshots out of the live tree).

.PARAMETER DryRun
  Pass --dry-run (with --archive, preview moves; without --archive, no-op).

.PARAMETER ThresholdGb
  Override threshold (default 2).

.PARAMETER TopN
  How many largest files to surface in the report (default 10).

.EXAMPLE
  .\31-viz-output-size.ps1
  Run a size report, exit 0/2 based on threshold.

.EXAMPLE
  .\31-viz-output-size.ps1 -Archive
  Report AND archive non-current snapshots to H:/prism-backups/viz/<ISO>/.

.EXAMPLE
  schtasks.exe /Create /SC WEEKLY /D SUN /ST 06:13 /TN "PRISM Viz Output Size" `
    /TR "pwsh.exe -NoProfile -ExecutionPolicy Bypass -File H:\prism\scripts\system-health\31-viz-output-size.ps1 -Archive"

.NOTES
  Cadence: weekly, Sunday 06:13 (off the :00/:30 marks per fleet scheduling).
  Output: stdout report (or --json) + side-effect archive directory under
          H:/prism-backups/viz/ when -Archive is passed.
#>
param(
  [switch]$Json,
  [switch]$Archive,
  [switch]$DryRun,
  [double]$ThresholdGb = 0,
  [int]$TopN = 0
)

$ErrorActionPreference = "Continue"

$here   = Split-Path -Parent $PSCommandPath
$repo   = Split-Path -Parent (Split-Path -Parent $here)
$script = Join-Path $repo "scripts/viz-output-size.mjs"

if (-not (Test-Path $script)) {
  Write-Error "viz-output-size.mjs not found at: $script"
  exit 1
}

$nodeArgs = @($script)
if ($Json)                { $nodeArgs += "--json" }
if ($Archive)             { $nodeArgs += "--archive" }
if ($DryRun)              { $nodeArgs += "--dry-run" }
if ($ThresholdGb -gt 0)   { $nodeArgs += "--threshold-gb"; $nodeArgs += "$ThresholdGb" }
if ($TopN -gt 0)          { $nodeArgs += "--top-n"; $nodeArgs += "$TopN" }

$nodeBin = "H:\Tools\nodejs\node.exe"
if (-not (Test-Path $nodeBin)) {
  $nodeBin = (Get-Command node -ErrorAction SilentlyContinue).Source
}
if (-not $nodeBin) {
  Write-Error "node binary not found (tried H:\Tools\nodejs\node.exe + PATH)"
  exit 1
}

& $nodeBin @nodeArgs
$exit = $LASTEXITCODE
if ($null -eq $exit) { $exit = 0 }
exit $exit
