/**
 * Auto-generated Zod action schemas for contextDispatcher
 * Generated: 2026-04-04
 */
import { z } from "zod";

export const ACTION_CONTEXT_SCHEMAS: Record<string, z.ZodObject<any>> = {
  "action": z.object({}).passthrough(),
  "active": z.object({}).passthrough(),
  "attention_score": z.object({}).passthrough(),
  "budget_get": z.object({ filter: z.record(z.string(), z.any()).optional(), limit: z.number().optional() }).passthrough(),
  "budget_report": z.object({}).passthrough(),
  "budget_reset": z.object({}).passthrough(),
  "budget_track": z.object({ source: z.string().optional(), interval_ms: z.number().optional() }).passthrough(),
  "catalog_engine": z.object({}).passthrough(),
  "catalog_overview": z.object({}).passthrough(),
  "catalog_search": z.object({ filter: z.record(z.string(), z.any()).optional(), limit: z.number().optional() }).passthrough(),
  "catalog_stats": z.object({}).passthrough(),
  "child_process": z.object({}).passthrough(),
  "complete": z.object({}).passthrough(),
  "context_monitor_check": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional(), source: z.string().optional(), interval_ms: z.number().optional() }).passthrough(),
  "crypto": z.object({}).passthrough(),
  "custom": z.object({}).passthrough(),
  "decision": z.object({}).passthrough(),
  "decisions": z.object({}).passthrough(),
  "done": z.object({}).passthrough(),
  "error": z.object({}).passthrough(),
  "error_patterns": z.object({}).passthrough(),
  "error_preserve": z.object({}).passthrough(),
  "errors": z.object({}).passthrough(),
  "event": z.object({}).passthrough(),
  "events": z.object({}).passthrough(),
  "focus_optimize": z.object({ target: z.string().optional(), constraints: z.record(z.string(), z.any()).optional(), objective: z.string().optional() }).passthrough(),
  "general": z.object({}).passthrough(),
  "in_progress": z.object({}).passthrough(),
  "inbox": z.object({}).passthrough(),
  "kv_check_stability": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "kv_sort_json": z.object({}).passthrough(),
  "memory_externalize": z.object({}).passthrough(),
  "memory_restore": z.object({}).passthrough(),
  "path": z.object({}).passthrough(),
  "pending": z.object({}).passthrough(),
  "phrase_alternate": z.object({}).passthrough(),
  "punctuation_vary": z.object({}).passthrough(),
  "relevance_filter": z.object({}).passthrough(),
  "sentence_reorder": z.object({}).passthrough(),
  "snapshot": z.object({}).passthrough(),
  "snapshots": z.object({}).passthrough(),
  "structure_vary": z.object({}).passthrough(),
  "synonym_swap": z.object({}).passthrough(),
  "tasks": z.object({}).passthrough(),
  "team_broadcast": z.object({}).passthrough(),
  "team_create_task": z.object({ id: z.string().optional(), data: z.record(z.string(), z.any()).optional() }).passthrough(),
  "team_heartbeat": z.object({}).passthrough(),
  "team_spawn": z.object({}).passthrough(),
  "teams": z.object({}).passthrough(),
  "todo_read": z.object({}).passthrough(),
  "todo_update": z.object({ id: z.string().optional(), data: z.record(z.string(), z.any()).optional() }).passthrough(),
  "tool_mask_state": z.object({}).passthrough(),
  "vary_response": z.object({}).passthrough(),
};
