/**
 * Auto-generated Zod action schemas for cplDispatcher
 * Generated: 2026-04-04
 */
import { z } from "zod";

export const ACTION_CPL_SCHEMAS: Record<string, z.ZodObject<any>> = {
  "balanced": z.object({}).passthrough(),
  "bar_stock_analyze": z.object({}).passthrough(),
  "bar_stock_chatter": z.object({}).passthrough(),
  "cam_validate": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "clothoid_blend": z.object({}).passthrough(),
  "contact_full_integrity": z.object({}).passthrough(),
  "contact_hertz": z.object({}).passthrough(),
  "controller_compatibility": z.object({}).passthrough(),
  "cut_reorder": z.object({}).passthrough(),
  "delegated": z.object({}).passthrough(),
  "dfm_analyze": z.object({}).passthrough(),
  "dfm_feedback": z.object({}).passthrough(),
  "distortion_predict": z.object({}).passthrough(),
  "fixture_plan": z.object({ jobs: z.array(z.record(z.string(), z.any())).optional(), horizon_hours: z.number().optional() }).passthrough(),
  "function": z.object({}).passthrough(),
  "gcode_diff": z.object({}).passthrough(),
  "gdt_propagate": z.object({}).passthrough(),
  "hole_reorder": z.object({}).passthrough(),
  "integration_test": z.object({}).passthrough(),
  "inverse_thermal_compensate": z.object({}).passthrough(),
  "inverse_thermal_warmup": z.object({}).passthrough(),
  "learning_corrections": z.object({}).passthrough(),
  "minimum_jerk_plan": z.object({ jobs: z.array(z.record(z.string(), z.any())).optional(), horizon_hours: z.number().optional() }).passthrough(),
  "minimum_jerk_segment": z.object({}).passthrough(),
  "multi_body_frf": z.object({}).passthrough(),
  "multi_body_stability": z.object({}).passthrough(),
  "nl_cam_command": z.object({}).passthrough(),
  "output_variants": z.object({}).passthrough(),
  "parallel_optimize": z.object({ target: z.string().optional(), constraints: z.record(z.string(), z.any()).optional(), objective: z.string().optional() }).passthrough(),
  "parse_dxf": z.object({}).passthrough(),
  "parse_svg": z.object({}).passthrough(),
  "ph_constant_feed": z.object({}).passthrough(),
  "ph_interpolate": z.object({}).passthrough(),
  "pipeline_calibration": z.object({}).passthrough(),
  "pipeline_record_predictions": z.object({ source: z.string().optional(), interval_ms: z.number().optional() }).passthrough(),
  "pipeline_submit_actuals": z.object({}).passthrough(),
  "rotary_axis_check": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "route_features": z.object({}).passthrough(),
  "servo_lag_compensate": z.object({}).passthrough(),
  "stochastic_pareto": z.object({}).passthrough(),
  "stochastic_route_optimize": z.object({ target: z.string().optional(), constraints: z.record(z.string(), z.any()).optional(), objective: z.string().optional() }).passthrough(),
  "thermal_field_route": z.object({}).passthrough(),
  "thermal_field_simulate": z.object({ material: z.string().optional(), temperature: z.number().optional(), heat_source: z.string().optional() }).passthrough(),
  "tolerance_driven_params": z.object({}).passthrough(),
  "tolerance_verify": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "trochoidal_variable_depth": z.object({}).passthrough(),
  "turning_profile": z.object({}).passthrough(),
  "voronoi_engagement": z.object({}).passthrough(),
  "voronoi_pocket": z.object({}).passthrough(),
  "voxel_init": z.object({}).passthrough(),
  "voxel_subtract": z.object({}).passthrough(),
  "voxel_thin_walls": z.object({}).passthrough(),
  "voxel_volume": z.object({}).passthrough(),
  "wear_compensate": z.object({}).passthrough(),
  "wear_life_extension": z.object({}).passthrough(),
  "wear_map": z.object({}).passthrough(),
};
