/**
 * Auto-generated Zod action schemas for spDispatcher
 * Generated: 2026-04-04
 */
import { z } from "zod";

export const ACTION_SP_SCHEMAS: Record<string, z.ZodObject<any>> = {
  "alarms": z.object({}).passthrough(),
  "brainstorm": z.object({}).passthrough(),
  "child_process": z.object({}).passthrough(),
  "cognitive_bayes": z.object({}).passthrough(),
  "cognitive_check": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "cognitive_init": z.object({}).passthrough(),
  "cognitive_rl": z.object({}).passthrough(),
  "combination_ilp": z.object({}).passthrough(),
  "context_attention_anchor": z.object({}).passthrough(),
  "context_error_preserve": z.object({}).passthrough(),
  "context_kv_optimize": z.object({ target: z.string().optional(), constraints: z.record(z.string(), z.any()).optional(), objective: z.string().optional() }).passthrough(),
  "coordination": z.object({}).passthrough(),
  "debug": z.object({}).passthrough(),
  "deep": z.object({}).passthrough(),
  "deliverable": z.object({}).passthrough(),
  "development": z.object({}).passthrough(),
  "effort": z.object({}).passthrough(),
  "evidence_level": z.object({}).passthrough(),
  "execute": z.object({}).passthrough(),
  "gap_inventory": z.object({}).passthrough(),
  "general": z.object({}).passthrough(),
  "impact": z.object({}).passthrough(),
  "likelihood": z.object({}).passthrough(),
  "machines": z.object({}).passthrough(),
  "materials": z.object({}).passthrough(),
  "metrics": z.object({}).passthrough(),
  "missing": z.object({}).passthrough(),
  "mitigation": z.object({}).passthrough(),
  "name": z.object({}).passthrough(),
  "none": z.object({}).passthrough(),
  "optimize_full": z.object({ target: z.string().optional(), constraints: z.record(z.string(), z.any()).optional(), objective: z.string().optional() }).passthrough(),
  "opus": z.object({}).passthrough(),
  "orchestration": z.object({}).passthrough(),
  "path": z.object({}).passthrough(),
  "phase": z.object({}).passthrough(),
  "phased_plan": z.object({ jobs: z.array(z.record(z.string(), z.any())).optional(), horizon_hours: z.number().optional() }).passthrough(),
  "physics": z.object({}).passthrough(),
  "plan": z.object({ jobs: z.array(z.record(z.string(), z.any())).optional(), horizon_hours: z.number().optional() }).passthrough(),
  "problem": z.object({}).passthrough(),
  "quick": z.object({}).passthrough(),
  "recommended_approach": z.object({}).passthrough(),
  "recommended_tools": z.object({}).passthrough(),
  "review_quality": z.object({}).passthrough(),
  "review_spec": z.object({}).passthrough(),
  "risk": z.object({}).passthrough(),
  "risk_matrix": z.object({}).passthrough(),
  "safety": z.object({}).passthrough(),
  "session_end_full": z.object({}).passthrough(),
  "session_start": z.object({}).passthrough(),
  "session_start_full": z.object({}).passthrough(),
  "standard": z.object({}).passthrough(),
  "synthesis": z.object({}).passthrough(),
  "tooling": z.object({}).passthrough(),
  "unknown": z.object({}).passthrough(),
  "validate_gates_full": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
  "validate_mathplan": z.object({ target: z.record(z.string(), z.any()).optional(), rules: z.array(z.string()).optional() }).passthrough(),
};
