import type { InventoryOperationsWorkspace } from './contracts';

export const INVENTORY_OPERATIONS_WORKSPACE: InventoryOperationsWorkspace = {
  summary:
    'Inventory should behave like a live custody system: documents populate the catalog, receiving routes material to the right department, workers check tooling out, and insert indexing feeds cost efficiency back into the business.',
  shellNote:
    'This seam is intentionally frontend-first so receiving, routing, checkout, and insert/index tracking can converge now while Claude lands the canonical backend events, persistence, and document-extraction routes.',
  documentTemplates: [
    {
      id: 'purchase-order',
      label: 'Purchase order / receiving',
      summary: 'Extract supplier, PO, part numbers, ordered quantity, unit cost, and target department from incoming buy documents.',
      extractionTargets: ['Supplier and PO number', 'Part number and description', 'Ordered quantity and unit cost', 'Suggested department route'],
      confidencePosture: 'Best for ERP-generated PDFs and emailed PO attachments.',
      samplePath: 'C:/Kienzle/DOCS/receiving/po-4821.pdf',
    },
    {
      id: 'delivery-order',
      label: 'Packing slip / delivery order',
      summary: 'Confirm what actually arrived, capture lots or serials, and stage discrepancies before items hit the floor.',
      extractionTargets: ['Delivered quantity', 'Lot or serial identifiers', 'Received-vs-ordered mismatch', 'Receiving timestamp'],
      confidencePosture: 'Highest confidence when the supplier slip is cleanly scanned or vendor-generated.',
      samplePath: 'C:/Kienzle/DOCS/receiving/delivery-1138.pdf',
    },
    {
      id: 'tooling-invoice',
      label: 'Tooling invoice / insert pack',
      summary: 'Populate the tool crib with insert grades, holder SKUs, manufacturer part numbers, and pack sizes.',
      extractionTargets: ['Tool or insert part number', 'Pack size and unit of measure', 'Supplier pricing', 'Reorder baseline'],
      confidencePosture: 'Useful for inserts, holders, drills, taps, and consumable tooling.',
      samplePath: 'C:/Kienzle/DOCS/tooling/kennametal-invoice-774.pdf',
    },
    {
      id: 'machine-packet',
      label: 'Machine packet / service manual',
      summary: 'Extract machine, controller, taper, toolchanger, and service-part identifiers into the machine inventory and alarm desks.',
      extractionTargets: ['Machine model and serial', 'Controller family', 'Service part identifiers', 'Consumable maintenance references'],
      confidencePosture: 'Best for OEM PDFs and service bulletins that repeat part numbers consistently.',
      samplePath: 'C:/Kienzle/DOCS/machines/vf2-service-packet.pdf',
    },
  ],
  receivingQueue: [
    {
      id: 'receipt-4821',
      supplier: 'Kennametal',
      reference: 'PO-4821',
      partCount: '14 line items',
      department: 'Tool crib',
      status: 'ready',
      note: 'Insert packs and holders are on the dock. Count, receive, then route to tool crib bins before first shift.',
    },
    {
      id: 'receipt-1138',
      supplier: 'Jergens',
      reference: 'Delivery-1138',
      partCount: '3 fixture service kits',
      department: 'Mill cell',
      status: 'watch',
      note: 'Needs seal-kit verification before the kits are checked into the mill fixture cabinet.',
    },
    {
      id: 'receipt-774',
      supplier: 'Master Fluid Solutions',
      reference: 'PO-774',
      partCount: '2 coolant drums',
      department: 'Maintenance',
      status: 'blocked',
      note: 'Do not release until concentration cert and SDS packet are attached to the receiving record.',
    },
  ],
  departmentRoutes: [
    {
      id: 'route-tool-crib',
      department: 'Tool crib',
      queuedItems: '14 items on deck',
      routingNote: 'Primary landing zone for inserts, holders, drills, and barcode labels before operator checkout.',
    },
    {
      id: 'route-mill',
      department: 'Mill cell',
      queuedItems: '6 items on deck',
      routingNote: 'Use when setup-critical workholding or stock needs to be staged directly at the machine area.',
    },
    {
      id: 'route-lathe',
      department: 'Lathe cell',
      queuedItems: '3 items on deck',
      routingNote: 'Route turning inserts, boring bars, and jaws here after crib receipt is complete.',
    },
    {
      id: 'route-quality',
      department: 'Quality bench',
      queuedItems: '2 items on deck',
      routingNote: 'Calibration items, gage certs, and first-article consumables wait here for quality release.',
    },
  ],
  checkoutQueue: [
    {
      id: 'checkout-cnmg',
      toolId: 'INS-CNMG-432-KC5010',
      label: 'CNMG432 KC5010 insert pack',
      category: 'Turning insert',
      location: 'Tool crib A-04',
      priceLabel: '$118 / box',
      status: 'ready',
      note: 'Default issue for ST-20 rough/finish queue. Track edges used, not just packs opened.',
    },
    {
      id: 'checkout-endmill',
      toolId: 'EM-0500-5F-HF',
      label: '1/2 in high-feed end mill',
      category: 'Milling cutter',
      location: 'Tool crib B-11',
      priceLabel: '$214 each',
      status: 'ready',
      note: 'Expected on HMC roughing jobs. Checkout should attach the tool to the job traveler and machine.',
    },
    {
      id: 'checkout-holder',
      toolId: 'HSK63A-SHRINK-ER32',
      label: 'HSK63A shrink-fit holder',
      category: 'Tool holder',
      location: 'Presetter rack 2',
      priceLabel: '$486 each',
      status: 'watch',
      note: 'Needs presetter confirmation before it should be checked out to the cell.',
    },
  ],
  usagePulses: [
    {
      id: 'usage-vf2-insert',
      label: 'CNMG finish insert active on valve body job',
      machine: 'Haas VF-2SS',
      operator: 'Avery Stone',
      state: 'In cycle now',
      indexedEdges: 2,
      maxEdges: 4,
      costPerPart: '$0.84 / part',
      nextAction: 'Index the next edge after the next 18 pieces or if finish drops.',
    },
    {
      id: 'usage-hmc-endmill',
      label: 'High-feed end mill roughing impeller pocket',
      machine: 'Makino a61nx',
      operator: 'Mason Reed',
      state: 'Warm standby',
      indexedEdges: 1,
      maxEdges: 3,
      costPerPart: '$2.36 / part',
      nextAction: 'Watch spindle load and swap after the current family if radial wear keeps climbing.',
    },
    {
      id: 'usage-lathe-vbmt',
      label: 'VBMT edge tracking on bearing spacer run',
      machine: 'Haas ST-20Y',
      operator: 'Jordan Hale',
      state: 'Needs update',
      indexedEdges: 1,
      maxEdges: 2,
      costPerPart: '$0.41 / part',
      nextAction: 'Operator should log the next edge flip as part of job stop or pause.',
    },
  ],
  formulaNotes: [
    {
      id: 'formula-receipt-normalization',
      label: 'Receipt normalization',
      purpose: 'Turn raw supplier lines into internal inventory records without duplicates.',
      output: 'Supplier part -> internal part -> department route -> received quantity delta',
      note: 'One shared normalization pass is better than custom parsing logic on every page.',
    },
    {
      id: 'formula-tool-cost',
      label: 'Tool cost per usable edge',
      purpose: 'Translate insert box price into real cost per edge and cost per part.',
      output: 'box cost / (inserts per box * usable edges) -> cost per edge -> cost per part',
      note: 'This should feed quoting, margin review, and machine/tooling ROI together.',
    },
    {
      id: 'formula-checkout-attribution',
      label: 'Checkout attribution',
      purpose: 'Know which job, employee, machine, and department are consuming tooling or consumables.',
      output: 'tool checkout + traveler + active machine context -> live usage ownership',
      note: 'Keep the event model unified so alarms, jobs, and inventory all see the same tool state.',
    },
    {
      id: 'formula-reorder',
      label: 'Reorder and shortage posture',
      purpose: 'Blend demand, remaining tooling life, and supplier ETA into one restock signal.',
      output: 'usage trend + remaining edges + queue demand + ETA risk -> reorder posture',
      note: 'Yes, Kienzle should use custom formulas here, but a small shared set is better than dozens of disconnected algorithms.',
    },
  ],
};
