/**
 * LatheMasterPostUnifiedOutputEngine Tests
 *
 * U-LTH26: Tests for unified output format across all sub-posts.
 * Verifies standard header/footer/metadata blocks and dialect normalization.
 */

import { describe, it, expect } from "vitest";
import {
  latheMasterPostUnifiedOutputEngine,
  type UnifyOutputInput,
  type UnifiedOutputMetadata,
  type ToolEntry,
} from "../engines/LatheMasterPostUnifiedOutputEngine.js";

describe("LatheMasterPostUnifiedOutputEngine", () => {
  const createBaseMetadata = (overrides: Partial<UnifiedOutputMetadata> = {}): UnifiedOutputMetadata => ({
    program_number: 1001,
    program_name: "TEST_PART",
    machine_id: "LTH-01",
    machine_name: "Okuma GENOS L300-M",
    controller_family: "okuma",
    controller_model: "OSP-P300L-R",
    material: "4140 Steel",
    customer: "ALCOA",
    part_number: "12345-A",
    operation_type: "turning",
    generated_at: "2026-04-17T12:00:00Z",
    generated_by: "PRISM Master Post",
    prism_version: "1.0.0",
    ...overrides,
  });

  const createBaseInput = (overrides: Partial<UnifyOutputInput> = {}): UnifyOutputInput => ({
    raw_gcode: "G00 X100 Z5\nG01 X50 Z0 F200\nG01 X50 Z-50 F200",
    metadata: createBaseMetadata(),
    tools: [
      { tool_number: 1, description: "OD ROUGHING", insert_type: "CNMG 432" },
      { tool_number: 2, description: "OD FINISHING", insert_type: "DNMG 432" },
    ],
    source_post: "PPOkumaTurningPostEngine",
    ...overrides,
  });

  describe("unify() - Header Generation", () => {
    it("includes program number in header", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("O1001");
    });

    it("includes program name in header", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("TEST_PART");
    });

    it("includes PRISM generator identification", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("GENERATED BY");
      expect(result.gcode).toContain("PRISM");
    });

    it("includes generation date", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("DATE:");
      expect(result.gcode).toContain("2026-04-17");
    });
  });

  describe("unify() - Metadata Block", () => {
    it("includes machine information", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.metadata_block).toContain("MACHINE:");
      expect(result.metadata_block).toContain("Okuma GENOS L300-M");
      expect(result.metadata_block).toContain("LTH-01");
    });

    it("includes controller model", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.metadata_block).toContain("CONTROLLER:");
      expect(result.metadata_block).toContain("OSP-P300L-R");
    });

    it("includes material when specified", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.metadata_block).toContain("MATERIAL:");
      expect(result.metadata_block).toContain("4140 Steel");
    });

    it("includes customer when specified", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.metadata_block).toContain("CUSTOMER:");
      expect(result.metadata_block).toContain("ALCOA");
    });
  });

  describe("unify() - Tool List Block", () => {
    it("includes tool list header", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.tool_list_block).toContain("TOOL LIST");
    });

    it("lists all tools with numbers", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.tool_list_block).toContain("T01");
      expect(result.tool_list_block).toContain("T02");
    });

    it("includes tool descriptions", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.tool_list_block).toContain("OD ROUGHING");
      expect(result.tool_list_block).toContain("OD FINISHING");
    });

    it("includes insert types", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.tool_list_block).toContain("CNMG 432");
      expect(result.tool_list_block).toContain("DNMG 432");
    });

    it("handles empty tool list gracefully", () => {
      const input = createBaseInput({ tools: [] });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.tool_list_block).toContain("none specified");
    });
  });

  describe("unify() - Safe Start Block", () => {
    it("includes G28 home command for Okuma", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("G28");
    });

    it("includes cancel codes (G40, G80)", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("G40");
      expect(result.gcode).toContain("G80");
    });

    it("includes spindle speed clamp (G50)", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("G50 S");
    });
  });

  describe("unify() - Footer", () => {
    it("includes coolant off (M09)", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("M09");
    });

    it("includes spindle stop (M05)", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("M05");
    });

    it("includes program end (M30)", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("M30");
    });

    it("ends with percent sign", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      const lines = result.gcode.split("\n");
      expect(lines[lines.length - 1]).toBe("%");
    });
  });

  describe("unify() - Line Counts", () => {
    it("reports accurate line count", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.line_count).toBe(result.gcode.split("\n").length);
    });

    it("reports header, body, and footer line counts", () => {
      const input = createBaseInput();
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.header_lines).toBeGreaterThan(0);
      expect(result.body_lines).toBeGreaterThan(0);
      expect(result.footer_lines).toBeGreaterThan(0);
    });
  });

  describe("unify() - Line Numbers", () => {
    it("adds line numbers when requested", () => {
      const input = createBaseInput({ include_line_numbers: true });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toMatch(/N\d+/);
    });

    it("starts line numbers at specified value", () => {
      const input = createBaseInput({
        include_line_numbers: true,
        line_number_start: 100,
      });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("N100");
    });

    it("increments line numbers by specified amount", () => {
      const input = createBaseInput({
        include_line_numbers: true,
        line_number_start: 10,
        line_number_increment: 5,
      });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("N10");
      expect(result.gcode).toContain("N15");
    });
  });

  describe("compareOutputs()", () => {
    it("identifies identical outputs", () => {
      const output = "G00 X100 Z5\nG01 X50 Z0 F200";
      const result = latheMasterPostUnifiedOutputEngine.compareOutputs(output, output);

      expect(result.identical).toBe(true);
      expect(result.dialect_differences.length).toBe(0);
    });

    it("detects code differences", () => {
      const output1 = "G00 X100 Z5";
      const output2 = "G00 X150 Z5";
      const result = latheMasterPostUnifiedOutputEngine.compareOutputs(output1, output2);

      expect(result.identical).toBe(false);
      expect(result.concerning_differences).toBeGreaterThan(0);
    });

    it("classifies comment-only differences correctly", () => {
      const output1 = "(RAPID MOVE)\nG00 X100 Z5";
      const output2 = "(FAST POSITIONING)\nG00 X100 Z5";
      const result = latheMasterPostUnifiedOutputEngine.compareOutputs(output1, output2);

      // When only comments differ, lines should be different but non-critical
      expect(result.dialect_differences.length).toBeGreaterThanOrEqual(0);
    });

    it("classifies reordered codes as order differences", () => {
      const output1 = "G00 X100 Z5";
      const output2 = "G00 Z5 X100";
      const result = latheMasterPostUnifiedOutputEngine.compareOutputs(output1, output2);

      // Reordered codes that have same values should be classified
      expect(result.dialect_differences.length).toBeGreaterThan(0);
      expect(result.dialect_differences[0]?.difference_type).toBe("order");
    });
  });

  describe("validateUnifiedFormat()", () => {
    it("validates complete unified output", () => {
      const input = createBaseInput();
      const unified = latheMasterPostUnifiedOutputEngine.unify(input);
      const validation = latheMasterPostUnifiedOutputEngine.validateUnifiedFormat(unified.gcode);

      expect(validation.valid).toBe(true);
      expect(validation.has_prism_header).toBe(true);
      expect(validation.has_metadata_block).toBe(true);
      expect(validation.has_proper_footer).toBe(true);
    });

    it("detects missing PRISM header", () => {
      const gcode = "O1001\nG00 X100\nM30";
      const validation = latheMasterPostUnifiedOutputEngine.validateUnifiedFormat(gcode);

      expect(validation.has_prism_header).toBe(false);
      expect(validation.issues.some(i => i.includes("PRISM"))).toBe(true);
    });

    it("detects missing program end", () => {
      const gcode = "O1001\n(PRISM GENERATED)\nG00 X100";
      const validation = latheMasterPostUnifiedOutputEngine.validateUnifiedFormat(gcode);

      expect(validation.has_proper_footer).toBe(false);
      expect(validation.issues.some(i => i.includes("M30"))).toBe(true);
    });
  });

  describe("Controller-specific Formatting", () => {
    it("uses correct comment characters for Siemens", () => {
      const input = createBaseInput({
        metadata: createBaseMetadata({ controller_family: "siemens" }),
      });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain(";");
    });

    it("uses parentheses for Fanuc comments", () => {
      const input = createBaseInput({
        metadata: createBaseMetadata({ controller_family: "fanuc" }),
      });
      const result = latheMasterPostUnifiedOutputEngine.unify(input);

      expect(result.gcode).toContain("(");
      expect(result.gcode).toContain(")");
    });
  });
});
