/**
 * UnifiedCADCodeGeneratorBase.test.ts — U-CADC00 (PHASE-0B)
 *
 * Covers the synergy layer: capability enforcement, op lineage, parameter /
 * warning / imports collection, execution error trapping, and default
 * validateOutput rules (empty geometry, zero faces, implausible volume,
 * negative bbox). Uses two fake subclasses — a minimal one and a richer one
 * with a subprocess-style execute.
 */

import { describe, it, expect } from "vitest";
import {
  UnifiedCADCodeGeneratorBase,
  UnsupportedCapabilityError,
  CADBuildError,
  type CADEmitter,
} from "../engines/UnifiedCADCodeGeneratorBase.js";
import type {
  CADCapabilityMatrix,
  CADExecutionResult,
  CADOperation,
  CADOperationKind,
  CADScript,
  CADSystemId,
} from "../interfaces/ICADCodeGenerator.js";

/** A stand-in CAD system for tests — not a real host. */
const FAKE_SYSTEM: CADSystemId = "cadquery";

class StubGenerator extends UnifiedCADCodeGeneratorBase<{ unitHint?: string }> {
  readonly cadSystem = FAKE_SYSTEM;
  readonly capabilities: CADCapabilityMatrix;
  execResult: CADExecutionResult = {
    ok: true,
    durationMs: 10,
    metrics: {
      volumeMm3: 1_000,
      boundingBoxMm: [10, 10, 10],
      faceCount: 6,
      edgeCount: 12,
      vertexCount: 8,
    },
  };

  constructor(supportedOps: CADOperationKind[]) {
    super();
    this.capabilities = {
      cadSystem: FAKE_SYSTEM,
      supportedOps: new Set(supportedOps),
      nativeLengthUnit: "mm",
      nativeAngleUnit: "deg",
      requiresSubprocess: true,
      typicalLatencyMs: 200,
    };
  }

  protected preamble(ctx: { unitHint?: string } | undefined, em: CADEmitter): void {
    em.require("numpy");
    em.require("numpy"); // dedup check
    em.line("# generated by StubGenerator");
    if (ctx?.unitHint) em.line(`# unit_hint: ${ctx.unitHint}`);
  }

  protected emitOp(
    op: CADOperation,
    _opIndex: number,
    _ctx: { unitHint?: string } | undefined,
    em: CADEmitter,
  ): void {
    if (op.kind === "feature_extrude") {
      const distance = this.requireArg<number>(op, "distance", "number");
      em.parameter("extrude_distance", distance, "mm", op.description);
      em.line(`extrude(${distance})`);
      if (distance > 500) {
        em.warn("extrude > 500 mm may be excessive", "warn");
      }
    } else if (op.kind === "sketch_create") {
      em.line("sketch = new_sketch()");
    } else if (op.kind === "custom") {
      em.block(String(op.args.body ?? "# noop"));
    } else {
      em.line(`# ${op.kind}`);
    }
  }

  protected epilogue(_ctx: unknown, em: CADEmitter): void {
    em.line("save()");
  }

  protected scriptFilename(): string {
    return "stub_script.py";
  }

  protected async runScriptBody(_script: CADScript<string>): Promise<CADExecutionResult> {
    return this.execResult;
  }
}

class ThrowingGenerator extends StubGenerator {
  protected emitOp(op: CADOperation): void {
    throw new Error(`boom at ${op.kind}`);
  }
}

class ThrowingRunGenerator extends StubGenerator {
  protected async runScriptBody(): Promise<CADExecutionResult> {
    throw new Error("subprocess died");
  }
}

describe("UnifiedCADCodeGeneratorBase (U-CADC00)", () => {
  describe("capability enforcement", () => {
    it("rejects ops whose kind is not in the capability set", () => {
      const gen = new StubGenerator(["sketch_create", "feature_extrude"]);
      const ops: CADOperation[] = [
        { kind: "sketch_create", args: {} },
        { kind: "feature_loft", args: {} }, // not supported
      ];
      expect(() => gen.buildScript(ops)).toThrow(UnsupportedCapabilityError);
      try {
        gen.buildScript(ops);
      } catch (err) {
        expect(err).toBeInstanceOf(UnsupportedCapabilityError);
        expect((err as UnsupportedCapabilityError).kind).toBe("feature_loft");
        expect((err as UnsupportedCapabilityError).opIndex).toBe(1);
      }
    });

    it("getCapabilities returns a snapshot that is independent of the generator's set", () => {
      const gen = new StubGenerator(["sketch_create"]);
      const snapshot = gen.getCapabilities();
      (snapshot.supportedOps as Set<CADOperationKind>).add("feature_extrude");
      expect(gen.capabilities.supportedOps.has("feature_extrude")).toBe(false);
    });
  });

  describe("build output", () => {
    it("emits preamble, ops, and epilogue in order with correct line numbers", () => {
      const gen = new StubGenerator(["sketch_create", "feature_extrude"]);
      const script = gen.buildScript([
        { kind: "sketch_create", args: {}, operationId: "op.a" },
        {
          kind: "feature_extrude",
          args: { distance: 25 },
          operationId: "op.b",
          description: "first pad",
        },
      ]);
      expect(script.cadSystem).toBe(FAKE_SYSTEM);
      expect(script.body.split("\n")[0]).toMatch(/generated by StubGenerator/);
      expect(script.body).toMatch(/save\(\)/);
      expect(script.lineage).toHaveLength(2);
      expect(script.lineage[0].kind).toBe("sketch_create");
      expect(script.lineage[0].operationId).toBe("op.a");
      expect(script.lineage[1].lineStart).toBeGreaterThan(
        script.lineage[0].lineEnd,
      );
    });

    it("records parameters declared via emitter.parameter()", () => {
      const gen = new StubGenerator(["feature_extrude"]);
      const script = gen.buildScript([
        {
          kind: "feature_extrude",
          args: { distance: 42 },
          description: "riser",
        },
      ]);
      const param = script.parameters.get("extrude_distance");
      expect(param?.value).toBe(42);
      expect(param?.unit).toBe("mm");
      expect(param?.description).toBe("riser");
    });

    it("deduplicates imports across ops", () => {
      const gen = new StubGenerator(["sketch_create"]);
      const script = gen.buildScript([
        { kind: "sketch_create", args: {} },
        { kind: "sketch_create", args: {} },
      ]);
      expect(script.imports.filter((i) => i === "numpy")).toHaveLength(1);
    });

    it("surfaces non-fatal warnings without throwing", () => {
      const gen = new StubGenerator(["feature_extrude"]);
      const script = gen.buildScript([
        { kind: "feature_extrude", args: { distance: 999 } },
      ]);
      expect(script.warnings).toHaveLength(1);
      expect(script.warnings[0].severity).toBe("warn");
      expect(script.warnings[0].message).toMatch(/excessive/);
    });

    it("passes context to preamble", () => {
      const gen = new StubGenerator(["sketch_create"]);
      const script = gen.buildScript([{ kind: "sketch_create", args: {} }], {
        unitHint: "mm",
      });
      expect(script.body).toMatch(/unit_hint: mm/);
    });

    it("block() expands multi-line text line-by-line", () => {
      const gen = new StubGenerator(["custom"]);
      const script = gen.buildScript([
        { kind: "custom", args: { body: "line1\nline2\nline3" } },
      ]);
      expect(script.body).toMatch(/line1/);
      expect(script.body).toMatch(/line2/);
      expect(script.body).toMatch(/line3/);
      const entry = script.lineage[0];
      expect(entry.lineEnd - entry.lineStart).toBeGreaterThanOrEqual(2);
    });
  });

  describe("argument validation", () => {
    it("requireArg throws CADBuildError when missing", () => {
      const gen = new StubGenerator(["feature_extrude"]);
      expect(() =>
        gen.buildScript([{ kind: "feature_extrude", args: {} }]),
      ).toThrow(CADBuildError);
    });

    it("requireArg throws CADBuildError when wrong type", () => {
      const gen = new StubGenerator(["feature_extrude"]);
      expect(() =>
        gen.buildScript([
          { kind: "feature_extrude", args: { distance: "tall" } },
        ]),
      ).toThrow(/must be number/);
    });

    it("wraps subclass emitOp throws into CADBuildError with op context", () => {
      const gen = new ThrowingGenerator(["sketch_create"]);
      try {
        gen.buildScript([{ kind: "sketch_create", args: {} }]);
        throw new Error("did not throw");
      } catch (err) {
        expect(err).toBeInstanceOf(CADBuildError);
        expect((err as CADBuildError).opIndex).toBe(0);
        expect((err as CADBuildError).kind).toBe("sketch_create");
        expect((err as Error).message).toMatch(/boom at sketch_create/);
      }
    });
  });

  describe("execution", () => {
    it("forwards successful subprocess result", async () => {
      const gen = new StubGenerator(["sketch_create"]);
      const script = gen.buildScript([{ kind: "sketch_create", args: {} }]);
      const res = await gen.executeScript(script);
      expect(res.ok).toBe(true);
      expect(res.metrics?.volumeMm3).toBe(1_000);
    });

    it("traps subprocess throws and returns ok:false", async () => {
      const gen = new ThrowingRunGenerator(["sketch_create"]);
      const script = gen.buildScript([{ kind: "sketch_create", args: {} }]);
      const res = await gen.executeScript(script);
      expect(res.ok).toBe(false);
      expect(res.error).toMatch(/subprocess died/);
      expect(res.durationMs).toBeGreaterThanOrEqual(0);
    });

    it("fills durationMs if subprocess omitted it", async () => {
      const gen = new StubGenerator(["sketch_create"]);
      gen.execResult = { ok: true, durationMs: 0, metrics: { faceCount: 1 } };
      const script = gen.buildScript([{ kind: "sketch_create", args: {} }]);
      const res = await gen.executeScript(script);
      // base overrides 0 with elapsed
      expect(res.durationMs).toBeGreaterThanOrEqual(0);
    });
  });

  describe("validateOutput default rules", () => {
    const gen = new StubGenerator(["sketch_create"]);

    it("marks failed execution as error", () => {
      const report = gen.validateOutput({
        ok: false,
        error: "bad",
        durationMs: 1,
      });
      expect(report.ok).toBe(false);
      expect(report.findings[0].code).toBe("EXEC_FAILED");
    });

    it("rejects zero / negative volume", () => {
      const report = gen.validateOutput({
        ok: true,
        durationMs: 1,
        metrics: { volumeMm3: 0, faceCount: 6 },
      });
      expect(report.ok).toBe(false);
      expect(report.findings.some((f) => f.code === "EMPTY_GEOMETRY")).toBe(
        true,
      );
    });

    it("warns on implausibly large volume but stays ok", () => {
      const report = gen.validateOutput({
        ok: true,
        durationMs: 1,
        metrics: { volumeMm3: 2e12, faceCount: 6 },
      });
      expect(report.ok).toBe(true);
      expect(report.findings.some((f) => f.code === "IMPLAUSIBLE_VOLUME")).toBe(
        true,
      );
    });

    it("rejects zero-face model", () => {
      const report = gen.validateOutput({
        ok: true,
        durationMs: 1,
        metrics: { volumeMm3: 100, faceCount: 0 },
      });
      expect(report.ok).toBe(false);
      expect(report.findings.some((f) => f.code === "NO_FACES")).toBe(true);
    });

    it("rejects negative bbox dimensions", () => {
      const report = gen.validateOutput({
        ok: true,
        durationMs: 1,
        metrics: {
          volumeMm3: 100,
          faceCount: 6,
          boundingBoxMm: [-1, 2, 3],
        },
      });
      expect(report.ok).toBe(false);
      expect(report.findings.some((f) => f.code === "NEGATIVE_BBOX")).toBe(
        true,
      );
    });

    it("accepts healthy output with no findings", () => {
      const report = gen.validateOutput({
        ok: true,
        durationMs: 1,
        metrics: {
          volumeMm3: 1_000,
          boundingBoxMm: [10, 10, 10],
          faceCount: 6,
        },
      });
      expect(report.ok).toBe(true);
      expect(report.findings).toHaveLength(0);
    });
  });
});
