// Pass-2 enrichment constants for Agent 3 (slug values in arrays to avoid prop:string regex)
const A_ENTRIES = [
  ["pipeline", "knowledge/wiki/architecture/domain-pipeline-ms0.md"],
  ["knowledgeConv", "knowledge/wiki/architecture/knowledge-conversion-ms0.md"],
  ["masterIdx", "knowledge/wiki/architecture/master-index-surface.md"],
  ["closeOut", "knowledge/wiki/architecture/close-out-audit.md"],
  ["ollamaMs0", "knowledge/wiki/architecture/ollama-pipeline-ms0.md"],
  ["sessionCont", "knowledge/wiki/architecture/session-continuity-stack.md"],
  ["perSlot", "knowledge/wiki/architecture/per-slot-claim-ms0.md"],
  ["fleetReaper", "knowledge/wiki/architecture/fleet-reaper.md"],
  ["obsidianFeed", "knowledge/wiki/architecture/obsidian-memory-feed-hook.md"],
  ["rgsMs0", "knowledge/wiki/architecture/rgs-tool-autoinvoke-ms0.md"],
  ["rgsMs1", "knowledge/wiki/architecture/rgs-tool-autoinvoke-ms1.md"],
  ["silentDrift", "knowledge/wiki/architecture/silent-close-out-drift.md"],
  ["priorityQ", "knowledge/wiki/architecture/priority-queue.md"],
  ["checkinLoop", "knowledge/wiki/architecture/checkin-loop-fullstack.md"],
  ["courseForgeStubs", "knowledge/wiki/architecture/course-forge-stubs-emitter.md"],
  ["courseForgeConv", "knowledge/wiki/architecture/course-forge-conversions.md"],
  ["featureGap", "knowledge/wiki/architecture/feature-gap-audit-2026-05-17.md"],
  ["knowledgeVault", "knowledge/wiki/architecture/knowledge-vault-schema.md"],
  ["costCascade", "knowledge/wiki/architecture/cost-cascade-ms0.md"],
  ["consensusCoord", "knowledge/wiki/architecture/consensus-coordinator.md"],
  ["memConflict", "knowledge/wiki/architecture/memory-conflict-resolver-engine.md"],
  ["skillAutoLoader", "knowledge/wiki/architecture/skill-auto-loader.md"],
  ["freecadInv", "knowledge/wiki/architecture/freecad-complete-inventory.md"],
  ["strategyKb", "knowledge/wiki/architecture/strategy-kb.md"],
  ["nnGraphMs0", "knowledge/wiki/architecture/nn-graph-ms0.md"],
  ["systemViz", "knowledge/wiki/architecture/system-viz.md"],
  ["shopFloor", "knowledge/wiki/architecture/shopfloorautomation.md"],
  ["fusionBridge", "knowledge/wiki/architecture/fusion-cam-bridge.md"],
  ["nngStratWire", "knowledge/wiki/architecture/u-nng-pipeline-stratified-wire.md"],
];
const A = Object.fromEntries(A_ENTRIES);
A.dom = (s) => "knowledge/wiki/architecture/domain-" + s + ".md";

const S_ENTRIES = [
  ["engine", "engine-creation-discipline"],
  ["realTests", "test-design-real-values"],
  ["hookSlug", "hook-authoring-discipline"],
  ["physicsConst", "physics-constants-discipline"],
  ["perFile", "per-file-scrutiny-gate"],
  ["atomic", "atomic-write-idempotency-patterns"],
  ["failLoud", "fail-loud-r12-patterns"],
  ["regression", "regression-prevention-doctrine"],
  ["schemaRead", "schema-read-discipline"],
  ["jsonlLedger", "jsonl-ledger-conventions"],
  ["mcp", "mcp-tool-design"],
  ["dispatcher", "dispatcher-action-design"],
  ["memoryCur", "memory-curation-discipline"],
  ["recall", "recall-injection-flow"],
  ["obsidian", "obsidian-vault-flow"],
  ["doc", "doc-reflection-rule"],
  ["handoff", "handoff-discipline"],
  ["tokenBud", "token-budget-management"],
  ["tsRecipes", "ts-error-recipe-bank"],
  ["wikiFront", "wiki-frontmatter-validation"],
  ["wikiAuto", "wiki-automation-discipline"],
  ["subagent", "subagent-orchestration-discipline"],
  ["parallel", "parallel-tool-call-discipline"],
  ["fleet", "fleet-coordination-discipline"],
  ["cron", "cron-and-scheduled-task-discipline"],
  ["commit", "commit-message-conventions"],
  ["selfUpdate", "prism-self-update-loop"],
  ["promptRails", "prompt-engineering-rails"],
  ["safetyTier", "safety-tier-discipline"],
  ["bashPS", "bash-vs-powershell-on-windows"],
  ["html", "html-companion-discipline"],
  ["loopState", "loop-state-tracking-discipline"],
  ["gitIdx", "git-shared-index-hazards"],
  ["slotWT", "slot-worktree-playbook"],
  ["k12", "karpathy-12-rule-discipline"],
  ["claudeMd", "claude-md-as-pointer-index"],
];
const S = Object.fromEntries(S_ENTRIES);

module.exports = { A, S };
