/**
 * viz-wiki-narrative.test.mjs -- real-assertion tests for the pure narrative
 * inject/strip/extract helpers. The load-bearing property is IDEMPOTENCY: the
 * post-pass runs every regen, so inject(inject(md,b),b) MUST equal inject(md,b)
 * or the wiki entries would accumulate duplicate blocks.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  splitFrontmatter,
  stripNarrative,
  narrativeBlock,
  injectNarrative,
  hasNarrative,
  extractContent,
  contentHash,
  NARRATIVE_START,
  NARRATIVE_END,
} from "./viz-wiki-narrative.mjs";

const FM = "---\ntitle: Domain X\ncategory: architecture\n---\n";
const BODY = "# Domain X\n\n| engine | count |\n|--------|-------|\n| Foo | 3 |\n";
const DOC = FM + BODY;

test("splitFrontmatter: with frontmatter splits at the closing ---", () => {
  const { frontmatter, body } = splitFrontmatter(DOC);
  assert.equal(frontmatter, FM);
  assert.equal(body, BODY);
  // frontmatter ends with a newline so a block can be appended cleanly
  assert.ok(frontmatter.endsWith("\n"));
});

test("splitFrontmatter: no frontmatter -> empty fm, whole body", () => {
  const { frontmatter, body } = splitFrontmatter(BODY);
  assert.equal(frontmatter, "");
  assert.equal(body, BODY);
});

test("splitFrontmatter: CRLF frontmatter handled", () => {
  const crlf = "---\r\ntitle: Y\r\n---\r\nbody here";
  const { frontmatter, body } = splitFrontmatter(crlf);
  assert.ok(frontmatter.startsWith("---"));
  assert.equal(body, "body here");
});

test("splitFrontmatter: ADVERSARIAL non-string -> empty", () => {
  for (const x of [null, undefined, 42, {}]) {
    assert.deepEqual(splitFrontmatter(x), { frontmatter: "", body: "" });
  }
});

test("narrativeBlock: blurb -> markers + blurb; empty -> ''", () => {
  const b = narrativeBlock("It situates the mill layer.");
  assert.ok(b.includes(NARRATIVE_START));
  assert.ok(b.includes(NARRATIVE_END));
  assert.ok(b.includes("It situates the mill layer."));
  assert.equal(narrativeBlock(""), "");
  assert.equal(narrativeBlock("   "), "");
  assert.equal(narrativeBlock(null), "");
});

test("injectNarrative: inserts block right after frontmatter", () => {
  const out = injectNarrative(DOC, "A blurb.");
  assert.ok(out.startsWith(FM)); // frontmatter preserved at top
  const afterFm = out.slice(FM.length);
  assert.ok(afterFm.startsWith(NARRATIVE_START)); // block immediately after fm
  assert.ok(out.includes(BODY)); // body preserved
  assert.ok(hasNarrative(out));
});

test("injectNarrative: IDEMPOTENT -- double inject == single inject (no dup block)", () => {
  const once = injectNarrative(DOC, "A blurb.");
  const twice = injectNarrative(once, "A blurb.");
  assert.equal(twice, once);
  // exactly one start marker
  assert.equal(once.split(NARRATIVE_START).length - 1, 1);
});

test("injectNarrative: replaces a STALE block (new blurb, only new survives)", () => {
  const v1 = injectNarrative(DOC, "Old blurb.");
  const v2 = injectNarrative(v1, "New blurb.");
  assert.equal(v2.split(NARRATIVE_START).length - 1, 1); // still one block
  assert.ok(v2.includes("New blurb."));
  assert.ok(!v2.includes("Old blurb."));
});

test("injectNarrative: empty blurb STRIPS an existing block, no-op when none", () => {
  const withBlock = injectNarrative(DOC, "Blurb.");
  const stripped = injectNarrative(withBlock, "");
  assert.ok(!hasNarrative(stripped));
  assert.equal(stripped, DOC); // back to original
  // no-op on a doc that never had a block
  assert.equal(injectNarrative(DOC, ""), DOC);
});

test("injectNarrative: no-frontmatter doc -> block at top", () => {
  const out = injectNarrative(BODY, "Blurb.");
  assert.ok(out.startsWith(NARRATIVE_START));
  assert.ok(out.includes(BODY));
  // idempotent here too
  assert.equal(injectNarrative(out, "Blurb."), out);
});

test("stripNarrative: removes block; no-op when absent; removes DUPLICATED blocks", () => {
  const withBlock = injectNarrative(DOC, "Blurb.");
  assert.equal(stripNarrative(withBlock), DOC);
  assert.equal(stripNarrative(DOC), DOC); // absent -> unchanged
  // ADVERSARIAL: a torn/duplicated double block is fully removed
  const dup = FM + narrativeBlock("one") + narrativeBlock("two") + BODY;
  const cleaned = stripNarrative(dup);
  assert.ok(!cleaned.includes(NARRATIVE_START));
  assert.ok(cleaned.includes(BODY));
});

test("strip/inject leave the generators' AUTO-START/AUTO-END blocks untouched", () => {
  // The 3 viz->wiki generators idempotently update their bodies between
  // `<!-- AUTO-START ... -->` / `<!-- AUTO-END -->`. Our narrative markers are
  // distinct literals, so strip/inject must NEVER eat an AUTO block.
  const AUTO = "<!-- AUTO-START -- regenerated by generate-domain-wiki.mjs -->\n| x | 1 |\n<!-- AUTO-END -->\n";
  const docWithAuto = FM + AUTO + "trailing\n";
  // inject puts the narrative AFTER frontmatter, BEFORE the AUTO block; AUTO survives verbatim
  const injected = injectNarrative(docWithAuto, "A blurb.");
  assert.ok(injected.includes(AUTO), "AUTO block preserved verbatim");
  assert.ok(injected.includes(NARRATIVE_START));
  // stripping the narrative leaves the AUTO block + body exactly as before inject
  assert.equal(stripNarrative(injected), docWithAuto);
  // idempotent with AUTO present
  assert.equal(injectNarrative(injected, "A blurb."), injected);
});

test("extractContent: strips frontmatter + existing narrative, caps length", () => {
  const withBlock = injectNarrative(DOC, "Existing blurb that must NOT feed back in.");
  const content = extractContent(withBlock);
  assert.ok(!content.includes("title: Domain X")); // frontmatter gone
  assert.ok(!content.includes("Existing blurb")); // own narrative gone (no feedback loop)
  assert.ok(content.includes("Domain X")); // the H1 + table survive
  // cap honored
  const huge = FM + "# T\n" + "x".repeat(10000);
  assert.equal(extractContent(huge, { maxContentChars: 500 }).length, 500);
  // bad cap -> default
  assert.ok(extractContent(huge, { maxContentChars: -5 }).length <= 4000);
});

test("hasNarrative: true after inject, false before", () => {
  assert.equal(hasNarrative(DOC), false);
  assert.equal(hasNarrative(injectNarrative(DOC, "b")), true);
  assert.equal(hasNarrative(null), false);
});

test("contentHash: deterministic, 16 hex, content-sensitive", () => {
  assert.equal(contentHash("abc"), contentHash("abc"));
  assert.notEqual(contentHash("abc"), contentHash("abd"));
  assert.match(contentHash("abc"), /^[0-9a-f]{16}$/);
  assert.equal(contentHash(null), contentHash("")); // non-string -> empty, no throw
});
