/**
 * MillingResultsPage — Results display for milling program generation.
 *
 * Tabs: Summary | Toolpath | Setup Sheet | G-Code
 * Exports: NC file, setup sheet (.txt), AI recommendations
 * Edit-and-rerun: navigates back to wizard with state preserved.
 *
 * MILL-WEB M1: U-MWRES03
 */

import { useCallback, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  ActionButton,
  PanelCard,
  SummaryTile,
  WorkspaceHero,
} from '../components/workspace/WorkspacePrimitives';

// ── Types ─────────────────────────────────────────────────────────────────────

type ResultTab = 'summary' | 'toolpath' | 'setup' | 'gcode' | 'ai';

interface MillingTool {
  number: number;
  description: string;
  diameter_mm: number;
  operation: string;
  cutting_time_min: number;
  rpm?: number;
  feed_mmpm?: number;
}

interface MillingOperation {
  id: string;
  strategy: string;
  tool_number: number;
  depth_mm?: number;
  stepover_pct?: number;
  passes?: number;
  estimated_time_min?: number;
}

interface MillingResult {
  program_text?: string;
  cycle_time_s?: number;
  setup_time_min?: number;
  cost_per_part?: number;
  cost_breakdown?: Record<string, number>;
  material_removal_rate_cm3_min?: number;
  surface_finish_Ra_um?: number;
  confidence_score?: number;
  safety_score?: number;
  tools?: MillingTool[];
  operations?: MillingOperation[];
  setup_notes?: string[];
  warnings?: string[];
  ai_recommendations?: string[];
  controller?: string;
  machine_name?: string;
}

interface MillingResultsLocationState {
  result?: MillingResult | null;
  jobId?: string;
  fileName?: string;
  fileRoute?: string;
  material?: string;
  machine?: string;
  strategies?: string[];
  qualityTier?: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  if (m === 0) return `${s}s`;
  return `${m}m ${String(s).padStart(2, '0')}s`;
}

function formatCost(cost: number): string {
  return `$${cost.toFixed(2)}`;
}

function confidenceColor(score: number): string {
  if (score >= 0.85) return 'text-emerald-400';
  if (score >= 0.60) return 'text-amber-400';
  return 'text-red-400';
}

function confidenceLabel(score: number): string {
  if (score >= 0.85) return 'High confidence';
  if (score >= 0.60) return 'Medium confidence';
  return 'Low confidence — review recommended';
}

function safetyColor(score: number): string {
  if (score >= 80) return 'text-emerald-400';
  if (score >= 50) return 'text-amber-400';
  return 'text-red-400';
}

function buildSetupSheetText(
  locState: MillingResultsLocationState | null,
  result: MillingResult,
): string {
  const lines: string[] = [
    '=== Kienzle MILLING SETUP SHEET ===',
    `File: ${locState?.fileName ?? 'unknown'}`,
    `Material: ${locState?.material ?? 'unknown'}`,
    `Machine: ${locState?.machine ?? result.machine_name ?? 'unknown'}`,
    `Quality: ${locState?.qualityTier ?? 'precision'}`,
    `Strategies: ${locState?.strategies?.join(', ') ?? '—'}`,
    '',
    '--- CYCLE TIME ---',
    `Cycle time: ${result.cycle_time_s ? formatTime(result.cycle_time_s) : '—'}`,
    `Setup time: ${result.setup_time_min != null ? `${result.setup_time_min} min` : '—'}`,
    '',
    '--- TOOLING ---',
    ...(result.tools ?? []).map(t =>
      `T${t.number}: ${t.description} | D${t.diameter_mm}mm | ${t.operation} | ${t.cutting_time_min?.toFixed(1) ?? '?'} min`,
    ),
    '',
    '--- SETUP NOTES ---',
    ...(result.setup_notes ?? ['No setup notes generated.']),
    '',
    '--- WARNINGS ---',
    ...(result.warnings ?? ['None']),
    '',
    `Generated by Kienzle Manufacturing Intelligence — ${new Date().toISOString()}`,
  ];
  return lines.join('\n');
}

function buildSVGToolpath(operations: MillingOperation[], tools: MillingTool[]): string {
  const W = 400;
  const H = 300;
  const colors = ['#8b5cf6', '#06b6d4', '#10b981', '#f59e0b', '#ef4444', '#a78bfa'];

  const rects = operations.map((op, i) => {
    const tool   = tools.find(t => t.number === op.tool_number);
    const diamMm = tool?.diameter_mm ?? 10;
    const x      = 20 + (i % 4) * 90;
    const y      = 20 + Math.floor(i / 4) * 80;
    const color  = colors[i % colors.length];
    return `
      <rect x="${x}" y="${y}" width="${diamMm * 3}" height="${(op.passes ?? 1) * 12}"
        fill="${color}" fill-opacity="0.18" stroke="${color}" stroke-width="1.2" rx="3"/>
      <text x="${x + 4}" y="${y + 14}" fill="${color}" font-size="10">${op.strategy.slice(0, 8)}</text>
    `;
  });

  if (rects.length === 0) {
    rects.push(`
      <text x="${W / 2}" y="${H / 2}" fill="#52525b" font-size="13" text-anchor="middle"
        dominant-baseline="middle">No toolpath data — connect backend to generate.</text>
    `);
  }

  return `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"
      style="background:#18181b;border-radius:8px">
      <rect width="${W}" height="${H}" fill="#18181b" rx="8"/>
      ${rects.join('')}
    </svg>
  `;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function MillingResultsPage() {
  const location  = useLocation();
  const navigate  = useNavigate();
  const [activeTab, setActiveTab] = useState<ResultTab>('summary');

  const locState = (location.state as MillingResultsLocationState | null) ?? null;

  const result: MillingResult = useMemo(() => locState?.result ?? {
    program_text: '(No program generated — check backend connection)',
    cycle_time_s: 0,
    cost_per_part: 0,
    confidence_score: 0,
    safety_score: 0,
    tools: [],
    operations: [],
    setup_notes: ['No setup notes — backend not connected.'],
    warnings: [],
    ai_recommendations: ['Connect the milling backend to receive AI recommendations.'],
  }, [locState]);

  const triggerDownload = useCallback((content: string, fileName: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10_000);
  }, []);

  const handleDownloadNC = useCallback(() => {
    const baseName = (locState?.fileName ?? 'milling-program').replace(/\.[^.]+$/, '');
    triggerDownload(result.program_text ?? '', `${baseName}.nc`);
  }, [locState, result.program_text, triggerDownload]);

  const handleDownloadSetup = useCallback(() => {
    const baseName = (locState?.fileName ?? 'milling-setup').replace(/\.[^.]+$/, '');
    triggerDownload(buildSetupSheetText(locState, result), `${baseName}-setup.txt`);
  }, [locState, result, triggerDownload]);

  const handleEdit = useCallback(() => {
    navigate('/milling/wizard', {
      state: {
        fileName:  locState?.fileName,
        fileRoute: locState?.fileRoute,
        material:  locState?.material,
        machine:   locState?.machine,
        strategies: locState?.strategies,
        qualityTier: locState?.qualityTier,
      },
    });
  }, [navigate, locState]);

  const sec = 'bg-zinc-900/80 border border-zinc-700/50 rounded-xl p-5';
  const lbl = 'text-[10px] text-zinc-500 uppercase tracking-wide';

  const cycleTime   = result.cycle_time_s ?? 0;
  const confidence  = result.confidence_score ?? 0;
  const safetyScore = result.safety_score ?? 0;

  const toolpathSVG = buildSVGToolpath(result.operations ?? [], result.tools ?? []);

  const TABS: Array<{ id: ResultTab; label: string }> = [
    { id: 'summary',  label: 'Summary' },
    { id: 'toolpath', label: 'Toolpath' },
    { id: 'setup',    label: 'Setup Sheet' },
    { id: 'gcode',    label: 'G-Code' },
    { id: 'ai',       label: 'AI Recommendations' },
  ];

  return (
    <div className="mx-auto flex w-full max-w-[1520px] flex-col gap-6 pb-12">
      <WorkspaceHero
        eyebrow={`Milling Results: ${locState?.fileName ?? 'Program'}`}
        title="Milling Program Generated"
        description={[
          locState?.material,
          locState?.machine,
          locState?.qualityTier,
          (locState?.strategies ?? []).join(', '),
        ].filter(Boolean).join(' | ')}
        metrics={
          <>
            <SummaryTile
              label="Cycle Time"
              value={cycleTime > 0 ? formatTime(cycleTime) : '—'}
              hint="estimated"
            />
            <SummaryTile
              label="Cost / Part"
              value={result.cost_per_part ? formatCost(result.cost_per_part) : '—'}
              hint="machine + tooling"
              accent="from-emerald-400/22 via-emerald-300/8 to-transparent"
            />
            <SummaryTile
              label="Confidence"
              value={confidence > 0 ? `${Math.round(confidence * 100)}%` : '—'}
              hint={confidence > 0 ? confidenceLabel(confidence) : 'not available'}
              accent="from-violet-400/22 via-violet-300/8 to-transparent"
            />
            <SummaryTile
              label="Safety"
              value={safetyScore > 0 ? `${safetyScore}/100` : '—'}
              hint="physics check"
              accent="from-amber-400/22 via-amber-300/8 to-transparent"
            />
          </>
        }
      />

      {/* Action bar */}
      <div className="flex flex-wrap gap-3">
        <ActionButton onClick={handleDownloadNC}>
          Download NC File
        </ActionButton>
        <ActionButton onClick={handleDownloadSetup}>
          Download Setup Sheet
        </ActionButton>
        <ActionButton onClick={handleEdit}>
          Edit & Re-Run
        </ActionButton>
        <ActionButton onClick={() => navigate('/milling')}>
          New Job
        </ActionButton>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 border-b border-zinc-700/50">
        {TABS.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`rounded-t-lg px-4 py-2 text-sm font-medium transition-colors ${
              activeTab === tab.id
                ? 'border-b-2 border-violet-400 bg-zinc-800/60 text-violet-300'
                : 'text-zinc-400 hover:bg-zinc-800/40 hover:text-zinc-200'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab: Summary */}
      {activeTab === 'summary' && (
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          {/* Metrics */}
          <div className={sec}>
            <h3 className="mb-4 text-sm font-semibold text-zinc-200">Program Summary</h3>
            <div className="grid grid-cols-2 gap-3">
              <MetricRow label="Cycle Time" value={cycleTime > 0 ? formatTime(cycleTime) : '—'} />
              <MetricRow
                label="Setup Time"
                value={result.setup_time_min ? `${result.setup_time_min} min` : '—'}
              />
              <MetricRow
                label="Cost / Part"
                value={result.cost_per_part ? formatCost(result.cost_per_part) : '—'}
              />
              <MetricRow
                label="MRR"
                value={result.material_removal_rate_cm3_min
                  ? `${result.material_removal_rate_cm3_min.toFixed(2)} cm³/min`
                  : '—'}
              />
              <MetricRow
                label="Surface Finish"
                value={result.surface_finish_Ra_um ? `Ra ${result.surface_finish_Ra_um} um` : '—'}
              />
              <MetricRow
                label="Controller"
                value={result.controller ?? result.machine_name ?? locState?.machine ?? '—'}
              />
            </div>
          </div>

          {/* Confidence & Safety */}
          <div className={sec}>
            <h3 className="mb-4 text-sm font-semibold text-zinc-200">Physics Validation</h3>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs text-zinc-400">Confidence Score</span>
                <span className={`text-sm font-semibold ${confidenceColor(confidence)}`}>
                  {confidence > 0 ? `${Math.round(confidence * 100)}%` : '—'}
                </span>
              </div>
              {confidence > 0 && (
                <div className="h-1.5 overflow-hidden rounded-full bg-zinc-700">
                  <div
                    className={`h-full rounded-full ${confidence >= 0.85 ? 'bg-emerald-400' : confidence >= 0.6 ? 'bg-amber-400' : 'bg-red-400'}`}
                    style={{ width: `${Math.round(confidence * 100)}%` }}
                  />
                </div>
              )}
              <div className="flex items-center justify-between">
                <span className="text-xs text-zinc-400">Safety Score</span>
                <span className={`text-sm font-semibold ${safetyColor(safetyScore)}`}>
                  {safetyScore > 0 ? `${safetyScore}/100` : '—'}
                </span>
              </div>
              {safetyScore > 0 && (
                <div className="h-1.5 overflow-hidden rounded-full bg-zinc-700">
                  <div
                    className={`h-full rounded-full ${safetyScore >= 80 ? 'bg-emerald-400' : safetyScore >= 50 ? 'bg-amber-400' : 'bg-red-400'}`}
                    style={{ width: `${safetyScore}%` }}
                  />
                </div>
              )}
              {(result.warnings ?? []).length > 0 && (
                <div className="mt-3 space-y-1">
                  <span className="text-xs font-semibold text-amber-400">Warnings</span>
                  {result.warnings!.map((w, i) => (
                    <p key={i} className="text-xs text-zinc-400">{w}</p>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Cost Breakdown */}
          {result.cost_breakdown && Object.keys(result.cost_breakdown).length > 0 && (
            <div className={sec}>
              <h3 className="mb-4 text-sm font-semibold text-zinc-200">Cost Breakdown</h3>
              <div className="space-y-2">
                {Object.entries(result.cost_breakdown).map(([key, val]) => (
                  <div key={key} className="flex items-center justify-between">
                    <span className="text-xs capitalize text-zinc-400">{key.replace(/_/g, ' ')}</span>
                    <span className="text-sm text-zinc-200">{formatCost(val)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Tool List */}
          {(result.tools ?? []).length > 0 && (
            <div className={sec}>
              <h3 className="mb-4 text-sm font-semibold text-zinc-200">Tooling List</h3>
              <div className="space-y-2">
                {result.tools!.map(t => (
                  <div
                    key={t.number}
                    className="flex items-start gap-3 rounded-lg bg-zinc-800/40 px-3 py-2"
                  >
                    <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-violet-500/20 text-xs font-bold text-violet-300">
                      T{t.number}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-medium text-zinc-200">{t.description}</p>
                      <p className="text-[11px] text-zinc-500">
                        D{t.diameter_mm}mm | {t.operation}
                        {t.rpm ? ` | ${t.rpm} RPM` : ''}
                        {t.feed_mmpm ? ` | ${t.feed_mmpm} mm/min` : ''}
                      </p>
                    </div>
                    <span className="text-[11px] text-zinc-400 shrink-0">
                      {t.cutting_time_min?.toFixed(1)} min
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Tab: Toolpath */}
      {activeTab === 'toolpath' && (
        <div className={sec}>
          <h3 className="mb-4 text-sm font-semibold text-zinc-200">Toolpath Preview</h3>
          <div className="flex justify-center">
            <div
              // eslint-disable-next-line react/no-danger
              dangerouslySetInnerHTML={{ __html: toolpathSVG }}
              className="rounded-lg overflow-hidden"
            />
          </div>
          {(result.operations ?? []).length > 0 && (
            <div className="mt-4 space-y-2">
              <p className="text-xs font-semibold text-zinc-400 uppercase tracking-wide">Operations</p>
              {result.operations!.map((op, i) => (
                <div key={op.id ?? i} className="flex items-center gap-3 rounded-lg bg-zinc-800/40 px-3 py-2">
                  <span className="text-[11px] font-semibold text-violet-300 w-24 shrink-0 capitalize">
                    {op.strategy}
                  </span>
                  <span className="text-[11px] text-zinc-400">T{op.tool_number}</span>
                  {op.depth_mm != null && (
                    <span className="text-[11px] text-zinc-500">Depth: {op.depth_mm} mm</span>
                  )}
                  {op.stepover_pct != null && (
                    <span className="text-[11px] text-zinc-500">Stepover: {op.stepover_pct}%</span>
                  )}
                  {op.passes != null && (
                    <span className="text-[11px] text-zinc-500">{op.passes} passes</span>
                  )}
                  {op.estimated_time_min != null && (
                    <span className="ml-auto text-[11px] text-zinc-400 shrink-0">
                      {op.estimated_time_min.toFixed(1)} min
                    </span>
                  )}
                </div>
              ))}
            </div>
          )}
          {(result.operations ?? []).length === 0 && (
            <p className="mt-4 text-center text-sm text-zinc-500">
              No operation data — connect the milling backend to generate toolpath operations.
            </p>
          )}
        </div>
      )}

      {/* Tab: Setup Sheet */}
      {activeTab === 'setup' && (
        <div className={sec}>
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-zinc-200">Setup Sheet</h3>
            <ActionButton onClick={handleDownloadSetup}>Download .txt</ActionButton>
          </div>
          <div className="space-y-4">
            <SetupSection title="Job Info">
              <p className={lbl}>File</p>
              <p className="text-sm text-zinc-200">{locState?.fileName ?? '—'}</p>
              <p className={`${lbl} mt-2`}>Material</p>
              <p className="text-sm text-zinc-200">{locState?.material ?? '—'}</p>
              <p className={`${lbl} mt-2`}>Machine</p>
              <p className="text-sm text-zinc-200">{locState?.machine ?? result.machine_name ?? '—'}</p>
              <p className={`${lbl} mt-2`}>Quality</p>
              <p className="text-sm text-zinc-200">{locState?.qualityTier ?? '—'}</p>
            </SetupSection>
            <SetupSection title="Tooling">
              {(result.tools ?? []).length > 0 ? (
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-zinc-500">
                      <th className="text-left py-1">T#</th>
                      <th className="text-left py-1">Description</th>
                      <th className="text-left py-1">Dia (mm)</th>
                      <th className="text-left py-1">Operation</th>
                      <th className="text-right py-1">Time (min)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {result.tools!.map(t => (
                      <tr key={t.number} className="border-t border-zinc-700/40 text-zinc-300">
                        <td className="py-1">T{t.number}</td>
                        <td className="py-1">{t.description}</td>
                        <td className="py-1">{t.diameter_mm}</td>
                        <td className="py-1">{t.operation}</td>
                        <td className="py-1 text-right">{t.cutting_time_min?.toFixed(1)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : (
                <p className="text-sm text-zinc-500">No tooling data — connect backend.</p>
              )}
            </SetupSection>
            <SetupSection title="Setup Notes">
              {(result.setup_notes ?? []).map((note, i) => (
                <p key={i} className="text-sm text-zinc-300">{note}</p>
              ))}
            </SetupSection>
          </div>
        </div>
      )}

      {/* Tab: G-Code */}
      {activeTab === 'gcode' && (
        <div className={sec}>
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-zinc-200">G-Code Preview</h3>
            <ActionButton onClick={handleDownloadNC}>Download .nc</ActionButton>
          </div>
          <pre className="max-h-[500px] overflow-auto rounded-lg bg-zinc-950 p-4 text-xs leading-relaxed text-emerald-300 font-mono">
            {result.program_text ?? '(No program generated)'}
          </pre>
        </div>
      )}

      {/* Tab: AI Recommendations */}
      {activeTab === 'ai' && (
        <div className={sec}>
          <h3 className="mb-4 text-sm font-semibold text-zinc-200">AI Recommendations</h3>
          {(result.ai_recommendations ?? []).length > 0 ? (
            <ul className="space-y-3">
              {result.ai_recommendations!.map((rec, i) => (
                <li key={i} className="flex gap-3 rounded-lg bg-violet-500/8 px-4 py-3 border border-violet-500/20">
                  <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-500/20 text-[11px] font-bold text-violet-300">
                    {i + 1}
                  </span>
                  <p className="text-sm text-zinc-300 leading-relaxed">{rec}</p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-zinc-500">
              No AI recommendations available. Connect the MillingMachineIntelligenceEngine backend to receive physics-driven advice.
            </p>
          )}
          <div className="mt-6 rounded-lg border border-zinc-700/40 bg-zinc-800/30 p-4">
            <p className="text-xs font-semibold text-zinc-400 uppercase tracking-wide mb-2">Physics Engines Used</p>
            <div className="flex flex-wrap gap-2">
              {[
                'KienzleForceModel',
                'CuttingTemperatureEngine',
                'ToolWearProgressionEngine',
                'ChatterStabilityLobe',
                'SurfaceFinishPredictor',
                'MillingMachineIntelligenceEngine',
              ].map(engine => (
                <span key={engine} className="rounded bg-zinc-700/60 px-2 py-0.5 text-[10px] text-zinc-400">
                  {engine}
                </span>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────────

function MetricRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg bg-zinc-800/40 px-3 py-2">
      <p className="text-[10px] text-zinc-500 uppercase tracking-wide">{label}</p>
      <p className="mt-0.5 text-sm font-semibold text-zinc-200">{value}</p>
    </div>
  );
}

function SetupSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-zinc-700/40 bg-zinc-800/30 p-4">
      <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-zinc-400">{title}</p>
      {children}
    </div>
  );
}
