$env:SystemRoot = 'C:\Windows'
$env:windir = 'C:\Windows'
$env:ComSpec = 'C:\Windows\System32\cmd.exe'
$env:PATHEXT = '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL'
Set-Location 'C:\PRISM\mcp-server\web'
& 'C:\Program Files\nodejs\npm.cmd' 'run' 'dev' '--' '--host' '127.0.0.1' '--port' '3100'
