$env:SystemRoot = 'C:\Windows'
$env:windir = 'C:\Windows'
$env:ComSpec = 'C:\Windows\System32\cmd.exe'
$env:PATHEXT = '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL'
$env:TRANSPORT = 'http'
$env:PORT = '3000'
$env:PRISM_BIND_HOST = '127.0.0.1'
Set-Location 'C:\PRISM\mcp-server'
& 'C:\Program Files\nodejs\npm.cmd' 'run' 'dev'
