#!/usr/bin/env python3
"""Generate TypeScript catalog files from extracted JSON for new manufacturers."""

import json, os

data_path = "C:/PRISM/mcp-server/src/data/"

# Load all new extractions
sources = [
    ("flash-tools-extracted.json", "Flash"),
    ("ma-ford-tools-extracted.json", "MA Ford"),
    ("korloy-tools-extracted.json", "Korloy"),
    ("unknown_solid-tools-extracted.json", "Generic"),
    ("rapidkut-tools-extracted.json", "Rapidkut"),
    ("yg1-tools-extracted.json", "YG-1"),
    ("accupro-tools-extracted.json", "Accupro"),
]

all_tools = []
seen = set()
for fn, mfg in sources:
    fp = os.path.join(data_path, fn)
    if not os.path.exists(fp):
        continue
    with open(fp) as f:
        tools = json.load(f)
    count = 0
    for t in tools:
        t["manufacturer"] = mfg
        # Ensure required fields exist
        if "cutting_diameter_mm" not in t or not t["cutting_diameter_mm"]:
            continue
        if "shank_diameter_mm" not in t:
            t["shank_diameter_mm"] = t["cutting_diameter_mm"]
        desig = t.get("designation", "")
        key = f"{mfg}-{desig}"
        if key in seen:
            continue
        seen.add(key)
        all_tools.append(t)
        count += 1
    print(f"{mfg}: {count} tools")

print(f"\nTotal: {len(all_tools)} tools")

# Generate TypeScript
lines = []
lines.append("// @ts-nocheck")
lines.append("// Additional manufacturer tools - extracted from PDF catalogs")
lines.append(f"// {len(all_tools)} tools from Flash, MA Ford, Korloy, Rapidkut, Generic + YG-1")
lines.append("// Generated by scripts/generate-additional-catalog-ts.py")
lines.append("")
lines.append("export interface AdditionalTool {")
lines.append("  designation: string;")
lines.append("  manufacturer: string;")
lines.append("  type: string;")
lines.append("  cutting_diameter_mm: number;")
lines.append("  shank_diameter_mm: number;")
lines.append("  overall_length_mm?: number;")
lines.append("  flute_length_mm?: number;")
lines.append("  corner_radius_mm?: number;")
lines.append("  flute_count?: number;")
lines.append("}")
lines.append("")
lines.append("export const ADDITIONAL_TOOLS: AdditionalTool[] = [")

for t in all_tools:
    parts = []
    d = t["designation"].replace('"', "'").replace("\n", "")
    parts.append(f'designation:"{d}"')
    parts.append(f'manufacturer:"{t["manufacturer"]}"')
    parts.append(f'type:"{t["type"]}"')
    parts.append(f'cutting_diameter_mm:{t["cutting_diameter_mm"]}')
    parts.append(f'shank_diameter_mm:{t["shank_diameter_mm"]}')
    if t.get("overall_length_mm") is not None:
        parts.append(f'overall_length_mm:{t["overall_length_mm"]}')
    if t.get("flute_length_mm") is not None:
        parts.append(f'flute_length_mm:{t["flute_length_mm"]}')
    if t.get("corner_radius_mm") is not None:
        parts.append(f'corner_radius_mm:{t["corner_radius_mm"]}')
    if t.get("flute_count") is not None:
        parts.append(f'flute_count:{t["flute_count"]}')
    lines.append("  {" + ",".join(parts) + "},")

lines.append("];")
lines.append("")

out_path = os.path.join(data_path, "additional-tool-catalog.ts")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Generated {out_path}: {len(lines)} lines")
