#!/usr/bin/env python3
"""Generate TypeScript catalog from extracted Tungaloy turning JSON."""
import sys, io, json

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

with open('C:/PRISM/mcp-server/src/data/tungaloy-turning-extracted.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

lines = []

# Header
lines.append('/**')
lines.append(' * Tungaloy Turning/Grooving/Threading Insert Catalog')
lines.append(f' * {data["summary"]["total_items"]} items extracted from GC_2023-2024_G_Turning-Grooving.pdf')
lines.append(f' * {data["summary"]["turning_inserts"]} turning + {data["summary"]["threading_inserts"]} threading + {data["summary"]["grooving_inserts"]} grooving inserts')
lines.append(f' * {data["summary"]["cutting_conditions"]} cutting condition entries across 18 grades')
lines.append(' * Generated by extract-tungaloy-turning.py')
lines.append(' */')
lines.append('')

# Interfaces
lines.append('export interface TungaloyTurningInsert {')
lines.append('  designation: string;')
lines.append('  type: "turning_insert";')
lines.append('  insert_shape: string;')
lines.append('  shape_code: string;')
lines.append('  clearance_angle: string;')
lines.append('  tolerance_class: string;')
lines.append('  fixing_type: string;')
lines.append('  nose_radius_mm: number;')
lines.append('  ic_mm: number;')
lines.append('  thickness_mm: number;')
lines.append('  chipbreaker: string;')
lines.append('  edge_length_mm?: number;')
lines.append('  available_grades?: string[];')
lines.append('}')
lines.append('')

lines.append('export interface TungaloyThreadingInsert {')
lines.append('  designation: string;')
lines.append('  type: "threading_insert";')
lines.append('  ic_mm: number;')
lines.append('  direction: "external" | "internal";')
lines.append('  thread_type: string;')
lines.append('  thread_angle_deg: number;')
lines.append('  profile: "full" | "partial" | "multi-start";')
lines.append('  chipbreaker: string;')
lines.append('  pdx_mm?: number;')
lines.append('  pdy_mm?: number;')
lines.append('  re_mm?: number;')
lines.append('  pitch_min_mm?: number;')
lines.append('  pitch_max_mm?: number;')
lines.append('  tpi_min?: number;')
lines.append('  tpi_max?: number;')
lines.append('  available_grades?: string[];')
lines.append('}')
lines.append('')

lines.append('export interface TungaloyGroovingInsert {')
lines.append('  designation: string;')
lines.append('  type: "grooving_insert";')
lines.append('  family: string;')
lines.append('  width_mm: number | null;')
lines.append('  hand?: "right" | "left";')
lines.append('  cutting_width_mm?: number;')
lines.append('  corner_radius_mm?: number;')
lines.append('  max_grooving_depth_mm?: number;')
lines.append('  available_grades?: string[];')
lines.append('}')
lines.append('')

lines.append('export interface TungaloyTurningCondition {')
lines.append('  chipbreaker: string;')
lines.append('  grade: string;')
lines.append('  ap_min_mm: number;')
lines.append('  ap_max_mm: number;')
lines.append('  feed_min_mm_rev: number;')
lines.append('  feed_max_mm_rev: number;')
lines.append('  iso_groups: string[];')
lines.append('  vc_ranges: { vc_min: number; vc_max: number; material_subgroup?: string }[];')
lines.append('}')
lines.append('')

lines.append('export interface TungaloyGradeInfo {')
lines.append('  grade: string;')
lines.append('  description: string;')
lines.append('  iso_groups: string[];')
lines.append('}')
lines.append('')

# Grade info
grade_iso = {
    'T9205': ['P'], 'T9215': ['P', 'M', 'K'], 'T9225': ['P', 'M', 'K'],
    'T9235': ['P', 'M', 'K'],
    'T6215': ['M'], 'T5105': ['M', 'K'], 'T5115': ['M'], 'T5125': ['K'],
    'T505': ['K', 'N'], 'T515': ['K'],
    'GT9530': ['P'], 'AT9530': ['P'], 'NS9530': ['P', 'M'],
    'NS520': ['N'],
    'AH8015': ['S', 'H'], 'AH8005': ['S', 'H'],
    'AH6225': ['N'], 'AH6235': ['N'], 'AH120': ['N'],
    'AH725': ['P', 'M', 'K'], 'AH7025': ['P', 'M'],
    'GH130': ['H'], 'GH330': ['S', 'H'],
    'BX480': ['H'], 'BX815': ['H'], 'BX930': ['H'], 'BXC90': ['H'],
    'TH10': ['H'], 'KS05F': ['N'],
    'TS200': ['S'], 'TS300': ['S'],
}

lines.append('export const TUNGALOY_TURNING_GRADES: TungaloyGradeInfo[] = [')
for grade, desc in sorted(data['grade_descriptions'].items()):
    iso = grade_iso.get(grade, ['P'])
    iso_str = ', '.join(f'"{g}"' for g in iso)
    lines.append(f'  {{ grade: "{grade}", description: "{desc}", iso_groups: [{iso_str}] }},')
lines.append('];')
lines.append('')

# Turning inserts
lines.append('export const TUNGALOY_TURNING_INSERTS: TungaloyTurningInsert[] = [')
for t in data['turning_inserts']:
    parts = []
    parts.append(f'designation: "{t["designation"]}"')
    parts.append('type: "turning_insert"')
    parts.append(f'insert_shape: "{t["insert_shape"]}"')
    parts.append(f'shape_code: "{t["shape_code"]}"')
    parts.append(f'clearance_angle: "{t["clearance_angle"]}"')
    parts.append(f'tolerance_class: "{t["tolerance_class"]}"')
    parts.append(f'fixing_type: "{t["fixing_type"]}"')
    parts.append(f'nose_radius_mm: {t["nose_radius_mm"]}')
    parts.append(f'ic_mm: {t["ic_mm"]}')
    parts.append(f'thickness_mm: {t["thickness_mm"]}')
    parts.append(f'chipbreaker: "{t["chipbreaker"]}"')
    if 'edge_length_mm' in t:
        parts.append(f'edge_length_mm: {t["edge_length_mm"]}')
    if 'available_grades' in t:
        grades_str = ', '.join(f'"{g}"' for g in t['available_grades'])
        parts.append(f'available_grades: [{grades_str}]')
    lines.append('  { ' + ', '.join(parts) + ' },')
lines.append('];')
lines.append('')

# Threading inserts
lines.append('export const TUNGALOY_THREADING_INSERTS: TungaloyThreadingInsert[] = [')
for t in data['threading_inserts']:
    parts = []
    parts.append(f'designation: "{t["designation"]}"')
    parts.append('type: "threading_insert"')
    parts.append(f'ic_mm: {t["ic_mm"]}')
    parts.append(f'direction: "{t["direction"]}"')
    parts.append(f'thread_type: "{t["thread_type"]}"')
    parts.append(f'thread_angle_deg: {t["thread_angle_deg"]}')
    parts.append(f'profile: "{t["profile"]}"')
    parts.append(f'chipbreaker: "{t["chipbreaker"]}"')
    for opt in ['pdx_mm', 'pdy_mm', 're_mm', 'pitch_min_mm', 'pitch_max_mm', 'tpi_min', 'tpi_max']:
        if opt in t and t[opt] is not None:
            parts.append(f'{opt}: {t[opt]}')
    if 'available_grades' in t:
        grades_str = ', '.join(f'"{g}"' for g in t['available_grades'])
        parts.append(f'available_grades: [{grades_str}]')
    lines.append('  { ' + ', '.join(parts) + ' },')
lines.append('];')
lines.append('')

# Grooving inserts
lines.append('export const TUNGALOY_GROOVING_INSERTS: TungaloyGroovingInsert[] = [')
for t in data['grooving_inserts']:
    parts = []
    parts.append(f'designation: "{t["designation"]}"')
    parts.append('type: "grooving_insert"')
    parts.append(f'family: "{t["family"]}"')
    if t.get('width_mm') is not None:
        parts.append(f'width_mm: {t["width_mm"]}')
    else:
        parts.append('width_mm: null')
    for opt in ['hand']:
        if opt in t and t[opt] is not None:
            parts.append(f'{opt}: "{t[opt]}"')
    for opt in ['cutting_width_mm', 'corner_radius_mm', 'max_grooving_depth_mm']:
        if opt in t and t[opt] is not None:
            parts.append(f'{opt}: {t[opt]}')
    if 'available_grades' in t:
        grades_str = ', '.join(f'"{g}"' for g in t['available_grades'])
        parts.append(f'available_grades: [{grades_str}]')
    lines.append('  { ' + ', '.join(parts) + ' },')
lines.append('];')
lines.append('')

# Cutting conditions
lines.append('export const TUNGALOY_TURNING_CONDITIONS: TungaloyTurningCondition[] = [')
for cc in data['cutting_conditions']:
    iso_str = ', '.join(f'"{g}"' for g in cc['iso_groups'])
    vc_parts = []
    for vc in cc['vc_ranges']:
        inner = f'vc_min: {vc["vc_min"]}, vc_max: {vc["vc_max"]}'
        if 'material_subgroup' in vc:
            inner += f', material_subgroup: "{vc["material_subgroup"]}"'
        vc_parts.append('{ ' + inner + ' }')
    vc_str = ', '.join(vc_parts)
    line = f'  {{ chipbreaker: "{cc["chipbreaker"]}", grade: "{cc["grade"]}", '
    line += f'ap_min_mm: {cc["ap_min_mm"]}, ap_max_mm: {cc["ap_max_mm"]}, '
    line += f'feed_min_mm_rev: {cc["feed_min_mm_rev"]}, feed_max_mm_rev: {cc["feed_max_mm_rev"]}, '
    line += f'iso_groups: [{iso_str}], vc_ranges: [{vc_str}] }},'
    lines.append(line)
lines.append('];')
lines.append('')

# Grooving conditions
lines.append('export const TUNGALOY_GROOVING_CONDITIONS: { grade: string; feed_min_mm_rev: number; feed_max_mm_rev: number; vc_min?: number; vc_max?: number }[] = [')
for gc in data['grooving_conditions']:
    parts = [f'grade: "{gc["grade"]}"', f'feed_min_mm_rev: {gc["feed_min_mm_rev"]}', f'feed_max_mm_rev: {gc["feed_max_mm_rev"]}']
    if 'vc_min' in gc:
        parts.append(f'vc_min: {gc["vc_min"]}')
        parts.append(f'vc_max: {gc["vc_max"]}')
    lines.append('  { ' + ', '.join(parts) + ' },')
lines.append('];')
lines.append('')

content = '\n'.join(lines)

with open('C:/PRISM/mcp-server/src/data/tungaloy-turning-catalog.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Written {len(content)} bytes ({len(content)//1024} KB) to tungaloy-turning-catalog.ts')
print(f'Total lines: {len(lines)}')
