#!/usr/bin/env python3
"""Generate TypeScript catalog from extracted indexable/insert JSON files.
Combines: Kennametal (milling, holemaking, turning, threading),
          ISCAR, Korloy (rotating, turning), Allied Machine.
Output: src/data/indexable-tool-catalog.ts
"""

import json
import os

DATA_DIR = "C:/PRISM/mcp-server/src/data"

sources = [
    ("kennametal-milling-extracted.json", "Kennametal"),
    ("kennametal-holemaking-extracted.json", "Kennametal"),
    ("kennametal-turning-extracted.json", "Kennametal"),
    ("kennametal-threading-extracted.json", "Kennametal"),
    ("iscar-tools-extracted.json", "ISCAR"),
    ("iscar-turning-extracted.json", "ISCAR"),
    ("korloy-rotating-extracted.json", "Korloy"),
    ("korloy-turning-extracted.json", "Korloy"),
    ("ampc-tools-extracted.json", "Allied"),
    ("camfix-tools-extracted.json", "CAMFIX"),
]

all_tools = []
seen = set()

for filename, default_mfr in sources:
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        print(f"  SKIP: {filename} not found")
        continue
    with open(path) as f:
        tools = json.load(f)
    count = 0
    for t in tools:
        desig = t.get('designation', '')
        mfr = t.get('manufacturer', default_mfr)
        key = f"{mfr}-{desig}"
        if key in seen:
            continue
        seen.add(key)
        all_tools.append(t)
        count += 1
    print(f"  {filename}: {count} tools")

print(f"\nTotal unique tools: {len(all_tools)}")

# Generate TypeScript
lines = []
lines.append("// @ts-nocheck")
lines.append("// Indexable & Insert Tool Catalog — extracted from manufacturer PDFs")
lines.append(f"// {len(all_tools)} tools across Kennametal, ISCAR, Korloy, Allied Machine")
lines.append("// Generated by scripts/generate-indexable-catalog-ts.py")
lines.append("")
lines.append("export interface IndexableTool {")
lines.append("  designation: string;")
lines.append("  manufacturer: string;")
lines.append("  type: string;")
lines.append("  subtype?: string;")
lines.append("  cutting_diameter_mm?: number;")
lines.append("  shank_diameter_mm?: number;")
lines.append("  overall_length_mm?: number;")
lines.append("  max_depth_of_cut_mm?: number;")
lines.append("  flute_length_mm?: number;")
lines.append("  insert_count?: number;")
lines.append("  approach_angle_deg?: number;")
lines.append("  corner_radius_mm?: number;")
lines.append("  inscribed_circle_mm?: number;")
lines.append("  thickness_mm?: number;")
lines.append("  bore_diameter_mm?: number;")
lines.append("  insert_designation?: string;")
lines.append("  projection_length_mm?: number;")
lines.append("  height_mm?: number;")
lines.append("  width_mm?: number;")
lines.append("  wf_mm?: number;")
lines.append("  effective_cutting_depth_mm?: number;")
lines.append("  capto_size?: number;")
lines.append("}")
lines.append("")
lines.append("export const INDEXABLE_TOOLS: IndexableTool[] = [")

for t in all_tools:
    parts = []
    parts.append(f'designation:{json.dumps(t["designation"])}')
    parts.append(f'manufacturer:{json.dumps(t.get("manufacturer", "Unknown"))}')
    parts.append(f'type:{json.dumps(t.get("type", "unknown"))}')
    if t.get("subtype"):
        parts.append(f'subtype:{json.dumps(t["subtype"])}')
    for key in ["cutting_diameter_mm", "shank_diameter_mm", "overall_length_mm",
                 "max_depth_of_cut_mm", "flute_length_mm", "insert_count",
                 "approach_angle_deg", "corner_radius_mm", "inscribed_circle_mm",
                 "thickness_mm", "bore_diameter_mm", "projection_length_mm",
                 "height_mm", "width_mm", "wf_mm", "effective_cutting_depth_mm",
                 "capto_size"]:
        if t.get(key) is not None:
            parts.append(f'{key}:{t[key]}')
    if t.get("insert_designation"):
        parts.append(f'insert_designation:{json.dumps(t["insert_designation"])}')
    lines.append("{" + ",".join(parts) + "},")

lines.append("];")

output_path = os.path.join(DATA_DIR, "indexable-tool-catalog.ts")
with open(output_path, "w") as f:
    f.write("\n".join(lines))

print(f"\nGenerated {output_path} ({len(lines)} lines)")

# Stats
type_counts = {}
mfr_counts = {}
for t in all_tools:
    tt = t.get("type", "?")
    type_counts[tt] = type_counts.get(tt, 0) + 1
    mm = t.get("manufacturer", "?")
    mfr_counts[mm] = mfr_counts.get(mm, 0) + 1

print("\nBy type:")
for tt, c in sorted(type_counts.items(), key=lambda x: -x[1]):
    print(f"  {tt}: {c}")
print("\nBy manufacturer:")
for mm, c in sorted(mfr_counts.items(), key=lambda x: -x[1]):
    print(f"  {mm}: {c}")
