#!/usr/bin/env python3
"""Generate TypeScript catalog files from extracted JSON for new manufacturers."""

import json, os

data_path = "C:/PRISM/mcp-server/src/data/"

# Load all new extractions
sources = [
    ("flash-tools-extracted.json", "Flash"),
    ("ma-ford-tools-extracted.json", "MA Ford"),
    ("korloy-tools-extracted.json", "Korloy"),
    ("unknown_solid-tools-extracted.json", "Generic"),
    ("rapidkut-tools-extracted.json", "Rapidkut"),
]

all_tools = []
for fn, mfg in sources:
    fp = os.path.join(data_path, fn)
    if os.path.exists(fp):
        with open(fp) as f:
            tools = json.load(f)
        if tools:
            for t in tools:
                t["manufacturer"] = mfg
            all_tools.extend(tools)
            print(f"{mfg}: {len(tools)} tools")

# Check YG-1 if available
yg_path = os.path.join(data_path, "yg-1-tools-extracted.json")
if os.path.exists(yg_path):
    with open(yg_path) as f:
        yg_tools = json.load(f)
    if yg_tools:
        for t in yg_tools:
            t["manufacturer"] = "YG-1"
        all_tools.extend(yg_tools)
        print(f"YG-1: {len(yg_tools)} tools")

print(f"\nTotal: {len(all_tools)} tools")

# Generate TypeScript
lines = []
lines.append("// @ts-nocheck")
lines.append("// Additional manufacturer tools - extracted from PDF catalogs")
lines.append(f"// {len(all_tools)} tools from Flash, MA Ford, Korloy, Rapidkut, Generic + YG-1")
lines.append("// Generated by scripts/generate-additional-catalog-ts.py")
lines.append("")
lines.append("export interface AdditionalTool {")
lines.append("  designation: string;")
lines.append("  manufacturer: string;")
lines.append("  type: string;")
lines.append("  cutting_diameter_mm: number;")
lines.append("  shank_diameter_mm: number;")
lines.append("  overall_length_mm?: number;")
lines.append("  flute_length_mm?: number;")
lines.append("  corner_radius_mm?: number;")
lines.append("  flute_count?: number;")
lines.append("}")
lines.append("")
lines.append("export const ADDITIONAL_TOOLS: AdditionalTool[] = [")

for t in all_tools:
    parts = []
    d = t["designation"].replace('"', "'").replace("\n", "")
    parts.append(f'designation:"{d}"')
    parts.append(f'manufacturer:"{t["manufacturer"]}"')
    parts.append(f'type:"{t["type"]}"')
    parts.append(f'cutting_diameter_mm:{t["cutting_diameter_mm"]}')
    parts.append(f'shank_diameter_mm:{t["shank_diameter_mm"]}')
    if t.get("overall_length_mm") is not None:
        parts.append(f'overall_length_mm:{t["overall_length_mm"]}')
    if t.get("flute_length_mm") is not None:
        parts.append(f'flute_length_mm:{t["flute_length_mm"]}')
    if t.get("corner_radius_mm") is not None:
        parts.append(f'corner_radius_mm:{t["corner_radius_mm"]}')
    if t.get("flute_count") is not None:
        parts.append(f'flute_count:{t["flute_count"]}')
    lines.append("  {" + ",".join(parts) + "},")

lines.append("];")
lines.append("")

out_path = os.path.join(data_path, "additional-tool-catalog.ts")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Generated {out_path}: {len(lines)} lines")
