/**
 * generate-corpus-cutting-corpus.test.ts
 * [JM-FUSION-TOOLS] corpus-cutting-data freshness + safety-invariant guard (slot:romeo).
 *
 * WHY THIS EXISTS
 *   `generate-corpus-cutting-corpus.ts` derives every preset's axial depth (`ap_in`) from the
 *   shared matrix lib (`conditionMatrix` -> `computeCondition`). When the matrix's milling ap
 *   rule changed to the diameter-relative 1xD-LOC baseline (operator 2026-06-17), the committed,
 *   git-TRACKED corpus SAMPLE (`state/shared/corpus-cutting-data/by-group-sample/CORPUS-<G>.sample.csv`)
 *   went STALE -- it still carried the pre-fix fixed-mm axial (a 0.007" endmill HEM row showed
 *   ap_in=0.6299" = 16 mm = ~90x diameter, a snap hazard) while the regenerated by-machine /
 *   Fusion / Mastercam libraries carried the new safe value. Nothing failed loudly; a scrutiny
 *   reviewer caught it. This test is that missing backstop.
 *
 * WHAT IT ASSERTS (CSV-self-contained -- reads ONLY the small tracked sample, no full-corpus load)
 *   For every MILLING row in each tracked sample CSV:
 *     ap_in <= STRATEGY_FACTORS[strategy].axialDx * dia_in   (the 1xD-LOC safety invariant)
 *   A stale fixed-mm sample violates this grossly (0.6299 > 2.0*0.007 = 0.014) and FAILS, so a
 *   future matrix change that is not propagated into the committed corpus sample is caught in CI.
 *   This is the corpus-side mirror of the matrix lib's own safety-invariant test.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { STRATEGY_FACTORS } from "./lib/jm-tool-condition-matrix.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
// test at mcp-server/scripts/ -> repo root is ../../
const SAMPLE_DIR = resolve(__dirname, "../../state/shared/corpus-cutting-data/by-group-sample");
const GROUPS = ["P", "M", "K", "N", "S", "H"] as const;
const STRATEGY_KEYS = Object.keys(STRATEGY_FACTORS);
// The corpus rounds ap_in to 4 decimals (round4(ap_mm * IN_PER_MM)), so a value at the exact
// diameter baseline can print up to half a 4-dp ULP (5e-5") ABOVE the unrounded baseline (e.g.
// 0.0010501" -> "0.0011"). Allow one full 4-dp ULP. This is NOT a weakened assertion: the
// stale-corpus violation this guards (e.g. ap_in 0.6299" vs baseline 0.014") is ~6000x larger.
const ROUND_TOL = 1e-4;

/** Parse a header line -> { columnName: index }. */
function headerIndex(headerLine: string): Record<string, number> {
  const cols = headerLine.split(",");
  const idx: Record<string, number> = {};
  cols.forEach((c, i) => (idx[c.trim()] = i));
  return idx;
}

describe("corpus-cutting-data sample: 1xD-LOC axial safety invariant (freshness guard)", () => {
  it("every tracked CORPUS-<G>.sample.csv exists", () => {
    for (const g of GROUPS) {
      const p = resolve(SAMPLE_DIR, `CORPUS-${g}.sample.csv`);
      expect(existsSync(p), `${p} must exist (regenerate via head -201 by-group/CORPUS-${g}.csv)`).toBe(true);
    }
  });

  for (const g of GROUPS) {
    it(`CORPUS-${g}: no milling row exceeds its diameter-relative axial baseline (ap_in <= axialDx*dia_in)`, () => {
      const path = resolve(SAMPLE_DIR, `CORPUS-${g}.sample.csv`);
      const lines = readFileSync(path, "utf8").split(/\r?\n/).filter((l) => l.length > 0);
      expect(lines.length, `${g} sample must have a header + rows`).toBeGreaterThan(1);

      const col = headerIndex(lines[0]);
      for (const k of ["op", "strategy", "dia_in", "ap_in"]) {
        expect(col[k], `${g} sample header must carry column '${k}'`).toBeGreaterThanOrEqual(0);
      }
      const nCols = lines[0].split(",").length;

      let milling = 0;
      for (let i = 1; i < lines.length; i++) {
        const cells = lines[i].split(",");
        // skip any row whose field count differs from the header (a comma inside a field would
        // shift columns -- never silently mis-assert; the well-formed rows are the guard).
        if (cells.length !== nCols) continue;
        if (cells[col.op] !== "milling") continue;

        const strategy = cells[col.strategy];
        // every milling strategy in the corpus must be one of the known STRATEGY_FACTORS keys
        expect(STRATEGY_KEYS, `${g} row ${i}: unknown milling strategy '${strategy}'`).toContain(strategy);
        const sm = STRATEGY_FACTORS[strategy];

        const dia = parseFloat(cells[col.dia_in]);
        const ap = parseFloat(cells[col.ap_in]);
        if (!(dia > 0) || !Number.isFinite(ap)) continue; // non-numeric guard
        milling++;

        const baseline = sm.axialDx * dia;
        expect(
          ap,
          `${g} row ${i} (${strategy} dia=${dia}"): ap_in ${ap} exceeds 1xD-LOC baseline ` +
            `axialDx(${sm.axialDx})*dia=${baseline.toFixed(4)} -- STALE corpus? re-run generate-corpus-cutting-corpus.ts ` +
            `then head -201 by-group/CORPUS-${g}.csv > by-group-sample/CORPUS-${g}.sample.csv`,
        ).toBeLessThanOrEqual(baseline + ROUND_TOL);
      }
      // sanity: the sample must actually contain milling rows (else the guard is vacuous)
      expect(milling, `${g} sample must contain milling rows to guard`).toBeGreaterThan(0);
    });
  }
});
