#!/usr/bin/env npx ts-node
/**
 * WEDM Documentation Cascade
 * Phase 0.11 U-WEDM-DOC3 - WEDM AGI Roadmap
 *
 * Cascade-updates documentation when WEDM engines change:
 * 1. Regenerate WEDM_DIGEST.md
 * 2. Update AUTO-WEDM-START/END block in CLAUDE.md
 * 3. Update SVI surface counts
 *
 * Usage: npx ts-node scripts/wedm_doc_cascade.ts
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, "../..");

function updateManagedBlock(
  filePath: string,
  startTag: string,
  endTag: string,
  newContent: string
): boolean {
  if (!fs.existsSync(filePath)) {
    console.warn(`File not found: ${filePath}`);
    return false;
  }

  const content = fs.readFileSync(filePath, "utf-8");
  const startRegex = new RegExp(`${startTag}[\\s\\S]*?${endTag}`, "g");

  if (!startRegex.test(content)) {
    console.warn(`Managed block not found in ${filePath}`);
    return false;
  }

  const replacement = `${startTag}\n${newContent}\n${endTag}`;
  const updated = content.replace(startRegex, replacement);

  if (updated !== content) {
    fs.writeFileSync(filePath, updated);
    return true;
  }
  return false;
}

async function main(): Promise<void> {
  console.log("\n=== WEDM Documentation Cascade ===\n");

  // 1. Regenerate WEDM_DIGEST.md
  console.log("[1/3] Regenerating WEDM_DIGEST.md...");
  try {
    execSync("npx ts-node scripts/wedm_generate_digest.ts", {
      cwd: path.resolve(__dirname, ".."),
      stdio: "inherit",
    });
  } catch (err) {
    console.error("  FAILED:", err);
  }

  // 2. Update CLAUDE.md managed block
  console.log("\n[2/3] Updating CLAUDE.md AUTO-WEDM-START/END block...");

  // Count live engines
  const enginesDir = path.resolve(__dirname, "../src/engines");
  const enginePattern = /^(WEDM|Wedm|EDM|WireEDM|MicroEDM|SinkerEDM|Stochastic|RecastLayer)/;
  const engines = fs.existsSync(enginesDir)
    ? fs.readdirSync(enginesDir).filter(
        (f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && enginePattern.test(f)
      ).length
    : 0;

  // Count playbooks
  const playbooksDir = path.resolve(__dirname, "../data/playbooks");
  const playbooks = fs.existsSync(playbooksDir)
    ? fs.readdirSync(playbooksDir).filter((f) => f.startsWith("wedm_") && f.endsWith(".json")).length
    : 0;

  // Count state files
  const stateDir = path.resolve(__dirname, "../data/state");
  const stateFiles = fs.existsSync(stateDir)
    ? fs.readdirSync(stateDir).filter((f) => f.startsWith("WEDM_") && f.endsWith(".json")).length
    : 0;

  // Load SVI
  const sviPath = path.resolve(stateDir, "WEDM_SVI_SURFACES.json");
  let psi = 0;
  if (fs.existsSync(sviPath)) {
    const svi = JSON.parse(fs.readFileSync(sviPath, "utf-8"));
    psi = svi.psi?.current ?? 0;
  }

  const managedContent = `## WEDM AGI Status (auto-generated by \`wedm_generate_digest.ts\`)

- **Engines**: ${engines} WEDM/EDM engines (\`src/engines/WEDM*.ts\`, \`EDM*.ts\`, \`WireEDM*.ts\`)
- **Skills**: 12 WEDM skills (\`~/.claude/commands/wedm-*.md\`)
- **Hooks**: 18 WEDM hooks (16 safety + 2 SVI coupling)
- **Playbooks**: ${playbooks} workflow playbooks (\`data/playbooks/wedm_*.json\`)
- **State Files**: ${stateFiles} WEDM state/index files (\`data/state/WEDM_*.json\`)
- **MIT Courses**: 5 courses integrated (2.008, 2.830, 2.813, 18.06, 6.S191)
- **Tribal Tips**: 46 WEDM tips (20 field + 26 MIT-derived)
- **Formulas**: 14 WEDM formulas with MIT citations
- **JM Die Programs**: 26 indexed (full harvest pending zip extraction)
- **SVI Psi**: ${psi.toFixed(3)} / 1.0 target
- **Last cascade**: ${new Date().toISOString()}`;

  const claudeMdPath = path.join(ROOT, "CLAUDE.md");
  const updated = updateManagedBlock(
    claudeMdPath,
    "<!-- AUTO-WEDM-START -->",
    "<!-- AUTO-WEDM-END -->",
    managedContent
  );
  console.log(`  ${updated ? "✓ Updated" : "✗ No change"}`);

  // 3. Update SVI surfaces
  console.log("\n[3/3] Updating SVI surface counts...");
  if (fs.existsSync(sviPath)) {
    const svi = JSON.parse(fs.readFileSync(sviPath, "utf-8"));
    if (svi.surfaces?.["wedm-engines"]) svi.surfaces["wedm-engines"].current = engines;
    if (svi.surfaces?.["wedm-playbooks"]) svi.surfaces["wedm-playbooks"].current = playbooks;
    if (svi.surfaces?.["wedm-state-files"]) svi.surfaces["wedm-state-files"].current = stateFiles;
    svi.psi.lastCalculated = new Date().toISOString();
    fs.writeFileSync(sviPath, JSON.stringify(svi, null, 2));
    console.log("  ✓ SVI surfaces updated");
  } else {
    console.log("  ✗ SVI surfaces file not found");
  }

  console.log("\n=== Cascade Complete ===");
}

main().catch(console.error);
