# FANUC ALARMS - VERIFIED FROM CNCCookbook.com
# Source: https://www.cnccookbook.com/fanuc-alarm-code-list/
# Valid for: 0i, 0i/0iMate Model B, 16/18/21 series
# Extracted: 2026-01-28

import json
from datetime import datetime

FANUC_ALARMS = [
    # P/S (Program/System) Alarms 0-100
    {"code": "000", "name": "PLEASE TURN OFF POWER", "category": "SYSTEM", "severity": "CRITICAL", "description": "Parameter or program was changed. Turn power off and back on to apply changes.", "causes": ["Parameter change", "System update"], "quick_fix": "Power cycle the control", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "001", "name": "TH PARITY ALARM", "category": "PROGRAM", "severity": "HIGH", "description": "Parity error detected in tape/program data during read. Data corruption in program.", "causes": ["Corrupted program data", "Communication error"], "quick_fix": "Re-transfer program, check communication cable", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "002", "name": "TV PARITY ALARM", "category": "PROGRAM", "severity": "HIGH", "description": "TV check alarm - character count in block is odd when should be even.", "causes": ["Program format error", "Missing character"], "quick_fix": "Edit program to correct block format", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "003", "name": "TOO MANY DIGITS", "category": "PROGRAM", "severity": "MEDIUM", "description": "Numeric value in program exceeds maximum allowed digits.", "causes": ["Value too large", "Decimal point error"], "quick_fix": "Check and correct numeric values in program", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "004", "name": "ADDRESS NOT FOUND", "category": "PROGRAM", "severity": "MEDIUM", "description": "First character of block is not an address letter (A-Z).", "causes": ["Program syntax error", "Missing address"], "quick_fix": "Add proper address letter to block start", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "005", "name": "NO DATA AFTER ADDRESS", "category": "PROGRAM", "severity": "MEDIUM", "description": "Address letter found but no numeric data follows it.", "causes": ["Incomplete command", "Missing value"], "quick_fix": "Add numeric value after address letter", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "006", "name": "ILLEGAL USE OF NEGATIVE SIGN", "category": "PROGRAM", "severity": "MEDIUM", "description": "Negative sign used where not allowed or incorrect position.", "causes": ["Syntax error", "Invalid negative value"], "quick_fix": "Check negative sign usage in program", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "007", "name": "ILLEGAL USE OF DECIMAL POINT", "category": "PROGRAM", "severity": "MEDIUM", "description": "Decimal point used incorrectly or where not allowed.", "causes": ["Syntax error", "Invalid decimal format"], "quick_fix": "Correct decimal point usage", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "010", "name": "IMPROPER G-CODE", "category": "PROGRAM", "severity": "MEDIUM", "description": "G-code used is not valid or not available on this control.", "causes": ["Invalid G-code", "Unsupported function"], "quick_fix": "Check G-code list for valid codes", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "011", "name": "NO FEEDRATE COMMANDED", "category": "PROGRAM", "severity": "MEDIUM", "description": "Cutting move commanded without feedrate specified.", "causes": ["Missing F command", "F=0"], "quick_fix": "Add F (feedrate) command before cutting move", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "020", "name": "OVER TOLERANCE OF RADIUS", "category": "PROGRAM", "severity": "MEDIUM", "description": "Arc start/end points don't match radius within tolerance.", "causes": ["Arc calculation error", "Endpoint mismatch"], "quick_fix": "Verify arc I, J, K values and endpoints", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "021", "name": "ILLEGAL PLANE AXIS COMMANDED", "category": "PROGRAM", "severity": "MEDIUM", "description": "Invalid axis specified for the selected plane (G17/G18/G19).", "causes": ["Wrong plane selected", "Invalid axis combination"], "quick_fix": "Match plane selection to axis commands", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "022", "name": "NO CIRCLE RADIUS", "category": "PROGRAM", "severity": "MEDIUM", "description": "Circular interpolation commanded without radius (R) or I,J,K.", "causes": ["Missing radius data", "Incomplete arc command"], "quick_fix": "Add R value or I,J,K to arc command", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "029", "name": "ILLEGAL OFFSET VALUE", "category": "PROGRAM", "severity": "MEDIUM", "description": "Tool offset value outside allowable range.", "causes": ["Offset too large", "Invalid offset number"], "quick_fix": "Check offset values in offset table", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "030", "name": "ILLEGAL OFFSET NUMBER", "category": "PROGRAM", "severity": "MEDIUM", "description": "Tool offset number specified doesn't exist or is invalid.", "causes": ["Invalid H or D number", "Offset not registered"], "quick_fix": "Verify offset number exists in table", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "033", "name": "NO SOLUTION AT CRC", "category": "PROGRAM", "severity": "HIGH", "description": "Cutter radius compensation cannot calculate valid path.", "causes": ["Tool radius too large", "Path geometry issue"], "quick_fix": "Reduce tool radius or modify path geometry", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "041", "name": "INTERFERENCE IN CRC", "category": "PROGRAM", "severity": "HIGH", "description": "Cutter compensation detects tool will gouge workpiece.", "causes": ["Tool too large for feature", "Path geometry problem"], "quick_fix": "Use smaller tool or modify programmed path", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "059", "name": "PROGRAM NUMBER NOT FOUND", "category": "PROGRAM", "severity": "MEDIUM", "description": "Called program number (O number) not found in memory.", "causes": ["Program not loaded", "Wrong program number"], "quick_fix": "Load program or correct program number", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "060", "name": "SEQUENCE NUMBER NOT FOUND", "category": "PROGRAM", "severity": "MEDIUM", "description": "Sequence number (N number) specified in search not found.", "causes": ["N number doesn't exist", "Search error"], "quick_fix": "Verify sequence number exists in program", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "070", "name": "NO PROGRAM SPACE IN MEMORY", "category": "MEMORY", "severity": "HIGH", "description": "Not enough memory to store program. Memory full.", "causes": ["Memory full", "Program too large"], "quick_fix": "Delete unused programs to free memory", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "071", "name": "DATA NOT FOUND", "category": "PROGRAM", "severity": "MEDIUM", "description": "Specified data or address not found during search.", "causes": ["Search target missing", "Data error"], "quick_fix": "Verify search target exists", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "072", "name": "TOO MANY PROGRAMS", "category": "MEMORY", "severity": "HIGH", "description": "Maximum number of programs in memory exceeded.", "causes": ["Too many O numbers registered"], "quick_fix": "Delete unused programs", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "073", "name": "PROGRAM NUMBER ALREADY IN", "category": "PROGRAM", "severity": "MEDIUM", "description": "Attempting to register program number that already exists.", "causes": ["Duplicate O number"], "quick_fix": "Use different program number or delete existing", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "074", "name": "ILLEGAL PROGRAM NUMBER", "category": "PROGRAM", "severity": "MEDIUM", "description": "Program number format invalid or out of range.", "causes": ["Invalid O number format"], "quick_fix": "Use valid program number format", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "085", "name": "COMMUNICATION ERROR", "category": "COMMUNICATION", "severity": "HIGH", "description": "Error during RS-232 or network communication.", "causes": ["Cable fault", "Baud rate mismatch", "Protocol error"], "quick_fix": "Check cables and communication settings", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "086", "name": "DR SIGNAL OFF", "category": "COMMUNICATION", "severity": "HIGH", "description": "Data Ready signal not received during communication.", "causes": ["Cable disconnected", "Device not ready"], "quick_fix": "Check RS-232 cable and device power", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "090", "name": "REFERENCE RETURN INCOMPLETE", "category": "AXIS", "severity": "HIGH", "description": "Reference point return (home) not completed on all axes.", "causes": ["Home position not established", "Dog/switch issue"], "quick_fix": "Execute reference return on all axes", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "100", "name": "PARAMETER WRITE ENABLE", "category": "SYSTEM", "severity": "LOW", "description": "Parameter write protection is disabled. Parameters can be changed.", "causes": ["PWE switch ON", "Intentional setting"], "quick_fix": "Turn off PWE after parameter changes", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # APC (Absolute Position Coder) Alarms 300-309
    {"code": "300", "name": "APC ALARM: n AXIS NEED ZRN", "category": "ENCODER", "severity": "HIGH", "description": "Absolute position data lost. Reference return required on axis n.", "causes": ["Battery died", "Encoder replaced", "First power on"], "quick_fix": "Perform reference point return on indicated axis", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "301", "name": "APC ALARM: n AXIS COMMUNICATION", "category": "ENCODER", "severity": "CRITICAL", "description": "Communication error with absolute encoder on axis n.", "causes": ["Encoder cable fault", "Encoder failure"], "quick_fix": "Check encoder cable connections and encoder", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "302", "name": "APC ALARM: n AXIS OVER TIME", "category": "ENCODER", "severity": "HIGH", "description": "Absolute position detector response timeout on axis n.", "causes": ["Encoder fault", "Communication problem"], "quick_fix": "Check encoder and communication lines", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "303", "name": "APC ALARM: n AXIS FRAMING", "category": "ENCODER", "severity": "HIGH", "description": "Framing error in absolute encoder data on axis n.", "causes": ["Cable noise", "Encoder fault"], "quick_fix": "Check encoder cable shielding and routing", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "304", "name": "APC ALARM: n AXIS PARITY", "category": "ENCODER", "severity": "HIGH", "description": "Parity error in absolute encoder data on axis n.", "causes": ["Data corruption", "Encoder fault"], "quick_fix": "Check encoder and replace if necessary", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "305", "name": "APC ALARM: n AXIS PULSE MISS", "category": "ENCODER", "severity": "HIGH", "description": "Pulse count error detected in absolute encoder on axis n.", "causes": ["Encoder contamination", "Encoder fault"], "quick_fix": "Clean or replace encoder", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "306", "name": "APC ALARM: n AXIS BATTERY ZERO", "category": "ENCODER", "severity": "CRITICAL", "description": "Absolute encoder battery completely discharged on axis n.", "causes": ["Battery dead", "Battery not installed"], "quick_fix": "Replace battery immediately and re-reference", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "307", "name": "APC ALARM: n AXIS BATTERY DOWN 1", "category": "ENCODER", "severity": "HIGH", "description": "Absolute encoder battery voltage low (warning level 1).", "causes": ["Battery aging", "Low voltage"], "quick_fix": "Replace battery soon - schedule replacement", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "308", "name": "APC ALARM: n AXIS BATTERY DOWN 2", "category": "ENCODER", "severity": "CRITICAL", "description": "Absolute encoder battery voltage critically low (warning level 2).", "causes": ["Battery nearly dead"], "quick_fix": "Replace battery immediately before position loss", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "309", "name": "APC ALARM: n AXIS ZRN IMPOSSIBLE", "category": "ENCODER", "severity": "CRITICAL", "description": "Reference return cannot be completed on axis n.", "causes": ["Mechanical obstruction", "Encoder fault", "Dog/switch fault"], "quick_fix": "Check mechanical system, dogs, and switches", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # Servo Alarms 400-468
    {"code": "400", "name": "SERVO ALARM: n-TH AXIS OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "Servo motor overload on axis n. Motor exceeded torque/current limit.", "causes": ["Mechanical binding", "Motor overworked", "Collision"], "quick_fix": "Check for mechanical binding, reduce load, check diagnosis 201", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "401", "name": "SERVO ALARM: n-TH AXIS VRDY OFF", "category": "SERVO", "severity": "CRITICAL", "description": "Servo amplifier ready signal (VRDY) turned off on axis n without CNC command.", "causes": ["Amplifier fault", "Power supply issue", "Emergency stop"], "quick_fix": "Check servo amplifier status, power supply, E-stop circuit", "data_source": "CNCCookbook_Fanuc_Alarm_List_MROElectric"},
    {"code": "402", "name": "SERVO ALARM: SV CARD NOT EXIST", "category": "SERVO", "severity": "CRITICAL", "description": "Servo control card/board not detected by CNC.", "causes": ["Card not installed", "Card fault", "Connection issue"], "quick_fix": "Check servo card installation and connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "403", "name": "SERVO ALARM: CARD/SOFT MISMATCH", "category": "SERVO", "severity": "HIGH", "description": "Servo card hardware and software versions incompatible.", "causes": ["Wrong card version", "Software update needed"], "quick_fix": "Match servo card and software versions", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "404", "name": "SERVO ALARM: n-TH AXIS VRDY ON", "category": "SERVO", "severity": "HIGH", "description": "Servo ready signal ON when it should be OFF on axis n.", "causes": ["Amplifier fault", "Control circuit issue"], "quick_fix": "Check servo amplifier and control signals", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "405", "name": "SERVO ALARM: ZERO POINT RETURN FAULT", "category": "SERVO", "severity": "HIGH", "description": "Reference point return operation failed.", "causes": ["Dog position wrong", "Deceleration signal fault", "Parameter error"], "quick_fix": "Check reference return dogs, switches, and parameters", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "407", "name": "SERVO ALARM: EXCESS ERROR", "category": "SERVO", "severity": "CRITICAL", "description": "Position error between command and feedback exceeds allowable tolerance.", "causes": ["Mechanical binding", "Servo gain issue", "Motor/encoder fault"], "quick_fix": "Check mechanical system, servo parameters, motor and encoder", "data_source": "CNCCookbook_Fanuc_Alarm_List_MROElectric"},
    {"code": "409", "name": "SERVO ALARM: n AXIS TORQUE ALM", "category": "SERVO", "severity": "HIGH", "description": "Torque limit alarm triggered on axis n.", "causes": ["Excessive load", "Mechanical interference", "Motor fault"], "quick_fix": "Check for mechanical interference, reduce load", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "410", "name": "SERVO ALARM: n-TH AXIS EXCESS ERROR", "category": "SERVO", "severity": "CRITICAL", "description": "Excessive position error at stop position on axis n.", "causes": ["Mechanical binding", "Servo instability"], "quick_fix": "Check mechanical system and servo tuning", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "411", "name": "SERVO ALARM: n-TH AXIS EXCESS ERROR", "category": "SERVO", "severity": "CRITICAL", "description": "Excessive position error during motion on axis n.", "causes": ["Mechanical resistance", "Servo gain too low"], "quick_fix": "Check mechanical system, adjust servo gains", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "413", "name": "SERVO ALARM: n-th AXIS LSI OVERFLOW", "category": "SERVO", "severity": "CRITICAL", "description": "Position data overflow in servo control LSI on axis n.", "causes": ["Parameter error", "Data corruption"], "quick_fix": "Check and reset servo parameters", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "414", "name": "SERVO ALARM: n-TH AXIS DETECTION RELATED ERROR", "category": "SERVO", "severity": "CRITICAL", "description": "Feedback or detection system error on axis n. Check diagnosis 200.", "causes": ["Encoder fault", "Feedback cable issue", "Amplifier fault"], "quick_fix": "Check diagnosis 200, inspect encoder and cables", "data_source": "CNCCookbook_Fanuc_Alarm_List_FanucWorld"},
    {"code": "415", "name": "SERVO ALARM: n-TH AXIS EXCESS SHIFT", "category": "SERVO", "severity": "HIGH", "description": "Excessive position shift detected on axis n.", "causes": ["Encoder fault", "Feedback cable noise"], "quick_fix": "Check encoder connections and cable shielding", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "416", "name": "SERVO ALARM: n-TH AXIS DISCONNECTION", "category": "SERVO", "severity": "CRITICAL", "description": "Servo motor or encoder disconnected on axis n.", "causes": ["Cable disconnected", "Connector fault", "Motor fault"], "quick_fix": "Check all motor and encoder cables and connectors", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "417", "name": "SERVO ALARM: n-TH AXIS PARAMETER INCORRECT", "category": "SERVO", "severity": "HIGH", "description": "Servo parameter setting incorrect for axis n.", "causes": ["Wrong motor type set", "Parameter corruption"], "quick_fix": "Verify and correct servo parameters for motor type", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "420", "name": "SERVO ALARM: n AXIS SYNC TORQUE", "category": "SERVO", "severity": "HIGH", "description": "Synchronous axis torque deviation exceeded on axis n.", "causes": ["Mechanical mismatch", "Tandem axis issue"], "quick_fix": "Check tandem/synchronous axis setup and mechanics", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "421", "name": "SERVO ALARM: n AXIS EXCESS ER (D)", "category": "SERVO", "severity": "HIGH", "description": "Excessive error during deceleration on axis n.", "causes": ["Deceleration too fast", "Mechanical resistance"], "quick_fix": "Adjust deceleration parameters, check mechanical system", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "430", "name": "n AXIS: SV MOTOR OVERHEAT", "category": "SERVO", "severity": "CRITICAL", "description": "Servo motor overtemperature on axis n. Motor thermal protection triggered.", "causes": ["Motor overworked", "Cooling failure", "Ambient temp high"], "quick_fix": "Allow motor to cool, check ventilation, reduce duty cycle", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "431", "name": "n AXIS: CNV. OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "Converter unit overloaded on axis n.", "causes": ["Excessive regenerative energy", "Power supply undersized"], "quick_fix": "Check power supply capacity and regenerative load", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "432", "name": "n AXIS: CNV. LOW VOLT CONTROL", "category": "SERVO", "severity": "HIGH", "description": "Converter control power voltage low on axis n.", "causes": ["Power supply issue", "Connection problem"], "quick_fix": "Check control power supply connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "433", "name": "n AXIS: CNV. LOW VOLT DC LINK", "category": "SERVO", "severity": "CRITICAL", "description": "DC link voltage too low in converter on axis n.", "causes": ["Main power issue", "Converter fault"], "quick_fix": "Check main power supply and converter", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "434", "name": "n AXIS: INV. LOW VOLT CONTROL", "category": "SERVO", "severity": "HIGH", "description": "Inverter control voltage low on axis n.", "causes": ["Power supply fault"], "quick_fix": "Check inverter power connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "435", "name": "n AXIS: INV. LOW VOLT DC LINK", "category": "SERVO", "severity": "CRITICAL", "description": "Inverter DC link voltage low on axis n.", "causes": ["Power supply issue", "Regeneration problem"], "quick_fix": "Check power supply and regenerative resistor", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "436", "name": "n AXIS: SOFTTHERMAL (OVC)", "category": "SERVO", "severity": "HIGH", "description": "Software thermal protection triggered (overcurrent) on axis n.", "causes": ["Motor overloaded", "Drive overloaded"], "quick_fix": "Reduce load, allow cooling, check for mechanical issues", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "437", "name": "n AXIS: CNV. OVERCURRENT POWER", "category": "SERVO", "severity": "CRITICAL", "description": "Overcurrent in converter power circuit on axis n.", "causes": ["Short circuit", "Motor fault", "Amplifier fault"], "quick_fix": "Check for short circuits in motor cables", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "438", "name": "n AXIS: INV. ABNORMAL CURRENT", "category": "SERVO", "severity": "CRITICAL", "description": "Abnormal current detected in inverter on axis n.", "causes": ["Motor fault", "Amplifier fault"], "quick_fix": "Check motor insulation and amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "439", "name": "n AXIS: CNV. OVER VOLT DC LINK", "category": "SERVO", "severity": "HIGH", "description": "DC link overvoltage in converter on axis n.", "causes": ["Regeneration overload", "Power surge"], "quick_fix": "Check regenerative resistor and power supply", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "440", "name": "n AXIS: CNV. EX DECELERATION POW", "category": "SERVO", "severity": "HIGH", "description": "Excessive deceleration power (regeneration) on axis n.", "causes": ["Deceleration too fast", "Regen resistor fault"], "quick_fix": "Adjust deceleration rate, check regen circuit", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "441", "name": "n AXIS: ABNORMAL CURRENT OFFSET", "category": "SERVO", "severity": "HIGH", "description": "Current sensor offset error on axis n.", "causes": ["Sensor drift", "Amplifier fault"], "quick_fix": "Recalibrate or replace amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "442", "name": "n AXIS: CNV. CHARGE FAILURE", "category": "SERVO", "severity": "CRITICAL", "description": "DC link capacitor charge failure on axis n.", "causes": ["Charge circuit fault", "Capacitor fault"], "quick_fix": "Check charge circuit and DC link capacitors", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "443", "name": "n AXIS: CNV. COOLING FAN FAILURE", "category": "SERVO", "severity": "HIGH", "description": "Converter cooling fan fault on axis n.", "causes": ["Fan stopped", "Fan sensor fault"], "quick_fix": "Check and replace cooling fan", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "444", "name": "n AXIS: INV. COOLING FAN FAILURE", "category": "SERVO", "severity": "HIGH", "description": "Inverter cooling fan fault on axis n.", "causes": ["Fan stopped", "Fan sensor fault"], "quick_fix": "Check and replace cooling fan", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "445", "name": "n AXIS: SOFT DISCONNECT ALARM", "category": "SERVO", "severity": "HIGH", "description": "Software detected motor disconnect on axis n.", "causes": ["Cable fault", "Connector loose"], "quick_fix": "Check motor power cables and connectors", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "446", "name": "n AXIS: HARD DISCONNECT ALARM", "category": "SERVO", "severity": "CRITICAL", "description": "Hardware detected motor disconnect on axis n.", "causes": ["Cable broken", "Connector disconnected"], "quick_fix": "Inspect and repair motor cable connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "447", "name": "n AXIS: HARD DISCONNECT (EXT)", "category": "SERVO", "severity": "CRITICAL", "description": "External hardware disconnect detected on axis n.", "causes": ["External cable fault"], "quick_fix": "Check external motor connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "448", "name": "n AXIS: UNMATCHED FEEDBACK ALARM", "category": "SERVO", "severity": "HIGH", "description": "Feedback signal mismatch on axis n (dual feedback).", "causes": ["Encoder mismatch", "Scale mismatch"], "quick_fix": "Check both feedback devices for matching signals", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "449", "name": "n AXIS: INV. IPM ALARM", "category": "SERVO", "severity": "CRITICAL", "description": "Intelligent Power Module alarm in inverter on axis n.", "causes": ["IPM fault", "Overcurrent protection"], "quick_fix": "Check IPM module and motor connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "460", "name": "n AXIS: FSSB DISCONNECT", "category": "SERVO", "severity": "CRITICAL", "description": "FSSB (high-speed serial bus) communication lost on axis n.", "causes": ["Fiber optic cable fault", "Amplifier fault"], "quick_fix": "Check FSSB fiber cables and amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "461", "name": "n AXIS: ILLEGAL AMP INTERFACE", "category": "SERVO", "severity": "HIGH", "description": "Invalid amplifier interface detected on axis n.", "causes": ["Wrong amplifier type", "Configuration error"], "quick_fix": "Verify amplifier type matches configuration", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "462", "name": "n AXIS: SEND CNC DATA FAILED", "category": "SERVO", "severity": "HIGH", "description": "Failed to send data from CNC to servo on axis n.", "causes": ["Communication fault", "Cable issue"], "quick_fix": "Check servo communication cables", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "466", "name": "n AXIS: MOTOR/AMP COMBINATION", "category": "SERVO", "severity": "HIGH", "description": "Motor and amplifier combination invalid on axis n.", "causes": ["Wrong motor for amplifier", "Parameter error"], "quick_fix": "Verify motor and amplifier compatibility", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # Overtravel Alarms 500-507
    {"code": "500", "name": "OVER TRAVEL: +n", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Positive direction software overtravel on axis n.", "causes": ["Axis exceeded positive limit", "Work offset error"], "quick_fix": "Jog axis back into range, check work offsets", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "501", "name": "OVER TRAVEL: -n", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Negative direction software overtravel on axis n.", "causes": ["Axis exceeded negative limit", "Work offset error"], "quick_fix": "Jog axis back into range, check work offsets", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "502", "name": "OVER TRAVEL: +n", "category": "OVERTRAVEL", "severity": "CRITICAL", "description": "Positive direction hardware overtravel on axis n.", "causes": ["Axis hit positive limit switch"], "quick_fix": "Jog axis off limit switch, check for damage", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "503", "name": "OVER TRAVEL: -n", "category": "OVERTRAVEL", "severity": "CRITICAL", "description": "Negative direction hardware overtravel on axis n.", "causes": ["Axis hit negative limit switch"], "quick_fix": "Jog axis off limit switch, check for damage", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "506", "name": "OVER TRAVEL: +n", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Positive stored stroke limit exceeded on axis n.", "causes": ["Programmed position beyond limit"], "quick_fix": "Modify program to stay within limits", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "507", "name": "OVER TRAVEL: -n", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Negative stored stroke limit exceeded on axis n.", "causes": ["Programmed position beyond limit"], "quick_fix": "Modify program to stay within limits", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # Overheat Alarms 700-704
    {"code": "700", "name": "OVERHEAT: CONTROL UNIT", "category": "OVERHEAT", "severity": "CRITICAL", "description": "CNC control unit temperature exceeded safe limit.", "causes": ["Cooling fan failure", "Ambient temp high", "Blocked ventilation"], "quick_fix": "Check fans, clean filters, improve ventilation", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "701", "name": "OVERHEAT: FAN MOTOR", "category": "OVERHEAT", "severity": "HIGH", "description": "Cooling fan motor overheated or failed.", "causes": ["Fan bearing failure", "Fan motor fault"], "quick_fix": "Replace cooling fan", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "704", "name": "OVERHEAT: SPINDLE", "category": "SPINDLE", "severity": "CRITICAL", "description": "Spindle motor temperature exceeded safe limit.", "causes": ["Spindle overworked", "Cooling failure", "Bearing failure"], "quick_fix": "Allow spindle to cool, check cooling system", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # Spindle Alarms 750-784
    {"code": "750", "name": "SPINDLE SERIAL LINK START FAULT", "category": "SPINDLE", "severity": "CRITICAL", "description": "Failed to establish serial communication with spindle amplifier.", "causes": ["Cable fault", "Amplifier fault", "Parameter error"], "quick_fix": "Check spindle communication cable and amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "751", "name": "FIRST SPINDLE ALARM DETECTION (AL-XX)", "category": "SPINDLE", "severity": "CRITICAL", "description": "Alarm detected in first spindle amplifier. XX indicates specific alarm.", "causes": ["Various spindle amplifier faults"], "quick_fix": "Check spindle amplifier LED display for specific fault", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "752", "name": "FIRST SPINDLE MODE CHANGE FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "First spindle failed to change mode (orientation, tapping, etc.).", "causes": ["Mechanical issue", "Amplifier fault"], "quick_fix": "Check spindle mechanics and amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "754", "name": "SPINDLE-1 ABNORMAL TORQUE ALM", "category": "SPINDLE", "severity": "HIGH", "description": "Abnormal torque detected on first spindle.", "causes": ["Tool breakage", "Workpiece issue", "Motor fault"], "quick_fix": "Check tool and workpiece, verify spindle operation", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "761", "name": "SECOND SPINDLE ALARM DETECTION (AL-XX)", "category": "SPINDLE", "severity": "CRITICAL", "description": "Alarm detected in second spindle amplifier.", "causes": ["Various spindle amplifier faults"], "quick_fix": "Check second spindle amplifier LED display", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "762", "name": "SECOND SPINDLE MODE CHANGE FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "Second spindle failed to change mode.", "causes": ["Mechanical issue", "Amplifier fault"], "quick_fix": "Check second spindle mechanics and amplifier", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    
    # System Alarms 900-976
    {"code": "900", "name": "ROM PARITY", "category": "SYSTEM", "severity": "CRITICAL", "description": "ROM parity error detected. System software corruption.", "causes": ["ROM chip failure", "Software corruption"], "quick_fix": "May require ROM replacement or system reload", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "910", "name": "SRAM PARITY: (BYTE 0)", "category": "SYSTEM", "severity": "CRITICAL", "description": "SRAM parity error in byte 0. Memory corruption.", "causes": ["Memory failure", "Battery failure"], "quick_fix": "Check battery, may need memory board replacement", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "920", "name": "SERVO ALARM (1-4 AXIS)", "category": "SYSTEM", "severity": "CRITICAL", "description": "General servo alarm on axes 1-4. Check specific axis.", "causes": ["Various servo faults"], "quick_fix": "Check individual axis alarms for details", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "926", "name": "FSSB ALARM", "category": "SYSTEM", "severity": "CRITICAL", "description": "FSSB (high-speed serial bus) system alarm.", "causes": ["Fiber cable fault", "Amplifier fault"], "quick_fix": "Check all FSSB fiber connections", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "930", "name": "CPU INTERRUPT", "category": "SYSTEM", "severity": "CRITICAL", "description": "CPU interrupt error. System fault.", "causes": ["Hardware failure", "Software error"], "quick_fix": "Power cycle, contact service if repeats", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "950", "name": "PMC SYSTEM ALARM", "category": "SYSTEM", "severity": "CRITICAL", "description": "PMC (Programmable Machine Controller) system error.", "causes": ["PMC program error", "Hardware fault"], "quick_fix": "Check PMC ladder diagram, may need PMC reload", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "951", "name": "PMC WATCH DOG ALARM", "category": "SYSTEM", "severity": "CRITICAL", "description": "PMC watchdog timer expired. PMC stopped responding.", "causes": ["PMC program stuck", "Hardware fault"], "quick_fix": "Check PMC program for infinite loops", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "973", "name": "NON MASK INTERRUPT", "category": "SYSTEM", "severity": "CRITICAL", "description": "Non-maskable interrupt occurred. Critical system fault.", "causes": ["Hardware failure"], "quick_fix": "Check hardware, contact service", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "974", "name": "F-BUS ERROR", "category": "SYSTEM", "severity": "CRITICAL", "description": "F-bus communication error.", "causes": ["Bus hardware fault"], "quick_fix": "Check bus connections, contact service", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
    {"code": "975", "name": "BUS ERROR", "category": "SYSTEM", "severity": "CRITICAL", "description": "System bus error detected.", "causes": ["Hardware fault"], "quick_fix": "Check hardware connections, contact service", "data_source": "CNCCookbook_Fanuc_Alarm_List"},
]

# Add alarm_id and other required fields
for alarm in FANUC_ALARMS:
    alarm['alarm_id'] = f"ALM-FAN-{alarm['code']}"
    alarm['requires_power_cycle'] = alarm['severity'] == 'CRITICAL'
    alarm['confidence'] = 'VERIFIED'

print(f"FANUC alarms prepared: {len(FANUC_ALARMS)} verified entries")
print(f"Categories: {set(a['category'] for a in FANUC_ALARMS)}")
