# MAZAK MAZATROL ALARMS - VERIFIED FROM Multiple Sources
# Sources: HelmanCNC.com, victoriacaruk.com (Mazak Manual), ManualsLib.com, MDCplus.fi
# Valid for: MAZATROL MATRIX, FUSION 640, INTEGREX, VTC series
# Extracted: 2026-01-28

MAZAK_ALARMS = [
    # System/Drive Alarms 1-99
    {"code": "001", "name": "SYSTEM HARDWARE ERROR", "category": "SYSTEM", "severity": "CRITICAL", "description": "Hardware trouble detected in CNC system.", "causes": ["Hardware failure"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "005", "name": "SERVO ABNORMAL (POWER-OFF LEVEL)", "category": "SERVO", "severity": "CRITICAL", "description": "Servo amplifier fault requiring power off.", "causes": ["Servo amplifier failure"], "quick_fix": "Replace servo amplifier, contact Mazak", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "006", "name": "SERVO PARAMETER ERROR", "category": "SERVO", "severity": "HIGH", "description": "Parameters transferred from NC to servo amplifier during power-on are incorrect.", "causes": ["Parameter corruption", "Wrong motor type"], "quick_fix": "Re-set servo parameters, contact Mazak", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "007", "name": "SERVO ABNORMAL (NC RESET LEVEL)", "category": "SERVO", "severity": "HIGH", "description": "Servo fault at NC reset level.", "causes": ["Servo amplifier fault"], "quick_fix": "Contact Mazak with alarm details", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "008", "name": "SERVO ABNORMAL (AMP POWER-OFF LEVEL)", "category": "SERVO", "severity": "CRITICAL", "description": "Servo amplifier power-off level fault.", "causes": ["Servo amplifier failure"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "015", "name": "SPINDLE ABNORMAL (POWER-OFF LEVEL)", "category": "SPINDLE", "severity": "CRITICAL", "description": "Spindle amplifier fault requiring power off.", "causes": ["Spindle amplifier failure"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "016", "name": "SPINDLE PARAMETER ERROR", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle parameters transferred during power-on are incorrect.", "causes": ["Parameter corruption"], "quick_fix": "Re-set spindle parameters", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "017", "name": "SPINDLE ABNORMAL (NC RESET LEVEL)", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle fault at NC reset level.", "causes": ["Spindle amplifier fault"], "quick_fix": "Contact Mazak with alarm details", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "025", "name": "SPINDLE SAFETY SPEED ERROR", "category": "SPINDLE", "severity": "CRITICAL", "description": "Spindle trouble in safety-speed operation mode.", "causes": ["Safety circuit fault", "Spindle fault"], "quick_fix": "Contact Mazak with alarm number details", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "030", "name": "MR-JT-C2 COMMUNICATION ERROR", "category": "COMMUNICATION", "severity": "CRITICAL", "description": "Communication trouble with MR-JT-C2. E2ROM write failure.", "causes": ["Amplifier fault", "Communication cable"], "quick_fix": "Replace MR-JT-C2 amplifier", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "050", "name": "BATTERY LOW", "category": "SYSTEM", "severity": "HIGH", "description": "NC battery reached minimum voltage for retaining parameters and programs.", "causes": ["Battery aging", "Battery failure"], "quick_fix": "Replace battery immediately", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "060", "name": "S-RAM ABNORMAL", "category": "SYSTEM", "severity": "CRITICAL", "description": "S-RAM on CPU card has become abnormal.", "causes": ["Memory failure"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "061", "name": "RAM ABNORMAL", "category": "SYSTEM", "severity": "CRITICAL", "description": "RAM on CPU card has become abnormal.", "causes": ["Memory failure"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "070", "name": "ABSOLUTE POSITION LOST", "category": "ENCODER", "severity": "CRITICAL", "description": "Absolute position detection system lost absolute position data.", "causes": ["Battery failure", "Encoder reset"], "quick_fix": "Re-set absolute position data", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "071", "name": "ABSOLUTE ENCODER ERROR", "category": "ENCODER", "severity": "CRITICAL", "description": "Absolute position detector error detected.", "causes": ["Encoder failure", "Battery failure"], "quick_fix": "Replace encoder or battery", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "072", "name": "ABSOLUTE POSITION MISMATCH", "category": "ENCODER", "severity": "CRITICAL", "description": "Cross-check error between detector absolute position and NC internal coordinate data.", "causes": ["Position data corruption", "Encoder fault"], "quick_fix": "Re-set absolute position data", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    
    # CNC Machine Control Alarms 100-199
    {"code": "100", "name": "OPERATION ERROR", "category": "PROGRAM", "severity": "MEDIUM", "description": "Operation mistake during automatic operation caused tool to overstep software limits.", "causes": ["Wrong operation sequence", "Program error"], "quick_fix": "Review operation sequence and program", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "102", "name": "SERVO-OFF COMMAND", "category": "SERVO", "severity": "LOW", "description": "Servo-off function is active.", "causes": ["Servo-off commanded", "Safety function"], "quick_fix": "Deactivate servo-off function", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "103", "name": "MODE SELECT ERROR", "category": "SYSTEM", "severity": "MEDIUM", "description": "Incorrect mode selection or mode selector switch malfunction.", "causes": ["Switch fault", "Wrong mode selected"], "quick_fix": "Contact Mazak Technical Center", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "105", "name": "CUTTING FEED OVERRIDE ZERO", "category": "PROGRAM", "severity": "LOW", "description": "Cutting-feed override value is set to 0 on operating panel.", "causes": ["Override dial at zero"], "quick_fix": "Set cutting-feed override to value greater than 0", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "106", "name": "MANUAL FEEDRATE ZERO", "category": "PROGRAM", "severity": "LOW", "description": "Manual feedrate set to 0 during automatic operation dry-run.", "causes": ["Manual feedrate dial at zero"], "quick_fix": "Set manual feedrate to value greater than 0", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "110", "name": "SPINDLE ROTATION ERROR", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle did not start rotating when commanded during automatic operation.", "causes": ["Spindle amplifier fault", "Encoder fault", "Motor fault"], "quick_fix": "Check spindle amplifier and encoder", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "111", "name": "SPINDLE SPEED LIMIT EXCEEDED", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle speed limit has been exceeded.", "causes": ["Commanded speed too high", "Amplifier fault"], "quick_fix": "Reduce spindle speed, check amplifier", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "112", "name": "INTERLOCK BLOCK START", "category": "SYSTEM", "severity": "MEDIUM", "description": "Interlock signal to lock start of program block has been input.", "causes": ["PLC interlock active"], "quick_fix": "Check sequence program for interlock condition", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "113", "name": "INTERLOCK CUTTING BLOCK", "category": "SYSTEM", "severity": "MEDIUM", "description": "Interlock signal to lock start of cutting program block has been input.", "causes": ["PLC interlock active"], "quick_fix": "Check sequence program for interlock condition", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "130", "name": "DYNAMIC COMPENSATION OVERFLOW", "category": "PROGRAM", "severity": "HIGH", "description": "Dynamic compensation amount exceeded 3mm (0.12 in).", "causes": ["Workpiece origin too far from table center"], "quick_fix": "Center workpiece coordinate zero in workpiece", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    
    # PLC Machine Control Alarms 200-399
    {"code": "200", "name": "HYDRAULIC UNIT PRESSURE DOWN", "category": "HYDRAULIC", "severity": "CRITICAL", "description": "Low hydraulic pressure state has continued.", "causes": ["Hydraulic pump fault", "Leak", "Filter clogged"], "quick_fix": "Check hydraulic system pressure, pump, and fluid level", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "202", "name": "AIR PRESSURE DOWN", "category": "PNEUMATIC", "severity": "HIGH", "description": "Air pressure below required minimum.", "causes": ["Compressor fault", "Leak", "Regulator fault"], "quick_fix": "Check air supply and pressure regulator", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "203", "name": "SPINDLE OIL PRESSURE DOWN", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle lubrication oil pressure is low.", "causes": ["Pump fault", "Filter clogged", "Low oil level"], "quick_fix": "Check spindle oil pump and level", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "204", "name": "SPINDLE OIL LOW", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle lubrication oil level is low.", "causes": ["Oil consumption", "Leak"], "quick_fix": "Refill spindle oil reservoir", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "206", "name": "SPINDLE CHILLER MALFUNCTION", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle cooling chiller has malfunctioned.", "causes": ["Chiller fault", "Temperature sensor fault"], "quick_fix": "Check chiller operation and coolant level", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "207", "name": "IRREGULAR SLIDEWAY OIL PRESSURE", "category": "LUBRICATION", "severity": "HIGH", "description": "Slideway lubrication oil pressure is irregular.", "causes": ["Pump fault", "Blockage", "Air in system"], "quick_fix": "Check slideway lube system", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "208", "name": "SLIDEWAY OIL LOW", "category": "LUBRICATION", "severity": "HIGH", "description": "Slideway lubrication oil level is low.", "causes": ["Oil consumption", "Leak"], "quick_fix": "Refill slideway oil reservoir", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "211", "name": "SPINDLE CONTROLLER MALFUNCTION", "category": "SPINDLE", "severity": "CRITICAL", "description": "Spindle drive controller has malfunctioned.", "causes": ["Drive fault", "Power supply issue"], "quick_fix": "Check spindle drive for specific fault code", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "212", "name": "MAGAZINE DRUM MALFUNCTION", "category": "ATC", "severity": "HIGH", "description": "Tool magazine drum has malfunctioned.", "causes": ["Motor fault", "Position sensor fault", "Mechanical jam"], "quick_fix": "Check magazine motor and position sensors", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "214", "name": "ILLEGAL TOOL DESIGNATED", "category": "ATC", "severity": "MEDIUM", "description": "Invalid tool number designated for tool change.", "causes": ["Tool number not in magazine", "Wrong T code"], "quick_fix": "Verify tool number exists in magazine", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "217", "name": "THERMAL TRIP", "category": "OVERHEAT", "severity": "CRITICAL", "description": "Thermal protection triggered on motor or drive.", "causes": ["Motor overload", "Cooling failure"], "quick_fix": "Allow cooling, check for overload condition", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "218", "name": "CONVEYOR THERMAL TRIP", "category": "OVERHEAT", "severity": "HIGH", "description": "Chip conveyor motor thermal protection triggered.", "causes": ["Conveyor overloaded", "Motor fault"], "quick_fix": "Clear chip buildup, allow motor to cool", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "219", "name": "MAIN TRANSFORMER OVERHEAT", "category": "OVERHEAT", "severity": "CRITICAL", "description": "Main power transformer temperature exceeded safe limit.", "causes": ["Cooling failure", "Overload", "Ambient temp high"], "quick_fix": "Allow cooling, check ventilation", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "222", "name": "AFC OVERLOAD", "category": "SYSTEM", "severity": "HIGH", "description": "Adaptive Feed Control system overload.", "causes": ["Cutting load too high", "Tool dull"], "quick_fix": "Reduce cutting parameters, check tool condition", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    {"code": "223", "name": "TOOL MEASUREMENT UNIT NOT IN POSITION", "category": "ATC", "severity": "MEDIUM", "description": "Tool measurement unit not in expected position.", "causes": ["Unit not retracted", "Position sensor fault"], "quick_fix": "Check tool setter position and sensors", "data_source": "Mazak_VTC_Manual_ManualsLib"},
    
    # Screen Operation Alarms 400-499
    {"code": "401", "name": "INPUT DATA FORMAT ERROR", "category": "PROGRAM", "severity": "MEDIUM", "description": "Format of input data is not valid.", "causes": ["Wrong data format", "Invalid characters"], "quick_fix": "Correct data format", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "440", "name": "PROGRAM LOCK ENABLED", "category": "PROGRAM", "severity": "LOW", "description": "Operation cannot be performed - program lock enabled.", "causes": ["Program protection active"], "quick_fix": "Set PROGRAM LOCK/ENABLE switch to ENABLE", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "441", "name": "TOOL IN SPINDLE", "category": "PROGRAM", "severity": "MEDIUM", "description": "Operation cannot be performed while tool is in spindle.", "causes": ["Tool still mounted"], "quick_fix": "Remove tool from spindle first", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "450", "name": "DATA NOT FOUND", "category": "PROGRAM", "severity": "MEDIUM", "description": "Designated number or character string does not exist in program.", "causes": ["Wrong search target", "Data deleted"], "quick_fix": "Designate an existent number or string", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    {"code": "451", "name": "MEMORY DATA DESTROYED", "category": "MEMORY", "severity": "CRITICAL", "description": "Memory contents in machining program storage area have been destroyed.", "causes": ["Power loss during edit", "Memory fault"], "quick_fix": "Delete corrupted program", "data_source": "Mazak_MATRIX_Manual_HelmanCNC"},
    
    # Interference Alarms 2100-2199
    {"code": "2100", "name": "INTERFERENCE DETECTED", "category": "SAFETY", "severity": "CRITICAL", "description": "Interference between moving groups detected. Collision prevention active.", "causes": ["Tool path collision risk", "Turret/spindle interference"], "quick_fix": "Modify program to avoid interference zone", "data_source": "Mazak_MDCplus"},
]

for alarm in MAZAK_ALARMS:
    alarm['alarm_id'] = f"ALM-MAZ-{alarm['code']}"
    alarm['requires_power_cycle'] = alarm['severity'] == 'CRITICAL'
    alarm['confidence'] = 'VERIFIED'

print(f"MAZAK alarms prepared: {len(MAZAK_ALARMS)} verified entries")
