# HAAS ALARMS - VERIFIED FROM Multiple Sources
# Sources: HelmanCNC.com, CNCReplacementParts.com, Pearl-hifi.com (Haas Manual), MDCplus.fi
# Valid for: Haas NGC, VF series, EC series, ST series
# Extracted: 2026-01-28

import json

HAAS_ALARMS = [
    # Communication/System Alarms 101-112
    {"code": "101", "name": "COMM. FAILURE WITH MOCON/MOCON MEMORY FAULT", "category": "SYSTEM", "severity": "CRITICAL", "description": "Communication failure between MOCON and main processor during self-test, or MOCON memory fault detected.", "causes": ["Cable connection loose", "ADDRESS/DATA bus cable fault", "MOCON board failure", "Main processor failure"], "quick_fix": "Check cable connections, re-seat bus cables, check MOCON/processor status lights", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "102", "name": "SERVOS OFF", "category": "SERVO", "severity": "MEDIUM", "description": "Servo motors are off, tool changer disabled, coolant off, spindle stopped. Normal at startup.", "causes": ["Emergency stop pressed", "Motor fault", "Power failure", "Normal startup state"], "quick_fix": "Press RESET to power servos on if no other fault exists", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "103", "name": "X SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "X-axis servo motor load exceeded parameter 9 maximum error. Position deviation too large.", "causes": ["Mechanical binding on X axis", "Ballscrew damage", "Servo motor fault", "Encoder fault"], "quick_fix": "Check X axis for mechanical binding, verify encoder, press RESET", "data_source": "Haas_Manual_HelmanCNC_MDCplus"},
    {"code": "104", "name": "Y SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "Y-axis servo motor load exceeded maximum error parameter. Position deviation too large.", "causes": ["Mechanical binding on Y axis", "Ballscrew damage", "Servo motor fault", "Encoder fault"], "quick_fix": "Check Y axis for mechanical binding, verify encoder, press RESET", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "105", "name": "Z SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "Z-axis servo motor load exceeded maximum error parameter. Position deviation too large.", "causes": ["Mechanical binding on Z axis", "Counterbalance issue", "Servo motor fault", "Encoder fault"], "quick_fix": "Check Z axis mechanics including counterbalance, press RESET", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "106", "name": "A SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "A-axis (rotary) servo motor load exceeded maximum error. Position deviation too large.", "causes": ["Mechanical binding", "Rotary table issue", "Servo motor fault"], "quick_fix": "Check A axis rotary table mechanics, press RESET", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "107", "name": "EMERGENCY OFF", "category": "SAFETY", "severity": "CRITICAL", "description": "Emergency stop button pressed or E-stop circuit triggered.", "causes": ["E-stop button pressed", "E-stop circuit fault", "Safety interlock triggered"], "quick_fix": "Release E-stop button, check safety interlocks, press RESET", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "108", "name": "X SERVO OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "X-axis servo motor current exceeded safe limits. Thermal protection may be active.", "causes": ["Excessive cutting load", "Mechanical binding", "Motor overheating", "Drive fault"], "quick_fix": "Reduce cutting load, check for binding, allow motor to cool", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "109", "name": "Y SERVO OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "Y-axis servo motor current exceeded safe limits.", "causes": ["Excessive cutting load", "Mechanical binding", "Motor overheating"], "quick_fix": "Reduce cutting load, check for binding, allow motor to cool", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "110", "name": "Z SERVO OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "Z-axis servo motor current exceeded safe limits.", "causes": ["Excessive cutting load", "Counterbalance failure", "Motor overheating"], "quick_fix": "Check counterbalance, reduce load, allow motor to cool", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "111", "name": "A SERVO OVERLOAD", "category": "SERVO", "severity": "CRITICAL", "description": "A-axis servo motor current exceeded safe limits.", "causes": ["Excessive load", "Rotary table binding", "Motor overheating"], "quick_fix": "Reduce load, check rotary table, allow motor to cool", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "112", "name": "NO INTERRUPT", "category": "SYSTEM", "severity": "CRITICAL", "description": "System interrupt signal not received. Control board communication fault.", "causes": ["Control board fault", "Cable connection issue"], "quick_fix": "Power cycle, check board connections, contact service if persists", "data_source": "Haas_Manual_HelmanCNC"},
    
    # Tool Changer Alarms 113-115 (Mill/Lathe variants)
    {"code": "113", "name": "SHUTTLE IN FAULT (Mill) / TURRET UNLOCK FAULT (Lathe)", "category": "ATC", "severity": "HIGH", "description": "Mill: Tool shuttle failed to move to spindle. Lathe: Turret failed to unlock.", "causes": ["Shuttle mechanism jam", "Turret clamp issue", "Proximity sensor fault", "Hydraulic/pneumatic fault"], "quick_fix": "Check tool changer mechanism, verify sensors, check air/hydraulic pressure", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "114", "name": "SHUTTLE OUT FAULT (Mill) / TURRET LOCK FAULT (Lathe)", "category": "ATC", "severity": "HIGH", "description": "Mill: Tool shuttle failed to retract. Lathe: Turret failed to lock after index.", "causes": ["Shuttle mechanism jam", "Turret clamp issue", "Proximity sensor fault"], "quick_fix": "Check mechanism for obstruction, verify sensor operation", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "115", "name": "TURRET ROTATE FAULT", "category": "ATC", "severity": "HIGH", "description": "Tool turret/carousel failed to start rotating or failed to stop at correct position.", "causes": ["Motor fault", "Encoder fault", "Mechanical jam", "Parameter 62/63 timing"], "quick_fix": "Check turret motor, verify position sensor, adjust parameters 62/63", "data_source": "Haas_Manual_HelmanCNC"},
    
    # Spindle Alarms 116-121
    {"code": "116", "name": "SPINDLE ORIENTATION FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle failed to reach orientation position for tool change or tapping.", "causes": ["Orientation sensor fault", "Spindle drive fault", "Belt slip", "Encoder fault"], "quick_fix": "Check spindle orientation sensor and encoder, verify belt tension", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "117", "name": "SPINDLE HIGH GEAR FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle failed to shift to high gear range.", "causes": ["Gear shift mechanism fault", "Solenoid fault", "Proximity sensor fault"], "quick_fix": "Check gear shift mechanism and solenoids", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "118", "name": "SPINDLE LOW GEAR FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle failed to shift to low gear range.", "causes": ["Gear shift mechanism fault", "Solenoid fault", "Proximity sensor fault"], "quick_fix": "Check gear shift mechanism and solenoids", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "119", "name": "ATC FAULT", "category": "ATC", "severity": "HIGH", "description": "General automatic tool changer fault detected.", "causes": ["ATC mechanism fault", "Tool not seated", "Carousel position error"], "quick_fix": "Check ATC mechanism, verify tool positions, run ATC recovery", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "120", "name": "SPINDLE FAULT", "category": "SPINDLE", "severity": "CRITICAL", "description": "General spindle drive fault detected.", "causes": ["Spindle drive fault", "Motor fault", "Overtemperature"], "quick_fix": "Check spindle drive display for specific error code", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "121", "name": "TOOL UNCLAMPED", "category": "SPINDLE", "severity": "CRITICAL", "description": "Tool not properly clamped in spindle during operation.", "causes": ["Drawbar fault", "Low air pressure", "Tool not seated properly"], "quick_fix": "Verify air pressure, check drawbar operation, reseat tool", "data_source": "Haas_Manual_CNCKnowledge"},
    
    # Overtravel Alarms 130-159
    {"code": "130", "name": "TOOL NOT FOUND", "category": "ATC", "severity": "HIGH", "description": "Programmed tool number not found in tool magazine.", "causes": ["Wrong tool number programmed", "Tool not loaded", "Tool table error"], "quick_fix": "Verify tool is in magazine and tool table is correct", "data_source": "Haas_CNCKnowledge"},
    {"code": "151", "name": "OVERTRAVEL +X", "category": "OVERTRAVEL", "severity": "HIGH", "description": "X-axis exceeded positive software travel limit.", "causes": ["Program error", "Work offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check work offsets and program", "data_source": "Haas_CNCKnowledge"},
    {"code": "152", "name": "OVERTRAVEL -X", "category": "OVERTRAVEL", "severity": "HIGH", "description": "X-axis exceeded negative software travel limit.", "causes": ["Program error", "Work offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check work offsets and program", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "153", "name": "OVERTRAVEL +Y", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Y-axis exceeded positive software travel limit.", "causes": ["Program error", "Work offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check work offsets and program", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "154", "name": "OVERTRAVEL -Y", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Y-axis exceeded negative software travel limit.", "causes": ["Program error", "Work offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check work offsets and program", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "155", "name": "OVERTRAVEL +Z", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Z-axis exceeded positive software travel limit.", "causes": ["Program error", "Tool length offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check tool length offsets", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "156", "name": "OVERTRAVEL -Z", "category": "OVERTRAVEL", "severity": "HIGH", "description": "Z-axis exceeded negative software travel limit.", "causes": ["Program error", "Tool length offset error", "Manual jog beyond limit"], "quick_fix": "Jog axis back into range, check tool length offsets", "data_source": "Haas_CNCKnowledge"},
    {"code": "160", "name": "SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "General servo following error exceeded tolerance on any axis.", "causes": ["Mechanical binding", "Servo fault", "Encoder fault"], "quick_fix": "Check which axis has error, inspect mechanical system", "data_source": "Haas_CNCKnowledge"},
    
    # Drive Faults 161-164
    {"code": "161", "name": "X AXIS DRIVE FAULT", "category": "SERVO", "severity": "CRITICAL", "description": "X-axis servo drive amplifier fault detected.", "causes": ["Drive overheated", "Drive hardware fault", "Power supply issue"], "quick_fix": "Check drive status LEDs, allow cooling, check power", "data_source": "Haas_MDCplus"},
    {"code": "162", "name": "Y AXIS DRIVE FAULT", "category": "SERVO", "severity": "CRITICAL", "description": "Y-axis servo drive amplifier fault detected.", "causes": ["Drive overheated", "Drive hardware fault", "Power supply issue"], "quick_fix": "Check drive status LEDs, allow cooling, check power", "data_source": "Haas_MDCplus"},
    {"code": "163", "name": "Z AXIS DRIVE FAULT", "category": "SERVO", "severity": "CRITICAL", "description": "Z-axis servo drive amplifier fault detected.", "causes": ["Drive overheated", "Drive hardware fault", "Power supply issue"], "quick_fix": "Check drive status LEDs, allow cooling, check power", "data_source": "Haas_MDCplus"},
    {"code": "164", "name": "A AXIS DRIVE FAULT", "category": "SERVO", "severity": "CRITICAL", "description": "A-axis servo drive amplifier fault detected.", "causes": ["Drive overheated", "Drive hardware fault", "Power supply issue"], "quick_fix": "Check drive status LEDs, allow cooling, check power", "data_source": "Haas_MDCplus"},
    {"code": "169", "name": "SPINDLE DIRECTION FAULT", "category": "SPINDLE", "severity": "HIGH", "description": "Problem with rigid tapping hardware. Spindle direction feedback error.", "causes": ["Rigid tapping sensor fault", "Encoder fault"], "quick_fix": "Check rigid tapping hardware and spindle encoder", "data_source": "Haas_Manual_HelmanCNC"},
    
    # APC/Pallet Alarms 171
    {"code": "171", "name": "APC-PALLET CLAMP TIMEOUT", "category": "ATC", "severity": "HIGH", "description": "Pallet in mill did not clamp within allowed time.", "causes": ["Foreign object under pallet", "Air pressure low", "Solenoid stuck", "Sensor fault"], "quick_fix": "Check for obstructions, verify air pressure, check solenoids", "data_source": "Haas_Manual_HelmanCNC"},
    
    # Additional Alarms 181-200
    {"code": "181", "name": "MACRO NOT COMPLETED - SPINDLE DISABLED", "category": "PROGRAM", "severity": "HIGH", "description": "Macro code for optional equipment not completed due to E-stop, reset, or power down.", "causes": ["Program interrupted", "E-stop pressed during macro"], "quick_fix": "Check optional equipment status, restart macro", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "186", "name": "SPINDLE NOT TURNING", "category": "SPINDLE", "severity": "HIGH", "description": "Spindle not turning when commanded. Check for G99 feed per revolution mode.", "causes": ["Spindle drive fault", "Belt broken", "Wrong programming mode"], "quick_fix": "Check spindle drive, verify belt, check G98/G99 mode", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "187", "name": "B SERVO ERROR TOO LARGE", "category": "SERVO", "severity": "CRITICAL", "description": "B-axis servo motor position error exceeded Parameter 159.", "causes": ["Mechanical binding", "Motor fault", "Encoder fault"], "quick_fix": "Check B axis mechanics, motor, and encoder", "data_source": "Haas_Manual_HelmanCNC"},
    {"code": "197", "name": "MISC. SOFTWARE ERROR", "category": "SYSTEM", "severity": "HIGH", "description": "Miscellaneous software error detected in control.", "causes": ["Software bug", "Memory corruption"], "quick_fix": "Power cycle machine, contact Haas if persists", "data_source": "Haas_CNCReplacementParts"},
    {"code": "200", "name": "VD OVER TEMP", "category": "OVERHEAT", "severity": "CRITICAL", "description": "Vector drive (spindle drive) temperature exceeded safe limit.", "causes": ["Drive overworked", "Cooling fan failure", "Ambient temp high"], "quick_fix": "Allow drive to cool, check cooling fans, reduce spindle load", "data_source": "Haas_CNCReplacementParts"},
    {"code": "208", "name": "SPINDLE OVERHEAT", "category": "SPINDLE", "severity": "CRITICAL", "description": "Spindle motor or bearing temperature exceeded safe limits.", "causes": ["Spindle overworked", "Bearing failure", "Cooling failure"], "quick_fix": "Stop spindle, allow cooling, check bearings if persists", "data_source": "Haas_CNCKnowledge"},
    {"code": "214", "name": "NO. OF PROGRAMS CHANGED", "category": "SYSTEM", "severity": "LOW", "description": "Number of programs in memory has changed since last edit.", "causes": ["Program added or deleted"], "quick_fix": "Informational only, verify program list is correct", "data_source": "Haas_CNCReplacementParts"},
    
    # Spindle Drive Faults 2040
    {"code": "2040", "name": "SPINDLE DRIVE FAULT", "category": "SPINDLE", "severity": "CRITICAL", "description": "Fault detected in spindle drive system.", "causes": ["Drive hardware fault", "Motor fault", "Power supply issue"], "quick_fix": "Check spindle drive status display for specific fault code", "data_source": "Haas_CNCKnowledge"},
    
    # Tool Change Alarms 317
    {"code": "317", "name": "TOOL CHANGE FAULT", "category": "ATC", "severity": "HIGH", "description": "Mechanical issue detected during tool change operation.", "causes": ["Tool stuck", "Carousel jam", "Arm fault", "Sensor fault"], "quick_fix": "Check ATC mechanism for obstructions, verify all sensors", "data_source": "Haas_CNCKnowledge"},
    
    # Macro/Program Alarms 517-525
    {"code": "517", "name": "EXPRSN. NOT ALLOWED WITH N OR O", "category": "PROGRAM", "severity": "MEDIUM", "description": "Expression not allowed with N (sequence) or O (program) addresses.", "causes": ["Syntax error in macro program"], "quick_fix": "Edit program to correct macro syntax", "data_source": "Haas_CNCReplacementParts"},
    {"code": "518", "name": "ILLEGAL MACRO EXPRESSION REFERENCE", "category": "PROGRAM", "severity": "MEDIUM", "description": "Invalid reference in macro expression.", "causes": ["Undefined variable", "Syntax error"], "quick_fix": "Check macro variable references", "data_source": "Haas_CNCReplacementParts"},
    {"code": "522", "name": "ILLEGAL ASSIGNMENT VAR OR VALUE", "category": "PROGRAM", "severity": "MEDIUM", "description": "Illegal variable assignment or value in macro.", "causes": ["Read-only variable", "Invalid value"], "quick_fix": "Check variable assignment in macro", "data_source": "Haas_CNCReplacementParts"},
    {"code": "523", "name": "CONDITIONAL REQUIRED PRIOR TO THEN", "category": "PROGRAM", "severity": "MEDIUM", "description": "IF statement missing before THEN in macro.", "causes": ["Macro syntax error"], "quick_fix": "Add IF conditional before THEN statement", "data_source": "Haas_CNCReplacementParts"},
    {"code": "525", "name": "VAR. REF. ILLEGAL DURING MOVEMENT", "category": "PROGRAM", "severity": "MEDIUM", "description": "Variable reference not allowed during axis motion.", "causes": ["Trying to read variable during move"], "quick_fix": "Read variable before or after motion block", "data_source": "Haas_CNCReplacementParts"},
    
    # Communication Alarms 791
    {"code": "791", "name": "COMM. FAILURE WITH MOCON2", "category": "SYSTEM", "severity": "CRITICAL", "description": "Communication failure with secondary MOCON board.", "causes": ["Cable fault", "MOCON2 board failure"], "quick_fix": "Check cable connections to MOCON2 board", "data_source": "Haas_CNCReplacementParts"},
    
    # G-code Alarms 802
    {"code": "802", "name": "NEGATIVE R AND C VALUES NOT ALLOWED", "category": "PROGRAM", "severity": "MEDIUM", "description": "Negative values for R (radius) or C (chamfer) not permitted.", "causes": ["Programming error"], "quick_fix": "Use positive values for R and C", "data_source": "Haas_CNCReplacementParts"},
    
    # Low Battery 
    {"code": "191", "name": "LOW BATTERY", "category": "SYSTEM", "severity": "HIGH", "description": "Control backup battery voltage is low. Risk of memory/parameter loss.", "causes": ["Battery aging", "Battery failure"], "quick_fix": "Replace backup battery soon", "data_source": "Haas_MDCplus"},
]

# Add alarm_id and other required fields
for alarm in HAAS_ALARMS:
    alarm['alarm_id'] = f"ALM-HAAS-{alarm['code']}"
    alarm['requires_power_cycle'] = alarm['severity'] == 'CRITICAL'
    alarm['confidence'] = 'VERIFIED'

print(f"HAAS alarms prepared: {len(HAAS_ALARMS)} verified entries")
