#!/usr/bin/env node
/**
 * dashboard-serve.mjs — PRISM-STAB-MS0/U-B6-light + U-C3 (2026-05-09).
 *
 * Local dashboard for PRISM context bundle and handoff browser. Vanilla
 * Node http (no Express, no Quartz install required). Combines what the
 * spec called Phase B6 (Quartz HTML) and Phase C3 (browseable context
 * dashboard) into one minimal server.
 *
 * Port: 8766 (system-viz uses 8765 — different process, different lifecycle)
 *
 * Routes:
 *   GET /                       landing page
 *   GET /context                context-bundle.html (rendered by C1 daemon)
 *   GET /context.json           context-bundle.json (raw)
 *   GET /context.md             context-bundle.md (raw)
 *   GET /handoffs               list of all per-chat handoffs
 *   GET /handoff/<name>         specific handoff rendered as HTML
 *   GET /handoff/<name>.md      specific handoff raw markdown
 *   GET /healthz                liveness check
 *
 * Read-only — never writes. Files come from C1 daemon and per-agent-handoff.
 * Run via daemon-supervisor:
 *   node scripts/daemon-supervisor.mjs start dashboard -- \
 *     "H:/Tools/nodejs/node.exe" "H:/prism/scripts/dashboard-serve.mjs"
 */

import http from "node:http";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import path from "node:path";

const PORT = Number(process.env.PRISM_DASHBOARD_PORT || 8766);
const HOST = process.env.PRISM_DASHBOARD_HOST || "127.0.0.1";

const PATHS = {
  contextHtml: "H:/prism/state/shared/context-bundle.html",
  contextJson: "H:/prism/state/shared/context-bundle.json",
  contextMd: "H:/prism/state/shared/context-bundle.md",
  handoffsDir: "H:/prism/state/shared/handoffs",
};

function send(res, status, body, contentType = "text/html; charset=utf-8") {
  res.writeHead(status, { "Content-Type": contentType, "Cache-Control": "no-cache" });
  res.end(body);
}

function send404(res, what) {
  send(res, 404, `<h1>404</h1><p>Not found: ${escape(what)}</p>`);
}

function escape(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function safeName(s) {
  // Allow letters/digits/hyphens/dots/underscores; strip path separators.
  return String(s).replace(/[^a-zA-Z0-9._-]/g, "");
}

function readSafe(p) {
  try { return readFileSync(p, "utf-8"); } catch { return null; }
}

function landing() {
  let bundleAge = "?";
  try {
    const stat = statSync(PATHS.contextJson);
    bundleAge = Math.round((Date.now() - stat.mtimeMs) / 1000) + "s";
  } catch { /* unknown */ }

  let handoffCount = 0;
  try {
    handoffCount = readdirSync(PATHS.handoffsDir).filter((f) => f.startsWith("HANDOFF-") && f.endsWith(".md")).length;
  } catch { /* unknown */ }

  return `<!doctype html>
<html><head>
<meta charset="utf-8"><title>PRISM Dashboard</title>
<style>
body{font:14px/1.45 ui-monospace,monospace;background:#0e1117;color:#c9d1d9;margin:0;padding:32px;max-width:900px}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
h1,h2{color:#58a6ff}
.card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin:12px 0}
.muted{color:#7d8590}
code{background:#21262d;padding:1px 6px;border-radius:3px}
</style></head><body>
<h1>PRISM Dashboard</h1>
<p class="muted">Local read-only browser for context bundle + handoffs. Port ${PORT}.</p>

<div class="card">
  <h2>Context Bundle</h2>
  <p class="muted">Refreshed every 30s by <code>prism-awareness-bundle.mjs --daemon</code>. Last write: ${bundleAge} ago.</p>
  <ul>
    <li><a href="/context">/context</a> — rendered HTML</li>
    <li><a href="/context.json">/context.json</a> — raw JSON</li>
    <li><a href="/context.md">/context.md</a> — raw markdown</li>
  </ul>
</div>

<div class="card">
  <h2>Per-Chat Handoffs (${handoffCount})</h2>
  <p class="muted">One per Claude/Codex session. Frontmatter keys: session, topic, machine, status. Also indexed in Obsidian via the <code>knowledge/handoffs/</code> NTFS junction.</p>
  <ul>
    <li><a href="/handoffs">/handoffs</a> — list all</li>
  </ul>
</div>

<div class="card">
  <h2>Cross-Links</h2>
  <ul>
    <li><a href="http://127.0.0.1:8765/" target="_blank">System-viz</a> — 3D codebase graph (port 8765, separate daemon)</li>
    <li><a href="/healthz">/healthz</a> — liveness</li>
  </ul>
</div>

<p class="muted">Generated by <code>scripts/dashboard-serve.mjs</code>. Stop: <code>node scripts/daemon-supervisor.mjs stop dashboard</code>.</p>
</body></html>`;
}

function listHandoffs() {
  let files = [];
  try {
    files = readdirSync(PATHS.handoffsDir)
      .filter((f) => f.startsWith("HANDOFF-") && f.endsWith(".md"))
      .map((f) => {
        const fp = path.join(PATHS.handoffsDir, f);
        const stat = statSync(fp);
        return { name: f, mtime: stat.mtimeMs, size: stat.size };
      })
      .sort((a, b) => b.mtime - a.mtime);
  } catch { /* dir missing */ }

  const rows = files.map((f) => {
    const ageMin = Math.round((Date.now() - f.mtime) / 60000);
    const ageStr = ageMin < 60 ? `${ageMin}m` : `${Math.round(ageMin / 60)}h`;
    const linkName = encodeURIComponent(f.name.replace(/\.md$/, ""));
    return `<tr><td><a href="/handoff/${linkName}">${escape(f.name)}</a></td><td class="muted">${ageStr}</td><td class="muted">${f.size}B</td></tr>`;
  }).join("");

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Handoffs (${files.length})</title>
<style>body{font:14px/1.45 ui-monospace,monospace;background:#0e1117;color:#c9d1d9;margin:0;padding:24px;max-width:1100px}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
table{border-collapse:collapse;width:100%}td{padding:6px 12px;border-bottom:1px solid #30363d}
.muted{color:#7d8590}h1{color:#58a6ff}
</style></head><body>
<h1>Handoffs (${files.length})</h1>
<p><a href="/">← back</a></p>
<table><tbody>${rows}</tbody></table>
</body></html>`;
}

function renderHandoff(name, asMarkdown) {
  const safe = safeName(name);
  if (!safe) return null;
  const file = safe.endsWith(".md") ? safe : `${safe}.md`;
  const fp = path.join(PATHS.handoffsDir, file);
  if (!existsSync(fp)) return null;
  const md = readSafe(fp);
  if (md === null) return null;
  if (asMarkdown) return { type: "text/markdown; charset=utf-8", body: md };
  // Render minimal: <pre>-wrap with light highlight on YAML frontmatter and ## headings
  const escaped = escape(md);
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escape(file)}</title>
<style>body{font:14px/1.5 ui-monospace,monospace;background:#0e1117;color:#c9d1d9;margin:0;padding:24px;max-width:900px}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
h1{color:#58a6ff}pre{white-space:pre-wrap;word-break:break-word;background:#161b22;padding:16px;border-radius:8px}
.muted{color:#7d8590}
</style></head><body>
<h1>${escape(file)}</h1>
<p><a href="/handoffs">← all handoffs</a> · <a href="/handoff/${encodeURIComponent(safe.replace(/\.md$/, ""))}.md">raw .md</a></p>
<pre>${escaped}</pre>
</body></html>`;
  return { type: "text/html; charset=utf-8", body: html };
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url || "/", `http://${HOST}`);
  const p = url.pathname;

  if (p === "/" || p === "/index.html") return send(res, 200, landing());
  if (p === "/healthz") return send(res, 200, JSON.stringify({ ok: true, port: PORT, ts: new Date().toISOString() }), "application/json");

  if (p === "/context") {
    const html = readSafe(PATHS.contextHtml);
    if (!html) return send404(res, p);
    return send(res, 200, html);
  }
  if (p === "/context.json") {
    const json = readSafe(PATHS.contextJson);
    if (!json) return send404(res, p);
    return send(res, 200, json, "application/json");
  }
  if (p === "/context.md") {
    const md = readSafe(PATHS.contextMd);
    if (!md) return send404(res, p);
    return send(res, 200, md, "text/markdown; charset=utf-8");
  }

  if (p === "/handoffs") return send(res, 200, listHandoffs());

  const handoffMatch = p.match(/^\/handoff\/(.+?)(\.md)?$/);
  if (handoffMatch) {
    const result = renderHandoff(handoffMatch[1], !!handoffMatch[2]);
    if (!result) return send404(res, p);
    return send(res, 200, result.body, result.type);
  }

  send404(res, p);
});

server.listen(PORT, HOST, () => {
  process.stdout.write(`PRISM dashboard on http://${HOST}:${PORT}/\n`);
});
