// Test -- hermes-enrichment-to-alpaca.mjs pure converter helpers (U-HERMES-LORA-CORPUS).
// Run: node scripts/hermes-enrichment-to-alpaca.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  tipDomain, cleanBody, cleanCite, hermesTipToAlpaca, convertStaging,
} from "./hermes-enrichment-to-alpaca.mjs";

const TIP = {
  id: "hkl-mill-001",
  title: "Select shrink-fit holders over ER collets for carbide tools under 6 mm.",
  body: "Select shrink-fit holders over ER collets for carbide tools under 6 mm. | formula/threshold: Max TIR = 0.003 mm for D <= 6 mm. | GENERATED BY ENRICHMENT-LOOP (cron) -- specialist must verify",
  tags: ["domain:mill", "hermes:grok-4.20", "verify:unreviewed-cron"],
  source: "hermes:enrichment-loop | cite: Sandvik Coromant Milling Technical Guide, 2022 ed., p. 68.",
  category: "milling",
};

test("tipDomain: domain:<x> tag wins; falls back to category, then general", () => {
  assert.equal(tipDomain(TIP), "mill");
  assert.equal(tipDomain({ tags: ["x"], category: "Lathe" }), "lathe");
  assert.equal(tipDomain({ tags: [] }), "general");
  assert.equal(tipDomain(null), "general");
});

test("cleanBody: strips the enrichment-loop cron marker, keeps rule + threshold", () => {
  const b = cleanBody(TIP.body);
  assert.match(b, /Max TIR = 0\.003 mm/);
  assert.ok(!/GENERATED BY ENRICHMENT-LOOP/.test(b), "cron marker must be stripped");
  assert.equal(cleanBody(""), "");
  assert.equal(cleanBody(null), "");
});

test("cleanCite: extracts the bare citation; empty for a bare loop source", () => {
  assert.equal(cleanCite(TIP.source), "Sandvik Coromant Milling Technical Guide, 2022 ed., p. 68.");
  assert.equal(cleanCite("hermes:enrichment-loop"), "");
  assert.equal(cleanCite("Machinery's Handbook 31e"), "Machinery's Handbook 31e");
  assert.equal(cleanCite(null), "");
});

test("hermesTipToAlpaca: builds {instruction,output,galaxy}; output adds detail+cite beyond instruction", () => {
  const r = hermesTipToAlpaca(TIP);
  assert.equal(r.galaxy, "mill");
  assert.match(r.instruction, /^PRISM mill machining best-practice\./);
  assert.match(r.instruction, /Topic: Select shrink-fit holders/);
  assert.match(r.output, /Max TIR = 0\.003 mm/);          // formula/threshold = info beyond the instruction
  assert.match(r.output, /Source: Sandvik Coromant/);     // real citation carried
  assert.ok(!/GENERATED BY ENRICHMENT-LOOP/.test(r.output));
  assert.ok(!/\.\./.test(r.output), "no double period (cite trailing dot stripped before the Source. terminator)");
});

test("hermesTipToAlpaca: no title -> null; missing cite -> no Source line", () => {
  assert.equal(hermesTipToAlpaca({ tags: ["domain:mill"] }), null);
  assert.equal(hermesTipToAlpaca(null), null);
  const noCite = hermesTipToAlpaca({ title: "Climb mill aluminum.", tags: ["domain:mill"], source: "hermes:enrichment-loop", body: "Climb mill aluminum." });
  assert.ok(!/Source:/.test(noCite.output));
});

test("convertStaging: distinct titles -> unique instructions (no contradiction); dedups identical", () => {
  const doc = { tips: [
    TIP,
    { id: "hkl-cad-002", title: "AP242 preserves PMI; AP214 drops it.", tags: ["domain:cad"], source: "ISO 10303-242", body: "AP242 preserves PMI." },
    TIP, // exact duplicate -> deduped by instruction
  ] };
  const rows = convertStaging(doc);
  assert.equal(rows.length, 2);                            // dup collapsed
  const instr = new Set(rows.map((r) => r.instruction));
  assert.equal(instr.size, 2);                             // unique instructions -> not contradictory SFT
  assert.deepEqual(rows.map((r) => r.galaxy).sort(), ["cad", "mill"]);
});

test("convertStaging: empty / garbage -> [] (never throws)", () => {
  assert.deepEqual(convertStaging({}), []);
  assert.deepEqual(convertStaging({ tips: [] }), []);
  assert.deepEqual(convertStaging(null), []);
});
