<#
.SYNOPSIS
    Register a Windows Scheduled Task that runs the quoting calibration pipeline nightly.

.DESCRIPTION
    iter26 — operator-facing installer for the iter9-25 quoting calibration chain.
    Registers "PRISM Quoting Pipeline" task that runs the full 4-stage chain
    (bootstrap -> docustrata-overlay -> train-cycle -> drift-alert) at the
    configured time, captures stdout/stderr to a per-run log, and exits with
    the drift-alert exit code (0=ok, 1=warn, 2=alert).

    Idempotent: if a task with the same name already exists, this script
    UPDATES it rather than failing.

    Exit codes (from this installer):
        0  — task registered / updated successfully
        1  — installer error (not elevated, paths missing, etc.)

.PARAMETER TaskName
    Scheduled Task name. Default: "PRISM Quoting Pipeline"

.PARAMETER TriggerHour
    Hour-of-day (0-23) the task fires. Default: 3 (3am local).

.PARAMETER PrismRoot
    Path to the prism repo root. Default: H:\prism

.PARAMETER NodeExe
    Path to node.exe. Default: H:\Tools\nodejs\node.exe (portable node)

.PARAMETER DryRun
    If set, prints the task spec instead of registering. Useful for ops review
    before commit.

.EXAMPLE
    # First-time install (elevated PowerShell required for system-level task)
    .\install-quoting-pipeline-cron.ps1

.EXAMPLE
    # Custom hour + dry-run inspection
    .\install-quoting-pipeline-cron.ps1 -TriggerHour 2 -DryRun

.NOTES
    Filed under QUOTING-SYNERGY-MS0/U-QP-CRON-INSTALL (charlie /goal-yolo iter26).
    Companion docs: state/shared/quoting/PIPELINE-RUNBOOK.md
                    knowledge/wiki/architecture/quoting-training-pipeline.md
#>

[CmdletBinding()]
param(
    [string]$TaskName = "PRISM Quoting Pipeline",
    [ValidateRange(0, 23)]
    [int]$TriggerHour = 3,
    [string]$PrismRoot = "H:\prism",
    [string]$NodeExe = "H:\Tools\nodejs\node.exe",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# --- Pre-flight ---

if (-not (Test-Path $PrismRoot)) {
    Write-Error "PrismRoot not found: $PrismRoot"
    exit 1
}
if (-not (Test-Path $NodeExe)) {
    Write-Warning "NodeExe not found at $NodeExe — falling back to PATH lookup"
    $NodeExe = (Get-Command node -ErrorAction SilentlyContinue).Source
    if (-not $NodeExe) {
        Write-Error "node.exe not found on PATH either. Aborting."
        exit 1
    }
}

# Stage 0 = the CLEAN corpus-source baseline (U-QP-CRON-STAGE0-CORPUS, 2026-06-11).
# Rewired from quoting-baseline-bootstrap.mjs, which produced POISONED records
# (machine names as customers, machine_class collapsed to mill, material_iso always
# null). quoting-baseline-from-corpus.mjs reads the canonical
# state/shared/databases/jm-{file-inventory,customers}.jsonl with real per-file
# (customer, machine_class, material) attribution -- same baseline-records.json
# output shape, drop-in. Accepts the same --limit/--summary flags (line ~121).
# The legacy bootstrap script is preserved on disk (never-delete) as a fallback.
$Stage0 = Join-Path $PrismRoot "scripts\quoting-baseline-from-corpus.mjs"
$Stage1 = Join-Path $PrismRoot "scripts\quoting-docustrata-pipeline.mjs"
$Stage2 = Join-Path $PrismRoot "scripts\quoting-train-cycle.mjs"
$Stage3 = Join-Path $PrismRoot "scripts\quoting-train-drift-alert.mjs"
$TsxBin = Join-Path $PrismRoot "mcp-server\node_modules\.bin\tsx.cmd"
$LogDir = Join-Path $PrismRoot "state\shared\quoting\cron-logs"

foreach ($f in @($Stage0, $Stage1, $Stage2, $Stage3)) {
    if (-not (Test-Path $f)) {
        Write-Error "Missing pipeline script: $f"
        exit 1
    }
}

if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
}

# Inline wrapper that runs all 4 stages, captures output, exits with drift-alert exit code.
# Uses && so a failing stage halts the chain.
$WrapperPath = Join-Path $PrismRoot "scripts\run-quoting-pipeline-nightly.ps1"
$WrapperContent = @"
# Auto-generated by install-quoting-pipeline-cron.ps1 (iter26)
# DO NOT hand-edit — regenerate via the installer.
`$ErrorActionPreference = 'Continue'
# U-QP-CRON-CWD-FIX (2026-06-11): pin cwd to the repo root. The stage scripts resolve
# DEFAULT paths cwd-relative (e.g. quoting-baseline-from-corpus.mjs reads
# state/shared/databases/*.jsonl and writes state/shared/quoting/baseline-records.json),
# but a scheduled task's default working directory is %windir%\system32 -- so without this
# the Stage 0 inputs/outputs resolve under System32 and the chain fails at Stage 0.
Set-Location '$PrismRoot'
`$LogFile = '$LogDir\quoting-pipeline-' + (Get-Date -Format 'yyyy-MM-dd_HHmm') + '.log'
# U-QP-CRON-REAL-CORPUS (charlie 2026-06-02 /goal /loop iter2): train the scheduled loop
# on the REAL 47,905-record JM corpus. Was the 69-record synth merge — guard-ADMITTED
# (so the loop wasn't dead) but tiny, leaving the real corpus entirely unused. The synth
# merge stays as --fallback-corpus belt (used only if the real corpus is missing; the
# train-cycle re-validates it through the poison-guard either way, U-QP-BASELINE-FALLBACK).
#
# SAFETY (scrutiny P1, 2026-06-02): Stage2 runs with --no-write. The real corpus is
# synthetic-revenue-DOMINANT (the train-cycle's own `synthetic_revenue_dominant` advisory:
# revenue is a near-fixed markup over modeled cost, NOT real outbound pricing — MAPE ~71%
# is self-consistency, not real-world accuracy). Auto-ACTIVATING a calibration factor from
# that into live quotes (active-calibration.json drives quoting) is unsafe. The scheduled
# loop therefore TRAINS + measures + feeds PSN (--feed-psn) + drift-alerts (Stage3) but
# does NOT activate. Remove --no-write only once a real-OUTBOUND-validated corpus exists
# (the OutboundPriceIndex calibration thread; today match_pct=0 / ext_price median is OCR-noisy).
`$BaselineReal = '$PrismRoot\state\shared\quoting\baseline-records-corpus-with-real.json'
`$BaselineFallback = '$PrismRoot\state\shared\quoting\baseline-records-with-synth.json'

Add-Content `$LogFile "[run-nightly] start `$(Get-Date -Format o)"

& '$NodeExe' '$Stage0' --limit 200 --summary *>> `$LogFile
if (`$LASTEXITCODE -ne 0) { Add-Content `$LogFile "[stage0] FAIL exit=`$LASTEXITCODE"; exit `$LASTEXITCODE }

& '$NodeExe' '$Stage1' --json *>> `$LogFile
if (`$LASTEXITCODE -ne 0) { Add-Content `$LogFile "[stage1] FAIL exit=`$LASTEXITCODE"; exit `$LASTEXITCODE }

if (Test-Path '$TsxBin') {
    & '$TsxBin' '$Stage2' --json --feed-psn --no-write --baseline `$BaselineReal --fallback-corpus `$BaselineFallback *>> `$LogFile
} else {
    & '$NodeExe' '$Stage2' --json --feed-psn --no-write --baseline `$BaselineReal --fallback-corpus `$BaselineFallback *>> `$LogFile
}
if (`$LASTEXITCODE -ne 0) { Add-Content `$LogFile "[stage2] FAIL exit=`$LASTEXITCODE"; exit `$LASTEXITCODE }

& '$NodeExe' '$Stage3' --json *>> `$LogFile
`$alertExit = `$LASTEXITCODE
Add-Content `$LogFile "[run-nightly] end `$(Get-Date -Format o) — drift-alert exit=`$alertExit"
exit `$alertExit
"@

if ($DryRun) {
    Write-Host "=== DRY RUN ==="
    Write-Host "Task name      : $TaskName"
    Write-Host "Trigger hour   : $TriggerHour (daily)"
    Write-Host "Wrapper script : $WrapperPath"
    Write-Host "Log directory  : $LogDir"
    Write-Host ""
    Write-Host "--- Wrapper contents ---"
    Write-Host $WrapperContent
    Write-Host "--- end ---"
    exit 0
}

# Write the wrapper
Set-Content -Path $WrapperPath -Value $WrapperContent -Encoding UTF8
Write-Host "Wrote wrapper: $WrapperPath"

# Build + register the Scheduled Task
$Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$WrapperPath`""
$Trigger = New-ScheduledTaskTrigger -Daily -At ([datetime]::Today.AddHours($TriggerHour))
$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 30)
$Principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType S4U -RunLevel Highest

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Updating existing task: $TaskName"
    Set-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal | Out-Null
} else {
    Write-Host "Registering new task: $TaskName"
    Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Description "PRISM quoting calibration pipeline — runs daily at $($TriggerHour):00 local. iter26." | Out-Null
}

Write-Host ""
Write-Host "Task registered. Verify with:"
Write-Host "  Get-ScheduledTask -TaskName '$TaskName' | Format-List"
Write-Host "  Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host ""
Write-Host "Logs land at: $LogDir"
Write-Host "Last drift-alert state: $PrismRoot\state\shared\quoting\latest-drift-alert.json"

exit 0
