/**
 * PRISM MATERIALS DATABASE - Aluminum 7xxx Series - High Strength
 * File: aluminum_7xxx_051_065.js
 * Materials: N-AL-051 through N-AL-065
 * 
 * ISO Category: N (Non-Ferrous)
 * 
 * Parameters per material: 127
 * Schema version: 3.0.0
 * Generated: 2026-01-24 21:02
 * 
 * AUTO-GENERATED by aluminum_materials_generator.py
 */

const ALUMINUM_7XXX_051_065 = {
  metadata: {
    file: "aluminum_7xxx_051_065.js",
    category: "N_NONFERROUS",
    subcategory: "Aluminum 7xxx Series - High Strength",
    materialCount: 15,
    idRange: { start: "N-AL-051", end: "N-AL-065" },
    schemaVersion: "3.0.0",
    generated: "2026-01-24"
  },

  materials: {
    "N-AL-051": {
    id: "N-AL-051",
    "name": "7075-O Annealed",
    "designation": {
        "aa": "7075",
        "uns": "A97075",
        "din": "3.4365",
        "jis": "A7075",
        "en": "EN AW-7075",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Annealed",
    "temper": "O",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 173,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 4.15e-08,
        "electrical_conductivity_iacs": 48,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 60,
            "rockwell_b": 35,
            "rockwell_c": null,
            "vickers": 63
        },
        "tensile_strength": {
            "min": 216,
            "typical": 230,
            "max": 243
        },
        "yield_strength": {
            "min": 97,
            "typical": 105,
            "max": 112
        },
        "compressive_strength": {
            "min": 97,
            "typical": 105,
            "max": 112
        },
        "elongation": {
            "min": 13,
            "typical": 17,
            "max": 21
        },
        "reduction_of_area": {
            "min": 25,
            "typical": 37,
            "max": 51
        },
        "impact_energy": {
            "joules": 18,
            "temperature": 20
        },
        "fatigue_strength": 69,
        "fracture_toughness": 38
    },
    "kienzle": {
        "kc1_1": 520,
        "mc": 0.26,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.95
    },
    "taylor": {
        "C": 950,
        "n": 0.36,
        "reference_speed": 475,
        "reference_life": 15,
        "speed_range": {
            "min": 205,
            "max": 902
        }
    },
    "johnson_cook": {
        "A": 130,
        "B": 360,
        "n": 0.44,
        "C": 0.02,
        "m": 1.1,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 70,
        "relative_to_1212": 0.7,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.43999999999999995,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 246,
                    "opt": 410,
                    "max": 656
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 492,
                    "opt": 820,
                    "max": 1230
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 205,
                    "opt": 348,
                    "max": 574
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 143,
                    "opt": 246,
                    "max": 410
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "forming_stock",
        "rivet_stock",
        "forging_billet"
    ],
    "heat_treatment": {
        "temper": "O",
        "solution_temp": null,
        "quench": null,
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "Highest strength Al series in annealed condition"
},

    "N-AL-052": {
    id: "N-AL-052",
    "name": "7075-T6 Peak Aged",
    "designation": {
        "aa": "7075",
        "uns": "A97075",
        "din": "3.4365",
        "jis": "A7075",
        "en": "EN AW-7075",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Artificial Age",
    "temper": "T6",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 130,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 6.3e-08,
        "electrical_conductivity_iacs": 36,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 150,
            "rockwell_b": 91,
            "rockwell_c": null,
            "vickers": 157
        },
        "tensile_strength": {
            "min": 537,
            "typical": 572,
            "max": 606
        },
        "yield_strength": {
            "min": 467,
            "typical": 503,
            "max": 538
        },
        "compressive_strength": {
            "min": 467,
            "typical": 503,
            "max": 538
        },
        "elongation": {
            "min": 7,
            "typical": 11,
            "max": 15
        },
        "reduction_of_area": {
            "min": 16,
            "typical": 24,
            "max": 33
        },
        "impact_energy": {
            "joules": 15,
            "temperature": 20
        },
        "fatigue_strength": 171,
        "fracture_toughness": 29
    },
    "kienzle": {
        "kc1_1": 850,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.5
    },
    "taylor": {
        "C": 720,
        "n": 0.32,
        "reference_speed": 360,
        "reference_life": 15,
        "speed_range": {
            "min": 287,
            "max": 1265
        }
    },
    "johnson_cook": {
        "A": 420,
        "B": 510,
        "n": 0.27,
        "C": 0.011,
        "m": 0.85,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 125,
        "relative_to_1212": 1.25,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.575,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 345,
                    "opt": 575,
                    "max": 920
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 690,
                    "opt": 1150,
                    "max": 1725
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 287,
                    "opt": 488,
                    "max": 805
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 201,
                    "opt": 345,
                    "max": 575
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "aircraft_structures",
        "aerospace_fittings",
        "gears",
        "shafts"
    ],
    "heat_treatment": {
        "temper": "T6",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": "standard"
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_susceptible",
        "exfoliation": "moderate"
    },
    "notes": "HIGHEST strength common aluminum. T6 susceptible to SCC"
},

    "N-AL-053": {
    id: "N-AL-053",
    "name": "7075-T651 Stress Relieved",
    "designation": {
        "aa": "7075",
        "uns": "A97075",
        "din": "3.4365",
        "jis": "A7075",
        "en": "EN AW-7075",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Artificial Age",
    "temper": "T651",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 130,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 6.3e-08,
        "electrical_conductivity_iacs": 36,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 150,
            "rockwell_b": 91,
            "rockwell_c": null,
            "vickers": 157
        },
        "tensile_strength": {
            "min": 537,
            "typical": 572,
            "max": 606
        },
        "yield_strength": {
            "min": 467,
            "typical": 503,
            "max": 538
        },
        "compressive_strength": {
            "min": 467,
            "typical": 503,
            "max": 538
        },
        "elongation": {
            "min": 5,
            "typical": 9,
            "max": 13
        },
        "reduction_of_area": {
            "min": 13,
            "typical": 19,
            "max": 27
        },
        "impact_energy": {
            "joules": 14,
            "temperature": 20
        },
        "fatigue_strength": 171,
        "fracture_toughness": 29
    },
    "kienzle": {
        "kc1_1": 850,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.5
    },
    "taylor": {
        "C": 720,
        "n": 0.32,
        "reference_speed": 360,
        "reference_life": 15,
        "speed_range": {
            "min": 295,
            "max": 1298
        }
    },
    "johnson_cook": {
        "A": 420,
        "B": 510,
        "n": 0.27,
        "C": 0.011,
        "m": 0.85,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 130,
        "relative_to_1212": 1.3,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.575,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 354,
                    "opt": 590,
                    "max": 944
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 708,
                    "opt": 1180,
                    "max": 1770
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 295,
                    "opt": 501,
                    "max": 826
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 206,
                    "opt": 354,
                    "max": 590
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "aircraft_plate",
        "precision_machined_parts",
        "mold_plates"
    ],
    "heat_treatment": {
        "temper": "T651",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": "standard"
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_susceptible",
        "exfoliation": "moderate"
    },
    "notes": "Stress-relieved plate. Minimal machining distortion"
},

    "N-AL-054": {
    id: "N-AL-054",
    "name": "7075-T73 SCC Resistant",
    "designation": {
        "aa": "7075",
        "uns": "A97075",
        "din": "3.4365",
        "jis": "A7075",
        "en": "EN AW-7075",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Over-age for SCC",
    "temper": "T73",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 155,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.05e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 135,
            "rockwell_b": 81,
            "rockwell_c": null,
            "vickers": 141
        },
        "tensile_strength": {
            "min": 472,
            "typical": 503,
            "max": 533
        },
        "yield_strength": {
            "min": 403,
            "typical": 434,
            "max": 464
        },
        "compressive_strength": {
            "min": 403,
            "typical": 434,
            "max": 464
        },
        "elongation": {
            "min": 9,
            "typical": 13,
            "max": 17
        },
        "reduction_of_area": {
            "min": 19,
            "typical": 28,
            "max": 39
        },
        "impact_energy": {
            "joules": 16,
            "temperature": 20
        },
        "fatigue_strength": 150,
        "fracture_toughness": 30
    },
    "kienzle": {
        "kc1_1": 780,
        "mc": 0.24,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.575
    },
    "taylor": {
        "C": 760,
        "n": 0.33,
        "reference_speed": 380,
        "reference_life": 15,
        "speed_range": {
            "min": 272,
            "max": 1199
        }
    },
    "johnson_cook": {
        "A": 380,
        "B": 480,
        "n": 0.29,
        "C": 0.012,
        "m": 0.88,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 115,
        "relative_to_1212": 1.15,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.5525,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 327,
                    "opt": 545,
                    "max": 872
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 654,
                    "opt": 1090,
                    "max": 1635
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 272,
                    "opt": 463,
                    "max": 763
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 190,
                    "opt": 327,
                    "max": 545
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "aircraft_fittings",
        "landing_gear_components"
    ],
    "heat_treatment": {
        "temper": "T73",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_resistant",
        "exfoliation": "moderate"
    },
    "notes": "OVERAGED for SCC resistance. 10-15% lower strength than T6"
},

    "N-AL-055": {
    id: "N-AL-055",
    "name": "7075-T76 Exfoliation Resistant",
    "designation": {
        "aa": "7075",
        "uns": "A97075",
        "din": "3.4365",
        "jis": "A7075",
        "en": "EN AW-7075",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Over-age for Exfoliation",
    "temper": "T76",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 142,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.7e-08,
        "electrical_conductivity_iacs": 39,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 140,
            "rockwell_b": 84,
            "rockwell_c": null,
            "vickers": 147
        },
        "tensile_strength": {
            "min": 498,
            "typical": 530,
            "max": 561
        },
        "yield_strength": {
            "min": 423,
            "typical": 455,
            "max": 486
        },
        "compressive_strength": {
            "min": 423,
            "typical": 455,
            "max": 486
        },
        "elongation": {
            "min": 8,
            "typical": 12,
            "max": 16
        },
        "reduction_of_area": {
            "min": 18,
            "typical": 26,
            "max": 36
        },
        "impact_energy": {
            "joules": 16,
            "temperature": 20
        },
        "fatigue_strength": 159,
        "fracture_toughness": 30
    },
    "kienzle": {
        "kc1_1": 810,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.55
    },
    "taylor": {
        "C": 740,
        "n": 0.33,
        "reference_speed": 370,
        "reference_life": 15,
        "speed_range": {
            "min": 280,
            "max": 1232
        }
    },
    "johnson_cook": {
        "A": 400,
        "B": 490,
        "n": 0.28,
        "C": 0.012,
        "m": 0.87,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 120,
        "relative_to_1212": 1.2,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.5599999999999999,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 336,
                    "opt": 560,
                    "max": 896
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 672,
                    "opt": 1120,
                    "max": 1680
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 280,
                    "opt": 476,
                    "max": 784
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 196,
                    "opt": 336,
                    "max": 560
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "aircraft_wing_skins",
        "fuselage_skins",
        "marine_aerospace"
    ],
    "heat_treatment": {
        "temper": "T76",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "highly_resistant"
    },
    "notes": "T76 = exfoliation resistant. Between T6 and T73"
},

    "N-AL-056": {
    id: "N-AL-056",
    "name": "7050-T7451 Aerospace Plate",
    "designation": {
        "aa": "7050",
        "uns": "A97050",
        "din": "3.4144",
        "jis": "A7050",
        "en": "EN AW-7050",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Over-age",
    "temper": "T7451",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.7,
            "typical": 6.2,
            "max": 6.7
        },
        "magnesium": {
            "min": 1.9,
            "typical": 2.25,
            "max": 2.6
        },
        "copper": {
            "min": 2.0,
            "typical": 2.3,
            "max": 2.6
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.12,
            "max": 0.15
        }
    },
    "physical": {
        "density": 2830,
        "melting_point": {
            "solidus": 488,
            "liquidus": 646
        },
        "specific_heat": 894.34,
        "thermal_conductivity": 157,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 4.95e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 145,
            "rockwell_b": 87,
            "rockwell_c": null,
            "vickers": 152
        },
        "tensile_strength": {
            "min": 518,
            "typical": 552,
            "max": 585
        },
        "yield_strength": {
            "min": 455,
            "typical": 490,
            "max": 524
        },
        "compressive_strength": {
            "min": 455,
            "typical": 490,
            "max": 524
        },
        "elongation": {
            "min": 8,
            "typical": 12,
            "max": 16
        },
        "reduction_of_area": {
            "min": 18,
            "typical": 26,
            "max": 36
        },
        "impact_energy": {
            "joules": 16,
            "temperature": 20
        },
        "fatigue_strength": 165,
        "fracture_toughness": 29
    },
    "kienzle": {
        "kc1_1": 830,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.525
    },
    "taylor": {
        "C": 740,
        "n": 0.33,
        "reference_speed": 370,
        "reference_life": 15,
        "speed_range": {
            "min": 280,
            "max": 1232
        }
    },
    "johnson_cook": {
        "A": 410,
        "B": 495,
        "n": 0.28,
        "C": 0.012,
        "m": 0.86,
        "T_melt": 646,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 120,
        "relative_to_1212": 1.2,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.5675,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 336,
                    "opt": 560,
                    "max": 896
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 672,
                    "opt": 1120,
                    "max": 1680
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 280,
                    "opt": 476,
                    "max": 784
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 196,
                    "opt": 336,
                    "max": 560
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "aircraft_wing_structures",
        "fuselage_frames",
        "bulkheads"
    ],
    "heat_treatment": {
        "temper": "T7451",
        "solution_temp": 478,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_resistant",
        "exfoliation": "moderate"
    },
    "notes": "7050 = higher Cu than 7075. F-15, F-18, 747"
},

    "N-AL-057": {
    id: "N-AL-057",
    "name": "7050-T7651 Higher Strength",
    "designation": {
        "aa": "7050",
        "uns": "A97050",
        "din": "3.4144",
        "jis": "A7050",
        "en": "EN AW-7050",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Alternate Age",
    "temper": "T7651",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.7,
            "typical": 6.2,
            "max": 6.7
        },
        "magnesium": {
            "min": 1.9,
            "typical": 2.25,
            "max": 2.6
        },
        "copper": {
            "min": 2.0,
            "typical": 2.3,
            "max": 2.6
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.12,
            "max": 0.15
        }
    },
    "physical": {
        "density": 2830,
        "melting_point": {
            "solidus": 488,
            "liquidus": 646
        },
        "specific_heat": 894.34,
        "thermal_conductivity": 147,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.4500000000000005e-08,
        "electrical_conductivity_iacs": 41,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 150,
            "rockwell_b": 91,
            "rockwell_c": null,
            "vickers": 157
        },
        "tensile_strength": {
            "min": 535,
            "typical": 570,
            "max": 604
        },
        "yield_strength": {
            "min": 474,
            "typical": 510,
            "max": 545
        },
        "compressive_strength": {
            "min": 474,
            "typical": 510,
            "max": 545
        },
        "elongation": {
            "min": 7,
            "typical": 11,
            "max": 15
        },
        "reduction_of_area": {
            "min": 16,
            "typical": 24,
            "max": 33
        },
        "impact_energy": {
            "joules": 15,
            "temperature": 20
        },
        "fatigue_strength": 171,
        "fracture_toughness": 29
    },
    "kienzle": {
        "kc1_1": 850,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.5
    },
    "taylor": {
        "C": 730,
        "n": 0.32,
        "reference_speed": 365,
        "reference_life": 15,
        "speed_range": {
            "min": 287,
            "max": 1265
        }
    },
    "johnson_cook": {
        "A": 430,
        "B": 505,
        "n": 0.27,
        "C": 0.011,
        "m": 0.85,
        "T_melt": 646,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 125,
        "relative_to_1212": 1.25,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.575,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 345,
                    "opt": 575,
                    "max": 920
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 690,
                    "opt": 1150,
                    "max": 1725
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 287,
                    "opt": 488,
                    "max": 805
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 201,
                    "opt": 345,
                    "max": 575
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "aircraft_wing_spars",
        "heavy_section_machining",
        "military_aircraft"
    ],
    "heat_treatment": {
        "temper": "T7651",
        "solution_temp": 478,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "T7651 = higher strength than T7451 with moderate SCC resistance"
},

    "N-AL-058": {
    id: "N-AL-058",
    "name": "7055-T7751 Highest Strength",
    "designation": {
        "aa": "7055",
        "uns": "A97055",
        "din": "3.4055",
        "jis": "A7055",
        "en": "EN AW-7055",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + RRA",
    "temper": "T7751",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 7.6,
            "typical": 8.0,
            "max": 8.4
        },
        "magnesium": {
            "min": 1.8,
            "typical": 2.05,
            "max": 2.3
        },
        "copper": {
            "min": 2.0,
            "typical": 2.3,
            "max": 2.6
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.12,
            "max": 0.25
        }
    },
    "physical": {
        "density": 2850,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.3,
        "thermal_conductivity": 155,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.05e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 165,
            "rockwell_b": 100,
            "rockwell_c": null,
            "vickers": 173
        },
        "tensile_strength": {
            "min": 595,
            "typical": 634,
            "max": 672
        },
        "yield_strength": {
            "min": 551,
            "typical": 593,
            "max": 634
        },
        "compressive_strength": {
            "min": 551,
            "typical": 593,
            "max": 634
        },
        "elongation": {
            "min": 5,
            "typical": 9,
            "max": 13
        },
        "reduction_of_area": {
            "min": 13,
            "typical": 19,
            "max": 27
        },
        "impact_energy": {
            "joules": 14,
            "temperature": 20
        },
        "fatigue_strength": 190,
        "fracture_toughness": 27
    },
    "kienzle": {
        "kc1_1": 920,
        "mc": 0.22,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.425
    },
    "taylor": {
        "C": 680,
        "n": 0.31,
        "reference_speed": 340,
        "reference_life": 15,
        "speed_range": {
            "min": 295,
            "max": 1298
        }
    },
    "johnson_cook": {
        "A": 510,
        "B": 545,
        "n": 0.24,
        "C": 0.01,
        "m": 0.82,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 130,
        "relative_to_1212": 1.3,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.5974999999999999,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 354,
                    "opt": 590,
                    "max": 944
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 708,
                    "opt": 1180,
                    "max": 1770
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 295,
                    "opt": 501,
                    "max": 826
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 206,
                    "opt": 354,
                    "max": 590
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "boeing_777_upper_wing_skins",
        "military_aircraft"
    ],
    "heat_treatment": {
        "temper": "T7751",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "HIGHEST strength production aluminum (634 MPa)"
},

    "N-AL-059": {
    id: "N-AL-059",
    "name": "7475-T7351 High Toughness",
    "designation": {
        "aa": "7475",
        "uns": "A97475",
        "din": "3.4475",
        "jis": "A7475",
        "en": "EN AW-7475",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Over-age",
    "temper": "T7351",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.2,
            "typical": 5.7,
            "max": 6.2
        },
        "magnesium": {
            "min": 1.9,
            "typical": 2.25,
            "max": 2.6
        },
        "copper": {
            "min": 1.2,
            "typical": 1.55,
            "max": 1.9
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.22,
            "max": 0.25
        },
        "iron": {
            "min": 0,
            "typical": 0.06,
            "max": 0.12
        },
        "silicon": {
            "min": 0,
            "typical": 0.05,
            "max": 0.1
        }
    },
    "physical": {
        "density": 2810,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.38,
        "thermal_conductivity": 163,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 4.65e-08,
        "electrical_conductivity_iacs": 45,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 140,
            "rockwell_b": 84,
            "rockwell_c": null,
            "vickers": 147
        },
        "tensile_strength": {
            "min": 472,
            "typical": 503,
            "max": 533
        },
        "yield_strength": {
            "min": 410,
            "typical": 441,
            "max": 471
        },
        "compressive_strength": {
            "min": 410,
            "typical": 441,
            "max": 471
        },
        "elongation": {
            "min": 10,
            "typical": 14,
            "max": 18
        },
        "reduction_of_area": {
            "min": 21,
            "typical": 30,
            "max": 42
        },
        "impact_energy": {
            "joules": 17,
            "temperature": 20
        },
        "fatigue_strength": 150,
        "fracture_toughness": 42
    },
    "kienzle": {
        "kc1_1": 780,
        "mc": 0.24,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.55
    },
    "taylor": {
        "C": 760,
        "n": 0.33,
        "reference_speed": 380,
        "reference_life": 15,
        "speed_range": {
            "min": 265,
            "max": 1166
        }
    },
    "johnson_cook": {
        "A": 390,
        "B": 480,
        "n": 0.3,
        "C": 0.012,
        "m": 0.88,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 110,
        "relative_to_1212": 1.1,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.5599999999999999,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 318,
                    "opt": 530,
                    "max": 848
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 636,
                    "opt": 1060,
                    "max": 1590
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 265,
                    "opt": 450,
                    "max": 742
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 185,
                    "opt": 318,
                    "max": 530
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "fuselage_lower_skins",
        "wing_lower_skins",
        "damage_tolerant_designs"
    ],
    "heat_treatment": {
        "temper": "T7351",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_resistant",
        "exfoliation": "moderate"
    },
    "notes": "HIGHEST TOUGHNESS 7xxx. Low Fe/Si = superior damage tolerance"
},

    "N-AL-060": {
    id: "N-AL-060",
    "name": "7178-T6 High Strength",
    "designation": {
        "aa": "7178",
        "uns": "A97178",
        "din": "3.4178",
        "jis": "A7178",
        "en": "EN AW-7178",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Artificial Age",
    "temper": "T6",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 6.3,
            "typical": 6.8,
            "max": 7.3
        },
        "magnesium": {
            "min": 2.4,
            "typical": 2.75,
            "max": 3.1
        },
        "copper": {
            "min": 1.6,
            "typical": 2.0,
            "max": 2.4
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        }
    },
    "physical": {
        "density": 2830,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.34,
        "thermal_conductivity": 125,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 6.55e-08,
        "electrical_conductivity_iacs": 35,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 160,
            "rockwell_b": 97,
            "rockwell_c": null,
            "vickers": 168
        },
        "tensile_strength": {
            "min": 570,
            "typical": 607,
            "max": 643
        },
        "yield_strength": {
            "min": 500,
            "typical": 538,
            "max": 575
        },
        "compressive_strength": {
            "min": 500,
            "typical": 538,
            "max": 575
        },
        "elongation": {
            "min": 4,
            "typical": 8,
            "max": 12
        },
        "reduction_of_area": {
            "min": 12,
            "typical": 17,
            "max": 24
        },
        "impact_energy": {
            "joules": 14,
            "temperature": 20
        },
        "fatigue_strength": 182,
        "fracture_toughness": 28
    },
    "kienzle": {
        "kc1_1": 900,
        "mc": 0.22,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.45
    },
    "taylor": {
        "C": 680,
        "n": 0.31,
        "reference_speed": 340,
        "reference_life": 15,
        "speed_range": {
            "min": 295,
            "max": 1298
        }
    },
    "johnson_cook": {
        "A": 480,
        "B": 530,
        "n": 0.25,
        "C": 0.01,
        "m": 0.83,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 130,
        "relative_to_1212": 1.3,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.59,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 354,
                    "opt": 590,
                    "max": 944
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 708,
                    "opt": 1180,
                    "max": 1770
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 295,
                    "opt": 501,
                    "max": 826
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 206,
                    "opt": 354,
                    "max": 590
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "highly_stressed_aircraft_parts",
        "wing_compression_members"
    ],
    "heat_treatment": {
        "temper": "T6",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": "standard"
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_susceptible",
        "exfoliation": "moderate"
    },
    "notes": "Higher Zn/Mg than 7075 = higher strength but lower toughness"
},

    "N-AL-061": {
    id: "N-AL-061",
    "name": "7039-T64 Military/Marine",
    "designation": {
        "aa": "7039",
        "uns": "A97039",
        "din": "3.4039",
        "jis": "A7039",
        "en": "EN AW-7039",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Artificial Age",
    "temper": "T64",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 3.5,
            "typical": 4.0,
            "max": 4.5
        },
        "magnesium": {
            "min": 2.3,
            "typical": 2.8,
            "max": 3.3
        },
        "manganese": {
            "min": 0.1,
            "typical": 0.25,
            "max": 0.4
        },
        "chromium": {
            "min": 0.15,
            "typical": 0.2,
            "max": 0.25
        },
        "copper": {
            "min": 0,
            "typical": 0.05,
            "max": 0.1
        }
    },
    "physical": {
        "density": 2740,
        "melting_point": {
            "solidus": 538,
            "liquidus": 696
        },
        "specific_heat": 894.52,
        "thermal_conductivity": 145,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.55e-08,
        "electrical_conductivity_iacs": 40,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 105,
            "rockwell_b": 63,
            "rockwell_c": null,
            "vickers": 110
        },
        "tensile_strength": {
            "min": 390,
            "typical": 415,
            "max": 439
        },
        "yield_strength": {
            "min": 316,
            "typical": 340,
            "max": 363
        },
        "compressive_strength": {
            "min": 316,
            "typical": 340,
            "max": 363
        },
        "elongation": {
            "min": 10,
            "typical": 14,
            "max": 18
        },
        "reduction_of_area": {
            "min": 21,
            "typical": 30,
            "max": 42
        },
        "impact_energy": {
            "joules": 17,
            "temperature": 20
        },
        "fatigue_strength": 124,
        "fracture_toughness": 33
    },
    "kienzle": {
        "kc1_1": 700,
        "mc": 0.24,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.725
    },
    "taylor": {
        "C": 800,
        "n": 0.34,
        "reference_speed": 400,
        "reference_life": 15,
        "speed_range": {
            "min": 242,
            "max": 1067
        }
    },
    "johnson_cook": {
        "A": 300,
        "B": 440,
        "n": 0.32,
        "C": 0.014,
        "m": 0.92,
        "T_melt": 696,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 95,
        "relative_to_1212": 0.95,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.5075,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 291,
                    "opt": 485,
                    "max": 776
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 582,
                    "opt": 970,
                    "max": 1455
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 242,
                    "opt": 412,
                    "max": 679
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 169,
                    "opt": 291,
                    "max": 485
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "military_vehicles",
        "pontoon_bridges",
        "marine_structures"
    ],
    "heat_treatment": {
        "temper": "T64",
        "solution_temp": 528,
        "quench": "water",
        "artificial_aging": "standard"
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "WELDABLE 7xxx! No Cu = good weldability. M113 APC armor"
},

    "N-AL-062": {
    id: "N-AL-062",
    "name": "7020-T6 Weldable Structural",
    "designation": {
        "aa": "7020",
        "uns": "A97020",
        "din": "3.4335",
        "jis": "A7020",
        "en": "EN AW-7020",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Artificial Age",
    "temper": "T6",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 4.0,
            "typical": 4.5,
            "max": 5.0
        },
        "magnesium": {
            "min": 1.0,
            "typical": 1.2,
            "max": 1.4
        },
        "manganese": {
            "min": 0.05,
            "typical": 0.28,
            "max": 0.5
        },
        "chromium": {
            "min": 0.1,
            "typical": 0.23,
            "max": 0.35
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.14,
            "max": 0.2
        },
        "copper": {
            "min": 0,
            "typical": 0.1,
            "max": 0.2
        }
    },
    "physical": {
        "density": 2780,
        "melting_point": {
            "solidus": 532,
            "liquidus": 690
        },
        "specific_heat": 894.44,
        "thermal_conductivity": 155,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.05e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71000,
        "shear_modulus": 26691
    },
    "mechanical": {
        "hardness": {
            "brinell": 115,
            "rockwell_b": 69,
            "rockwell_c": null,
            "vickers": 120
        },
        "tensile_strength": {
            "min": 361,
            "typical": 385,
            "max": 408
        },
        "yield_strength": {
            "min": 302,
            "typical": 325,
            "max": 347
        },
        "compressive_strength": {
            "min": 302,
            "typical": 325,
            "max": 347
        },
        "elongation": {
            "min": 10,
            "typical": 14,
            "max": 18
        },
        "reduction_of_area": {
            "min": 21,
            "typical": 30,
            "max": 42
        },
        "impact_energy": {
            "joules": 17,
            "temperature": 20
        },
        "fatigue_strength": 115,
        "fracture_toughness": 32
    },
    "kienzle": {
        "kc1_1": 700,
        "mc": 0.24,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.675
    },
    "taylor": {
        "C": 820,
        "n": 0.35,
        "reference_speed": 410,
        "reference_life": 15,
        "speed_range": {
            "min": 250,
            "max": 1100
        }
    },
    "johnson_cook": {
        "A": 290,
        "B": 420,
        "n": 0.33,
        "C": 0.014,
        "m": 0.92,
        "T_melt": 690,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 100,
        "relative_to_1212": 1.0,
        "chip_form": "short_curled",
        "surface_finish_achievable": 0.6,
        "cutting_force_factor": 0.5225,
        "built_up_edge_tendency": "moderate",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 300,
                    "opt": 500,
                    "max": 800
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 600,
                    "opt": 1000,
                    "max": 1500
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 250,
                    "opt": 425,
                    "max": 700
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 175,
                    "opt": 300,
                    "max": 500
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "neutral",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.04,
        "surface_roughness_typical": {
            "Ra": 0.7,
            "Rz": 4.0
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "minimal"
    },
    "applications": [
        "welded_structures",
        "railway_vehicles",
        "truck_bodies",
        "trailers"
    ],
    "heat_treatment": {
        "temper": "T6",
        "solution_temp": 522,
        "quench": "water",
        "artificial_aging": "standard"
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "Natural aging after welding restores ~80% weld zone strength"
},

    "N-AL-063": {
    id: "N-AL-063",
    "name": "7085-T7651 Ultra-Thick Plate",
    "designation": {
        "aa": "7085",
        "uns": "A97085",
        "din": "3.4085",
        "jis": "A7085",
        "en": "EN AW-7085",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Over-age",
    "temper": "T7651",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 7.0,
            "typical": 7.5,
            "max": 8.0
        },
        "magnesium": {
            "min": 1.2,
            "typical": 1.5,
            "max": 1.8
        },
        "copper": {
            "min": 1.3,
            "typical": 1.65,
            "max": 2.0
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.12,
            "max": 0.15
        },
        "iron": {
            "min": 0,
            "typical": 0.04,
            "max": 0.08
        },
        "silicon": {
            "min": 0,
            "typical": 0.03,
            "max": 0.06
        }
    },
    "physical": {
        "density": 2850,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.3,
        "thermal_conductivity": 157,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 4.95e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 145,
            "rockwell_b": 87,
            "rockwell_c": null,
            "vickers": 152
        },
        "tensile_strength": {
            "min": 517,
            "typical": 550,
            "max": 583
        },
        "yield_strength": {
            "min": 461,
            "typical": 496,
            "max": 530
        },
        "compressive_strength": {
            "min": 461,
            "typical": 496,
            "max": 530
        },
        "elongation": {
            "min": 7,
            "typical": 11,
            "max": 15
        },
        "reduction_of_area": {
            "min": 16,
            "typical": 24,
            "max": 33
        },
        "impact_energy": {
            "joules": 15,
            "temperature": 20
        },
        "fatigue_strength": 165,
        "fracture_toughness": 35
    },
    "kienzle": {
        "kc1_1": 820,
        "mc": 0.23,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.525
    },
    "taylor": {
        "C": 740,
        "n": 0.33,
        "reference_speed": 370,
        "reference_life": 15,
        "speed_range": {
            "min": 277,
            "max": 1218
        }
    },
    "johnson_cook": {
        "A": 425,
        "B": 495,
        "n": 0.27,
        "C": 0.011,
        "m": 0.85,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 118,
        "relative_to_1212": 1.18,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.5675,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 332,
                    "opt": 554,
                    "max": 886
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 664,
                    "opt": 1108,
                    "max": 1662
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 277,
                    "opt": 470,
                    "max": 775
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 193,
                    "opt": 332,
                    "max": 554
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "wing_box_ribs",
        "bulkheads",
        "A380_wing_components"
    ],
    "heat_treatment": {
        "temper": "T7651",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_resistant",
        "exfoliation": "moderate"
    },
    "notes": "Ultra-low Fe/Si for thick section properties. Up to 300mm thick"
},

    "N-AL-064": {
    id: "N-AL-064",
    "name": "7150-T7751 High Strength/Toughness",
    "designation": {
        "aa": "7150",
        "uns": "A97150",
        "din": "3.4150",
        "jis": "A7150",
        "en": "EN AW-7150",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + RRA",
    "temper": "T7751",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.9,
            "typical": 6.4,
            "max": 6.9
        },
        "magnesium": {
            "min": 2.0,
            "typical": 2.35,
            "max": 2.7
        },
        "copper": {
            "min": 1.9,
            "typical": 2.2,
            "max": 2.5
        },
        "zirconium": {
            "min": 0.08,
            "typical": 0.12,
            "max": 0.15
        }
    },
    "physical": {
        "density": 2840,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.32,
        "thermal_conductivity": 155,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 5.05e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 158,
            "rockwell_b": 95,
            "rockwell_c": null,
            "vickers": 165
        },
        "tensile_strength": {
            "min": 570,
            "typical": 607,
            "max": 643
        },
        "yield_strength": {
            "min": 518,
            "typical": 558,
            "max": 597
        },
        "compressive_strength": {
            "min": 518,
            "typical": 558,
            "max": 597
        },
        "elongation": {
            "min": 6,
            "typical": 10,
            "max": 14
        },
        "reduction_of_area": {
            "min": 15,
            "typical": 22,
            "max": 30
        },
        "impact_energy": {
            "joules": 15,
            "temperature": 20
        },
        "fatigue_strength": 182,
        "fracture_toughness": 30
    },
    "kienzle": {
        "kc1_1": 880,
        "mc": 0.22,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.46
    },
    "taylor": {
        "C": 700,
        "n": 0.31,
        "reference_speed": 350,
        "reference_life": 15,
        "speed_range": {
            "min": 292,
            "max": 1284
        }
    },
    "johnson_cook": {
        "A": 470,
        "B": 525,
        "n": 0.25,
        "C": 0.01,
        "m": 0.83,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 128,
        "relative_to_1212": 1.28,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.587,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 350,
                    "opt": 584,
                    "max": 934
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 700,
                    "opt": 1168,
                    "max": 1752
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 292,
                    "opt": 496,
                    "max": 817
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 204,
                    "opt": 350,
                    "max": 584
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "wing_spar_caps",
        "fuselage_stringers",
        "F-22_components"
    ],
    "heat_treatment": {
        "temper": "T7751",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "resistant",
        "exfoliation": "moderate"
    },
    "notes": "Zr instead of Cr. Better thick-section properties than 7050"
},

    "N-AL-065": {
    id: "N-AL-065",
    "name": "7175-T7351 High Purity Forging",
    "designation": {
        "aa": "7175",
        "uns": "A97175",
        "din": "3.4175",
        "jis": "A7175",
        "en": "EN AW-7175",
        "iso": "AlZn"
    },
    "iso_group": "N",
    "material_class": "Aluminum - 7xxx Series",
    "condition": "Solution + Stretch + Over-age",
    "temper": "T7351",
    "composition": {
        "aluminum": {
            "min": 85.0,
            "max": 98.0,
            "typical": 91.0
        },
        "zinc": {
            "min": 5.1,
            "typical": 5.6,
            "max": 6.1
        },
        "magnesium": {
            "min": 2.1,
            "typical": 2.5,
            "max": 2.9
        },
        "copper": {
            "min": 1.2,
            "typical": 1.6,
            "max": 2.0
        },
        "chromium": {
            "min": 0.18,
            "typical": 0.23,
            "max": 0.28
        },
        "iron": {
            "min": 0,
            "typical": 0.1,
            "max": 0.2
        },
        "silicon": {
            "min": 0,
            "typical": 0.075,
            "max": 0.15
        }
    },
    "physical": {
        "density": 2800,
        "melting_point": {
            "solidus": 477,
            "liquidus": 635
        },
        "specific_heat": 894.4,
        "thermal_conductivity": 157,
        "thermal_expansion": 2.34e-05,
        "electrical_resistivity": 4.95e-08,
        "electrical_conductivity_iacs": 43,
        "magnetic_permeability": 1.0,
        "poissons_ratio": 0.33,
        "elastic_modulus": 71700,
        "shear_modulus": 26954
    },
    "mechanical": {
        "hardness": {
            "brinell": 142,
            "rockwell_b": 86,
            "rockwell_c": null,
            "vickers": 149
        },
        "tensile_strength": {
            "min": 492,
            "typical": 524,
            "max": 555
        },
        "yield_strength": {
            "min": 429,
            "typical": 462,
            "max": 494
        },
        "compressive_strength": {
            "min": 429,
            "typical": 462,
            "max": 494
        },
        "elongation": {
            "min": 9,
            "typical": 13,
            "max": 17
        },
        "reduction_of_area": {
            "min": 19,
            "typical": 28,
            "max": 39
        },
        "impact_energy": {
            "joules": 16,
            "temperature": 20
        },
        "fatigue_strength": 157,
        "fracture_toughness": 38
    },
    "kienzle": {
        "kc1_1": 800,
        "mc": 0.24,
        "kc_adjust_rake": -3.5,
        "kc_adjust_speed": -0.08,
        "chip_compression": 2.54
    },
    "taylor": {
        "C": 750,
        "n": 0.33,
        "reference_speed": 375,
        "reference_life": 15,
        "speed_range": {
            "min": 268,
            "max": 1179
        }
    },
    "johnson_cook": {
        "A": 400,
        "B": 490,
        "n": 0.29,
        "C": 0.012,
        "m": 0.87,
        "T_melt": 635,
        "T_ref": 20,
        "epsilon_ref": 1.0
    },
    "machinability": {
        "aisi_rating": 112,
        "relative_to_1212": 1.12,
        "chip_form": "short_segmented",
        "surface_finish_achievable": 0.4,
        "cutting_force_factor": 0.563,
        "built_up_edge_tendency": "very_low",
        "tool_wear_pattern": "even_flank"
    },
    "recommended_cutting": {
        "turning": {
            "carbide_coated": {
                "speed": {
                    "min": 321,
                    "opt": 536,
                    "max": 857
                },
                "feed": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.46
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 7.5
                }
            },
            "pcd": {
                "speed": {
                    "min": 643,
                    "opt": 1072,
                    "max": 1608
                },
                "feed": {
                    "min": 0.08,
                    "opt": 0.2,
                    "max": 0.38
                },
                "doc": {
                    "min": 0.4,
                    "opt": 2.2,
                    "max": 6.0
                }
            }
        },
        "milling": {
            "carbide_coated": {
                "speed": {
                    "min": 268,
                    "opt": 455,
                    "max": 750
                },
                "feed_per_tooth": {
                    "min": 0.08,
                    "opt": 0.19,
                    "max": 0.36
                },
                "doc": {
                    "min": 0.6,
                    "opt": 2.8,
                    "max": 6.0
                },
                "woc_factor": 0.68
            }
        },
        "drilling": {
            "carbide": {
                "speed": {
                    "min": 187,
                    "opt": 321,
                    "max": 536
                },
                "feed_per_rev": {
                    "min": 0.1,
                    "opt": 0.24,
                    "max": 0.44
                }
            }
        }
    },
    "surface_integrity": {
        "residual_stress_tendency": "compressive",
        "white_layer_risk": "none",
        "work_hardening_depth": 0.02,
        "surface_roughness_typical": {
            "Ra": 0.4,
            "Rz": 2.5
        }
    },
    "coolant": {
        "requirement": "recommended",
        "recommended_type": "soluble_oil",
        "mql_suitable": true,
        "cryogenic_benefit": "slight"
    },
    "applications": [
        "aircraft_forgings",
        "landing_gear",
        "structural_forgings"
    ],
    "heat_treatment": {
        "temper": "T7351",
        "solution_temp": 467,
        "quench": "water",
        "artificial_aging": null
    },
    "corrosion_resistance": {
        "general": "good",
        "stress_corrosion": "highly_resistant",
        "exfoliation": "moderate"
    },
    "notes": "HIGH PURITY 7075 for forgings. Lower Fe/Si = better toughness"
}
  }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = ALUMINUM_7XXX_051_065;
}
