const PRISM_LAYER3_ENHANCED = {
    svd: PRISM_SVD_ENGINE,
    graph: PRISM_GRAPH_ALGORITHMS,
    collision: PRISM_COLLISION_ALGORITHMS,
    curves: PRISM_CURVE_SURFACE,
    constrainedOpt: PRISM_CONSTRAINED_OPTIMIZATION
}