const PRISM_POST_PROCESSOR_GENERATOR = {
  version: '1.0.0',

  // COMPLETE MACHINE DATABASE WITH POST PROCESSOR SPECS

  machines: {
    // HAAS VF2 PRE-NGC
    'haas_vf2_pre_ngc': {
      id: 'haas_vf2_pre_ngc',
      name: 'HAAS VF2 Pre-NGC',
      manufacturer: 'HAAS Automation',
      control: 'HAAS Classic (Pre-NGC)',
      type: 'mill',
      axes: 3,
      travels: { x: 762, y: 406, z: 508 }, // mm
      spindle: { maxRpm: 7500, power: 14.9, taper: 'CAT40' },
      toolCapacity: 20,
      rapidRate: { x: 25400, y: 25400, z: 25400 }, // mm/min
      features: ['canned_cycles', 'tool_preload', 'probing'],
      coolant: ['flood', 'mist', 'tsc'],

      // Post processor specifics
      post: {
        extension: 'nc',
        dialect: 'haas_classic',
        programFormat: 'O%05d',
        blockNumbering: true,
        blockIncrement: 10,

        // Formatting
        formats: {
          x: { decimals: 4, prefix: 'X' },
          y: { decimals: 4, prefix: 'Y' },
          z: { decimals: 4, prefix: 'Z' },
          feed: { decimals: 1, prefix: 'F' },
          speed: { decimals: 0, prefix: 'S' }
        },
        // G-codes
        gCodes: {
          rapid: 'G0', linear: 'G1', cwArc: 'G2', ccwArc: 'G3',
          dwell: 'G4', exactStop: 'G9',
          xyPlane: 'G17', xzPlane: 'G18', yzPlane: 'G19',
          inch: 'G20', metric: 'G21',
          home: 'G28', homeSecondary: 'G30',
          toolLengthPlus: 'G43', toolLengthCancel: 'G49',
          cutterCompLeft: 'G41', cutterCompRight: 'G42', cutterCompCancel: 'G40',
          cycleCancel: 'G80',
          drill: 'G81', spotDrill: 'G82', peckDrill: 'G83', tap: 'G84',
          bore: 'G85', bore2: 'G86', chipBreak: 'G73',
          absolute: 'G90', incremental: 'G91',
          feedPerMin: 'G94', feedPerRev: 'G95',
          cycleRetract: 'G98', cycleInitial: 'G99',
          workOffset: ['G54', 'G55', 'G56', 'G57', 'G58', 'G59'],
          extendedOffset: 'G154 P%d',
          safeRetract: 'G53 Z0'
        },
        // M-codes
        mCodes: {
          programStop: 'M0', optionalStop: 'M1', programEnd: 'M2',
          spindleCW: 'M3', spindleCCW: 'M4', spindleStop: 'M5',
          toolChange: 'M6',
          coolantMist: 'M7', coolantFlood: 'M8', coolantOff: 'M9',
          endReset: 'M30'
        },
        // Header template
        header: [
          '%',
          'O{programNumber} ({programName})',
          '({date})',
          '(MACHINE: HAAS VF2 PRE-NGC)',
          '(GENERATED BY PRISM)',
          '',
          '(SAFETY BLOCK)',
          'G17 G40 G49 G80',
          'G{units}',
          'G90'
        ],

        // Footer template
        footer: [
          '',
          '(END PROGRAM)',
          'M5',
          'M9',
          'G28 G91 Z0',
          'G90',
          'G28 X0 Y0',
          'M30',
          '%'
        ],

        // Tool change template
        toolChange: [
          '',
          '(TOOL {toolNumber} - {toolComment})',
          'G28 G91 Z0',
          'G90',
          'T{toolNumber} M6',
          '{nextTool}',
          'G43 H{toolNumber}',
          'S{speed} M{spindleDir}',
          '{coolant}'
        ]
      }
    },
    // HURCO VM30i
    'hurco_vm30i': {
      id: 'hurco_vm30i',
      name: 'HURCO VM30i',
      manufacturer: 'HURCO',
      control: 'WinMax',
      type: 'mill',
      axes: 3,
      travels: { x: 762, y: 508, z: 610 },
      spindle: { maxRpm: 12000, power: 11.2, taper: 'BT40' },
      toolCapacity: 24,
      rapidRate: { x: 35000, y: 35000, z: 30000 },
      features: ['conversational', 'ultimotion', 'rigid_tapping', 'probing'],
      coolant: ['flood', 'mist', 'tsc'],

      post: {
        extension: 'nc',
        dialect: 'hurco_winmax',
        programFormat: 'O%d',
        blockNumbering: true,
        blockIncrement: 10,

        formats: {
          x: { decimals: 4, prefix: 'X' },
          y: { decimals: 4, prefix: 'Y' },
          z: { decimals: 4, prefix: 'Z' },
          feed: { decimals: 1, prefix: 'F' },
          speed: { decimals: 0, prefix: 'S' }
        },
        gCodes: {
          rapid: 'G0', linear: 'G1', cwArc: 'G2', ccwArc: 'G3',
          dwell: 'G4',
          xyPlane: 'G17', xzPlane: 'G18', yzPlane: 'G19',
          inch: 'G20', metric: 'G21',
          home: 'G28',
          toolLengthPlus: 'G43', toolLengthCancel: 'G49',
          cutterCompLeft: 'G41', cutterCompRight: 'G42', cutterCompCancel: 'G40',
          cycleCancel: 'G80',
          drill: 'G81', spotDrill: 'G82', peckDrill: 'G83',
          rigidTap: 'G84.2', rigidTapLeft: 'G74.2',
          tap: 'G84', tapLeft: 'G74',
          bore: 'G85', bore2: 'G86',
          absolute: 'G90', incremental: 'G91',
          feedPerMin: 'G94', feedPerRev: 'G95',
          workOffset: ['G54', 'G55', 'G56', 'G57', 'G58', 'G59'],
          extendedOffset: 'G154 P%d',
          safeRetract: 'G53 Z0'
        },
        mCodes: {
          programStop: 'M0', optionalStop: 'M1', programEnd: 'M2',
          spindleCW: 'M3', spindleCCW: 'M4', spindleStop: 'M5',
          toolChange: 'M6',
          coolantMist: 'M7', coolantFlood: 'M8', coolantOff: 'M9',
          endReset: 'M30'
        },
        header: [
          '%',
          'O{programNumber} ({programName})',
          '(HURCO VM30i - WINMAX CONTROL)',
          '(GENERATED BY PRISM)',
          '({date})',
          '',
          'G17 G40 G49 G80',
          'G{units}',
          'G90'
        ],

        footer: [
          '',
          'M5',
          'M9',
          'G53 Z0',
          'G53 X0 Y0',
          'M30',
          '%'
        ],

        toolChange: [
          '',
          '(TOOL {toolNumber} - {toolComment})',
          'G53 Z0',
          'T{toolNumber} M6',
          'G43 H{toolNumber}',
          'S{speed} M{spindleDir}',
          '{coolant}'
        ],

        // HURCO-specific features
        features: {
          useRigidTapping: true,
          rigidTapCodes: { cw: 'G84.2', ccw: 'G74.2' }
        }
      }
    },
    // OKUMA MULTUS B250II-W
    'okuma_multus_b250ii_w': {
      id: 'okuma_multus_b250ii_w',
      name: 'OKUMA MULTUS B250II-W',
      manufacturer: 'OKUMA',
      control: 'OSP-P300SA',
      type: 'mill_turn',
      axes: 9, // X, Y, Z, C, B + sub-spindle
      travels: { x: 580, y: 150, z: 900, b: 225, c: 360 },
      spindle: {
        main: { maxRpm: 4000, power: 22 },
        sub: { maxRpm: 4000, power: 15 },
        milling: { maxRpm: 12000, power: 22 }
      },
      turret: 12,
      features: ['mill_turn', 'y_axis', 'b_axis', 'sub_spindle', 'css', 'polar_interpolation'],
      coolant: ['flood', 'tsc'],

      post: {
        extension: 'min', // OKUMA uses .min
        dialect: 'okuma_osp',
        programFormat: 'O%04d',
        blockNumbering: true,
        blockIncrement: 1,

        formats: {
          x: { decimals: 3, prefix: 'X' }, // Diameter programming
          y: { decimals: 3, prefix: 'Y' },
          z: { decimals: 3, prefix: 'Z' },
          c: { decimals: 3, prefix: 'C' },
          b: { decimals: 3, prefix: 'B' },
          feed: { decimals: 3, prefix: 'F' },
          speed: { decimals: 0, prefix: 'S' }
        },
        gCodes: {
          rapid: 'G0', linear: 'G1', cwArc: 'G2', ccwArc: 'G3',
          dwell: 'G4',
          xyPlane: 'G17', xzPlane: 'G18', yzPlane: 'G19',
          inch: 'G20', metric: 'G21',
          home: 'G28',
          yAxisOn: 'G15 H1', yAxisOff: 'G13',
          polarOn: 'G112', polarOff: 'G112.1',
          css: 'G96', rpm: 'G97',
          cssLimit: 'G92',
          toolLengthPlus: 'G43', toolLengthCancel: 'G49',
          cutterCompCancel: 'G40',
          cycleCancel: 'G80',
          absolute: 'G90', incremental: 'G91',
          feedPerMin: 'G94', feedPerRev: 'G95',
          selectMainSpindle: 'G14 H1',
          selectSubSpindle: 'G14 H2',
          workOffset: 'G14 H%d'
        },
        mCodes: {
          programStop: 'M0', optionalStop: 'M1', programEnd: 'M2',
          spindleCW: 'M3', spindleCCW: 'M4', spindleStop: 'M5',
          millingSpindleCW: 'M203', millingSpindleCCW: 'M204', millingSpindleStop: 'M205',
          coolantFlood: 'M8', coolantOff: 'M9',
          tsc: 'M51',
          chipConveyorOn: 'M30', chipConveyorOff: 'M31',
          endReset: 'M2'
        },
        header: [
          '$',
          '(OKUMA MULTUS B250II-W)',
          '(OSP-P300SA CONTROL)',
          '(GENERATED BY PRISM)',
          '({date})',
          '',
          'G40 G80',
          'G{units}',
          'G90'
        ],

        footer: [
          '',
          'M5',
          'M205',
          'M9',
          'G0 X{homeX}',
          'G0 Z{homeZ}',
          'M2',
          '$'
        ],

        toolChange: [
          '',
          '(TOOL {toolNumber} - {toolComment})',
          'G0 X{safeX}',
          'G0 Z{safeZ}',
          'T{toolNumber}',
          '{spindleSetup}',
          '{coolant}'
        ],

        // Multi-tasking features
        features: {
          diameterProgramming: true,
          yAxisMode: 'G15 H1',
          polarInterpolation: 'G112',
          mainSpindle: 'G14 H1',
          subSpindle: 'G14 H2'
        }
      }
    },
    // OKUMA GENOS M460V-5AX
    'okuma_genos_m460v_5ax': {
      id: 'okuma_genos_m460v_5ax',
      name: 'OKUMA GENOS M460V-5AX',
      manufacturer: 'OKUMA',
      control: 'OSP-P300MA',
      type: 'mill',
      axes: 5, // X, Y, Z, A, C (trunnion)
      travels: { x: 762, y: 460, z: 460, a: [-120, 30], c: 360 },
      spindle: { maxRpm: 15000, power: 22, taper: 'CAT40' },
      toolCapacity: 32,
      rapidRate: { x: 40000, y: 40000, z: 32000 },
      features: ['5_axis', 'tcp', 'tcpc', 'tilted_workplane', 'collision_avoidance'],
      coolant: ['flood', 'tsc'],

      post: {
        extension: 'min',
        dialect: 'okuma_osp_5ax',
        programFormat: 'O%04d',
        blockNumbering: true,
        blockIncrement: 1,

        formats: {
          x: { decimals: 4, prefix: 'X' },
          y: { decimals: 4, prefix: 'Y' },
          z: { decimals: 4, prefix: 'Z' },
          a: { decimals: 3, prefix: 'A' },
          c: { decimals: 3, prefix: 'C' },
          feed: { decimals: 1, prefix: 'F' },
          speed: { decimals: 0, prefix: 'S' }
        },
        gCodes: {
          rapid: 'G0', linear: 'G1', cwArc: 'G2', ccwArc: 'G3',
          dwell: 'G4',
          xyPlane: 'G17', xzPlane: 'G18', yzPlane: 'G19',
          inch: 'G20', metric: 'G21',
          home: 'G28',
          toolLengthPlus: 'G43', toolLengthCancel: 'G49',
          tcp1: 'G43.4', tcp2: 'G43.5', tcpOkuma: 'G169',
          tiltedWorkplane: 'G68.2', tiltedWorkplaneCancel: 'G69',
          cutterCompCancel: 'G40',
          cycleCancel: 'G80',
          drill: 'G81', spotDrill: 'G82', peckDrill: 'G83', tap: 'G84',
          absolute: 'G90', incremental: 'G91',
          feedPerMin: 'G94',
          cycleRetract: 'G98',
          workOffset: ['G54', 'G55', 'G56', 'G57', 'G58', 'G59'],
          extendedOffset: 'G15 H%d',
          safeRetract: 'G53 Z0'
        },
        mCodes: {
          programStop: 'M0', optionalStop: 'M1', programEnd: 'M2',
          spindleCW: 'M3', spindleCCW: 'M4', spindleStop: 'M5',
          toolChange: 'M6',
          coolantFlood: 'M8', coolantOff: 'M9',
          tsc: 'M51',
          endReset: 'M2'
        },
        header: [
          '$',
          '(OKUMA GENOS M460V-5AX)',
          '(OSP-P300MA 5-AXIS CONTROL)',
          '(GENERATED BY PRISM)',
          '({date})',
          '',
          'G17 G40 G49 G80',
          'G69',
          'G{units}',
          'G90'
        ],

        footer: [
          '',
          'G69',
          'G49',
          'M5',
          'M9',
          'G53 Z0',
          'G53 A0 C0',
          'G53 X0 Y0',
          'M2',
          '$'
        ],

        toolChange: [
          '',
          '(TOOL {toolNumber} - {toolComment})',
          'G69',
          'G49',
          'G53 Z0',
          'T{toolNumber} M6',
          'S{speed} M{spindleDir}',
          '{coolant}'
        ],

        // 5-axis features
        features: {
          tcpModes: ['G43.4', 'G43.5', 'G169'],
          defaultTCP: 'G43.4',
          tiltedWorkplane: true,
          tiltedWorkplaneCode: 'G68.2',
          axisLimits: { aMin: -120, aMax: 30, cMin: -360, cMax: 360 }
        }
      }
    },
    // ROKU-ROKU HC-658II (Fanuc 31i-Model B5)
    'roku_roku_hc658ii_fanuc_31i_b5': {
      id: 'roku_roku_hc658ii_fanuc_31i_b5',
      name: 'ROKU-ROKU HC-658II',
      manufacturer: 'ROKU-ROKU (Shibaura)',
      control: 'FANUC 31i-Model B5',
      type: 'mill',
      axes: 3,
      travels: { x: 650, y: 580, z: 450 },
      spindle: { maxRpm: 30000, power: 22, taper: 'HSK-E40' },
      toolCapacity: 30,
      rapidRate: { x: 60000, y: 60000, z: 50000 },
      features: ['high_speed', 'hsm', 'nano_smoothing', 'aicc', 'look_ahead'],
      coolant: ['flood', 'tsc_high_pressure'],

      post: {
        extension: 'nc',
        dialect: 'fanuc_31i_hsm',
        programFormat: 'O%04d',
        blockNumbering: false, // HSM optimization - no block numbers
        blockIncrement: 10,

        formats: {
          x: { decimals: 4, prefix: 'X' }, // 0.0001mm precision for HSM
          y: { decimals: 4, prefix: 'Y' },
          z: { decimals: 4, prefix: 'Z' },
          i: { decimals: 4, prefix: 'I' },
          j: { decimals: 4, prefix: 'J' },
          k: { decimals: 4, prefix: 'K' },
          feed: { decimals: 1, prefix: 'F' },
          speed: { decimals: 0, prefix: 'S' }
        },
        gCodes: {
          rapid: 'G0', linear: 'G1', cwArc: 'G2', ccwArc: 'G3',
          dwell: 'G4',
          xyPlane: 'G17', xzPlane: 'G18', yzPlane: 'G19',
          inch: 'G20', metric: 'G21',
          home: 'G28', home2: 'G30',
          toolLengthPlus: 'G43', toolLengthCancel: 'G49',
          cutterCompCancel: 'G40',
          cycleCancel: 'G80',
          drill: 'G81', spotDrill: 'G82', peckDrill: 'G83', chipBreak: 'G73',
          rigidTap: 'G84.2', rigidTapLeft: 'G74.2',
          bore: 'G85', bore2: 'G86',
          absolute: 'G90', incremental: 'G91',
          feedPerMin: 'G94',
          cycleRetract: 'G98',
          cuttingMode: 'G64',
          exactStop: 'G61',
          workOffset: ['G54', 'G55', 'G56', 'G57', 'G58', 'G59'],
          extendedOffset: 'G54.1 P%d',
          safeRetract: 'G53 Z0',

          // High-speed modes
          aicc: 'G05.1 Q1',         // AI Contour Control
          nanoSmoothing: 'G05.1 Q2', // AI Nano Smoothing
          hpcc: 'G05 P10000',        // High Precision Contour Control
          hsmOff: 'G05.1 Q0',
          lookAheadOn: 'G08 P1',
          lookAheadOff: 'G08 P0',
          cornerRoundingOn: 'G62 P1',
          cornerRoundingOff: 'G62 P0'
        },
        mCodes: {
          programStop: 'M0', optionalStop: 'M1', programEnd: 'M2',
          spindleCW: 'M3', spindleCCW: 'M4', spindleStop: 'M5',
          toolChange: 'M6',
          coolantFlood: 'M8', coolantO