const PRISM_LEGAL_NOTICE = {
  version: '1.0.0',

  disclaimer: `
LEGAL DISCLAIMER & TRADEMARK NOTICE

PRISM is an independent machining calculation and post-processing tool developed
independently and is not affiliated with, endorsed by, sponsored by, or in any
way officially connected with any CAM software vendor, machine tool manufacturer,
or tooling company mentioned within this application.

TRADEMARK ACKNOWLEDGMENTS:
• Mastercam® is a registered trademark of CNC Software, LLC
• Fusion 360® and PowerMill® are registered trademarks of Autodesk, Inc.
• SolidCAM® is a registered trademark of SolidCAM Ltd.
• GibbsCAM® is a registered trademark of Cambrio (a Sandvik company)
• ESPRIT® is a registered trademark of Hexagon AB
• hyperMILL® is a registered trademark of OPEN MIND Technologies AG
• CAMWorks® is a registered trademark of HCL Technologies Limited
• HAAS® is a registered trademark of Haas Automation, Inc.
• Mazak® and Mazatrol® are registered trademarks of Yamazaki Mazak Corporation
• FANUC® is a registered trademark of FANUC Corporation
• Siemens® is a registered trademark of Siemens AG
• Heidenhain® is a registered trademark of DR. JOHANNES HEIDENHAIN GmbH
• Okuma® is a registered trademark of Okuma Corporation
• DMG MORI® is a registered trademark of DMG MORI CO., LTD.
• Hurco® is a registered trademark of Hurco Companies, Inc.
• Makino® is a registered trademark of Makino Milling Machine Co., Ltd.
• Sandvik Coromant®, Kennametal®, ISCAR®, Seco Tools®, Walter® are registered
  trademarks of their respective owners.

All other product names, logos, and brands mentioned are property of their
respective owners. All company, product, and service names used are for
identification purposes only. Use of these names, logos, and brands does not
imply endorsement or affiliation.

COMPATIBILITY STATEMENTS:
References to "For [CAM Software] Users" or format compatibility indicate that
PRISM can generate G-code output that follows similar formatting conventions
and can be used alongside toolpaths generated by these software packages. This
does not imply that PRISM is a replacement for, equivalent to, or certified by
any of these software vendors.

DATA SOURCES:
Machine specifications, cutting data, and material properties contained in this
application are compiled from publicly available sources including manufacturer
websites, published specifications, industry handbooks, and peer-reviewed
engineering literature. Users should always verify critical parameters against
official manufacturer documentation.

LIABILITY:
PRISM is provided "as is" without warranty of any kind. The developers are not
responsible for any damages, machine crashes, tool breakage, or injuries resulting
from the use of generated G-code. Users are solely responsible for verifying all
output before running on actual machinery.

© ${new Date().getFullYear()} PRISM Development Team. All rights reserved.
`,

  shortDisclaimer: `PRISM is independent software. All trademarks are property of their respective owners. Not affiliated with any CAM vendor or machine manufacturer.`,

  /**
   * Show full legal disclaimer popup
   */
  showFullDisclaimer() {
    const overlay = document.createElement('div');
    overlay.id = 'legalDisclaimerOverlay';
    overlay.style.cssText = `
      position: fixed; top: 0; left: 0; right: 0; bottom: 0;
      background: rgba(0,0,0,0.9); z-index: 100000;
      display: flex; align-items: center; justify-content: center;
    `;

    overlay.innerHTML = `
      <div style="background: #1a1a2e; border-radius: 12px; max-width: 800px; max-height: 80vh; overflow: auto; padding: 30px; color: #fff; border: 1px solid rgba(255,255,255,0.1);">
        <h2 style="margin: 0 0 20px 0; color: #3498db;">⚖️ Legal Disclaimer</h2>
        <pre style="white-space: pre-wrap; font-family: inherit; font-size: 13px; line-height: 1.6; color: rgba(255,255,255,0.85);">${this.disclaimer}</pre>
        <button onclick="document.getElementById('legalDisclaimerOverlay')?.remove()"
                style="margin-top: 20px; padding: 12px 30px; background: #3498db; color: #fff; border: none; border-radius: 6px; cursor: pointer; font-size: 14px;">
          I Understand
        </button>
      </div>
    `;

    document.body.appendChild(overlay);
  },
  /**
   * Get footer disclaimer HTML
   */
  getFooterHTML() {
    return `
      <div class="legal-footer" style="text-align: center; padding: 15px; font-size: 11px; color: rgba(255,255,255,0.5); border-top: 1px solid rgba(255,255,255,0.1); margin-top: 20px;">
        <p style="margin: 0;">${this.shortDisclaimer}</p>
        <a href="#" onclick="PRISM_LEGAL_NOTICE.showFullDisclaimer(); return false;"
           style="color: #3498db; text-decoration: none;">View Full Legal Notice</a>
      </div>
    `;
  },
  /**
   * Add disclaimer to page footer
   */
  addToFooter() {
    // Find or create footer
    let footer = document.querySelector('footer') || document.querySelector('.app-footer');
    if (!footer) {
      footer = document.createElement('footer');
      footer.className = 'app-footer';
      document.body.appendChild(footer);
    }
    // Add disclaimer if not already present
    if (!footer.querySelector('.legal-footer')) {
      footer.insertAdjacentHTML('beforeend', this.getFooterHTML());
    }
  },
  /**
   * Check if user has acknowledged disclaimer
   */
  hasAcknowledged() {
    return localStorage.getItem('prism_legal_acknowledged') === 'true';
  },
  /**
   * Show first-time disclaimer
   */
  showFirstTimeNotice() {
    if (this.hasAcknowledged()) return;

    const banner = document.createElement('div');
    banner.id = 'legalBanner';
    banner.style.cssText = `
      position: fixed; bottom: 0; left: 0; right: 0;
      background: linear-gradient(135deg, #1a1a2e, #16213e);
      padding: 15px 20px; z-index: 99999;
      display: flex; align-items: center; justify-content: space-between;
      border-top: 2px solid #3498db;
      box-shadow: 0 -5px 20px rgba(0,0,0,0.3);
    `;

    banner.innerHTML = `
      <div style="flex: 1; color: rgba(255,255,255,0.9); font-size: 13px;">
        <strong>⚖️ Legal Notice:</strong> ${this.shortDisclaimer}
        <a href="#" onclick="PRISM_LEGAL_NOTICE.showFullDisclaimer(); return false;"
           style="color: #3498db; margin-left: 10px;">Read Full Disclaimer</a>
      </div>
      <button onclick="PRISM_LEGAL_NOTICE.acknowledge()"
              style="padding: 8px 20px; background: #3498db; color: #fff; border: none; border-radius: 4px; cursor: pointer; margin-left: 20px;">
        I Understand
      </button>
    `;

    document.body.appendChild(banner);
  },
  /**
   * Acknowledge disclaimer
   */
  acknowledge() {
    localStorage.setItem('prism_legal_acknowledged', 'true');
    const banner = document.getElementById('legalBanner');
    if (banner) banner.remove();
  }
}