const PRISM_MFG_STRUCTURES_KB = {
    toolpath: {
        spiral: { name: "spiral", description: "X(t) = rsin(t + k) However, Euler’s method causes the solution to spiral outward, no matter how small h is. After imple­ menting Euler’s method, you should see the single particle spiral outwardly in a 2D space, similar to the image below. 4 Next, implement the Trapezoidal Rule. ", source: "6.837" },
        zigzag: { name: "zigzag", description: ". Your task will be to generate triangles that connect each repetition of the proﬁle curve, as shown in the following image. The basic strategy is to zigzag back and forth between adjacent repetitions to build the triangles. In OpenGL, you are required to specify the vertices in ", source: "6.837" },
        finishing: { name: "finishing", description: "starts by eliminating all the edges of the odd/red nodes (remember that the graph is numbered row by row starting from the bottom left corner). After finishing with the odd nodes, the algorithm continues to eliminate the even nodes until all the edges have been eliminated. A comp", source: "18.086" },
        contour: { name: "contour", description: "n images appear as regions with strong intensity variations. In the case of images obtained with a conventional camera, edges typically represent the contour and/or morphology of the object(s) contained in the field of view (FOV) of the imaging system. From an optics perspective,", source: "18.086" },
        pencil: { name: "pencil", description: "es, which you may never meet. I have never personally met, but it has to be dealt with and there are codes -- I\'ll just mention the code dasil by [? pencil ?] I\'ll finish saying the one word. A model problem here would be some matrix times u prime equal f of u and t, so a sort ", source: "18.086" },
        toolpath: { name: "toolpath", description: "g. 3 • use Mastercam to draw the lathe profile of your paperweight (the top drawing can be done by hand or any software) • use Mastercam to run a toolpath on the profile • prepare for next week\'s lab During Lab II you and your lab mate will: • learn how to use Mastercam Mill • c", source: "2.008-spring-2003" },
        roughing: { name: "roughing", description: "along with the holder dimensions. Parameter screens allow the editing of how the tool is to be used, such as depths of cut and step-over amounts for roughing as well as speed and feed for the tool to use. These are already setup to fairly good values to minimize tool breakage. Pl", source: "2.008-spring-2003" },
    },
    multiaxis: {
        collision: { name: "collision", description: "ith the cloth. You may, for instance, allow the user to click on certain parts of the cloth and drag parts around. • Implement frictionless collisions of cloth with a simple primitive such as a sphere. This is simpler than it may sound at ﬁrst: just check whether a particle is “i", source: "6.837" },
    },
    cutting: {
        material_removal_rate: { name: "material removal rate", description: "a rough estimate. The speciﬁc cutting energy of 4140 is 3.35J/mm 3 . When the machine stalled, the spindle was 540rpm, and t0 = 0.027. Therefore, the material removal rate was M RR = (540 ∗ π ∗ 3) ∗ 0.027 ∗ 0.075 = 10.3008 in3 /min. Since the machine stalled, the power of the mac", source: "2.008-spring-2003" },
        feed_rate: { name: "feed rate", description: "Meaning Address Meaning O program number F feed rate N sequence number E thread lead G preparatory function S spindle speed X, Y, Z coordinate axis motion T tool number R arc/corner radius, or rapid plane M misc./machine functions I absolute center of arc in x-axis J absolute cen", source: "2.008-spring-2003" },
        spindle_speed: { name: "spindle speed", description: "d Z-axes to a predetermined clearance point for changing tools. N1M26T11S2000 Install tool T11 (1.5\" end mill) for facing top surface, spindle speed 2000RPM Rapid positioning mode, designate work coordinate system 1, multi-quadrant circle N2G0G55G75G90X-2.0Y-1.3 mode, absolute p", source: "2.008-spring-2003" },
        tool_life: { name: "tool life", description: "Figure 3: Turned Flange The way that this problem is currently stated makes it really quite diﬃcult. The Taylor equation gives tool life for a speciﬁc speed. However, by ﬁxing ω, the speed changes throughout the turning process, and so the rate of wear changes. One compromise (ap", source: "2.008-spring-2003" },
        taylor_equation: { name: "taylor equation", description: "Figure 3: Turned Flange The way that this problem is currently stated makes it really quite diﬃcult. The Taylor equation gives tool life for a speciﬁc speed. However, by ﬁxing ω, the speed changes throughout the turning process, and so the rate of wear changes. One compromise (ap", source: "2.008-spring-2003" },
    },
}